### ISSUE TITLE
Different p values for two functions

### ISSUE THREAD

**Issue by lucavd** [ddsjoberg/gtsummary#1006]
Hi Daniel, thank you for your wonderful package.

Maybe I don't understand the underlying theory, but is it intended that the `add_p() `and `add_difference() `functions give two similar but different p-values for the same variable?

Thank you

**Comment by ddsjoberg** [comment]
Hi @lucavd 
You'll need to give an example. There are different default methods for the functions, and the method is indicated in the footnote.

**Comment by lucavd** [comment]
You are right. `add_p()` uses the Wilcoxon rank sum test as default, while `add_difference` uses Welch t-test.
Sorry for the naive question
