### ISSUE TITLE
Feature request: Compute p-values and add add_significance_stars() functionality to objects of class svyolr

### ISSUE THREAD

**Issue by gjones1219** [ddsjoberg/gtsummary#1014]
Do not use this form to ask a question, or ask for assistance. Instead, ask on <https://stackoverflow.com/> using the gtsummary tag.
Questions about a function's use will be closed without a response.

**Is your feature request related to a problem? Please describe.**

Currently, you cannot add significance stars when you insert an object of class "svyolr" (ordinal logistic regression) into tbl_regression, as the initial model output does not provide p-values (only t-values)

**Describe the solution you'd like**

I would like you all to add this functionality to tbl_regression, so that when you input an object of class "svyolr", tbl_regression can a. automatically computes p-values for this object class and b. convert those p-values into significance stars within a column containing the estimate and the confidence interval.

**Describe alternatives you've considered**

I have tried to create a new object containing p-values for the svyolr object using the "coeftest" function from the lmtest package, and then inputting that object into the tbl_regression function, to no avail. 

**Additional context**

Look forward to being in touch about this. Thank you.

**Comment by ddsjoberg** [comment]
@gjones1219 does the suggestion from @larmarange solve your issue? (Thanks @larmarange !)

**Comment by gjones1219** [comment]
Hi Daniel and Joseph,

Thanks for the suggestion; however, this doesn't work (also, the
svyclm function takes a prohibitively long time [~25-50 minutes] to run a
fairly simple model). However, when I input the model into the
tbl_regression function, I got the following error:

"x Unable to identify the list of variables.

  This is usually due to an error calling `stats::model.frame(x)`or
`stats::model.matrix(x)`.
  It could be the case if that type of model does not implement these
methods.
  Rarely, this error may occur if the model object was created within
  a functional programming framework (e.g. using `lappy()`, `purrr::map()`,
etc.).
Error: Cannot identify variables. Quitting execution."

Please advise! I would really love to be able to report the p-values of
these models in the tables that I report. Any suggestions/work arounds you
have or any package tweaks you could make would be seriously appreciated.
Thank you!

Best,
Grant

**Comment by ddsjoberg** [comment]
Hey @gjones1219 ,

If that isn't going to work for you, then I *think* your best bet is to write a custom tidier; that is, write a short function that wraps the `broom::tidy()` and adds a column for the p-values (the p-value column must be called `p.value`). You can then pass your model with `tbl_regression(mod, tidy_fun = grants_tidy)` and you should get a table with the p-values. 

If you run into issues, give us an example we can run on our machines that is, 1. As minimal and short as possible, 2. Also provide code how you calculate the p-values.

**Comment by gjones1219** [comment]
Hi Daniel,

Again, there are issues with this. When I try to wrap broom::tidy, I get
the following warning

Warning message:
Data frame tidiers are deprecated and will be removed in an upcoming
release of broom.

Thus, I think tidiers are going to be removed from broom? Do you have any
further suggestions here?

Also, since I am relatively new-ish at some elements of coding, some of the
things you would like (i.e. making minimally reproducible code from
intricate code like mine) I am not clear on. Trying my best to explain my
issues, but also not totally sure what you mean sometimes! Let me know also
if it would be easier to hop on zoom ever.

Thank you,
Grant

**Comment by ddsjoberg** [comment]
Can you provide an example that I can run on my machine and give the code you use to calculate the pvalues? Please make the example and simple and short as possible.

**Comment by gjones1219** [comment]
I figured it out! attaching code here

Grant

**Comment by ddsjoberg** [comment]
Can you post the code as a comment here for future prosperity? The attachments don't come through on github.

**Comment by gjones1219** [comment]
library(survey)
library(gtsummary)

# Load example data
data(api)

# Create a survey design object
dclus1 <- svydesign(id=~dnum, weights=~pw, data=apiclus1, fpc=~fpc)

# Add an ordinal variable to the data
dclus1 <- update(dclus1, mealcat=cut(meals,c(0,25,50,75,100)))

# Fit an ordinal regression model
m <- svyolr(formula = mealcat ~ avg.ed + stype,
            design = dclus1)

#make p-value table
summary_table_m<- coef(summary(m))
pval <- pnorm(abs(summary_table_m[, "t value"]),lower.tail = FALSE)* 2
MwithP.values <- cbind(summary_table_m, "p.value" = round(pval,3))

#try to turn into a tidy object
MwithP.values<- broom::tidy(MwithP.values)
  #get error: 'tidy.numeric' is deprecated


ErrorTablewithMmodel <-
  tbl_regression(
    m,
    exponentiate = TRUE,  include = c(
      "avg.ed", "stype"
    ))  %>%  modify_table_body(
      mutate,
      est_ci =
        dplyr::case_when(
          p.value < 0.001 ~ stringr::str_glue("{style_sigfig(estimate)}***
({ci})"),
          p.value < 0.01 ~ stringr::str_glue("{style_sigfig(estimate)}**
({ci})"),
          p.value < 0.05 ~ stringr::str_glue("{style_sigfig(estimate)}*
({ci})"),
          !is.na(estimate) ~ stringr::str_glue("{style_sigfig(estimate)}
({ci})")
        )) %>%
  # add column header for new column
  modify_header(est_ci ~ "**aOR (95% CI)**") %>%
  # hide columns no longer needed
  modify_column_hide(column = c(estimate, ci, p.value)) %>%
  # add footnote about p-value stars
  modify_footnote(est_ci ~ "aOR = adjusted odds ratio; CI = confidence
interval; * p<0.05; ** p<0.01; *** p<0.001") %>%
  modify_table_header(column = label, label = c("**Lifetime Use**"))
    #get error: x obkect 'p.value' is not found

**Comment by gjones1219** [comment]
Hello,

I am wondering why you closed this issue?

Grant

**Comment by ddsjoberg** [comment]
Oh, I thought you solved it :) What more do we need to do here?

**Comment by gjones1219** [comment]
Oh, so sorry! My email was totally unclear lol. I figured out a minimally
reproducible example to send you, definitely have not figured out how to
get p-values in gtsummary or through the tidy package. Your help would be
immensely appreciated!

Grant

**Comment by ddsjoberg** [comment]
No worries...i think the example below will get you what you need. I incorporated the code you sent into a custom tidier that returns the p-value. Note that the statistic returned looks like the T statistic, but you're assuming normality or a Z statistic in the p-value calculation...likely similar in most situations, but not 100% accurate.


``` r
library(survey)
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.5.0'
data(api)

# Create a survey design object
dclus1 <- svydesign(id=~dnum, weights=~pw, data=apiclus1, fpc=~fpc)
# Add an ordinal variable to the data
dclus1 <- update(dclus1, mealcat=cut(meals,c(0,25,50,75,100)))
# Fit an ordinal regression model
m <- svyolr(formula = mealcat ~ avg.ed + stype,
            design = dclus1)


grants_tidy <- function(x, ...) {
  broom::tidy(x, ...) %>%
    dplyr::mutate(
      p.value =
        pnorm(abs(statistic), lower.tail = FALSE) * 2
    )
}

tbl <-
  tbl_regression(
    m,
    exponentiate = TRUE,  
    include = c(avg.ed, stype),
    tidy_fun = grants_tidy
  ) %>%
  add_significance_stars(hide_ci = FALSE, hide_p = FALSE)
```
![image](https://user-images.githubusercontent.com/26774684/139562600-f97402ed-a8da-469d-8e55-59004def7b9b.png)

<sup>Created on 2021-10-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gjones1219** [comment]
Daniel!! This works perfectly! You are actually a saint -- thank you so
much!

Also, please let me know if you have a venmo or somewhere I can donate. You
have been so immensely helpful to me over the course of the past while, it
really would be the least I could do!

Grant

**Comment by ddsjoberg** [comment]
lol no one has asked before, but it's @dansjoberg . Happy Programming! Glad it worked for you

**Comment by gjones1219** [comment]
I can't believe that! You are seriously too helpful. Just sent you some
money! Thanks again, and hope to be in touch -- you seem like you have a
wealth of statistical knowledge, so if there is any way I can ever learn
from you more in depth please let me know! Would love to connect.

Grant

**Comment by ddsjoberg** [comment]
add me on twitter!
https://twitter.com/statistishdan

**Comment by gjones1219** [comment]
I'm not on twitter/any social media unfortunately but let me know if there
are other avenues, thanks!

Grant
