### ISSUE TITLE
Feature request: <Add a custom function for column header count>

### ISSUE THREAD

**Issue by shengchaohou** [ddsjoberg/gtsummary#1021]
I tried to generate a table using tbl_summary, but I could not set the right total number N in the column header. I think the total number works fine if each row is unique or if I want the denominator is the total (or non-missing) row number of whole data. But sometimes there's need to customize the denominator for each group because I want to calculate the percentage of a stratified population instead of the whole dataset. 

**Describe the solution you'd like**
I would like a customizable total number for column header. Non-missing total is a good start but more customizable function is desired.

**Comment by ddsjoberg** [comment]
@shengchaohou thanks for the post

Can you give an example creating a table where you hard code the statistics into the header that you want to report? I'm not sure what stratifying Ns you're referring to

**Comment by shengchaohou** [comment]
For instance, I have a table which has 5 rows and 3 columns, where each row represents an event. 

columns:
  SUBJID: Subject ID
  GROUP: Group ID that subject in
  CAT1: category of the event.

And I am trying to generate a table that shows among each group, what is the number of the event in each category and percentage. But I want to use unique subject in each group as denominator. 

`
library(dplyr)
library(gtsummary)

table <- tibble(SUBJID = c(1, 1, 2, 3, 4),
               GROUP = c("G1", "G1", "G1", "G2", "G3"),
               CAT1 = c("A", "B", "C", "A", "B"))

summary <- table %>%
  select(-SUBJID) %>%
  tbl_summary(by = GROUP)

`

By using the code above, the N for G1 will be 3, where what I really want is 2 because there are two unique subjects in Group 1.

**Comment by ddsjoberg** [comment]
Does this work for you?

``` r
library(dplyr)
library(gtsummary)
#> #BlackLivesMatter

table <- tibble(SUBJID = c(1, 1, 2, 3, 4),
                GROUP = c("G1", "G1", "G1", "G2", "G3"),
                CAT1 = c("A", "B", "C", "A", "B"))

summary <- 
  table %>%
  group_by(SUBJID) %>%
  mutate(first_id = row_number() == 1, .before = 1) %>%
  ungroup() %>%
  select(-SUBJID) %>%
  tbl_summary(
    by = GROUP,
    statistic = first_id ~ "{n}",
    label = first_id ~ "No. of Subjects"
  ) %>%
  as_kable() # convert to kable to display on GitHub
```

<sup>Created on 2021-11-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by shengchaohou** [comment]
Hi @ddsjoberg,

Thanks for the solution. However, your solution does not change the percentage of the cell, since the denominator was still 3.

**Comment by ddsjoberg** [comment]
@shengchaohou what denom do you want to be 2? In CAT1?

**Comment by shengchaohou** [comment]
@ddsjoberg 

Yes, I want to present that in Group G1, how many subject has event of category A and what is the percentage. The denom would be the count of unique subjects in G1 instead of the total number of events in G1.

**Comment by ddsjoberg** [comment]
@shengchaohou can you update your example to include the table you want to see in the end?

**Comment by shengchaohou** [comment]
@ddsjoberg 

Sure. The table below is how I wanted it to be. 

Characteristic | G1, N = 2 | G2, N = 1 | G3, N = 1
-- | -- | -- | --
CAT1 |   |   |  
A | 1 (50%) | 1 (100%) | 0 (0%)
B | 1 (50%) | 0 (0%) | 1 (100%)
C | 1 (50%) | 0 (0%) | 0 (0%)

**Comment by ddsjoberg** [comment]
Hmmmm, I am not sure this is something we'll update to support. The first column looks incorrect with the column percentages summing to 150%. Essentially what you want is for the n reported to the the raw counts, but you want the denominator to come from another clustering column. We depend heavily throughout the package on the link between N and the percent saved in `tbl_summary()`.

**Comment by shengchaohou** [comment]
I totally understand. Thank you very much for the clarification. Other than this minor thing I think your package is very useful. Thanks again.

**Comment by ddsjoberg** [comment]
There is a new function that allows you to create HIGHLY customized summaries within the gtsummary context. You may be able to use this fn to get what you need
http://www.danieldsjoberg.com/gtsummary/reference/tbl_custom_summary.html
