### ISSUE TITLE
Feature request: An `add_p.tbl_continuous` method for summarizing a continuous variable

### ISSUE THREAD

**Issue by karissawhiting** [ddsjoberg/gtsummary#1023]
**Is your feature request related to a problem? Please describe.**
I often want to summarize and compare a given continuous variable (e.g. a biomarker) across a set of other variables. `tbl_continuous()` gives me a beautiful summary. It would be great to also have a statistical comparison readily available. 

**Describe the solution you'd like**
I think an `add_p()` method available for this class would be great. Wilcoxan rank sum seems a natural default test when there are two groups to compare, and perhaps kruskal-wallis could be used for more groups.

**Describe alternatives you've considered**
A custom function worked previously when `tbl_continuous()` was still of class `tbl_summary` but it no longer works now that it is its own class (although I totally could be coding this wrong):

``` r
library(gtsummary)
library(tidyverse)

add_p_test_kruskal2 <- function(data, variable, by, tbl, ...) {
  
  sum_var <- tbl$inputs$variable
  
  stats::kruskal.test(data[[sum_var]], as.factor(data[[variable]])) %>%
    broom::tidy() %>% select(p.value)
  
}

trial %>%
  select(age, response, grade) %>%
  tbl_continuous(variable = age) %>% 
  add_stat(fns = everything() ~ add_p_test_kruskal2) 

#> Error: Argument `x=` must be of class 'tbl_summary' or 'tbl_svysummary'
```
<sup>Created on 2021-11-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Even when it worked, I was a bit confused by the fact that `variable` means a different thing in the `tbl_continuous` context.

(side note: it would also be cool to easily compare continuous by a bunch of other continuous, but not sure if there is a natural default way to display this, and it may be outside the scope of summary tables anyway)

Thank you!!

**Comment by ddsjoberg** [comment]
Thanks @karissawhiting ! We def need to add this. 
 
> I was a bit confused by the fact that `"variable"` means a different thing in the `tbl_continuous()` context.

I am afraid this may need to persist. All the `add_p()` methods share a common infrastructure....we'll see when we get to it. 

>  it would also be cool to easily compare continuous by a bunch of other continuous

I am not sure what you mean here. do you want to open another issue with an example of the output you are looking for?

**Comment by ddsjoberg** [comment]
A few notes...

- All methods for continuous variables available in `add_p.tbl_summary()` are applicable for `tbl_continuous()` tables when the `by=` variable is NULL.
- To easily add these methods, we'll need to write a wrappers for each test that correctly applies the variables names (i.e. need to switch the `by` and `variable`, and the continuous variable name will need to be extracted from `tbl$inputs$variable`
- It will be best if the names of the tests can remain the same. When we subset the internal data frame with all the tests, we'll need to double check that the subsetting first occurs on the methods acceptable for `tbl_continuous()`.

**Comment by karissawhiting** [comment]
> 
> I am not sure what you mean here. do you want to open another issue with an example of the output you are looking for?

I was thinking like a correlation statistic with p-value or something that could easily summarize the relationship between two continuous variables along side continuous-categorical in `tbl_continuous()`:
```r
trial %>%
  select(age, ttdeath, trt) %>%
  tbl_continuous(variable = age, 
                 type = ttdeath ~ "continuous") %>% 
  add_p()
```

but upon further thought I think this is outside the scope of this function and there isn't really a natural way to display this in a summary table, so I rescind for now :) 

Thanks, as always for the prompt responses!

**Comment by kwakuduahc1** [comment]
> I am not sure what you mean here. do you want to open another issue with an example of the output you are looking for?

I saw this feature today and I find it very exciting. For 2 continuous variables, a Pearson or Spearman could be reported depending on the distribution. The Spearman could be reported by default for the user to select Pearson if wanted.
