### ISSUE TITLE
Feature request: Report rates per 1000 people

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#1029]
This SO post asked about reporting scaled rates. seems like a reasonable request. Perhaps it's easy with @larmarange `tbl_custom_summary()`? Need to look into further.

https://stackoverflow.com/questions/69956495/

**Comment by larmarange** [comment]
Hmm, something like

``` r
library(gtsummary)

t1 <- trial %>%
  tbl_custom_summary(
    include = NULL,
    by = stage,
    stat_fns = ~ proportion_summary("response", 1),
    statistic = ~ "{prop} ({conf.low}-{conf.high})",
    digits = ~ scales::label_number(scale = 10000, accuracy = .1),
    overall_row = TRUE,
    overall_row_label = "response"
  )

t2 <- trial %>%
  tbl_custom_summary(
    include = NULL,
    by = stage,
    stat_fns = ~ proportion_summary("death", 1),
    statistic = ~ "{prop} ({conf.low}-{conf.high})",
    digits = ~ scales::label_number(scale = 10000, accuracy = .1),
    overall_row = TRUE,
    overall_row_label = "death"
  )


tbl_stack(list(t1, t2)) %>%
  as_kable()
```

| **Characteristic** | **T1**, N = 53            | **T2**, N = 54            | **T3**, N = 43            | **T4**, N = 50            |
|:-------------------|:--------------------------|:--------------------------|:--------------------------|:--------------------------|
| response           | 3 461.5 (2 233.4-4 916.5) | 2 500.0 (1 447.5-3 923.3) | 3 750.0 (2 317.4-5 419.0) | 3 061.2 (1 867.9-4 557.8) |
| death              | 4 528.3 (3 180.2-5 944.5) | 5 000.0 (3 711.5-6 288.5) | 5 116.3 (3 568.1-6 643.9) | 7 800.0 (6 366.9-8 800.6) |

<sup>Created on 2021-11-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by larmarange** [comment]
PS: you should check https://www.danieldsjoberg.com/gtsummary/reference/index.html  I do not find tbl_custom_summary

**Comment by larmarange** [comment]
Note : to report a proportion per 10000, simply use `scales::label_number()`

**Comment by larmarange** [comment]
``` r
library(gtsummary)

trial %>%
  select(response, death, trt) %>%
  tbl_summary(
    by = trt, missing = "no", statistic = everything() ~ "{p}%",
    digits = ~ scales::label_number(scale = 10000)
  ) %>%
  add_ci(
    method = everything() ~ "wilson",
    style_fun = ~ scales::label_number(scale = 10000)
  ) %>%
  modify_cols_merge("{stat_1} ({ci_stat_1})") %>%
  modify_cols_merge("{stat_2} ({ci_stat_2})") %>%
  as_kable() # convert to kable to display on SO
```

| **Characteristic** | **Drug A**, N = 98      | **Drug B**, N = 102     |
|:-------------------|:------------------------|:------------------------|
| Tumor Response     | 2 947% (2 079%, 3 984%) | 3 367% (2 463%, 4 401%) |
| Patient Died       | 5 306% (4 276%, 6 312%) | 5 882% (4 863%, 6 834%) |

<sup>Created on 2021-11-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
omg of course! just update the formatting function!

**Comment by larmarange** [comment]
It could be worth to add a `cols_merge` option in `add_ci()`

modify_cols_merge is quite of advance usage

**Comment by larmarange** [comment]
Hi

Currently on annual leave until January 10.

If urgent, I cannot review it, otherwise in January

Best regards

Joseph Larmarange

Le mar. 28 déc. 2021 à 20:33, Daniel Sjoberg ***@***.***> a
écrit :

**Comment by ddsjoberg** [comment]
@larmarange enjoy your vacation!

No rush, when you return is great. I'll try to get gtsummary in a place where we can make broom.helpers and gtsummary releases in the new year. sound good?
