### ISSUE TITLE
{gtsummary} example table size in README & pkgdown site

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#103]
I shrunk the size of the example table images in the README with this code:

```
![](man/figures/README-tbl_summary.png){ width=65% }
```

This works great when the images are rendered on the pkgdown site.  But when the README is displayed on the GitHub landing page, the tables are shown at 100% width.  When the *.Rmd is rendered to *.md the width argument disappears.
```
![](man/figures/README-tbl_summary.png)
```

Is there a way to make this work on GitHub and the pkgdown site.

**Comment by karissawhiting** [comment]
It looks like it is not possible at the moment to retain image size specifications when rendering github docs from .Rmd, see:  https://github.com/yihui/knitr/issues/1670

**Comment by ddsjoberg** [comment]
That is great to know!

I guess we can keep these as they are!

**Comment by karissawhiting** [comment]
As discussed, you can try replacing .rmd image code with html code in README.Rmd, e.g.  <img src="man/figures/table_image.png" width="800px">

**Comment by ddsjoberg** [comment]
Worked like a charm!
#117
