### ISSUE TITLE
Feature request: Adding missing = to tbl_continuous

### ISSUE THREAD

**Issue by Stephonomon** [ddsjoberg/gtsummary#1032]
**Is your feature request related to a problem? Please describe.**
When using tbl_merge between tbl_summary and tbl_continuous, if i use missing =, those missing rows still show up because tbl_continuous cannot ignore them.

**Comment by ddsjoberg** [comment]
hello @Stephonomon ! thanks for the post. can you use a reproducible example to show me what results you're getting, and provide a mock-up of the table you'd like to see?

**Comment by ddsjoberg** [comment]
Hello! I'm going to close this for now. But feel free to reopen when you add the mock-up of the table
