### ISSUE TITLE
`tbl_continous()` and `add_overall()`

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#1037]
It seems that `add_overall()` is not working for `tbl_continuous()` while it could be used with `tbl_custom_summary()`.

``` r
library(gtsummary)

tbl1 <- trial %>%
  tbl_continuous(
    variable = "age",
    include = c("grade", "stage"),
    by = "trt",
    statistic = ~ "{mean}"
  )

tbl1 %>% as_kable()
```

| **Characteristic** | **Drug A**, N = 98 | **Drug B**, N = 102 |
|:-------------------|:-------------------|:--------------------|
| Grade              |                    |                     |
| I                  | 46                 | 46                  |
| II                 | 45                 | 50                  |
| III                | 51                 | 46                  |
| T Stage            |                    |                     |
| T1                 | 44                 | 50                  |
| T2                 | 50                 | 46                  |
| T3                 | 49                 | 50                  |
| T4                 | 45                 | 44                  |

``` r
tbl1 %>% add_overall() %>% as_kable()
#> Error in (function (data, by = NULL, label = NULL, stat_fns, statistic, : argument inutilisé (variable = "age")

tbl2 <- trial %>%
  tbl_custom_summary(
    include = c("grade", "stage"),
    by = "trt",
    stat_fns = ~ continuous_summary("age"),
    statistic = ~ "{mean}"
  )

tbl2 %>% as_kable()
```

| **Characteristic** | **Drug A**, N = 98 | **Drug B**, N = 102 |
|:-------------------|:-------------------|:--------------------|
| Grade              |                    |                     |
| I                  | 46                 | 46                  |
| II                 | 45                 | 50                  |
| III                | 51                 | 46                  |
| T Stage            |                    |                     |
| T1                 | 44                 | 50                  |
| T2                 | 50                 | 46                  |
| T3                 | 49                 | 50                  |
| T4                 | 45                 | 44                  |

``` r
tbl2 %>% add_overall() %>% as_kable()
```

| **Characteristic** | **Overall**, N = 200 | **Drug A**, N = 98 | **Drug B**, N = 102 |
|:-------------------|:---------------------|:-------------------|:--------------------|
| Grade              |                      |                    |                     |
| I                  | 46                   | 46                 | 46                  |
| II                 | 48                   | 45                 | 50                  |
| III                | 48                   | 51                 | 46                  |
| T Stage            |                      |                    |                     |
| T1                 | 47                   | 44                 | 50                  |
| T2                 | 48                   | 50                 | 46                  |
| T3                 | 49                   | 49                 | 50                  |
| T4                 | 45                   | 45                 | 44                  |

<sup>Created on 2021-11-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
Thanks @larmarange ! Are you using the released version of the dev version?

In the dev version, I updated the class to be `c("tbl_continuous", "gtsummary")`...maybe that is having an effect on the output.

**Comment by larmarange** [comment]
Just checked with dev version.

```
Error in UseMethod("add_overall") : 
  no applicable method for 'add_overall' applied to an object of class "c('tbl_continuous', 'gtsummary')"
```
