### ISSUE TITLE
Would flextable be relavant for PDF output?

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#1045]
Following #579 would it be relevant to consider flextable as a default output for PDF documents?

**Comment by larmarange** [comment]
If strong PDF support is arriving in `gt`, it is therefore relevant to wait for it. I agree.

**Comment by ddsjoberg** [comment]
I spoke with the gt maintainer a while back about this, and he thought it could be released as early as the first half of 2021. So I hope it arrives soon. It'll be a super helpful addition!
