### ISSUE TITLE
{gtsummary} - add option to sort variables by p-value

### ISSUE THREAD

**Issue by karissawhiting** [ddsjoberg/gtsummary#105]
Have an option in tbl_summary() to arrange table variables by  p-value, smallest to largest.

**Comment by ddsjoberg** [comment]
I think you'd need to add this option to `add_comparison`, and the sort could execute after the p-value are calculated

**Comment by ddsjoberg** [comment]
@karissawhiting should this be a separate function?  It could sort `tbl_summary`, `tbl_uvregression`, or `tbl_regression` ?  What do you think?

**Comment by karissawhiting** [comment]
Yes, I think a separate function makes sense. How about `tab_style_sort_p()`?

**Comment by ddsjoberg** [comment]
Sounds great
