### ISSUE TITLE
Bug Report: translation of statistical tests does not work when `separate_p_footnotes()` is used

### ISSUE THREAD

**Issue by palantre** [ddsjoberg/gtsummary#1055]
I've observed that the translation into Spanish of statistical test used by `add_p()` does not work if I also use `separate_p_footnotes()`.

EXAMPLE:

```r
library(tidyverse)
library(gtsummary)

#dummy dataset
Edad <- rnorm(500, 50, 10)
Sexo = sample(c("M", "F", NA_character_), 500, replace = TRUE)
Tratamiento = sample(c("Sí", "No", NA_character_), 500, replace = TRUE)
ensayo <- data.frame(Edad, Sexo, Tratamiento, stringsAsFactors = TRUE)

#Change language to Spanish
set_gtsummary_theme(theme_gtsummary_language("es"))

#table in Spanish
ensayo %>%
      select(Edad, Sexo, Tratamiento) %>%
      tbl_summary(by = Tratamiento) %>%
      add_p() 
```
![Rplot](https://user-images.githubusercontent.com/31016510/145710464-0d4cce13-28c6-44f2-a427-9afb94678345.png)

The above example works OK. Both footnotes are in Spanish.

```r
#table in Spanish with separated footnotes
ensayo %>%
      select(Edad, Sexo, Tratamiento) %>%
      tbl_summary(by = Tratamiento) %>%
      add_p()  %>%
      separate_p_footnotes()
```
![Rplot01](https://user-images.githubusercontent.com/31016510/145710499-8954bbb2-b6eb-4fd4-af2a-ce0eaf8f5abe.png)

Now, just the first footnote is translated, but the other two, that refer to statistical test used for p values, are in English.

The problem is reproducible also in other languages (I've tried with French)

**Comment by ddsjoberg** [comment]
@palantre thank you for reporting! Fox has been merged!

**Comment by palantre** [comment]
This bug is present again in gtsummary 2.5 and R version 4.5.2.

**Reproducible example:**

Using separate_p_footnotes(), the "Kruskal-Wallis rank sum test" is not translated into Spanish.

```
mtcars %>%
      tbl_summary(
        by = cyl,
        include = c(mpg, disp, hp)
    ) %>%
      add_overall() %>%
      add_p() %>%
      separate_p_footnotes()
```

<img width="1271" height="606" alt="Image" src="https://github.com/user-attachments/assets/413bf932-f401-4671-a283-3210e493ef99" />

If separate_p_footnotes() is not used, the footnote is properly translated as "test de Kruskall-Wallis".

```
mtcars %>%
      tbl_summary(
        by = cyl,
        include = c(mpg, disp, hp)
    ) %>%
      add_overall() %>%
      add_p() 
```

<img width="1269" height="198" alt="Image" src="https://github.com/user-attachments/assets/61c66c7a-0d6c-48bd-be08-cde0099fb457" />
