### ISSUE TITLE
Merge two or more gtsummary objects : problem ?

### ISSUE THREAD

**Issue by hass91** [ddsjoberg/gtsummary#1057]
Do not use this form to ask a question, or ask for assistance. Instead, ask on <https://stackoverflow.com/> using the gtsummary tag.
Questions about a function's use will be closed without a response.

If you have found a bug, please briefly describe your problem and what output you expect.

INCLUDE a *minimal* reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>. It'll take minutes to master creating a reprex.
ISSUES WITHOUT A REPRODUCIBLE EXAMPLE WILL LIKELY BE CLOSED WITHOUT A RESPONSE.

---

Dear,

By wanting to reproduce one of your examples, I got the error message below:

```r
# Example 2 ----------------------------------
# Descriptive statistics alongside univariate regression, with no spanning header

t3 <- trial[c("age", "grade", "response")] %>%
  tbl_summary(missing = "no",
              type = list(where(is.numeric) ~ "continuous2")) %>%
  add_n() %>%
  modify_header(stat_0 ~ "**Summary Statistics**")

t4 <- tbl_uvregression(
    trial[c("ttdeath", "death", "age", "grade", "response")],
    method = coxph,
    y = Surv(ttdeath, death),
    exponentiate = TRUE,
    hide_n = TRUE
  )

tbl_merge_ex2 <-
  tbl_merge(tbls = list(t3, t4)) %>%
  modify_spanning_header(everything() ~ NA)

tbl_merge_ex2

Error: Problem with `mutate()` column `row_numbers`.
i `row_numbers = `%>%`(...)`.
x operations are possible only for numeric, logical or complex types
i The error occurred in row 1.
Run `rlang::last_error()` to see where the error occurred.

```
Thank you in advance for your assistance !

**Comment by ddsjoberg** [comment]
dear @hass91 ,

1. Close all R sessions on your machine.
2. Open a single R or RStudio session.
3. Install the most recent version of gtsummary.
4. Try your code again. If you see an error, then you'll need to put your code in a proper reprex (described above) and add update your post with the results.

**Comment by ddsjoberg** [comment]
Thank you for the bug report. I"ll investigate and update as needed~

**Comment by ddsjoberg** [comment]
Dear @hass91 , Thank you again for letting me know about this bug. 

I have an open pull request that addresses the issue and it will be merged into the code base soon.

**Comment by hass91** [comment]
Dear @ddsjoberg, 

Thank you very much for this great job !

**Comment by ddsjoberg** [comment]
Thank YOU @hass91 for letting me know about the issue! Much appreciated!
