### ISSUE TITLE
Should we support dates in tbl_summary?

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#106]
@karissawhiting @zabore @margarethannum @michaelcurry1123 

What do you think?  Should we make an effort to report some kind of summary when date variables are passed? Currently, the function returns an error that the type isn't supported.  If we choose not to support dates, should we update to ignore dates rather than stop the function with an error?  We could simply print a message that the unsupported types were ignored?

**Comment by zabore** [comment]
I don't see when a summary of dates would make sense, so my vote is not to support it. I like the idea of excluding dates and continuing to run with a message rather than stopping completely with an error, though.

**Comment by michaelcurry1123** [comment]
I think understanding the date range (Min/Max) is important, but I often only look at dates to make sure I identified the correct cohort/ specific treatments started at a certain time. I don't really report them out to investigators. I think a warning message would be good instead of an error.

**Comment by karissawhiting** [comment]
I third this! I think a warning (not error) would be sufficient.

**Comment by ddsjoberg** [comment]
Great, thanks for the input.  I agree you all too!!

**Comment by ddsjoberg** [comment]
#107

**Comment by ercbk** [comment]
Just to add a use case. I think I'm going to use this function to help create a data dictionary. A date range (Min/Max) would be nice.

**Comment by ddsjoberg** [comment]
@ercbk FYI this is being added in https://github.com/ddsjoberg/gtsummary/pull/794
