### ISSUE TITLE
mice multinom tbl_regression lacks group variable

### ISSUE THREAD

**Issue by uakimix** [ddsjoberg/gtsummary#1065]
When using `tbl_regression` with a `mice` model, the generated table does not have the grouping variable. When viewing the table_body it is clear that is does not have a `groupname_col`, whereas the table generated by the missing data (not using mice) does. 

``` r
library(mice)
#> 
#> Attaching package: 'mice'
#> The following object is masked from 'package:stats':
#> 
#>     filter
#> The following objects are masked from 'package:base':
#> 
#>     cbind, rbind
library(nnet)
library(gtsummary)
#> Warning: package 'gtsummary' was built under R version 4.0.5

model <- multinom(age ~ bmi + chl, trace = F, data = nhanes)

imp <- mice(nhanes2, m = 2, print = FALSE, seed = 22112)
mice_model <- with(imp, multinom(age ~ bmi + chl, trace = F))

tbl_regression(model)
#> ℹ Multinomial models have a different underlying structure than the models
#> gtsummary was designed for. Other gtsummary functions designed to work with
#> tbl_regression objects may yield unexpected results.
```

<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>log(OR)</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <td colspan="4" class="gt_group_heading">2</td>
    </tr>
    <tr><td class="gt_row gt_left">bmi</td>
<td class="gt_row gt_center">-5.3</td>
<td class="gt_row gt_center">-9.8, -0.85</td>
<td class="gt_row gt_center">0.020</td></tr>
    <tr><td class="gt_row gt_left">chl</td>
<td class="gt_row gt_center">0.60</td>
<td class="gt_row gt_center">-0.04, 1.2</td>
<td class="gt_row gt_center">0.068</td></tr>
    <tr class="gt_group_heading_row">
      <td colspan="4" class="gt_group_heading">3</td>
    </tr>
    <tr><td class="gt_row gt_left">bmi</td>
<td class="gt_row gt_center">-5.6</td>
<td class="gt_row gt_center">-9.9, -1.2</td>
<td class="gt_row gt_center">0.012</td></tr>
    <tr><td class="gt_row gt_left">chl</td>
<td class="gt_row gt_center">0.65</td>
<td class="gt_row gt_center">-0.01, 1.3</td>
<td class="gt_row gt_center">0.052</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          OR = Odds Ratio, CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>

``` r
tbl_regression(mice_model)
```
#> pool_and_tidy_mice(): Tidying mice model with
#> `mice::pool(x) %>% mice::tidy(exponentiate = FALSE, conf.int = TRUE, conf.level = 0.95)`
<div id="vpudntczum" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>log(OR)</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">bmi</td>
<td class="gt_row gt_center">-0.58</td>
<td class="gt_row gt_center">-1.2, 0.02</td>
<td class="gt_row gt_center">0.058</td></tr>
    <tr><td class="gt_row gt_left">chl</td>
<td class="gt_row gt_center">0.06</td>
<td class="gt_row gt_center">-0.01, 0.13</td>
<td class="gt_row gt_center">0.10</td></tr>
    <tr><td class="gt_row gt_left">bmi</td>
<td class="gt_row gt_center">-0.60</td>
<td class="gt_row gt_center">-1.2, 0.03</td>
<td class="gt_row gt_center">0.059</td></tr>
    <tr><td class="gt_row gt_left">chl</td>
<td class="gt_row gt_center">0.08</td>
<td class="gt_row gt_center">-0.02, 0.19</td>
<td class="gt_row gt_center">0.086</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          OR = Odds Ratio, CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>

<sup>Created on 2021-12-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
Thank you for reporting this!

This could be tricky because we use the `mice::tidy()` function for imputed data models, but have another tidier for multinomial models and the the tidy functions cannot be added to one another.

**Comment by ddsjoberg** [comment]
The mice pool method does return the `"y.level"` column that can be used to group the outcomes like in the model on unimputed data.

``` r
library(mice)
library(nnet)
library(gtsummary)

model <- multinom(age ~ bmi + chl, trace = F, data = nhanes)

imp <- mice(nhanes2, m = 2, print = FALSE, seed = 22112)
mice_model <- with(imp, multinom(age ~ bmi + chl, trace = F))

tidy(model)
#> # A tibble: 6 x 6
#>   y.level term        estimate std.error statistic  p.value
#>   <chr>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>
#> 1 2       (Intercept)   36.2       5.43       6.67 2.64e-11
#> 2 2       bmi           -5.31      2.28      -2.33 1.96e- 2
#> 3 2       chl            0.600     0.329      1.82 6.81e- 2
#> 4 3       (Intercept)   30.9       5.34       5.78 7.31e- 9
#> 5 3       bmi           -5.56      2.23      -2.50 1.25e- 2
#> 6 3       chl            0.648     0.334      1.94 5.23e- 2
mice_model %>% 
  pool_and_tidy_mice() %>%
  as_tibble()
#> pool_and_tidy_mice(): Tidying mice model with
#> `mice::pool(x) %>% mice::tidy()`
#> # A tibble: 6 x 14
#>   term    estimate std.error statistic p.value       b    df dfcom   fmi  lambda
#>   <chr>      <dbl>     <dbl>     <dbl>   <dbl>   <dbl> <dbl> <int> <dbl>   <dbl>
#> 1 (Inter~   4.85      4.76      1.02    0.329  2.04e+0 11.8     19 0.252 0.135  
#> 2 bmi      -0.584     0.287    -2.03    0.0578 3.89e-4 17.1     19 0.106 0.00708
#> 3 chl       0.0582    0.0319    1.82    0.0999 1.25e-4  9.58    19 0.313 0.183  
#> 4 (Inter~  -0.343     7.01     -0.0489  0.963  9.38e+0  6.13    19 0.443 0.286  
#> 5 bmi      -0.600     0.297    -2.02    0.0589 3.41e-4 17.2     19 0.104 0.00581
#> 6 chl       0.0847    0.0411    2.06    0.0862 3.34e-4  5.88    19 0.455 0.296  
#> # ... with 4 more variables: m <int>, riv <dbl>, ubar <dbl>, y.level <fct>
```

<sup>Created on 2021-12-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The gtsummary package has special handling for other model models (e.g. mixed effects, `survival::survreg()`, Stan Bayesian models, GAMs). Is there a way to handle all these special cases in the mice tidying framework?

**Comment by ddsjoberg** [comment]
@uakimix please install the dev version of the package from GitHub and let me know if your issue is resolved.

**Comment by uakimix** [comment]
It works.  issue resolved
That was really fast, Thanks!
