### ISSUE TITLE
Help keeping whitespaces at the beginning

### ISSUE THREAD

**Issue by mdidish** [ddsjoberg/gtsummary#1080]
Dear
First, thank for your great package!

I failed to keep several whitespaces in row names wit gt:: functions. In this example, _mpg_ label should be preceded by two whitespace:

```
mtcars[,1:6] %>%
  tbl_summary(label = mpg ~ "  mpg") %>%
  as_gt() %>%
  tab_style(style = gt::cell_text(whitespace = "break-spaces"),
            locations = cells_stub())
```
What could be the solution?

Best,
Marc

**Comment by ddsjoberg** [comment]
Dear @mdidish , 

I am not sure the best way to handle this in gt. Within gtsummary, you can add indentation (you can also do this in gt, btw).

```r
mtcars[,1:6] %>%
  tbl_summary() %>%
  modify_table_styling(
    columns = label,
    rows = variable == "mpg",
    text_format = "indent"
  )
```
![image](https://user-images.githubusercontent.com/26774684/147664614-273d2ff1-771b-4833-910b-2e97c57de95a.png)

hope this helps

**Comment by mdidish** [comment]
Thank you a lot for your very fast response, I didn't know "indent" text_format, very useful.
Best,
