### ISSUE TITLE
Feature request: Option to change value of "numeric variables with fewer than 10 unique levels".

### ISSUE THREAD

**Issue by toshifumikuroda** [ddsjoberg/gtsummary#1086]
In case of small sample, numerical variables may takes less than 10 unique levels.
Especially, in case of many observation takes value 0.

I am using list of the variable set to make many tables with uniform style tables for categorical variables and tables for numerical variables. However, gtsummary's  tbl_summary does not accept this way because it forces numerical variables with less than 10 unique levels as categorical variables.
I request to add option value to set the number of unique levels to summarize as categorical variables for numerical variables.

Thank you for your consideration.

**Comment by ddsjoberg** [comment]
Would using the selectors to change the summary type of all numeric columns work?
https://www.danieldsjoberg.com/gtsummary/dev/reference/syntax.html

``` r
library(gtsummary)

mtcars %>%
  tbl_summary(type = where(is.numeric) ~ "continuous") %>%
  as_kable()
```

| **Characteristic** | **N = 32**           |
|:-------------------|:---------------------|
| mpg                | 19.2 (15.4, 22.8)    |
| cyl                | 6.00 (4.00, 8.00)    |
| disp               | 196 (121, 326)       |
| hp                 | 123 (96, 180)        |
| drat               | 3.70 (3.08, 3.92)    |
| wt                 | 3.33 (2.58, 3.61)    |
| qsec               | 17.71 (16.89, 18.90) |
| vs                 | 0.00 (0.00, 1.00)    |
| am                 | 0.00 (0.00, 1.00)    |
| gear               | 4.00 (3.00, 4.00)    |
| carb               | 2.00 (2.00, 4.00)    |

<sup>Created on 2022-01-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If this is not a good solution for you, please provide more details.

**Comment by toshifumikuroda** [comment]
Thank you for your recommendation.
It works as I want.
I appreciate your help in this matter and hope many people will know about it.
