### ISSUE TITLE
Help with Custom add_p/add_difference function in tbl_summary object

### ISSUE THREAD

**Issue by feizhadj** [ddsjoberg/gtsummary#1094]
Hi there,

First off, happy 2022 and thank you so much for this wonderful package. I apologize for my novice-experience with GitHub and R-coding in advance, but I've been trying to create a custom add_p function such that p-values from a linear regression model would be pulled. The reason being is that I would like to format a tbl_summary object rather than merging a tbl_regression object. The furthest I was able to get was with this:

`lm <- function(data, variable, by, ...) {
  model = lm(variable ~ as.numeric(factor(by)), data = data)
  summary(model)$coefficient[,"Pr(>|t|)"][2]
}`

To preface, "by" is comprised of discrete, ordered values and "variable" is continuous. 
However, when I tried to run the `add_p(test = variable ~ "lm", include = variable)` addition to my table, I receive a C stack usage error:

`There was an error in 'add_p()/add_difference()' for variable, p-value omitted:
Error: C stack usage 15923920 is too close to the limit.`

Without the add_p, this table is able to be compiled without a hitch, so I would like to ask how I could go about revising this function code if you wouldn't take too much of your time.

Thank you!

**Comment by ddsjoberg** [comment]
Thanks @feizhadj for the post.

You don't need to define a custom function. ANOVA and lm() are the same method. You can use `add_p(everything() ~ "aov")`.

FYI, GitHub Issues are a great place to make feature requests or report bugs. To ask questions about using the package, please post to stackoverflow.com

Happy Programming!

**Comment by ddsjoberg** [comment]
Happy New Year!
