### ISSUE TITLE
Bug Report: Can't pass arg `correct = FALSE` to `mcnemar.test.wide`

### ISSUE THREAD

**Issue by philsf** [ddsjoberg/gtsummary#1095]
I am trying to use McNemar's test with `tbl_cross`. After the inclusion of the `mcnemar.test.wide` flavor it is much easier to do so (thanks!), but I can't pass any arguments to the underlying `mcnemar.test` function. The following code was tested in `gtsummary` version 1.5.0.9025.

Upon close inspection of the code in functions `add_p_test_mcnemar.test` and `add_p_test_mcnemar.test_wide` they use the same syntax for passing `test.args` to the base function, so if this is a bug, it's probably not there. I am not familiar with the internal `gtsummary` workflow so I can't figure out where the problem is.

```r
# data
trial_paired <- trial %>%
  select(trt, response) %>%
  mutate(trt = str_remove(trt, "Drug ")) %>%
  group_by(trt) %>%
  mutate(id = row_number()) %>%
  ungroup() %>%
  filter(complete.cases(.)) %>%
  group_by(id) %>%
  filter(n() == 2) %>%
  ungroup()

trial_paired_wide <- trial_paired %>%
  pivot_wider(id, names_from = trt, values_from = response)

# expected p-values with/without correction
mcnemar.test(trial_paired_wide$A, trial_paired_wide$B)$p.value %>% style_pvalue(digits = 3)
# [1] "0.542"
mcnemar.test(trial_paired_wide$A, trial_paired_wide$B, correct = FALSE)$p.value %>% style_pvalue(digits = 3)
# [1] "0.446"
```

Using the previous mcnemar wrapper, with slight modifications to the example in the gallery:

```r
trial_paired %>%
  tbl_summary(by = trt, include = response) %>%
  add_p(test = list(all_categorical() ~ "mcnemar.test"),
        test.args = all_tests("mcnemar.test") ~ list(correct = FALSE),
        group = id)
```
|**Characteristic** |**A**, N = 92 |**B**, N = 92 |**p-value** |
|:------------------|:-------------|:-------------|:-----------|
|Tumor Response     |26 (28%)      |31 (34%)      |0.4         |

(table rendered in RStudio viewer pane shows "McNemar's Chi-squared test")

Three attempts using the new wrapper:

```r
trial_paired_wide %>%
  tbl_cross(row = A, col = B) %>%
  # # tbl_summary syntax does not work for mcnemar.test.wide in tbl_cross
  # add_p(test = list(all_categorical() ~ "mcnemar.test.wide"),
  # # tbl_cross-friendly syntax
  add_p(test = "mcnemar.test.wide",
        test.args = all_tests("mcnemar.test") ~ list(correct = FALSE),
  )
```
|**Characteristic** |0  |1  |**Total** |**p-value** |
|:------------------|:--|:--|:---------|:-----------|
|__Tumor Response__ |   |   |          |0.5         |
|0                  |42 |24 |66        |            |
|1                  |19 |7  |26        |            |
|__Total__          |61 |31 |92        |            |

(table rendered in RStudio viewer pane shows "McNemar's Chi-squared test with continuity correction ).

**Comment by philsf** [comment]
I'd be happy to create a PR if someone points me to where I should try to make changes.

**Comment by ddsjoberg** [comment]
Thanks for the post @philsf !

The issue is that `add_p.tbl_cross()` doesn't have a `test.args=` argument. When it was passed, it was being swallowed in the `...` and ignored. It's easy enough to add!

**Comment by ddsjoberg** [comment]
@philsf do you want to take a quick look at the pull request before I merge? Does this do what you're looking for?
https://github.com/ddsjoberg/gtsummary/pull/1096

**Comment by philsf** [comment]
Sure, I was still trying to parse those functions, but thanks for helping out so promply! I will clone and test

**Comment by philsf** [comment]
Side note: I really want to include/improve some of the *pt* translations, including adding one for the McNemar test. I found some translations in an excel file `data-raw/gtsummary_translated.xlsx` <- is this the right place to add these translations?
