### ISSUE TITLE
Bug Report: update pt translations

### ISSUE THREAD

**Issue by philsf** [ddsjoberg/gtsummary#1098]
This issue is a followup to #1097. It includes some translations of commonly used strings in `gtsummary` for the pt language:

**New strings:**
- added two new lines in add_p.tbl_summary for McNemar test (with/ without continuity correction)
- added a new line for Paired t-test
- SE / standard error

**Changes to previously translations:**
- t-test: now mentions Welch correction (as per the en string)
- RR: translated as Risk Ratio (instead of Relative Risk)
- CI (et al):  changed to IC in pt (similar to fr)
- p-value: Capitalized (for consistency with q-value)
- One-way ANOVA: different choice of translation, consistent with books/tutorials in pt
- random intercept logistic regression: transation is now closer to the original meaning
- IQR: translated as AIQ
- Variance

Note that the RR string is proposed to change (from relative risk to risk ratio). If this is not approriate, let me know and I will revert the translation back to "relative risk".

Attached below is a CSV with all lines changed from `data-raw/gtsummary_translated.xlsx `

[pt_updates.csv](https://github.com/ddsjoberg/gtsummary/files/7833898/pt_updates.csv)

**Comment by philsf** [comment]
The CSV was exported from the original XLSX with `readr`, and it is encoded in UTF-8. I hope this makes encoding issues easier to deal with.

**Comment by philsf** [comment]
It works wonderful for all the translations I tested (thanks). However I just stumbled in a missing one: t-test without Welch correction.

is it too late to add this last one?

**Comment by ddsjoberg** [comment]
@philsf not too late! You can just add it here, and I'll copy it in

**Comment by philsf** [comment]
en = "Two Sample t-test"
pt = "Teste t para amostras independentes"

Updated CSV below

[pt_updates.csv](https://github.com/ddsjoberg/gtsummary/files/7834018/pt_updates.csv)
