### ISSUE TITLE
gtsummary + R Markdown vignette: limitations of flextable

### ISSUE THREAD

**Issue by dmenne** [ddsjoberg/gtsummary#1110]
The gtsummary + R Markdown vignette suggests that all is fine with gtsummary and MS Word. To avoid others to try and fail, it would be good to add a comment there that Word template, e.g. for tables, will never be supported by design. It works ok with kable though.

See also https://github.com/davidgohel/flextable/issues/372

[gtsummary_table.zip](https://github.com/ddsjoberg/gtsummary/files/7891131/gtsummary_table.zip)

**Comment by ddsjoberg** [comment]
Hello @dmenne ! Thanks for the post.

The Word templates are a knitr (and therefore, `kable()`) feature. I don't think any other pkgs support them, in the same way. My first instinct is to leave it up to the users to know what features are and are not available based on the output type they select? 

(Primarily, this removes the burden from me to know every output type's features frontwards and backwards. Recently, I had text indicating that one of the output formats did not support markdown language styling in the column headers....then the package was later updated to support them and I had incorrect information on my site for quite some time. Anyway, it is a lot to keep up on the developments in every pkg that creates tables.)

I am not too familiar with officedown, but the website does indicate that flextables are fully supported. Perhaps you could use the officedown Word output type with a template and a gtsummary table that is converted to flextable?

**Comment by dmenne** [comment]
I understand the maintainability issue - it is a mess to keep my https://gist.github.com/dmenne/f8eb291c9e71a5de44764d442e8bdefd updated - it should include gtsummary.

Maybe it is ok to keep it here - googlers will find it, even when closed.

Using officedown is a bit awkward, because then I am limited to Office output or have to add switches.  I was using pander, which does not support table numbering and is no longer maintained. Adding table numbers manually is possible.
