### ISSUE TITLE
Combined total N in header with tbl_strata in combination with tbl_stack

### ISSUE THREAD

**Issue by cjprobst** [ddsjoberg/gtsummary#1125]
Hey, thanks first for your awesome package!

I found this question on stackoverflow: 
[https://stackoverflow.com/questions/64533310/list-total-n-in-header-of-tbl-stack](https://stackoverflow.com/questions/64533310/list-total-n-in-header-of-tbl-stack)
It's really nice, that we now can do this with tbl_strata in combination with tbl_stack but the initial problem with the incorrect totals remains. Is there a way to achieve the "total totals" within tbl_strata?

Thanks for any help
Christine

**Comment by ddsjoberg** [comment]
To be clear, the Ns are **not** incorrect, and the expected behavior is well documented. For example, the `tbl_stack()` help file indicates that the attributes (which include headers, footnotes, etc) are retained from the first table. Also, when the tables are stacked, if the headers are different, a note is printed alerting the user. 

Consider that `tbl_stack()` is a general function for any gtsummary table, even those where Ns are neither applicable nor defined. Similarly, `tbl_strata()` is a general purpose function.

If you have a situation that continually arises where you create stratified `tbl_summary()` tables that are stacked and have a desired output format, please provide details along with a reproducible code example and we can continue the conversation.

**Comment by cjprobst** [comment]
Hi again,

next try with a reproducible example. I would need a summary table for subsets (strata) with a grouping variable (by). I can achieve this with the nice function tbl_strata like this: 

`tbl_strata_ex1 <-
  trial %>%
  select(age, grade, response, trt) %>%
  mutate(grade = paste("Grade", grade)) %>%
  tbl_strata(
    strata = grade,
    .tbl_fun =
      ~ .x %>%
      tbl_summary(by = trt, missing = "ifany"),
    .combine_with = "tbl_stack",
    .header = "{strata}, N = {n}"
  )

tbl_strata_ex1
`
This results in the message:

"Column headers among stacked tables differ. Headers from the first table are
used. Use `quiet = TRUE` to supress this message."

And what looks like 'totals' for Drug A and Drug B are, as described by the message, only the totals for the first strata. That's rather confusing in this setting.

![image](https://user-images.githubusercontent.com/95871833/151505064-d503c32f-8511-4cbc-8519-7aa8e7491fd9.png)

I can manually change the header, but it would be nice if there will be an internal function to calculate the totals over all strata.

Expected outcome for the header:

![image](https://user-images.githubusercontent.com/95871833/151519712-af91529f-ceed-4ac6-84c5-bca9729bf7e9.png)

Thanks for help!

**Comment by ddsjoberg** [comment]
Hello, 

I've been thinking about this issue for some time, and I don't think there is a robust way to solve this programmatically: the `tbl_stack()` function to quite general and therefore a pointed solution doesn't seem possible.

Here is a solution that will work in this situation, however.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.5.2'

tbl_stratified <- 
  trial %>%
  tbl_strata(
    strata = trt, 
    ~ .x %>%
      tbl_summary(include = age),
    .combine_with = "tbl_stack"
  )
#> i Column headers among stacked tables differ. Headers from the first table are
#> used. Use `quiet = TRUE` to supress this message.

tbl_overall <- tbl_summary(trial, include = age)

# update headers from overall table
tbl_stratified$table_styling$header <-
  dplyr::rows_update(
    tbl_stratified$table_styling$header,
    tbl_overall$table_styling$header,
    by = "column"
  )

tbl_stratified %>%
  as_kable() # convert to kable to display on GH
```

| **Group** | **Characteristic** | **N = 200** |
|:----------|:-------------------|:-----------:|
| Drug A    | Age                | 46 (37, 59) |
|           | Unknown            |      7      |
| Drug B    | Age                | 48 (39, 56) |
|           | Unknown            |      4      |

<sup>Created on 2022-03-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
