### ISSUE TITLE
Using add_overall() before add_n() in tbl_summary() doubles n

### ISSUE THREAD

**Issue by brachem-christian** [ddsjoberg/gtsummary#1126]
Hello,

thanks for the awesome package!

When adding both add_overall() and add_n() to a tbl_summary() the results change depending on the order. When add_overall() is used first, the N are doubled.

Reprex:

Doubled N:
``` r
library(gtsummary)

tbl_summary(iris, by = Species) |> 
  add_overall() |> 
  add_n()
```

<div id="gibruvntcs" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>N</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Overall</strong>, N = 150<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>setosa</strong>, N = 50<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>versicolor</strong>, N = 50<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>virginica</strong>, N = 50<sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Sepal.Length</td>
<td class="gt_row gt_center">300</td>
<td class="gt_row gt_center">5.80 (5.10, 6.40)</td>
<td class="gt_row gt_center">5.00 (4.80, 5.20)</td>
<td class="gt_row gt_center">5.90 (5.60, 6.30)</td>
<td class="gt_row gt_center">6.50 (6.23, 6.90)</td></tr>
    <tr><td class="gt_row gt_left">Sepal.Width</td>
<td class="gt_row gt_center">300</td>
<td class="gt_row gt_center">3.00 (2.80, 3.30)</td>
<td class="gt_row gt_center">3.40 (3.20, 3.68)</td>
<td class="gt_row gt_center">2.80 (2.52, 3.00)</td>
<td class="gt_row gt_center">3.00 (2.80, 3.18)</td></tr>
    <tr><td class="gt_row gt_left">Petal.Length</td>
<td class="gt_row gt_center">300</td>
<td class="gt_row gt_center">4.35 (1.60, 5.10)</td>
<td class="gt_row gt_center">1.50 (1.40, 1.58)</td>
<td class="gt_row gt_center">4.35 (4.00, 4.60)</td>
<td class="gt_row gt_center">5.55 (5.10, 5.88)</td></tr>
    <tr><td class="gt_row gt_left">Petal.Width</td>
<td class="gt_row gt_center">300</td>
<td class="gt_row gt_center">1.30 (0.30, 1.80)</td>
<td class="gt_row gt_center">0.20 (0.20, 0.30)</td>
<td class="gt_row gt_center">1.30 (1.20, 1.50)</td>
<td class="gt_row gt_center">2.00 (1.80, 2.30)</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="6">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          Median (IQR)
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>

Correct N:
```r 
tbl_summary(iris, by = Species) |> 
  add_n() |> 
  add_overall() 
```
<div id="fghnbwordo" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>N</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Overall</strong>, N = 150<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>setosa</strong>, N = 50<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>versicolor</strong>, N = 50<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>virginica</strong>, N = 50<sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Sepal.Length</td>
<td class="gt_row gt_center">150</td>
<td class="gt_row gt_center">5.80 (5.10, 6.40)</td>
<td class="gt_row gt_center">5.00 (4.80, 5.20)</td>
<td class="gt_row gt_center">5.90 (5.60, 6.30)</td>
<td class="gt_row gt_center">6.50 (6.23, 6.90)</td></tr>
    <tr><td class="gt_row gt_left">Sepal.Width</td>
<td class="gt_row gt_center">150</td>
<td class="gt_row gt_center">3.00 (2.80, 3.30)</td>
<td class="gt_row gt_center">3.40 (3.20, 3.68)</td>
<td class="gt_row gt_center">2.80 (2.52, 3.00)</td>
<td class="gt_row gt_center">3.00 (2.80, 3.18)</td></tr>
    <tr><td class="gt_row gt_left">Petal.Length</td>
<td class="gt_row gt_center">150</td>
<td class="gt_row gt_center">4.35 (1.60, 5.10)</td>
<td class="gt_row gt_center">1.50 (1.40, 1.58)</td>
<td class="gt_row gt_center">4.35 (4.00, 4.60)</td>
<td class="gt_row gt_center">5.55 (5.10, 5.88)</td></tr>
    <tr><td class="gt_row gt_left">Petal.Width</td>
<td class="gt_row gt_center">150</td>
<td class="gt_row gt_center">1.30 (0.30, 1.80)</td>
<td class="gt_row gt_center">0.20 (0.20, 0.30)</td>
<td class="gt_row gt_center">1.30 (1.20, 1.50)</td>
<td class="gt_row gt_center">2.00 (1.80, 2.30)</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="6">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          Median (IQR)
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>

<sup>Created on 2022-01-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I deleted the style portion the reprex package created because it seems irrelevant for this example.

**Comment by ddsjoberg** [comment]
@brachem-christian thank you so much for the bug report and the reprex! I know exactly the update I made that results in this bug and will patch ASAP. Much appreciated!
