### ISSUE TITLE
Bug Report: Footnotes on `tbl_summary()`

### ISSUE THREAD

**Issue by jalavery** [ddsjoberg/gtsummary#1127]
There may be a bug in the footnotes for `tbl_summary()` and variables specified to be of type continuous2.

```r
library(gtsummary)

# footnote appears as expected
tbl_summary(trial)

# footnote still available
tbl_summary(trial, 
            by = trt)

# footnote still available
tbl_summary(trial, 
            by = trt) %>% 
  add_overall()

# missing footnote?
tbl_summary(trial,
            by = trt,
            type = list(age ~ "continuous2"),
            statistic = list(
              age ~ c("{median} ({p25}, {p75})", "{min}, {max}")))

# footnote there, but incorrect
tbl_summary(trial,
            by = trt,
            type = list(age ~ "continuous2"),
            statistic = list(
              age ~ c("{median} ({p25}, {p75})", "{min}, {max}"))) %>% 
  add_overall()
```

**Comment by ddsjoberg** [comment]
Hey hey @jalavery ! Thanks for the post!

```r
# missing footnote?
tbl_summary(trial,
            by = trt,
            type = list(age ~ "continuous2"),
            statistic = list(
              age ~ c("{median} ({p25}, {p75})", "{min}, {max}")))
```
When we add `"continuous2"` the stat labels are added next to the variable, so I think (it's been a while since this decision was made) to merely exclude the footnote. Yes, this excludes the footnotes for the categorical data too, but these are typically more obvious. But in this case, only 1 continuous variable is `"continuous2"`, but the other footnotes are omitted as well.

What do you think the footnote should be in this case?

```r
# footnote there, but incorrect
tbl_summary(trial,
            by = trt,
            type = list(age ~ "continuous2"),
            statistic = list(
              age ~ c("{median} ({p25}, {p75})", "{min}, {max}"))) %>% 
  add_overall()
```
Oh goodness, yes, this footnote needs an update. What do you think it should be here?

**Comment by jalavery** [comment]
Ah, gotcha! Thanks for taking a look at this. 

For the first, I think if the only other variables are categorical, it makes sense not to show the n (%) on a footnote - I agree that updating the documentation will help. In this case there is also a regular `"continous"` (not `"continuous2"`) variable on the table, so it's not obvious what statistic is shown for that variable. Is there a way for the footnote to be "Median (IQR); n (%)" as it would be if there was no continuous2 variable on the table?

```
# missing footnote?
tbl_summary(trial,
            by = trt,
            type = list(age ~ "continuous2"),
            statistic = list(
              age ~ c("{median} ({p25}, {p75})", "{min}, {max}")))
```

For the second, similar to the above, I was expecting it to say "Median (IQR); n (%)" to reflect the `"continuous"` variable that's included on the table. 

```
# footnote there, but incorrect
tbl_summary(trial,
            by = trt,
            type = list(age ~ "continuous2"),
            statistic = list(
              age ~ c("{median} ({p25}, {p75})", "{min}, {max}"))) %>% 
  add_overall()
```

**Comment by ddsjoberg** [comment]
Which is easier to implement?
- No footnotes when any continuous2 summary?
- No footnotes for continuous2 variables, but all other vars retain the same footnotes
