### ISSUE TITLE
Feature request: <Describe request>

### ISSUE THREAD

**Issue by jojosgithub** [ddsjoberg/gtsummary#1134]
**Describe the solution you'd like**
I would like to be able to use plus minus notation in the tables

**Additional context**
![YkkGN](https://user-images.githubusercontent.com/20014621/151657806-2901ccec-61f5-4ee7-8429-46bb18e1a907.png)

**Comment by ddsjoberg** [comment]
Please review the help file for `tbl_summary()` and the vignette on the package website. You'll need to modify the `statistic=` argument.

GitHub Issues is a place to make bug reports and feature requests. Please use stackoverflow.com to ask questions about how to use the package.
