### ISSUE TITLE
Error when variable types are sepcified in the type argument of tbl_summary function

### ISSUE THREAD

**Issue by saifelayan** [ddsjoberg/gtsummary#1136]
Every time I specify variable types using the type argument in tbl_summary function, I get the following error:
"Error in type_check(rhs) : object 'rlang_is_string' not found".
The problem occurs regardless of which or how many variables I try to specify the types thereof. 

The error can be reporduced using the code below:

mtcars %>% 
  tbl_summary(
     include =c("mpg", "cyl", "disp"),
     type = cyl ~ "continuous",
  )

**Comment by ddsjoberg** [comment]
Hi @saifelayan , thank you for the post!

This is an error related to the recent release of rlang 1.0.0. gtsummary was built with rlang 4.1.2 and isn't compatible with the newest version. The fix was just put to CRAN an hour or so ago. Couple of options for you. 
1. Reinstall gtsummary using `install.packages("gtsummary", type = "source")`
2. Install gtsummary from GitHub using `devtools::install_github("ddsjoberg/gtsummary")`

Sorry for the inconvenience!

**Comment by saifelayan** [comment]
> Hi @saifelayan , thank you for the post!
> 
> This is an error related to the recent release of rlang 1.0.0. gtsummary was built with rlang 4.1.2 and isn't compatible with the newest version. The fix was just put to CRAN an hour or so ago. Couple of options for you.
> 
>     1. Reinstall gtsummary using `install.packages("gtsummary", type = "source")`
> 
>     2. Install gtsummary from GitHub using `devtools::install_github("ddsjoberg/gtsummary")`
> 
> 
> Sorry for the inconvenience!

**Comment by saifelayan** [comment]
> Hi @saifelayan , thank you for the post!
> 
> This is an error related to the recent release of rlang 1.0.0. gtsummary was built with rlang 4.1.2 and isn't compatible with the newest version. The fix was just put to CRAN an hour or so ago. Couple of options for you.
> 
>     1. Reinstall gtsummary using `install.packages("gtsummary", type = "source")`
> 
>     2. Install gtsummary from GitHub using `devtools::install_github("ddsjoberg/gtsummary")`
> 
>     3. Revert to the previous version of rlang
> 
> 
> Sorry for the inconvenience!


Thanks, @ddsjoberg! I reinstalled gtsummary the way you suggested and the problem was solved. Thanks for this wonderful package and for your great follow up.

**Comment by ddsjoberg** [comment]
I am going to pin this issue, and update the title in case others encounter the same issue in the coming days FYI
