### ISSUE TITLE
Feature request: <Formatting of glance table>

### ISSUE THREAD

**Issue by bhattmaulik** [ddsjoberg/gtsummary#1138]
Changing the format of glance table in tbl_regression function

First of all, I would like to thank you for making my life easier with your package gtsummary. I am a doctoral student, and I am frequently expected to prepare regression summary tables because of my course requirement. The function tbl_regression() in your package gtsummary has helped me a lot in this coursework. However, when it comes to presenting the regression diagnostic numbers, I have an issue to deal with. Let me share with you a reproducible example to explain the issue.

> library(tidyverse)
> #;-) -- Attaching packages --------------------------------------- tidyverse 1.3.1 --
> #;-) v ggplot2 3.3.5     v purrr   0.3.4
> #;-) v tibble  3.1.6     v dplyr   1.0.7
> #;-) v tidyr   1.1.4     v stringr 1.4.0
> #;-) v readr   2.1.2     v forcats 0.5.1
> #;-) -- Conflicts ------------------------------------------ tidyverse_conflicts() --
> #;-) x dplyr::filter() masks stats::filter()
> #;-) x dplyr::lag()    masks stats::lag()
> library(broom)
> library(gt)
> library(gtsummary)

First, I would prepare a basic linear regression model, and create a summary table for the same, using gtsummary package. I am also expected to show how effective this model is. Therefore, I am also adding glance table at the end of the regression summary.

```
mod1 <- lm(mpg ~ ., data = mtcars)
gt_summary <- tbl_regression(mod1) %>% add_glance_table()
gt_summary
Characteristic	Beta	95% CI1	p-value
cyl	-0.11	-2.3, 2.1	>0.9
disp	0.01	-0.02, 0.05	0.5
hp	-0.02	-0.07, 0.02	0.3
drat	0.79	-2.6, 4.2	0.6
wt	-3.7	-7.7, 0.22	0.063
qsec	0.82	-0.70, 2.3	0.3
vs	0.32	-4.1, 4.7	0.9
am	2.5	-1.8, 6.8	0.2
gear	0.66	-2.4, 3.8	0.7
carb	-0.20	-1.9, 1.5	0.8
R²	0.869		
Adjusted R²	0.807		
Sigma	2.65		
Statistic	13.9		
p-value	<0.001		
df	10		
Log-likelihood	-69.9		
AIC	164		
BIC	181		
Deviance	147		
Residual df	21		
No. Obs.	32		
1 CI = Confidence Interval
```
We can see that there are four columns in the main regression summary table, while the glance table has only two columns. Therefore, two columns on the bottom right of the gt_summary table remains empty. There are two issues with this. First, it looks aesthetically unappealing. There are 12 rows, where left hand side columns are filled, while right hand side columns are empty. Secondly, it also increases the page count some times.

As a workaround, I generally knit the document in Microsoft Word, and manually cut and paste the bottom 6 rows of the glance table on the right hand side. Then I would delete the empty rows in Microsoft Word. Then I would print it to PDF to submit the document.

So, I have prepared a format of glance table that would be helpful for my purpose.

```
basic_glance_table <- glance(mod1) # glance table using broom package
long_glance_table <- pivot_longer(basic_glance_table, names_to = "Parameter", values_to = "Value", cols = everything()) # converting it to long format
half_number <- if_else(nrow(long_glance_table) %% 2 == 0, nrow(long_glance_table) / 2, (nrow(long_glance_table)) / 2) # We will keep these many rows in the left column of the glance table. The remaining rows will appear in the right hand side.
glance1 <- head(long_glance_table, half_number)
glance2 <- tail(long_glance_table, half_number)
final_glance_table <- bind_cols(glance1, glance2)
#;-) New names:
#;-) * Parameter -> Parameter...1
#;-) * Value -> Value...2
#;-) * Parameter -> Parameter...3
#;-) * Value -> Value...4
gt::gt(final_glance_table)
Parameter...1	Value...2	Parameter...3	Value...4
r.squared	8.690158e-01	logLik	-69.85491
adj.r.squared	8.066423e-01	AIC	163.70981
sigma	2.650197e+00	BIC	181.29864
statistic	1.393246e+01	deviance	147.49443
p.value	3.793152e-07	df.residual	21.00000
df	1.000000e+01	nobs	32.00000
```
I would like the glance table to appear in this format. Indeed, software like EViews present the regression output in this format.

So, can you please suggest a way to change the format of glance table in this format? I suspect, if this is made the default format for the glance table, it might break the code for previous work. So, I think this can be achieved using a theme for regression table. Is it possible to do so?

Session info
Because session_info is TRUE, the rendered result includes session info, even though no such code is included here in the source document.

 Standard output and standard error
 Session info
```
sessioninfo::session_info()
#;-) - Session info ---------------------------------------------------------------
#;-)  setting  value
#;-)  version  R version 4.1.2 (2021-11-01)
#;-)  os       Windows 10 x64 (build 19044)
#;-)  system   x86_64, mingw32
#;-)  ui       RTerm
#;-)  language (EN)
#;-)  collate  English_India.1252
#;-)  ctype    English_India.1252
#;-)  tz       Asia/Calcutta
#;-)  date     2022-02-01
#;-)  pandoc   2.17.0.1 @ C:/Program Files/RStudio/bin/quarto/bin/ (via rmarkdown)
#;-) 
#;-) - Packages -------------------------------------------------------------------
#;-)  package       * version    date (UTC) lib source
#;-)  assertthat      0.2.1      2019-03-21 [1] CRAN (R 4.1.1)
#;-)  backports       1.4.1      2021-12-13 [1] CRAN (R 4.1.2)
#;-)  broom         * 0.7.12     2022-01-28 [1] CRAN (R 4.1.2)
#;-)  broom.helpers   1.6.0      2022-01-12 [1] CRAN (R 4.1.2)
#;-)  cellranger      1.1.0      2016-07-27 [1] CRAN (R 4.1.1)
#;-)  checkmate       2.0.0      2020-02-06 [1] CRAN (R 4.1.1)
#;-)  cli             3.1.1      2022-01-20 [1] CRAN (R 4.1.2)
#;-)  colorspace      2.0-2      2021-06-24 [1] CRAN (R 4.1.0)
#;-)  commonmark      1.7        2018-12-01 [1] CRAN (R 4.1.1)
#;-)  crayon          1.4.2      2021-10-29 [1] CRAN (R 4.1.1)
#;-)  DBI             1.1.2      2021-12-20 [1] CRAN (R 4.1.2)
#;-)  dbplyr          2.1.1      2021-04-06 [1] CRAN (R 4.1.1)
#;-)  digest          0.6.29     2021-12-01 [1] CRAN (R 4.1.2)
#;-)  dplyr         * 1.0.7      2021-06-18 [1] CRAN (R 4.1.0)
#;-)  ellipsis        0.3.2      2021-04-29 [1] CRAN (R 4.1.1)
#;-)  evaluate        0.14       2019-05-28 [1] CRAN (R 4.1.1)
#;-)  fansi           1.0.2      2022-01-14 [1] CRAN (R 4.1.2)
#;-)  fastmap         1.1.0      2021-01-25 [1] CRAN (R 4.1.1)
#;-)  forcats       * 0.5.1      2021-01-27 [1] CRAN (R 4.1.1)
#;-)  fs              1.5.2      2021-12-08 [1] CRAN (R 4.1.2)
#;-)  generics        0.1.2      2022-01-31 [1] CRAN (R 4.1.2)
#;-)  ggplot2       * 3.3.5      2021-06-25 [1] CRAN (R 4.1.0)
#;-)  glue            1.6.1      2022-01-22 [1] CRAN (R 4.1.2)
#;-)  gt            * 0.3.1.9000 2022-01-30 [1] Github (rstudio/gt@c44578b)
#;-)  gtable          0.3.0      2019-03-25 [1] CRAN (R 4.1.1)
#;-)  gtsummary     * 1.5.2.9000 2022-01-30 [1] Github (ddsjoberg/gtsummary@eaf772a)
#;-)  haven           2.4.3      2021-08-04 [1] CRAN (R 4.1.0)
#;-)  hms             1.1.1      2021-09-26 [1] CRAN (R 4.1.1)
#;-)  htmltools       0.5.2      2021-08-25 [1] CRAN (R 4.1.1)
#;-)  httr            1.4.2      2020-07-20 [1] CRAN (R 4.1.1)
#;-)  jsonlite        1.7.3      2022-01-17 [1] CRAN (R 4.1.2)
#;-)  knitr           1.37       2021-12-16 [1] CRAN (R 4.1.2)
#;-)  labelled        2.9.0      2021-10-29 [1] CRAN (R 4.1.1)
#;-)  lifecycle       1.0.1      2021-09-24 [1] CRAN (R 4.1.1)
#;-)  lubridate       1.8.0      2021-10-07 [1] CRAN (R 4.1.1)
#;-)  magrittr        2.0.2      2022-01-26 [1] CRAN (R 4.1.2)
#;-)  modelr          0.1.8      2020-05-19 [1] CRAN (R 4.1.1)
#;-)  munsell         0.5.0      2018-06-12 [1] CRAN (R 4.1.1)
#;-)  pillar          1.6.5      2022-01-25 [1] CRAN (R 4.1.2)
#;-)  pkgconfig       2.0.3      2019-09-22 [1] CRAN (R 4.1.1)
#;-)  purrr         * 0.3.4      2020-04-17 [1] CRAN (R 4.1.1)
#;-)  R.cache         0.15.0     2021-04-30 [1] CRAN (R 4.1.1)
#;-)  R.methodsS3     1.8.1      2020-08-26 [1] CRAN (R 4.1.1)
#;-)  R.oo            1.24.0     2020-08-26 [1] CRAN (R 4.1.1)
#;-)  R.utils         2.11.0     2021-09-26 [1] CRAN (R 4.1.1)
#;-)  R6              2.5.1      2021-08-19 [1] CRAN (R 4.1.0)
#;-)  Rcpp            1.0.8      2022-01-13 [1] CRAN (R 4.1.2)
#;-)  readr         * 2.1.2      2022-01-30 [1] CRAN (R 4.1.2)
#;-)  readxl          1.3.1      2019-03-13 [1] CRAN (R 4.1.1)
#;-)  rematch2        2.1.2      2020-05-01 [1] CRAN (R 4.1.1)
#;-)  reprex          2.0.1.9000 2021-11-07 [1] Github (tidyverse/reprex@b96611f)
#;-)  rlang           1.0.0      2022-01-26 [1] CRAN (R 4.1.2)
#;-)  rmarkdown       2.11       2021-09-14 [1] CRAN (R 4.1.0)
#;-)  rstudioapi      0.13       2020-11-12 [1] CRAN (R 4.1.1)
#;-)  rvest           1.0.2      2021-10-16 [1] CRAN (R 4.1.1)
#;-)  sass            0.4.0.9000 2021-11-28 [1] Github (rstudio/sass@f7a9540)
#;-)  scales          1.1.1      2020-05-11 [1] CRAN (R 4.1.1)
#;-)  sessioninfo     1.2.2      2021-12-06 [1] CRAN (R 4.1.2)
#;-)  stringi         1.7.6      2021-11-29 [1] CRAN (R 4.1.2)
#;-)  stringr       * 1.4.0      2019-02-10 [1] CRAN (R 4.1.1)
#;-)  styler          1.6.2      2021-09-23 [1] CRAN (R 4.1.1)
#;-)  tibble        * 3.1.6      2021-11-07 [1] CRAN (R 4.1.2)
#;-)  tidyr         * 1.1.4      2021-09-27 [1] CRAN (R 4.1.1)
#;-)  tidyselect      1.1.1      2021-04-30 [1] CRAN (R 4.1.1)
#;-)  tidyverse     * 1.3.1      2021-04-15 [1] CRAN (R 4.1.1)
#;-)  tzdb            0.2.0      2021-10-27 [1] CRAN (R 4.1.1)
#;-)  utf8            1.2.2      2021-07-24 [1] CRAN (R 4.1.0)
#;-)  vctrs           0.3.8      2021-04-29 [1] CRAN (R 4.1.1)
#;-)  withr           2.4.3      2021-11-30 [1] CRAN (R 4.1.2)
#;-)  xfun            0.29       2021-12-14 [1] CRAN (R 4.1.2)
#;-)  xml2            1.3.3      2021-11-30 [1] CRAN (R 4.1.2)
#;-)  yaml            2.2.2      2022-01-25 [1] CRAN (R 4.1.2)
#;-) 
#;-)  [1] C:/Users/************/Documents/R/win-library/4.1
#;-)  [2] C:/Program Files/R/R-4.1.2/library
#;-) 
#;-) --------------------------------------------------------------------

```

**Comment by ddsjoberg** [comment]
hello @bhattmaulik , thank you for the kind words.

What you're asking is technically possible; it's a bit tricky, and it'll need more work to look nice. I would recommend to just use `add_glance_source_note()` instead that will fill the space below the table with the statistics.

``` r
library(gtsummary)

add_2column_glance <- function(x) {
  # calculate glance stats
  df_glance_long <- 
    broom::glance(x$model_obj) %>%
    tidyr::gather()
  
  # split stats into two tibbles
  lst_glance <- 
    df_glance_long %>%
    dplyr::mutate(group = dplyr::row_number() <= dplyr::n() / 2) %>%
    dplyr::group_by(group) %>%
    dplyr::group_split()
  
  # merge into single tibble
  df_glance <-
    dplyr::bind_cols(
      lst_glance[[1]] %>% dplyr::select(label = key, estimate = value),
      lst_glance[[2]] %>% dplyr::select(ci = key, p.value = value)
    ) %>%
    dplyr::mutate(row_type = "my_glance_row")
  
  x %>%
    # add table to gtsummary object
    modify_table_body(
      ~ .x %>%
        dplyr::bind_rows(df_glance)
    ) %>%
    # apply a formatting function to the stats
    modify_fmt_fun(
      c(estimate, p.value) ~ style_sigfig,
      rows = row_type %in% "my_glance_row"
    )
}

lm(mpg ~ ., data = mtcars) %>%
  tbl_regression() %>%
  add_2column_glance() %>%
  as_kable() # convert to kable so it shows up in GH
#> Warning: attributes are not identical across measure variables;
#> they will be dropped
```

| **Characteristic** | **Beta** |  **95% CI**   | **p-value** |
|:-------------------|:--------:|:-------------:|:-----------:|
| cyl                |  -0.11   |   -2.3, 2.1   |    \>0.9    |
| disp               |   0.01   |  -0.02, 0.05  |     0.5     |
| hp                 |  -0.02   |  -0.07, 0.02  |     0.3     |
| drat               |   0.79   |   -2.6, 4.2   |     0.6     |
| wt                 |   -3.7   |  -7.7, 0.22   |    0.063    |
| qsec               |   0.82   |  -0.70, 2.3   |     0.3     |
| vs                 |   0.32   |   -4.1, 4.7   |     0.9     |
| am                 |   2.5    |   -1.8, 6.8   |     0.2     |
| gear               |   0.66   |   -2.4, 3.8   |     0.7     |
| carb               |  -0.20   |   -1.9, 1.5   |     0.8     |
| logLik             |   -70    |   r.squared   |    0.87     |
| AIC                |   164    | adj.r.squared |    0.81     |
| BIC                |   181    |     sigma     |     2.7     |
| deviance           |   147    |   statistic   |     14      |
| df.residual        |    21    |    p.value    |    0.00     |
| nobs               |    32    |      df       |     10      |

<sup>Created on 2022-02-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bhattmaulik** [comment]
Thank you for your quick and super helpful response. I could knit it to both - PDF and MS Word. My problem was actually more than just formatting. My faculties insist for closed source software like EViews or Stata. And I am adamant that I would use R as far as possible. Your package gtsummary is quite helpful to me, because it gives impression that I have used some closed source software. As you suggested, it is easy to use glance source note instead of such table, but then it would be easy to recognize that I am using R.
Secondly, I have learnt a lot from your use of tidyverse packages. Please let me know if I can help you any way. At least I can test features that you want to implement, if not anything else.
