### ISSUE TITLE
Consider updating `style_number()` to no longer use `round()`

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#1140]
The `round()` function has documented odd behavior when rounding values at 0.5. Something like `janitor::round_half_up()` has more expected outputs.

```r
round(0.5)
#> [1] 0

janitor::round_half_up(0.5)
#> [1] 1
```

**Comment by larmarange** [comment]
Something that could also be considered, is a rounding algorithm that preserves the sum, cf. https://larmarange.github.io/JLutils/reference/round_preserve_sum.html

(Note: no need to import the package, simply copy the code if of interest)

An option could be to propose an alternative style function.

Regards

**Comment by ddsjoberg** [comment]
Thanks @larmarange !

I not all the percentages are sounded in an env where we expect the sum to be one, so this would require some larger changes. But when I get to it, i'll certainly take a look!

**Comment by larmarange** [comment]
Thanks @ddsjoberg 

Just for your information, the vector doesn't have to sum to 1. It will preserve any sum, as long as all values are provided together to the function.

```
> x <- c(1.2, 1.9, 2.3, 5.6)
> sum(x)
[1] 11
> round_preserve_sum(x)
[1] 1 2 2 6
> round_preserve_sum(x) |> sum()
[1] 11
```

**Comment by ddsjoberg** [comment]
Maybe something like this would work

``` r
round2 <- function(x, digits = 0) {
  round(abs(x) + sqrt(.Machine$double.eps), digits = digits) * sign(x)
}
vv <- c(0.5, -0.5)
round(vv)
#> [1] 0 0
round2(vv)
#> [1]  1 -1
```

<sup>Created on 2022-02-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
