### ISSUE TITLE
Add option to specify n digits with `add_ci()`

### ISSUE THREAD

**Issue by rmgpanw** [ddsjoberg/gtsummary#1141]
Thanks for this amazing package. Would it be possible to add the option to specify the number of digits to display for confidence intervals? 

In the example below, I would like 1 digit after the decimal place for all percentages, and 2 digits for continuous variables. Thanks!

``` r
library(gtsummary)
#> Warning: package 'gtsummary' was built under R version 4.1.2
library(magrittr)

iris %>% 
  tbl_summary(statistic = list(gtsummary::all_continuous() ~ "{mean}\n({sd}",
                               gtsummary::all_categorical() ~ "{n}\n({p}%"),
              digits = list(gtsummary::all_categorical() ~ c(0, 1))) %>% 
  add_ci(pattern = "{stat}; {ci})")
```

<div id="oezsupdbjc" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>N = 150</strong>; <strong>95% CI</strong>)<sup class="gt_footnote_marks">1,2</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Sepal.Length</td>
<td class="gt_row gt_center">5.84
(0.83; 5.7, 6.0)</td></tr>
    <tr><td class="gt_row gt_left">Sepal.Width</td>
<td class="gt_row gt_center">3.06
(0.44; 3.0, 3.1)</td></tr>
    <tr><td class="gt_row gt_left">Petal.Length</td>
<td class="gt_row gt_center">3.76
(1.77; 3.5, 4.0)</td></tr>
    <tr><td class="gt_row gt_left">Petal.Width</td>
<td class="gt_row gt_center">1.20
(0.76; 1.1, 1.3)</td></tr>
    <tr><td class="gt_row gt_left">Species</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">setosa</td>
<td class="gt_row gt_center">50
(33.3%; 26%, 42%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">versicolor</td>
<td class="gt_row gt_center">50
(33.3%; 26%, 42%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">virginica</td>
<td class="gt_row gt_center">50
(33.3%; 26%, 42%)</td></tr>
  </tbody>
 

<sup>Created on 2022-02-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
In this case, you'll use the `style_fun=` argument to pass a function to round the statistics.
https://www.danieldsjoberg.com/gtsummary/reference/add_ci.html

**Comment by rmgpanw** [comment]
Apologies, thanks I see now:

``` r
library(gtsummary)
#> Warning: package 'gtsummary' was built under R version 4.1.2
library(magrittr)

style_percent_1digits <- purrr::partial(gtsummary::style_percent, digits = 1)
style_number_2digits <- purrr::partial(gtsummary::style_number, digits = 2)

iris %>% 
  tbl_summary(statistic = list(gtsummary::all_continuous() ~ "{mean}\n({sd}",
                               gtsummary::all_categorical() ~ "{n}\n({p}%"),
              digits = list(gtsummary::all_categorical() ~ c(0, 1))) %>% 
  add_ci(pattern = "{stat}; {ci})", 
         style_fun = list("Species" ~ style_percent_1digits,
                          "Sepal.Length" ~ style_number_2digits))
```


<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>N = 150</strong>; <strong>95% CI</strong>)<sup class="gt_footnote_marks">1,2</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Sepal.Length</td>
<td class="gt_row gt_center">5.84
(0.83; 5.71, 5.98)</td></tr>
    <tr><td class="gt_row gt_left">Sepal.Width</td>
<td class="gt_row gt_center">3.06
(0.44; 3.0, 3.1)</td></tr>
    <tr><td class="gt_row gt_left">Petal.Length</td>
<td class="gt_row gt_center">3.76
(1.77; 3.5, 4.0)</td></tr>
    <tr><td class="gt_row gt_left">Petal.Width</td>
<td class="gt_row gt_center">1.20
(0.76; 1.1, 1.3)</td></tr>
    <tr><td class="gt_row gt_left">Species</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">setosa</td>
<td class="gt_row gt_center">50
(33.3%; 26.0%, 41.6%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">versicolor</td>
<td class="gt_row gt_center">50
(33.3%; 26.0%, 41.6%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">virginica</td>
<td class="gt_row gt_center">50
(33.3%; 26.0%, 41.6%)</td></tr>
  </tbody>
  

<sup>Created on 2022-02-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
great!

**Comment by rmgpanw** [comment]
Following on from above, I get an error when I try to use `all_continuous()` or `all_categorical()` with `style_fun`:

``` r
library(gtsummary)
#> Warning: package 'gtsummary' was built under R version 4.1.2
#> #BlackLivesMatter
library(magrittr)


iris %>% 
  tbl_summary(statistic = list(gtsummary::all_continuous() ~ "{mean}\n({sd}",
                               gtsummary::all_categorical() ~ "{n}\n({p}%"),
              digits = list(gtsummary::all_categorical() ~ c(0, 1))) %>% 
  add_ci(pattern = "{stat}; {ci})", 
         style_fun = list(gtsummary::all_categorical() ~ style_percent_1digits,
                          gtsummary::all_continuous() ~ style_number_2digits))
#> x Cannot use selector 'all_categorical()' in this context.
#> Error: Error in `style_fun=` argument input. Select from 'Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width', 'Species'
```

<sup>Created on 2022-02-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

In the documentation it states that the default for `style_fun` is `list(all_categorical() ~ purrr::partial(style_sigfig, scale = 100), all_continuous() ~ style_sigfig)`, so I thought I would be able to do the same. Am I doing something wrong?

**Comment by ddsjoberg** [comment]
Thank you so much for letting me know! Can you try again using the dev version of the package?

**Comment by rmgpanw** [comment]
Thanks - this works now!

``` r
library(gtsummary)
#> #BlackLivesMatter
library(magrittr)

style_percent_1digits <- purrr::partial(gtsummary::style_percent, digits = 1)
style_number_2digits <- purrr::partial(gtsummary::style_number, digits = 2)

iris %>% 
  tbl_summary(statistic = list(gtsummary::all_continuous() ~ "{mean}\n({sd}",
                               gtsummary::all_categorical() ~ "{n}\n({p}%"),
              digits = list(gtsummary::all_categorical() ~ c(0, 1))) %>% 
  add_ci(pattern = "{stat}; {ci})", 
         style_fun = list(gtsummary::all_categorical() ~ style_percent_1digits,
                          gtsummary::all_continuous() ~ style_number_2digits))
```

<div id="hjhngjogcp" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>N = 150</strong>; <strong>95% CI</strong>)<sup class="gt_footnote_marks">1,2</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Sepal.Length</td>
<td class="gt_row gt_center">5.84
(0.83; 5.71, 5.98)</td></tr>
    <tr><td class="gt_row gt_left">Sepal.Width</td>
<td class="gt_row gt_center">3.06
(0.44; 2.99, 3.13)</td></tr>
    <tr><td class="gt_row gt_left">Petal.Length</td>
<td class="gt_row gt_center">3.76
(1.77; 3.47, 4.04)</td></tr>
    <tr><td class="gt_row gt_left">Petal.Width</td>
<td class="gt_row gt_center">1.20
(0.76; 1.08, 1.32)</td></tr>
    <tr><td class="gt_row gt_left">Species</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">setosa</td>
<td class="gt_row gt_center">50
(33.3%; 26.0%, 41.6%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">versicolor</td>
<td class="gt_row gt_center">50
(33.3%; 26.0%, 41.6%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">virginica</td>
<td class="gt_row gt_center">50
(33.3%; 26.0%, 41.6%)</td></tr>
  </tbody>

<sup>Created on 2022-02-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
