### ISSUE TITLE
Feature request: <Set Min/Max values to display for odds ratios/estimates for tbl_uvregression()>

### ISSUE THREAD

**Issue by RiversPharmD** [ddsjoberg/gtsummary#1147]
**Is your feature request related to a problem? Please describe.**
Stacked UV regression results can be hard to interpret when the SE and point estimate for one parameter is large. (https://stackoverflow.com/questions/65484295/problem-with-95-ci-output-gtsummary-package-in-r/65485281#65485281) The suggestion from @ddsjoberg here to set to scientific notation is nice, but that notation can be overwhelming/hard to digest.

**Describe the solution you'd like**
A helper function or parameter that takes a min and a max value to display and returns those values when the OR or Estimate value is outside the boundary. Something like: style_ratio_bounds(est_mn = 0.001, est_max = 100) which when applied to an output like this (Beta: 0.01, 95% CI: 0.0000000001-0.9) results in (Beta: 0.01, 95% CI <0.001-0.9). In a perfect world, this would automatically add a footnote to the table that it was capped.

**Describe alternatives you've considered**
Alternatives include documentation in the style_ratio() function for how to achieve this when individuals are codingly challenged, or a helper function that removes parameters from the stacked table if the number of digits in the estimate or odds ratio exceed a set value. The first alternative feels like it requires more work and introduces more chances for error in code. The helper function would be useful for report generation if the user was only interested in values with reasonable estimates or CIs, but would be challenging to use in a manuscript or report setting.

Thanks for considering this feature!

**Comment by ddsjoberg** [comment]
Hello @RiversPharmD ! Thanks for the suggestion.

First, let's review how you can make this work. Example below!

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.5.2'

bounded_style_ratio <- function(x, min = -Inf, max = Inf, ...) {
  dplyr::case_when(
    x < min ~ paste0("<", gtsummary::style_ratio(min, ...)), 
    x > max ~ paste0(">", gtsummary::style_ratio(max, ...)),
    TRUE ~ gtsummary::style_ratio(x, ...)
  )
}

bounded_style_ratio(c(0.2, 1.4, 6), min = 0.5, max = 3)
#> [1] "<0.50" "1.40"  ">3.00"

tbl <-
  glm(response ~ grade + trt, trial, family = binomial) %>%
  tbl_regression(
    exponentiate = TRUE,
    estimate_fun = purrr::partial(bounded_style_ratio, max = 2)
  ) %>%
  modify_footnote(c(estimate, ci) ~ "ORs larger than 2.00 shown as '>2.00'")
```
![image](https://user-images.githubusercontent.com/26774684/153232791-35319e32-ead6-47eb-9189-80b6fb20a109.png)

<sup>Created on 2022-02-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I don't know if we'll make this a top-level feature in the package. But it is possible to make this top level for you and your colleagues using gtsummary themes.
https://www.danieldsjoberg.com/gtsummary/articles/themes.html#writing-themes
You can use themes to make the bounded styling function above the default styler in regression tables. Using themes you can also auto-add the footnote to every `tbl_regression()` tables.

Will that work for you?

**Comment by RiversPharmD** [comment]
this will work great! I'll get the theme built and distributed to my team of one today. I appreciate your quick response!
