### ISSUE TITLE
Feature request: Cannot use selector 'all_categorical()' in this context. add_ci()

### ISSUE THREAD

**Issue by HichemLa** [ddsjoberg/gtsummary#1151]
Hi everyone,

I'm posting this for those who didn't find a solution to the following error message : : « Cannot use selector 'all_categorical()' in this context. » while using add_ci() from gtsummary package.

Here is a reproducible example of code : 

```
set.seed(124)
df = data.frame(cat= sample(c("YES","NO"), 10, replace=TRUE), num = rnorm(10, 0,1))

df %>% tbl_summary(statistic = list(all_continuous2() ~ c("{mean}", "{median}"), 
                                    all_categorical() ~ c("{n} / {N} ({p}%")),
                   digits = list(all_categorical() ~c(0,1), all_continuous() ~c(1,1))) %>%
                   add_ci(method = list(all_categorical() ~ "exact", all_continuous() ~ "t.test"))
```

In fact, the error message appeared when I changed default value in the method argument, passing from "list(all_categorical() ~ "**wilson**", all_continuous() ~ "t.test")" to list(all_categorical() ~ "**exact**", all_continuous() ~ "t.test") (see : https://www.danieldsjoberg.com/gtsummary/reference/add_ci.html).

After some mails with Joseph LARMARANGE, I found what was wrong. To solve this :

1. I had to reinstall rtools following this tutorial : https://cran.r-project.org/bin/windows/Rtools/rtools40.html, but there are many others so it is up to you.

2. I also reinstalled gtsummary with the following command : `remotes::install_github("ddsjoberg/gtsummary")`. And I got this message : 
```Downloading GitHub repo ddsjoberg/gtsummary@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                        
2: CRAN packages only         
3: None                       
4: cli (3.1.1 -> 3.2.0) [CRAN]
5: gt  (0.3.1 -> 0.4.0) [CRAN]
Enter one or more numbers, or an empty line to skip updates: 
```
At this point we can see that cli and gt packages were not updated. So, as suggested, I just entered "1" to update all of the indicated packages (ie gt and cli). After a couple of seconds, everything has been successfully installed. I can post downloading messages for those you are interested.

3. I tried to execute the same command in the above example, but this time I had this : 

```
set.seed(124)
> df = data.frame(cat= sample(c("YES","NO"), 10, replace=TRUE), num = rnorm(10, 0,1))
> df %>% tbl_summary(statistic = list(all_continuous2() ~ c("{mean}", "{median}"), 
+                                     all_categorical() ~ c("{n} / {N} ({p}%")),
+                    digits = list(all_categorical() ~c(0,1), all_continuous() ~c(1,1))) %>%
+   add_ci(method = list(all_categorical() ~ "exact", all_continuous() ~ "t.test"))
x The "Hmisc" package is required for function `add_ci(method = c("exact", "asymptotic"))`.
* Install "Hmisc" with the code below.
install.packages("Hmisc")
There was an error for variable 'cat':
Error in `mutate()`:
! Problem while computing `ci = calculate_prop_ci(...)`.
i The error occurred in row 1.
Caused by error:
! Install required package
x `add_ci()` added mean CI for "num"; however, no mean is shown in the `tbl_summary()` table.
```
So I just, installed the missing package "Hmisc" using this command `install.packages("Hmisc")`. And everything went well this time. The table had been generated successfully with the exact confidence interval / Clopper Pearson ci.
![image](https://user-images.githubusercontent.com/73237961/154106265-7bcf8533-5c62-49a4-94a9-5a65f622fe1a.png)

Hope it will help some of you folks !

**Comment by ddsjoberg** [comment]
Thank you @HichemLa for this post! This was a bug in the recent release that has been fix in the dev version of the package on GitHub.

I think for most users, simply installing the version from github will solve this bug. 💯
