### ISSUE TITLE
Bug Report: as_flex_table() error using p-value from svy.wald.test

### ISSUE THREAD

**Issue by jmbarajas** [ddsjoberg/gtsummary#1153]
Hi there,

I'm encountering an error when converting a `tbl_svysummary` object to a flextable using `as_flex_table()` when it has a p-value from the svy.wald.test. This seems to have broken between release 1.5.0 and 1.5.1. See reprexes below: the first code chunk works when outputting to html.

``` r
library(survey)
#> Loading required package: grid
#> Loading required package: Matrix
#> Loading required package: survival
#> 
#> Attaching package: 'survey'
#> The following object is masked from 'package:graphics':
#> 
#>     dotchart
library(gtsummary)

data(api)
dstrat<-svydesign(id=~1,strata=~stype, weights=~pw, data=apistrat, fpc=~fpc)

tbl_svysummary(dstrat,
               by = awards,
               include = c(api00, api99)) %>% 
  add_p(test = list(all_continuous() ~ "svy.wald.test"))
```

<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>No</strong>, N = 2,236<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Yes</strong>, N = 3,958<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong><sup class="gt_footnote_marks">2</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">api00</td>
<td class="gt_row gt_center">641 (528, 743)</td>
<td class="gt_row gt_center">671 (588, 765)</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">api99</td>
<td class="gt_row gt_center">636 (524, 724)</td>
<td class="gt_row gt_center">625 (526, 727)</td>
<td class="gt_row gt_center"><0.001</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><sup class="gt_footnote_marks">1</sup> Median (IQR)</td>
    </tr>
    <tr>
      <td class="gt_footnote" colspan="4"><sup class="gt_footnote_marks">2</sup> Wald test of independence for complex survey samples</td>
    </tr>
  </tfoot>
</table>
</div>

<sup>Created on 2022-02-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

But the second fails when converting.

``` r
library(survey)
#> Loading required package: grid
#> Loading required package: Matrix
#> Loading required package: survival
#> 
#> Attaching package: 'survey'
#> The following object is masked from 'package:graphics':
#> 
#>     dotchart
library(gtsummary)

data(api)
dstrat<-svydesign(id=~1,strata=~stype, weights=~pw, data=apistrat, fpc=~fpc)

tbl_svysummary(dstrat,
               by = awards,
               include = c(api00, api99)) %>% 
  add_p(test = list(all_continuous() ~ "svy.wald.test")) %>% 
  as_flex_table()
#> Error:
#> ! Assigned data `df_updated` must be compatible with existing data.
#> i Error occurred for column `p.value`.
#> x Can't convert <character[,1]> to <character>.
#> Cannot decrease dimensions.
```

<sup>Created on 2022-02-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The error doesn't occur with the default Wilcoxon rank sum test. The code appears to be choking because the p-value is stored as matrix rather than a single numeric value, but I don't know what change was introduced to cause the bug.

**Comment by ddsjoberg** [comment]
Thank you for letting me know! The p-value column was being saved as a nX1 matrix in the data frame, as opposed to a numeric vector. I'll need to fix that, but in the meantime, you can use the code below to get a working table.

``` r
library(gtsummary)

data(api, package = "survey")
dstrat <- survey::svydesign(id=~1,strata=~stype, weights=~pw, data=apistrat, fpc=~fpc)

tbl <- 
  tbl_svysummary(
    dstrat,
    by = awards,
    include = c(api00, api99)
  ) %>% 
  add_p(test = list(all_continuous() ~ "svy.wald.test")) %>%
  # convert these columns to numeric vectors (somehow was stored as a nX1 matrix)
  modify_table_body(
    ~.x %>% dplyr::mutate(dplyr::across(c(statistic, p.value), as.numeric))
  )

as_flex_table(tbl)
```
![image](https://user-images.githubusercontent.com/26774684/154187012-7005711e-b865-42b6-9ed7-8c178101ee6e.png)

<sup>Created on 2022-02-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
Issue submitted to the broom package https://github.com/tidymodels/broom/issues/1081

**Comment by jmbarajas** [comment]
Thanks for the workaround and upcoming fix!
