### ISSUE TITLE
Bug Report: `tbl_butcher` reduces object size, but `saveRDS` still creates large files

### ISSUE THREAD

**Issue by rmgpanw** [ddsjoberg/gtsummary#1158]
Hi! I really like the option to reduce the size of large `tbl_regression` objects with `tbl_butcher`, however I am finding that when saving a (small) 'butchered' object, the resultant .rds file becomes large if the original model was large. Please see reprex below

Is there a way for `tbl_butcher` to prevent this from happening when using `saveRDS`? Many thanks!

``` r
library(gtsummary)
library(magrittr)

# lm object - large
iris_lm <- lm(Sepal.Length ~ ., data = purrr::map_df(iris, ~ rep(.x, 1000)))
format(object.size(iris_lm), units = "Mb")
#> [1] "44.1 Mb"

# tbl_regression object - larger
tbl_reg_iris_lm <- tbl_regression(iris_lm)
format(object.size(tbl_reg_iris_lm), units = "Mb")
#> [1] "89.3 Mb"

# butchered tbl_regression object - small
tbl_reg_iris_lm_butchered <- tbl_butcher(tbl_reg_iris_lm)
format(object.size(tbl_reg_iris_lm_butchered), units = "Mb")
#> [1] "0.8 Mb"

# save to tempdir
temp_file <- tempfile()
saveRDS(tbl_reg_iris_lm_butchered, file = temp_file)

# RDS file size (in Mb) - larger than butchered tbl_regression object
file.size(temp_file) / 1000000
#> [1] 15.77227

# re-loaded tbl_regression object - (still) small
tbl_reg_iris_lm_butchered_reloaded <- readRDS(temp_file)
format(object.size(tbl_reg_iris_lm_butchered_reloaded), units = "Mb")
#> [1] "0.8 Mb"

# print
tbl_reg_iris_lm_butchered_reloaded
```

<div id="aziknkbsug" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Sepal.Width</td>
<td class="gt_row gt_center">0.50</td>
<td class="gt_row gt_center">0.49, 0.50</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Petal.Length</td>
<td class="gt_row gt_center">0.83</td>
<td class="gt_row gt_center">0.83, 0.83</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Petal.Width</td>
<td class="gt_row gt_center">-0.32</td>
<td class="gt_row gt_center">-0.32, -0.31</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Species</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">setosa</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">versicolor</td>
<td class="gt_row gt_center">-0.72</td>
<td class="gt_row gt_center">-0.74, -0.71</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">virginica</td>
<td class="gt_row gt_center">-1.0</td>
<td class="gt_row gt_center">-1.0, -1.0</td>
<td class="gt_row gt_center"><0.001</td></tr>
  </tbody>
  
 
</table>
</div>

<sup>Created on 2022-02-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
Thanks for the post @rmgpanw . I am not sure what to tell you. I don't know the ins and outs of `saveRDS()`. Do you have a proposed solution?

**Comment by rmgpanw** [comment]
No unfortunately I do not, sorry. I am currently working with a large regression object that shrinks nicely to just a few Mb with `tbl_butcher()`, but saves as a >10GB rds file.

I appreciate that this is really an issue with `saveRDS()` than `tbl_butcher()`, but thought I'd post here anyhow in case others were also hoping to use `tbl_butcher()` to create small objects for saving as rds (and in case you/others may have a potential solution!)

**Comment by ddsjoberg** [comment]
I would guess that the size of the un-butchered saved file is larger? I can imagine that saving any R object will be larger after saved to a file.
