### ISSUE TITLE
Bug Report: stratified tables with tbl_svysummary() not always working

### ISSUE THREAD

**Issue by aspina7** [ddsjoberg/gtsummary#1166]
hi folks - I might be getting things entirely wrong here, but tbl_svysummary() throws an error if I try to create a grouped table (using `by = `) when the grouping variable of interest is the `strata` variable in the survey design. 
Context: for a stratified survey (say e.g. want to get the percentage of people vaccinated in two different regions of the same district - or say two subdivisions of a refugee camp) - we would take an appropriate sample from each strata, then the survey design would include the regions as the stratifying variable, and then we would be able to calculate stratified estimates for each region using the `by` argument (as well as being able to calculate an appropriately weighted overall estimate when not using `by`). 
An example below comparing to {survey} and {srvyr} outputs below using the api dataset. (Example 1)
As well as an example of the original error that was thrown. (Example 2)
(Sorry is not a full reprex - markdown formatting messes up the output)

Also sorry for lengthy post but just trying to explain as much as possible - thanks a lot for all the work you do on this package! 

- In example 1, things work when I use {srvyr} to select variables in advance of `tbl_svysummary()` and outputs are the same as when using only {survey} functions;  but the error I get from `survey_design %>% tbl_svysummary(by = "stype", include = c(both, stype))` is: 
```r
Error in `by=` argument input. Select from ‘cds’, ‘name’, ‘sname’, ‘snum’, ‘dname’, ‘dnum’, ‘cname’, ‘cnum’, ‘flag’, ‘pcttest’, ‘api00’, ‘api99’, ‘target’, ‘growth’, ‘sch.wide’, ‘comp.imp’, ‘both’, ‘awards’, ‘meals’, ‘ell’, ‘yr.rnd’, ‘mobility’, ‘acs.k3’, ‘acs.46’, ‘acs.core’, ‘pct.resp’, ‘not.hsg’, ‘hsg’, ‘some.col’, ‘col.grad’, ‘grad.sch’, ‘avg.ed’, ‘full’, ‘emer’, ‘enroll’, ‘api.stu’
```
- In example 2 when running `survey_design %>%  select(died, health_district) %>%  tbl_svysummary(by = died)` I get the following error, but the other methods seem to work fine: 
```r
Error: Problem with `mutate()` column `stat_label`.
i `stat_label = stat_label_match(.data$stat_display)`.
x Column `stat` not found in `.data`
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
x
+-<error/dplyr:::mutate_error>
| Problem with `mutate()` column `stat_label`.
| i `stat_label = stat_label_match(.data$stat_display)`.
| x Column `stat` not found in `.data`
\-<error/rlang_error_data_pronoun_not_found>
  Column `stat` not found in `.data`
Backtrace:
  1. survey_design %>% select(died, health_district) %>% tbl_svysummary(by = died)
 27. rlang:::abort_data_pronoun(x)
Run `rlang::last_trace()` to see the full context.
```

-----------------------------------------------------------------------

```r
## install extra packages from github (for example 2)
# remotes::install_github("R4EPI/epitabulate")
# remotes::install_github("R4EPI/epidict")
# remotes::install_github("R4EPI/epikit")

## load packages
library("dplyr")       # for wrangling
library("epitabulate") # for dplyr wrappers of survey package
library("epidict")     # for fake datasets
library("epikit")      # for calculating weights
library("survey")      # for survey functions
library("srvyr")       # dplyr wrapper for survey package
library("gtsummary")   # produce tables)



## EXAMPLE 1

    
    
# A dataset with a complex design
data(api, package = "survey")

## define a survey object from stratified
survey_design <- survey::svydesign(id=~1,strata=~stype, weights=~pw, data=apistrat, fpc=~fpc)

## make {srvyr} object for reference
survey_design_srvyr <- srvyr::as_survey(survey_design)


## calculate proportions using {survey} object and {gtsummary}
survey_design %>%
  tbl_svysummary(by = "stype", include = c(both, stype))

## calculate proportions using {srvyr} object and {gtsummary}
survey_design_srvyr %>%
  select(both, stype) %>%
  tbl_svysummary(by = "stype")

## calculate proportions using {srvyr} object and {epitabulate}
survey_design_srvyr %>%
  tab_survey(both, strata = stype)

## calculate proportions using {survey} object and {survey} funs
svyby(~both, by = ~ stype, FUN = svyciprop, design = survey_design, vartype = "ci")





##  EXAMPLE 2


## creating fake data, population and cluster counts

## generates a fake dataset for use as an example
study_data_cleaned <- epidict::gen_data(dictionary = "Mortality",
                           varnames   = "name",
                           numcases   = 1000)


## create an age group variable by specifying categorical breaks (of years)
study_data_cleaned <- study_data_cleaned %>%
  mutate(age_group = age_categories(age_years,
                                    breakers = c(0, 3, 15, 30, 45)
  ))


## create a character variable based off groups of a different variable
study_data_cleaned <- study_data_cleaned %>%
  mutate(health_district = case_when(
    cluster_number %in% c(1:5) ~ "district_a",
    TRUE ~ "district_b"
  ))

## generate population data by age groups in years for district A
population_data_age_district_a <- gen_population(total_pop = 10000, # set total population
                                                 groups      = c("0-2", "3-14", "15-29", "30-44", "45+"), # set groups
                                                 proportions = c(0.0340, 0.1811, 0.1380, 0.0808, 0.0661), # set proportions for each group
                                                 strata      = c("male", "female")) %>%           # stratify by gender
  rename(age_group  = groups,                      # rename columns (NEW NAME = OLD NAME)
         sex        = strata,
         population = n) %>%
  mutate(health_district = "district_a")           # add a column to identify region


## generate population data by age groups in years for district B
population_data_age_district_b <- gen_population(total_pop = 10000, # set total population
                                                 groups      = c("0-2", "3-14", "15-29", "30-44", "45+"), # set groups
                                                 proportions = c(0.0340, 0.1811, 0.1380, 0.0808, 0.0661), # set proportions for each group
                                                 strata      = c("male", "female")) %>%           # stratify by gender
  rename(age_group  = groups,                      # rename columns (NEW NAME = OLD NAME)
         sex        = strata,
         population = n) %>%
  mutate(health_district = "district_b")           # add a column to identify region



## bind region population data together to get overall population
population_data_age <- bind_rows(population_data_age_district_a,
                                 population_data_age_district_b)


## create fake cluster countss
cluster_counts <- tibble(cluster = c("village_1", "village_2", "village_3", "village_4",
                                     "village_5", "village_6", "village_7", "village_8",
                                     "village_9", "village_10"),
                         households = c(700, 400, 600, 500, 300,
                                        800, 700, 400, 500, 500))

## adding survey weights

## get the number of people of individuals interviewed per household
## adds a variable with counts of the household (parent) index variable
study_data_cleaned <- study_data_cleaned %>%
  add_count(index, name = "interviewed")


## create a variable called "surv_weight_strata"
## contains weights for each individual - by age group, sex and health district
study_data_cleaned <- add_weights_strata(x = study_data_cleaned,
                                         p = population_data_age,
                                         surv_weight = "surv_weight_strata",
                                         surv_weight_ID = "surv_weight_ID_strata",
                                         age_group, sex, health_district)

## create cluster weights
study_data_cleaned <- add_weights_cluster(x = study_data_cleaned,
                                          cl = cluster_counts,
                                          eligible = member_number,
                                          interviewed = interviewed,
                                          cluster_x = village_name,
                                          cluster_cl = cluster,
                                          household_x = index,
                                          household_cl = households,
                                          surv_weight = "surv_weight_cluster",
                                          surv_weight_ID = "surv_weight_ID_cluster",
                                          ignore_cluster = FALSE,
                                          ignore_household = FALSE)

## create a survey weight for cluster and strata
study_data_cleaned <- study_data_cleaned %>%
  mutate(surv_weight_cluster_strata = surv_weight_strata * surv_weight_cluster)

## drop missing weights
study_data_cleaned <- study_data_cleaned %>%
  filter(!is.na(surv_weight_cluster_strata))


## create a srvyr object for a stratified cluster survey
survey_design <- study_data_cleaned %>%
  as_survey_design(ids = village_name, # cluster ids
                   weights = surv_weight_cluster_strata, # weight variable created above
                   strata = health_district # sampling was stratified by district
  )


## make died in to a TRUE/FALSE variable (because {survey} doesnt accept chars)
survey_design <- survey_design %>%
  mutate(died = died == "yes")


## calculate proportions using {survey} object and {survey} funs
svyby(~died, by = ~health_district, FUN = svyciprop, design = survey_design, vartype = "ci")


## calculate proportions using {srvyr} object and {epitabulate}
tab_survey(survey_design, died,
           strata = health_district,
           deff = TRUE)

## calculate proportions with {srvyr} object and {gtsummary}
survey_design %>%
  select(died, health_district) %>%
  tbl_svysummary(by = died)

```

**Comment by ddsjoberg** [comment]
The design columns are excluded from the list of variables that can be used in `tbl_svysummary()`, which is why you're seeing the error. For now, you can create a copy of the strata column in your dataset and use the copy as a summary variable.

Can you confirm the strata column can be used in `svyby()` to calculate summary stats? I can foresee potential issues including the design variables in the summary tables (including incorrect summaries). But would need to look into the details

**Comment by aspina7** [comment]
yeap can confirm that `svyby()` works, and `tbl_svysummary()` works too if used in combination with {srvyr}. 
I don't think it would produce incorrect summaries if used as the grouping variable - I might be wrong though

**Comment by ddsjoberg** [comment]
Thanks for checking @aspina7 !

For now, I think we'll continue to omit design columns from the summary tables. When needed, you can make a copy of the column.

@larmarange if you disagree, please do chime in here.

**Comment by larmarange** [comment]
Hi

Sorry for not having reacted before. 

For stratified surveys, it is not uncommon to report statistics by strata. On the contrary, it is sometimes important as strata are important variables for those we want to improve representativeness. For example, many big surveys are stratified by region or residency. Statistically it is not a problem and the survey package will handle it properly.

Reporting statistics by cluster is less common as they are often a high number of clusters but in surveys with few clusters, once again it could be relevant to present summary statistics by cluster, and once again it will be handled by survey property.

Therefore, I'm not sure it is relevant to exclude design columns from tbl_svysummary and I guess that other users will ask to be able to include such variables.

Best regards

**Comment by ddsjoberg** [comment]
Thanks @larmarange !

What do you think the best implementation is?
1. Simply, make the columns available. The downside is that this would change the default table for users (`include = everything()`), by adding the new design columns to the summary table. (breaking change for some)
2. Add a new selector, `all_svy_design_cols()`, and update the default value to `include = c(everything(), -all_svy_design_cols())`
3. Something else?

**Comment by larmarange** [comment]
In the long term, I would say that the first option is the simplest. These variables are any way variables of the survey data.frame. Logically, they should be part of `everything()`.

I understand that it could be for some a minor breaking change, although for big surveys you usually have to be more specific in `include` due to the high number of variables that dataset usually have.

I do not think it will impact to much users.

Therefore, my personal preference would be option 1, the simplest one, avoiding adding complexity with new selectors.

@aspina7 do you have any preference?

**Comment by aspina7** [comment]
Actually it should be fine because they effectively remain as a tibble (with the design variables in there) and can use tidy selectors (as seen in example 1 above) - I guess you could add that to testing?

**Comment by larmarange** [comment]
I do not see any potential issue. I guess that you are referring to a use case when you apply `select()` and do not retain strata or clusters variables.

In a survey object, strata and clusters variables are already internally duplicated by `survey` in `x$strata` and `x$clusters` and could therefore be removed from the data frame itself stored in `x$variables`. 

`everything()` should refer to variables stored in `x$variables`. And users still have the option to remove design variables with a select (this is ok because they are still internally stored).

Therefore, I suggest to remove https://github.com/ddsjoberg/gtsummary/blob/0a97bc1b9fd980420fa14ba702b8af736af77b65/R/tbl_svysummary.R#L620 condition and to keep only

https://github.com/ddsjoberg/gtsummary/blob/0a97bc1b9fd980420fa14ba702b8af736af77b65/R/tbl_svysummary.R#L627

``` r
library(srvyr)
#> 
#> Attachement du package : 'srvyr'
#> L'objet suivant est masqué depuis 'package:stats':
#> 
#>     filter
library(survey)
#> Le chargement a nécessité le package : grid
#> Le chargement a nécessité le package : Matrix
#> Le chargement a nécessité le package : survival
#> 
#> Attachement du package : 'survey'
#> L'objet suivant est masqué depuis 'package:graphics':
#> 
#>     dotchart
library(gtsummary)

data(api)

d <- apistrat %>%
  as_survey(strata = stype, weights = pw)

d2 <- d  %>% 
  select(sch.wide, api99)

d2$variables %>% head()
#> # A tibble: 6 x 2
#>   sch.wide api99
#>   <fct>    <int>
#> 1 Yes        816
#> 2 Yes        476
#> 3 No         544
#> 4 Yes        457
#> 5 Yes        659
#> 6 Yes        780

d2$strata %>% head()
#>   stype
#> 1     E
#> 2     E
#> 3     E
#> 4     E
#> 5     E
#> 6     E

d2 %>% tbl_svysummary() %>% as_kable()
```

| **Characteristic** | **N = 6,194**  |
|:-------------------|:--------------:|
| sch.wide           |  5,128 (83%)   |
| api99              | 631 (525, 727) |

<sup>Created on 2022-03-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by larmarange** [comment]
I users want to remove weighting, cluster or strata variables, we should let them do it explicitely.
