### ISSUE TITLE
Allow multiple cross tables with one-line code function with gtsummary

### ISSUE THREAD

**Issue by aito123** [ddsjoberg/gtsummary#1186]
Hello, i wanted to suggest to implement a new function in gtsummary that allows you to create a frequency table with multiple crosstabs. This is important because having multiple crosstabs altogether allows you to observe insights from the beginning. Happily, the code solution has already been resolved in the slack channel R4DS Community and i wanted to repost it here. Hopefully it can be implemented in a newer version of gtsummary. Regards.

Ps. The second approach lets you select the cross variable by number position really useful.

**June C approach**

```{r}
library(tidyverse)
library(gt)
library(gtsummary)

fn_subtable <- function(data, main, sub){
  data %>% 
    dplyr::select({{main}},{{sub}}) %>% 
    gtsummary::tbl_summary(
      by = {{sub}}, 
      statistic = gtsummary::all_categorical()~ "{p}% ({n})",
      digits = list(dplyr::everything() ~ c(2, 0)))
  
}

fn_table3 <- function(data, main_var, sub_vars){
  
  main_var <- rlang::enexpr(main_var)
  sub_vars_expr <- rlang::enexpr(sub_vars)         # 1. Capture `list(...)` call as expression
  sub_vars_args <- rlang::call_args(sub_vars_expr) # 2. Pull out the arguments (they're now also exprs)
  sub_vars_fn   <- rlang::call_fn(sub_vars_expr)   # 3. Pull out the fn call
  # 4. Evaluate the fn with expr-ed arguments (this becomes `list( expr(agegp), expr(alcgp) )` )
  sub_vars_reconstructed <- rlang::exec(sub_vars_fn, !!!sub_vars_args)
  
  # --- sub_vars replaced with sub_vars_reconstructed from here onwards ---
  
  t0 <- data %>% 
    dplyr::select({{main_var}}) %>% 
    gtsummary::tbl_summary(statistic = gtsummary::all_categorical() ~ "{p}% ({n})",
                           digits = list(dplyr::everything() ~ c(2, 0))) %>%
    gtsummary::modify_header(label ~ "") %>% 
    gtsummary::bold_labels()
  
  sub_tables <- purrr::map(sub_vars_reconstructed, ~fn_subtable(data = data, main = main_var, sub = .x))
  
  tbls <-  c(list(t0), sub_tables) %>% 
    gtsummary::tbl_merge(tab_spanner = c("**Total**", paste0("**",sub_vars_reconstructed,"**"))) %>%
    gtsummary::as_gt() %>% 
    gt::tab_source_note(gt::md("*Fuente: Empresa1*"))
  
  tbls
  
}

fn_table3(esoph,tobgp,list(agegp,alcgp))
fn_table3(esoph,tobgp,c(agegp,alcgp))
```
**Tyler Grant Smith approach**

```{r}
fn_table3 <- function(data, main_var, sub_vars){
  
  main_var <- rlang::enexpr(main_var)
  # sub_vars_expr <- rlang::enexpr(sub_vars)
  
  sub_vars <- tidyselect::eval_select(enquo(sub_vars), data[unique(names(data))])
  sub_vars <- names(sub_vars)
  sub_vars <- rlang::syms(sub_vars)
  
  # --- sub_vars replaced with sub_vars_reconstructed from here onwards ---
  
  t0 <- data %>% 
    dplyr::select({{main_var}}) %>% 
    gtsummary::tbl_summary(statistic = gtsummary::all_categorical() ~ "{p}% ({n})",
                           digits = list(dplyr::everything() ~ c(2, 0))) %>%
    gtsummary::modify_header(label ~ "") %>% 
    gtsummary::bold_labels()
  
  sub_tables <- purrr::map(sub_vars, ~fn_subtable(data = data, main = main_var, sub = .x))
  
  tbls <-  c(list(t0), sub_tables) %>% 
    gtsummary::tbl_merge(tab_spanner = c("**Total**", paste0("**",sub_vars,"**"))) %>%
    gtsummary::as_gt() %>% 
    gt::tab_source_note(gt::md("*Fuente: Empresa1*"))
  
  tbls
}

fn_table3(esoph,tobgp,c(agegp,alcgp))

# can also use numeric column identifiers now
fn_table3(esoph,tobgp,c(1,2))
```

**Comment by ddsjoberg** [comment]
HI @aito123 , thanks for the post.

I am not sure if I"ll add a new function for this. I"ve included a somewhat simpler implementation below. You can create a couple of cross tabs and merge them. I can't expand `tbl_cross()` to accept more than one column variable because of the implications for other functions/methods like `add_p.tbl_cross()`. Also, it'll be one more function to continue to maintain, and maintenance is actually a big job by itself!

``` r
library(gtsummary)
#> #BlackLivesMatter
packageVersion("gtsummary")
#> [1] '1.5.2'

tbl_wide_cross <- function(data, row, columns) {
  purrr::map(
    columns, 
    ~tbl_cross(data = data, row = all_of(row), col = all_of(.x), margin = NULL)
  ) %>%
    tbl_merge(tab_spanner = FALSE)
}

tbl <-
  tbl_wide_cross(data = trial, row = "response",  columns = c("trt", "grade"))
```
![image](https://user-images.githubusercontent.com/26774684/160455720-30638d29-b552-4d3f-989b-fb765b9c32f2.png)

<sup>Created on 2022-03-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by aito123** [comment]
> HI @aito123 , thanks for the post.
> 
> I am not sure if I"ll add a new function for this. I"ve included a somewhat simpler implementation below. You can create a couple of cross tabs and merge them. I can't expand `tbl_cross()` to accept more than one column variable because of the implications for other functions/methods like `add_p.tbl_cross()`. Also, it'll be one more function to continue to maintain, and maintenance is actually a big job by itself!
> 
> ```r
> library(gtsummary)
> #> #BlackLivesMatter
> packageVersion("gtsummary")
> #> [1] '1.5.2'
> 
> tbl_wide_cross <- function(data, row, columns) {
>   purrr::map(
>     columns, 
>     ~tbl_cross(data = data, row = all_of(row), col = all_of(.x), margin = NULL)
>   ) %>%
>     tbl_merge(tab_spanner = FALSE)
> }
> 
> tbl <-
>   tbl_wide_cross(data = trial, row = "response",  columns = c("trt", "grade"))
> ```
> 
> ![image](https://user-images.githubusercontent.com/26774684/160455720-30638d29-b552-4d3f-989b-fb765b9c32f2.png)
> 
> Created on 2022-03-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)

Thanks Daniel for the response. Sure it must be hard to maintain a package as good as this. And i can imagine that you and your team are trying to make every function work in the ecosystem gtsummary and their function. Though let me know if you change your mind 😛
