### ISSUE TITLE
Feature request: Calculate precision estimates for proportions on survey objects

### ISSUE THREAD

**Issue by szimmer** [ddsjoberg/gtsummary#1187]
**Is your feature request related to a problem? Please describe.**
When calculating proportions (or percentages) from a survey, there is a standard error associated with that. This should be calculated in the survey package.

**Describe the solution you'd like**
Add the following statistics for categorical variables with suggested name:
- Standard error of the percentage: `p_se`

**Describe alternatives you've considered**
Currently, I do this in the srvyr package and then wrangle data to make a nice table using gt package. No current method directly available in gtsummary.

**Additional context**
Here's a very rough reprex of what output is expected.

``` r
data(api, package = "survey")
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tidyr)
library(gtsummary)
library(gt)

# Example from gtsummary documentation
data(api, package = "survey")
tbl_svysummary_ex2 <-
  survey::svydesign(id = ~dnum, weights = ~pw, data = apiclus1, fpc = ~fpc) %>%
  tbl_svysummary(by = "both", include = c(cname))

tbl_svysummary_ex2
```

<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>No</strong>, N = 1,692<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Yes</strong>, N = 4,502<sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">cname</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Alameda</td>
<td class="gt_row gt_center">68 (4.0%)</td>
<td class="gt_row gt_center">305 (6.8%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Fresno</td>
<td class="gt_row gt_center">0 (0%)</td>
<td class="gt_row gt_center">135 (3.0%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Kern</td>
<td class="gt_row gt_center">34 (2.0%)</td>
<td class="gt_row gt_center">34 (0.8%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Los Angeles</td>
<td class="gt_row gt_center">135 (8.0%)</td>
<td class="gt_row gt_center">372 (8.3%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Mendocino</td>
<td class="gt_row gt_center">135 (8.0%)</td>
<td class="gt_row gt_center">0 (0%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Merced</td>
<td class="gt_row gt_center">34 (2.0%)</td>
<td class="gt_row gt_center">102 (2.3%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Orange</td>
<td class="gt_row gt_center">102 (6.0%)</td>
<td class="gt_row gt_center">440 (9.8%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Plumas</td>
<td class="gt_row gt_center">169 (10%)</td>
<td class="gt_row gt_center">135 (3.0%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">San Diego</td>
<td class="gt_row gt_center">508 (30%)</td>
<td class="gt_row gt_center">1,354 (30%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">San Joaquin</td>
<td class="gt_row gt_center">372 (22%)</td>
<td class="gt_row gt_center">880 (20%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Santa Clara</td>
<td class="gt_row gt_center">135 (8.0%)</td>
<td class="gt_row gt_center">745 (17%)</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="3"><sup class="gt_footnote_marks">1</sup> n (%)</td>
    </tr>
  </tfoot>
</table>
</div>

```r
# Example with se of p

estlong <- apiclus1 %>%
  srvyr::as_survey_design(id = dnum, weights = pw, fpc = fpc) %>%
  group_by(both, cname) %>%
  summarise(
    p=srvyr::survey_prop(proportion = TRUE),
    .groups="drop"
  ) 

estlong
```
#> # A tibble: 20 x 4
#>    both  cname             p    p_se
#>    <fct> <chr>         <dbl>   <dbl>
#>  1 No    Alameda     0.0400  0.0419 
#>  2 No    Kern        0.0200  0.0214 
#>  3 No    Los Angeles 0.0800  0.0806 
#>  4 No    Mendocino   0.0800  0.0806 
#>  5 No    Merced      0.0200  0.0214 
#>  6 No    Orange      0.0600  0.0617 
#>  7 No    Plumas      0.100   0.0986 
#>  8 No    San Diego   0.300   0.176  
#>  9 No    San Joaquin 0.220   0.187  
#> 10 No    Santa Clara 0.0800  0.0662 
#> 11 Yes   Alameda     0.0677  0.0689 
#> 12 Yes   Fresno      0.0301  0.0318 
#> 13 Yes   Kern        0.00752 0.00810
#> 14 Yes   Los Angeles 0.0827  0.0713 
#> 15 Yes   Merced      0.0226  0.0240 
#> 16 Yes   Orange      0.0977  0.0964 
#> 17 Yes   Plumas      0.0301  0.0318 
#> 18 Yes   San Diego   0.301   0.179  
#> 19 Yes   San Joaquin 0.195   0.171  
#> 20 Yes   Santa Clara 0.165   0.111

```r
# Very rough example but note the standard erros of the p

estwide <-
  estlong %>%
  complete(both, cname) %>%
  replace_na(list(p=0)) %>%
  mutate(
    value=glue::glue("{format(p*100, digits=1)} ({format(p_se*100, digits=1)})")
  ) %>%
  pivot_wider(id_cols=cname, names_from=both, values_from=value) %>%
  gt() %>%
  tab_footnote("% (se)", locations=cells_column_labels(c("No", "Yes")))

estwide
```
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">cname</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">No<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">Yes<sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Alameda</td>
<td class="gt_row gt_center"> 4.0 ( 4.2)</td>
<td class="gt_row gt_center"> 6.8 ( 6.9)</td></tr>
    <tr><td class="gt_row gt_left">Fresno</td>
<td class="gt_row gt_center"> 0.0 (  NA)</td>
<td class="gt_row gt_center"> 3.0 ( 3.2)</td></tr>
    <tr><td class="gt_row gt_left">Kern</td>
<td class="gt_row gt_center"> 2.0 ( 2.1)</td>
<td class="gt_row gt_center"> 0.8 ( 0.8)</td></tr>
    <tr><td class="gt_row gt_left">Los Angeles</td>
<td class="gt_row gt_center"> 8.0 ( 8.1)</td>
<td class="gt_row gt_center"> 8.3 ( 7.1)</td></tr>
    <tr><td class="gt_row gt_left">Mendocino</td>
<td class="gt_row gt_center"> 8.0 ( 8.1)</td>
<td class="gt_row gt_center"> 0.0 (  NA)</td></tr>
    <tr><td class="gt_row gt_left">Merced</td>
<td class="gt_row gt_center"> 2.0 ( 2.1)</td>
<td class="gt_row gt_center"> 2.3 ( 2.4)</td></tr>
    <tr><td class="gt_row gt_left">Orange</td>
<td class="gt_row gt_center"> 6.0 ( 6.2)</td>
<td class="gt_row gt_center"> 9.8 ( 9.6)</td></tr>
    <tr><td class="gt_row gt_left">Plumas</td>
<td class="gt_row gt_center">10.0 ( 9.9)</td>
<td class="gt_row gt_center"> 3.0 ( 3.2)</td></tr>
    <tr><td class="gt_row gt_left">San Diego</td>
<td class="gt_row gt_center">30.0 (17.6)</td>
<td class="gt_row gt_center">30.1 (17.9)</td></tr>
    <tr><td class="gt_row gt_left">San Joaquin</td>
<td class="gt_row gt_center">22.0 (18.7)</td>
<td class="gt_row gt_center">19.5 (17.1)</td></tr>
    <tr><td class="gt_row gt_left">Santa Clara</td>
<td class="gt_row gt_center"> 8.0 ( 6.6)</td>
<td class="gt_row gt_center">16.5 (11.1)</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="3"><sup class="gt_footnote_marks">1</sup> % (se)</td>
    </tr>
  </tfoot>
</table>
</div>

<sup>Created on 2022-03-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
Thanks for the detailed post.

Is it possible to calculate the SE using the survey package instead of svryr?

**Comment by szimmer** [comment]
Yes, I can work on that example tomorrow. I tend to use srvyr so quicker to
make an example using that package

**Comment by larmarange** [comment]
This issue may be related to #965 (adding `add_ci()` method to `tbl_svysummary` objects).

For that request, you should first use `survey::svyciprop()` which computes variance and confidence intervals (several methods available) and then apply `survey::SE()` on the result to get the standard deviation.

Therefore, a possible solution could be to develop `add_ci()` method for `tbl_svysummary` objects and to allow the possibility of using `{se}` in the statistic of the method.

``` r
library(survey)
#> Le chargement a nécessité le package : grid
#> Le chargement a nécessité le package : Matrix
#> Le chargement a nécessité le package : survival
#> 
#> Attachement du package : 'survey'
#> L'objet suivant est masqué depuis 'package:graphics':
#> 
#>     dotchart
data(api)
dclus1 <- svydesign(id=~dnum, fpc=~fpc, data=apiclus1)

p <- svyciprop(~I(ell==0), dclus1, method="li")
p
#>                          2.5% 97.5%
#> I(ell == 0) 0.021858 0.000664  0.11
str(p)
#>  'svyciprop' Named num 0.0219
#>  - attr(*, "names")= chr "I(ell == 0)"
#>  - attr(*, "var")= num [1, 1] 0.000512
#>   ..- attr(*, "dimnames")=List of 2
#>   .. ..$ : chr "as.numeric(I(ell == 0))"
#>   .. ..$ : chr "as.numeric(I(ell == 0))"
#>  - attr(*, "ci")= Named num [1:2] 0.000664 0.107778
#>   ..- attr(*, "names")= chr [1:2] "2.5%" "97.5%"
SE(p)
#> as.numeric(I(ell == 0)) 
#>              0.02262245
```

<sup>Created on 2022-03-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by szimmer** [comment]
OK, this uncovered a bug (I think) in the survey package but here's an example:

``` r
data(api, package = "survey")
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tidyr)

des <- survey::svydesign(id = ~dnum, weights = ~pw, data = apiclus1, fpc = ~fpc)

est0 <-
  survey::svyby(design=des, formula=~cname, by=~both, FUN=survey::svymean, keep.var=TRUE) %>%
  as_tibble()

est0Yes <- 
  survey::svymean(x=~cname, design=subset(des, both=="Yes")) %>%
  as_tibble(rownames = "cname") %>%
  mutate(
    Yes=glue::glue('{formatC(mean*100, digits=1, format="f")} ({formatC(SE*100, digits=1, format="f")})'),
    cname=stringr::str_remove(cname, "^cname"),
  )
est0No <- 
  survey::svymean(x=~cname, design=subset(des, both=="No")) %>%
  as_tibble(rownames = "cname") %>%
  mutate(
    No=glue::glue('{formatC(mean*100, digits=1, format="f")} ({formatC(SE*100, digits=1, format="f")})'),
    cname=stringr::str_remove(cname, "^cname"),
  )

select(est0Yes, cname, Yes) %>%
  full_join(select(est0No, cname, No), by="cname")
#> # A tibble: 11 x 3
#>    cname       Yes         No         
#>    <chr>       <glue>      <glue>     
#>  1 Alameda     6.8 (6.9)   4.0 (4.2)  
#>  2 Fresno      3.0 (3.2)   <NA>       
#>  3 Kern        0.8 (0.8)   2.0 (2.1)  
#>  4 Los Angeles 8.3 (7.1)   8.0 (8.1)  
#>  5 Merced      2.3 (2.4)   2.0 (2.1)  
#>  6 Orange      9.8 (9.6)   6.0 (6.2)  
#>  7 Plumas      3.0 (3.2)   10.0 (9.9) 
#>  8 San Diego   30.1 (17.9) 30.0 (17.6)
#>  9 San Joaquin 19.5 (17.1) 22.0 (18.7)
#> 10 Santa Clara 16.5 (11.1) 8.0 (6.6)  
#> 11 Mendocino   <NA>        8.0 (8.1)

# seems to be some bug in svyby when not all levels are present - not all counties are showing up (Fresno) 
est0[,-1] %>%
  t()
#>                           [,1]        [,2]
#> cnameAlameda        0.04000000 0.067669173
#> cnameKern           0.02000000 0.030075188
#> cnameLos Angeles    0.08000000 0.007518797
#> cnameMendocino      0.08000000 0.082706767
#> cnameMerced         0.02000000 0.022556391
#> cnameOrange         0.06000000 0.097744361
#> cnamePlumas         0.10000000 0.030075188
#> cnameSan Diego      0.30000000 0.300751880
#> cnameSan Joaquin    0.22000000 0.195488722
#> cnameSanta Clara    0.08000000 0.165413534
#> se.cnameAlameda     0.04193189 0.068860947
#> se.cnameKern        0.02136291 0.031750283
#> se.cnameLos Angeles 0.08059425 0.008104529
#> se.cnameMendocino   0.08059425 0.071299641
#> se.cnameMerced      0.02136291 0.023980833
#> se.cnameOrange      0.06168395 0.096384262
#> se.cnamePlumas      0.09863587 0.031750283
#> se.cnameSan Diego   0.17588245 0.179332414
#> se.cnameSan Joaquin 0.18678713 0.171213083
#> se.cnameSanta Clara 0.06616823 0.110939332
```

<sup>Created on 2022-03-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
@larmarange very good point. This functionality belongs in the CI function.

@szimmer while this is on our radar to implement, I have no timeline for its release. I just don't have the time at the moment.

**Comment by szimmer** [comment]
Thanks, I understand being busy!

I'm not sure this would belong in a CI function. You can request `sd` for a continuous variable so this is the `sd` for a categorical variable - doesn't really have to do with the CI.

**Comment by ddsjoberg** [comment]
with many varying methods for calculating the SE for the proportion, there is no single value we could easily use. I do feel it fits better in the CI function (as far as the organization of the package goes).

**Comment by ddsjoberg** [comment]
i am going to close this issue for now. if you're interested in contributing to the `add_ci_tbl_svysummary()` method, please reach out and we can spec out the updates needed together.

**Comment by szimmer** [comment]
Can we re-open this? This is separate from CI implementation.

**Comment by szimmer** [comment]
I made progress on this but stuck for how to set the default style of `p_se` to be style_percent and adjust how it's referred in the footnote. Code in progress at: https://github.com/szimmer/gtsummary/tree/svy-prop-se

Reprex of current work:

``` r
library(gtsummary)
data(api, package = "survey")
mydes <- survey::svydesign(id = ~dnum, weights = ~pw, data = apiclus1, fpc = ~fpc) 

mydes %>%
  tbl_svysummary(include = c(api00, stype), 
                 statistic=list(all_continuous() ~ "{median} ({p25}, {p75})",
                                all_categorical() ~ "{p}% ({p_se})"))
```
![ss_20220507](https://user-images.githubusercontent.com/8659598/167262801-d4ec0e1e-cf69-434f-8e28-2f6960c629bc.png)

**Comment by ddsjoberg** [comment]
@szimmer if you create a pull request, I can look into adding the default rounding and naming of the statistic.

**Comment by ddsjoberg** [comment]
But with so many varying methods for calculating the SE for the proportion,
there is no single value we could easily use. I do feel it fits better in
the CI function (as far as the organization of the package goes).

**Comment by larmarange** [comment]
@ddsjoberg Are you reopening the discussion?

In the current implementation, `tbl_svysummary()` returns the basic standard errors, as computed by `svymean()`.

Other methods are covered only by `svyciprop()` and should be covered only by `add_ci()`.

I'm realizing that we didn't develop yet an `add_ci()` methods for `tbl_svysummary()`

**Comment by ddsjoberg** [comment]
Hey hey @szimmer ! Are you still interested in contributing an `add_ci()` function for `tbl_svysummary()`.

@larmarange FYI, this is being tracked here https://github.com/ddsjoberg/gtsummary/issues/965
