### ISSUE TITLE
error when exporting to docx and pdf via huxtable, flextable or kable extra

### ISSUE THREAD

**Issue by tibirkrajc** [ddsjoberg/gtsummary#1188]
All the above methods produce the same error even with the latest package from remotes::install_github("ddsjoberg/gtsummary"):

i Updating gtsummary object from `x$table_header` to `x$table_styling` introduced in "v1.4.0".
Error in UseMethod("mutate") : 
  no applicable method for 'mutate' applied to an object of class "NULL"

It's kinda frustrating to stare at the nice table and not be able to export it...
Thanks for looking into the issue!

**Comment by ddsjoberg** [comment]
Hey, can you update your post with a reproducible example?

**Comment by tibirkrajc** [comment]
wow, that was fast!

i suspect the gt related bit of code, when i remove it, huxtable and flextable work.

tbl_summary(dat, by = VAMLA,
            statistic = list(
                all_continuous() ~ "{median} ({mean}±{sd})",
                all_categorical() ~ "{n} ({p}%)")) %>%    #/ {N}
    add_p() %>%
    bold_labels() %>%
    italicize_levels() %>%
    modify_header(label ~ "***Charakteristiken***") %>%
    add_glance_source_note() %>%   # removing this one and the following 4 lines helps
    as_gt() %>%
    gt::tab_header(
        title = "Auf Tumor bezogene Eigenschaften der Gruppen",
        subtitle = "inklusive Patienten mit postoperativen Komplikationen"
    )

**Comment by tibirkrajc** [comment]
dat <- read.csv("[gtsummary.csv](https://github.com/ddsjoberg/gtsummary/files/8379793/gtsummary.csv)")
dat <- dat %>% mutate(Stadium = factor(Stadium))
dat <- dat %>% mutate(VAMLA = factor(VAMLA, labels = c('MLND','VAMLA')))
dat <- dat %>% mutate(T_Deskriptor = factor(T_Deskriptor))
dat <- dat %>% mutate(N_Deskriptor = factor(N_Deskriptor))
str(dat)

t <- tbl_summary(dat, by = VAMLA,
            statistic = list(
                all_continuous() ~ "{median} ({mean}±{sd})",
                all_categorical() ~ "{n} ({p}%)")) %>%    #/ {N}
    add_p() %>%
    bold_labels() %>%
    italicize_levels() %>%
    modify_header(label ~ "**Stuff of Interest**") %>%
    as_gt() %>%
    gt::tab_header(title = "Title of this pretty Table",
                   subtitle = "which I cannot have in word or pdf"
    )

t
# table shows in viewer ok, some error messages regarding p values ignored

as_hux_table(
    t,
    include = everything(),
    return_calls = FALSE,
    strip_md_bold = FALSE
)

as_kable_extra(
    t,
    include = everything(),
    return_calls = FALSE,
    strip_md_bold = TRUE,
    fmt_missing = TRUE
    )

#both yield the same error:
#i Updating gtsummary object from `x$table_header` to `x$table_styling` introduced in "v1.4.0".
#Error in UseMethod("mutate") : 
#  no applicable method for 'mutate' applied to an object of class "NULL"

Thanks!

**Comment by ddsjoberg** [comment]
Hey hey @tibirkrajc , Can you please update with a reproducible example that I can run on my machine as well? Then I can look into it. 

Please also keep the example as minimal as possible.
https://reprex.tidyverse.org

**Comment by ddsjoberg** [comment]
Thanks for the update Tibor.

I'll have time to investigate further next week. But I think I've spotted
the issue. The functions as_gt(), as_hux_table(), and the other as_*()
functions covert gtsummary tables to gt, huxtable, etc objects. Once you've
converted a gtsummary table to gt with as_gt(), you can no longer run
functions like as_hux_table() because you no longer have a gtsummary object.

I should improve the error messaging in these functions.

**Comment by tibirkrajc** [comment]
Awesome, thanks!
If I understand correctly, exporting into pdf or docx via flex_table is not
possible when adding title and subtitle to the table by piping it to gt
like this: %>% gt::tab_header(title = "Title of this pretty Table",
subtitle = "which I cannot have in word or pdf").
What is your usual way of adding title/subtitle to tables made with
gtsummary?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ddsjoberg** [comment]
you can convert a gtsummary table to gt, flextable, huxtable, kableExtra, kable, and tibbles. But we do not provide the functionality to convert among all the output formats.

You can add titles with `modify_caption()` and you can of course add more titles using the functions within flextable after you run `as_flex_table()`
