### ISSUE TITLE
Feature request: Storing more metadata into the dataset (value, digits...)

### ISSUE THREAD

**Issue by JeremyPasco** [ddsjoberg/gtsummary#1192]
Hi,
When I use gtsummary, I usually call `labelled` package just after importing data to define var labels and value labels once for all. And it works great since gtsummary leverage labelled too!
But I was wondering if I could centralize a bit more of these metadata declarations: AFAIK there is no way do declare the `value` of dichotomous variables (as expected in the `value` parameter of `tbl_summary`) like `labelled` set labels. Which imply to redeclare this in every new table, or to work with a custom storage system (which I do now: I embed `tbl_summary` into a function that leverage external definitions of my dataset and fullfill parameters accordingly).

I think that setting other metadata like `type` or `digit` (parameters of `tbl_summary`) would be great too.

Do you thing the following could be in the scope of `gtsummary`?
- functions to store metadata directly into a dataframe (as `labelled` do)
- modifications on `tbl_summary` to levarage them

Of course, I can work on a pull request for this.

**Comment by JeremyPasco** [comment]
Thank you for your reply. Looking for a existing package was my first idea indead but I couldn't find something like this.

For information, my custom implementation of the idea allows me to infer the following parameters (which can still be overloaded when calling the function) based on a centralized declaration :
- `tbl_summary` / `tbl_svysummary`: statistic, digits, type, value, missing_text
- `add_p`: test (mainly as a shortcut to handle differently parametric and non parametric continuous variables)
- `add_ci`: method (same reason)
- `add_stat`: fns and location
- `tbl_regression` / `tbl_uvregression`: show_single_row (infered like value in `tbl_summary`)

**Comment by ddsjoberg** [comment]
hey hey @JeremyPasco !

I've been giving this some thought and chatting with other pkg authors, and I think this type of specific functionality is out of the scope of gtsummary. We landed on this decision primarily because this would be creating a data dictionary whose primary use is only for `tbl_summary()` tables.

As this is something quite specific, I think something like this will work/help.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.5.2.9019'

data_dictionary <-
  tibble::tribble(
    ~variable,        ~type, ~digits,
    "age",     "continuous",       1,
    "marker",  "continuous",       3
  )

# extract arg and convert to list
data_dictionary_to_list <- function(data_dictionary, argument) {
  data_dictionary[c("variable", argument)] %>%
    tibble::deframe() %>%
    as.list() %>%
    purrr::compact()
}

trial %>%
  select(age, marker) %>%
  tbl_summary(
    type = data_dictionary_to_list(data_dictionary, "type"),
    digits = data_dictionary_to_list(data_dictionary, "digits"),
    missing = "no"
  ) %>%
  as_kable()
```

| **Characteristic**   |     **N = 200**      |
|:---------------------|:--------------------:|
| Age                  |  47.0 (38.0, 57.0)   |
| Marker Level (ng/mL) | 0.639 (0.215, 1.393) |

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


Anyway, thank you for the post and happy programming!

**Comment by JeremyPasco** [comment]
Hey, that's the idea, thanks!
I've been doing something similar with a few improvments these last months. I understand that's a too specific niche for the package scope. So If others are interested in for local developments, here were my ideas:
- store these metadata in a specific file I'll be using for the whole project (ie: if your data file is named trials.xlsx, I usually store this into a trials.yaml or a trial.json)
- create a custom `tbl_summary` function that will always look for a metadata file accordingly (ie: `tbl_summary(xyz)` will search for `xyz.json`)
- parse these metadata and complete `tbl_summary` arguments accordingly (see `data_dictionnay_to_list`)
- if `tbl_summary` is given arguments in conflict with metadata, here are the priority i've been giving for each argument (ie: digits):
    - variable specific argument are always used in priority if given (ie: `digits=list(xyz=2)`)
    - if a variable has received no configuration through specific argument, metadata are considered
    - arguments with, general selector like `all_continuous` are considered lastly
 
That way, any variable that has to be deal with specificaly will inherit these paremeters for the whole project, and you still can overload these metadata giving arguments to your custom `tbl_summary` function.

I haven't post the full code because my implementation is tightly coupled with a specific enterprise environment right now (most of our metadata files are now automatically generated by our eCRF solution!). But if someone is interested, just notify me and I'll do some cleaning.
