### ISSUE TITLE
error using "pattern" argument in inline_text() for tbl_summary() + add_difference()

### ISSUE THREAD

**Issue by emilyvertosick** [ddsjoberg/gtsummary#1193]
After creating a tbl_summary table and adding a mean difference using add_difference(), inline_text() will not allow the use of the "pattern" option. Using the pattern option gives an error and it seems to be defaulting to look for column "stat_0" which doesn't exist in this table, rather than behaving like tbl_regression and allowing estimates to be extracted using the "pattern" option (eg "{estimate} ({ci}), {p.value}").

``` r
library(tidyverse)
library(gtsummary)

tbl_difference <-
  trial %>%
  select(trt, marker) %>%
  tbl_summary(by = trt) %>%
  add_difference()

# This works
inline_text(tbl_difference, variable = "marker", column = "estimate")
#> [1] "0.20"

# This doesn't work
inline_text(tbl_difference, variable = "marker", pattern = "{estimate}")
#> Error: Error in `column=` argument input. Select from 'variable', 'test_name', 'var_type', 'var_label', 'row_type', 'label', 'stat_1', 'stat_2', 'test_result', 'estimate', 'statistic', 'parameter', 'ci', 'conf.low', 'conf.high', 'p.value', 'estimate1', 'estimate2', 'alternative', 'raw_stat_1_median', 'raw_stat_2_median', 'raw_stat_1_p25', 'raw_stat_2_p25', 'raw_stat_1_p75', 'raw_stat_2_p75', 'raw_stat_1_N_miss', 'raw_stat_2_N_miss', 'raw_stat_1_N_obs', 'raw_stat_2_N_obs', 'raw_stat_1_p_miss', 'raw_stat_2_p_miss', 'raw_stat_1_N_nonmiss', 'raw_stat_2_N_nonmiss', 'raw_stat_1_p_nonmiss', 'raw_stat_2_p_nonmiss'
```

<sup>Created on 2022-04-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
My concern about updating this to no longer input a default column of `stat_0` is that it will be a breaking change. Need to think about best way to improve the function.

1. If user passes neither `column=` nor `pattern=` we can still default to `column = stat_0`?
2. If a user passes no column and passes `pattern=`, previously we would default to `column = stat_0`, but maybe we can change this (breaking change) to no longer populate the `column=` arg.
