### ISSUE TITLE
tbl_regression with stan_glm

### ISSUE THREAD

**Issue by kwakuduahc1** [ddsjoberg/gtsummary#1195]
I just encountered an issue tbl_regression. I fit a Bayesian regression with stan_glm and reported it with tbl_regression. It works almost perfectly except I tried to use the inline_text function only to be told the p.value could not be found. I do not know whether I am missing something.

As noted below, the confidence interval should be reported as credible interval, if it is a bayesian regression. I do not know whether I am missing something.

Again, the pd could be shown in this case.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rstanarm)
library(bayestestR)
library(gtsummary)
cd <- carData::Arrests
```

```{r include=FALSE}
mod <- stan_glm(checks ~ colour + age + sex, data = cd)
```

```{r}
describe_posterior(mod)
```
![image](https://user-images.githubusercontent.com/11381582/163374675-93072eff-7504-443a-8340-5657c1a17944.png)

```{r}
tbl <- tbl_regression(mod, intercept = T, labe = list(age ~ "Age", colour ~ "Race", sex ~ "Sex") )
```

```{r}
tbl |> as_flex_table()
```

![image](https://user-images.githubusercontent.com/11381582/163374371-718e94e1-2634-4496-ab67-938488ed3c48.png)

The ~Confidence Interval~ report should rather be reported as *Credible Interval*. 

But most importantly, the inline_text function is going to fail with the error message:

/*
Error in eval(parse(text = text, keep.source = FALSE), envir) : 
  object 'p.value' not found
*/

**Comment by ddsjoberg** [comment]
Thanks @kwakuduahc1 for the post.

I don't see any pvalues in the summary, which is where they'd be pulled from. What pvalues are you expecting to be reported?

**Comment by kwakuduahc1** [comment]
Yes, for a Bayesian regression, there is typically no p-value. However, the PD is a great approximation of the p-value (See https://easystats.github.io/bayestestR/articles/guidelines.html#uncertainty).

That notwithstanding, the inline_text should be able to report the estimate and the Credible Interval, even without the PD (p-value). Currently, it throws an error.

Best regards.

**Comment by ddsjoberg** [comment]
The default tidier is `broom.mixed::tidy()` and returns neither a p-value or PD. you can use the parameters package to tidy by specifying `tidy_fun = broom.helpers::tidy_parameters`, which will give you access to PD, but will not be printed by default.

I'll open another issue regarding printing credible interval vs confidence interval
