### ISSUE TITLE
Report Credible Interval for Bayesian Regression Models

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#1196]
The default labelling of Confidence Interval does not apply to Bayesian models. See details here https://github.com/ddsjoberg/gtsummary/issues/1195

**Comment by kwakuduahc1** [comment]
Excellent, but is it possible to report the PD value too? It can even be reported as 1 - PD. Having a PD of 0.995 is equivalent to a p.value of 1-0.995 = 0.005 in the frequentist framework. Therefore a PD of 1 can be reported as <0.001

Best regards.

**Comment by ddsjoberg** [comment]
Yep, the column is hidden by default and you can unhide it with the modify column unhide function. See all the columns by inspecting the x$table_styling$header object

**Comment by kwakuduahc1** [comment]
Thank you.

I managed to produce this with your suggestions

`tbl <- tbl_regression(model, tidy_fun = broom.helpers::tidy_parameters,
               label = list(h_bieeding_c_u  ~ "Bleeding", complications ~ "Complications", outcome ~ "Outcome")) %>% 
  modify_column_unhide(columns = c("pd")) %>% 
  modify_footnote(list(ci ~ "CI = Credible Interval", pd ~ "Probability Direction"), abbreviation = T) %>% 
  modify_header(pd = "PD")`
  
  
![image](https://user-images.githubusercontent.com/11381582/163502158-40554383-a0dd-4841-8fd7-f86fdbc8cd84.png)

Then with that, `inline_text(tbl, variable = "complications", level = "Yes" , pattern = "{estimate} ({conf.level }% CI {conf.low}, {conf.high}; {pd}")
`

![image](https://user-images.githubusercontent.com/11381582/163502229-83f134e4-4ab0-4b2f-9b58-2c232d6479ac.png)

**Comment by ddsjoberg** [comment]
@kwakuduahc1 it's gorgeous :) FYI using `modify_header(pd = "PD")` will automatically unhide the column

**Comment by kwakuduahc1** [comment]
Yes, you are right, of course! 😀

**Comment by kwakuduahc1** [comment]
I hope this can help. 

I produced a markdown file as a possible solution. Admittedly, it works with models generated with _rstanarm_. It simply checks if there is a *PD* column, it is indicative of a bayesian model as the frequentist models do not produce that.

I do not know if other tools do not generate the *PD* variable. It may generate it in another name.
---
title: "Credible Intervals with gtsummary"
author: "Ibrahim Duah Kwaku"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(rstanarm)
library(dplyr)
library(broom.helpers)
```

## Fit a Bayesian generalized linear model with _rstanarm_

```{r message=FALSE, include=FALSE}
mod1 <- 
  stan_glm(
    Sepal.Length ~ Sepal.Width,
    data = iris, 
  )
```

## Check the model parameters
```{r}
tidy_parameters(mod1)
```

## Confirm same for a linear model
```{r message=FALSE, warning=FALSE}
mod2 <- 
  stan_lm(mpg ~ wt + qsec + am, data = mtcars, prior = R2(0.75), 
                # the next line is only to make the example go fast enough
                chains = 1, iter = 300, seed = 12345, refresh = 0) %>%  
  tidy_parameters()
```

The model always contains a PD

```{r message=FALSE, warning=FALSE}
tidy_parameters(mod2)
```

## The pd column is not part of a frequentist model
```{r message=FALSE, warning=FALSE}
mod3 <- lm(mpg ~ wt + qsec + am, data = mtcars) %>%  
  tidy_parameters()

mod3
```

## Proposed solution
```{r}
mod2 %>% 
  broom.helpers::tidy_parameters() %>% 
  mutate(
    g = {if("pd" %in% names(.)) "Credible Intervals" else "Confidence Intervals"},
    h = {case_when("pd" %in% names(.) ~  "Credible Intervals", T ~ "Confidence Intervals")}
  ) %>% 
  select(g,h)
```
Depending on the choice of base r or dplyr, any of them should produce the same results
*translate_text* should work as before
```{r}
mod3 %>% 
  mutate(
    g = {if("pd" %in% names(.)) "Credible Intervals" else "Confidence Intervals"},
    h = {case_when("pd" %in% names(.) ~ "Credible Intervals", T ~ "Confidence Intervals")}
  ) %>% 
  select(g,h)
```

Modifying line 117 of the _utils-tbl_regression.R_ with the proposal should thus solve the problem.

Best regards.

**Comment by ddsjoberg** [comment]
Awesome, thanks @kwakuduahc1 

By default we are using the broom tidiers, which do not return a PD column. I think I'll end up checking the class of the model object to decide whether to label the CI as a confidence interval or a credible interval
