### ISSUE TITLE
Improve error messaging when a column is all NA in `tbl_svysummary()`

### ISSUE THREAD

**Issue by jenifav** [ddsjoberg/gtsummary#1197]
I have a dataset on two provinces and have subset them using :

svy_hp <- subset(svy, n001=="City 2")

I ran this code and it ran fine on one and the other I get this error:

Code:
tbl_hp <- 
  svy_hp %>%
  tbl_svysummary(statistic = everything() ~ "{n} {p}%", missing="no", 
                 include=all_of(vars3),
                 digits = list(everything() ~ c(0, 2))) %>%
  modify_table_body(
    ~.x %>%
      left_join(
        df_hp, by = c("variable", "label")
      )
  ) %>%
  modify_header(ci = "**95% CI**") 

Error:

Error in `mutate()`:
! Problem while computing `df_stats = pmap(...)`.
Caused by error:
! 'n' statistic is not supported for survey objects.
Run `rlang::last_error()` to see where the error occurred.

I did NOT get this error on the other subset for the other city.

**Comment by ddsjoberg** [comment]
Thank you for your post. Please update your post with a reproducible example, aka a reprex. A reprex includes both data and code I can run on my machine that replicates the issue you're reporting. Take just a few minutes to review [reprex.tidyverse.org ](https://reprex.tidyverse.org/) for detailed instructions on how to create a reprex.

I am going to go ahead and close this issue for now. But please do re-open the issue after you've added your reproducible example.

**Comment by jenifav** [comment]
I saved the dput but I can't drag and drop it here.  Can I upload it somewhere you can get to it?

**Comment by ddsjoberg** [comment]
if you can replicate the issue with just a few lines from the `dput()`, you can paste them into a code block here on GH.

**Comment by jenifav** [comment]
I think I figured it out.  One of the variables I was running through the functions to make the table didn't  have any observations in the subgroup so the statistics couldn't be computed (naturally).  Sorry to take up your time over this!  But thank you so much for trying to help.

**Comment by ddsjoberg** [comment]
Thank you for letting me know! That is definitely something where (minimally) the error messaging could be improved. I don't use survey data in my own work, so I don't touch those functions as much!

**Comment by jenifav** [comment]
I found it very useful for producing a table for a customer who needed survey adjusted proportions and confidence intervals for something like 150 variables.  The one that broke the code was part of a diagnostic cascade so had dwindling data, which I was aware of.  I just didn't realize one of the subgroups had NO data at the end of the cascade.  Thanks, again!

**Comment by ddsjoberg** [comment]
HI @larmarange ! Do you have a preference how these situations are handled? It's easiest to just return an error signaling that `tbl_svysummary()` can't summarize a column that is all NA.

**Comment by jenifav** [comment]
Hi Daniel, I think that would be useful only because what it does now is

Caused by error:
! 'n' statistic is not supported for survey objects.

And that was confusing in that it made me initially think the problem was getting sample stats on survey objects rather than it was a empty column.  If it were easy I'd say if there was no error and tbl_svysummary() would just report out NAs or 0%, etc.  But that might be too much work.

**Comment by ddsjoberg** [comment]
@jenifav was there something else special about the column that threw an error? I just passed an all NA column, and the code worked without any issue.

``` r
library(gtsummary)

svy <-
  survey::svydesign(
    ids = ~1, 
    data = trial %>% select(age) %>% dplyr::mutate(age = NA), 
    weights = ~1
  )

tbl_svysummary(svy) %>% as_kable()
```

| **Characteristic** | **N = 200** |
|:-------------------|:-----------:|
| age                |   0 (NA%)   |
| Unknown            |     200     |

<sup>Created on 2022-04-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
@jenifav if you can provide a reprex, i can look into this further

**Comment by larmarange** [comment]
I tried with a factor, and it is also working correctly.

``` r
library(gtsummary)

svy <-
  survey::svydesign(
    ids = ~1, 
    data = trial %>% select(grade, stage) %>% 
      dplyr::mutate(grade = labelled::recode_if(grade, !is.na(grade), NA)), 
    weights = ~1
  )

tbl_svysummary(svy, by = stage) %>% as_kable()
```

| **Characteristic** | **T1**, N = 53 | **T2**, N = 54 | **T3**, N = 43 | **T4**, N = 50 |
|:-------------------|:--------------:|:--------------:|:--------------:|:--------------:|
| Grade              |                |                |                |                |
| I                  |    0 (NA%)     |    0 (NA%)     |    0 (NA%)     |    0 (NA%)     |
| II                 |    0 (NA%)     |    0 (NA%)     |    0 (NA%)     |    0 (NA%)     |
| III                |    0 (NA%)     |    0 (NA%)     |    0 (NA%)     |    0 (NA%)     |
| Unknown            |       53       |       54       |       43       |       50       |

``` r
tbl_svysummary(svy, by = stage) %>% add_p() %>% as_kable()
#> There was an error in 'add_p()/add_difference()' for variable 'grade', p-value omitted:
#> Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]): contrasts can be applied only to factors with 2 or more levels
```

| **Characteristic** | **T1**, N = 53 | **T2**, N = 54 | **T3**, N = 43 | **T4**, N = 50 | **p-value** |
|:-------------------|:--------------:|:--------------:|:--------------:|:--------------:|:-----------:|
| Grade              |                |                |                |                |             |
| I                  |    0 (NA%)     |    0 (NA%)     |    0 (NA%)     |    0 (NA%)     |             |
| II                 |    0 (NA%)     |    0 (NA%)     |    0 (NA%)     |    0 (NA%)     |             |
| III                |    0 (NA%)     |    0 (NA%)     |    0 (NA%)     |    0 (NA%)     |             |
| Unknown            |       53       |       54       |       43       |       50       |             |

<sup>Created on 2022-04-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jenifav** [comment]
Hmmm, I will do the reprex.  In my case I had some pre-processing that I didn't and didn't post here because they ran fine  but am putting the whole set of code here now.:

#just in case

library(ggplot2)
library(haven)
library(tidyr)
library(reshape2)
library(dplyr)
library(data.table)
library(stringr)
library(tidyverse)
library(skimr)
library(openxlsx)
library(dataCompareR)
library(freqtables)
library(gtsummary)
library(ciTools)
library(survey)
library(purrr)

df_hp <- 
  tibble(variable = vars3) %>%
  rowwise() %>%
  mutate(
    level = unique(svy_hp$variables[[variable]]) %>% as.list() %>% list(),
    label = unique(svy_hp$variables[[variable]]) %>% as.character() %>% as.list() %>% list()
  ) %>%
  unnest(c(level, label)) %>%
  mutate(
    label = unlist(label)
  ) 

df_hp <- na.omit(df_hp)
df_hp$variable <- factor(df_hp$variable, levels=unique(df_hp$variable))
df_hp <- df_hp %>%
  group_by(variable) %>%
  arrange(desc(level), label, .by_group = TRUE)


df_hp$variable <- as.character(df_hp$variable)
df_hp$svyciprop <-
  map2(
    df_hp$variable, df_hp$label,
    function(variable, level) rlang::inject(survey::svyciprop(~I(!!rlang::sym(variable) == !!level), svy_hp, na.rm=T))
  ) 


df_hp <-
  df_hp %>%
  rowwise() %>%
  mutate(
    ci = 
      paste0("(", svyciprop %>%
               attr("ci") %>%
               style_sigfig(digits=4,
                            scale = 100) %>%
               paste0("%", collapse = ", "), ")")) %>%
  ungroup() %>%
  select(variable, label, ci)

tbl_hp <- 
  svy_hp %>%
  tbl_svysummary(statistic = everything() ~ "{n} {p}%", missing="no", 
                 include=all_of(vars3),
                 digits = list(everything() ~ c(0, 2))) %>%
  modify_table_body(
    ~.x %>%
      left_join(
        df_hp, by = c("variable", "label")
      )
  ) %>%
  modify_header(ci = "**95% CI**") 


To trouble shoot this I ran my data through using a subset of rows and still got the error and then a subset of columns and did NOT get the error, finally backing out the column in the cascade that I suspected was the problem, and did not get the error.

I've got a meeting in a second but after that I will do the reprex.

**Comment by jenifav** [comment]
OK,  here's the reprex:

tbl_hp <- svy_hp %>% tbl_svysummary(statistic = everything() ~ 
    "{n} {p}%", missing = "no", include = all_of(vars3), digits = list(everything() ~ 
    c(0, 2))) %>% modify_table_body(~.x %>% left_join(df_hp, 
    by = c("variable", "label"))) %>% modify_header(ci = "**95% CI**")
#> Error in svy_hp %>% tbl_svysummary(statistic = everything() ~ "{n} {p}%", : could not find function "%>%"

Which doesn't make much sense to me.  I've been using the pipe operator in several places before this.

**Comment by ddsjoberg** [comment]
the reprex runs in a new environment. you need to load gtsummary and any other packages/data needed. please use a data source that is available for me as well

**Comment by jenifav** [comment]
Yes, that's what it said on the clip board.  Let me post the dput and the all the code you need to run what I was trying to run.  Would you like me to just save it all as a script file and link it here or paste the whole thing in a comment?

**Comment by ddsjoberg** [comment]
Maybe just add the code to a GitHub Gist https://gist.github.com/

**Comment by jenifav** [comment]
Can you access:  https://gist.github.com/jenifav/47e11210db1285102cf693d549cd1b0b

**Comment by ddsjoberg** [comment]
@jenifav yes i can see it, thanks!

One more request....can you make the example as minimal as possible? it is truly helpful when reviewing

**Comment by jenifav** [comment]
How's it now?

**Comment by ddsjoberg** [comment]
Is it as short as possible while still returning the error?

By glancing at it, it seems the error likely occurs in tbl_svysummary, but there is a lot more code in the gist than just this. Please make it as simple as possible while still replicating the error

**Comment by jenifav** [comment]
OK, I'll see what I can do.  Apologies but I probably won't get to it today due to having a meeting-heavy day.  My fave.

**Comment by ddsjoberg** [comment]
hey hey @jenifav , I took a look at your code. You have columns that are all NA, and they are being summarized as continuous, and you're trying to force their summary statistics to be counts and percentages. These are not defined for continuous variables. The call below will run without error;

```r
tbl_hp <- 
  svy_hp %>%
  tbl_svysummary(
    statistic = c(c101, hocvan) ~ "{n} {p}%",
    missing="no",
    include = all_of(colnames(hp[,c(4:8)])),
    digits = list(everything() ~ c(0, 2))
  )
```

**Comment by jenifav** [comment]
@ddsjoberg Aha!  I was coming here with further minimalized code.  So, those variables are actually categorical.  So, I changed my code to:

```
tbl_hp <- 
  svy_hp %>%
  tbl_svysummary(statistic = all_categorical() ~ "{n} {p}%", missing="no", 
                 include=all_of(vars3),
                 digits = list(everything() ~ c(0, 2))) %>%
  modify_table_body(
    ~.x %>%
      left_join(
        df_hp, by = c("variable", "label")
      )
  ) %>%
  modify_header(ci = "**95% CI**") 
```

And that worked!  Thanks so much!
