### ISSUE TITLE
Add ability to set global options for {gtsummary}

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#120]
For example, user can define a default p-value function, or a function to round regression model coefficients.

**Comment by margarethannum** [comment]
For this one do you mean instead of having gtsummary guess which test to do, demand it does certain test (or define test in a formula)?

**Comment by ddsjoberg** [comment]
I was thinking that a user could set a global option for pvalue formatting, for example.

```r
options(gtsummary.pvalue_fun = purrr::partial(style_pvalue, digits = 2)
```

Then all the {gtsummary} defaults would use the `getOptions()` to first check whether an option was set, and secondarily use the defaults that are already set.

I haven't thought it all out yet.  But something along these lines.

**Comment by ddsjoberg** [comment]
Also, this may just add an unnecessary level of complexity?

idk, I think it' worth a chat.

**Comment by ddsjoberg** [comment]
Thinking about this more...is this a good idea?
- yes, it can be good for an individual user who always wants to set their own defaults
- it's bad for reproducibility, as the same code will produce different results since some may have the options set in their `Rprofile`.
- perhaps it is fine, because these are primarily used to Rmarkdown files where the `Rprofile` is ignored (at least, I think it is).

**Comment by ddsjoberg** [comment]
Types of global variables to set:
- All Functions
    - [ ] `pvalue_fun` 
    - [ ] `conf.level` 
- `tbl_summary()`
    - [ ] `statistic =` set default statistics to present.  Is there a way to set multiple stat defaults, but not overwrite all defaults if any change is made
- `add_p()`
    - [ ] `test = `
- `tbl_regression()` / `tbl_uvregression()`
    - [ ] `estimate_fun = `

**Comment by FImodels** [comment]
@ahinton-mmc 

I see in the examples you send me every so often that you always change the pvalue function.  It would be easier for you to set an option at the top of the program so all pvalues in gtsummary functions will be rounded to two places, for example.

What other variables would be useful to set options for?

**Comment by ddsjoberg** [comment]
@ahinton-mmc

I see in the examples you send me every so often that you always change the pvalue function. It would be easier for you to set an option at the top of the program so all pvalues in gtsummary functions will be rounded to two places, for example.

What other variables would be useful to set options for?

**Comment by ahinton-mmc** [comment]
@ddsjoberg That would be great! Although I prefer the way gt_summary rounds pvalues, others prefer a standard number of decimal points regardless of value. If its possible, I'd like to be able to select a level to display for categorical variables other than binary ones. For example, I have a factor variable that is binary but since its not 0/1, I don't seem to be able to specify that I only want to display one level. I could also just be incorrectly specifying :-) That's all I can think of right now, but I'll come back and post if I think of something else! Thanks for asking!!! <3 *gtsummary's biggest fan*

**Comment by ddsjoberg** [comment]
@ahinton-mmc 

You can specify a level in the `value =` argument to display a specific value as a dichotomous variable in the tables.

**Comment by ddsjoberg** [comment]
these updates are now in dev branch

**Comment by ddsjoberg** [comment]
Users can now set default p-value formatting functions, regression coefficient formatting functions, and default confidence level for confidence intervals
