### ISSUE TITLE
Adding p-value to each level of a categorical variable add_p(keep = TRUE)

### ISSUE THREAD

**Issue by postgres-newbie** [ddsjoberg/gtsummary#1208]
The add_p() function does not allow for adding p-values to each level of a categorical variable like the add_global_p() function through the keep=TRUE option. 

Please make the keep feature available to add_p()

Currently to add p-values for each level of a categorical variable, one has to calculate them manually.

**Comment by ddsjoberg** [comment]
Thank you for your post. Please update your post with a reproducible example, aka a reprex. A reprex includes both data and code I can run on my machine that replicates the issue you're reporting. Take just a few minutes to review [reprex.tidyverse.org ](https://reprex.tidyverse.org/) for detailed instructions on how to create a reprex.

I am going to go ahead and close this issue for now. But please do re-open the issue after you've added your reproducible example.

**Comment by ddsjoberg** [comment]
FYI, you'll need to create dummy/binary variables if you want to use `add_p()` and get p-values for every level.

**Comment by postgres-newbie** [comment]
Here's some reproducible code:

library(gtsummary); 
library(gt); 
library(survival) 
library(dplyr); 
library(stringr); 
library(purrr); 
library(forcats); 
library(tidyr)

save_tbl_summary<-trial %>%
  select(response, age, grade) %>%
  mutate(response = factor(response, labels = c("No Tumor Response", "Tumor Responded"))) %>%
  tbl_summary(
    by = response,
    missing = "no",
    label = list(age ~ "Patient Age", grade ~ "Tumor Grade")
  ) %>%
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 2)) %>%
  add_q()

This produces a table where the cancer grades (I, II and III) i.e. individual categories within the categorical variable "grade" do not have a p-value on every row between the tumor responded vs. tumor not responding columns. The add_global_p() function has the feature keep = TRUE to allow calculation of p-values for every category of a categorical variable, but add_global_p() cannot be used on tbl_summary and gt_summary objects. The error message received when this is attempted is: 

Error in UseMethod("add_global_p") : no applicable method for 'add_global_p' applied to an object of class "c('tbl_summary', 'gtsummary')"

Please add the keep = TRUE feature to add_p() so users can generate p-values per category within a categorical variable. It is painful to calculate these p-values separately for every table. Thanks for your help. If this feature can't be added, please provide a workaround for users.

**Comment by postgres-newbie** [comment]
Yes, I tend to create over 50 dummy variables to get p-values for every level. Would really appreciate it if the keep = TRUE feature is added to add_p()

**Comment by ddsjoberg** [comment]
I think if you familiarize yourself with the `modify_table_body()` function. You can easily merge any results into the data frame that is eventually printed.

**Comment by postgres-newbie** [comment]
Will try that, thank you for providing an alternative to test.
