### ISSUE TITLE
bkm [Table 1] should only contain alphanumeric characters, ':', '-' and '_'.Bug Report: <Describe bug>

### ISSUE THREAD

**Issue by motocci** [ddsjoberg/gtsummary#1217]
I tried to export .docx from Rmarkdown.
It echos "bkm [Table 1] should only contain alphanumeric characters, ':', '-' and '_'." Error.
I can knit to HTML and PDF/LaTeX.

data.frame/tible %>% flextable , data.frame/tible %>% tbl_summary %>% as_tible %>% flextable , works well.
Only data.frame %>% tbl_summary %>% as_flex_table

How can this be resolved?
Now I copy and paste HTML table to Word docx.
Ver 1.5.2（R 4.1.3）Win 11

Best Regards.

**Comment by ddsjoberg** [comment]
Thank you for your post. Please update your post with a reproducible example, aka a reprex. A reprex includes both data and code I can run on my machine that replicates your finding. Make the example as short as possible: the minimal amount of code to reproduce your finding and nothing more.

Take just a few minutes to review [reprex.tidyverse.org](https://reprex.tidyverse.org/) for detailed instructions on how to create a reprex.

I am going to go ahead and close this issue for now. But please do re-open the issue after you've added your reproducible example.
