### ISSUE TITLE
Document tidy_wald_test() on a separate page with an appropriate example

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#1223]
Hi @ddsjoberg 

just tested quickly `tidy_wald_test()` with categorical variables. And it seems not optimal the way `broom.helpers` and `tbl_regression()` deal with it. 

Maybe I didn't use `tidy_wald_test()` as it should. In fact, I was rather thinking about an `add_wald_test()` similar to `add_global_test()` but I probably miss here a use case. Is `tidy_wald_test()` intended to be used with `broom.helpers`? If yes, I have to check in order that variables are correctly identified.

``` r
library(gtsummary)
library(broom.helpers)
#> 
#> Attachement du package : 'broom.helpers'
#> Les objets suivants sont masqués depuis 'package:gtsummary':
#> 
#>     all_continuous, all_contrasts

mod <- glm(response ~ age + grade + stage, trial, family = binomial())

mod %>%
  tbl_regression(exponentiate = TRUE) %>%
  as_kable()
```

| **Characteristic** | **OR** | **95% CI** | **p-value** |
|:-------------------|:------:|:----------:|:-----------:|
| Age                |  1.02  | 1.00, 1.04 |    0.092    |
| Grade              |        |            |             |
| I                  |        |            |             |
| II                 |  0.84  | 0.38, 1.85 |     0.7     |
| III                |  1.05  | 0.49, 2.25 |    \>0.9    |
| T Stage            |        |            |             |
| T1                 |        |            |             |
| T2                 |  0.57  | 0.23, 1.34 |     0.2     |
| T3                 |  0.91  | 0.37, 2.22 |     0.8     |
| T4                 |  0.76  | 0.31, 1.85 |     0.6     |

``` r
mod %>%
  tidy_wald_test()
#> # A tibble: 4 x 4
#>   term           df statistic p.value
#>   <chr>       <dbl>     <dbl>   <dbl>
#> 1 (Intercept)     1     4.68   0.0305
#> 2 age             1     2.84   0.0921
#> 3 grade           2     0.313  0.855 
#> 4 stage           3     1.84   0.607

mod %>%
  tbl_regression(tidy_fun = tidy_wald_test) %>%
  as_kable()
```

| **Characteristic** | **p-value** |
|:-------------------|:-----------:|
| Age                |    0.092    |

``` r
mod %>%
  tidy_and_attach(tidy_fun = tidy_wald_test) %>%
  tidy_identify_variables()
#> # A tibble: 4 x 8
#>   term        variable    var_class var_type var_nlevels    df statistic p.value
#>   <chr>       <chr>       <chr>     <chr>          <int> <dbl>     <dbl>   <dbl>
#> 1 (Intercept) (Intercept) <NA>      interce~          NA     1     4.68   0.0305
#> 2 age         age         numeric   continu~          NA     1     2.84   0.0921
#> 3 grade       grade       <NA>      interce~          NA     2     0.313  0.855 
#> 4 stage       stage       <NA>      interce~          NA     3     1.84   0.607

mod %>%
  tbl_regression(tidy_fun = tidy_wald_test, intercept = TRUE) %>%
  as_kable()
```

| **Characteristic** | **p-value** |
|:-------------------|:-----------:|
| (Intercept)        |    0.030    |
| Age                |    0.092    |
| Grade              |             |
| I                  |             |
| Grade              |     0.9     |
| T Stage            |             |
| T1                 |             |
| T Stage            |     0.6     |

<sup>Created on 2022-04-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by larmarange** [comment]
My mistake, `tidy_wald_test()` is supposed to be used in `add_global_p()`

cf. https://www.danieldsjoberg.com/gtsummary/reference/add_global_p.html

I have been confused because it is documented on the same page as the other custom tidiers: https://www.danieldsjoberg.com/gtsummary/reference/custom_tidiers.html

May I suggest that this function should be documented on a separate page with an example showing how to use it with `add_globla_p()`?

**Comment by ddsjoberg** [comment]
> May I suggest that this function should be documented on a separate page with an example showing how to use it with `add_globla_p()`?

That is great idea!

**Comment by ddsjoberg** [comment]
Hey @larmarange !

I was thinking about this more. This function does tidy the aod Wald test object (similarly, `broom::tidy()` has a method for `car::Anova()`. To make it more clear, I added this to the documentation.
![image](https://user-images.githubusercontent.com/26774684/165659541-818f3880-8776-4024-9ee0-3b1c7ba7f67d.png)

**Comment by larmarange** [comment]
It is true that `broom::tidy()` is very generic and can be applied to a lot of different types of objects.  In `broom`, the different types of tidiers are usually documented on a dedicated page.

In the context of `gtsummary`, my feeling is that we should separate more clearly the different custom tidiers according to where there are supposed to be used. In that sense, I would be in favour of having different pages for tidiers to be used with `tbl_regression()` and tidiers to be used with `add_global_p()` because they are not of the same nature.

**Comment by ddsjoberg** [comment]
You're making very good points!

I do like the idea of keeping them all together, because I am concerned that a single tidier may get lost into the ether. But you're correct there should be a clearer delineation between the types of tidiers. Maybe something like this will be clear to users 

![image](https://user-images.githubusercontent.com/26774684/165847616-06751048-9049-44c2-9220-926db241c480.png)
