### ISSUE TITLE
missing libicuil8n.so.70 when installing

### ISSUE THREAD

**Issue by ge-generation** [ddsjoberg/gtsummary#1227]
Hi,

I have had to recently reinstall my Linux desktop, and was reinstalling my R packages to run my R code including gtsummary, when I encountered this error:

```
* installing *source* package ‘gtsummary’ ...
** package ‘gtsummary’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/lib/R/library/stringi/libs/stringi.so':
  libicui18n.so.70: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘gtsummary’
* removing ‘/usr/lib/R/library/gtsummary’

```
I'm currently on Arch Linux, kernel 5.17.4-arch1, and icu version 71.1.

I'm suspecting that this is due to the change in the icu version that is the issue, and I was wondering if you had plans to upgrade to the new version in the near future?

Thanks!

**Comment by ddsjoberg** [comment]
I think this installation error is coming from either RStudio, the gt package, or the sass package.

This was _just_ merged into the the dev RStudio IDE. Perhaps it's related?
https://github.com/rstudio/rstudio/pull/11074

I don't think there is anything i can do to help you as the gtsummary maintainer.

**Comment by ge-generation** [comment]
I'm using VS code, and I was able to install gt and sass fine with no errors.

The message is from whenever I try and install gtsummary in the R terminal (radian to be exact).

Thanks for your help.

**Comment by ddsjoberg** [comment]
OK, looks like an issue installing stringi, then, no?

```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/lib/R/library/stringi/libs/stringi.so':
  libicui18n.so.70: cannot open shared object file: No such file or directory
```

**Comment by ge-generation** [comment]
Yep, just saw that.

I re-installed stringi from github so it is compiled against icu 71 and it worked!

Sorry to bother you.
