### ISSUE TITLE
Bug Report: as_kable_extra() + bold_labels() extra escape

### ISSUE THREAD

**Issue by shannonpileggi** [ddsjoberg/gtsummary#1230]
I love these amazing `as_kable_extra()` updates!! The print to pdf works beautifully!

Unfortunately, I think I may have stumbled upon an edge case. When printing to pdf via as_kable_extra() in conjunction with bold_labels() special characters seem to be doubly escaped.

Here is the rendered result from the markdown below.
[penguins_demo.pdf](https://github.com/ddsjoberg/gtsummary/files/8593169/penguins_demo.pdf)

The chunk with bold labels shows as
![image](https://user-images.githubusercontent.com/17747575/166027190-722370b9-0b55-4338-9bed-384c17037c1c.png)

```
---
title: "Penguins Report"
author: "Shannon Pileggi"
date: "`r Sys.Date()`"
output: pdf_document
---

# Chunk Settings

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE
  )
```

# packages

```{r load-packages}
library(tidyverse)
library(kableExtra)
library(gtsummary)
library(palmerpenguins)
```

# without bold

```{r}
penguins %>% 
  gtsummary::tbl_summary(
    by = species
  ) %>% 
  #gtsummary::bold_labels() %>% 
  gtsummary::as_kable_extra()
```

# with bold

```{r}
penguins %>% 
  gtsummary::tbl_summary(
    by = species
  ) %>% 
  gtsummary::bold_labels() %>% 
  gtsummary::as_kable_extra() 
```

```

**Comment by ddsjoberg** [comment]
Thank you so much for the repex! I think i have a working version in PR #1231. Can you do more testing? The code in that section is getting pretty ugly 😨

**Comment by ddsjoberg** [comment]
> The code in that section is getting pretty ugly

This section of code has one call to `mutate()` for every shown column in the table. I collapsed this into one call to `mutate()` per alignment level (e.g. left, center).
