### ISSUE TITLE
Add snapshot tests for output

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#1236]
- [x] test-add_ci.R
- [x] test-add_difference.R
- [x] test-add_glance.R
- [x] test-add_global_p.R
- [x] test-add_n.R
- [x] test-add_nevent.R
- [x] test-add_overall.R
- [x] test-add_p.tbl_continuous.R
- [x] test-add_p.tbl_cross.R
- [x] test-add_p.tbl_summary.R
- [x] test-add_p.tbl_survfit.R
- [x] test-add_p.tbl_svysummary.R
- [x] test-add_p_test_safe.R
- [x] test-add_q.R
- [x] test-add_significance_stars.R
- [x] test-add_stat.R
- [x] test-add_stat_label.R
- [x] test-add_vif.R
- [x] test-as_flex_table.R
- [x] test-as_gt.R
- [x] test-as_hux_table.R
- [x] test-as_hux_xlsx.R
- [x] test-as_kable.R
- [x] test-as_kable_extra.R
- [x] test-as_tibble.R
- [x] test-assign_dichotomous_value.R
- [x] test-assign_summary_type.R
- [x] test-bold_italicize_labels_levels.R
- [x] test-bold_p.R
- [x] test-combine_terms.R
- [x] test-continuous_digits_guess.R
- [x] test-custom_tidiers.R
- [x] test-filter_p.R
- [x] test-inline_text.R
- [x] test-modify_caption.R
- [x] test-modify_cols_merge.R
- [x] test-modify_column_alignment.R
- [x] test-modify_column_hide.R
- [x] test-modify_column_indent.R
- [x] test-modify_fmt_fun.R
- [x] test-modify_footnote.R
- [x] test-modify_header.R
- [x] test-modify_spanning_header.R
- [x] test-modify_table_body.R
- [x] test-modify_table_styling.R
- [x] test-plot.R
- [x] test-remove_row_type.R
- [x] test-select_helpers.R
- [x] test-separate_p_footnotes.R
- [x] test-set_gtsummary_theme.R
- [x] test-show_header_names.R
- [x] test-sort_p.R
- [x] test-style_number.R
- [x] test-style_percent.R
- [x] test-style_pvalue.R
- [x] test-style_ratio.R
- [x] test-style_sigfig.R
- [x] test-tbl_butcher.R
- [x] test-tbl_continuous.R
- [x] test-tbl_cross.R
- [x] test-tbl_custom_summary.R
- [x] test-tbl_merge.R
- [x] test-tbl_regression.R
- [x] test-tbl_split.R
- [x] test-tbl_stack.R
- [x] test-tbl_strata.R
- [x] test-tbl_summary.R
- [x] test-tbl_summary_input_checks.R
- [x] test-tbl_survfit.R
- [x] test-tbl_survival.R
- [x] test-tbl_svysummary.R
- [x] test-tbl_uvregression.R

**Comment by shannonpileggi** [comment]
More info on the {testthat} 3.1.0 release here: https://www.tidyverse.org/blog/2021/10/testthat-3-1/

**Comment by ddsjoberg** [comment]
- [ ] test-add_ci.R
- [ ] test-add_difference.R
- [ ] test-add_glance.R
- [ ] test-add_global_p.R
- [ ] test-add_n.R
- [ ] test-add_nevent.R
- [ ] test-add_overall.R
- [ ] test-add_p.tbl_continuous.R
- [ ] test-add_p.tbl_cross.R
- [ ] test-add_p.tbl_summary.R
- [ ] test-add_p.tbl_survfit.R
- [ ] test-add_p.tbl_svysummary.R
- [ ] test-add_p_test_safe.R
- [ ] test-add_q.R
- [ ] test-add_significance_stars.R
- [ ] test-add_stat.R
- [ ] test-add_stat_label.R
- [ ] test-add_vif.R
- [ ] test-as_flex_table.R
- [ ] test-as_gt.R
- [ ] test-as_hux_table.R
- [ ] test-as_hux_xlsx.R
- [ ] test-as_kable.R
- [ ] test-as_kable_extra.R
- [ ] test-as_tibble.R
- [ ] test-assign_dichotomous_value.R
- [ ] test-assign_summary_type.R
- [ ] test-bold_italicize_labels_levels.R
- [ ] test-bold_p.R
- [ ] test-combine_terms.R
- [ ] test-continuous_digits_guess.R
- [ ] test-custom_tidiers.R
- [ ] test-filter_p.R
- [ ] test-inline_text.R
- [ ] test-modify_caption.R
- [ ] test-modify_cols_merge.R
- [ ] test-modify_column_alignment.R
- [ ] test-modify_column_hide.R
- [ ] test-modify_column_indent.R
- [ ] test-modify_fmt_fun.R
- [ ] test-modify_footnote.R
- [ ] test-modify_header.R
- [ ] test-modify_spanning_header.R
- [ ] test-modify_table_body.R
- [ ] test-modify_table_styling.R
- [ ] test-plot.R
- [ ] test-remove_row_type.R
- [ ] test-select_helpers.R
- [ ] test-separate_p_footnotes.R
- [ ] test-set_gtsummary_theme.R
- [ ] test-show_header_names.R
- [ ] test-sort_p.R
- [ ] test-style_number.R
- [ ] test-style_percent.R
- [ ] test-style_pvalue.R
- [ ] test-style_ratio.R
- [ ] test-style_sigfig.R
- [ ] test-tbl_butcher.R
- [ ] test-tbl_continuous.R
- [ ] test-tbl_cross.R
- [ ] test-tbl_custom_summary.R
- [ ] test-tbl_merge.R
- [ ] test-tbl_regression.R
- [ ] test-tbl_split.R
- [ ] test-tbl_stack.R
- [ ] test-tbl_strata.R
- [ ] test-tbl_summary.R
- [ ] test-tbl_summary_input_checks.R
- [ ] test-tbl_survfit.R
- [ ] test-tbl_survival.R
- [ ] test-tbl_svysummary.R
- [ ] test-tbl_uvregression.R
