### ISSUE TITLE
Allow htmlwidgets::setWidgetIdSeed to make html container ids constant

### ISSUE THREAD

**Issue by dchiu911** [ddsjoberg/gtsummary#1239]
**Is your feature request related to a problem? Please describe.**
Every time I regenerate a bookdown HTML report with `tbl_summary()` tables, the HTML  div ids change, causing an appearance in git diff even though there isn't really a change in the table contents. 

**Describe the solution you'd like**
Would it be possible to allow `htmlwidget::setWidgetIdSeed()` to make these randomly generated ids constant to better reflect when the table contents change? I've used this before in other HTML content such as containers for `DiagrammeR`.

**Describe alternatives you've considered**
No other solutions as this is a low impact feature but I thought nice to have.

**Additional context**
For example
```git
<div id="dbboiioyhp" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<div id="jlfiazkihm" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
```
```
#dbboiioyhp .gt_table {
#jlfiazkihm .gt_table {
```

**Comment by ddsjoberg** [comment]
Hello @dchiu911 ! That is an interesting idea, but I am not sure the solution will (or can) live in gtsummary. 

A gtsummary object is essentially a data frame and a list of instructions to print the data frame. By default, most gtsummary tables are printed with {gt} using the `gtsummary::as_gt()` function. What this does is create a series of calls to gt to be executed on the data frame resulting in a gt table in the end. Do you know if it's possible to add the div ids to a gt table? If you can, please show me how you do this, and I can either show you how to incorporate that with a gtsummary workflow or we can look into adding it as a feature if it's not possible for some reason. Sound good?

**Comment by ddsjoberg** [comment]
Oh ok, nice. Where should we go from here? If you get a working example in gt syntax, I can help you integrate that with gtsummary

**Comment by ddsjoberg** [comment]
Hey hey @dchiu911 I am going to go ahead and close this issue for now. But please feel free to re-open if/when you need to return to it.
