### ISSUE TITLE
Hiding missing for dichotomous/categoricals/continuous

### ISSUE THREAD

**Issue by spiralparagon** [ddsjoberg/gtsummary#1243]
Hi!

Is there a way to hide missing for a type of data?
For example, If I'm presenting dichotomous as  {n] / {N], I could skip showing missing as it shows the total population available for the calculation. But I'd like them for say a continous variable. Is there a way to make this separation in "missing = "no"?

**Comment by ddsjoberg** [comment]
Sure! You can use the `remove_row_type()` function to remove any rows needed. Example below

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.6.0'

trial %>%
  select(age, response, trt) %>%
  tbl_summary(by = trt, statistic = response ~ "{n} / {N} ({p}%)") %>%
  remove_row_type(variables = response, type = "missing") %>%
  as_kable() # convert to kable so it will show on GH
```

| **Characteristic** | **Drug A**, N = 98 | **Drug B**, N = 102 |
|:-------------------|:------------------:|:-------------------:|
| Age                |    46 (37, 59)     |     48 (39, 56)     |
| Unknown            |         7          |          4          |
| Tumor Response     |   28 / 95 (29%)    |    33 / 98 (34%)    |

<sup>Created on 2022-05-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
if this isn't the solution you're looking for, please feel free to reopen the issue!
