### ISSUE TITLE
The `fmt_missing()` function in gt will be replaced by `sub_missing()` (former will be soft-deprecated) 

### ISSUE THREAD

**Issue by rich-iannone** [ddsjoberg/gtsummary#1257]
Hey Dan, just wanted to let you know that v. soon the gt function `fmt_missing()` will be replaced with `sub_missing()` (part of the `v0.6.0` release). It's a soft deprecation so `fmt_missing()` will remain for a few more releases but there will be a warning asking people to use `sub_missing()`.

Sorry for the late notice on this but I'm hoping this won't be as brutal a change as before (with the tidyselect/`vars()` stuff).

**Comment by ddsjoberg** [comment]
Thank you for the heads up @rich-iannone !!

And congratulations on today's release! I increased the min version required for gt to the latest :)
