### ISSUE TITLE
Format sections of an output

### ISSUE THREAD

**Issue by kwakuduahc1** [ddsjoberg/gtsummary#1271]
**Is your feature request related to a problem? Please describe.**
The glue function is called on the text that is applied when the statistics parameter is specified.  This prevents calls to formatting functions that would have been called on the text to display it in the viewer, e.g. md()  and html() functions from the gt package.

Would it be possible to apply formatting to only a section of the statistics output leaving the rest out, such as ... `statistics =  everything() ~ "**{sum}**, {median} (p25}-{p75}"`? Currently, the text would be printed with the ** instead of it being formatted as bold.

E.g.
![image](https://user-images.githubusercontent.com/11381582/173538854-c336b346-dd0f-436f-982e-ace90dc234af.png)

**Describe the solution you'd like** 
I formatted this as a word document to demonstrate the potential output.
![image](https://user-images.githubusercontent.com/11381582/173542136-7fe70d24-a066-44f7-8034-a52d982354cf.png)

**Describe alternatives you've considered**
Create 2 separate tables with the desired formatting and use tbl_merge to merge them as a single table.

**Additional context**
None.

**Comment by ddsjoberg** [comment]
This code will work for you.

``` r
library(gtsummary)

tbl <-
  trial %>%
  select(age, marker) %>%
  tbl_summary(
    statistic = everything() ~ "**{sum}**, {median} ({p25}-{p75})"
  ) %>%
  as_gt() %>%
  gt::fmt_markdown(columns = all_stat_cols())
```
![image](https://user-images.githubusercontent.com/26774684/173707564-d4944c0d-50e7-41ac-9255-c43aaf9f7fd7.png)

<sup>Created on 2022-06-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kwakuduahc1** [comment]
A trillion thanks.
