### ISSUE TITLE
Percent function for tbl_continuous 

### ISSUE THREAD

**Issue by kwakuduahc1** [ddsjoberg/gtsummary#1272]
---

When the {p} or {percent} is used in the statistics of a tbl_continuous it throws an error which I think should not be the case. It should calculate the percent over categorical variables and possibly ignore continuous variables.

```r
carData::Salaries %>% 
  select(sex, salary) %>% 
  tbl_continuous(variable = salary, statistic = everything() ~ "{percent}") 
```
The percent function should be the sum of each group divided by the total of all levels in the group.

Best regards.

**Comment by ddsjoberg** [comment]
Thank you for your post. Please update your post with a reproducible example, aka a reprex. A reprex includes both data and code I can run on my machine that replicates your finding. Make the example as short as possible: the minimal amount of code to reproduce your finding and nothing more.

Take just a few minutes to review [reprex.tidyverse.org](https://reprex.tidyverse.org/) for detailed instructions on how to create a reprex.

I am going to go ahead and close this issue for now. But please do re-open the issue after you've added your reproducible example.

**Comment by kwakuduahc1** [comment]
Helo @ddsjoberg , kindly, the feature request I have requested has a reprex that produces the error but should otherwise work. I used the `Salaries` data from the `carData` library which I think you should be able to reproduce on your machine.

Admittedly, I was having a headache in the morning and I may have mistyped a lot.

Kindly have a look at it again.

Best regards.

**Comment by ddsjoberg** [comment]
Review the reprex website. I can't run the code as you've written it.

**Comment by kwakuduahc1** [comment]
Noted, I will improve it. Best.

**Comment by ddsjoberg** [comment]
> Noted, I will improve it. Best.

For example, i have no idea where you're getting the `percent()` function from. Load the needed pkgs, and wrap it all in `reprex::reprex()`

**Comment by kwakuduahc1** [comment]
Oh! I was equally worried at first because I thought it came from the gtsummary package. I was trying to use the `p` for percentage.

The correct code should therefore be:

`
carData::Salaries %>% 

select(sex, salary) %>% 

tbl_continuous(variable = salary, statistic = everything() ~ "{p}") 
`

It also occurred to me an ANOVA could be implemented when the `add_p` is called on such a table, but that is for another day.

Kind regards.

**Comment by ddsjoberg** [comment]
`tbl_continuous()` summarizes a continuous variable, and `"{p}"` is for categorical data. You need to pass a function that summarizes continuous data.

**Comment by kwakuduahc1** [comment]
Yes, `{p}` is for categorical. Kindly consider, as in the example I have given; the `p` function is perfectly legal. It is summing the continuous variable across a categorical variable.

The code below shows how that can be achieved using `dplyr`.
```
library(dplyr)

carData::Salaries %>% 
  group_by(sex) %>% 
  summarise(
    Salary = sum(salary),
  ) %>% 
  mutate(
    Percent = round(Salary/sum(Salary)*100, 1)
  )
```
# A tibble: 2 × 3
  sex         Salary        Percent
  <fct>     <int>         <dbl>
1 Female  3939094     8.7
2 Male      41202370   91.3 

This I think should be doable in the `tbl_continuous` function.

Kind regards.

**Comment by ddsjoberg** [comment]
continuous variable summaries only accept functions that operate on numeric vectors. if you want this functionality, you can define your own function and pass that to `tbl_continuous()`
