### ISSUE TITLE
Error adding difference> There may only be one observation per `group=` per `by=` level

### ISSUE THREAD

**Issue by mbac** [ddsjoberg/gtsummary#1273]
Hi,

I'm trying to add a wilcoxon paired test to my `tbl_summary`, but I keep getting:
```
Error: 'HADS_A': There may only be one observation per `group=` per `by=` level.
There was an error in 'add_p()/add_difference()' for variable 'HADS_D', p-value omitted:
```
(one for each variable in the table.

Everything works fine when I use:
```
mtcars |>
    mutate(vs = as.factor(vs)) |> 
    tbl_summary(
        by = vs,
        statistic = all_continuous() ~ "{median} ({p25}—{p75})"
    ) |> 
    add_difference()
```
But if I try and choose a specific test for the difference…
```
mtcars |>
    mutate(vs = as.factor(vs)) |> 
    tbl_summary(
        by = vs,
        statistic = all_continuous() ~ "{median} ({p25}—{p75})"
    ) |> 
    add_difference(test = all_continuous() ~ "paired.wilcox.test")
```
Ouch…
```
There was an error in 'add_p()/add_difference()' for variable 'mpg', p-value omitted:
Error: 'mpg': There may only be one observation per `group=` per `by=` level.
There was an error in 'add_p()/add_difference()' for variable 'disp', p-value omitted:
Error: 'disp': There may only be one observation per `group=` per `by=` level.
There was an error in 'add_p()/add_difference()' for variable 'hp', p-value omitted:
Error: 'hp': There may only be one observation per `group=` per `by=` level.
There was an error in 'add_p()/add_difference()' for variable 'drat', p-value omitted:
Error: 'drat': There may only be one observation per `group=` per `by=` level.
There was an error in 'add_p()/add_difference()' for variable 'wt', p-value omitted:
Error: 'wt': There may only be one observation per `group=` per `by=` level.
There was an error in 'add_p()/add_difference()' for variable 'qsec', p-value omitted:
Error: 'qsec': There may only be one observation per `group=` per `by=` level.
Warning message:
The `fmt_missing()` function is deprecated and will soon be removed
* Use the `sub_missing()` function instead 
```

**Comment by ddsjoberg** [comment]
Paired tests need the group argument specified. Check out these examples
https://www.danieldsjoberg.com/gtsummary/articles/gallery.html#paired-test

But the error message here certainly can be more informative! I'll update

**Comment by mbac** [comment]
Sorry but I found something else after you helped me solve my problem!

When I run the paired wilcox test I'm only getting a p value, despite using `add_difference()`:
```
    add_difference(
        group = ID,
        include = -all_categorical(),
        test = all_continuous() ~ "paired.wilcox.test"
    )
```
When I run the wilcox.test by itself, it does report a difference and its CIs:
```
> attach(airquality)
> wilcox.test(Ozone, Month, paired = TRUE, conf.int = TRUE, conf.level = 0.95)
# same call as add_difference(), according to "Tests" documentation page

	Wilcoxon signed rank test with continuity correction

data:  Ozone and Month
V = 6536.5, p-value < 2.2e-16
alternative hypothesis: true location shift is not equal to 0
95 percent confidence interval:
 24.50002 39.00001
sample estimates:
(pseudo)median 
      31.99997 
```
Am I still getting something wrong?

Thanks for your outstanding support!

**Comment by mbac** [comment]
PS: screenshot of the table I'm getting with that `add_difference()` call:

<img width="529" alt="image" src="https://user-images.githubusercontent.com/308068/174392452-989c0638-a8d3-431b-9792-d4616f99a8b1.png">

**Comment by ddsjoberg** [comment]
I need to make this more clear in the documentation...just not sure how to do it. 

I personally do not like the psuedo-median difference that is returned, and I think far more people will misinterpret the results than those who will use it appropriately (which is why it's so ambiguous). But I need to make a decision and document it. 

Anyway, here's how you can make it work...just use the `test.args=` argument to request the CI and estimate

``` r
library(gtsummary)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

trial_paired <-
  trial %>%
  select(trt, marker, response) %>%
  group_by(trt) %>%
  mutate(id = row_number()) %>%
  ungroup()

# you must first delete incomplete pairs from the data, then you can build the table
trial_paired %>%
  # delete missing values
  filter(complete.cases(.)) %>%
  # keep IDs with both measurements
  group_by(id) %>%
  filter(n() == 2) %>%
  ungroup() %>%
  # summarize data
  tbl_summary(by = trt, include = -c(id, response)) %>%
  add_difference(test = list(marker ~ "paired.wilcox.test"),
                 test.args = marker ~ list(conf.int = TRUE),
                 group = id) %>%
  as_kable() # convert to kable to display results in GH
```

| **Characteristic**   | **Drug A**, N = 83 | **Drug B**, N = 83 | **Difference** | **95% CI**  | **p-value** |
|:---------------------|:------------------:|:------------------:|:--------------:|:-----------:|:-----------:|
| Marker Level (ng/mL) | 0.82 (0.22, 1.63)  | 0.53 (0.18, 1.26)  |      0.20      | -0.09, 0.48 |     0.2     |

<sup>Created on 2022-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mbac** [comment]
I see, and I realize this is not the best place but… I, for one, would be very grateful if you suggested a different, more sensible approach to the difference in point estimate for non-normally distributed data. I'll bet a lot of users would be, too!
