### ISSUE TITLE
tbl_custom_summary error when using melted dataset

### ISSUE THREAD

**Issue by myensr** [ddsjoberg/gtsummary#1285]
I am getting a cryptic error messages when using tbl_custom_summary with a dataset from data.table melt. I believe there is a bug with tbl_custom_summary that is causing this because the default dataset produced by melt contains a variable called "variable" and that is not tolerated by the tbl_custom_summary function (it can't even be in the dataset, let alone be the variable in the by= option). Made some simple code using the trial dataset to illustrate. 

library(gtsummary)
library(data.table)

#Using the trial data as an example
trial.long <- data.table::melt(trial, id.vars = c('age','trt'), measure.vars=c('ttdeath','marker'), variable.factor = FALSE)

trial.long %>%
  tbl_custom_summary(by = "variable",
                     stat_fns = ~ continuous_summary("value"),
                     statistic = ~ "{mean} ({sd})") 

#repeat but add a new variable 'variable' with a different name, variable2
trial.long <- trial.long %>%
  mutate(variable2 = variable) #Note: the variable 'variable' still exists in the data

#still getting weird error message
trial.long %>%
  tbl_custom_summary( by = "variable2",
                      stat_fns = ~ continuous_summary("value"),
                      statistic = ~ "{mean} ({sd})") 

#now completely delete out the 'variable' variable from the dataset
trial.long <- trial.long %>%
  select(-'variable')

#it now runs without errors
trial.long %>%
  tbl_custom_summary( by = "variable2",
                      stat_fns = ~ continuous_summary("value"),
                      statistic = ~ "{mean} ({sd})")

**Comment by ddsjoberg** [comment]
There was a similar bug fixed in `tbl_summary()` in the last release. Can you install gtsummary v1.6.1 and try again (released this morning)? Thanks for the report!

**Comment by larmarange** [comment]
I tried quickly with the dev version and there is still the bug. Sorry, I didn't have time to investigate where the is a problem
