### ISSUE TITLE
Bug Report: *updated* corruption error when loading gtsummary package

### ISSUE THREAD

**Issue by sandhyapc** [ddsjoberg/gtsummary#1287]
Hello,
I am getting the following error when I load your package "library(gtsummary)"

"Error: package or namespace load failed for ‘gtsummary’ in get(method, envir = home):
lazy-load database '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/gtsummary/R/gtsummary.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4], :
restarting interrupted promise evaluation
2: In get(method, envir = home) :
restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1"

Prior to your 1.6.1 update on 6/22/22 I did not have this issue. I have used the following syntax "install.packages("gtsummary"), library(gtsummary), remotes::install_github("rstudio/gt"), remotes::install_github("ddsjoberg/gtsummary")" but still receive the same error. I am not able to run my code as my functions are no longer recognizable. Any help would be appreciated, thank you!

---

```r
install.packages("gtsummary")
library(gtsummary)
remotes::install_github("rstudio/gt")
remotes::install_github("ddsjoberg/gtsummary")
```

**Comment by ddsjoberg** [comment]
What OS are you on? FYI, before a package is accepted on CRAN, CRAN checks that the package can be loaded on many many (13 I think) different operating systems

```r
sessionInfo()
```

**Comment by sandhyapc** [comment]
oh ok. OS:
Running under: macOS Catalina 10.15.7
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)

**Comment by ddsjoberg** [comment]
this looks like the same issue https://github.com/r-lib/devtools/issues/1980

follow those instructions, and let me know if it resolves, please

**Comment by ddsjoberg** [comment]
Could also be related to cloud drives and syncing 
https://community.rstudio.com/t/error-when-loading-packages/137830/2

**Comment by sandhyapc** [comment]
fixed using the following: https://github.com/r-lib/devtools/issues/1980 👍 . Thank you so much for your help, and for creating an incredible rpackage!
