### ISSUE TITLE
MultiCox get the sample‘s number

### ISSUE THREAD

**Issue by BioYork** [ddsjoberg/gtsummary#1288]
Hi，
In the MultiCox regression of Coxph, if I want to show N in a table, like UnivCox, what should I do？

**Comment by ddsjoberg** [comment]
Thank you for your post. Please update your post with a reproducible example, aka a reprex. A reprex includes both data and code I can run on my machine that replicates your finding. Make the example as short as possible: the minimal amount of code to reproduce your finding and nothing more.

Take just a few minutes to review [reprex.tidyverse.org](https://reprex.tidyverse.org/) for detailed instructions on how to create a reprex.

I am going to go ahead and close this issue for now. But please do re-open the issue after you've added your reproducible example.
