### ISSUE TITLE
Make gt the default printer for all output types

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#1295]
No more default kable, flextable, etc. At some point we can make gt the default

**Comment by bryanpmayfield** [comment]
Is Word output supported in gt now (I don't see that it is, but maybe I'm missing something)? PDF and RTF? What would be the workaround when knitting an R Markdown document to Word (or rendering a Quarto document to Word)? 

Just trying to understand why you want to make this change? I would guess that lots of people still need to output to Word to work with collaborators? Love this package and it has been super useful, especially the ability to use flextable for Word output. Removing that as a default might make things a bit more challenging?

**Comment by ddsjoberg** [comment]
@bryanpmayfield Word support is in the current dev version of gt.

This is on the gtsummary v2.0 roadmap and won't be implemented until all output types are supported by gt. We will not be removing support for other output formats, but we will focus on gt once it's available for Word, RTF, PDF, and HTML.

**Comment by ddsjoberg** [comment]
gt is now the default printer in all cases
