### ISSUE TITLE
add_n option causes superscripts not to render with as_flex_table()

### ISSUE THREAD

**Issue by ChongTienGoh** [ddsjoberg/gtsummary#1299]
Hi, many thanks for this excellent package.  While creating a flextable object from a gtsummary table so that I can create a .docx file I noticed that if I added add_n in the pipeline for the gtsummary table, that causes the superscripts to not render in the header row in flextable.  Removing add_n eliminates this issue.   

```r
library(reprex)
library(gtsummary)
library(flextable)

#load sample dataset
strep_tb <- medicaldata::strep_tb

table <- strep_tb %>% select(gender, arm, baseline_cavitation) %>%
  tbl_summary(
    by = gender,
    missing = "no",
    sort = list(everything() ~ "frequency")
    ) %>%
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 2)) %>%
  bold_labels() %>%
  modify_caption("Fig 1: Simple Table") 

table_add_n <- table %>% add_n()

# print gtsummary table
table
table_add_n

# create flextable objects
ft.table <- table %>% as_flex_table()

ft.table_add_n <- table_add_n %>% as_flex_table()

# print flextable, superscripts in table heading disappears in ft.table_add_n
ft.table
ft.table_add_n
```

**Comment by ddsjoberg** [comment]
Thank you for the report! I'll investigate in the coming weeks!

**Comment by ddsjoberg** [comment]
@ChongTienGoh  this looks like a bug in {flextable}. I've submitted an issue on their site. You can follow the progress here, if you'd like https://github.com/davidgohel/flextable/issues/443

**Comment by ddsjoberg** [comment]
Fixed in flextable.

**Comment by ChongTienGoh** [comment]
thanks! works perfect!
