### ISSUE TITLE
How to add a new statistic, like cv?

### ISSUE THREAD

**Issue by Zoulf001** [ddsjoberg/gtsummary#1301]
I use the function: cv <- function(x) sd(x,na.rm = T)/mean(x,na.rm=T)
but can't return the right value.

cv <- function(x) sd(x,na.rm = T)/mean(x,na.rm=T)

data %>%
  tbl_summary(
    by = Group,
    type = list(all_continuous() ~ "continuous2",
                all_categorical() ~ "continuous2"),
    statistic = all_continuous() ~ c("{N_nonmiss}","{mean}","{sd}","{median}","{min}","{max}","{cv}"),
  )%>%
  bold_labels()

Thank you in advance.

**Comment by ddsjoberg** [comment]
HI @Zoulf001 , This GitHub Issues tracker is for bugs and feature requests. Please ask questions on stackoverflow.com and use the gtsummary tag.
https://stackoverflow.com/questions/63160875
