### ISSUE TITLE
Bug Report: as_hux_table does not preserve footnote numbers

### ISSUE THREAD

**Issue by kendonB** [ddsjoberg/gtsummary#1305]
---

gtsummary includes the nice "1" and the huxtable doesn't

``` r
  library(gtsummary)
  trial %>% 
    tbl_summary(by = trt) 
  
  trial %>% 
    tbl_summary(by = trt) %>% 
    as_hux_table()
```

Just the code as the reprex output isn't converting the html for some reason

**Comment by ddsjoberg** [comment]
Does hextable support numbered footnotes?

**Comment by kendonB** [comment]
I don't believe they do natively, but it could be done in a hacky way manually inserting the numbers. It depends on your dev philosophy for these converting functions. If it's aiming to be as close as possible to the visual output of your tables, this is a bug. If you're aiming to convert to the closest equivalent in their native system, this should be closed.

**Comment by ddsjoberg** [comment]
Thanks for looking into the details @kendonB !

I think implementing new footnote features for huxtable is out of the scope of this package. However, if they add support, please do let me know, and I'll see what I can do to incorporate them there. 🕺🏼
