### ISSUE TITLE
Can I replace all `"<br>"` calls with `"  \n"`?

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#1311]

**Comment by kwakuduahc1** [comment]
Apart from having to type fewer, is there any advantage of the substitution to make it worth the effort? With Quarto around the corner, HTML publishing should be a bit more popular going forward, in my opinion. I suspect <br/> should therefore do better than \n.

**Comment by ddsjoberg** [comment]
The "\n" is supported by most of the output formats as a lineabreaker

**Comment by kwakuduahc1** [comment]
Ok then.

**Comment by kendonB** [comment]
Just in case it's been missed, this does not yet work in the `tab_spanner` argument of `tbl_merge`:

``` r
library(survival)
library(tidyverse)
library(gtsummary)
t1 <-
  glm(response ~ trt + grade + age, trial, family = binomial) %>%
  tbl_regression(exponentiate = TRUE)
t2 <-
  coxph(Surv(ttdeath, death) ~ trt + grade + age, trial) %>%
  tbl_regression(exponentiate = TRUE) %>% 
  modify_header(estimate ~ "**Coefficient\n(SE)**") 
tbl_merge(
  tbls = list(t1, t2),
  tab_spanner = c("**Tumor\nResponse**", "**Time<br>to Death**")
)
```
![image](https://user-images.githubusercontent.com/5327505/194954320-d788e8eb-0a5b-4ceb-a0a1-2427d0ed998e.png)


<sup>Created on 2022-10-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
For some reason, you need two spaces in front of the \n for gt tables. Idk if it'll work everywhere though. I need to do some testing when I have the time

**Comment by kwakuduahc1** [comment]
How do you want the test done so that I can help?

Best.

**Comment by sss203** [comment]
Is it possible to use \n to insert a space when printing output statistics? E.g., within tbl_summary:

statistic = all_continuous() ~ "{mean} ± {sd}  \n{median} ({p25}, {p75})"

If I'd like to see mean/SD on one line, followed by median/IQR on the second line?

**Comment by ddsjoberg** [comment]
@sss203 see example below. Please post any questions you have in the future to stackoverflow.com. When you use the gtsummary tag, I"ll be notified of the post.

```
trial %>%
  select(age) |> 
  tbl_summary(
    statistic = 
      all_continuous() ~ "{mean} ± {sd}  \n{median} ({p25}, {p75})"
  ) |> 
  as_gt() |> 
  gt::fmt_markdown(columns = everything())
```

**Comment by sss203** [comment]
Hmm this seems to lead to some odd formatting of the rest of the table:

<img width="502" alt="Screenshot 2023-03-01 at 10 27 28 AM" src="https://user-images.githubusercontent.com/57676735/222184985-546f0ac0-9dc1-4384-b13a-15cdae84ba9e.png">


Will do, thanks!

**Comment by ddsjoberg** [comment]
Update column call to `columns = all_stat_cols()`
