### ISSUE TITLE
Feature request: allow `include` argument in `tbl_regression` to use factor levels 

### ISSUE THREAD

**Issue by kendonB** [ddsjoberg/gtsummary#1313]
**Is your feature request related to a problem? Please describe.**
I have a use case where I have a factor (region) with only a few levels of interest for the reader because the rest are quite small. I'd like to keep 6 regions as rows, and replace the remainder with a row saying "Other regions" as the variable name and "< X" as the value.

**Describe the solution you'd like**
The ability to specify factor levels in `include`, in addition to variable names.

**Describe alternatives you've considered**
Removing rows after converting to flextable doesn't seem to be supported.

**Comment by ddsjoberg** [comment]
In the current dev version of the pkg, the `remove_row_type()` has the ability to select levels to remove from the output.
https://www.danieldsjoberg.com/gtsummary/dev/reference/remove_row_type.html

Will that work for you?

**Comment by kendonB** [comment]
Yes that works nicely. Thanks!

**Comment by kendonB** [comment]
I'm not sure if this is a general enough use case for you but I'd also like to replace these removed rows with one at the bottom of the section saying "Other regions" as the variable and "< XX" as the value.

Would something like that be worth including natively or should that be left to the rendering packages (gt, flextable etc)?

**Comment by ddsjoberg** [comment]
you can use `modify_table_body()` to directly edit the data frame that will be printed FYI You can delete rows, overwrite labels, etc.

**Comment by larmarange** [comment]
> I'm not sure if this is a general enough use case for you but I'd also like to replace these removed rows with one at the bottom of the section saying "Other regions" as the variable and "< XX" as the value.

If you have few observations for these regions, you should not keep the `region` variable in your model as it is. You should merge these other regions into a unique modality (cf. https://forcats.tidyverse.org/reference/fct_lump.html ) and use this recoded variable in your model.

**Comment by kendonB** [comment]
@larmarange the column I'm talking about is not the number of observations, it's the coefficient estimate from a regression.

**Comment by ddsjoberg** [comment]
@larmarange 's suggestion is a good one, and one that I agree with. I would update your model to lump together regions with few observations into a single misc region in the modelling stage.

**Comment by kendonB** [comment]
Again, this is not motivated by a small number of observations. It's about highlighting select regions of interest
