### ISSUE TITLE
Bug Report: stars p-value footnote should be removed with not including stars in add_significance_stars

### ISSUE THREAD

**Issue by kendonB** [ddsjoberg/gtsummary#1315]
---

If the user doesn't include the `{stars}` in `add_significance_stars`, the footnote showing e.g. `p<0.05**` should not appear.

Consider also renaming the function as is doesn't only add significance stars. Something like `rearrange_estimates` would be more general.

``` r
library(gtsummary)

tbl <-
  lm(time ~ ph.ecog + sex, survival::lung) %>%
  tbl_regression(label = list(ph.ecog = "ECOG Score", sex = "Sex"))

add_significance_stars_ex3 <-
  tbl %>%
  add_significance_stars(
    hide_se = TRUE,
    pattern = "{estimate}  \n({std.error})"
  ) %>%
  modify_header(estimate ~ "**Beta (SE)**") %>%
  modify_footnote(estimate ~ "SE = Standard Error", abbreviation = TRUE) 
#> `pattern=` argument does not contain '{stars}' column, and no stars will be
#> added.

add_significance_stars_ex3
```

![image](https://user-images.githubusercontent.com/5327505/184789880-7001e54e-4d8f-4ac4-acfe-c5c54bc6e8f3.png)

<sup>Created on 2022-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
I export a modify_column_merge() function for merging. This one is meant for stars so I think it's ok to leave the footnote.
