### ISSUE TITLE
Feature request: More flexible tab_spanner controls with `tbl_merge`

### ISSUE THREAD

**Issue by kendonB** [ddsjoberg/gtsummary#1316]
**Is your feature request related to a problem? Please describe.**
I'm trying to merge two SE-under-estimate regressions, each with one values column with estimates and standard errors.

``` r
library(gtsummary)

tbl <-
  lm(time ~ ph.ecog + sex, survival::lung) %>%
  tbl_regression(label = list(ph.ecog = "ECOG Score", sex = "Sex"))

add_significance_stars_ex3 <-
  tbl %>%
  add_significance_stars(
    hide_se = TRUE,
    pattern = "{estimate}  \n({std.error})"
  ) %>%
  modify_header(estimate ~ "**Beta (SE)**") %>%
  modify_footnote(estimate ~ "SE = Standard Error", abbreviation = TRUE) 
#> `pattern=` argument does not contain '{stars}' column, and no stars will be
#> added.

tbl_merge(list(add_significance_stars_ex3, add_significance_stars_ex3))
```

<sup>Created on 2022-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

![image](https://user-images.githubusercontent.com/5327505/184796923-75600dc7-807d-43b8-8c48-754b26a3bb7f.png)

**Describe the solution you'd like**
Ideally, the function would be clever enough in this case to see that 1) the column names are the same and 2) each table has a single values column then use the common column name as the first-row spanner across the two tables' columns. Then there could be another argument to set the individual column names. I would like "(1)" and (2)" in this case.

**Describe alternatives you've considered**
I tried setting the column names as (1) and (2) first then setting the tab_spanner argument but then the footnote numbers end up in the wrong place.

**Comment by ddsjoberg** [comment]
What are you proposing the headers become?

**Comment by kendonB** [comment]
For this example, the first-row spanning header would be the "Beta (SE)^1,2" (Where Table 1 and Table 2 is now). and the second row headers would be (1) and (2).

I don't really know what the best way to address this is. `stargazer`'s approach is to just make the table directly from the two (or more) lm models but it results in such an unwieldy interface. Happy to help brainstorm

**Comment by kendonB** [comment]
I think I've figured out what should be the correct approach. Something like this:

``` r
library(gtsummary)
#> #StandWithUkraine

tbl <-
  lm(time ~ ph.ecog + sex, survival::lung) %>%
  tbl_regression(label = list(ph.ecog = "ECOG Score", sex = "Sex"))

tbl1 <-
  tbl %>%
  modify_column_merge("{estimate}<br>({std.error})") %>%
  gtsummary::modify_column_hide(c("ci", "p.value")) %>% 
  modify_header(estimate ~ "(1)")

tbl2 <- tbl1 %>% 
  modify_header(estimate ~ "(2)")

# tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Beta<br>(SE)**", "**Beta<br>(SE)**")) %>%
#   modify_footnote(SPANNER_LABEL_HERE ~ "SE = Standard Error", abbreviation = TRUE)
```
but there is no label for the spanner I can see (which is where the footnote should go):
```
show_header_names(tbl_merge(list(tbl1, tbl2), tab_spanner = c("**Beta<br>(SE)**", "**Beta<br>(SE)**")))
#> ℹ As a usage guide, the code below re-creates the current column headers.
#> modify_header(
#>   label = '**Characteristic**',
#>   estimate_1 = '(1)',
#>   estimate_2 = '(2)'
#> )
#> 
#> 
#> Column Name   Column Header      
#> ------------  -------------------
#> label         **Characteristic** 
#> estimate_1    (1)                
#> estimate_2    (2)
```

<sup>Created on 2022-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
You're right, there is no way to place footnotes in spanning header from within gtsummary. You'd need to convert to gt (or whatever print engine you're using) and add it there. I had this issue (https://github.com/ddsjoberg/gtsummary/issues/1011) open for a while, but decided to just move on (trying to take a dev break from this package for a while, and focus on other work).
