### ISSUE TITLE
Bug Report: continuous variable default summary with n < 10

### ISSUE THREAD

**Issue by bcjaeger** [ddsjoberg/gtsummary#1318]
Continuous variables are automatically treated like categorical variables when the data have less than 10 rows. This may be the intended way to summarize continuous data in smaller samples, but may be a bug if it's not intended. 

```r

library(gtsummary)

tbl_make <- function(n, ...){
 
 group <- sample(c(1,2), size = n, replace=TRUE) %>% 
  factor(labels = c("A", "B"))
 
 data.frame(group = group,
            continuous_variable = rnorm(n)) %>% 
  tbl_summary(by = group, ...)
 
}
```

```r
# output looks just like I would expect for n >= 10
tbl_make(n = 10)
```

<html>
<body>

Characteristic | A, N = 6 | B, N = 4
-- | -- | --
continuous_variable | 0.63 (0.36, 1.01) | 0.16 (-0.62, 0.44)
1 Median (IQR)

</body>
</html>

```r
# With n < 10, The continuous variable is automatically categorized. Is this intentional?
tbl_make(n = 9)
```
<html>
<body>

Characteristic | A, N = 61 | B, N = 31
-- | -- | --
continuous_variable |   |  
-0.568256394209814 | 1 (17%) | 0 (0%)
0.128730399718633 | 1 (17%) | 0 (0%)
0.16098727888922 | 1 (17%) | 0 (0%)
0.162943537657024 | 1 (17%) | 0 (0%)
0.537860461823971 | 0 (0%) | 1 (33%)
0.621441734749362 | 1 (17%) | 0 (0%)
0.982586926382029 | 1 (17%) | 0 (0%)
1.23422295776402 | 0 (0%) | 1 (33%)
1.63630831944991 | 0 (0%) | 1 (33%)
1 n (%)

</body>
</html>

```r
# it's easy enough for a user to fix, just seemed like strange defaults
tbl_make(n = 9, type = list(continuous_variable ~ "continuous"))
```

<html>
<body>

Characteristic | A, N = 4 | B, N = 5
-- | -- | --
continuous_variable | -0.88 (-1.05, -0.62) | -0.32 (-0.62, 0.60)
1 Median (IQR)

</body>
</html>

**Comment by ddsjoberg** [comment]
hello @bcjaeger ! thanks for the post.

Yes, this is indeed the intended behavior. I documented it here https://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html#type-argument-1, but it's often missed.

If i could do it all over again, i would not have made this 10-level cutoff 🤷🏼

**Comment by ddsjoberg** [comment]
> Ah I see! Sorry I missed that in the documentation. Thank you!

No worries ! It was a bad design choice! Haha
