### ISSUE TITLE
Bug Report: Sugar from add_significance_stars should be in modify_column_hide

### ISSUE THREAD

**Issue by kendonB** [ddsjoberg/gtsummary#1323]
The `add_significance_stars` function nicely merges the rows associated with factor names and the omitted category (see second image). Is it possible to add the merging sugar from that function into `modify_column_hide`?

``` r
library(gtsummary)

tbl <-
  lm(time ~ ph.ecog + sex + factor(status), survival::lung) %>%
  tbl_regression(label = list(ph.ecog = "ECOG Score", sex = "Sex"))

tbl %>%
  modify_column_merge("{estimate}<br>({std.error})") %>%
  gtsummary::modify_column_hide(c("ci", "p.value"))
```

![image](https://user-images.githubusercontent.com/5327505/186066856-827c1462-031e-4bd0-89b6-a85998634922.png)

``` r
tbl %>% 
  add_significance_stars(
    hide_se = TRUE,
    pattern = "{estimate}<br>({std.error})"
  )
```

![image](https://user-images.githubusercontent.com/5327505/186066891-0deb45a2-b72d-4b65-80e6-1650abc8ddbd.png)

<sup>Created on 2022-08-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Try using it like this:

```r
modify_column_merge("{estimate}<br>({std.error})", rows = !is.na(estimate)) 
```

I think that is all i do when adding the stars.

**Comment by ddsjoberg** [comment]
is this the sugar you're referring to?
