### ISSUE TITLE
Bug Report: Weird tbl_summary miscalculations

### ISSUE THREAD

**Issue by kwakuduahc1** [ddsjoberg/gtsummary#1334]
Brief description of the problem.

There is a weird bug where tbl_summary incorrectly rounds up figures when calculating percentages.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gtsummary)

x <- data.frame(Level = c(
  rep("A", 483),
  "B")) 
```

## prop.table
```{r}
table(x$Level) %>% prop.table()
```
![image](https://user-images.githubusercontent.com/11381582/188126932-4895de42-74ff-46c0-ba03-3488006f961e.png)

## tbl_summary
```{r}
tbl_summary(x)
```
![image](https://user-images.githubusercontent.com/11381582/188126997-5f211c65-852b-4ba1-aa99-fc1fa06154b4.png)

**Comment by ddsjoberg** [comment]
It's not a bug, it's been rounded. You can use the digits argument to modify the default rounding

**Comment by kwakuduahc1** [comment]
Thank you for your response. However, the rounding affects the counts too which is not aesthetically pleasing.

````
```{r}
tbl_summary(
  x,
  digits = everything() ~ 2
  )
```
````
![image](https://user-images.githubusercontent.com/11381582/188139636-0b587152-ea9a-4e5c-99de-8d8c54528edc.png)

It is a bug in my opinion because Zero/No rounding of 0.002 cannot and should not be 0.2

![image](https://user-images.githubusercontent.com/11381582/188139820-9fed2d79-f89a-48b9-ace9-b0817f95657e.png)


Thank you for your patience.

**Comment by ddsjoberg** [comment]
Did you read the function help file? Please review and let me know if it's unclear

**Comment by kwakuduahc1** [comment]
Yes, that is it. I should actually know this by now.

````
```{r}
tbl_summary(
  x,
  digits = everything() ~ c(0, 1)
  )
```
````
![image](https://user-images.githubusercontent.com/11381582/188148618-0f2f2f68-ecb3-4a29-b5a5-8877c7949bf3.png)

I have also identified why I was thinking about it wrongly 🙇‍♂️: I was rounding the proportion before the percent function in my head, as such it was always going to be 0 but that is wrong thinking on my part; `percent` before `rounding`
