### ISSUE TITLE
Feature request: Add vignette that shows how to use {gtsummary} with R Shiny

### ISSUE THREAD

**Issue by parmsam** [ddsjoberg/gtsummary#1335]
Do not use this form to ask a question, or ask for assistance. Instead, ask on <https://stackoverflow.com/> using the gtsummary tag.
Questions about a function's use will be closed without a response.

**Is your feature request related to a problem? Please describe.**

Thanks for the package! gtsummary objects need to be converted into gt objects in order to render in R Shiny. Having this in a vignette would help first time users who want to use the package in a Shiny app.

**Describe the solution you'd like**

Short vignette showing example Shiny app with {gtsummary}

**Describe alternatives you've considered**

**Additional context**

Here is an example app that could be included in a vignette called `gtsummary + shiny`. I can submit a PR if that's okay.

```
library(shiny)
library(gtsummary)
library(gt)
library(datasets)
listDatasets <- c("USArrests", "VADeaths", "Seatbelts")
shinyApp(
  ui = fluidPage(
    selectInput("dataset", "Select dataset", listDatasets),
    gt::gt_output('table')
  ),
  server = function(input, output) {
    selectedData <- reactive({
      req(input$dataset)
      gtsummary::as_tibble(get(input$dataset, "package:datasets"))
    })
    gtObject <- reactive({
      req(input$dataset)
      gts_object <- gtsummary::tbl_summary(selectedData())
      gtsummary::as_gt(gts_object)
    })
    output$table <- render_gt({
      req(input$dataset)
      gtObject()
    })
  }
)
```

**Comment by ddsjoberg** [comment]
@parmsam ! thanks for the post, and it sounds like a great suggestion and a PR would be great.

- rather than a vignette, let's do an article (`usethis::use_article()`). it'll be posted to the website, but won't be shipped as a proper vignette with the package from CRAN.
- do you plan on making a live app as the example? where would that live?

**Comment by parmsam** [comment]
Yes, that sounds good instead. I can host the simple example app on my [shinyapps](https://www.shinyapps.io/#) account, if needed. Here's the app: https://parmsam.shinyapps.io/example-gtsummary-app/

**Comment by ddsjoberg** [comment]
hey @parmsam , apologies for the delay; i was caught up with work. I still need some time to think about where/how to incorporate Shiny examples. I'll get back to you!
