### ISSUE TITLE
Adding the effect-sizes

### ISSUE THREAD

**Issue by Generalized** [ddsjoberg/gtsummary#1337]
Dear Authors, in continuation to my previous request, I believe it would be very beneficial to implement something like _add_effect_size()_ and _add_effect_interpretation()_. The package [effectsize](https://easystats.github.io/effectsize/) provides lots of them along with appropriate confidence intervals and interpretation rules ("small", "moderate", "large" and so on) from a number of authors. Reporting the effect size follows the best practices advised also in the pharmaceutical industry (though not a panaceum and the practical significance, i.e. the MCID should be defined anyway).

For instance:
- Cohen's D and Hedges' G (unequal variances) + maybe the "overlap" + NNT + "common language interpretation" measures for continuous data that can be summarized with arithmetic means meaningfully (typically following parametric tests). This may be helpful too: https://rpsychologist.com/cohend/ | https://rpsychologist.com/cohend/ | https://imaging.mrc-cbu.cam.ac.uk/statswiki/FAQ/effectSize | https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3444174/ | https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0058777
- Rank biserial, standardized Wilcoxon statistic, Cliff's delta for data typically analysed non-parametrically.
- OR, RR, Yule, Crammer V/phi for categorical ones
and so on.

**Comment by ddsjoberg** [comment]
FYI The add_effect_size() function you're suggesting is encompassed in `add_difference()`. Just like `add_p()`, the `add_difference()` function is customizable.

Do you feel like you're in a position to assist in making these updates for the package?

**Comment by ddsjoberg** [comment]
There is a lot here, and I am going to go ahead and close this issue for now. If you're available to assist in implementing any of these methods, please open a separate issue for a single method/ Please review the code for implementing custom `add_p()` and `add_difference()` methods, and include codes to implementing the method you're requesting.
