### ISSUE TITLE
Bug Report: tbl_svysummary /percent =row issue

### ISSUE THREAD

**Issue by AurelienDasre** [ddsjoberg/gtsummary#1352]
Hello,

I have an issue when I try to make a simple statistic table on weighted data with tbl_svysummary.

The next code give me a table with only NA results in all the cells. :

selfumw %>% tbl_svysummary(
  include=c("fum","qager_rec"),
  by="fum",
  statistic=list(all_categorical()~"{p}% ({n})"),
  percent="row")

while it's working good when I try to  do => percent="col".

It's also work for unweighted data with the code below:

selfum %>% tbl_summary(
  include=c("fum","qager_rec"),
  by="fum",
  statistic=list(all_categorical()~"{p}% ({n})"),
  percent="row")

The code was running well last year I don't know why it's not working anymore. Do you have an idea?

Thank you in advance for ay help.

Berst regards.

Aurélien.

**Comment by ddsjoberg** [comment]
Thank you for your post. Please update your post with a reproducible example, aka a reprex. A reprex includes both data and code I can run on my machine that replicates your finding. Make the example as short as possible: the minimal amount of code to reproduce your finding and nothing more.

Take just a few minutes to review [reprex.tidyverse.org](https://reprex.tidyverse.org/) for detailed instructions on how to create a reprex.

I am going to go ahead and close this issue for now. But please do re-open the issue after you've added your reproducible example.
