### ISSUE TITLE
Bug Report: Bold not preserved in as_flex_table()

### ISSUE THREAD

**Issue by kendonB** [ddsjoberg/gtsummary#1361]
``` r
library(gtsummary)

lm(mtcars$mpg ~ mtcars$cyl) %>%
  tbl_regression()
```
![image](https://user-images.githubusercontent.com/5327505/194972653-3006a202-a98d-418b-afed-991b39f6c0e1.png)
```r
lm(mtcars$mpg ~ mtcars$cyl) %>%
  tbl_regression() %>% 
  as_flex_table()
```
![image](https://user-images.githubusercontent.com/5327505/194972676-14f5da37-5de2-48ef-820f-f613a38b5ca5.png)

<sup>Created on 2022-10-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Yeah, I know. We use markdown syntax for bold, italics, etc. But flextable, as far as I know, doesn't recognize MD syntax.

You can use flextable functions to bold the entire header row.

Do you know if flextable can utilize markdown syntax or even apply bold/italic styling to a partial string in the header?

**Comment by kendonB** [comment]
@davidgohel, would it be possible to recognise markdown syntax for bolding subsets of text in cells?

**Comment by davidgohel** [comment]
@kendonB see https://ardata-fr.github.io/flextable-book/cell-content-1.html#multi-content

There are several ways to do it in flextable, but not with markdown. One way to do it is to use dedicated functions, `as_i()`:

```r
ft <- flextable(data.frame(a= 1)) %>% theme_box() %>% 
  mk_par(j = "a", part = "header", 
         value = as_paragraph(as_i("aaaaa"), "\nbbbbb\n ", as_b("ccccc"))) %>% 
  bold(part = "header", bold = F)

ft
```

<img width="808" alt="Capture d’écran 2022-10-11 à 09 19 51" src="https://user-images.githubusercontent.com/4331618/195021704-f2898ccd-f412-4d05-9137-ec06fdfc66ab.png">

**Comment by davidgohel** [comment]
@ddsjoberg 'flextable' is allowing multiple formats per chunk in all cells. You can use `compose()/mk_par()` to create a whole paragraph made of chunks, you can also add content to existing paragraphs in cells with `append_chunks()`, `prepend_chunks()`. These are working for all cell/rows/columns in headers/body and footers.

**Comment by ddsjoberg** [comment]
@davidgohel thank you kindly for the details! I didn't know about those functions!

Notes to self:
Implementation here will be similar to what I did for `kableExtra(format = 'latex')`. I'll need to use the string substituting functions to map the markdown syntax to flextable code.

**Comment by ddsjoberg** [comment]
Dear @davidgohel , Thank you again for the details on how to incorporate bold/italic in the column headers.

Is there a way to do the same for spanning header rows? Something like this:

``` r
ft <-
  mtcars[1:4, 1:4] |> 
  flextable::flextable() 

ft |> 
  flextable::add_header_row(
    values = flextable::as_paragraph(flextable::as_b("SPANNING")),
    colwidths = 4
  )
#> Error in inverse.rle(structure(list(lengths = colwidths, values = values), : invalid 'rle' structure
```

<sup>Created on 2022-10-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
OK, I think I figured it out. You need to first define a spanning header, and THEN you can overwrite it with a composed spanning header that includes partial bold/italic text.

``` r
library(flextable)

mtcars[1:4, 1:4] |> 
  flextable() |> 
  add_header_row(values = c("no md1", "no md2"), colwidths = c(2, 2)) |>
  compose(i = 1, j = 1:2, part = "header", value = as_paragraph(as_b("bold"), "not bold")) |>
  compose(i = 1, j = 3:4, part = "header", value = as_paragraph(as_b("bold2"), "not bold"))
```
![image](https://user-images.githubusercontent.com/26774684/197658969-9c83a95f-3737-49de-a629-5d1d5f6899b5.png)

<sup>Created on 2022-10-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by davidgohel** [comment]
Hello, 

Sorry for the delay

That's the correct way. I already enabled support for `as_paragraph()` in functions `add_header_lines()` and `add_header_lines()`. I will try to do the same for `add_header_row()` and `add_footer_row()` soon so that you can do it directly.

**Comment by ddsjoberg** [comment]
Thank you @davidgohel !

**Comment by ddsjoberg** [comment]
@kendonB this is implemented in the dev version of gtsummary. Can you please check it out?
https://www.danieldsjoberg.com/gtsummary/dev/reference/as_flex_table.html#details-1

**Comment by kendonB** [comment]
Looks great! In my example, the italicised footnote marker doesn't get passed through - should that also work now?

**Comment by ddsjoberg** [comment]
Thanks for the quick check.

Nope, it only works for headers and spanning headers. You can still add bold/italic footnotes with `as_flex_table() %>% <flextable functions for adding footnotes>`
