### ISSUE TITLE
Feature request: display both row and column percents?

### ISSUE THREAD

**Issue by browne123** [ddsjoberg/gtsummary#1363]
I love the ability to show either column or row percents, but there are some situations when both would be useful.

Could there be a way to have tables show both "row" and "column" percents at the same time (i.e. percent = c("column", "row"))?

I have attempted to calculate these using the "statistic" option but have not been able to.

**Comment by ddsjoberg** [comment]
Thanks for the post @browne123 !

This update would require some pretty major updates (HUGE), and unfortunately don't have the bandwidth to implement.

**Comment by browne123** [comment]
No problem; we’re big fans of gtsummary and use it all the time, thanks for writing.

Ethan
From: Daniel Sjoberg ***@***.***>
Date: Friday, October 14, 2022 at 3:08 PM
To: ddsjoberg/gtsummary ***@***.***>
Cc: browne123 ***@***.***>, Mention ***@***.***>
Subject: Re: [ddsjoberg/gtsummary] Feature request: display both row and column percents? (Issue #1363)

Thanks for the post @browne123<https://github.com/browne123> !

This update would require some pretty major updates (HUGE), and unfortunately don't have the bandwidth to implement.

**Comment by larmarange** [comment]
In fact, it is already possible using `tbl_custom_summary()`. ;-)

``` r
library(gtsummary)

cross_table_summary <- function(data, full_data, variable, by, ...) {
  if (!is.null(by)) {
    # removing missing values
    full_data <- full_data %>%
      dplyr::filter(!is.na(.data[[variable]]) & !is.na(.data[[by]]))
    
    n <- data %>% nrow()
    n_total <- full_data %>%nrow()
    n_row <- full_data %>%
      dplyr::filter(.data[[variable]] %in% unique(data[[variable]])) %>%
      nrow()
    n_col <- full_data %>%
      dplyr::filter(.data[[by]] %in% unique(data[[by]])) %>%
      nrow()
  } else {
    # removing missing values
    full_data <- full_data %>%
      dplyr::filter(!is.na(.data[[variable]]))
    
    n <- data %>% nrow()
    n_total <- full_data %>%nrow()
    n_row <- n
    n_col <- n_total
  }
  
  dplyr::tibble(
    n = n,
    n_row = n_row,
    n_col = n_col,
    n_total = n_total,
    cell_prop = n / n_total,
    row_prop = n / n_row,
    col_prop = n / n_col
  )
}

trial %>%
  tbl_custom_summary(
    include = grade,
    by = trt,
    stat_fns = ~ cross_table_summary,
    statistic = ~ "row: {row_prop}% / col: {col_prop}% / cell: {cell_prop}%",
    digits = ~ style_percent,
    overall_row = TRUE,
    overall_row_last = TRUE
  ) %>%
  add_overall(last = TRUE) %>%
  as_kable()
```

| **Characteristic** |        **Drug A**, N = 98        |       **Drug B**, N = 102        |        **Overall**, N = 200        |
|:-------------------|:--------------------------------:|:--------------------------------:|:----------------------------------:|
| Grade              |                                  |                                  |                                    |
| I                  | row: 51% / col: 36% / cell: 18%  | row: 49% / col: 32% / cell: 16%  |  row: 100% / col: 34% / cell: 34%  |
| II                 | row: 47% / col: 33% / cell: 16%  | row: 53% / col: 35% / cell: 18%  |  row: 100% / col: 34% / cell: 34%  |
| III                | row: 48% / col: 32% / cell: 16%  | row: 52% / col: 32% / cell: 16%  |  row: 100% / col: 32% / cell: 32%  |
| Overall            | row: 49% / col: 100% / cell: 49% | row: 51% / col: 100% / cell: 51% | row: 100% / col: 100% / cell: 100% |

<sup>Created on 2022-10-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Oh my goodness, thank you Joseph!

**Comment by browne123** [comment]
That’s great – thank you!

From: Daniel Sjoberg ***@***.***>
Date: Saturday, October 15, 2022 at 8:33 AM
To: ddsjoberg/gtsummary ***@***.***>
Cc: browne123 ***@***.***>, Mention ***@***.***>
Subject: Re: [ddsjoberg/gtsummary] Feature request: display both row and column percents? (Issue #1363)

Oh my goodness, thank you Joseph!
