### ISSUE TITLE
How to drop  ” 1CI = Confidence Interval” in the footnote of the tables produced by tbl_summaryBug Report: <Describe bug>

### ISSUE THREAD

**Issue by zawkzaw** [ddsjoberg/gtsummary#1365]
Hello!

May I know drop  ” 1CI = Confidence Interval” in the footnote of the tables produced by tbl_summary? 

I try the following but failed.

modify_footnote(everything() ~ NA) 
modify_footnote(update = everything() ~ NA) 
modify_footnote(stat_0 ~ NA)

Thanks in advance

Regards

Ko Ko Zaw

**Comment by ddsjoberg** [comment]
Dear @zawkzaw , 

Thanks for the post. I am happy to answer questions. Please post your question to stackoverflow.com. If you include the gtsummary tag, I'll be notified of your post.

Your post should include a minimal reproducible example, aka a minimal reprex. A reprex includes both data and code I can run on my machine. If needed, include a mock-up of what you want your results to look like.

Take just a few minutes to review reprex.tidyverse.org for detailed instructions on how to create a reprex.
