### ISSUE TITLE
Use `ggstats::ggcoef_plot()` instead of `GGally::ggcoel_plot()`

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#1367]
It has recently been decided to move `ggcoef_*()` family of functions to a separate package (`ggtsats`) to facilitate maintenance and updated.

`ggstats` is now on CRAN. `GGally` will reexport `ggstats` functions. But it could be wise to use `ggtstats::ggcoef_plot()` instead of `GGally::ggcoef_plot()` in https://github.com/ddsjoberg/gtsummary/blob/main/R/plot.R

**Comment by ddsjoberg** [comment]
sounds good!
