### ISSUE TITLE
Despite providing grouping variable there is an error message when running paired tests. There may only be one observation per group= per by= level - problem.

### ISSUE THREAD

**Issue by TAOS25** [ddsjoberg/gtsummary#1377]
Dear Sir, thank you for package. I  found a problem that I cant resolve. I am getting error regarding paired test. Similar issue was reported but there was a group variable missing in the code. I specified gruop variable, nonetheless I still get the same error message:"

# insert reprex here
data(lalonde)
variables <- lalonde%>% select(age,treat)
table1 <- 
  tbl_summary(
    variables,
    by = treat, # split table by group
    statistic = list(all_continuous() ~ "{mean} ({sd})"),
    digits = all_continuous() ~ 2,
    missing_text = "(Missing)") %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p(list(all_continuous() ~ "paired.t.test"),group="treat") %>% 
  modify_header(label = "**Treatment**") %>% # update the column header
  bold_labels() 

I get the following message:

Error: 'age': There may only be one observation per `group=` per `by=` level.

I dont if it is a bug or I am doing sth wrong. I would be most grateful if you could look at it. 
Best regards
Tadeusz Osadnik

**Comment by ddsjoberg** [comment]
it looks like you've also posted this to stackoverflow (which is where questions should be posted)
https://stackoverflow.com/questions/74221773
