### ISSUE TITLE
Feature request: Welsh ANOVA with var.equal = FALSE

### ISSUE THREAD

**Issue by yuryzablotski** [ddsjoberg/gtsummary#1382]
Dear Daniel,

thanks for your amazing package, I love every bit of it and use it more and more in my daily scientific job.

As I went trough possible simple tests, I realised there is a support for a Welsh t.test, but not Welsh ANOVA (only usual, Fisher's ANOVA):

would be nice if it would be possible to use code like this:

trial %>% 
  select(age, stage) %>% 
  tbl_summary(
    by = stage, 
    statistic = age ~ "mean ({sd})") %>% 
  add_p(
    age ~ "aov", 
    pvalue_fun = ~ style_pvalue(.x, digits = 2),
    test.args = age ~ list(var.equal = FALSE))

As for now, var.equal = F and var.equal = T produce identical result.

Here is the result which would be Welsh ANOVA:

ggbetweenstats(trial, stage, age, var.equal = F)

Kind regards!
Yury

**Comment by ddsjoberg** [comment]
Dear @yuryzablotski ! Thank you for the note.

1. You can create a custom function to calculate any statistics/p-values you may need, even if it's not built into the package.
2. Is there are base R way to get the pvalue you are after? We can't incorporate another pkg dependency unfortunately .

**Comment by yuryzablotski** [comment]
Dear Daniel, 

thanks for your replay! Yes, there is a base R way for Welch's ANOVA:

stats::oneway.test(age ~ stage, data = trial, var.equal = F)

**Comment by ddsjoberg** [comment]
I'll leave this PR open to implement at some point. But I don't have a timeline...not sure when i'll have time for it.

**Comment by yuryzablotski** [comment]
👍 it's not urgent.

**Comment by tsurikova-nadezhda** [comment]
Dear Yury, I saw your question and have the same problem, here is my solution. Kind regards, Nadezhda.
> Welsh ANOVA

test_welch_anova <- function(data, variable, by, ...) {
  # drop NA
  data <- data %>% drop_na({{ variable }}, {{ by }})
  
  # making test
  formula <- as.formula(paste(variable, by, sep = " ~ "))
  test_result <- oneway.test(formula, data = data, var.equal = FALSE)
  
  # return result
  return(test_result$p.value)
}
