### ISSUE TITLE
Bug Report: as_hux_xlsx fails to indent row w/ numeric value

### ISSUE THREAD

**Issue by shannonpileggi** [ddsjoberg/gtsummary#1386]
Levels that only have numbers in them do not indent with the `as_hux_xlsx()` export.

```r
library(gtsummary)
library(dplyr)
library(huxtable)

t1 <- trial |> 
  mutate(
    age_category = case_when(
      is.na(age) ~ NA_character_,
      age == 6 ~ "6",
      age > 6 ~ "7 - 83")
  ) |> 
  select(trt, age_category, response) |> 
  tbl_summary()

t1
```

![image](https://user-images.githubusercontent.com/17747575/202266825-23796617-e424-4597-9960-87169213ced8.png)

```
as_hux_xlsx(t1, "table1.xlsx")
```

![image](https://user-images.githubusercontent.com/17747575/202267160-346784e6-e4ba-4862-9d93-318297765744.png)

I haven't been able to get a reprex together yet to see if `quick_xlsx()` produces the same result, but I can keep working on that.

**Comment by ddsjoberg** [comment]
FYI, this occurs with a data frame passed directly to `huxtable::quick_xlxs()` as well.

**Comment by ddsjoberg** [comment]
@shannonpileggi we can either transfer the issue to huxtable, or experiment with some non-breaking unicode spaces and see if that can solve the issue
