### ISSUE TITLE
Bug Report: add_nevent throws an error when using tbl_survfit + survfit2

### ISSUE THREAD

**Issue by kentm4** [ddsjoberg/gtsummary#1389]
The following code throws `Error: Each of the survfit() objects must have class 'survfit' only. Multi-state
models are not supported by this function.` but using `survfit` instead of `survfit2` the `add_nevent()` function works as expected. In most cases, it would be nice to create one model using `survfit2` for KM plots using `ggsurvfit` and then passing the same model to the table functions (instead of switching to `survfit` for the tables.

```r
library(gtsummary)

my_surv_model <- survfit2(Surv(time = time, event = status) ~ rx, data = df_colon)

tbl_survfit(
  x = my_surv_model,
  times = c(1, 2, 5),
  label_header = "**{time}-Year Survival**",
)  %>% 
  add_n() %>%
  add_nevent()
```

**Comment by ddsjoberg** [comment]
Sure, this check can be relaxed for `survfit2` objects. I'll leave this open for now. not sure when i'll get to the update FYI
