### ISSUE TITLE
R gtsummary package: How to Hide Colums in Summary Table

### ISSUE THREAD

**Issue by adilsonbauhofer** [ddsjoberg/gtsummary#1392]
I'm using gtsummary to prepare my tables, I'm trying to hide one of the columns from the groups, the third column labeled as "1, N = 61"

Below is the code ran,

library(gtsummary)
trial <- trial
trial %>% 
tbl_summary(by=response,
            statistic = list(trt~"{n}/{N} ({p}%)")) %>% 
  add_overall() %>%
  add_p() %>% 
  modify_column_hide(columns = "1")

**Comment by ddsjoberg** [comment]
Use the `show_header_names()` function to print the proper header names to be used in the hide function.

**Comment by adilsonbauhofer** [comment]
Thank you for the input, helped a lot solving the problem.

Daniel Sjoberg ***@***.***> escreveu no dia terça, 29/11/2022
à(s) 17:17:
