### ISSUE TITLE
Column `r.squared` doesn't exist. but is passed via `modelsummary` /`summ`

### ISSUE THREAD

**Issue by themichjam** [ddsjoberg/gtsummary#1399]
When passing a `svyglm` to tbl_regression` with the `add_glance_source_note` it shows everything but R2 and when making this explicit feeds back Column `r.squared` doesn't exist. However R2 does appear when using `summ` or `modelsummary`?

**Comment by ddsjoberg** [comment]
The statistics available are those returned with `broom::glance()` for your model type. You can customize if that doesn't include what you need.

Update your post with a reproducible example and separate code to calculate the R2 for your model type, and we can reopen the issue

**Comment by ddsjoberg** [comment]
@themichjam please refrain from posting the same question here and on SO
https://stackoverflow.com/questions/74753136
