### ISSUE TITLE
Function "as_flex_table" returns error

### ISSUE THREAD

**Issue by tjmeyers** [ddsjoberg/gtsummary#1406]
```
tbl_cross(trial, row = trt, col = response) %>%
as_flex_table()
```
The `tbl_cross` call returns the expected output but `as_flex_table` returns
`Error in max(nrows) : invalid 'type' (list) of argument`

I'm running gtsummary v1.6.3 in R v4.1.1. Thanks.

**Comment by ddsjoberg** [comment]
Thanks @tjmeyers ! 

The last release included an update for flextable output for bold/italic in the column headers. But I hadn't accounted for the case when the header is blank. Can you check out the the pull request?

**Comment by tjmeyers** [comment]
Hi Daniel. Thanks for addressing this in your latest commit. I installed your updated development version 1.6.3.9004 but the `as_flex_table` call throws the same error. Let me know if you would like my session info; apologies if I'm missing something obvious. Thanks again. Travis

**Comment by ddsjoberg** [comment]
Can you add a proper reprex with session info here? Thanks

**Comment by tjmeyers** [comment]
Please ignore my last post. I updated all dependencies and restarted my session, and the line in my original post works. Thank you!

**Comment by ddsjoberg** [comment]
Great to hear!
