### ISSUE TITLE
tbl_regression - support competing risks regression models

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#142]
@margarethannum, we weren't able to support competing risks regression models because we couldn't get the input data set, right? Usually we use `model.frame()`, but with the competing risks' non-standard input, we were not able to use this function.

I think there may be a way to construct the input data set, and from there "tidy" up the model results.

There's a cute trick where we use the function call, extract the components, and grab those inputs from the parent environment.  Do you think this would work for these models?

Check out the code in #141.

**Comment by margarethannum** [comment]
@ddsjoberg yes, `model.frame()` wasn't a part of the competing risks results.
Excited about the possible workaround!

**Comment by ddsjoberg** [comment]
Do you still have the code where you tidied up the regression model results?

**Comment by margarethannum** [comment]
Making a tidier for the `crr()` results was okay-ish but the main problem was ugly labeling because of the missing `model.frame()`! But I'll open my code again and see if I can do a cute workaround like you suggested :)

**Comment by margarethannum** [comment]
Going to look into incorporating https://github.com/raredd/cmprsk2 which already made extensions to cmprsk, including `model.frame()`

**Comment by margarethannum** [comment]
Partially addressed in #315 in combination with https://github.com/margarethannum/riskybiz. In {riskybiz}, I made a wrapper function for `cmprsk::crr()` and corresponding `model.frame()` and `tidy.crr()` functions. Then, in the #315 PR, we allow for user to input tidy function that needs to be used for a particular model. 

Not sure if this issue can be closed at this point or if we want to keep it open to add `cuminc()` functionality as well.
