### ISSUE TITLE
Feature request: Option to print hux table as default

### ISSUE THREAD

**Issue by dafxy** [ddsjoberg/gtsummary#1440]
It would be useful if you let the user select the output method. Instead of using as_hux_table(), an option like option(gtsummary.default="hux") to print the tables and summaries in general as hux as default option instead of on the web browser would be appreciated.

**Comment by ddsjoberg** [comment]
HI @dafxy , You can use the themes to set a difference default printer: `theme_gtsummary_printer("huxtable")`.
https://www.danieldsjoberg.com/gtsummary/reference/theme_gtsummary.html
