### ISSUE TITLE
Lancet style does not include enough precision in p values

### ISSUE THREAD

**Issue by davideyre** [ddsjoberg/gtsummary#1442]
The Lancet style does not provide enough precision in low p values, rounding to <0.001 rather than to <0.0001.

The Lancet guidance is "p-values should be given to two significant figures, but no longer than 4 decimal places (e.g. p<0.0001)."

**Comment by ddsjoberg** [comment]
Thanks @davideyre ! Can you link to their style guide?

**Comment by davideyre** [comment]
Here is one version - https://www.thelancet.com/pb-assets/Lancet/authors/tl-info-for-authors-1660039239213.pdf

Thanks!

**Comment by ddsjoberg** [comment]
Note to self: Did I change the output font to Times New Roman?
![image](https://user-images.githubusercontent.com/26774684/211549595-357e0963-d904-452e-9079-5aec943656c4.png)

**Comment by ddsjoberg** [comment]
Here's a function to round for Lancet. Need to think of the best way to incorporate into the theme....can I save obj in the environment somehow, then ref the obj in the env? Or just copy the entire function into the theme field?

``` r
style_pvalue_lancet <- function(x, prepend_p = FALSE) {
  # this function assures that 5s are rounded up (and not to even, the default in `round()`)
  round2 <- function(x, digits = 0) {
    round(x + .Machine$double.eps * sign(x), digits = digits)
  }
  
  p_fmt <-
    dplyr::case_when(
      # allowing some leeway for numeric storage errors
      x > 1 + 1e-15 ~ NA_character_,
      x < 0 - 1e-15 ~ NA_character_,
      round2(x, digits = 2) > 0.99 ~ paste0(">", gtsummary::style_number(x = 0.99, digits = 2)),
      round2(x, digits = 2) >= 0.10 ~ gtsummary::style_number(x, digits = 2),
      round2(x, digits = 3) >= 0.01 ~ gtsummary::style_number(x, digits = 3),
      round2(x, digits = 4) >= 0.001 ~ gtsummary::style_number(x, digits = 4),
      round2(x, digits = 5) >= 0.0001 ~ gtsummary::style_number(x, digits = 5),
      round2(x, digits = 4) < 0.0001 ~ paste0("<", gtsummary::style_number(x = 0.0001, digits = 4))
    )
  
  # prepending a p = in front of value
  if (prepend_p == TRUE) {
    p_fmt <- dplyr::case_when(
      is.na(p_fmt) ~ NA_character_,
      stringr::str_sub(p_fmt, end = 1L) %in% c("<", ">") ~ paste0("p", p_fmt),
      TRUE ~ paste0("p=", p_fmt)
    )
  }
  
  attributes(p_fmt) <- attributes(x)
  return(p_fmt)
}


c(-1, 2, 0.000001, 0.000100001, 0.0002234, 0.0452342, 0.5, 0.99, 0.999) |> 
  style_pvalue_lancet()
#> [1] NA        NA        "<0.0001" "0.00010" "0.00022" "0.045"   "0.50"   
#> [8] "0.99"    ">0.99"
```

<sup>Created on 2023-01-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by davideyre** [comment]
Thanks!

**Comment by ddsjoberg** [comment]
@davideyre i updated the function above to better handle p-values at the rounding thresholds. 

Can you test a few scenarios? Anything that isn't rounding properly?
