### ISSUE TITLE
Feature request: Regression Predictions

### ISSUE THREAD

**Issue by jerrodanzalone** [ddsjoberg/gtsummary#1447]
I absolutely love this package. One potential extension to the tbl_regression functions I think would have some benefit would be to include a prediction option based on the regression models. My specific use case is to estimate excess burden based on glm predictions, which I would love to be able to easily append to a gtsummary object.

**Comment by ddsjoberg** [comment]
Thanks for the suggestion @jerrodanzalone .

I think @larmarange has recently been working on something similar. @jerrodanzalone can you please post an example of a model and what you imagine the results would look like?

**Comment by jerrodanzalone** [comment]
@ddsjoberg The current working version I'm using is for incidence rate ratios Poisson regression. So it would effectively be an additional column predicted incidence per 1,000 person months. So if I'm looking at associations between immunosuppressive medications and breakthrough COVID-19 infections with the following models, I'd want to be able to add a column for predicted breakthrough infections: 

    m1=glm(bti ~ age_category + sex + tp + prior_infection + obesity + comorbidity_count + primary_vax_type + region + medication_exposure + offset(log(person_time)), family="poisson", data=local_df[which(local_df$person_time>0),]) %>%
    tbl_regression(exponentiate = TRUE)  %>%
      add_nevent(location = "level") %>%
      modify_header(exposure ~ "**Exposure**") %>%
      modify_table_body(
        ~.x %>%
          mutate(rate = (stat_nevent * 1000) / (exposure/30.4) , 
                 .after = stat_nevent)
      ) %>%
      modify_header(rate ~ "**Rate**") %>%
      modify_fmt_fun(rate ~ partial(style_number, digits=2))

I'm currently using predict.glm function to gather this for each covariate, but it'd be amazing if this could be integrated into gtsummary even as a sanity check. Thanks!

**Comment by larmarange** [comment]
Could you provide a productive example?

You may have a look at https://larmarange.github.io/broom.helpers/dev/articles/marginal_tidiers.html

**Comment by jerrodanzalone** [comment]
@larmarange That example in itself is very helpful. I'll have to make some synthetic data, and then I can provide an example later this week. Thank you!

**Comment by ddsjoberg** [comment]
@jerrodanzalone feel free to reopen when you're ready to continue
