### ISSUE TITLE
Allow the addition of footnotes on table captions

### ISSUE THREAD

**Issue by mlamias** [ddsjoberg/gtsummary#1448]
I frequently need to add a footnote to my gtsummary table, but require the footnote reference number to be in the table caption rather than in x$table_body.  The following code comes close to producting what I frequently want to create:

```
library(tidyverse)
library(flextable)
library(gtsummary)
mytable <-   iris %>% 
      mutate(Long.Petal = ifelse(Petal.Width > .2, "Yes", "No")) %>% 
    tbl_cross(
      row =  Long.Petal,
      col = Species,
      percent = "cell"
    ) %>% 
   modify_table_styling(
    columns = label,
    rows = row_type == "label",
    footnote = "This is my footnote."
  )
```
However, in this example, the footnote reference number (the superscripted number 1), appears after the label Long.Petal as shown below

![image](https://user-images.githubusercontent.com/9097516/212615555-f2ab4ba5-1aa7-415f-be4f-a2d5f07843c3.png)

Instead, I'd like to see an enhancement where, withing gtsummary, I could place the footnote reference in the caption, after the word "Species."

**Comment by ddsjoberg** [comment]
I'm in favor of adding this option. Do you know whether gt, flextable, Huxtable, kableExtra can place footnotes in the caption?

If so, can you provide the code for each?

**Comment by ddsjoberg** [comment]
Feel free to reopen when you're ready
