### ISSUE TITLE
Feature request: add units to tbl_summary

### ISSUE THREAD

**Issue by levossen** [ddsjoberg/gtsummary#1449]
Hi!
I love the gtsummary package and how it integrates with other helpful packages like dplyr and flextable. I was wondering, is there a way to add units to a tbl_summary()?
Thanks!
Laura

**Comment by ddsjoberg** [comment]
Please update your post with an example of what you're looking for

**Comment by larmarange** [comment]
Have you consider `sacles::label_number()` using `scale_cut` argument with `scales::cut_si()` to generate a formatter function to be transmitted to `digits` argument of `tbl_summary()`?

**Comment by ddsjoberg** [comment]
@levossen please feel free to reopen when you're ready to respond
