### ISSUE TITLE
Like how tbl_continuous has an option to allocate a variable, is there a way of doing this for tbl_summary

### ISSUE THREAD

**Issue by O16789** [ddsjoberg/gtsummary#1453]
I am trying to summarise my data for a medical score
tbl_continuous works fine for my categorical variables
but I can't seem to find an option for my continuous variables

Please help if you can!

**Comment by ddsjoberg** [comment]
As the prompt indicated when you opened this issue, this is not the place for questions. Please post your question to stackoverflow.com. If you include the gtsummary tag, I'll be notified of your post.

Your post should include a minimal reproducible example, aka a minimal reprex (also indicated in the prompt prior to posting this issue). A reprex includes both data and code I can run on my machine. If needed, include a mock-up of what you want your results to look like.

Take just a few minutes to review reprex.tidyverse.org for detailed instructions on how to create a reprex.
