### ISSUE TITLE
Bug Report: add_p () different test performed in table for modalities of the same categorical variable

### ISSUE THREAD

**Issue by ClaudiaCampani** [ddsjoberg/gtsummary#1457]
Hello,
I used the gtsummary package to create a table describing the median differences of a continuous variable (cfDNA) based on two categorical variables (BCLC and Timing) and reporting the p-value obtained with paired-Wilcoxon.
To do this I used:
`Paired_Wilcoxon<-plasmadf %>%
  select(Cc_Fil,Timing,Couple_of_plasma,BCLC_recoded) %>%
  tbl_strata(
    strata = BCLC_recoded,
    .tbl_fun =
      ~ .x %>%
      tbl_summary(
        by = Timing,
        include=-Couple_of_plasma,
        digits=all_continuous()~2,
        label=c(Cc_Fil~"cfDNA concentration (ng/μL)"),
        missing = "no") %>%
      add_p(test=list(Cc_Fil~"paired.wilcox.test"),
            group=Couple_of_plasma,
            pvalue_fun = ~ style_pvalue(.x, digits = 3)) %>%
      bold_p(t=0.05, q=FALSE) %>% 
      add_n(),
    .header = "**{strata}**, N = {n}"
  ) %>% 
  modify_footnote(
    all_stat_cols()~"Median (IQR)"
  ) %>%
  modify_header(label~"**Variable**") %>% 
  modify_caption ("**Table 3.1.2 Differences in cfDNA concentration (ng/μL) according to BCLC stage**") %>% 
  bold_labels() %>% 
  as_gt() %>%
  gt::tab_source_note(gt::md("cfDNA: circulating free DNA.BCLC: Barcelona Clinic Liver Classification. H0: prelevement at the treatment. H24: prelevement 24 hours after the treatment. Significant p-values are reported in bold"))
`
In the resulting table, however, I noticed that paired Wilcoxon is applied to compare the median of cfDNA between H0 and H24 only in the first two categories of BCLC (0 and A) while in the third class (B/C) an unpaired Wilcoxon is applied (image attached).
![GitHub](https://user-images.githubusercontent.com/124942738/217969732-a97ee13c-c11c-4865-abc3-29a08182c5d6.jpg)

The same thing happens in all tables in which the modalities number of the " hierarchically superior" categorical variable is more than two.
How can this be solved?

**Comment by ddsjoberg** [comment]
Thank you for your post. Please update your post with a reproducible example, aka a reprex. A reprex includes both data and code I can run on my machine that replicates your finding. Make the example as short as possible: the minimal amount of code to reproduce your finding and nothing more.

Take just a few minutes to review [reprex.tidyverse.org](https://reprex.tidyverse.org/) for detailed instructions on how to create a reprex.

I am going to go ahead and close this issue for now. But please do re-open the issue after you've added your reproducible example.
