### ISSUE TITLE
Feature request: Make adjusting output digits in `tbl_regression` easier

### ISSUE THREAD

**Issue by norcalbiostat** [ddsjoberg/gtsummary#1458]
**Is your feature request related to a problem? Please describe.**
I don't always agree with the level of rounding that is presented in tbl_regression. 

**Describe the solution you'd like**
I want a digits= option to be added. 

**Describe alternatives you've considered**
I found a solution that works [here](https://stackoverflow.com/questions/67551356/increase-number-of-digits-on-presented-ors-and-95-ci-by-tbl-regression-in-gtsum), but it took me 20 minutes of searching and then starting to write my own SO post when it popped up. And there is NO WAY i would have figured out to use `purrr::partial()`..., even if i was familiar with that. And absolutely no way I will show that to students as a solution. 

**Additional context**
I really want to be able to fully promote this package to my undergraduate students.

**Comment by ddsjoberg** [comment]
Sorry you spent to much time and effort finding a solution. I suggest next time you begin with the function's help file. You don't need to use purrr partial if you're not familiar with it. You can also use the suite of formatting functions in the tidyverse's scales package. The argument merely accepts an R function, regardless how you create it.

**Comment by norcalbiostat** [comment]
I appreciate your reply, but do not appreciate the tone.  Over 75% of the time i spent looking for an answer _was_ in your documentation. That's where I came across `style_number()` function which allowed me to refine my search queries ultimately led me to the SO post that uses purrr. Perhaps I should  restate my request as to "update the documentation to include a concrete example of how this function is used". Is it piped in like the `add_` arguments?  The help file for `tbl_rgression()` does not appear to show an argument for `style`.  The statement "The argument merely accepts an R function, regardless how you create it." is confusing and a bit unhelpful imo. - what argument are you referring to? In which function?  

I'm just asking for clarification in the documentation.

**Comment by ddsjoberg** [comment]
Great, sounds like we're on the same page about not appreciating the other's tone.
