### ISSUE TITLE
Feature request: tbl_cross with srvyr object

### ISSUE THREAD

**Issue by jonasrekdalmathisen** [ddsjoberg/gtsummary#1459]
Hi and thanks for such a great package! I work a lot with survey data and would love to use gtsummary fulltime. The tbl_svysummary is already quite useful!

I wondered if there are any considerations of making srvyr objects readable with tbl_cross? 

A more broad approach could be to include a weight argument (to identify a weight column) in all functions. This may supersede my main purpose of using srvyr, and may be even so more useful when making gt-tables.   

Best,
Jonas Mathisen

**Comment by ddsjoberg** [comment]
I am not against adding `tbl_svycross()` (or some other name). I don't have the bandwidth to write it however, so it'll likely be some time before you see it.

**Comment by ddsjoberg** [comment]
As this is not on any roadmaps to implement, I am going to go ahead and close. If someone is interested in adding in the future, please make a note here first.
