### ISSUE TITLE
Add support for ..numeric.., ..integer.., etc for specifying column attributes in tbl_summary

### ISSUE THREAD

**Issue by sammo3182** [ddsjoberg/gtsummary#146]
A quick question-suggestions:

Is there a way to change the categories of variables without specifying each of them? In `fmt_table1`, variables will be presented according to their properties (continuous or categorical/binary). You offered a way to customize that with the argument type in the current version of the function. What I was looking for was a way to change how `fmt_table1` treats a whole class of variables. For instance, based on my limited practice of this function, it appears to treat integer vectors with a small number of values as "categorical." So, is there a way that I can ask the function to treat all types of numeric vectors as "continuous," no matter how many types of values it has---a way that I don't have to specify each vector through the type argument?

**Comment by ddsjoberg** [comment]
Hi Sammo, 

I like your suggestion a lot.  Imagine I have a data set with columns that are integers and doubles, and we want all integer columns to be displayed as categorical.  Perhaps something like this could work, where `..integer..`, `..double..`, `..numeric..`, etc. are special names.
```r
my_data %>%
  fmt_table1(type = list(..integer.. = "categorical"))
```
If I wanted all numeric variables to be displayed as categorical variables in the table, I would use:
```r
my_data %>%
  fmt_table1(type = list(..numeric.. = "categorical"))
```

Does this look like what you have in mind?  

I think you're using v0.1.0.  I have implemented a lot of updates in v1.0.0 (not yet on CRAN).  In this version, I reserve the names `..continuous..`, `..categorical..`, and `..dichotomous..` to make changes to the class of variables in one statement.  But I hadn't thought of your suggestion, and I like it.

**Comment by sammo3182** [comment]
It will be great if the function has that argument as you described! An alternative approach might be a separate function mimicking `dplyr::mutate_if` to define the presenting types before running `fmt_table1`. Something like: 

```r
my_data %>% 
  fmt_categorize_if(is.integer, "categorical") %>% 
  fmt_table1()   
```

An advantage of this approach is you don't need to reserve names for every class of vectors. Users are also more free to customize the presenting rules, such as only when integer variables have fewer than three unique values is the "categorical" rule applied (` fmt_categorize_if(length(unique(.)) <= 3, "categorical") `). 

Of course, I just propose this suggestion from the perspective of users. It might be super hard to achieve from the developer view. So, any effort to address this suggestion will be sincerely appreciated!

**Comment by ddsjoberg** [comment]
I'll add to my list!

I like your proposed framework, but it would be a big change to the function's API to start doing pre-processing before passing a dataset to `tbl_summary`.  For that reason, I'll stick with the convention already implemented.

**Comment by ddsjoberg** [comment]
Hey @sammo3182 , I have been thinking about your suggestion.  What do you think of this solution? 

The {gtsummary} package uses named lists to change default behavior.  For example, the `tbl_summary()` function guesses whether a column in a data frame is categorical or continuous.  If the function thinks the column `age` is continuous but we want `age` summarized as a categorical variable, we use the type argument: `type = list(age = "categorical")`. 

Rather than using named lists as the input, we can utilize the already well known {tidyselect} functions used in {dplyr} and other {tidyverse} packages. 

```r
mtcars %>%
  tbl_summary(
    type = list(starts_with("cy") ~ "continuous", 
                vars(hp, mpg) ~ "continuous")
  )
```

We can also supplement the {tidyselect} functions with a few of our own.  I would include functions to select variables by their type.

```r
mtcars %>%
  tbl_summary(
    type = list(all_integer() ~ "continuous", 
                all_numeric() ~ "categorical")
  )
```

This would be a breaking change.  I'd appreciate your input before making any updates!


PS @karissawhiting We don't necessarily need to make this a breaking change.  We could check whether the input is a named list.  If it is a named list, we could print a message that the named list inputs are deprecated, but use the list as it is.  If it's not a named list, then we use the {tidyselect} framework to parse the argument input.

**Comment by margarethannum** [comment]
I think this is a really good suggestion/solution @ddsjoberg, to be able to do things in bulk, by flexible, user-specified categories, using a strategy already familiar to users of the tidyverse. 
[`gt::tab_row_group()`](https://gt.rstudio.com/reference/tab_row_group.html) recommends selecting variables the same way, so I think your suggestion fits in nicely with {gt} overall. Sounds like it would be worth the break :)

**Comment by sammo3182** [comment]
@ddsjoberg I like both ways! They should provide sufficient flexibility for users to identify the variable as they want! Look forward to the update!

**Comment by ddsjoberg** [comment]
To do:
- [ ] Write these selector functions: `all_numeric()`, `all_double()`, `all_integer()`, `all_logical()`, `all_character()`, `all_continuous()`, `all_categorical(dichotomous = TRUE)`, and `all_dichotomous()`  
- [ ] Write a function to convert a list of formulas into a named list.  If a single formula is passed, convert the single formula into named list.
- `tbl_summary()`
    - [ ] Update `tbl_summary_input_checks()` to check for appropriately passed formulas
    - [ ] Incorporate the formula lists into the function arguments: type, label, value, statistic, and digits
- `add_p()`
    - [ ] Incorporate the formula lists into the test argument
- `tbl_regression()`
   - [ ] Incorporate the formula lists into the label argument
- `tbl_uvregression()`
   - [ ] Incorporate the formula lists into the label argument
