### ISSUE TITLE
Bug Report: Unable to produce tbl_regression after setting a gtsummary theme

### ISSUE THREAD

**Issue by bhattmaulik** [ddsjoberg/gtsummary#1461]
I am using the gtsummary package version 1.7.0.9001. I am unable to create a gtsummary table using the `tbl_regression` function, after I set a gtsummary theme. The table displayes well without the theme, but after setting the theme, the same table shows an error. Let me show a reprex with a simple example.
```
lm_model <- lm(mpg~wt+cyl, data = mtcars)
tbl_regression(lm_model)
```

This table displays well. Then I set a theme for my table.
```
my_theme <-
  list(
    # round large p-values to two places
    "pkgwide-fn:pvalue_fun" = function(x) style_pvalue(x, digits = 2),
    "pkgwide-fn:prependpvalue_fun" = function(x) style_pvalue(x, digits = 2, prepend_p = TRUE),
    # report median (IQR) and n (percent) as default stats in `tbl_summary()`
    "tbl_summary-str:continuous_stat" = "{median} ({p25} - {p75})",
    "tbl_summary-str:categorical_stat" = "{n} ({p})",
    "tbl_regression-lst:tidy_plus_plus" = "list(conf.int = TRUE, add_header_rows = TRUE, add_estimate_to_reference_rows = TRUE)"
  )
set_gtsummary_theme(my_theme)
```

After setting this theme, I run the same code
`tbl_regression(lm_model)`

But now, I get an error message:

```
Error in `.update_vector()`:
! All elements of y should be named.
Backtrace:
  1. gtsummary::tbl_regression(lm_model)
 10. broom.helpers:::.update_vector(., labels)
```

**Comment by larmarange** [comment]
The list passed to `"tbl_regression-lst:tidy_plus_plus" ` should not be quoted.

You can try

```
my_theme <-
  list(
    # round large p-values to two places
    "pkgwide-fn:pvalue_fun" = function(x) style_pvalue(x, digits = 2),
    "pkgwide-fn:prependpvalue_fun" = function(x) style_pvalue(x, digits = 2, prepend_p = TRUE),
    # report median (IQR) and n (percent) as default stats in `tbl_summary()`
    "tbl_summary-str:continuous_stat" = "{median} ({p25} - {p75})",
    "tbl_summary-str:categorical_stat" = "{n} ({p})",
    "tbl_regression-lst:tidy_plus_plus" = list(add_header_rows = TRUE)
  )
set_gtsummary_theme(my_theme)

```

**Comment by bhattmaulik** [comment]
Thank you for the suggestion. But after removing the inverted comma from the list, now the error is different.
```
Error in broom.helpers::tidy_plus_plus(model = list(coefficients = c(`(Intercept)` = 39.6862614802529, : 
formal argument "conf.int" matched by multiple actual arguments
```

This is the error that I get now.

**Comment by ddsjoberg** [comment]
Dear @bhattmaulik ,

I'll take a look when I have a moment (moving cross country right now). In the meantime, can you make your example minimal? Please only include parts absolutely necessary for illustrating your issue. Thanks

**Comment by larmarange** [comment]
I guess that the problem is coming from here:

https://github.com/ddsjoberg/gtsummary/blob/b4ec87bfa2442d891592abbbf46e31cf5c7e3406/R/utils-tbl_regression.R#L10-L39

The `conf.int` argument is passed twice. 

It would be better to update `tidy_plus_plus_args` with default value if not present before calling `tidy_plusp_plus()`

**Comment by ddsjoberg** [comment]
@bhattmaulik can you just remove `conf.int = TRUE` from your theme?

**Comment by bhattmaulik** [comment]
I just removed conf.int = TRUE from the theme. But I am still getting error. Let me first paste the theme that I am using.

```
my_theme <-
  list(
    # round large p-values to two places
    "pkgwide-fn:pvalue_fun" = function(x) style_pvalue(x, digits = 2),
    "pkgwide-fn:prependpvalue_fun" = function(x) style_pvalue(x, digits = 2, prepend_p = TRUE),
    # report median (IQR) and n (percent) as default stats in `tbl_summary()`
    "tbl_summary-str:continuous_stat" = "{median} ({p25} - {p75})",
    "tbl_summary-str:categorical_stat" = "{n} ({p})",
    "tbl_regression-lst:tidy_plus_plus" = list(add_header_rows = TRUE, add_estimate_to_reference_rows = TRUE)
  )
set_gtsummary_theme(my_theme)
```

After that, I attempted to run tbl_regression function again.
```
tbl_regression(lm_model)
#lm_model <- lm(mpg~wt+cyl, data = mtcars)
```

Output:
```
Error in broom.helpers::tidy_plus_plus(model = list(coefficients = c(`(Intercept)` = 39.6862614802529, : 
formal argument "add_estimate_to_reference_rows" matched by multiple actual arguments
```

**Comment by ddsjoberg** [comment]
You'll need to also remove add_estimate_to_reference_rows as this is also an argument in the primary function

**Comment by ddsjoberg** [comment]
I am going to assume that this resolved your issue. Feel free to re-open if not
