### ISSUE TITLE
error when running the example after the update

### ISSUE THREAD

**Issue by dimbage** [ddsjoberg/gtsummary#1463]
_Hello,
When I run example:_
---
```
library(dplyr)
library(gtsummary)**

trial2 <- trial %>% select(age, grade, response, trt)**
tbl_summary(trial2)
```

_I've got an error:_

> Error in `mutate()`:
> ℹ In argument: `stat_label = stat_label_match(.data$stat_display)`.
> Caused by error:
> ! attempt to select less than one item in integerOneIndex

`rlang::last_error() `

> error/dplyr:::mutate_error
> Error in `mutate()`:
> 
>  ℹ In argument: `stat_label = stat_label_match(.data$stat_display)`.
>  Caused by error:
>  ! attempt to select less than one item in integerOneIndex
> 
> Backtrace:
> 1. gtsummary::tbl_summary(trial2)
> 28. `<fn>`()

`rlang::last_trace()`

> rlang::last_trace()
> <error/dplyr:::mutate_error>
> Error in `mutate()`:
> ℹ In argument: `stat_label = stat_label_match(.data$stat_display)`.
> Caused by error:
> ! attempt to select less than one item in integerOneIndex
> 
> Backtrace:
>   1. ├─gtsummary::tbl_summary(trial2)
>   2. │ └─gtsummary:::generate_metadata(...)
>   3. │   └─meta_data %>% ...
>   4. ├─dplyr::mutate(...)

_Error is at 5 step_

>   5. ├─**dplyr:::mutate.data.frame(...)**
>   6. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
>   7. │   ├─base::withCallingHandlers(...)
>   8. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
>   9. │     └─mask$eval_all_mutate(quo)
>  10. │       └─dplyr (local) eval()
>  11. ├─gtsummary:::stat_label_match(.data$stat_display)
>  12. │ └─... %>% ...
>  13. ├─dplyr::bind_rows(...)
>  14. │ └─rlang::list2(...)
>  15. ├─tibble::tibble(...)
>  16. │ └─tibble:::tibble_quos(xs, .rows, .name_repair)
>  17. │   └─rlang::eval_tidy(xs[[j]], mask)
>  18. ├─... %>% unique()
>  19. ├─base::unique(.)
>  20. ├─base::unlist(.)
>  21. ├─stringr::str_extract_all(unlist(stat_display), "\\{.*?\\}")
>  22. │ └─stringr:::check_lengths(string, pattern)
>  23. │   └─vctrs::vec_size_common(...)
>  24. ├─base::unlist(stat_display)
>  25. ├─stat_display
>  26. ├─rlang:::`$.rlang_data_pronoun`(.data, stat_display)
>  27. │ └─rlang:::data_pronoun_get(...)
>  28. ├─`<fn>`()
>  29. └─base::.handleSimpleError(...)
>  30.   └─dplyr (local) h(simpleError(msg, call))
>  31.     └─rlang::abort(message, class = error_class, parent = parent, call = error_call)

_My session info:_

>locale:
[1] LC_COLLATE=Russian_Russia.utf8  LC_CTYPE=Russian_Russia.utf8
[3] LC_MONETARY=Russian_Russia.utf8 LC_NUMERIC=C
[5] LC_TIME=Russian_Russia.utf8

>attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

>other attached packages:
[1] gtsummary_1.7.0.9001 dplyr_1.1.0.9000

>loaded via a namespace (and not attached):
 [1] knitr_1.42           magrittr_2.0.3       tidyselect_1.2.0
 [4] gt_0.8.0             munsell_0.5.0        colorspace_2.1-0    
 [7] R6_2.5.1             rlang_1.0.6.9000     fastmap_1.1.0
[10] fansi_1.0.4          stringr_1.5.0        tools_4.2.2
[13] broom.helpers_1.12.0 grid_4.2.2           gtable_0.3.1
[16] xfun_0.37            utf8_1.2.3           cli_3.6.0
[19] withr_2.5.0          htmltools_0.5.4      digest_0.6.31
[22] tibble_3.1.8.9006    lifecycle_1.0.3      tidyr_1.3.0.9000    
[25] purrr_1.0.1.9000     ggplot2_3.4.0.9000   vctrs_0.5.2.9000
[28] glue_1.6.2           stringi_1.7.12       compiler_4.2.2
[31] pillar_1.8.1         generics_0.1.3.9000  scales_1.2.1
[34] jsonlite_1.8.4       pkgconfig_2.0.3

**Comment by ddsjoberg** [comment]
HI @dimbage, this is a pretty basic example that ran without error locally for me and on the 12+ systems CRAN tests packages on, so I suspect the issue is something about your install.

I see you have many dev versions for some tidyverse packages. Install the versions of these packages from CRAN, and let me know if that solves your issue.

**Comment by dimbage** [comment]
Dear @ddsjoberg, 
thank you for prompt reply (and for so usefull package)
update some r pacakge including dplyr from github... 
may be during compilation r packages something wrong happend.
Now i installed dplyr and gtsummary from cran and it works
Thank you!
