### ISSUE TITLE
gtsummary fails to generate p value for multi level categorical variables in large datasets

### ISSUE THREAD

**Issue by Mathicaa** [ddsjoberg/gtsummary#1464]
---

I noticed gtsummary fails to calculate p-value for variable Gender and instead it returns NA while it generates P-value for other variables.
I tried running the function on the head of dataset couple of times. it seems like for some reason it generates p -vale for All the variables only when the number of row are really smaller.
I wonder if it is a bug or not. 

```r
 df %>%
    gtsummary::tbl_summary(by = Outcome, 
                           type = list(
                                Gender  ~ "categorical",
                                Race ~ "categorical"
                                ),
                           statistic = list(
                                    all_continuous() ~ "{median} ({p25}, {p75})",
                                    all_categorical() ~ "{n} ({p}%)"),
                                    missing_text = "(missing)" 
                              ) %>%
                  gtsummary::add_p() %>%
                  gtsummary::bold_labels() %>%
    as_tibble()
```

**Comment by ddsjoberg** [comment]
can you drop the data into a GitHub Gist? That site is blocked by my company

**Comment by ddsjoberg** [comment]
ping @Mathicaa

**Comment by ddsjoberg** [comment]
please feel free to re-open when you're free to update
