### ISSUE TITLE
Bug Report: <add_difference(everything()~"smd") returns an error about inherited method for function n_mean_var for signature `"labelled", "missing"'>

### ISSUE THREAD

**Issue by proshano** [ddsjoberg/gtsummary#1465]
I get the error message:

There was an error in 'add_p()/add_difference()' for variable 'var2', p-value omitted:
Error in (function (classes, fdef, mtable) : unable to find an inherited method for function ‘n_mean_var’ for signature ‘"labelled", "missing"’

This is produced for 3 of many variables. These three are continuous variables. Another continuous variable appears to be handled just fine. 

```r
data[vars] %>%
  tbl_summary(
    by = var1,
    missing = "no",
    #statistic = all_continuous() ~ "{median} ({IQR})",
    digits = list(c("var2","var3", "var4", "var5", "var6") ~ 1)
  ) %>%
  modify_header(all_stat_cols(FALSE) ~ "**{level}**<br>N = {n} ({style_percent(p)}%)") %>%
  add_n() %>%
  add_difference(everything()~"smd")%>%
  add_p(test = list(all_continuous() ~ "kruskal.test"))  %>%
  bold_labels() %>%
  modify_spanning_header(starts_with("stat_") ~ "**Exposure variable**")
```

**Comment by ddsjoberg** [comment]
Thank you for your post. Please update your post with a reproducible example, aka a reprex. A reprex includes both data and code I can run on my machine that replicates your finding. Make the example as short as possible: the minimal amount of code to reproduce your finding and nothing more.

Take just a few minutes to review [reprex.tidyverse.org](https://reprex.tidyverse.org/) for detailed instructions on how to create a reprex.

I am going to go ahead and close this issue for now. But please do re-open the issue after you've added your reproducible example.
