### ISSUE TITLE
Error in theme_gtsummary_compact(.) 

### ISSUE THREAD

**Issue by mariamaseng** [ddsjoberg/gtsummary#1466]
Hello!
I am making a gt_summary table, and would like to have the theme as compact by "theme_gtsummary_compact". 
My data is numeric, and tabled by categories.

I am getting this error message: 
Error in theme_gtsummary_compact(.) :
'list' object cannot be coerced to type 'logical'

THis is my code:

meta %>%
  select(-"country", -"obese") %>%
  tbl_summary(by = "countryobese") %>%
  add_p() %>%
  theme_gtsummary_compact()

Help is much appriciated! Btw - I love gtsummary <3

**Comment by mariamaseng** [comment]
Update - however, despite warning, making the table now - without the "theme compact" it is compact! Did I just have to "set" the theme by running the command, not including it in the table-creation-formula?

**Comment by ddsjoberg** [comment]
Dear @mariamaseng 

The themes are set once per session and apply to all tables created within that session.

Check out the help file for an example!
