### ISSUE TITLE
Transpose the table

### ISSUE THREAD

**Issue by mariamaseng** [ddsjoberg/gtsummary#1467]
hi!
I have a a table with is 3*9 as I the variable which the table is split by has 9 variables. I would love to be able to transpose the table. Is there an easy way of doing just that?

**Comment by ddsjoberg** [comment]
Dear @mariamaseng ,

The underlying structure doesn't allow for simple transposing unfortunately.

You could use as_tibble() to convert it to a tibble and transpose from there ?
