### ISSUE TITLE
separate_p_footnotes() throws error after add_difference()

### ISSUE THREAD

**Issue by DesiQuintans** [ddsjoberg/gtsummary#1475]
I have tried both the CRAN version of `gtsummary` as well as the current dev version 1.7.0.9002 from GitHub. 

In both versions, trying to produce separate P-value footnotes for tests performed by `add_difference()` produces an error:

---

```r
library(gtsummary)

trial %>% 
    tbl_summary(by = trt) %>% 
    add_difference() %>% 
    separate_p_footnotes()
#> Error in separate_p_footnotes(.): The `x$meta_data` data frame must have a column called 'stat_test_lbl'.
```

<sup>Created on 2023-03-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Thanks for the report @DesiQuintans . The function wasn't written to work with `add_difference()` and it's a reasonable request. I'll leave this open, and perhaps implement in the future.

**Comment by ddsjoberg** [comment]
FYI, I am not sure this update is feasible: some `add_difference()` methods do not add a p-value column and I don't save the difference and difference CI footnotes in the same way I do the p-value footnotes.

I am going to go ahead and close this issue, unfortunately.
