### ISSUE TITLE
Bug Report: <Describe bug>

### ISSUE THREAD

**Issue by eugenividal** [ddsjoberg/gtsummary#1480]
**Code shown before table printed in a github Readme**

Hi guys, great package!

I found an issue using `tbl_summary` when I render a github_document and git push it as a README.Rmd. The table is printed but for some reason, there is some code before. Please see the code and gif showing the issue below. 

```
tab1 = simd_gc_matrix %>% 
  select(km_ped, km_cyc, km_ped_dark, km_cyc_dark, crime_rate, nightlight_index, income_rate, density, access_rank, km_infras) %>%  
  tbl_summary()

tab1
```
![Peek 2023-03-23 12-53](https://user-images.githubusercontent.com/32644567/227210559-9ad0ca85-99c5-4314-890a-cca61afaf82e.gif)

**Comment by ddsjoberg** [comment]
@eugenividal thanks for the post. The tables are printed default to HTML, but GitHub does not fully support HTML. You can try to investigate solutions by adding the converted gt table to a container or by saving the table as an image and placing the image in your document.
