### ISSUE TITLE
Displaying Dichotomous Variables as fractions in gtsummary Tables

### ISSUE THREAD

**Issue by TPDeramus** [ddsjoberg/gtsummary#1481]
Apologies if this has been shared elsewhere in the repository, but I haven’t been able to find it in my searches.

I’m wanting to create a table in gtsummary that displays entries for “Yes” and “No” as fractions rather than a relative to the total (e.g. {n} / {N} in the documentation).

I realize I can split them into rows with something like:
type = all_dichotomous() ~ "categorical"

But I would honestly much rather display the variable as something like:
Condition? (Y/N)                   count “Yes”/ count “No”

Is this possible to do in gtsummary?

Thank you in advance.

**Comment by ddsjoberg** [comment]
HI @TPDeramus , 

Thank you for the post. Can you please update with data+code I can run on my machine. Please also include a mock-up of what you have in mind.

**Comment by TPDeramus** [comment]
Sorry for the wait. This is probably the best example I can give:

```

Simset = read.csv('Example.csv')

library(gtsummary)
library(dplyr)

t1 <- Simset %>% select(colnames(Simset)[-1]) %>% tbl_summary(by = PorrQual, type = list(all_dichotomous() ~ "categorical", c(Age, FSIQ, FD) ~ "continuous2"), statistic = list(c(Age, FSIQ, FD) ~ c("{mean}","{median} ({p25}, {p75})","{min}, {max}")), label = list(Age ~ "Age in Years", Gender ~ "Reported Gender Identity", FSIQ ~ "Full-Scale IQ", Tics ~ "Presence of Tics Disorder?", FD ~ "Framewise Displacement?", DX ~ "Diagnostic Group"))  %>% 
modify_spanning_header(all_stat_cols() ~ "**Data Quality Category**") %>% modify_caption("**Table 1. Participant Characteristics Relative to Data Quality Rating**") %>% bold_labels() %>% as_gt() %>% gt::tab_source_note(gt::md("*Median(IQR) = Median(25% Interquartile Range, 75% Interquartile Range)*"))

t1

t2 <- Simset %>% select(colnames(Simset)[-1]) %>% tbl_summary(by = PorrQual, type = list(c(Age, FSIQ, FD) ~ "continuous2"), statistic = list(all_dichotomous() ~ "{n} / {N} ({p}%)", c(Age, FSIQ, FD) ~ c("{mean
![Screenshot 2023-03-27 at 16-31-30 Screenshot](https://user-images.githubusercontent.com/112449969/228060377-87f2378f-c985-45d4-944c-215946c108e1.png)
}","{median} ({p25}, {p75})","{min}, {max}")), label = list(Age ~ "Age in Years", Gender ~ "Reported Gender Identity", FSIQ ~ "Full-Scale IQ", Tics ~ "Presence of Tics Disorder?", FD ~ "Framewise Displacement?", DX ~ "Diagnostic Group"))  %>% 
modify_spanning_header(all_stat_cols() ~ "**Data Quality Category**") %>% modify_caption("**Table 1. Participant Characteristics Relative to Data Quality Rating**") %>% bold_labels() %>% as_gt() %>% gt::tab_source_note(gt::md("*Median(IQR) = Median(25% Interquartile Range, 75% Interquartile Range)*"))

t2
````

![Screenshot 2023-03-27 at 16-31-30 Screenshot](https://user-images.githubusercontent.com/112449969/228060469-105ec86d-4b45-4983-817b-8f190f58579e.png)
![Screenshot 2023-03-27 at 16-34-01 Screenshot - Copy](https://user-images.githubusercontent.com/112449969/228060470-96db004c-52e8-40fe-9b4c-6d70c01ef5cb.png)
[Example.csv](https://github.com/ddsjoberg/gtsummary/files/11082835/Example.csv)

As you can see from Table 1 vs Table 2, Table 1 has the Binary values (0 & 1) separated into rows, while Table 2 has the 1 values next to the total (N at the top of the column).

In a perfect world, I would prefer to have the data split "1 / 0" or "0 / 1" for "Yes/No" or "No/Yes" in order to save space rather than it be "Number of True flags / Total observations."

**Comment by TPDeramus** [comment]
Ah. Was just making sure.

Thanks so much!

**Comment by larmarange** [comment]
It should be possible with tbl_custom_summary(). 

Can you clarify if the number of yes/no corresponds to the include or the by variable?

Could you provide an example of the table you would like to obtain?

**Comment by larmarange** [comment]
Maybe something easier. You cannot pass custom functions to categorical variables, but it is possible for continuous variables.

You can convert your continuous variables into 0/1 numerical variables, force them to be "continuous" and then define two custom functions to count the number of 0 and the number of 1.

``` r
library(gtsummary)

# response is coded as 0/1
n0 <- function(x) {sum(x == 0, na.rm = TRUE)}
n1 <- function(x) {sum(x == 1, na.rm = TRUE)}

trial |> 
  tbl_summary(
    include = c(response, marker),
    by = trt,
    type = response ~ "continuous",
    statistic = response ~ "{n1} yes / {n0} no"
  ) |> 
  add_overall() |> 
  as_kable()
```

| **Characteristic**   | **Overall**, N = 200 | **Drug A**, N = 98 | **Drug B**, N = 102 |
|:---------------------|:--------------------:|:------------------:|:-------------------:|
| Tumor Response       |   61 yes / 132 no    |   28 yes / 67 no   |   33 yes / 65 no    |
| Unknown              |          7           |         3          |          4          |
| Marker Level (ng/mL) |  0.64 (0.22, 1.39)   | 0.84 (0.24, 1.57)  |  0.52 (0.19, 1.20)  |
| Unknown              |          10          |         6          |          4          |

<sup>Created on 2023-03-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
You can even compute the proportion of yes.

``` r
library(gtsummary)
#> #BlackLivesMatter

# response is coded as 0/1
n0 <- function(x) {sum(x == 0, na.rm = TRUE)}
n1 <- function(x) {sum(x == 1, na.rm = TRUE)}
prop1 <- function (x) {mean(x, na.rm = TRUE)}

trial |> 
  tbl_summary(
    include = c(response, marker),
    by = trt,
    type = response ~ "continuous",
    statistic = response ~ "{n1} yes / {n0} no (prop yes: {prop1}%)",
    digits = response ~ c(0, 0, style_percent)
  ) |> 
  add_overall() |> 
  as_kable()
```

| **Characteristic**   |      **Overall**, N = 200       |       **Drug A**, N = 98       |      **Drug B**, N = 102       |
|:---------------------|:-------------------------------:|:------------------------------:|:------------------------------:|
| Tumor Response       | 61 yes / 132 no (prop yes: 32%) | 28 yes / 67 no (prop yes: 29%) | 33 yes / 65 no (prop yes: 34%) |
| Unknown              |                7                |               3                |               4                |
| Marker Level (ng/mL) |        0.64 (0.22, 1.39)        |       0.84 (0.24, 1.57)        |       0.52 (0.19, 1.20)        |
| Unknown              |               10                |               6                |               4                |

<sup>Created on 2023-03-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
A more generic approach / trick, using labelled vectors to pass value labels.

``` r
library(gtsummary)
#> #BlackLivesMatter
library(labelled)

one_line_table <- function(x) {
  x <- labelled::to_factor(x)
  tab <- xtabs(~x)
  paste(tab, names(tab), collapse = " / ")
}

trial$grade_labelled <-to_labelled(trial$grade) 
trial$stage_labelled <- to_labelled(trial$stage)
one_line_table(trial$stage_labelled)
#> [1] "53 T1 / 54 T2 / 43 T3 / 50 T4"

trial |> 
  tbl_summary(
    include = c(grade_labelled, response, stage_labelled),
    by = trt,
    type = ~ "continuous",
    statistic = ~ "{one_line_table}",
    digits = ~ as.character
  ) |> 
  add_overall() |> 
  as_kable()
#> ℹ Column(s) grade_labelled and stage_labelled are class "haven_labelled". This is an intermediate datastructure not meant for analysis. Convert columns with `haven::as_factor()`, `labelled::to_factor()`, `labelled::unlabelled()`, and `unclass()`. "haven_labelled" value labels are ignored when columns are not converted. Failure to convert may have unintended consequences or result in error.
#> • https://haven.tidyverse.org/articles/semantics.html
#> • https://larmarange.github.io/labelled/articles/intro_labelled.html#unlabelled
#> ℹ Column(s) grade_labelled and stage_labelled are class "haven_labelled". This is an intermediate datastructure not meant for analysis. Convert columns with `haven::as_factor()`, `labelled::to_factor()`, `labelled::unlabelled()`, and `unclass()`. "haven_labelled" value labels are ignored when columns are not converted. Failure to convert may have unintended consequences or result in error.
#> • https://haven.tidyverse.org/articles/semantics.html
#> • https://larmarange.github.io/labelled/articles/intro_labelled.html#unlabelled
```

| **Characteristic** |     **Overall**, N = 200      |      **Drug A**, N = 98       |      **Drug B**, N = 102      |
|:-------------------|:-----------------------------:|:-----------------------------:|:-----------------------------:|
| Grade              |     68 I / 68 II / 64 III     |     35 I / 32 II / 31 III     |     33 I / 36 II / 33 III     |
| Tumor Response     |         132 0 / 61 1          |          67 0 / 28 1          |          65 0 / 33 1          |
| Unknown            |               7               |               3               |               4               |
| T Stage            | 53 T1 / 54 T2 / 43 T3 / 50 T4 | 28 T1 / 25 T2 / 22 T3 / 23 T4 | 25 T1 / 29 T2 / 21 T3 / 27 T4 |

<sup>Created on 2023-03-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by TPDeramus** [comment]
Oh wow. Your first two examples are almost exactly what I want!

I'm surprised the {n1} and {n0} calls aren't in the document already (or I completely missed them if they were.

Thank you so much @larmarange!
