### ISSUE TITLE
Is the mood.test() you use in gtsummary indeed THE test of median or rather test of scales?

### ISSUE THREAD

**Issue by Generalized** [ddsjoberg/gtsummary#1482]
Hi!
In one presentation on the Internet I found a table, where samples were compared using the Mood's test. It was said that **this test tests for medians**.

That's true, Mood's test does it, but I'm wondering **which** test you use, because there are two:
- **Mood's test for dispersions** (scales), which does nothing with the location shift (medians). In R it can be done via moods.test()

- **(Brown-) Mood's test for medians,** which looks exactly at the location shift (and is less vulnerable to dispersions and shapes than Wilcoxon-Mann-Whitney, which totally fails as a test of medians, by the way. Brunner-Munzel performs a little bit better). This one can be found in coin::median_test() for instance

I created a small example illustrating the difference. There are 2 variables of same dispersion, but huge difference in means/medians (normal ones). The stats::mood.test() shows no difference with p=1. The other Brown-Mood's test shows p almost zero, as it should be.

```{r}
> set.seed(1000)
> x <- rnorm(100, mean=1, sd=2)
> y <- rnorm(100, mean=100, sd=2)
> df <- data.frame(value = c(x, y), grp = factor(rep(c("A", "B"), each=100)))
> mood.test(x, y)   # see? The means and medians are 1 and 100, but p-value is 1

	Mood two-sample test of scale

data:  x and y
Z = 0, p-value = 1
alternative hypothesis: two.sided

> coin::median_test(value ~ grp, data=df)  # here p-value is almost 0

	Asymptotic Two-Sample Brown-Mood Median Test

data:  value by grp (A, B)
Z = -14.107, p-value < 2.2e-16
alternative hypothesis: true mu is not equal to 0
```
Please make sure you don't use the stats::mood.test() if the intention was to compare medians rather than scales (dispersions).
For years this was a source of confusion among the R users. I think you might want to describe this in the package manual.|
Otherwise, if people will confuse the two, and report the result of mood.test() as a test of medians, they work may be compromised. They may have a giant effect (like on the graph below) but this test won't show it, with very high p-value.

![obraz](https://user-images.githubusercontent.com/60151643/228925227-fd78eb8a-bceb-4550-8186-1179669ae43a.png)

**Comment by Generalized** [comment]
Yes, I checked it and it says only "Mood two-sample test" but it doesn't precise **what kind of test**. If you call the stats::moods.test() then it tests the dispersions. It would be then reasonable to add it to the description something like: "_Mood two-sample test for dispersions (This is not a test of medians)_"

I just saw an example on LinkedIn, where this test was used in spirit of medians, because people recognize the "Mood's test" as a test of median. The confusion is an old, long-lasting issue, but that's exactly why it's good to clear doubts on the manual page.

BTW, you have the true Mood's test of medians below, under "**survey::svyranktest()**".

**Comment by ddsjoberg** [comment]
Thank you both. I agree that adding coin an a dependency wouldn't be great at this time (only looking to purge dependencies now!)

We do add a footnote "Mood two-sample test of scale" whenever someone uses this test, which comes from `broom::tidy()`. I would hope that users would see this and note the test of scale rather than medians. We can make this more clear; although i would stop short of adding "not a test of medians".

**Comment by Generalized** [comment]
I think it perfectly clears the doubt!

But, at the same time, as I couldn't make the other Mood's test from the survey package, please consider adding the code provided by @larmarange or the one from RVAideMemoire (they seem equivalent, though the former looks much simpler :) ) in place of the survey's one.

You will save one dependency and it will work as expected.

**Comment by larmarange** [comment]
I completely understand the fact that it is important not to add additional dependency.

Do we have a way for a user to provide a custom test? If not, would it be complex to implement?

**Comment by Generalized** [comment]
Maybe you'll find these useful:
- [Brown, Mood, "On Median Tests for Linear Hypotheses"](https://digitalassets.lib.berkeley.edu/math/ucb/text/math_s2_article-12.pdf)
- https://www.jstor.org/stable/2335872?origin=JSTOR-pdf (if you cannot access it, I can provide the article via temporary link ;])
- https://support.sas.com/documentation/onlinedoc/stat/141/npar1way.pdf

**Comment by ddsjoberg** [comment]
To be 100% transparent here...I don't have the bandwidth to read a methods paper and compare the methods implmented in `fisher.test()` 😆

**Comment by ddsjoberg** [comment]
Hi All, 

I am reviewing issues today. It seems no one is volunteering to do the work of reviewing the methods papers, researching the precise methods used in `fisher.test()` to confirm they are identical.

Therefore, I will close this issue, and users are free to use the test of medians as outlined above by passing a custom function to `add_p()`.

thank you!

**Comment by Generalized** [comment]
Let me repoen it for the reason I created the issue:
to update the manual to say "**Mood two-sample test of scale parameters**" 
or - better "**Mood two-sample test of scale parameters (not to be confused with the Brown-Mood test of medians)**".

Could you do this?

Otherwise I'm afraid many people will get confused as they already are and report completely different test than they wanted, resulting in wrong conclusions. It's exactly like running F test instead of t-test.

**Comment by ddsjoberg** [comment]
what manual are you referring to?

**Comment by Generalized** [comment]
@ddsjoberg 

I mean the reference page: https://www.danieldsjoberg.com/gtsummary/reference/tests.html

To change this:
![obraz](https://user-images.githubusercontent.com/60151643/231663615-a650c8da-0f46-4397-ad21-5ebac4cd5a81.png)

into to something like this:
![obraz](https://user-images.githubusercontent.com/60151643/231663884-e7a3f2d8-70c5-44d0-aa3b-13ac96497aca.png)

**Comment by ddsjoberg** [comment]
just pushed the update, thank you
