### ISSUE TITLE
Bug Report: <Beta estimate truncated in tbl_regression using estimate_fun=

### ISSUE THREAD

**Issue by jbtov** [ddsjoberg/gtsummary#1483]
---

Hello,

thanks for everything, in tbl_summary I wanted only one digit in my output. I used that: tbl_regression(intercept = T, estimate_fun = purrr::partial(style_ratio, digits = 1)), to do so, it aparently worked but for certain estimates and CI (close to -1), output was truncated to 1.0 which is false. I might not understand estimate_fun not properly...
Best,

```r
library(gtsummary)

mod_ex <- lm(ttdeath
                 ~
               response+grade+stage+age+trt
                 ,data = trial)
summary(mod_ex)
confint(mod_ex)

tbl_mod_ex <-
  mod_ex %>% 
  tbl_regression(intercept = T, estimate_fun = purrr::partial(style_ratio, digits = 3))
tbl_mod_ex
```

**Comment by ddsjoberg** [comment]
I am going to go ahead and close this issue. please feel free to re-open when needed

**Comment by jbtov** [comment]
Dear Pr Sjoberg,
thank you for your swift reply and sorry for my delay. 
I was expecting the Beta provided and CI to be correct which is not the case (compare in my example the outputs of summary(mod_ex) vs. tbl_regression for grades II and III, stages 3 and 4 and drug B). 
It might be linked indeed to the fact that I used  style_ratio() instead of the proper command, which I don't know what should be for Beta estimates...

**Comment by ddsjoberg** [comment]
use the default rounding.

**Comment by ddsjoberg** [comment]
my last message was truncated: use the default rounding, and provide the precise reference to the number you believe is incorrect.
