### ISSUE TITLE
add_CI with cell and row percentages

### ISSUE THREAD

**Issue by hescalar** [ddsjoberg/gtsummary#1485]
I got this output using `add_ci` with a survey design within a `tbl_svysummary` function using `percent = "cell"`

![imagen](https://user-images.githubusercontent.com/45439749/230853367-c7661eac-8e19-46ea-bd6b-d3db4cff1984.png)

The CI column is retrieving the column percentage interval, I would like it to show row or cell percentage when I need it.

**Comment by ddsjoberg** [comment]
Thank you for the post @hescalar .

Please update your post with a minimal reproducible example (a reprex). Also include what you expect to see and please ensure you're using the most recent version of the package when preparing the example.

Thank you

**Comment by larmarange** [comment]
It may be related to #1471. 

Did you try the dev version of the package?

**Comment by ddsjoberg** [comment]
Thank you @larmarange ! I mistakenly thought we had already released this on CRAN.

@hescalar please install the dev version of the package and test. Thank you

**Comment by ddsjoberg** [comment]
i think it's time to make another release....there are a number of updates that would be good to have released

**Comment by larmarange** [comment]
> i think it's time to make another release....there are a number of updates that would be good to have released

good idea!

**Comment by ddsjoberg** [comment]
@hescalar i assume this resolved your issue. please re-open if not
