### ISSUE TITLE
Bug Report: round2 is unreliable

### ISSUE THREAD

**Issue by nikostr** [ddsjoberg/gtsummary#1494]
`round2` does not reliably solve the issue of `round` not behaving in the expected way.

```r
round2(2.5)
#> 2
```
It seems to be an issue with `(number + .Machine$double.eps) == number` being true for numbers greater than 2. Perhaps it would make sense to implement `round2` as in this link? https://stackoverflow.com/questions/12688717/round-up-from-5/12688836#12688836 This is what `janitor` references in its implementation of `round_half_up`: https://github.com/sfirke/janitor/blob/main/R/round_half_up.R

**Comment by ddsjoberg** [comment]
Thank you for reporting! Gah, I hate that simple rounding is made difficult in R!
