### ISSUE TITLE
Strange outputs using `add_global_p()` with `crr()`

### ISSUE THREAD

**Issue by fdehrich** [ddsjoberg/gtsummary#1501]
Hi there,

I was experiencing some strange outputs when using `add_global_p()` with `crr()`:

- Some global p-values didn't seem to align with the CIs (eg, p <0.05 while the 95% CI included the null)
- There was a pattern where, for each of my four competing events, the global p-value for a given 4-level categorical variable was always the same as individual p-value corresponding to its third level - this could have been just a coincidence, but seemed a bit strange
- I was having an issue where switching between the options `keep = TRUE` and `keep = FALSE` seemed to shift the p-values up and down by one row, but I wasn't able to reproduce that with public data - I can send an update if I am able to later

I was able to recreate the first two items above using `tidycmprsk::trial` dataset (I had to add some extra variables and used the death variable as a predictor which doesn't make sense, but helped me recreate for some reason):
- `response` p-values don't seem to align with confidence intervals
- Seeing the same pattern described above with the `stage` and `new_categorical` variables

Thank you!

``` r
library(tidycmprsk)

# Update trial data to include additional variables
trial_updated =
  trial %>% 
  dplyr::mutate(
    new_binary = sample(c(0, 1), 
                        replace = TRUE, 
                        size = nrow(trial)),
    new_categorical = sample(c("A", "B", "C", "D"), 
                             replace = TRUE, 
                             size = nrow(trial))
  )

# Estimates for death from cancer
crr(Surv(ttdeath, death_cr) ~ ., 
    failcode = "death from cancer",
    cencode = "censor",
    trial_updated) %>%
  gtsummary::tbl_regression(exp = TRUE) %>%
  gtsummary::add_global_p(keep = TRUE) %>% 
  gtsummary::as_kable()
#> 27 cases omitted due to missing values
```

| **Characteristic**     | **HR**  |   **95% CI**    | **p-value** |
|:-----------------------|:-------:|:---------------:|:-----------:|
| Chemotherapy Treatment |         |                 |     0.4     |
| Drug A                 |    —    |        —        |             |
| Drug B                 |  1.53   |   0.81, 2.91    |     0.2     |
| Age                    |  1.01   |   0.98, 1.04    |    0.12     |
| Marker Level (ng/mL)   |  1.41   |   0.91, 2.16    |     0.7     |
| T Stage                |         |                 |     0.2     |
| T1                     |    —    |        —        |             |
| T2                     |  0.78   |   0.27, 2.29    |     0.7     |
| T3                     |  1.90   |   0.72, 5.05    |     0.2     |
| T4                     |  1.50   |   0.56, 4.03    |     0.4     |
| Grade                  |         |                 |     0.2     |
| I                      |    —    |        —        |             |
| II                     |  2.36   |   1.06, 5.27    |    0.036    |
| III                    |  1.24   |   0.62, 2.47    |     0.6     |
| Tumor Response         |  0.85   |   0.44, 1.65    |   \<0.001   |
| Patient Died           | 110,642 | 62,742, 195,110 |    0.063    |
| new_binary             |  0.53   |   0.27, 1.04    |    0.044    |
| new_categorical        |         |                 |     0.6     |
| A                      |    —    |        —        |             |
| B                      |  0.33   |   0.12, 0.97    |    0.044    |
| C                      |  0.76   |   0.29, 1.96    |     0.6     |
| D                      |  0.75   |   0.29, 1.94    |     0.6     |

``` r

# Estimates for death from other causes
crr(Surv(ttdeath, death_cr) ~ ., 
    failcode = "death other causes",
    cencode = "censor",
    trial_updated) %>%
  gtsummary::tbl_regression(exp = TRUE) %>%
  gtsummary::add_global_p(keep = TRUE) %>% 
  gtsummary::as_kable()
#> 27 cases omitted due to missing values
```

| **Characteristic**     | **HR**  |   **95% CI**    | **p-value** |
|:-----------------------|:-------:|:---------------:|:-----------:|
| Chemotherapy Treatment |         |                 |    \>0.9    |
| Drug A                 |    —    |        —        |             |
| Drug B                 |  0.91   |   0.47, 1.75    |     0.8     |
| Age                    |  1.00   |   0.97, 1.02    |     0.5     |
| Marker Level (ng/mL)   |  0.87   |   0.58, 1.31    |     0.6     |
| T Stage                |         |                 |     0.4     |
| T1                     |    —    |        —        |             |
| T2                     |  1.30   |   0.55, 3.08    |     0.6     |
| T3                     |  0.64   |   0.22, 1.87    |     0.4     |
| T4                     |  0.92   |   0.37, 2.27    |     0.9     |
| Grade                  |         |                 |     0.9     |
| I                      |    —    |        —        |             |
| II                     |  0.69   |   0.29, 1.67    |     0.4     |
| III                    |  0.91   |   0.45, 1.86    |     0.8     |
| Tumor Response         |  1.14   |   0.51, 2.55    |   \<0.001   |
| Patient Died           | 102,841 | 63,899, 165,515 |     0.2     |
| new_binary             |  1.53   |   0.79, 2.96    |    0.13     |
| new_categorical        |         |                 |     0.8     |
| A                      |    —    |        —        |             |
| B                      |  2.02   |   0.81, 5.05    |    0.13     |
| C                      |  0.87   |   0.30, 2.54    |     0.8     |
| D                      |  1.09   |   0.38, 3.10    |     0.9     |

<sup>Created on 2023-04-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
dear @fdehrich , can you post these are separate issue to the tidycmprsk package GH page?

CI and p-values _sometimes_ have a one to one relationship, but not always. We document the CI method on the tidycmprsk website
