### ISSUE TITLE
Feature request: Ability to pass a weighted dataframe into gt_summary()

### ISSUE THREAD

**Issue by ablack3** [ddsjoberg/gtsummary#1504]
**Is your feature request related to a problem? Please describe.**
The dataset I have is too large to fit into R. I can however create a small weighted dataset where each row represents `n` people instead of 1 person. I would like to pass this weighted dataset into `gt_summary`.

**Describe the solution you'd like**
Add a `wt` argument to `gt_summary`. This new argument would be used to pass the name of a weight variable and `gt_summary` would weight all the statistics by the value of this variable.

**Comment by ddsjoberg** [comment]
you can do this by converting your data to a survey object and utilizing `tbl_svysummary()`.

**Comment by ablack3** [comment]
Nice! here is a simple reprex. It might still be nice for tbl_summary to support weights but this works for me. Thank you for this awesome R package.

``` r
df <- tibble::tribble(
  ~label,   ~n,
  "Alcohol Abuse",  30L,
  "Alcohol Dependence",  17L,
  "Anxiety Disorder", 180L,
  "Backache", 324L,
  "Cannabis abuse",   4L,
  "Cannabis dependence",   5L,
  "Chronic kidney disease", 206L,
  "Congestive heart failure", 270L,
  "Coronary artery disease", 349L,
  "Mood disorder", 285L,
  "Nicotine dependence", 123L,
  "Opioid abuse",   2L,
  "Opioid dependence",  10L,
  "Personality disorder",  34L,
  "Posttraumatic stress disorder",  18L,
  "Psychoactive substance abuse",  46L,
  "Psychoactive substance dependence",  17L,
  "Psychoactive substance use disorder",  24L,
  "Psychotic disorder", 147L,
  "Substance abuse",  54L
)


gtsummary::tbl_svysummary(survey::svydesign(~1, data = df, weights = ~n), include = -n)
```

<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
 
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">label</td>
<td headers="stat_0" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Alcohol Abuse</td>
<td headers="stat_0" class="gt_row gt_center">30 (1.4%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Alcohol Dependence</td>
<td headers="stat_0" class="gt_row gt_center">17 (0.8%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Anxiety Disorder</td>
<td headers="stat_0" class="gt_row gt_center">180 (8.4%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Backache</td>
<td headers="stat_0" class="gt_row gt_center">324 (15%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Cannabis abuse</td>
<td headers="stat_0" class="gt_row gt_center">4 (0.2%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Cannabis dependence</td>
<td headers="stat_0" class="gt_row gt_center">5 (0.2%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Chronic kidney disease</td>
<td headers="stat_0" class="gt_row gt_center">206 (9.6%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Congestive heart failure</td>
<td headers="stat_0" class="gt_row gt_center">270 (13%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Coronary artery disease</td>
<td headers="stat_0" class="gt_row gt_center">349 (16%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Mood disorder</td>
<td headers="stat_0" class="gt_row gt_center">285 (13%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Nicotine dependence</td>
<td headers="stat_0" class="gt_row gt_center">123 (5.7%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Opioid abuse</td>
<td headers="stat_0" class="gt_row gt_center">2 (&lt;0.1%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Opioid dependence</td>
<td headers="stat_0" class="gt_row gt_center">10 (0.5%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Personality disorder</td>
<td headers="stat_0" class="gt_row gt_center">34 (1.6%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Posttraumatic stress disorder</td>
<td headers="stat_0" class="gt_row gt_center">18 (0.8%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Psychoactive substance abuse</td>
<td headers="stat_0" class="gt_row gt_center">46 (2.1%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Psychoactive substance dependence</td>
<td headers="stat_0" class="gt_row gt_center">17 (0.8%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Psychoactive substance use disorder</td>
<td headers="stat_0" class="gt_row gt_center">24 (1.1%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Psychotic disorder</td>
<td headers="stat_0" class="gt_row gt_center">147 (6.9%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Substance abuse</td>
<td headers="stat_0" class="gt_row gt_center">54 (2.5%)</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="2"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> n (%)</td>
    </tr>
  </tfoot>
</table>
</div>

<sup>Created on 2023-05-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
