### ISSUE TITLE
Feature request: Could you count missing values in continuous variables?

### ISSUE THREAD

**Issue by JBarsotti** [ddsjoberg/gtsummary#1508]
First off, wonderful R library!

I noticed that when I choose the option to add a "missing" column to a table, it will include the number of missing values in the total count of observations for each categorical variable (e.g., gender). However, it will not include the number of missing values in the total count for continuous variables (e.g., age). For instance, if I have 30 observations, and 5 are missing gender and age, the total number of observations for gender will be 30, but it will only be 25 for age.

Is there a way to work around that? I'd like to count the missing values and add them to the total number of observations (age and gender both equal 30) in my example.

Thank you for such an awesome R library!

**Comment by ddsjoberg** [comment]
@JBarsotti delighted the package has been useful for you!

Can you give an example of the output you want to see?

**Comment by ddsjoberg** [comment]
Please feel free to re=open when you're ready

**Comment by JBarsotti** [comment]
Sorry for the late reply. I had finals week. Here is a table of fake data illustrating what I was talking about. I get why you don't count the N/A values for the continuous variable because they are ignored when calculated mean, standard deviation, etc. but it does make the counts between continuous and categorical inconsistent.

![summary_stats](https://github.com/ddsjoberg/gtsummary/assets/75189583/182c7a37-e4fd-42a0-bf32-b10ff87ac8be)

**Comment by ddsjoberg** [comment]
No worries. Honestly I am still confused what you're requesting, or even what which Ns you're comparing. Are you referring to the counts in `add_n()`. The default is to report the number of non-missing, which does not count missing values for continuous and categorical data differently.

Please include an example (you can use the `trial` data set that is exported from gtsummary) and code that shows the inconsistent results. Then please mock-up a table of what you'd like to see, and we can go from there?

**Comment by JBarsotti** [comment]
Okay, here it is:

![image](https://github.com/ddsjoberg/gtsummary/assets/75189583/5cf5c2b2-c6dc-4f11-8444-973ba7f712fb)

I guess I'd like to see _n = 200_ for the continuous variables. In my dataset (which I'm not at liberty to share) there are missing values in categorical and continuous variables, but the categorical variables all have _n = 200_ while the continuous do not count the missing values.

**Comment by ddsjoberg** [comment]
Hmmm, but in the example above, the categorical variables don't have missing observations, so it's reporting N=200.

In the example below, i've made one missing observation in grade, so it now shows N=199 non-missing observations.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.7.1'

trial |> 
  dplyr::mutate(grade = ifelse(dplyr::row_number() == 1L, NA, grade)) |> 
  tbl_summary(
    include = c(age, grade, stage),
    missing = "always"    
  ) |> 
  add_n() |> 
  as_kable()
```

| **Characteristic** | **N** | **N = 200** |
|:-------------------|:-----:|:-----------:|
| Age                |  189  | 47 (38, 57) |
| Unknown            |       |     11      |
| grade              |  199  |             |
| 1                  |       |  68 (34%)   |
| 2                  |       |  67 (34%)   |
| 3                  |       |  64 (32%)   |
| Unknown            |       |      1      |
| T Stage            |  200  |             |
| T1                 |       |  53 (27%)   |
| T2                 |       |  54 (27%)   |
| T3                 |       |  43 (22%)   |
| T4                 |       |  50 (25%)   |
| Unknown            |       |      0      |

<sup>Created on 2023-05-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


I think we are talking about different things?

**Comment by ddsjoberg** [comment]
Maybe adding the denominator makes it more clear?

``` r
library(gtsummary)
#> #StandWithUkraine
packageVersion("gtsummary")
#> [1] '1.7.1'

trial |> 
  dplyr::mutate(grade = ifelse(dplyr::row_number() == 1L, NA, grade)) |> 
  tbl_summary(
    include = c(age, grade, stage),
    missing = "always"    
  ) |> 
  add_n(statistic = "{n} / {N_obs}") |> 
  as_kable()
```

| **Characteristic** |   **N**   | **N = 200** |
|:-------------------|:---------:|:-----------:|
| Age                | 189 / 200 | 47 (38, 57) |
| Unknown            |           |     11      |
| grade              | 199 / 200 |             |
| 1                  |           |  68 (34%)   |
| 2                  |           |  67 (34%)   |
| 3                  |           |  64 (32%)   |
| Unknown            |           |      1      |
| T Stage            | 200 / 200 |             |
| T1                 |           |  53 (27%)   |
| T2                 |           |  54 (27%)   |
| T3                 |           |  43 (22%)   |
| T4                 |           |  50 (25%)   |
| Unknown            |           |      0      |

<sup>Created on 2023-05-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by JBarsotti** [comment]
I created a table using my data where the missing were getting counted for categorical variables but not for continuous. Maybe it's something unique to my dataset, though, because it appears to be working in your example.
________________________________
From: Daniel Sjoberg ***@***.***>
Sent: Saturday, May 20, 2023 9:06 PM
To: ddsjoberg/gtsummary ***@***.***>
Cc: Barsotti, Ercole ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [ddsjoberg/gtsummary] Feature request: Could you count missing values in continuous variables? (Issue #1508)


Hmmm, but in the example above, the categorical variables don't have missing observations, so it's reporting N=200.

In the example below, i've made one missing observation in grade, so it now shows N=199 non-missing observations.

library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.7.1'

trial |>
  dplyr::mutate(grade = ifelse(dplyr::row_number() == 1L, NA, grade)) |>
  tbl_summary(
    include = c(age, grade, stage),
    missing = "always"
  ) |>
  add_n() |>
  as_kable()

Characteristic  N       N = 200
Age     189     47 (38, 57)
Unknown         11
grade   199
1               68 (34%)
2               67 (34%)
3               64 (32%)
Unknown         1
T Stage 200
T1              53 (27%)
T2              54 (27%)
T3              43 (22%)
T4              50 (25%)
Unknown         0

Created on 2023-05-20 with reprex v2.0.2<https://reprex.tidyverse.org>

I think we are talking about different things?

**Comment by JBarsotti** [comment]
Oh, I like that idea! I didn't even think of that!
________________________________
From: Daniel Sjoberg ***@***.***>
Sent: Saturday, May 20, 2023 9:08 PM
To: ddsjoberg/gtsummary ***@***.***>
Cc: Barsotti, Ercole ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [ddsjoberg/gtsummary] Feature request: Could you count missing values in continuous variables? (Issue #1508)


Maybe adding the denominator makes it more clear?

library(gtsummary)
#> #StandWithUkraine
packageVersion("gtsummary")
#> [1] '1.7.1'

trial |>
  dplyr::mutate(grade = ifelse(dplyr::row_number() == 1L, NA, grade)) |>
  tbl_summary(
    include = c(age, grade, stage),
    missing = "always"
  ) |>
  add_n(statistic = "{n} / {N_obs}") |>
  as_kable()

Characteristic  N       N = 200
Age     189 / 200       47 (38, 57)
Unknown         11
grade   199 / 200
1               68 (34%)
2               67 (34%)
3               64 (32%)
Unknown         1
T Stage 200 / 200
T1              53 (27%)
T2              54 (27%)
T3              43 (22%)
T4              50 (25%)
Unknown         0

Created on 2023-05-20 with reprex v2.0.2<https://reprex.tidyverse.org>

**Comment by JBarsotti** [comment]
I'm so sorry for wasting your time. I figured out what it was after looking at my code again. I was replacing some N/A with a string, so gtsummary thought it wasn't unknown when it was.
