### ISSUE TITLE
Bug Report: using chi² whereas Fisher is expected

### ISSUE THREAD

**Issue by oliviercailloux** [ddsjoberg/gtsummary#1513]
I apologize in advance if I missed something again, but the following code seems to behave differently than documented.

```r
t <- tibble(type = character(), answer = character()) %>% 
  add_row(uncount(tibble(type = "A", answer = "C1"), 5)) %>% 
  add_row(uncount(tibble(type = "B", answer = "C1"), 10)) %>% 
  add_row(uncount(tibble(type = "A", answer = "C2"), 100)) %>% 
  add_row(uncount(tibble(type = "B", answer = "C2"), 305)) %>% 
  add_row(uncount(tibble(type = "A", answer = NA), 400)) %>% 
  add_row(uncount(tibble(type = "B", answer = NA), 300))
t %>% tbl_summary(by=type) %>% add_p()
```

The [doc](https://www.danieldsjoberg.com/gtsummary/reference/add_p.tbl_summary.html) states that "Tests default to (...) "chisq.test.no.correct" for categorical variables with all expected cell counts >=5, and "fisher.test" for categorical variables with any expected cell count <5." Here, cell A/C1 has expected count 15 * 105 / 420 = 15 / 4 < 4 but gtsummary uses a chi squared test (as it indicates in the footnote, and as appears in the warning sent by chi squared test which is unhappy about the approximation).

**Comment by ddsjoberg** [comment]
I think you calculated your expected counts incorrectly

``` r
library(gtsummary)

ttt <- tibble::tibble(type = character(), answer = character()) %>% 
  tibble::add_row(tidyr::uncount(tibble::tibble(type = "A", answer = "C1"), 5)) %>% 
  tibble::add_row(tidyr::uncount(tibble::tibble(type = "B", answer = "C1"), 10)) %>% 
  tibble::add_row(tidyr::uncount(tibble::tibble(type = "A", answer = "C2"), 100)) %>% 
  tibble::add_row(tidyr::uncount(tibble::tibble(type = "B", answer = "C2"), 305)) %>% 
  tibble::add_row(tidyr::uncount(tibble::tibble(type = "A", answer = NA), 400)) %>% 
  tibble::add_row(tidyr::uncount(tibble::tibble(type = "B", answer = NA), 300))

ttt |> 
  tbl_cross(statistic = "{p}%") |> 
  as_kable()
```

|       |  C1  |  C2  | Unknown | Total |
|:------|:----:|:----:|:-------:|:-----:|
| type  |      |      |         |       |
| A     | 0.4% | 8.9% |   36%   |  45%  |
| B     | 0.9% | 27%  |   27%   |  55%  |
| Total | 1.3% | 36%  |   63%   | 100%  |

``` r
# expected count
0.013 * 0.45 * nrow(ttt)
#> [1] 6.552
 
```

<sup>Created on 2023-05-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by oliviercailloux** [comment]
Ah, you consider the expected counts by including the NA (Unknown) entries, contrary to me. This is as if NA was another category, treated on par with the C1 and C2 categories. 

Considering NA as yet another category certainly makes sense in some situations, but then shouldn’t the chi² test itself also consider NA as a category? Currently, gtsummary seems to apply chi² as [documented](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/chisq.test), thus, “cases with missing values are removed”. I find it therefore surprising that the expected counts consider NA as a category.

Note that a supplementary side effect of this treatment is that the `chisq.test` function warns about a possibly invalid approximation.

**Comment by ddsjoberg** [comment]
you're 100% correct, apologies. When the NAs are removed, the expected counts are still above 5

**Comment by ddsjoberg** [comment]
(and the NAs are removed before making the expected count assessment)

**Comment by oliviercailloux** [comment]
> ```r
> 0.036 * 0.25 * nrow(ttt)
> #> [1] 10.08

That’s with `nrow(ttt)` = 1120. With the removed NAs, the total count is 420.

**Comment by ddsjoberg** [comment]
@oliviercailloux thank you so much for reporting this! the bug occurred when there was a large number of missing in one variable relative to the other as the rates we being calculated separately, rather than a complete case estimation by both variables. again, thank you!
