### ISSUE TITLE
Bug Report: tbl_butcher not really butchering

### ISSUE THREAD

**Issue by xtimbeau** [ddsjoberg/gtsummary#1515]
When running a regression on a large dataset and `gtsummary::tbl_regression`-ing it, I do get a large object. tbl_butcher should strip everything linked to the original model, but environment of function inside table_styling are still there and the objet is not reduce in size.
What is expected is to have a stripped object without the environment ?

here is a reprex with a small regression model :
```
library(survival)
library(gtsummary)
library(lobstr)
tbl_r <-  coxph(Surv(ttdeath, death) ~ age + marker, trial) %>%
  tbl_regression(exponentiate = TRUE)
tbl_rb <- tbl_r |> tbl_butcher()
obj_size(tbl_r)
obj_size(tbl_rb)
obj_size(tbl_rb$table_styling$fmt_fun$fmt_fun)

# partialised functions still have the environment and all the data
purrr::map(tbl_rb$table_styling$fmt_fun$fmt_fun, ~obj_size(.x))

# here it is: 
mget("x", environment(tbl_rb$table_styling$fmt_fun$fmt_fun[[10]]))$x |> names()
mget("x", environment(tbl_rb$table_styling$fmt_fun$fmt_fun[[10]]))$x$inputs |> obj_size()
mget("x", environment(tbl_rb$table_styling$fmt_fun$fmt_fun[[10]]))$x$model_obj |> obj_size()
mget("x", environment(tbl_rb$table_styling$fmt_fun$fmt_fun[[10]]))$x$call_list |> obj_size()
obj_size(mget("x", environment(tbl_rb$table_styling$fmt_fun$fmt_fun[[10]]))$x$call_list)
```

output:
```
> # partialised functions still have the environment and all the data
> purrr::map_dbl(tbl_rb$table_styling$fmt_fun$fmt_fun, ~obj_size(.x))
 [1]  10664  22576  22576  22576  22576  22576  10664  10664  33616 234728 234728 234728 234728 234728
> 
> # here it is: 
> mget("x", environment(tbl_rb$table_styling$fmt_fun$fmt_fun[[10]]))$x |> names()
[1] "table_body"    "table_styling" "N"             "n"             "N_event"       "model_obj"     "inputs"       
[8] "call_list"    
> mget("x", environment(tbl_rb$table_styling$fmt_fun$fmt_fun[[10]]))$x$inputs |> obj_size()
118.45 kB
> mget("x", environment(tbl_rb$table_styling$fmt_fun$fmt_fun[[10]]))$x$model_obj |> obj_size()
32.08 kB
> mget("x", environment(tbl_rb$table_styling$fmt_fun$fmt_fun[[10]]))$x$call_list |> obj_size()
25.01 kB
> obj_size(mget("x", environment(tbl_rb$table_styling$fmt_fun$fmt_fun[[10]]))$x$call_list)
25.01
```

**Comment by ddsjoberg** [comment]
ahh, thank you for the detailed post. this must have been a regression at some point and I didn't realize. I am planning a major re-write of the internals to speed it up and remove dependencies like purrrr (and partialized functions), so that should take care of it.

**Comment by xtimbeau** [comment]
Good to know !
Any work around in the meantime ?

**Comment by ddsjoberg** [comment]
Hmmm, no good solutions at the moment. You could try replacing those `fmt_fun` objects with a function that hasn't been partialized...i haven't tested this solution fyi

**Comment by xtimbeau** [comment]
ok, that works for my use case although it not very clean in the making, but this idea may solve the issue (environment from partialise is wrong, gtsummary namespace is sufficient)
```
tbl_deepbutcher <- function(tbl) {
  tbl <- tbl_butcher(tbl)
  environment(tbl$table_styling$fmt_fun$fmt_fun[[1]]) -> gtsum
  tbl$table_styling$fmt_missing$rows <- map(tbl$table_styling$fmt_missing$rows, ~{
    environment(.x) <- gtsum
    .x
  })
  tbl$table_styling$fmt_fun$rows <- map(tbl$table_styling$fmt_fun$rows, ~{
    environment(.x) <- gtsum
    .x
  })
  tbl$table_styling$fmt_fun$fmt_fun <- map(tbl$table_styling$fmt_fun$fmt_fun, ~{
    environment(.x) <- gtsum
    .x
  })
  tbl$table_styling$cols_merge$rows <- map(tbl$table_styling$cols_merge$rows, ~{
    environment(.x) <- gtsum
    .x
  })
  tbl
}
```

**Comment by ddsjoberg** [comment]
NOTE TO SELF: I think the easiest way to reduce the size of these functions is to save the same information not in a function, because the function saves the environment where it was created with it. For example, if the stat is to be rounded to one decimal place, just save `1L`. That would cover most of them, but I would need to come up with simple syntax for sigfig rounding and ratio rounding.

Alternatively, I could probably play around with a way of defining a function (which will always have the env attached), but create it in an fresh env.

**Comment by DesiQuintans** [comment]
I did a bit of noodling with some generated tables from work (therefore unshareable, sorry!) and their final file sizes. The output is a `list` of 10 `tbl_regression()` objects generated from `glmer` models with 13 covariates each, so pretty beefy already. The list itself was `save()`d and here are the sizes of the final .Rdata files:

| Conversion             | File size  |
|------------------------|------------|
| as_gt()                | 157,197 KB |
| Raw (tbl_regression()) | 156,514 KB |
| tbl_butcher()          | 146,007 KB |
| as_flex_table()        | 50 KB      |
| as_hux_table()         | 7.4 KB     |
| as_kable_extra()       | 4.1 KB     |
| as_tibble()            | 3.8 KB     |
| as_kable()             | 3.7 KB     |
| as.data.frame()        | 3.5 KB     |

So for anyone else who wants a solution in the meantime, `as_flex_table()` is a good option for shrinking table file sizes that still gives great control over the final table's presentation in reports etc.

**Comment by ddsjoberg** [comment]
Hello,

In the current dev version, rather than creating formatting functions that save the env they were created in, I've opted for functions that return formatting functions making the associated env much much smaller.

Hope that helps!

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.9.9.9000'
```

``` r

tbl_large <-
  trial |>
  tbl_uvregression(
    y = age,
    method = lm
  )

tbl_butchered <-
  tbl_large |>
  tbl_butcher()

# percent size reduction
((object.size(tbl_butchered) - object.size(tbl_large)) / object.size(tbl_large)) %>%
  {paste0(style_sigfig(., scale = 100), "%")}
#> [1] "-81%"
```

<sup>Created on 2024-06-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
