### ISSUE TITLE
Feature request: Add coxphf to existing models

### ISSUE THREAD

**Issue by albamrt** [ddsjoberg/gtsummary#1519]
**Is your feature request related to a problem? Please describe.**
In the listing of the supported models for tbl_regression and tbl_uvregression, it says: '[...] If a model follows a standard format and has a tidier, it’s likely to be supported as well, even if not listed below.'

I guess the coxphf function does not have a tidier, but its output is pretty standard and the usage is quite similar to the coxph function from the survival package, so I was wondering if it would be possible to include it as an option in the future.

**Describe alternatives you've considered**
I really like your package and for now I will just build the tables myself, but I was wondering if it would be possible to include it in the future. Thank you in advance!

**Comment by ddsjoberg** [comment]
All of the regression model prep is handled with @larmarange  in the broom.helpers package. https://github.com/larmarange/broom.helpers/issues

Please post the issue there and please include a working code example we can run on our machine (eg code and data). Also please document whether there is a tidier function from the {broom} package or another package.

Thanks
