### ISSUE TITLE
Modify_footnote does not work with tbl_svysummary

### ISSUE THREAD

**Issue by abduazizR** [ddsjoberg/gtsummary#1521]
Hi,

First of all, thank you so much for the work on this awesome package.
I just wanted to bring to your attention that modify_footer does not work with tbl_svysummary

Running the following example does not remove the footer

```
data(api, package = "survey")
tbl_svysummary_ex2 <-
    survey::svydesign(id = ~dnum, weights = ~pw, data = apiclus1, fpc = ~fpc) %>%
    tbl_svysummary(by = "both", include = c(api00, stype))

tbl_svysummary_ex2 |>   modify_footnote(update = everything() ~ NA, abbreviation = TRUE)
```

Any help?

Thanks

**Comment by ddsjoberg** [comment]
What do you expect the output to be? I imagine you just need to leave the abbreviation argument to FALSE.

**Comment by abduazizR** [comment]
Thanks. For some reason, this does not work for confidence intervals when I use add_ci(). It still shows me the footnote regardless

**Comment by ddsjoberg** [comment]
run the function twice, once for abbreviations and once for other footnotes....they are handled separately (it's confusing, and was a poor design choice!)

**Comment by abduazizR** [comment]
This worked!!!
Thanks a lot!
