### ISSUE TITLE
Feature request: Option for tbl_summary to use variable names as labels, even when variable labels are available

### ISSUE THREAD

**Issue by eremingt** [ddsjoberg/gtsummary#1522]
Currently, the behavior of tbl_summary in the case that `label` is not specified:

> If a variable's label is not specified here, the label attribute (attr(data$age, "label")) is used. If attribute label is NULL, the variable name will be used.

This is a problem when using tidyr::pivot_wider() prior to tbl_summary, when the value column has a label, e.g.:

```
df %>%
  tidyr::pivot_wider(
    names_from = label_col, # I want these to be the label
    values_from = values_col, # If this column has a label, tidyr applies it to all the new columns
  ) %>%
  gtsummary::tbl_summary()
```

In this case, every item in my table summary has the same label.

I would like to have an option like `label = NULL`, or `label = 'name'`, where tbl_summary will use the variable names as labels, even if `(attr(df$col, "label"))` is not NULL

It seems like the ideal solution would be some control in tidyr about what gets assigned to the label when using pivot_wider, but it seems that is [not in the cards](https://github.com/tidyverse/tidyr/issues/1082). Stripping the label from the value column prior to pivoting is a suitable workaround, but thought I would suggest this as well.

**Comment by larmarange** [comment]
You could simply apply labelled::remove_var_label() justbefor calling tbl_summay()

Cf. https://larmarange.github.io/labelled/reference/remove_labels.html

**Comment by eremingt** [comment]
> You could simply apply labelled::remove_var_label() justbefor calling tbl_summay()
> 
> Cf. https://larmarange.github.io/labelled/reference/remove_labels.html

Yes, that's what I'm doing now, but thought to suggest this as well. Feel free to close.

**Comment by ddsjoberg** [comment]
i like @larmarange 's suggestion for this! thank you for the posts!
