### ISSUE TITLE
Feature request: <Add_ci for row percent in tbl_svysummary>

### ISSUE THREAD

**Issue by jbtov** [ddsjoberg/gtsummary#1523]
Hello,

I saw a [post](https://stackoverflow.com/questions/75186902/add-ci-for-row-percentages-gtsummary-and-tbl-svysummary) about that and I'm not sure the request has been done. It would be great to have the CI of row percents in epidemiology.

Don't you think?

Best,

tbl_svysummary_ex1 <-
  survey::svydesign(~1, data = as.data.frame(Titanic), weights = ~Freq) %>%
  tbl_svysummary(include = c(Class, Age),
                 by = Survived,
                 statistic = c(Class, Age) ~ "{p} %",
                 percent = "row"
                 )%>%
  add_ci(
    method = c(Class, Age) ~ "svyprop",
    style_fun = c(Class, Age) ~ purrr::partial(style_percent, digits = 1)
  )%>%
  modify_header(all_stat_cols() ~ "**Survived**")%>%
  modify_column_hide(columns = c("stat_1", "ci_stat_1"))%>%
  add_overall(
    last = F,
    statistic = ~"{n}",
    digits = ~0
  )
tbl_svysummary_ex1

**Comment by larmarange** [comment]
It has been fixed in the dev version. cf. #1471

**Comment by ddsjoberg** [comment]
@jbtov this is in the most recent release available on CRAN. please update your gtsummary installation to take advantage of the update
