### ISSUE TITLE
Bug Report: knitr::kable() changes after using as_kable_extra()

### ISSUE THREAD

**Issue by melindahiggins2000** [ddsjoberg/gtsummary#1524]
After using gtsummary::as_kable_extra() the formatting of tables changes for all following code chunks. Here is a reproducible Rmarkdown example to illustrate the issue.

````
---
title: "Rep Example gtsummary kable"
author: "First Last"
date: "2023-06-10"
output:
  pdf_document: default
---

## Using knitr::kable()

```{r}
library(dplyr)

mtcars %>%
  slice(1:5) %>%
  knitr::kable(caption = "1st 5 rows of mtcars")
```

\newpage
## Using gtsummary with as_kable_extra(tbl, format = "latex")

By adding `as_kable_extra(tbl, format = "latex")` to knit to PDF, the table is now forced to top of page before the heading and also changes the formatting and page placement of the next table generated in the next R chunk below.

```{r}
library(gtsummary)

tbl <- mtcars %>%
  select(cyl) %>%
  tbl_summary() %>%
  modify_caption(caption = "summary of cylinders")

as_kable_extra(tbl, format = "latex")
```

\newpage
## Do knitr::kable() again

notice the added lines - formatting is different

```{r}
mtcars %>%
  slice(1:5) %>%
  knitr::kable(caption = "1st 5 rows of mtcars")
```
````

**Comment by ddsjoberg** [comment]
Thank you for the post @melindahiggins2000 ! I'll investigate when i get a chance. In the meantime, can you post attach the resulting PDF to the issue?

**Comment by melindahiggins2000** [comment]
I found a work around by manipulating the auto formatting settings in `kableExtra`. Here is the corrected Rmarkdown.

It would be nice if there was a way to incorporate these options in the `as_kable_extra()` pass throughs.

Corrected Rmarkdown:

````
---
title: "Rep Example gtsummary kable"
author: "Firstname Lastname"
date: "2023-06-10"
output:
  pdf_document: default
---

## Using knitr::kable()

```{r}
library(dplyr)

mtcars %>%
  slice(1:5) %>%
  knitr::kable(caption = "1st 5 rows of mtcars")
```

\newpage
## Using gtsummary with as_kable_extra(tbl, format = "latex")

By adding `as_kable_extra(tbl, format = "latex")` to knit to PDF, the table is now forced to top of page before the heading and also changes the formatting and page placement of the next table generated in the next R chunk below.

```{r}
# see p3-4 of https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_pdf.pdf to turn off auto formatting
options(kableExtra.auto_format = FALSE)

library(gtsummary)

tbl <- mtcars %>%
  select(cyl) %>%
  tbl_summary() %>%
  modify_caption(caption = "summary of cylinders")

# to remove auto positioning
# set kableExtra::kable_styling(latex_options = "HOLD_position")
# see https://tex.stackexchange.com/questions/544858/how-to-keep-a-table-on-the-same-page
tbl %>% as_kable_extra(format = "latex") %>%
  kableExtra::kable_styling(latex_options = "HOLD_position")
```

\newpage
## Do knitr::kable() again

notice the added lines - formatting is different

```{r}
mtcars %>%
  slice(1:5) %>%
  knitr::kable(caption = "1st 5 rows of mtcars")
```
````

And I'm attaching the uncorrected and corrected PDFs for reference.

Thank you!
Melinda

## PDF without corrections
[repExample_gtsummary_woCorrections.pdf](https://github.com/ddsjoberg/gtsummary/files/11712696/repExample_gtsummary_woCorrections.pdf)

## PDF with corrections
[repExample_gtsummary_wCorrections.pdf](https://github.com/ddsjoberg/gtsummary/files/11712695/repExample_gtsummary_wCorrections.pdf)

**Comment by ddsjoberg** [comment]
Thanks for the update @melindahiggins2000 .

This is a feature in kableExtra, and I don't think gtsummary should be changing default kableExtra behavior because it will likely cause more headaches for other users expecting the default behavior. 

![image](https://github.com/ddsjoberg/gtsummary/assets/26774684/7c558adf-81e7-46c3-aecd-a455d42b0a91)

What do you think?

**Comment by melindahiggins2000** [comment]
Sounds good. Perhaps add some more information on the gtsummary Rmarkdown vignette [https://www.danieldsjoberg.com/gtsummary/articles/rmarkdown.html](https://www.danieldsjoberg.com/gtsummary/articles/rmarkdown.html). And this issue will be on Github for others to find and reference.

Thank you again for the quick reply!!
Melinda

**Comment by ddsjoberg** [comment]
thank you for posting! i learned something new today :)
