### ISSUE TITLE
Bug Report: `as_kable` breaks lines when theme is set to journal "qjecon"

### ISSUE THREAD

**Issue by philsf** [ddsjoberg/gtsummary#1526]
Hi, I noticed that when the table theme is set to `qjecon` the output of `as_kable()` has linebreaks that create quite a mess in RMarkdown documents.

Here is the output of the first example in the manpage. It appears that the linebreaks are being introduced between the estimate and the SE.

Observed:
```
theme_gtsummary_journal("qjecon")
coxph(Surv(ttdeath, death) ~ age + marker, trial) %>% tbl_regression(exponentiate = TRUE) %>% as_kable()

|**Characteristic**   | **HR**  
**(SE)** |
|:--------------------|:----------------:|
|Age                  |  1.01  
(0.007)   |
|Marker Level (ng/mL) |  0.96  
(0.121)   |
```

Expected:
```
theme_gtsummary_journal("lancet")
coxph(Surv(ttdeath, death) ~ age + marker, trial) %>% tbl_regression(exponentiate = TRUE) %>% as_kable()

|**Characteristic**   | **HR** |  **95% CI**  | **p-value** |
|:--------------------|:------:|:------------:|:-----------:|
|Age                  |  1·01  | 0·99 to 1·02 |    0·36     |
|Marker Level (ng/mL) |  0·96  | 0·76 to 1·21 |    0·72     |
```

My guess is that the issue appears in the following two `\n` in `theme_gtsummary_journal()`. Calling `add_significance_stars()` manually without  the linebreak fixes the formatting in the table body.
```
paste(x$table_styling$header %>% filter(.data$column == "estimate") %>% pull("label"), "**(SE)**", sep = "  \n") # in the header
add_significance_stars(pattern = "{estimate}{stars}  \n({std.error})", hide_se = TRUE) # in the estimate
```

Is there a reason for these two linebreaks in the function, or perhaps they are just fossils of a bygone era?

**Comment by ddsjoberg** [comment]
Hi @philsf ! Thanks for the post!

>  quite a mess in RMarkdown documents

Can you update your post with a screenshot of a rendered R markdown document illustrating the issue?

**Comment by ddsjoberg** [comment]
Nevermind about the screenshot

![image](https://github.com/ddsjoberg/gtsummary/assets/26774684/2966e28e-5e97-4b5b-a4d7-81453d683286)

The linebreaks are there to stack the HR and SE, which is how these results are presented in that journal.

The package is focused on gt output (hence the name). I support other output formats, but not all formatting features are available for all formats. For example, kable does not support spanning headers, footnotes, or indentation. And now I can add line breaks within a cell to that list ;)

What do you think?

**Comment by ddsjoberg** [comment]
My first suggestion is that if you need `as_kable()`, don't use functions/themes that add line breaks. I am not really looking to put more dev time into gtsummary right now, unfortunately.

There are a couple of other options:
![image](https://github.com/ddsjoberg/gtsummary/assets/26774684/d981dfa3-d6b2-4918-b476-5fc0e3be26bb)

**Comment by ddsjoberg** [comment]
also, I promise `as_kable()` isn't going anywhere ;)
