### ISSUE TITLE
Bug Report: <gtsummary Overall Columns moves after merge>

### ISSUE THREAD

**Issue by derekstein** [ddsjoberg/gtsummary#1527]
It seems at one point this bug was fixed but I am observing the same behaviour where the Overall column moves after a merge with the following argument: modify_spanning_header(stat_0_1 ~ NA). The behaviour was documented in this stackoverflow issue (https://stackoverflow.com/questions/65882941/r-gtsummary-overall-column-moved-after-merge#_=_). Is there a version of gtsummary that I can use that will correct this?

**Comment by ddsjoberg** [comment]
thank you for the post! greatly appreciated.
#1528
