### ISSUE TITLE
Bug Report: Error when rendering pdf quarto documents with gtsummary::tbl_regression(intercept = TRUE) |> gtsummary::as_gt() 

### ISSUE THREAD

**Issue by gorkang** [ddsjoberg/gtsummary#1533]
If as quarto (.qmd) document has a gtsummary::tbl_regression(model, **intercept = TRUE**) |> gtsummary::as_gt() it will fail when rendering as a pdf.

`gtsummary::tbl_regression(model) |> gtsummary::as_gt() ` will work, so all points to **intercept = TRUE** as the culprit.

The error is:

```
compilation failed- error
Undefined control sequence.
<argument> ...al \expandafter \let \cmrsideswitch 
                                                  \@tempa \fi \fi 
l.210 (Intercept)
                  & 0.93 & 0.50, 1.4 & <0.001 \\ 


```

---

This are the contents of a minimal qmd document that fails.  

```
---
format: pdf
---

```{r}
model = lm(marker ~ age , gtsummary::trial)
gtsummary::tbl_regression(model, intercept = TRUE) |> gtsummary::as_gt() 

```

```

**Comment by ddsjoberg** [comment]
If this is only happening for PDF output, then this wold be a gt bug. Can you confirm a similar table also errors with gt?

**Comment by ddsjoberg** [comment]
No worries at all @gorkang ! Please do post the issue to gt, so they are aware.

**Comment by gorkang** [comment]
Just for future reference, and while the issue is solved in gt (might be a while, as the original bug report is from 2019), this is a hacky way to edit the "(Intercept)" cell.

```
model = lm(marker ~ age , gtsummary::trial)
TABLE = gtsummary::tbl_regression(model, intercept = TRUE, show_single_row = "(Intercept)")
TABLE$table_body$label[1] = "Intercept"

TABLE |> gtsummary::as_gt()
```

**Comment by ddsjoberg** [comment]
They've definitely put a lot of effort into latex output recently. So hopefully it's high on the list of bugs to address

**Comment by kit-hcrn** [comment]
@ddsjoberg, 

I am seeing additional errors when outputting to Word. Would that be tied to gt as well?

Thanks!

**Comment by ddsjoberg** [comment]
> @ddsjoberg, 
> 
> I am seeing additional errors when outputting to Word. Would that be tied to gt as well?
> 
> Thanks!

@kit-hcrn yep! Please be sure to install the latest version of gt before you submit. When you post the reprex to the gt, please remove gtsummary-specific code, and present a minimal example.
