### ISSUE TITLE
Feature request: ability to change value labels 

### ISSUE THREAD

**Issue by mrmvergeer** [ddsjoberg/gtsummary#1537]
**Is your feature request related to a problem?**
Using MASS::contrasts (e.g., contr.sdif), the original factor names/labels are replaced with a concatenation of the variable name and indicator values of factor levels.

**Describe the solution you'd like**
An option in gtsummary and tbl_regression to specify new labels/names for factor levels. 

**Describe alternatives you've considered**
changing the names  directly in the lm-model and lmer-model.

**Additional context**
see https://stackoverflow.com/questions/76776863/how-to-change-attributes-or-value-labels-of-a-contrast for an example and discussion

**Comment by larmarange** [comment]
Term labels could be customized with term_labels argument

**Comment by mrmvergeer** [comment]
> Term labels could be customized with term_labels argument

thanks, do you mean it can be done with an existing term function, or can the term function be used for the new feature?

**Comment by ddsjoberg** [comment]
@mrmvergeer any additional arguments passed to `tbl_regression(...)` are. passed directly to `broom.helpers::tidy_plus_plus()`. That function has a `term_labels=` argument to customize what is printed. Take a look at the link below! 🕺🏼 

https://larmarange.github.io/broom.helpers/reference/tidy_plus_plus.html

**Comment by larmarange** [comment]
I may explore including support of contr.sdif in broom.helpers

**Comment by mrmvergeer** [comment]
@larmarange @ddsjoberg sounds great! In the mean time,  I'll try  term_labels.  I misdirected my search for a solution by searching for value labels :-)

**Comment by larmarange** [comment]
I guess we can close the issue for now. Let us know if you encounter another problem
