### ISSUE TITLE
Bug Report: Typo in ggsurvfit

### ISSUE THREAD

**Issue by karl-an** [ddsjoberg/gtsummary#1541]
There is a little typo in the `ggsurvfit `package. There is no issue page over there, so I will submit it here. 
I think that there is a spare y om the details section: 

Details
This function creates a ggplot figure from the 'survfit' object. To better understand how to modify the figure, review the simplified code used internally:

```
survfit2(Surv(time, status) ~ sex, data = df_lung) %>%
  tidy_survfit() %>%
  ggplot(aes(**x = time, y = estimate, y**
             min = conf.low, ymax = conf.low,
             color = strata, fill = strata)) +
  geom_step()
```

**Comment by ddsjoberg** [comment]
Thanks for the report! FYI, the ggsurvfit repo was migrated to the pharmaverse recently https://github.com/pharmaverse/ggsurvfit/issues

**Comment by ddsjoberg** [comment]
fixed
