### ISSUE TITLE
Bug/Documentation: add_stat_labels() changes categorical labels without warning.

### ISSUE THREAD

**Issue by dereksonderegger** [ddsjoberg/gtsummary#1542]
When updating tbl_summary() statistic labels for the continuous2 variables, the categorical variable labels are also modified and the fix is not obvious. My expectation is that the default labels would remain identical except for the one that were requested to change.

Adding a simple documentation update to the add_stat_labels() function would probably help people out, but ideally the default for categorical variables should be to not be modified.

    library(tidyverse)
    library(gtsummary)
    #> Warning: package 'gtsummary' was built under R version 4.3.1

    
    # Confirm what version of gtsummary we are using
    packageVersion('gtsummary')
    #> [1] '1.7.2'

    
    # Notice that by default the categorical variables just 
    # use the variable name for the label.
    tbl <- trial %>%
      dplyr::select(trt, age, grade, response) %>%
      tbl_summary(by = trt)
    tbl |> as_tibble()
    #> # A tibble: 8 × 3
    #>   `**Characteristic**` `**Drug A**, N = 98` `**Drug B**, N = 102`
    #>   <chr>                <chr>                <chr>                
    #> 1 Age                  46 (37, 59)          48 (39, 56)          
    #> 2 Unknown              7                    4                    
    #> 3 Grade                <NA>                 <NA>                 
    #> 4 I                    35 (36%)             33 (32%)             
    #> 5 II                   32 (33%)             36 (35%)             
    #> 6 III                  31 (32%)             33 (32%)             
    #> 7 Tumor Response       28 (29%)             33 (34%)             
    #> 8 Unknown              3                    4

    
    # Example 1 ----------------------------------
    # Add statistic presented to the variable label row
    # But indirectly also changes the categorical variables
    # to include a ", n (%)" without asking for it!
    add_stat_label_ex1 <-
      tbl %>%
      add_stat_label(
        # update default statistic label for continuous variables
        label = all_continuous() ~ "med. (iqr)"
      )
    add_stat_label_ex1 |> as_tibble()
    #> # A tibble: 8 × 3
    #>   `**Characteristic**`  `**Drug A**, N = 98` `**Drug B**, N = 102`
    #>   <chr>                 <chr>                <chr>                
    #> 1 Age, med. (iqr)       46 (37, 59)          48 (39, 56)          
    #> 2 Unknown               7                    4                    
    #> 3 Grade, n (%)          <NA>                 <NA>                 
    #> 4 I                     35 (36%)             33 (32%)             
    #> 5 II                    32 (33%)             36 (35%)             
    #> 6 III                   31 (32%)             33 (32%)             
    #> 7 Tumor Response, n (%) 28 (29%)             33 (34%)             
    #> 8 Unknown               3                    4

    
    # Example 1b ---------------------------------
    # To avoid the change, just set the added string 
    # to be the missing character string value. If
    # a standard NA is included, then it throws an
    # error.
    add_stat_label_ex1a <-
      tbl %>%
      add_stat_label(
        # update default statistic label for continuous variables
        label = list(
          all_continuous() ~ "med. (iqr)",
          all_categorical() ~ NA_character_
        )
      )
    add_stat_label_ex1a |> as_tibble()
    #> # A tibble: 8 × 3
    #>   `**Characteristic**` `**Drug A**, N = 98` `**Drug B**, N = 102`
    #>   <chr>                <chr>                <chr>                
    #> 1 Age, med. (iqr)      46 (37, 59)          48 (39, 56)          
    #> 2 Unknown              7                    4                    
    #> 3 Grade                <NA>                 <NA>                 
    #> 4 I                    35 (36%)             33 (32%)             
    #> 5 II                   32 (33%)             36 (35%)             
    #> 6 III                  31 (32%)             33 (32%)             
    #> 7 Tumor Response       28 (29%)             33 (34%)             
    #> 8 Unknown              3                    4

    

    
    # Example 1b ---------------------------------
    # If we pass a NULL object, then the default 
    # behavior occurs. I'll bet that somewhere this
    # is the default being used!
    add_stat_label_ex1a <-
      tbl %>%
      add_stat_label(
        # update default statistic label for continuous variables
        label = list(
          all_continuous() ~ "med. (iqr)",
          all_categorical() ~ NULL
        )
      )
    add_stat_label_ex1a |> as_tibble()
    #> # A tibble: 8 × 3
    #>   `**Characteristic**`  `**Drug A**, N = 98` `**Drug B**, N = 102`
    #>   <chr>                 <chr>                <chr>                
    #> 1 Age, med. (iqr)       46 (37, 59)          48 (39, 56)          
    #> 2 Unknown               7                    4                    
    #> 3 Grade, n (%)          <NA>                 <NA>                 
    #> 4 I                     35 (36%)             33 (32%)             
    #> 5 II                    32 (33%)             36 (35%)             
    #> 6 III                   31 (32%)             33 (32%)             
    #> 7 Tumor Response, n (%) 28 (29%)             33 (34%)             
    #> 8 Unknown               3                    4
    Created on 2023-08-08 with [reprex v2.0.2](https://reprex.tidyverse.org/)

**Comment by ddsjoberg** [comment]
The function has default behavior that changes all the stat labels for categorical, dichotomous, and continuous variables by adding the statistic label to the variable label. continuous2 variables are special in that the default is to not modify them, because the stat labels already exist.

When you change the default for continuous2, the other defaults remain in place (i.e. the "n (%)" is added to categorical variables).

Can you prepare a PR with your suggested amendment? Ideally, I would like to keep this addition as a text-only, ie no additional table in the examples section.
