### ISSUE TITLE
Feature request: add documentation for the `formula` argument of tbl_regression and tbl_uvregression

### ISSUE THREAD

**Issue by jsavinc** [ddsjoberg/gtsummary#1546]
I tried to use `survival::clogit` which uses a formula specification of the type `y ~ x + strata(id)` and couldn't work out from the documentation how to implement this in `tbl_regression` and `tbl_uvregression`; there is a `formula` argument that I couldn't find the documentation for apart from a stackoverflow answer here: https://stackoverflow.com/questions/72536717/gtsummarytbl-uvregression-for-poisson-regression

Can this be added to the documentation please?

**Comment by ddsjoberg** [comment]
Dear @jsavinc , thank you for the post.

- I don't think your issue applies to `tbl_regression()`. If I am incorrect, can you please provide more context.
- The following appears in the documentation for the `tbl_uvregression(formula)` argument illustrating how to include additional parameters/variables in a regression model. If you'd like more documentation, can you please propose examples of what you'd like to see and where?
  ![image](https://github.com/ddsjoberg/gtsummary/assets/26774684/c368ace2-b24f-4357-b2b4-ed4127e6b6f0)

**Comment by jsavinc** [comment]
Apologies, I completely missed that part in the reference for some reason!
