### ISSUE TITLE
Feature request: <Describe request>

### ISSUE THREAD

**Issue by zhangkaicr** [ddsjoberg/gtsummary#1547]
I'm an Oncology PhD Institute. Thank you very much for this package that can easily general baseline information table. However, many current clinical studies need to apply weighting or matching scoring methods to weight patients in different groups. After weighting, it is also necessary to calculate the standardized difference rate (SMD) to further evaluate the balance between groups. However, in clinical research, we often need to display the baseline information of the patients in addition to analyzing the weighted or matching SMD of the two groups of patients before and after. Unfortunately, I haven't found a package that can do this well. I believe that if this function can be completed, the application of your package in the medical field will be more common, thank you.

Below is a table of baseline information from an article in a top journal on surgery
![image](https://github.com/ddsjoberg/gtsummary/assets/74847937/42b903af-537f-49f4-a9a9-1800153dc6d6)
https://pubmed.ncbi.nlm.nih.gov/31478977/

**Comment by ddsjoberg** [comment]
Dear @zhangkaicr, Thank you for your post.

Please review the `tbl_svysummary()` and `add_difference.tbl_svysummary()` help files. This is exact table is possible with functions in the package.

You can further review this article with similar examples.
https://github.com/ddsjoberg/gtsummary/blob/50d13a3b2e9ab69436cdf328d9aeb7ce48257d8e/vignettes/articles/propensity_scores.Rmd

Best,

**Comment by zhangkaicr** [comment]
Thank you very much for your answer, I will carefully study the tutorial you gave
