### ISSUE TITLE
Feature request (tbl_summary):  Split numbers and percentages into separate columns

### ISSUE THREAD

**Issue by Polperobis** [ddsjoberg/gtsummary#1549]
[Some journals](https://www.eurosurveillance.org/for-authors#Tables%20and%20Figures) require numbers and percentages to be split into separate columns. Could this option be added to tbl_summary? The [solution proposed in Stackoverflow](https://stackoverflow.com/questions/68687297/split-frequency-and-percentage-in-tbl-summary-in-to-two-separate-columns) does not work when adding _by_ variables.

**Comment by ddsjoberg** [comment]
Thank you for the post! I am aware of this limitation...it's a tricky one to remedy in the current frame work (not to say that I won't ever get around to updating...just difficult as it's currently written).

In the meantime, here's a hacky solution

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.7.2'

# first build the basic summary table with stats combined
tbl <- trial |> 
  select(trt, response, grade) |> 
  tbl_summary(
    by = trt,
    missing = "no",
    statistic = ~"{n} {p}%"
  )

# grab the underlying column names...we'll use them later
original_stat_colnames <-tbl$table_body |> select(all_stat_cols()) |> colnames()

tbl_final <-
  tbl |> 
  # this splits each column into two columns (N and %)
  modify_table_body(
    function(table_body) {
      for (stat_col in original_stat_colnames) {
        table_body[c(paste0(stat_col, "_1"), paste0(stat_col, "_2"))] <-
          stringr::str_split_fixed(table_body[[stat_col]], pattern = " ", n = 2)
      }
      table_body
    }
  ) |> 
  # this makes all the columns visiable in the final print.
  modify_column_unhide(starts_with("stat_")) |> 
  # this hides the original columns
  modify_column_hide(all_of(original_stat_colnames)) |> 
  # if your original table has more/fewer columns, you'll need to update this line.
  # use `show_header_names()` to print the underlying column names.
  modify_header(stat_1_1 = "**N**", stat_1_2 = "**%**",
                stat_2_1 = "**N**", stat_2_2 = "**%**") |> 
  modify_spanning_header(
    starts_with("stat_1") ~ "**Drug A**", 
    starts_with("stat_2") ~ "**Drug B**"
  )
```
![image](https://github.com/ddsjoberg/gtsummary/assets/26774684/5e1f666e-f01c-4317-b28b-0c8b536e3dce)

<sup>Created on 2023-09-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Polperobis** [comment]
It works well. Thank you very much. Here's a small contribution. Spanning headers are now set automatically.
`library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.7.2'

# A function to split one "{n} {p}%" column in two columns
# limitation: Works only with a 2 columns tbl_summary object

# param@ tbl : a tbl_summary object
# return@ : a tbl_summary object

splitCol <- function(tbl){
  
  # grab the underlying column names...we'll use them later
  original_stat <- tbl$table_styling$header[grep(pattern = "stat_", 
                                                 x = tbl$table_styling$header$column ), 
                                            c(1, 5)]
  # 
  try(if (nrow(original_stat) != 2) 
    stop("This version only work with a 2 columns tbl_summary object :-(",
         call. = FALSE))
  
  tbl_final <-
    tbl |> 
    # this splits each column into two columns (N and %)
    modify_table_body(
      function(table_body) {
        for (stat_col in original_stat$column) {
          table_body[c(paste0(stat_col, "_1"), paste0(stat_col, "_2"))] <-
            stringr::str_split_fixed(table_body[[stat_col]], pattern = " ", n = 2)
        }
        table_body
      }
    ) %>% 
    # this makes all the columns visiable in the final print.
    modify_column_unhide(starts_with("stat_")) %>% 
    # this hides the original columns
    modify_column_hide(all_of(original_stat$column)) %>% 
    # if your original table has more/fewer columns, you'll need to update this line.
    # use `show_header_names()` to print the underlying column names.
    modify_header(stat_1_1 = "**N**", stat_1_2 = "**%**",
                  stat_2_1 = "**N**", stat_2_2 = "**%**") %>% 
    modify_spanning_header(
      starts_with("stat_1") ~ original_stat$label[1], 
      starts_with("stat_2") ~ original_stat$label[2]
    )
  return(tbl_final)
}


# first build the basic summary table with stats combined
tbl <- trial |> 
  select(trt, response, grade) |> 
  tbl_summary(
    by = trt,
    missing = "no",
    statistic = ~"{n} {p}%"
  )
tbl

# Split columns
tbl_final <- splitCol(tbl)
tbl_final
`
