### ISSUE TITLE
Formatting issue with decimal places for certain categories using gtsummary::tbl_custom_summary

### ISSUE THREAD

**Issue by myamortor** [ddsjoberg/gtsummary#1550]
Hello everyone,

I'm encountering an issue using the tbl_custom_summary function from the gtsummary package. I'm working with categorical variables and my aim is to display the incidence of y in percentage for each level of each variable. I use the stat_fns argument with the proportion_summary function to obtain these proportions. My goal in terms of formatting is to display only a single digit after the decimal point. For this, I'm using the digits argument with the style_percent function. 

However, a strange behavior occurs: although I try to force the display to a single digit after the decimal, one category from the x3 variable and two categories from the x7 variable display two digits after the decimal. All my variables, including the output y, are categorical.

Here's my code for illustration:

Frequency <- my_data %>%
  tbl_custom_summary(
    include = c("x1", "x2", "x3", "x4", "x5", "x6", "x7"),
    stat_fns = ~ proportion_summary("y", "1"),
    statistic = ~"{prop} ({n}/{N})",
    digits = ~ list(
      function(x) {
      style_percent(x, symbol = TRUE, digits = 1)}
                 ,0,0),
    overall_row = TRUE,
    overall_row_last = TRUE,
    label = list(x1 ~ "Label 1", x2 ~ "Label 2", x3 ~ "Label 3", x4 ~ "Label 4", x5 ~ "Label 5", x6 ~ "Label 6", x7 ~ "Label 7")
  ) %>%
  bold_labels() %>%
  modify_footnote(
    update = all_stat_cols() ~ "Output label"
  )
Has anyone encountered this behavior before or can help me understand what's happening?

Thank you in advance for your help and feedback.

**Comment by larmarange** [comment]
Hi, could you provide a minimal and reproductive example?  cf. https://reprex.tidyverse.org/

**Comment by myamortor** [comment]
``` r
rm(list = ls())
cat("\f")
```



``` r


library(readxl) # excel import
library(dplyr) # data manipulation
#> 
#> Attachement du package : 'dplyr'
#> Les objets suivants sont masqués depuis 'package:stats':
#> 
#>     filter, lag
#> Les objets suivants sont masqués depuis 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2) # data visualization
library(gtsummary)
#> #BlackLivesMatter
library(webshot2)


root <- "C:/Users/ramzi/Desktop/IVI/Projets IVI/ECHO-N/HEV risk factor/Analysis1"
org <- file.path(root, "Data")
prg <- file.path(root, "Programs")
out <- file.path(root, "Results")


# Import datasets
dataset <- read_excel(file.path(prg, "dataset.xlsx"))



# Convert it to a factor
dataset$Var8<- as.factor(dataset$Var8)
dataset$Var1 <- as.factor(dataset$Var1)
dataset$Var2 <- as.factor(dataset$Var2)
dataset$Var3<-as.factor(dataset$Var3)
dataset$Var4<- as.factor(dataset$Var4)
dataset$Var5<-as.factor(dataset$Var5)
dataset$Var6<- as.factor(dataset$Var6)
dataset$Var7<- as.factor(dataset$Var7)





dataset %>%
  tbl_custom_summary(
    include = c("Var1", "Var2", "Var3",  
                "Var4", "Var5", "Var6", "Var7"),
    # Use the new denom variable as the denominator
    stat_fns = ~ proportion_summary("Var8", "1"),
    statistic = ~"{prop} ({n}/{N})",
    digits = ~ list(
      function(x) {
        style_percent(x, symbol = TRUE, digits = 1)}
      ,0,0),
    overall_row = TRUE,
    overall_row_last = TRUE
  ) %>%
  bold_labels() %>%
  modify_footnote(
    update = all_stat_cols() ~ "Prop % (n/N)")
```

<div id="fxvuniofuv" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#fxvuniofuv table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#fxvuniofuv thead, #fxvuniofuv tbody, #fxvuniofuv tfoot, #fxvuniofuv tr, #fxvuniofuv td, #fxvuniofuv th {
  border-style: none;
}

#fxvuniofuv p {
  margin: 0;
  padding: 0;
}

#fxvuniofuv .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#fxvuniofuv .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#fxvuniofuv .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#fxvuniofuv .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#fxvuniofuv .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#fxvuniofuv .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fxvuniofuv .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#fxvuniofuv .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#fxvuniofuv .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#fxvuniofuv .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#fxvuniofuv .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#fxvuniofuv .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#fxvuniofuv .gt_spanner_row {
  border-bottom-style: hidden;
}

#fxvuniofuv .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#fxvuniofuv .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#fxvuniofuv .gt_from_md > :first-child {
  margin-top: 0;
}

#fxvuniofuv .gt_from_md > :last-child {
  margin-bottom: 0;
}

#fxvuniofuv .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#fxvuniofuv .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#fxvuniofuv .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#fxvuniofuv .gt_row_group_first td {
  border-top-width: 2px;
}

#fxvuniofuv .gt_row_group_first th {
  border-top-width: 2px;
}

#fxvuniofuv .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#fxvuniofuv .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#fxvuniofuv .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#fxvuniofuv .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fxvuniofuv .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#fxvuniofuv .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#fxvuniofuv .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#fxvuniofuv .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#fxvuniofuv .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fxvuniofuv .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#fxvuniofuv .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#fxvuniofuv .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#fxvuniofuv .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#fxvuniofuv .gt_left {
  text-align: left;
}

#fxvuniofuv .gt_center {
  text-align: center;
}

#fxvuniofuv .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#fxvuniofuv .gt_font_normal {
  font-weight: normal;
}

#fxvuniofuv .gt_font_bold {
  font-weight: bold;
}

#fxvuniofuv .gt_font_italic {
  font-style: italic;
}

#fxvuniofuv .gt_super {
  font-size: 65%;
}

#fxvuniofuv .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#fxvuniofuv .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#fxvuniofuv .gt_indent_1 {
  text-indent: 5px;
}

#fxvuniofuv .gt_indent_2 {
  text-indent: 10px;
}

#fxvuniofuv .gt_indent_3 {
  text-indent: 15px;
}

#fxvuniofuv .gt_indent_4 {
  text-indent: 20px;
}

#fxvuniofuv .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;N = 3,703&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>N = 3,703</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">Var1</td>
<td headers="stat_0" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level1.1</td>
<td headers="stat_0" class="gt_row gt_center">6.04% (11/182)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level1.2</td>
<td headers="stat_0" class="gt_row gt_center">3.34% (39/1,169)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level1.3</td>
<td headers="stat_0" class="gt_row gt_center">21.3% (248/1,164)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level1.4</td>
<td headers="stat_0" class="gt_row gt_center">36.7% (304/829)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level1.5</td>
<td headers="stat_0" class="gt_row gt_center">47.4% (170/359)</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">Var2</td>
<td headers="stat_0" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level2.1</td>
<td headers="stat_0" class="gt_row gt_center">18.6% (374/2,010)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level2.2</td>
<td headers="stat_0" class="gt_row gt_center">23.5% (398/1,693)</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">Var3</td>
<td headers="stat_0" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level3.1</td>
<td headers="stat_0" class="gt_row gt_center">20.6% (512/2,484)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level3.2</td>
<td headers="stat_0" class="gt_row gt_center">21.3% (260/1,219)</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">Var4</td>
<td headers="stat_0" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level4.1</td>
<td headers="stat_0" class="gt_row gt_center">14.2% (281/1,974)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level4.2</td>
<td headers="stat_0" class="gt_row gt_center">24.6% (52/211)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level4.3</td>
<td headers="stat_0" class="gt_row gt_center">28.9% (439/1,518)</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">Var5</td>
<td headers="stat_0" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level5.1</td>
<td headers="stat_0" class="gt_row gt_center">20.7% (664/3,203)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level5.2</td>
<td headers="stat_0" class="gt_row gt_center">21.6% (108/500)</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">Var6</td>
<td headers="stat_0" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level6.1</td>
<td headers="stat_0" class="gt_row gt_center">36.2% (77/213)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level6.2</td>
<td headers="stat_0" class="gt_row gt_center">19.9% (695/3,490)</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">Var7</td>
<td headers="stat_0" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level7.1</td>
<td headers="stat_0" class="gt_row gt_center">26.9% (59/219)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level7.2</td>
<td headers="stat_0" class="gt_row gt_center">13.6% (100/738)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level7.3</td>
<td headers="stat_0" class="gt_row gt_center">9.21% (62/673)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level7.4</td>
<td headers="stat_0" class="gt_row gt_center">37.4% (280/748)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level7.5</td>
<td headers="stat_0" class="gt_row gt_center">15.8% (52/330)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level7.6</td>
<td headers="stat_0" class="gt_row gt_center">20.1% (138/685)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Level7.7</td>
<td headers="stat_0" class="gt_row gt_center">26.1% (81/310)</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">Overall</td>
<td headers="stat_0" class="gt_row gt_center">20.8% (772/3,703)</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="2"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> Prop % (n/N)</td>
    </tr>
  </tfoot>
</table>
</div>

<sup>Created on 2023-09-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by myamortor** [comment]
You can see the issue for Var1 : Level 1.1 and 1.2 and for Var7 : Level7.1
Thank you.

**Comment by larmarange** [comment]
Just a quick question, do you have the same issue if you are using as a formatted `scales::label_percent(accuracy = 0.1, suffix = "")`?

cf. https://scales.r-lib.org/reference/label_percent.html

**Comment by ddsjoberg** [comment]
seems like this is solved. please reopen if not fully addressed!
