### ISSUE TITLE
How to set the parameters of tbl_uvregression function in different models?

### ISSUE THREAD

**Issue by zhangkaicr** [ddsjoberg/gtsummary#1551]
When using the tbl_regression function, we only need to bring various regression models directly into the function. The parameters of each function can be determined in its equation. Similar to the code below. We can directly input the result of the coxph model to the tbl_regression through the pipe character. The tbl_regression does not need to be set for a specific regression model.

`tbl_regression_ex1 <-
  coxph(Surv(ttdeath, death) ~ age + marker, trial) %>%
  tbl_regression(exponentiate = TRUE)`

In contrast, because batch calculations are required, the tbl_uvregression function cannot directly accept models. We need to set the different parameters of each model inside the function, such as the following code.

`Ime4_uv<-
  tbl_uvregression(
    mtcars %>%
      select("am","gear","hp","cyl"),
    method = lme4::glmer,
    y = am,
    formula = "{y} ~ {x} + (1|gear)",
    method.args = list(family = binomial),
    hide_n = TRUE,
    pvalue_fun = function(x) style_pvalue(x, digits = 2)#p值保留2位小数
  )`

Because the parameter setting of each model is different, how to set the parameter tutorial is not fully explained, whether it is possible to add this part of the description or adjust the function to have a unified input standard.
For example, I now need to perform batch calculations on competitive risk models, but I don't know how to set parameters.

Looking forward to your answer, thank you very much

**Comment by ddsjoberg** [comment]
@zhangkaicr thank you for the post!

Apologies, but I am not sure what you're asking to be further documented. In your example, you mention a competing risks regression model. Can you provide an example of a single model you create, and perhaps I can show you how to create that in `tbl_uvregression()`.

**Comment by ddsjoberg** [comment]
I am going to go ahead and close this. please feel free to re-open when you are able to respond.
