### ISSUE TITLE
multinom_pivot_wider adapted to other package than nnet ? 

### ISSUE THREAD

**Issue by Spring75xx** [ddsjoberg/gtsummary#1552]
Hello ! 

We used the svy_vglm() function (svyVGAM package) to use a weighted multinomial logistic regression and then gave this to tbl_regression to have a nice table. However, the table being printed in long format, we used the function multinom_pivot_wider() to have the wide version. However, it seems that the function was developped according to the nnet package as the following error appeared : "`x=` must be class 'tbl_regression' summary of a `nnet::multinom()` model."

Is it possible to have the multinom_pivot_wider function adapted to other packages than nnet (like the svyVGAM package ?) ? 

Thank you very much for your help !

```r
# insert reprex here
```

**Comment by ddsjoberg** [comment]
I think I may be missing something...that function is not in the gtsummary package. You can just delete the line that checks for the nnet class?
https://gist.github.com/ddsjoberg/a55afa74ac58e1f895862fcabab62406
