### ISSUE TITLE
Error using tbl_svysummary function after calculating weight using test data of weightit package

### ISSUE THREAD

**Issue by zhangkaicr** [ddsjoberg/gtsummary#1553]
I currently use the test data from the weightit official website to calculate the weight of each observation. I want to use the tbl function to return the weighted table and calculate the SMD, but the following error is reported.

![image](https://github.com/ddsjoberg/gtsummary/assets/74847937/c6fa877e-1cfe-43c4-a345-4952e31efa9a)

The official website address is as follows
[https://ngreifer.github.io/WeightIt/articles/estimating-effects.html](url)

The test code is as follows
`
glimpse(d)
#计算权重
W <- weightit(A ~ X1 + X2 + X3 + X4 + X5 + 
                X6 + X7 + X8 + X9, data = d,
              method = "glm", estimand = "ATE")
W

#将计算的权重带入数据
d$weights <- W$weights

tbl_weight <-
  survey::svydesign(~1, data = d, weights = ~ weights) %>%
  tbl_svysummary(by = A)
`

![image](https://github.com/ddsjoberg/gtsummary/assets/74847937/fb59cd47-6890-4995-9d1e-07d3094a25c3)

Test data generation code
`#Generating data similar to Austin (2009) for demonstrating treatment effect estimation
gen_X <- function(n) {
  X <- matrix(rnorm(9 * n), nrow = n, ncol = 9)
  X[,5] <- as.numeric(X[,5] < .5)
  X
}

gen_Ac <- function(X) {
  LP_A <- -1.2 + log(2)*X[,1] - log(1.5)*X[,2] + log(2)*X[,4] - log(2.4)*X[,5] + log(2)*X[,7] - log(1.5)*X[,8]
  LP_A + rlogis(nrow(X))
}

#~20% treated
gen_A <- function(Ac) {
  1 * (Ac > 0)
}

gen_Am <- function(A) {
  factor(ifelse(A == 1, "T", sample(c("C1", "C2"), length(A), TRUE)))
}

# Continuous outcome
gen_Y_C <- function(A, X) {
  2*A + 2*X[,1] + 2*X[,2] + 2*X[,3] + 1*X[,4] + 2*X[,5] + 1*X[,6] + rnorm(length(A), 0, 5)
}
#Conditional:
#  MD: 2
#Marginal:
#  MD: 2

# Binary outcome
gen_Y_B <- function(A, X) {
  LP_B <- -2 + log(2.4)*A + log(2)*X[,1] + log(2)*X[,2] + log(2)*X[,3] + log(1.5)*X[,4] + log(2.4)*X[,5] + log(1.5)*X[,6]
  P_B <- plogis(LP_B)
  rbinom(length(A), 1, P_B)
}
#Conditional:
#  OR:   2.4
#  logOR: .875
#Marginal:
#  RD:    .144
#  RR:   1.54
#  logRR: .433
#  OR:   1.92
#  logOR  .655

# Survival outcome
gen_Y_S <- function(A, X) {
  LP_S <- -2 + log(2.4)*A + log(2)*X[,1] + log(2)*X[,2] + log(2)*X[,3] + log(1.5)*X[,4] + log(2.4)*X[,5] + log(1.5)*X[,6]
  sqrt(-log(runif(length(A)))*2e4*exp(-LP_S))
}
#Conditional:
#  HR:   2.4
#  logHR: .875
#Marginal:
#  HR:   1.57
#  logHR: .452

set.seed(19599)

n <- 2000
X <- gen_X(n)
Ac <- gen_Ac(X)
A <- gen_A(Ac)
Am <- gen_Am(A)

Y_C <- gen_Y_C(A, X)
Y_B <- gen_Y_B(A, X)
Y_S <- gen_Y_S(A, X)

d <- data.frame(A, Am, Ac, X, Y_C, Y_B, Y_S)`

**Comment by ddsjoberg** [comment]
Dear @zhangkaicr , Can you please update your post using a reprex. The reprex package website outlines precisely how to implement and report the results. https://reprex.tidyverse.org/

Please only include minimal code to illustrate your issue, and please use the output from reprex as it is returned so the results format properly.

**Comment by ddsjoberg** [comment]
Please feel free to reopen when you're ready
