### ISSUE TITLE
Feature request: Convert `tbl_split` object to `gt_group`

### ISSUE THREAD

**Issue by paulduf** [ddsjoberg/gtsummary#1554]
Do not use this form to ask a question, or ask for assistance. Instead, ask on <https://stackoverflow.com/> using the gtsummary tag.
Questions about a function's use will be closed without a response.

**Is your feature request related to a problem? Please describe.**

I cannot find a clear and documented way to save a `tbl_split` object into multiple files.
Plus, there exists a `gt_group` object in the `gt` API that seems to do the same job. [See this doc.](https://gt.rstudio.com/reference/gt_group.html)

**Describe the solution you'd like**

Is it possible to convert a `tbl_split` to a `gt_group` object ? Or could the `tbl_split` function directly output a `gt_group` object ?

**Comment by ddsjoberg** [comment]
After you split a gtsummary table, it's just a list of gtsummary tables. you can convert each of these tables to gt with `as_gt()`.

**Comment by paulduf** [comment]
OK, then the feature I probably want is that calling `as_gt` with a `tbl_split` object should return a `gt_group` object because they represent the same data to me. Right now, I'm able to do this with

```r
library(gtsummary)

tbls <- mtcars %>%
  tbl_summary() %>%
  tbl_split(variables="wt")

tbls_gt <- gt::gt_group(.list = purrr::map(tbls, function(tbl) as_gt(tbl)))
```

The last line could be a way to extend `gtsummary::as_gt` to work with `tbl_split`, what do you think ? I can submit a PR if needed.

I think it's nice to interface with `gt` in this way because then we can use export functions of `gt` for groups of tables.

**Comment by ddsjoberg** [comment]
That is an interesting proposal @paulduf ! Thanks!

I am considering some larger structural changes and I am reluctant to add this type of functionality at the moment. Furthermore, I've chatted with the gt author about that function in particular and there may be changes to it in the future (not sure if they would be breaking or not), so I think it's best for me to avoid it for the moment.
