### ISSUE TITLE
Feature request: `add_overall` for `tbl_strata`

### ISSUE THREAD

**Issue by lamberp6** [ddsjoberg/gtsummary#1556]
Is it possible/feasible for `add_overall` to support `tbl_strata` objects?  

Currently:

```
tbl_strata_ex1 <-
  trial %>%
  select(age, grade, stage, trt) %>%
  mutate(grade = paste("Grade", grade)) %>%
  tbl_strata(
    strata = grade,
    .tbl_fun =
      ~ .x %>%
      tbl_summary(by = trt, missing = "no") %>%
      add_n(),
    .header = "**{strata}**, N = {n}"
  ) %>% add_overall()
```
returns:

```
Error in UseMethod("add_overall") : 
  no applicable method for 'add_overall' applied to an object of class "c('tbl_strata', 'tbl_merge', 'gtsummary')"

```

**Comment by ddsjoberg** [comment]
Thank you for the post @lamberp6 !

Unfortunately, once a table has been processed with `tbl_merge()`, there is lost context and adding a robust `add_overall()` method would not be possible to consistently implement. `tbl_merge()` is a general utility that can be performed on any kind of gtsummary table, and even gtsummary tables of different types/classes.

In your example, I think you'll create a new "overall" table, then merge it into stratified table.

**Comment by lamberp6** [comment]
Thanks @ddsjoberg - that works!
