### ISSUE TITLE
Paired t-tests do not respect group levels

### ISSUE THREAD

**Issue by JeremyPasco** [ddsjoberg/gtsummary#1557]
Hi,
I've encountered some discrepancies when reporting size effect of paired t-tests.

If I summarise a continuous variable `measure` at times `T0` and `T1` and compare them with a t-test I get a mean difference which sign depends on `time` levels (here T1-T0), which is consistent with columns order.

```r
library(tidyverse)
library(gtsummary)

set.seed(1234)

x <- tibble(
  id = c(1:50, 1:50),
  time = factor(
    c(rep('T0', 50), rep('T1', 50)),
    c("T1", "T0")
  ),
  measure = runif(100)
)

x %>% 
  tbl_summary(
    by = time,
    include = measure
  ) %>% 
  add_difference()
```

![image](https://github.com/ddsjoberg/gtsummary/assets/32913603/4a000a5a-baaf-41b1-9542-44b531bf6c3e)

But if I do the same with a `paired.t.test`, the comparison is done in the reverse side (T0-T1):

```r
x %>% 
  tbl_summary(
    by = time,
    include = measure
  ) %>% 
  add_difference(
    group = id,
    test = list(
      all_continuous() ~ "paired.t.test"
    )
  )
```

![image](https://github.com/ddsjoberg/gtsummary/assets/32913603/6136b69a-68fe-4447-b46c-98b60172794f)

Looks like with a paired t-test, size effect depends on group occurence order rather than its levels:
```r
x %>% 
  arrange(time) %>% # fix
  tbl_summary(
    by = time,
    include = measure
  ) %>% 
  add_difference(
    group = id,
    test = list(
      all_continuous() ~ "paired.t.test"
    )
  )
```

![image](https://github.com/ddsjoberg/gtsummary/assets/32913603/e84de6c8-736e-4aab-a56a-bddda8257fb6)

**Possible solution**: reapply group levels in gtsummary custom paired.t.test? (somewhere in `tidyr::pivot_wider(id_cols = group, ...); t.test(by_1, by_2, paired = TRUE, conf.level = 0.95, ...)`)

**Comment by ddsjoberg** [comment]
Thanks for the post @JeremyPasco ! I'll take a look!

**Comment by ddsjoberg** [comment]
@JeremyPasco thank you again for reporting the bug! Much appreciated!

The main branch has the fix now, please check it out when you have a moment.

**Comment by MendelYev** [comment]
Thanks for the fix @ddsjoberg, it works perfectly now!
