### ISSUE TITLE
tbl_svysummary error: "sum not meaningful for factors" when leaving the weights in the dataset

### ISSUE THREAD

**Issue by zheer-kejlberg** [ddsjoberg/gtsummary#1558]
Took me a while to find out why the following kept throwing an error - I fixed this by using 'include' to leave out "weights" from the table. Could this be done automatically for the variable that is supplied as weight to the svydesign-object?

```
library(dplyr)
library(gtsummary)
library(survey)
library(WeightIt)

n <- 100000
age <- rnorm(n,60,10)
sex <- rbinom(n,1,0.5)
X <- rbinom(n,1,0.4) * rnorm(n,30,5) + sex * rnorm(n,40,5) + age
X <- round(pnorm(X, mean(X), sd(X)))
Y <- 30*X + age + 40*sex
df <- data.frame(age = age, sex = sex, X = X, Y = Y)
df$weights <- weightit(data = df, formula = X ~ age + sex)$weights

svy_tbl <- svydesign(~1, data = df, weights = ~weights) %>%
  tbl_svysummary(by = X)

```

Error message:
```

Error in `mutate()`:
ℹ In argument: `df_stats = pmap(...)`.
Caused by error in `Summary.factor()`:
! ‘sum’ not meaningful for factors
Run `rlang::last_trace()` to see where the error occurred.
```

Fix:

```
svy_tbl <- svydesign(~1, data = df, weights = ~weights) %>%
  tbl_svysummary(by = X,include=c(X, Y, age, sex))
```

**Comment by larmarange** [comment]
After exploring it, the issue is not coming from `gtsummary` but from `survey`. The `survey::svytable()` is failing if we ask it to summarize a variable named **weights**. If you change the variable name, there is no problem.

``` r
library(dplyr)
#> 
#> Attachement du package : 'dplyr'
#> Les objets suivants sont masqués depuis 'package:stats':
#> 
#>     filter, lag
#> Les objets suivants sont masqués depuis 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(gtsummary)
library(survey)
#> Le chargement a nécessité le package : grid
#> Le chargement a nécessité le package : Matrix
#> Le chargement a nécessité le package : survival
#> 
#> Attachement du package : 'survey'
#> L'objet suivant est masqué depuis 'package:graphics':
#> 
#>     dotchart
library(WeightIt)

n <- 100000
age <- rnorm(n,60,10)
sex <- rbinom(n,1,0.5)
X <- rbinom(n,1,0.4) * rnorm(n,30,5) + sex * rnorm(n,40,5) + age
X <- round(pnorm(X, mean(X), sd(X)))
Y <- 30*X + age + 40*sex
df <- data.frame(age = age, sex = sex, X = X, Y = Y)
df$w <- weightit(data = df, formula = X ~ age + sex)$weights

svy_tbl <- svydesign(~1, data = df, weights = ~w) %>%
  tbl_svysummary(by = X)
svy_tbl |> 
  as_kable()
```

| **Characteristic** | **0**, N = 81,261 | **1**, N = 93,096 |
|:-------------------|:-----------------:|:-----------------:|
| age                |    57 (51, 64)    |    62 (57, 67)    |
| sex                |   28,743 (35%)    |   50,170 (54%)    |
| Y                  |    70 (57, 90)    |   115 (94, 131)   |
| w                  |  1.5 (1.1, 4.0)   |  1.6 (1.1, 6.1)   |

<sup>Created on 2023-10-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
On `survey` side, it could be worth to mention the issue to their team, at lest to mention in the documentation that **weights** is a reserved named. (even if this variable is something else than the survey weights).

On `gtsummary` side, we could eventually add a check on the names in `include` and add a specific error message. @ddsjoberg  What do you think?

**Comment by ddsjoberg** [comment]
Before we add a message in gtsummary, @zheer-kejlberg can you file a bug report with `survey` package? Hopefully, they'll just update on their end and we won't need to keep track of this message. Sound good @larmarange ?

**Comment by larmarange** [comment]
Good to me

**Comment by zheer-kejlberg** [comment]
Sounds great! Thanks for the quick response. I’ll file a bug with survey and keep you posted once they respond.

**Comment by ddsjoberg** [comment]
Great, thank you! Please update us on the outcome! Even if they don't wish to make the update in survey, i hope more informative messaging could be added.
