### ISSUE TITLE
tbl_summary seems not working with filtered data frames or tibbles. 

### ISSUE THREAD

**Issue by s-j-choi** [ddsjoberg/gtsummary#1561]
I wanted to make a summary table after filtering out some rows. However, tbl_summary still shows the filtered-out rows in the summary table.  

```r
table0 <-
  df.wide.paired.filtered %>% 
  filter(Disease_subtype == 1 | Disease_subtype == 2 | Disease_subtype == 3) %>%
  tbl_summary(include = c(Sex, Age, Disease_subtype, EDSS, MS_Tx, T25FW, HPT, domHPT, nondomHPT, LCVA, SDMT,
                          PASAT),
              by = Disease_subtype) %>%
  add_p() %>% 
  bold_labels()
table0
```

The summary table looks like the screen capture below:
![Rplot](https://github.com/ddsjoberg/gtsummary/assets/8732330/b7cfe620-8a00-4e98-8356-a02d2caa7bd2)

**Comment by ddsjoberg** [comment]
Dear @s-j-choi ,

Please, do not use this form to ask a question, or ask for assistance. Instead, ask on <https://stackoverflow.com/> using the gtsummary tag.

INCLUDE a *minimal* reproducible example (AKA a reprex) in your stackoverflow post. If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>. It'll take minutes to master creating a reprex.
