### ISSUE TITLE
Landmark analysis in tbl_regression

### ISSUE THREAD

**Issue by hichew22** [ddsjoberg/gtsummary#1564]
Hello,

I was wondering if there is a way to directly integrate landmark analysis into tbl_uvregression( ). For example, I understand you can conduct landmark analysis with a single covariate as follows:
```
coxph(
  Surv(time, status) ~ sex,
  subset = time >= 90,
  data = colon
) %>% 
  tbl_regression(exp = TRUE)
```

And pipe multiple covariates into tbl_uvregression to generate a table of univariate models as follows:
```
colon %>%
  select(time, status, sex, nodes, adhere) %>%
  tbl_uvregression(
    method = coxph,
    y = Surv(time, status),
    exponentiate = TRUE,
    pvalue_fun = ~ style_pvalue(.x, digits = 2)
  ) %>%
  add_nevent() %>%
  bold_p() %>%
  bold_labels()
```

Is there a way to conduct multiple landmark analyses using multiple covariates at once, for example, by introducing the subset within tbl_uvregression() in the second example?

**Comment by ddsjoberg** [comment]
HI @hichew22 ! Thanks for the post!

I am happy to answer questions. Please post your question to stackoverflow.com. If you include the gtsummary tag, I'll be notified of your post. Github is for bug reports and sometimes feature requests.

Your post should include a minimal reproducible example, aka a minimal reprex. A reprex includes both data and code I can run on my machine. If needed, include a mock-up of what you want your results to look like. Please also include more details in your stackoverflow post. I am not sure what you mean by multiple landmark analyses...it seems you can just subset your data before passing it to `tbl_uvregression()`.

Take just a few minutes to review reprex.tidyverse.org for detailed instructions on how to create a reprex.
