### ISSUE TITLE
tbl_regression does not work on the output of a replicate svyglm model.

### ISSUE THREAD

**Issue by FrancoisGhesquiere** [ddsjoberg/gtsummary#1571]
Hello, 

I have noticed that the function tbl_regression does not work on a the output of svyglm model with replicate weights (although it works fine with a ‘classical’ svyglm model). 
I got the message : « Error in tcm * w : non-conformable arrays ».
It would be great if we could use  tbl_regression on complex survey with replicates regressions models. 

Thanks in advance, 

François Ghesquière

**Comment by ddsjoberg** [comment]
Dear @FrancoisGhesquiere , 

Thank you for the post. Here are the next steps:
1. Prepare a small reproducible example (including both data and code we can run on our machines).
2. You'll want to make the support request on https://github.com/larmarange/broom.helpers/issues

I am going to close this issue, and i'll see you on the other repo!

**Comment by FrancoisGhesquiere** [comment]
thanks
