### ISSUE TITLE
Warning when using weights < 1 in tbl_svysummary

### ISSUE THREAD

**Issue by LucyMcGowan** [ddsjoberg/gtsummary#1572]
When we have weights that are < 1 (which is common in causal inference, i.e. ATT weights if the treatment group is smaller than the control group, etc), we are seeing a warning when using `tbl_svysummary` -- it seems like this is propagating from the survey package, but I can't reproduce it from the package itself, i.e. when I run `svymeans` I do not see it. See below for a reprex, thank you!

``` r
library(survey)
#> Loading required package: grid
#> Loading required package: Matrix
#> Loading required package: survival
#> 
#> Attaching package: 'survey'
#> The following object is masked from 'package:graphics':
#> 
#>     dotchart
library(gtsummary)
d <- mtcars[, 1, drop = FALSE]
d$weight <- runif(nrow(mtcars), 0, 0.5)
des <- svydesign(~1, weights = ~weight, data = d)
svymean(~mpg, des)
#>       mean     SE
#> mpg 19.803 1.5083
library(gtsummary)
tbl_svysummary(des, include = mpg)
#> Warning: There was 1 warning in `mutate()`.
#> ℹ In argument: `df_stats = pmap(...)`.
#> Caused by warning in `svymean.survey.design2()`:
#> ! Sample size greater than population size: are weights correctly scaled?
```
<sup>Created on 2023-11-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Thank you @LucyMcGowan for the report and the simple reprex (much appreciated!).

The warning appears from using the `deff=TRUE` argument.

``` r
library(survey, warn.conflicts = FALSE)
#> Loading required package: grid
#> Loading required package: Matrix
#> Loading required package: survival

d <- mtcars[, 1, drop = FALSE]
d$weight <- runif(nrow(mtcars), 0, 0.5)
des <- svydesign(~1, weights = ~weight, data = d)
svymean(~mpg, des, na.rm = TRUE, deff = TRUE)
#> Warning in svymean.survey.design2(~mpg, des, na.rm = TRUE, deff = TRUE): Sample
#> size greater than population size: are weights correctly scaled?
#>        mean      SE DEff
#> mpg 20.3106  1.1444   NA
```

<sup>Created on 2023-11-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

@larmarange the line in question is coming from here:
https://github.com/ddsjoberg/gtsummary/blob/30ef7175b9cc935ddcfd41f7c9c2418f3ee52cd8/R/tbl_svysummary.R#L361

I don't know why/if this is needed. Can you chime in, please?

**Comment by LucyMcGowan** [comment]
Ah! I was trying to fiddle with it and somehow missed that option — estimating the Design Effect definitely doesn’t make sense from a propensity score weighting perspective but not sure how that is used internally

**Comment by ddsjoberg** [comment]
@LucyMcGowan The design effect is only used to estimate the proportion of missing data and not in the primary mean calculation. @larmarange can comment on these differences with more authority than I can!

As an aside: we're planning a rather large refactor, and if there are pain points or suggestions, please feel free to voice them here!

**Comment by larmarange** [comment]
Hi, following #1486, we have added design effects to the list of statistics available in `tbl_svysummary()`.

Due to the design of the functions, inherited from `tbl_summary()`, `summarize_continuous_survey()` computes deff only on demand, while `summarize_categorical_survey()` always computes all the possible statistics.

To be noted, even for a continuous variable, `summarize_categorical_survey()` is called to calculate the number of observations. 

https://github.com/ddsjoberg/gtsummary/blob/30ef7175b9cc935ddcfd41f7c9c2418f3ee52cd8/R/tbl_svysummary.R#L650

We probably need to update `summarize_categorical_survey()` to compute deff only when required.

**Comment by ddsjoberg** [comment]
Thanks @larmarange !

FYI @LucyMcGowan in the next version of the package, the messaging will be more clear where any warnings come from, for example it will say that this warning comes from estimating the statistic to measure the proportion of missing data.
