### ISSUE TITLE
Bug Report: Contingency Tables Not Working When The Data Variable Has Only 'yes' or 'no' Levels

### ISSUE THREAD

**Issue by rawand-hanna** [ddsjoberg/gtsummary#1579]
This does not work
survey1 %>% tbl_summary(by = 'sex', include = 'still_have_contract_with_employer')

This works
survey1 %>% mutate(still_have_contract_with_employer = case_when(still_have_contract_with_employer == 'yes' ~ 'Yes', 
                                                                 still_have_contract_with_employer == 'no' ~ 'No ',
                                                                 TRUE ~ still_have_contract_with_employer)) %>% tbl_summary(by = 'sex')
---

```r
# insert reprex here
```

**Comment by rawand-hanna** [comment]
Notice that I have added a space to the categorical level 'No' >> 'No ' 

If the levels are only 'yes' 'no' it won't work

**Comment by ddsjoberg** [comment]
Thank you for your post. I am not sure what the bug you're reporting is. Please update your post with a reproducible example, aka a reprex. A reprex includes both data and code I can run on my machine that replicates your finding. Make the example as short as possible: the minimal amount of code to reproduce your finding and nothing more.

Take just a few minutes to review [reprex.tidyverse.org](https://reprex.tidyverse.org/) for detailed instructions on how to create a reprex.

I am going to go ahead and close this issue for now. But please do re-open the issue after you've added your reproducible example. Also, be sure to download the most recent version of the package.

**Comment by plbaldoni** [comment]
Maybe @rawand-hanna is referring to the following?
```
test_data <- tibble(yes.no = c('Yes','Yes','Yes','No','No'))
test_data$yes.no.with.space <- paste(test_data$yes.no,' ')
test_data |> tbl_summary()
```
Is it expected for `yes.no.with.space` to be broken down into the two categories while `yes.no` is not?
