### ISSUE TITLE
bold_labels, italicize_levels  cannot be used to make specific labels bold or italic.

### ISSUE THREAD

**Issue by zawkzaw** [ddsjoberg/gtsummary#1582]
Hello!
bold_labels, italicize_labels  in tbl_summary function make all labels bold or italic. and these are very useful features.
    
However,  bold_labels, italicize_labels  cannot be used to make specific labels bold or italic. We need sometime these features.

May I suggest that bold_labels, italicize_labels  are made to include a feature for specifying some, not all, labels.

Best wishes

Ko Ko Zaw

**Comment by ddsjoberg** [comment]
Hello @zawkzaw , thank you for the post.

There are just wrappers for `modify_table_styling()`, which you can use to bold/italicize any cells you'd like. https://www.danieldsjoberg.com/gtsummary/reference/modify_table_styling.html

For example, the `bold_labels()` function is essentially:

```r
  # bold labels ----------------------------------------------------------------
  x <-
    modify_table_styling(
      x,
      columns = "label",
      rows = .data$row_type == "label",
      text_format = "bold"
    )
```

Hope that helps!

**Comment by zawkzaw** [comment]
Hello
Thank you a lot.
It really help.
