### ISSUE TITLE
Bug Report: as_kable_extra will auto-escape "<" to "&lt;" in output p-values if bold_p() was applied.

### ISSUE THREAD

**Issue by violet-nova** [ddsjoberg/gtsummary#1587]
I'm unsure if this is best classified as a "bug" or "feature request"; happy to change it if "bug" is incorrect. 

When calling as_kable_extra(), if you have applied `bold_p()`, the output will convert "<" to "&lt"

```r
### Reproduce Issue: 
library(gtsummary)
mtcars %>% gtsummary::tbl_summary(by = vs) %>% add_p() %>% bold_p() %>% as_kable_extra()

### Does not happen if you don't bold:
mtcars %>% gtsummary::tbl_summary(by = vs) %>% add_p() %>% as_kable_extra()

### Escaped characters in non-bold, such as ">" also don't have the same issue:
ToothGrowth %>% gtsummary::tbl_summary(by = supp) %>% add_p() %>% bold_p() %>% as_kable_extra()

### If we coerce to bold,  ">" runs into the same issue: 
 ToothGrowth %>% gtsummary::tbl_summary(by = supp) %>% add_p() %>% bold_p(t = 1) %>% as_kable_extra()
```

Current workaround I'm using is to set `escape = TRUE`:

```r
mtcars %>% gtsummary::tbl_summary(by = vs) %>% add_p() %>% bold_p() %>% as_kable_extra(escape = True)
```

But I'm assuming this behavior is not intended nor desired. Thank you for any time you can dedicate to this.

**Comment by ddsjoberg** [comment]
Hi @violet-nova , thanks for the post! Do you know how to solve this in a pretty straight-forward way? Perhaps the simplest is to add `escape=TRUE`? To be up front, I don't know if/when I'll have the bandwidth to delve into the hellish landscape of latex and escaping 😬

**Comment by ddsjoberg** [comment]
For now, I will leave it to the users to utilize the solution to suggested.
