### ISSUE TITLE
get error if add_overall() if label on `by` variable is defined

### ISSUE THREAD

**Issue by CorradoLanera** [ddsjoberg/gtsummary#1588]
If labels are set on the variable used in `by`, that standard table is created as expected; you can `add_p` and `add_n`, but you cannot `add_overall`.

That could be a "feature" and not a bug, but in that case, can `tbl_summary` throws an error if the label is set on the `by` variable directly?

```r
library(gtsummary)

trial |> 
  tbl_summary(
    by = trt,
    label = list(trt ~ "Treatment")
  ) |> 
  add_overall()
#> Error:
#> ! Error in `label=` argument input. Select from 'age', 'marker',
#>   'stage', 'grade', 'response', 'death', 'ttdeath'
#> Backtrace:
#>      ▆
#>   1. ├─gtsummary::add_overall(...)
#>   2. └─gtsummary:::add_overall.tbl_summary(...)
#>   3.   └─gtsummary:::add_overall_generic(...)
#>   4.     ├─base::do.call(class(x)[1], x_copy$inputs)
#>   5.     └─gtsummary::tbl_summary(...)
#>   6.       └─gtsummary:::generate_metadata(...)
#>   7.         └─broom.helpers::.formula_list_to_named_list(...)
#>   8.           ├─... %>% list()
#>   9.           └─broom.helpers:::.single_formula_to_list(...)
#>  10.             └─broom.helpers::.select_to_varnames(...)
#>  11.               └─base::tryCatch(...)
#>  12.                 └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>  13.                   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  14.                     └─value[[3L]](cond)
#>  15.                       └─cli::cli_abort(error_msg, call = NULL)
#>  16.                         └─rlang::abort(...)
```

<sup>Created on 2024-01-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Thank you @CorradoLanera for the post!

FYI, I probably won't address this for a couple of months, since there are other items that are taking priority. But I do truly appreciate you posting this, and I will get to it.

In the meantime, you can use `list(trt = "Treatment")` instead. Note, however, that this line is not being used/not changing anything in the table because the labels supplied here change the labels of variables in the body of the table and not the by variable.

**Comment by ddsjoberg** [comment]
Dear @CorradoLanera , thanks again for the post.

l've updated the internals to select among the variables included in the table. In your case, you'll still get an error, but you'll see it earlier in the call to `tbl_summary()`. Note that using syntax like `trt ~ "Treatment"` triggers tidyselect, and tidyselect will not find the trt variable among the variable reported in the table. Simple named lists will simple be subset to the names that match the variables in the table.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.9.9.9000'
```

``` r

trial |> 
  tbl_summary(
    by = trt,
    label = list(trt ~ "Treatment")
  )
#> Error in `tbl_summary()`:
#> ! Error processing `label` argument.
#> ! Can't select columns that don't exist. ✖ Column `trt` doesn't exist.
#> ℹ Select among columns "age", "marker", "stage", "grade", "response", "death",
#>   and "ttdeath"
```

<sup>Created on 2024-06-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
