### ISSUE TITLE
Bug Report: <number of digits for p-value different for table and inline presentation>

### ISSUE THREAD

**Issue by mrmvergeer** [ddsjoberg/gtsummary#1589]
---
The following code show inconsistent presentation of the number of digits for the p-values.  
The cyl p-value should show three digits but it only shows two.
When commenting out the pvalue_fun then the p-value in the table also shows two instead of three digits
In another document - my real analysis - the number of digits even changes to one instead of three digits. 
The patterns seems to be related to p-values higher than 0.05. 

```{r}
library(pacman)
p_load(tidyverse, gtsummary)
model <- lm(mpg ~ cyl + hp + gear, data = mtcars)

tab1 <- model  %>%
  tbl_regression(conf.int = F,
  estimate_fun= purrr::partial(style_number, digits = 3),
  pvalue_fun = ~ style_pvalue(.x, digits = 3))
tab1
```
# the following lines are the inline presentations of estimates and p-values in an Rmd file

text1 `r inline_text(tab1, variable = cyl, pattern = "(b = {estimate}, {p.value})")` text2

text1 `r inline_text(tab1, variable = hp, pattern = "(b = {estimate}, {p.value})")` text2

text1 `r inline_text(tab1, variable = gear, pattern = "(b = {estimate}, {p.value})")` text2

**Comment by mrmvergeer** [comment]
Thanks @ddsjoberg !, it's not a bug, it's a feature. It now seems logical to me the function is not inherited. Again thanks

**Comment by mrmvergeer** [comment]
Sorry, but there still seems something off. In my code, having added the **pvalue_fun** code, the number of digits is now correct, but inline now doesn't prepend p< or p=. See example below.


```{r}
library(pacman)
p_load(tidyverse, gtsummary)
model <- lm(mpg ~ cyl + hp + gear, data = mtcars)
```

```{r}
tab1 <- model  %>%
  tbl_regression(conf.int = F,
  estimate_fun= purrr::partial(style_number, digits = 3),
  pvalue_fun = ~ style_pvalue(.x, digits = 3)) 
tab1
```

text1 `r inline_text(tab1, variable = cyl, pattern = "(b = {estimate}, {p.value})", pvalue_fun = ~ style_pvalue(.x, digits = 3))` text2

**Comment by ddsjoberg** [comment]
I would first review the `style_pvalue()` help file for instructions on how to format the pvalue the way you want it. If there are further questions, I would post the question on stackoverflow.com using the gtsummary tag.
