### ISSUE TITLE
support for QLMM (mixed quantile regressions) needed

### ISSUE THREAD

**Issue by yuryzablotski** [ddsjoberg/gtsummary#1591]
tbl_regression does not work with QLMM package. It works with emmeans already, thus, I think, the issue is minor. 

library(tidyverse)
library(lqmm)
theme_set(theme_test())

data(Orthodont) 
Orthodont <- Orthodont %>% 
  mutate(age = factor(age))

rim <- lqmm(distance ~ age, random = ~ 1, 
            group = Subject,
            tau = 0.75, data = Orthodont)

library(emmeans)
bla <- emmeans(rim, pairwise ~ age, tau = 0.75)
bla
plot(bla$emmeans)
plot(bla$contrasts)
emmip(rim, ~ age,  CIs = T, tau = 0.75, weights = "prop")

library(gtsummary)
tbl_regression(rim, add_pairwise_contrasts = T)

**Comment by ddsjoberg** [comment]
thanks for the post @yuryzablotski !

Can you post the minimal reproducible example along with the expected output to the broom.helpers repo? You can replace the `tbl_regression()` call with `broom.helpers::tidy_plus_plus()`

Thanks!

**Comment by larmarange** [comment]
Support of such model will be complicated:

- no `tidy()` method although `tidy_parameters()` seems to work but results are not consistent with the `summary()` method for this model
- no `terms()`, `model.frame()` or `model.matrix()` for these models
- unclear about the maintenance of the package: last version published in April 2022 and no GitHub repository

Support of such model would require some evolutions of the lqmm package

**Comment by larmarange** [comment]
For information, lqmm models are not officially supported by emmeans according to https://cran.r-project.org/web/packages/emmeans/vignettes/models.html

**Comment by yuryzablotski** [comment]
So, when Joseph is already involved in this issue, I better don't go to broom.helpers with a tidy_plus_plus example?

And, Joseph, the link you provided is outdated. It also doesnt really say emmeans supports usual (not-mixed) quantile regression, but I have worked with the author of emmeans on QR and it does very well support the QR. Here is the proof: https://yuzar-blog.netlify.app/posts/2024-01-04-qr2/

The example above also shows that emmeans does support the lqmm with, e.g. quantile = 0.75. That is why I thought that gtsummary and broom.helpers could work too.

**Comment by larmarange** [comment]
Thanks @yuryzablotski 

In all cases, the first thing would be to have a proper tidier for such model. The best would be for it to be developed directly in the package.

With such a tidier, we could add basic support (i.e. just returning the tidy tibble of the coefficients). For other functionalities included in `broom.helpers` (identification of variables, reference rows, etc.) we would need terms(), model.matrix() and model.frame() added to the original package.

Best regards

**Comment by yuryzablotski** [comment]
I have composed a new issue on the github of lqmm package. The owner did work on it September 2023 last time. So I hope he will react to the issue.

I'll get back to you when he replies. Until then, here is my message to him for your information:

"A tidier of results would be greatly appreciated. Because it does not work with some packages. Here is the warning:

! broom::tidy() failed to tidy the model.
! tidy_parameters() also failed.

With such a tidier, we could add basic support (i.e. just returning the tidy tibble of the coefficients). For other functionalities included in broom.helpers (identification of variables, reference rows, etc.) we would need terms(), model.matrix() and model.frame() added to the original package.

Here is an example where it does work with emmeans somehow, but it does not work with other packages for plotting and producing results:

library(tidyverse)
library(lqmm)
theme_set(theme_test())

data(Orthodont)
Orthodont <- Orthodont %>%
mutate(age = factor(age))

rim <- lqmm(distance ~ age, random = ~ 1,
group = Subject,
tau = 0.75, data = Orthodont)

library(emmeans)
bla <- emmeans(rim, pairwise ~ age, tau = 0.75)
bla
plot(bla$emmeans)
plot(bla$contrasts)
emmip(rim, ~ age, CIs = T, tau = 0.75, weights = "prop")

library(sjPlot)
plot_model(rim, type = "eff", terms = "age")

library(gtsummary)
tbl_regression(rim, add_pairwise_contrasts = T)

Best regards"

**Comment by larmarange** [comment]
For reference: https://github.com/marco-geraci/lqmm/issues/3
