### ISSUE TITLE
Bug Report: `add_glance_*()` functions break if log-likelihood is not a numeric value

### ISSUE THREAD

**Issue by ndunnewind** [ddsjoberg/gtsummary#1592]
Some `glance()` methods return the log-likelihood as a `logLik` object instead of a numeric value. This breaks the `add_glance_table()` and `add_glance_source_note()` methods.

``` r
quine.nb1 <- MASS::glm.nb(Days ~ Sex/(Age + Eth*Lrn), data = MASS::quine)
tbl <- gtsummary::tbl_regression(quine.nb1)
gtsummary::add_glance_source_note(tbl)
#> Error in `tidyr::pivot_longer()`:
#> ! Can't combine `null.deviance` <double> and `logLik` <logLik>.
```

<sup>Created on 2024-01-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Thank you @ndunnewind for the report! I hadn't come across that before.

FYI it may be a number of months before we get to updating this, and in the meantime, you can use:

```r
quine.nb1 <- MASS::glm.nb(Days ~ Sex/(Age + Eth*Lrn), data = MASS::quine)
broom::glance(quine.nb1)$logLik |> str()

tbl <- gtsummary::tbl_regression(quine.nb1)
gtsummary::add_glance_source_note(
  tbl,
  glance_fun = \(x) broom::glance(x) |> dplyr::mutate(dplyr::across(dplyr::everything(), as.numeric))
)
```

**Comment by ddsjoberg** [comment]
Thanks again for your post! This has been addressed in the dev version.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.9.9.9000'
```

``` r

quine.nb1 <- MASS::glm.nb(Days ~ Sex/(Age + Eth*Lrn), data = MASS::quine)
tbl <- tbl_regression(quine.nb1)
add_glance_source_note(tbl) |> 
  as_kable()
```

| **Characteristic** | **log(IRR)** | **95% CI**  | **p-value** |
|:-------------------|:------------:|:-----------:|:-----------:|
| Sex                |              |             |             |
| F                  |      —       |      —      |             |
| M                  |    -0.48     | -1.3, 0.29  |     0.2     |
| Sex \* Age         |              |             |             |
| F \* F1            |    -0.71     | -1.4, -0.09 |    0.028    |
| M \* F1            |    -0.72     | -1.3, -0.09 |    0.029    |
| F \* F2            |    -0.61     | -1.4, 0.15  |    0.10     |
| M \* F2            |     0.63     |  0.08, 1.2  |    0.022    |
| F \* F3            |    -0.34     | -1.0, 0.29  |     0.3     |
| M \* F3            |     1.2      |  0.52, 1.8  |   \<0.001   |
| Sex \* Eth         |              |             |             |
| F \* N             |    -0.07     | -0.60, 0.45 |     0.8     |
| M \* N             |    -0.68     | -1.2, -0.16 |    0.008    |
| Sex \* Lrn         |              |             |             |
| F \* SL            |     0.94     |  0.26, 1.6  |    0.003    |
| M \* SL            |     0.24     | -0.39, 0.91 |     0.5     |
| Sex \* Eth \* Lrn  |              |             |             |
| F \* N \* SL       |     -1.4     | -2.1, -0.61 |   \<0.001   |
| M \* N \* SL       |     0.76     | -0.11, 1.6  |    0.084    |

<sup>Created on 2024-06-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
