### ISSUE TITLE
Customize "desired" reference level for tbl_regression()

### ISSUE THREAD

**Issue by Andrzej-Andrzej** [ddsjoberg/gtsummary#1593]
Hi,
This is more of a question than an issue, I have read this:
[https://github.com/ddsjoberg/gtsummary/issues/628](https://github.com/ddsjoberg/gtsummary/issues/628)

I would like to ask how to change emdash to word "Reference" in regression resulting table ?
Also, would it be possible to change a reference level of a particular factor ? 
```
x2 <- rbind(
  data.frame(time = "Pre", treatment = "Control", response = rnorm(100, mean=1)),
  data.frame(time = "Pre", treatment = "Treatment", response = rnorm(100, mean=2)),
  data.frame(time = "Post", treatment = "Control", response = rnorm(100, mean=1)),
  data.frame(time = "Post", treatment = "Treatment", response = rnorm(100, mean=2))
) %>% mutate(time = factor(time, levels = c("Pre", "Post"))) %>%
mutate(treatment = factor(treatment, levels = c("Control", "Treatmented")))


m <- lm(response ~ time * treatment, data=x, contrasts = list(time = "contr.sum", treatment= "contr.sum"))

m1 <- lm(response ~ time * treatment, data=x)

m %>% tbl_regression()

m1 %>% tbl_regression()
```
This resulting table is a bit modest, can it be expanded somehow to present more informations (like intercept, std error) ?
That proposition from referenced post is not working here, neither _gt_tjmeyers() function  :
```
list("tbl_regression-lgl:add_ref_est" = TRUE,
     "tbl_regression-str:ref_row_text" = "Reference") %>%
  set_gtsummary_theme()
  ```
I am beginner with gtsummary, so kindly please advise.

**Comment by ddsjoberg** [comment]
@Andrzej-Andrzej thanks for the post. Questions are best asked and answered on stackoverflow.com. Use the gtsummary tag and I'll be notified of your question

**Comment by larmarange** [comment]
To change a reference row, you should do it when computing your model. Cf. https://larmarange.github.io/broom.helpers/articles/tidy.html#different-type-of-contrasts

**Comment by Andrzej-Andrzej** [comment]
Hi @larmarange and thank you, 
do you know by any chance what to do with rms ols() function used with tbl_regression()  ? 
I got "! `broom::tidy()` failed to tidy the model" error.

**Comment by larmarange** [comment]
This question is unrelated to this issue. 

Please open a separate issue on broom.helpers GitHub with a reproductive example
