### ISSUE TITLE
Feature request: Association Tests Between Two Categorical Variables (Both With Multiple Response Options)

### ISSUE THREAD

**Issue by rawand-hanna** [ddsjoberg/gtsummary#1594]
**Is your feature request related to a problem? Please describe.**
I can't use gtsummary to test for association among two categorical variables having **multiple response** options, the gtsummary package will generate a table for every possible pair of options among the two categorical variables. 
For example, if variable 1 has 3 options and variable 2 has 3 options, then gtsummary will generate 9 tables.

But often, we need to test for association between the variables and not between the pairs of the categorical variable options. 

**Describe the solution you'd like**
Adding the capability to test for association between categorical variables (multiple responses) and not between the pairs of options would be amazing.

**Describe alternatives you've considered**
The [MRCV] (https://journal.r-project.org/archive/2014/RJ-2014-014/RJ-2014-014.pdf#page=7&zoom=100,98,473) works well for such cases but lacks other features provided by the gtsummary package.

**Comment by ddsjoberg** [comment]
Thanks for the post @rawand-hanna . I think you'll need to add some concrete examples of what you're requesting. I am not sure I follow 100%

**Comment by rawand-hanna** [comment]
Hey @ddsjoberg 
Thanks for the response 

Here is an example 

library(tidyverse)
library(gtsummary)

df <- tibble(language = c('Arabic French', 'French Spanish', 'Spanish Arabic', 'Arabic', 'French'),
             education = c('Primary', 'Primary', 'Secondary', 'Secondary', 'Primary'))

df %>% tbl_summary(by = education) %>% 
  add_overall() %>% 
  add_p()

Here is the result
![image](https://github.com/ddsjoberg/gtsummary/assets/134291202/c5bf0f93-6ee6-474d-b9b7-ec5c9a4d7dc7)

The issue is that the cross table is **not displaying** each language on a **separate row**, instead, it displays each **combination** of languages on each row.

Is there a way to tell **gtsummary** that the **type** of a variable is **categorical** with '**select multiple**' type?

**Comment by ddsjoberg** [comment]
Perhaps this will be helpful: https://mskcc-epi-bio.github.io/bstfun/reference/add_variable_grouping.html

As I mentioned in the stackoverflow post you recently made, gtsummary will only tabulate what is in the data frame.

**Comment by rawand-hanna** [comment]
Thanks @ddsjoberg 
You are the best

Just a quick note, while using the **add_variable_grouping()** function, the **p-value** is still calculated per **each** of the categorical variables with the cross-tab variable.

![Untitled](https://github.com/ddsjoberg/gtsummary/assets/134291202/2d21f2d2-1f83-4e03-8e8f-479a5150fd79)

I used the same sample code as [here](https://mskcc-epi-bio.github.io/bstfun/reference/add_variable_grouping.html)

Added age_group variable to the code

`set.seed(11234)

  data.frame(
    race_asian = sample(c(TRUE, FALSE), 20, replace = TRUE),
    race_black = sample(c(TRUE, FALSE), 20, replace = TRUE),
    race_white = sample(c(TRUE, FALSE), 20, replace = TRUE),
    age = rnorm(20, mean = 50, sd = 10)
  ) %>%
  **mutate(age_group = cut(age, breaks = 3)) %>%** 
  gtsummary::tbl_summary(by = age_group,
    label = list(race_asian = "Asian",
                 race_black = "Black",
                 race_white = "White",
                 age = "Age")
  ) %>% 
  add_variable_grouping(
    "Race (check all that apply)" = c("race_asian", "race_black", "race_white")
  ) %>% 
  **add_p()**`
