### ISSUE TITLE
Feature request: Creating a unified download button to download an excel file with gtsummary tables and dataframes

### ISSUE THREAD

**Issue by bc-teixeira** [ddsjoberg/gtsummary#1598]
Hi @ddsjoberg 

First of all, this package is one of the greatest things I've seen in the R community. It is saving me loads of time and I'm using it all around in my commpany.

A common request I receive from clients is the capability of generating excel tables from a markdown or quarto output. I ended up solving this issue and will send a pull request since I feel this will be very helpful to the package. So the function I created will get a list of named objects being them gtsumary tables or DFs, add them to a temp excel file and create a button to download to be added into quarto or Markdown.

Just let me know if you agree this is helpfull. ;)

Best

Bruno

**Comment by bc-teixeira** [comment]
[Fork here](https://github.com/bc-teixeira/gtsummary/commit/c98f5e9d7a2b35d5597fcd2d8157733fa6eb0a8d)

**Comment by ddsjoberg** [comment]
hi @bc-teixeira ! thanks for the post and the kind words!

I think this sounds like a super helpful feature not just for gtsummary tables, but many kinds of tables. Unfortunately, I think it's a feature that is a bit out of the scope of the gtsummary package.

It sounds like this is something that could work for any gt table, right? Perhaps first add the function to your own package, and once it's up and running you could ping them to ask if they'd like to support it?
