### ISSUE TITLE
Feature request: tbl_summary() analyze only non-missing values in "split by" operations

### ISSUE THREAD

**Issue by ledermanr** [ddsjoberg/gtsummary#1599]
In   tbl_summary(by = trt)

it would be extremely helpful to provide an option to confined analyses to non-missing values, by variable.

For example
A with n=60 subjects at timepoint=baseline, n=45 subjects at timepoint=day30, and n=30 subjects at timepoint=day60 may have inconsistently missing values for variables such as mr_severity, mitral_gradient, lvot_diameter across timepoints.

A classic shortcoming of medical literature is that mean/median values for observations tbl_summary(by=timepoint) that are depicted in tabular form, created using tools such as tbl_summary, without accounting for missing values.  Yes I know I could filter the data piped into tbl_summary, but that is difficult for a civilian like me.

Thank you for considering this feature request and for this fabulous toolkit!

**Comment by ddsjoberg** [comment]
hi @ledermanr , thanks for the post!!

I certainly understand where you're coming from. The `tbl_summary()` tool is quite general for many more cases than baseline and followup visits, which would make this operation difficult to generalize (e.g. `tbl_summary()` doesn't even know the subject ID). Unfortunately, I don't think this is a feature we can implement.

If it helps, this code can quickly remove subjects without full followup. Image each subject is meant to have 2 rows in the data: baseline and followup.

```r
df |>
  # remove subjects without both baseline and followup visits 
  dplyr::filter(
    .by = SUBJECTID,
    dplyr::n() == 2
  )
```
