### ISSUE TITLE
Add possibility to show N without NAs in column headers

### ISSUE THREAD

**Issue by maciekbanas** [ddsjoberg/gtsummary#1601]
Excuse me if I am missing something but I think it would be nice if I could somehow pass to the overall header a N value but without NAs (missing values) especially when I decide to switch them off.

Please consider the workflow:
```
df <- data.frame(
  has_treatment = c("Yes", "Yes", "No", "Yes", "No"),
  treatment = c("Trt1", "Trt2", NA, "Trt2", NA)
)
```

Makes sense when gtsummary shows N for NAs as well
```
df %>%
  gtsummary::tbl_summary(by = has_treatment, missing = "ifany") %>%
  gtsummary::add_overall()
```
<img width="210" alt="image" src="https://github.com/ddsjoberg/gtsummary/assets/74212933/5fa2a878-4902-4edb-b888-67ce6c66e95a">

BUT this one may be confusing for the user (where are these 2 No's):
```
df %>%
  gtsummary::tbl_summary(by = has_treatment, missing = "no") %>%
  gtsummary::add_overall()
```
<img width="201" alt="image" src="https://github.com/ddsjoberg/gtsummary/assets/74212933/f8dee5c8-c4a5-402b-bfa8-37f1427dd6f4">

I couldn't find any simple way to avoid counting NAs in the headers. 
In my view, it would be more intuitive if there was no NA/missing data counted if I pass "no" argument to the `missing` parameter.

**Comment by ddsjoberg** [comment]
@maciekbanas thanks for the post.

In your example, there is single variable, so one could feasibly match the counts from the variable tabulation to the header. But most tables have more than one variable summarized in them, and each variable may have different patterns of missingness.

For your cases I would do something like this 

```r
data |>
  dplyr::select(varname, by_varname) |>
  tidyr::drop_na() |>
  gtsummary::tbl_summary(by = by_varname)
```

**Comment by maciekbanas** [comment]
@ddsjoberg thank you for quick response.
Yes, it makes sense. In my real case I wanted to remain with the columns (here "No" column). But probably it would seem unintuitive to leave the column with no data.
