### ISSUE TITLE
Please clearly explain how to suppress `zzz.R` in final rendered content

### ISSUE THREAD

**Issue by jhchou** [ddsjoberg/gtsummary#1609]
While using `gtsummary` in a Quarto document for table generation in a professional report, I was surprised to intermittently see `#Uighur` and `#BlackLivesMatter` in the final rendered output.

I then spent a significant amount of time assuming I had a compromised RStudio or `quarto` installation, and was preparing to wipe and reinstall everything, before I came across the [`gtsummary/R/zzz.R` file](https://github.com/ddsjoberg/gtsummary/blob/main/R/zzz.R), which has been present for several years now.

Regardless of whether I agree or disagree with the sentiments (I do, in fact, agree), I DO NOT want this to have a 20% chance of being inserted without my knowledge into reports that I am disseminating to my hospital leadership.

This is very unprofessional and concerning behavior on the part of `gtsummary` developers.

If the message is to be inserted, please at least make it VERY clear how to suppress its insertion into final rendered documents.

I'm hoping that `suppressPackageStartupMessages(library(gtssummary))` will be sufficient to avoid needing to explain myself to my bosses.

**Comment by ddsjoberg** [comment]
> This is very unprofessional and concerning behavior on the part of gtsummary developers.

I hope this free software has been useful for you.
