### ISSUE TITLE
Issue exporting tbl_cross with gt::gtsave

### ISSUE THREAD

**Issue by anddis** [ddsjoberg/gtsummary#1613]
Exporting a `tbl_cross` as .docx with `as_gt()` followed by `gt::gtsave()` generates a Word file that, when opened, triggers this warning pop-up window: 

> Word found unreadable content in t1.docx. Do you want to recover the contents of this document? If you trust the source of the document, click Yes 

Clicking on Yes will open the document but the table's formatting is lost.

```r
library(gtsummary)
library(gt)
xxx <- mtcars |> 
  tbl_cross(row = vs, 
            col = am) |> 
  as_gt()
gtsave(xxx, "t1.docx")
```

---

```r
> packageVersion("gtsummary")
[1] ‘1.7.2’
> packageVersion("gt")
[1] ‘0.10.1’
```
Word v16.83 on macOS 14.3.1

**Comment by ddsjoberg** [comment]
Thanks for reporting @anddis !

I was expecting your table to have complex styling, which would lead to the error. But this all seems pretty standard. 
![image](https://github.com/ddsjoberg/gtsummary/assets/26774684/aec57183-4eb5-4cd4-a621-992d1083d038)

It looks like the error is related to a column with a blank header. If you add a header (as I've done below), there is no issue.

```r
library(gtsummary)
library(gt)
xxx <- mtcars |> 
  tbl_cross(row = vs, 
            col = am) |> 
  modify_header(label = "adding a header") |> 
  as_gt()
gtsave(xxx, "t1.docx")
```

I think you should go ahead and report this bug to {gt}. Thanks again for the post!

**Comment by anddis** [comment]
Will do! Thank you for the bush fix, worked perfectly.
