### ISSUE TITLE
Label of Median (IQR)

### ISSUE THREAD

**Issue by dchiu911** [ddsjoberg/gtsummary#1616]
Is it currently accepted that the IQR is just synonymous with reporting the range (Q1, Q3)? How come the footnote doesn't say "Median (Q1, Q3)" in line with the default (`all_continuous() ~ "{median} ({p25}, {p75})"`).

``` r
library(gtsummary)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
trial %>%
  select(age, grade, response) %>%
  tbl_summary()
```

<table class="gt_table">
  &#10;  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>N = 200</strong><sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Age</td>
<td class="gt_row gt_center">47 (38, 57)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Unknown</td>
<td class="gt_row gt_center">11</td></tr>
    <tr><td class="gt_row gt_left">Grade</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">I</td>
<td class="gt_row gt_center">68 (34%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">II</td>
<td class="gt_row gt_center">68 (34%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">III</td>
<td class="gt_row gt_center">64 (32%)</td></tr>
    <tr><td class="gt_row gt_left">Tumor Response</td>
<td class="gt_row gt_center">61 (32%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Unknown</td>
<td class="gt_row gt_center">7</td></tr>
  </tbody>
  &#10;  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="2">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           &#10;          Median (IQR); n (%)
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>

<sup>Created on 2024-03-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
We haven't found any issues with the current messaging. We do however provide the functionality to change the stat label (`add_stat_label()`) and the footnote (`modify_footnote()`) to be whatever you prefer. Thanks
