### ISSUE TITLE
Bug Report: Can not exponentiate survreg() model

### ISSUE THREAD

**Issue by YousufMohammed2002** [ddsjoberg/gtsummary#1618]
I have fitted a accelerated failure time model in r using the survReg model. I can create a summary table with tbl_regression but I get this error: 

Warning: The `exponentiate` argument is not supported in the `tidy()` method for `survreg` objects and will be ignored. 

And it only prints a summary table without it being exponentiated. It works fine for a coxph model I fitted earlier. It says survreg() is a supported model on the website but does not exponentiate.

Thanks in advance! 

---

I am trying to fit

```r
exp <- survreg(Surv(futime, fustat) ~ ecog.ps + rx, ovarian,
        dist="exponential")

tbl_regression(exp, expontiate = TRUE) -> aft1
aft
```

**Comment by larmarange** [comment]
https://stackoverflow.com/questions/74803815/how-do-i-get-gtsummary-to-exponentiate-a-weibull-model

**Comment by ddsjoberg** [comment]
thanks @larmarange !!
