### ISSUE TITLE
Question about how to add corresponding test statistics to the table

### ISSUE THREAD

**Issue by zhonghua723** [ddsjoberg/gtsummary#1622]
gtsummary  is a very powerful and easy-to-use R package, but I have encountered a small problem and need to seek an answer.

I am trying to create a summary table using the tbl_summary() function, which involves adding p-values and corresponding test statistics to the table. The intention is to automatically apply the appropriate statistical test based on variable type—Wilcoxon rank-sum or t-test for continuous variables, and chi-squared or exact test for categorical variables—and then display the test statistic (e.g., χ² value, t statistic, or rank-sum statistic).

After asking ChatGPT-4 and other websites, They provide me some codes:

```r 
library(dplyr)
library(gtsummary)
data %>%
  mutate(
    # Conversion of variables to factor...
  ) %>%
  tbl_summary(
    by = SAP,
    type = all_continuous() ~ "continuous2",
    statistic = all_continuous() ~ c("{mean} ({sd})", "{median} ({p25}, {p75})", "{min}, {max}"),
    digits = all_continuous() ~ 2
  ) %>%
  add_n() %>%
  add_p() %>%
  add_stat_label() %>%
  as_flex_table() 
```
  
My expectation was that add_stat_label() would automatically detect the type of tests conducted and append the test statistics next to the p-values in the summary table. However, the test statistics are not being displayed in the generated table.
  
Thank you for your time and assistance with this matter.

**Comment by ddsjoberg** [comment]
Dear @zhonghua723 , Thanks for the post.

I am happy to answer questions. But it's best for the community if they are asked and answered on a public forum. Please post your question to stackoverflow.com. If you include the gtsummary tag, I'll be notified of your post. If I recall correct, similar posts have already been made.

Your post should include a minimal reproducible example, aka a minimal reprex. A reprex includes both data and code I can run on my machine. If needed, include a mock-up of what you want your results to look like.

Take just a few minutes to review reprex.tidyverse.org for detailed instructions on how to create a reprex.
