### ISSUE TITLE
Feature request: <Describe request>

### ISSUE THREAD

**Issue by zhaohongxin0** [ddsjoberg/gtsummary#1623]
In the documentation, it is mentioned that we can utilize both the Wald confidence intervals (CI) and profile likelihood CI by applying different settings:

```
my_tidy <- function(x, exponentiate = FALSE, conf.level = 0.95, ...) {
  dplyr::bind_cols(
    broom::tidy(x, exponentiate = exponentiate, conf.int = FALSE),
    # calculate the confidence intervals, and save them in a tibble
    stats::confint.default(x) %>%
      tibble::as_tibble() %>%
      rlang::set_names(c("conf.low", "conf.high"))
  )
}

lm(age ~ grade + marker, trial) %>%
  tbl_regression(tidy_fun = my_tidy)
```

I have a question regarding the application of this method to multiple imputation datasets. For instance:

```
df_imputed <- mice::mice(trial, m = 2)

imputed_model <- with(df_imputed, lm(age ~ marker + grade))

tbl_regression(imputed_model) 
```

Could you inform me which method is used for CI calculation in this context? Is it Wald or profile likelihood? This is because tbl_regression() does not accept the tidy_fun = my_tidy argument in this scenario, resulting in errors. How can we obtain the desired CIs?

Thank you very much!

**Comment by ddsjoberg** [comment]
Dear @zhaohongxin0 , thanks for the post.

The tidy function for mice regression models is [pool_and_tidy_mice()](https://github.com/ddsjoberg/gtsummary/blob/30ef7175b9cc935ddcfd41f7c9c2418f3ee52cd8/R/custom_tidiers.R#L243), which is essentially `mice::pool() |> mice::tidy()`. Each model type could have different defaults, and you'd need to check in with the mice package to see what the defaults are.

To customize, you'd need to write a tidier similar to `pool_and_tidy_mice()`.

Hope that helps
