### ISSUE TITLE
Bug Report: gtsummary does not show all levels of a factor for mixed effects survival analysis

### ISSUE THREAD

**Issue by lukejenner6** [ddsjoberg/gtsummary#1624]
When applying the function to a survival object created using coxph() with a frailty() term, gtsummary produces a table with the correct coefficients. However, it does not include all levels/groups of factors included in the analysis.

**Comment by larmarange** [comment]
Do you have a reproductive example?
What does return `broom::tidy()` for such model?

**Comment by ddsjoberg** [comment]
Dear @lukejenner6 , please feel free to re-open the issue when you have a reproducible example.
