### ISSUE TITLE
The SMD calculation method in gtsummary is wrong?

### ISSUE THREAD

**Issue by zhangkaicr** [ddsjoberg/gtsummary#1633]
The SMD calculation method in gtsummary is wrong. After looking at your calculation method.(https://github.com/ddsjoberg/gtsummary/blob/50d13a3b2e9ab69436cdf328d9aeb7ce48257d8e/vignettes/articles/propensity_scores.Rmd)

 you use the gtsummary package to directly calculate the SMD after matching, such as test = everything() ~ "smd". This result is different from the SMD automatically calculated after matching by the Matchit package. See the paper for specific reasons:
Megan M. Chung, Cheryl Pan, Hideyuki Hayashi, Viswajit Kandula, Yanling Zhao, Dov Levine, Patra Childress, Lauren Sutherland, Syed T. Raza, Paul Kurlansky, Craig R. Smith, Hiroo Takayama, Significance of isolated postoperative atrial fibrillation in thoracic aortic aneurysm repair, The Journal of Thoracic and Cardiovascular Surgery, 10.1016/j.jtcvs.2023.12.023, (2024).

Why the regular gtsummary package and tableone package cannot be used to calculate SMD before and after matching, the explanation is as follows:The MatchIt package manual says that:

The standardized mean differences are computed both before and after matching or subclassification as the difference in treatment group means divided by a standardization factor computed in the unmatched (original) sample. The standardization factor depends on the argument supplied toestimand in matchit(): for "ATT", it is the standard deviation in the treated group; for "ATC",it is the standard deviation in the control group; for "ATE", it is the square root of the average of the variances within each treatment group. The post-matching mean difference is computed with weighted means in the treatment groups using the matching or subclassification weights.

The problem is that when comparing balance before and after matching, the SMD will be affected not only by changes in balance but also by changes in the standard deviation of the covariate when the standard deviation of the matched sample is used as the standardization factor after matching. This muddles two things together when we only care about one. Holding the standard deviation constant prevents this, isolating the effect of matching on balance alone.

Consider the following example. Let's say the mean of a covariate X (e.g., age) in the treated group is 44 and the mean in the control group is 46, and the pooled standard deviation is 9. Let's say that after matching, the control group mean is now 45 and the pooled standard deviation is now 4. Was there better balance before matching or after matching?

It should be clear that the covariate means are closer together, which indicates an improvement in balance and therefore a reduction in bias. Which method of computing the SMD reflects this?

Prior to matching, the SMD is (46-44)/9 = .22. By the standard criterion of SMDs less than .1, this would be considered imbalanced.

Using the formula for the SMD that uses the standard deviation in the unmatched sample, the matched SMD is (45-44)/9 = .11, indicating better balance.

Using the formula for the SMD that uses the standard deviation in the matched sample, the matched SMD is (45-44)/4 = .25, indicating that balance got worse after matching!

Remember that the bias of the effect estimate is a function of the mean differences, and standardizing them to produce the SMD is just a way to simplify balance statistics for users. It's all arbitrary anyway, but at least using the unmatched standard deviation correctly isolates changes in balance from changes in variability, the latter of which is not related to bias.

**Comment by ddsjoberg** [comment]
Thanks @zhangkaicr for the detailed note. That PR has been on-going for 3+ years now. If it ever gets to the point where it's ready for review, I'll be sure to address your comments. Much appreciated!
