### ISSUE TITLE
modify_table_styling does not work when applied to groupname_col

### ISSUE THREAD

**Issue by ltj-github** [ddsjoberg/gtsummary#1635]
```r
> B$table_body
# A tibble: 12 × 80
   groupname_col tbl_id1 tbl_id2 variable      var_label  row_type label var_type_1 reference_row_1
   <chr>           <int>   <int> <chr>         <chr>      <chr>    <chr> <chr>      <lgl>          
 1 Model 1             1       1 Periodontitis Periodont… label    Peri… dichotomo… NA             
 2 Model 1             1       1 Periodontitis Periodont… level    No    dichotomo… TRUE           
 3 Model 1             1       1 Periodontitis Periodont… level    Yes   dichotomo… FALSE          
 4 Model 2             1       2 Periodontitis Periodont… label    Peri… dichotomo… NA             
 5 Model 2             1       2 Periodontitis Periodont… level    No    dichotomo… TRUE           
 6 Model 2             1       2 Periodontitis Periodont… level    Yes   dichotomo… FALSE          
 7 Model 3             1       3 Periodontitis Periodont… label    Peri… dichotomo… NA             
 8 Model 3             1       3 Periodontitis Periodont… level    No    dichotomo… TRUE           
 9 Model 3             1       3 Periodontitis Periodont… level    Yes   dichotomo… FALSE          
10 Model 4             1       4 Periodontitis Periodont… label    Peri… dichotomo… NA             
11 Model 4             1       4 Periodontitis Periodont… level    No    dichotomo… TRUE           
12 Model 4             1       4 Periodontitis Periodont… level    Yes   dichotomo… FALSE  

B |> 
  modify_table_styling(
    columns = groupname_col ,  
    rows =groupname_col  == "Model 1",  
    footnote = "Model 1: Not adjusted"
  )
 
```

**Comment by ddsjoberg** [comment]
Dear @ltj-github , thanks for the post.

- this seems like a post that is better suited for stackoverflow.com. that is the best place to ask questions about the package.
- when you post on stackoverflow, and even when you post here, you must include a minimal reproducible example https://reprex.tidyverse.org/
- when you post, you're more likely to get help by clearly stating your question. include details on what you're seeing and what you expect to see.

**Comment by ltj-github** [comment]
`

library(gtsummary)

Model1 <-
  glm(response ~ age, trial, family = binomial(link = "logit")) %>%
  tbl_regression(exponentiate = TRUE,include = age)

Model2 <- glm(response ~ age + grade, trial, family = binomial(link = "logit")) %>%
  tbl_regression(exponentiate = TRUE,include = age)

Model <- tbl_stack(list(Model1, Model2),group_header = c("Model 1", "Model 2"))


Model <- Model |> 
  modify_table_styling(
    columns = groupname_col ,  
    rows =groupname_col  == "Model 1",  
    footnote = "Model 1: Not adjusted"
  )

Model       
`

This is a repetitive case that I have worked on, and it seems that I am unable to add footnotes.

**Comment by ltj-github** [comment]
> Dear @ltj-github , thanks for the post.
> 
> - this seems like a post that is better suited for stackoverflow.com. that is the best place to ask questions about the package.
> - when you post on stackoverflow, and even when you post here, you must include a minimal reproducible example https://reprex.tidyverse.org/
> - when you post, you're more likely to get help by clearly stating your question. include details on what you're seeing and what you expect to see.

I tried to post my questions on stackoverflow, but it seems that I need relevant points to ask questions, and I finally failed to upload relevant posts.

**Comment by ddsjoberg** [comment]
You can definitely post on stackoverflow. There are many resources available to help you learn stackoverflow. Good luck!

**Comment by ltj-github** [comment]
> You can definitely post on stackoverflow. There are many resources available to help you learn stackoverflow. Good luck!

Thank you for your patient reply. I will try to post again tomorrow! ! Thank you!
