### ISSUE TITLE
Exclude some variables from testing when using add_p()

### ISSUE THREAD

**Issue by jflynn264** [ddsjoberg/gtsummary#164]
Option to incorporate which variables to given p-values to and which to just provide summary statistics for

**Comment by ddsjoberg** [comment]
I think this is great!  Let's meet to discuss the details

**Comment by ddsjoberg** [comment]
`tbl_regression()` has options to either list included variables or list variables to exclude.
![image](https://user-images.githubusercontent.com/26774684/60125627-35faf200-975a-11e9-960c-eca17f196970.png)

The function default to include all variables.  But if include is specified, then only the vars listed will be included...same but opposite for exclude.

Does this sound like a good approach?

**Comment by karissawhiting** [comment]
I like this! I like having the option of easily including or excluding.

**Comment by ddsjoberg** [comment]
We should probably make this work with the select helpers as well.  

(and update `tbl_regression()` to work with them too!)

Question:  Currently, the `as_gt()` function has an `omit = ` option.  Should we update that to be `include = `, and `exclude = ` to match? hmmm...thinking...thinking...

**Comment by margarethannum** [comment]
What does the `omit = ` option usually do? What should it omit? I really like the idea of making it work with select helpers to include/exclude certain results

**Comment by ddsjoberg** [comment]
Every returned gtsummary object (e.g. tbl_summary, tbl_regression, etc.) is a list with at least two elements: `table_body` and `gt_calls`.  `table_body` is a tibble that contains all the columns that will be printed via {gt}, and `gt_calls` is a list of {gt} function calls that are executed on `table_body`.  

If a user wants to customize the output, they can omit certain calls from `gt_calls` from being executed with the `omit = ` option.

**Comment by ddsjoberg** [comment]
Thank you @jflynn264 for the pull request!  #174
