### ISSUE TITLE
Feature request: digits for each statistic in merged_columns

### ISSUE THREAD

**Issue by AlexZHENGH** [ddsjoberg/gtsummary#1644]
**Is your feature request related to a problem? Please describe.**

I would like to create a table with different digit specifications for each statistic in merged_columns. For example, 1 digit for `"{N_obs}"`, 2 and 3 digits for `"{mean} ({sd})"`, and 2 digits for `"{min} - {max}"`. Currently, this isn't possible using the `digits` argument in `tbl_summary()`.

```
library(gtsummary)

tbl_summary_ex4 <-
  trial %>%
  select(age, marker) %>%
  tbl_summary(
    type = all_continuous() ~ "continuous2",
    statistic = all_continuous() ~ c("{N_obs}", "{mean} ({sd})", "{min} - {max}"),
    digits = all_continuous() ~ c(2, 3)  # this results in 3 digits for max
  )
tbl_summary_ex4
```

**Describe the solution you'd like**

I would like to be able to specify digits for each statistic in merged_columns individually:

```R
tbl_summary_ex4 <-
  trial %>%
  select(age, marker) %>%
  tbl_summary(
    type = all_continuous() ~ "continuous2",
    statistic = all_continuous() ~ c("{N_obs}", "{mean} ({sd})", "{min} - {max}"),
     digits = all_continuous() ~ list(
       "{N_obs}" = 1,
       "{mean} ({sd})" = c(2, 3),
       "{min} - {max}" = c(2, 2)
     ),
    missing = "no"
  )
tbl_summary_ex4
```

**Describe alternatives you've considered**

Another approach could be to allow specifying digits for each built-in or customized statistic separately:

```R
tbl_summary_ex4 <-
  trial %>%
  select(age, marker) %>%
  tbl_summary(
    type = all_continuous() ~ "continuous2",
    statistic = all_continuous() ~ c("{N_obs}", "{mean} ({sd})", "{min} - {max}"),
     digits = all_continuous() ~ list(
       N_obs = 1,
       mean = 2,
       sd = 3,
       min = 2,
       max = 2
     ),
    missing = "no"
  )
tbl_summary_ex4
```

**Additional context**

The following image shows how the table should look:

![image](https://github.com/ddsjoberg/gtsummary/assets/7163285/56a5fa02-c1a7-4188-a369-fa95d00b61ad)

**Comment by ddsjoberg** [comment]
Dear @AlexZHENGH , thanks for the post.

You can control the formatting for each statistic. See the example below. In the next version of the package, you can use a named list to change a single statistics as well.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.7.2'

trial |> 
  select(age, marker) |> 
  tbl_summary(
    type = all_continuous() ~ "continuous2",
    statistic = all_continuous() ~ c("{N_obs}", "{mean} ({sd})", "{min} - {max}"),
    digits = all_continuous() ~ list(0, 2, 3, 2, 2),
    missing = "no"
  ) |> 
  bold_labels() |> 
  as_kable() # convert to kable to display on GH
```

| **Characteristic**       |  **N = 200**   |
|:-------------------------|:--------------:|
| **Age**                  |                |
| No. obs.                 |      200       |
| Mean (SD)                | 47.24 (14.312) |
| Range                    |  6.00 - 83.00  |
| **Marker Level (ng/mL)** |                |
| No. obs.                 |      200       |
| Mean (SD)                |  0.92 (0.859)  |
| Range                    |  0.00 - 3.87   |

<sup>Created on 2024-05-15 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

FYI the best place to get guidance on how to use the package is stackoverflow.

**Comment by AlexZHENGH** [comment]
@ddsjoberg Many thanks!
