### ISSUE TITLE
by() w/10+ levels are not sorted properly

### ISSUE THREAD

**Issue by ahinton-mmc** [ddsjoberg/gtsummary#166]
First of all, BIG gtsummary fan here!!!! <3  

But...

by() variables with more than 10 levels are not sorted properly. Columns are displayed 1, 10, 2, 3, 4, 5... etc. when it should be 1:10. 

```r
 trial %>%
 mutate(byv = sample(1:10, n(), replace = TRUE)) %>%
 tbl_summary(by = "byv") 
```

**Comment by ddsjoberg** [comment]
OK @ahinton-mmc !  This update has been included !
