### ISSUE TITLE
Question / Feature request: type "dichotomous" option in tbl_summary not displaying both levels 

### ISSUE THREAD

**Issue by jkylearmstrong** [ddsjoberg/gtsummary#1674]
Is there a way to change this behavior that I am missing:

"dichotomous" categorical variables that are displayed on a single row, rather than one row per level of the variable. Variables coded as TRUE/FALSE, 0/1, or yes/no are assumed to be dichotomous, and the TRUE, 1, and yes rows are displayed. Otherwise, the value to display must be specified in the value argument, e.g. value = list(varname ~ "level to show")

```{r}
tmp <- data.frame(
  treatment = factor(sample(c("Treatment", "Control"), 100, replace = TRUE)),
  v1 = factor(sample(c("Yes", "No"), 100, replace = TRUE)),
  v2 = factor(sample(c("Yes", "No"), 100, replace = TRUE))
  )
```

```{r}
tmp |>
  tbl_summary(
    by = treatment,
    #setting dichotomous to FALSE maintains the single-row reporting for the yes class 
    statistic = list(all_categorical(dichotomous = FALSE) ~ "{n} ({p}%)")  
    )
```

```{r}
tmp |>
  tbl_summary(
    by = treatment,
    statistic = list( all_categorical(dichotomous = FALSE) ~ "{n} ({p}%)"),
    # this option did not allow me to report both either
    value = list(v1 ~ c("Yes","No"))
    )
```

I had to reclassify variables from 'yes' to "TRUE" and "no" to "FALSE" to make it so the table would display both levels for reporting purposes: 

```{r}
tmp |>
  mutate(
    across(
      c('v1', 'v2'), 
      \(x){if_else(x == "Yes", "TRUE", "FALSE")}
      )) |>
  tbl_summary(
    by = treatment,
    statistic = list( all_categorical(dichotomous = FALSE) ~ "{n} ({p}%)")
  )
```

Otherwise, I am enjoying the package and finding it very useful! Thanks!

**Comment by ddsjoberg** [comment]
Dear @jkylearmstrong , thanks of the post. Generally, stackoverflow is the best place to ask for help with the package.

Check out this previous response to this question. I hope that helps. https://github.com/ddsjoberg/gtsummary/issues/533

**Comment by jkylearmstrong** [comment]
I looked on Stackoverflow and saw that post but I did not find a solution, however, this appears to work. 

```
tmp |>
  tbl_summary(
    by = treatment,
    type = list(all_categorical()~ "categorical"),
  )
 ```
 
 so `stat` appears to control the stats displayed, whereas type shows how they are displayed?
 
 neat package! 
 
 I really appreciate the flexibility of using my own functions for p-values, very helpful.

**Comment by ddsjoberg** [comment]
great! glad it has been useful!
