### ISSUE TITLE
Wording in `tbl_uregression()` documentation: univariable instead of univariate?

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#1683]
This is an open question, but I have the feeling that in the documentation of `tbl_uregression()` it would be more appropriate to speak about "univariable regression model" rather than "univariate regression model".

In the litterature, "multivariate" is now very often limited to models with repeated outcomes, and the "multivariable" used to indicate a model with several predictors. Therefore, a model with one predictor would be a "simple" model or "univariable" model.

**Comment by ddsjoberg** [comment]
That's a good point! Will update :) (`tbl_uvregression()` should be added to the v2.0 branch this week)

**Comment by ddsjoberg** [comment]
updated in https://github.com/ddsjoberg/gtsummary/pull/1692
