### ISSUE TITLE
Feature request: Informative caption when using `tbl_regression()` with `mice::mira` 

### ISSUE THREAD

**Issue by ABohynDOE** [ddsjoberg/gtsummary#1689]
Whenever I'm using `tbl_regression()` with several imputed datasets (in the form of a `mice::mira` object), I always think that it would be informative to add a caption in the bottom of the table that says something like 'Results pooled from X imputations'.

I think this shouldn't be too hard to implement since when you pass a `mice::mira` object it also contains the number of imputations.
For now, the only solution that I have found is adding a footnote manually when converting the table to `gt` or `flextable`, but I feel like it would be better to have it directly in the `tbl_regression` part.

Here is an example to demonstrate what I mean;

``` r
# Impute m data sets
set.seed(1)
imp <- mice::mice(iris, m = 2)
#> 
#>  iter imp variable
#>   1   1
#>   1   2
#>   2   1
#>   2   2
#>   3   1
#>   3   2
#>   4   1
#>   4   2
#>   5   1
#>   5   2
```

``` r

# Fit a model for each imputation
mod <- with(imp, lm(Petal.Width ~ Petal.Length))

# Recall the number of imputations
mod$call1[[3]]
#> [1] 2
```

``` r

# Generate the regression table
gtsummary::tbl_regression(mod) |> 
  gtsummary::as_gt() |> 
  gt::tab_footnote(
    glue::glue("Results pooled from {mod$call1[[3]]} imputations")
  )
#> pool_and_tidy_mice(): Tidying mice model with
#> `mice::pool(x) %>% mice::tidy(conf.int = TRUE, conf.level = 0.95, exponentiate = FALSE)`
```

<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Beta&lt;/strong&gt;"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;p-value&lt;/strong&gt;"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">Petal.Length</td>
<td headers="estimate" class="gt_row gt_center">0.42</td>
<td headers="ci" class="gt_row gt_center">0.40, 0.43</td>
<td headers="p.value" class="gt_row gt_center"><0.001</td></tr>
  </tbody>
  &#10;  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"> Results pooled from 2 imputations</td>
    </tr>
    <tr>
      <td class="gt_footnote" colspan="4"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> CI = Confidence Interval</td>
    </tr>
  </tfoot>
</table>
</div>

<sup>Created on 2024-05-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Dear @ABohynDOE , thanks for the post. That is an interesting idea. 

First, I just want to point out that you can add footnotes from within gtsummary, and it will be included whether you use gt or flextable output (see example below).

Regarding the request: hmmm, there is certainly good information that could be reported alongside MICE regression models. I think that statement applies to all models, actually. But I question whether it needs to be included by default, since it's possible to simply update the table with _any_ additional information you'd like. 
 🤔 

``` r
set.seed(1)
imp <- mice::mice(iris, m = 2)
```

``` r

# Fit a model for each imputation
mod <- with(imp, lm(Petal.Width ~ Petal.Length))

gtsummary::tbl_regression(mod) |> 
  gtsummary::modify_footnote(label = glue::glue("Results pooled from {mod$call1[[3]]} imputations"))
#> pool_and_tidy_mice(): Tidying mice model with
#> `mice::pool(x) %>% mice::tidy(conf.int = TRUE, conf.level = 0.95, exponentiate = FALSE)`
```

<div id="ydgabwknrs" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>Characteristic</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Beta&lt;/strong&gt;"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;2&lt;/sup&gt;&lt;/span&gt;"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>2</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;p-value&lt;/strong&gt;"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">Petal.Length</td>
<td headers="estimate" class="gt_row gt_center">0.42</td>
<td headers="ci" class="gt_row gt_center">0.40, 0.43</td>
<td headers="p.value" class="gt_row gt_center"><0.001</td></tr>
  </tbody>
  &#10;  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> Results pooled from 2 imputations</td>
    </tr>
    <tr>
      <td class="gt_footnote" colspan="4"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>2</sup></span> CI = Confidence Interval</td>
    </tr>
  </tfoot>
</table>
</div>

<sup>Created on 2024-05-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ABohynDOE** [comment]
Dear @ddsjoberg, thanks a lot for the quick answer ! I wasn't aware that `modify_footnote()` could **add** new footnote, that's really interesting ! 

Given this new information I don't think that adding the caption by default is a good idea because, as you mentioned, it opens the door to doing it differently for each possible model that can be passed to `tbl_regression()`.

So I'll stick with your solution and close this issue. Thanks for the help !
