### ISSUE TITLE
Review `tbl_custom_summary()`

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#1699]
The `tbl_custom_summary()` function was merged in PR #1698

Can you please review to ensure there are no unknown regressions in functionality.

There are two known regressions:
- `continuous_summary()` is currently deprecated. The deprecation note indicates that similar functionality is available in `tbl_continuous()`.
- The default formatting performed for the displayed statistics are numeric formatters, e.g. `45.123123` -> `'45'`. When the statistic is character, the user needs to specify a formatting function (via `digits` argument) that works with characters, e.g. `as.character`. This behaviour mimics what occurs in `tbl_summary()`. But we could move things around to make this work.... 🤔

**Comment by ddsjoberg** [comment]
> The default formatting performed for the displayed statistics are numeric formatters, e.g. 45.123123 -> '45'. When the statistic is character, the user needs to specify a formatting function (via digits argument) that works with characters, e.g. as.character. This behaviour mimics what occurs in tbl_summary(). But we could move things around to make this work.... 🤔

FYI @larmarange this was fixed in #1806

**Comment by larmarange** [comment]
Thanks a lot

**Comment by ddsjoberg** [comment]
I am thinking more about creating Analysis Results Datasets first to power this more customized tables these days (because that is a format that will soon be required by CDISC and the FDA, and so it's a part of my job now).

The lovely thing about this approach is that you can put any statistic (univariable, multivariable...anything) in the ARD and then place it in a table. 

``` r
library(cards)
library(gtsummary)

bind_ard(
  ard_categorical(trial, by = trt, variables = grade, statistic = ~"p", denominator = "column") |> mutate(stat_name = "p_col"),  
  ard_categorical(trial, by = trt, variables = grade, statistic = ~"p", denominator = "row") |> mutate(stat_name = "p_row"),
  ard_categorical(trial, by = trt, variables = grade, statistic = ~"p", denominator = "cell") |> mutate(stat_name = "p_cell"),
  ard_categorical(trial, variables = trt)
) |> 
  tbl_ard_summary(
    by = trt,
    statistic = grade ~ "Column {p_col}%; Row {p_row}%; Cell {p_cell}%",
    missing = "no"
  ) |> 
  as_kable()
```

| **Characteristic** |          **Drug A** N = 98          |         **Drug B** N = 102          |
|:-------------------|:-----------------------------------:|:-----------------------------------:|
| grade              |                                     |                                     |
| I                  | Column 35.7%; Row 51.5%; Cell 17.5% | Column 32.4%; Row 48.5%; Cell 16.5% |
| II                 | Column 32.7%; Row 47.1%; Cell 16.0% | Column 35.3%; Row 52.9%; Cell 18.0% |
| III                | Column 31.6%; Row 48.4%; Cell 15.5% | Column 32.4%; Row 51.6%; Cell 16.5% |

<sup>Created on 2024-07-20 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

We can continue the convo, but let's take a pause for the release and do that in a new issue.

**Comment by larmarange** [comment]
Oh I see.

I'm not yet familiar enough with ARD format. But if I understand properly, the idea would be, once everything stabilized, to extend with new ard_* functions for advanced tables rather than having to extend gtsummary?

For example, an ard_ratio() instead of calling ratio_summary() with tbl_custom_summary().

I suppose that at some point you will prepare a vignette to present how to extend  cards/cardx?

Of course, once new version of gtsummary will be stabilized.

**Comment by ddsjoberg** [comment]
> if I understand properly, the idea would be, once everything stabilized, to extend with new ard_* functions for advanced tables rather than having to extend gtsummary?
> I suppose that at some point you will prepare a vignette to present how to extend cards/cardx?

Absolutely. I would love a world where gtsummary is a flexible framework, and extensions for more complex analysis/tables can be done in separate packages. (And hopefully it's quite simple to make extensions)

> For example, an ard_ratio() instead of calling ratio_summary() with tbl_custom_summary().

I don't think we'll ever need to force anyone into the ARD framework, but I think going forward we'll steer people towards it.
