### ISSUE TITLE
Bug Report: Factor level with `NA` label causes "Column stat_n doesn't exist" error (e.g. created by forcats).

### ISSUE THREAD

**Issue by DesiQuintans** [ddsjoberg/gtsummary#1704]
If a person uses something like `forcats::fct_na_value_to_level()` to convert missing values in a factor into an explicit level that has a missing label (i.e. the default behaviour of that function), then it raises an error in `tbl_summary()` because it expects levels to always have names.

``` r
library(gtsummary)
library(forcats)

set.seed(123456)

# Create a version of iris$Species that has missing entries.
sampled_Species <- sample(c(NA, "setosa", "virginica", "versicolor"), size = 150, replace = TRUE)

# By default, forcats::fct_na_value_to_level() turns missings into a level called `NA` that is actually
# a missing level name.
na_Species <- forcats::fct_na_value_to_level(sampled_Species)
table(na_Species)
#> na_Species
#>     setosa versicolor  virginica       <NA> 
#>         45         42         34         29

# Here, I assign a real name to that level.
named_Species <- forcats::fct_na_value_to_level(sampled_Species, level = "Missing")
table(named_Species)
#> named_Species
#>     setosa versicolor  virginica    Missing 
#>         45         42         34         29

my_iris <- iris
my_iris$na_Species <- na_Species
my_iris$named_Species <- named_Species

head(my_iris)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species na_Species
#> 1          5.1         3.5          1.4         0.2  setosa versicolor
#> 2          4.9         3.0          1.4         0.2  setosa     setosa
#> 3          4.7         3.2          1.3         0.2  setosa     setosa
#> 4          4.6         3.1          1.5         0.2  setosa       <NA>
#> 5          5.0         3.6          1.4         0.2  setosa     setosa
#> 6          5.4         3.9          1.7         0.4  setosa  virginica
#>   named_Species
#> 1    versicolor
#> 2        setosa
#> 3        setosa
#> 4       Missing
#> 5        setosa
#> 6     virginica

tbl_summary(
    my_iris,
    by = na_Species,
    include = c(Sepal.Length:Petal.Width)
)
#> Error in `mutate()`:
#> ℹ In argument: `tbl_stats = pmap(...)`.
#> Caused by error in `pmap()`:
#> ℹ In index: 1.
#> Caused by error in `all_of()`:
#> ! Can't subset columns that don't exist.
#> ✖ Column `stat_4` doesn't exist.

tbl_summary(
    my_iris,
    by = named_Species,
    include = c(Sepal.Length:Petal.Width)
)
```

<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;setosa&lt;/strong&gt;, N = 45&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>setosa</strong>, N = 45<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;versicolor&lt;/strong&gt;, N = 42&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>versicolor</strong>, N = 42<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;virginica&lt;/strong&gt;, N = 34&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>virginica</strong>, N = 34<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Missing&lt;/strong&gt;, N = 29&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>Missing</strong>, N = 29<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">Sepal.Length</td>
<td headers="stat_1" class="gt_row gt_center">5.60 (5.00, 6.10)</td>
<td headers="stat_2" class="gt_row gt_center">5.80 (5.40, 6.30)</td>
<td headers="stat_3" class="gt_row gt_center">5.70 (5.10, 6.50)</td>
<td headers="stat_4" class="gt_row gt_center">6.40 (5.50, 6.70)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Sepal.Width</td>
<td headers="stat_1" class="gt_row gt_center">3.00 (2.80, 3.30)</td>
<td headers="stat_2" class="gt_row gt_center">2.90 (2.70, 3.08)</td>
<td headers="stat_3" class="gt_row gt_center">3.20 (3.00, 3.48)</td>
<td headers="stat_4" class="gt_row gt_center">3.00 (2.90, 3.40)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Petal.Length</td>
<td headers="stat_1" class="gt_row gt_center">4.00 (1.50, 4.90)</td>
<td headers="stat_2" class="gt_row gt_center">4.35 (2.30, 5.08)</td>
<td headers="stat_3" class="gt_row gt_center">4.15 (1.53, 5.08)</td>
<td headers="stat_4" class="gt_row gt_center">4.90 (3.30, 5.50)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Petal.Width</td>
<td headers="stat_1" class="gt_row gt_center">1.30 (0.30, 1.60)</td>
<td headers="stat_2" class="gt_row gt_center">1.30 (0.55, 1.80)</td>
<td headers="stat_3" class="gt_row gt_center">1.25 (0.30, 1.78)</td>
<td headers="stat_4" class="gt_row gt_center">1.80 (1.00, 2.10)</td></tr>
  </tbody>
  &#10;  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="5"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> Median (IQR)</td>
    </tr>
  </tfoot>
</table>
</div>

<sup>Created on 2024-06-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Thank you @DesiQuintans for the post with the great reprex!

I don't think there is a big need to support factors with NA levels in the package. I'll probably just add a check for this in the input data, and return an error if found. This messaging will surely help future users! Thank you!

**Comment by DesiQuintans** [comment]
@ddsjoberg Sounds good!

**Comment by ddsjoberg** [comment]
Thanks again for this. Now tracking this update in another repo FYI
