### ISSUE TITLE
tbl_strata coding issues

### ISSUE THREAD

**Issue by irene9116** [ddsjoberg/gtsummary#1714]
Hello, I'm having a problem with the strata function... 
I managed to get my table with the code 

df_5 %>% 
  group_by(outcome) %>%
  select(outcome, lac, ast, alt, bf, do2, vo2) %>%
      tbl_summary(by = outcome,     
                  type = where(is.numeric) ~ "continuous",
                  statistic = list(all_continuous() ~ "{median} ({p25}, {p75})",        
                                   all_categorical() ~ "{n} / {N} ({p}%)"),  
                  label = list (lac ~ "Lactaate mmol/l",                                           
                                ast ~ "AST (U/I)",
                                alt  ~ "ALT (U/I)",
                                bf  ~ "Blood Flow (l/min)",
                                do2 ~ "DO2 (ml/min)",
                                vo2 ~ "VO2 (ml/min)"),
                  missing = "no")%>%
  add_p() %>% 
  as_gt() %>% 
  gt::tab_header(title = "Table 2")

but when I try to divide the variables among the 4 time points I get an error with my code that I'm not figuring out.

df_5 %>% 
  group_by(outcome) %>%
  select(outcome, time_nrp, lac, ast, alt, bf, do2, vo2) %>%
  mutate(time_nrp = paste(time_nrp, "NRP time point"),
         outcome = factor(outcome, labels = c("Discarded", "Transplanted")))%>%
  tbl_strata(
    strata = time_nrp,
    ~.x %>%
      tbl_summary(by = outcome,     
                  type = where(is.numeric) ~ "continuous",
                  statistic = list(all_continuous() ~ "{median} ({p25}, {p75})",        
                                   all_categorical() ~ "{n} / {N} ({p}%)"),  
                  label = list (lac ~ "Lactaate mmol/l",                                           
                                ast ~ "AST (U/I)",
                                alt  ~ "ALT (U/I)",
                                bf  ~ "Blood Flow (l/min)",
                                do2 ~ "DO2 (ml/min)",
                                vo2 ~ "VO2 (ml/min)"),
                  missing = "no")%>%
      modify_header(all_stat_cols() ~ "**{level}**", label = "**Characteristics**")) %>% 
  add_p() %>% 
  as_gt() %>% 
  gt::tab_header(title = "Table 2")

Error in `mutate()`:
ℹ In argument: `outcome = factor(outcome, labels = c("Discarded",
  "Transplanted"))`.
ℹ In group 1: `outcome = 0`.
Caused by error in `factor()`:
! invalid 'labels'; length 2 should be 1 or 1

if anyone can help,

thanks

**Comment by ddsjoberg** [comment]
I am happy to answer questions. But it's best for the community if they are asked and answered on a public forum for questions. Please post your question to stackoverflow.com. If you include the gtsummary tag, I'll be notified of your post.

Your post must include a **minimal reproducible example**, aka a minimal reprex. A reprex includes both data and code I can run on my machine. If needed, include a mock-up of what you want your results to look like.

Take just a few minutes to review reprex.tidyverse.org for detailed instructions on how to create a reprex.

If you think you've discovered a bug, the same **minimal reproducible example** is required here.

I am going to go ahead and close this issue for now. Please re-open this issue if you wish to make a bug report after you've updated your post with a **minimal reproducible example**.
