### ISSUE TITLE
Bug Report: <Rows are not displayed in the right order, when merging nested regressions using add_glance_table()>

### ISSUE THREAD

**Issue by CharlyMarie** [ddsjoberg/gtsummary#1805]
Hello

This is not a huge bug per se, as the package still works. But the rows are not displayed in the correct order, which needs further cleaning and ordering to make the table as expected.

Description of the problem is: I want to display nested models side by side _and_ use add_glance_table() at the same time to get information about my models. When I do this, all rows are displayed well, but the second model is displayed below the add_glance_table() rows.

Thanks again for your hard work :)

```r
library(gtsummary)
trial <- gtsummary::trial

m1 <- lm(response ~ age, trial) %>%
  tbl_regression() %>%
  add_glance_table()

m2 <- lm(response ~ age + stage, trial) %>%
  tbl_regression() %>%
  add_glance_table()

final_tbl <-
  tbl_merge(tbls = list(m1, m2),
            tab_spanner = c("Model 1", "Model 2"))

final_tbl # Everything is well displayed, but in the wrong order :(
```

**Comment by ddsjoberg** [comment]
Check out the Tips section in the help file. I think that will solve your ordering issue.

https://www.danieldsjoberg.com/gtsummary/reference/add_glance.html

**Comment by CharlyMarie** [comment]
Thank you, it did exactly what it was supposed to.

**Comment by CharlyMarie** [comment]
Thank you, it did exactly what it was supposed to.
