### ISSUE TITLE
Feature request: Can we add an argument to tbl_regression() for testing directional hypotheses / get one-tailed tests?

### ISSUE THREAD

**Issue by CharlyMarie** [ddsjoberg/gtsummary#1813]
Hello

**Is your feature request related to a problem? Please describe.**
Say I have a directional hypothesis: X should _increase_ Y.

**A clear and concise description of the problem.**
Unfortunately, the lm() function in r does not take an argument for testing directional hypotheses. To get one-tailed tests, I would have to do this manually. 

While this is easy to do, it is a bit more complicated to wrap in the tbl_regression() function. A [similar question was asked at SO](https://stackoverflow.com/questions/69516321/is-there-a-way-to-conduct-one-tailed-t-test-using-add-p-or-add-difference-functi) about the tbl_summary() function.

**Describe the solution you'd like to see.**
It would be great to have an argument to tbl_regression, such as (direction = higher/lower/false) to get directional tests and one-tailed p-values.

Thanks :)

**Comment by larmarange** [comment]
Alternatively, if you are able to develop you own tidier, you can pass it to `tbl_regression` with `tidy_fun`.

How would you compute such one-tailed p-values from a lm object?

**Comment by CharlyMarie** [comment]
I would follow [this answer](https://stats.stackexchange.com/questions/325354/if-and-how-to-use-one-tailed-testing-in-multiple-regression), which makes it look quite simple

**Comment by ddsjoberg** [comment]
I like the suggestion from @larmarange to create a tidying function that performs this modification to the results.

I don't _think_ this is something we'll seek to support for all model types, since it's not a common request.

**Comment by larmarange** [comment]
I do agree. The simplest is to create a custom tidier that will call `broom::tidy()` and then recompute p-values.

**Comment by ddsjoberg** [comment]
@CharlyMarie Is it clear how to modify/create a tidying function to implement?

**Comment by ddsjoberg** [comment]
HI @CharlyMarie , This si how i'd approach this using a custom tidier and `tbl_regression()`. Hope it helps.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.9.9.9008'


tidy_lm <- function(x, alternative = c("two.sided", "less", "greater"), ...) {
  if (!inherits(x, "lm")) stop("This function is for `lm()` models only.")
  alternative <- rlang::arg_match(alternative)
  df_tidy <- broom::tidy(x = x, ...)

  if (alternative %in% c("less", "greater")) {
    df_tidy <- 
      df_tidy |> 
      dplyr::rowwise() |> 
      dplyr::mutate(
        p.value =  pt(statistic, broom::glance(x)$df.residual, lower = alternative == "less")
      ) |> 
      dplyr::ungroup()
  }
  
  df_tidy
}

lm(mpg ~ hp + wt, mtcars) |> 
  tidy_lm(alternative = "less")
#> # A tibble: 3 × 5
#>   term        estimate std.error statistic     p.value
#>   <chr>          <dbl>     <dbl>     <dbl>       <dbl>
#> 1 (Intercept)  37.2      1.60        23.3  1          
#> 2 hp           -0.0318   0.00903     -3.52 0.000726   
#> 3 wt           -3.88     0.633       -6.13 0.000000560

lm(mpg ~ hp + wt, mtcars) |> 
  tbl_regression(tidy_fun = tidy_lm) |> 
  as_kable() # convert to kable to display on GH
```

| **Characteristic** | **Beta** |  **95% CI**  | **p-value** |
|:-------------------|:--------:|:------------:|:-----------:|
| hp                 |  -0.03   | -0.05, -0.01 |    0.001    |
| wt                 |   -3.9   |  -5.2, -2.6  |   \<0.001   |

<sup>Created on 2024-07-14 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by CharlyMarie** [comment]
Hi @ddsjoberg. Thank you, I tried to do this but did not succeed. Your function will help me understand the process.
