### ISSUE TITLE
add_p() in tbl_summary loops "cardx" (>= 0.1.0.9067) is required

### ISSUE THREAD

**Issue by johnryan412** [ddsjoberg/gtsummary#1814]
When creating a tbl_summary and using the add_p() it returns 
ℹ The package "cardx" (>= 0.1.0.9067) is required.
✖ Would you like to install it?

I keep hitting 1 to install and it just keeps asking over and over about cardx.  Also tried installing cardx through install.packages.

Without add_p() the function runs fine.

```r
temp<-trial %>%
  tbl_summary(
    by=trt,
    missing="no",
        label=list(
          age ~ "Age (years)"
        ),
    type = list(
      age ~ "continuous"
    )
  ) %>%
  modify_caption("Table 1.  Reprex.") %>%
  add_n() %>%
  add_p()
```

**Comment by ddsjoberg** [comment]
Hi @johnryan412 ! Thank you for the post.

Can you give me a bit more details? When you installed the dev version of gtsummary, the cardx should have been installed at the same time.

Can you close all your R instances (e.g. close all instances of RStudio), and in a fresh R session run `pak::pak("ddsjoberg/gtsummary")`.

Then let me know what you see when running:

```r
packageVersion("gtsummary")
packageVersion("cards")
packageVersion("cardx")
```

I suspect there was an error during the install, which happens sometimes.

**Comment by johnryan412** [comment]
> pak::pak("ddsjoberg/gtsummary")
✔ Loading metadata database ... done                            
                                                                                
ℹ No downloads are needed
✔ 1 pkg + 62 deps: kept 57 [4.7s]
> packageVersion("gtsummary")
[1] ‘1.9.9.9005’
> packageVersion("cards")
[1] ‘0.1.0.9046’
> packageVersion("cardx")
[1] ‘0.1.0’

I tried doing an install.packages("cardx") again and restarting R - still no luck.  Still asking if I'd like to install (>= 0.1.0.9067)

**Comment by ddsjoberg** [comment]
Thanks for the quick response. 

The install _should_ be grabbing {cardx} from GitHub, but you have the CRAN version installed. To install the GH version, please run 

```r
pak::pak("insightsengineering/cards")
pak::pak("insightsengineering/cardx")
```

I'll look into these details and investigate how you got the CRAN version. Thanks!

**Comment by ddsjoberg** [comment]
Thank you for giving the new version a whirl!! MUCH APPRECIATED!
