### ISSUE TITLE
Trying dev (1.9) version 

### ISSUE THREAD

**Issue by oranwutang** [ddsjoberg/gtsummary#1816]
Hi, Daniel and all the members of the team developing this great package!

I've just tried the dev version (1.9...). 

I have tried it by compiling a .rmd (to pdf) document that I use monthly and that heavily uses [gtsummary}, it has like 8 tables with a lot of variables and statistics and significance tests calculated, it also uses the translation to Spanish feature.

I can say that it worked perfectly, the compilation time didn't seem to be affected, and all the (gtsummary-)tables where correctly rendered.

I only found that there is a little difference in the rendering of the tables.

For example:

v 1.7.2
![image](https://github.com/ddsjoberg/gtsummary/assets/6965617/d9922a6a-48d5-4840-83e0-1b9c5777a0b6)

v. 1.9

![image](https://github.com/ddsjoberg/gtsummary/assets/6965617/8ece0eda-47d2-4db6-9b58-78861190c5bf)

As you may see, the dev version puts the "N" in a new line below the label of the column. Is just a minimal change that I think that will be irrelevant for the vast majority of use cases.

Also, after installing the new gtsummary version and before knitting again the  .rmd document, I was forced to update {tinytex}, I don't now if it is related with the gtsummary installation, but I think it is not. I must add that my OS is linux (Ubuntu 22.04) and Tex and LaTex compiling has always been some kind of problematic for me. 

In brief, I think the newest version works correctly.

Besides, as this post is not strictly an "Issue", may I suggest you to create a "Discussions" section in your github site similar to the one that I have seen in the Positron site ([https://github.com/posit-dev/positron/discussions](https://github.com/posit-dev/positron/discussions)) there the beta testers of gtsummary would be able to leave you comments and suggestions for the developing version without creating Issues that need to be solved.

Best regards and best wishes for the new version, I'm eager to see it released!

**Comment by ddsjoberg** [comment]
Gustavo! Thank you for trying it out! Great to "hear" from you :)

> the dev version puts the "N" in a new line below the label of the column

That is expected, I changed the default header to have the line break.

> I was forced to update {tinytex}

I agree, I don't think this has anything to do with gtsummary. We don't touch latex (thankfully!)
