### ISSUE TITLE
Bug Report: `tbl_cross()` fails for html Quarto output under new version of gt package

### ISSUE THREAD

**Issue by remlapmot** [ddsjoberg/gtsummary#1830]
Thanks so much for this amazing package.

I think I see that under the new version of **gt** (0.11.0) that `tbl_cross()` fails for Quarto html output. Interestingly it doesn't fail under rmarkdown html output.

So I am a bit baffled whether this is a Quarto bug, or a **gt** bug, or whether there's something in **gtsummary** that needs a fix, or maybe I've just got this wrong.

I have created an example repo <https://github.com/remlapmot/tbl-cross-reprex>

I used the Example 1 from the `tbl_cross()` helpfile, so my Quarto reprex file is simply

````qmd
---
title: "tbl_cross reprex"
format:
  html:
    embed-resources: true
---

```{r}
library(gtsummary)
# Example 1 ----------------------------------
trial |>
  tbl_cross(row = trt, col = response) |>
  bold_labels()
```
````

The error that I see when rendering is (I have tested under Quarto versions 1.5.54 and 1.6.1)

```
==> quarto preview tbl-cross-reprex.qmd --to html --no-watch-inputs --no-browse



processing file: tbl-cross-reprex.qmd
  |...................................                 |  67% [unnamed-chunk-1]Error in `vapply()`:
! values must be length 1,
 but FUN(X[[1]]) result is length 0
Backtrace:
  1. global .main()
 27. gt:::knit_print.gt_tbl(.)
 29. gt:::as.tags.gt_tbl(x, ...)
 31. gt:::render_as_html(data = x)
 32. gt:::build_data(data = data, context = "html")
 33. gt:::dt_boxhead_build(data = data, context = context)
 34. base::lapply(...)
 35. gt (local) FUN(X[[i]], ...)
 36. gt:::process_text(label, context)
 37. base::vapply(...)



Quitting from lines 9-14 [unnamed-chunk-1] (tbl-cross-reprex.qmd)
                                                                                                            
Execution halted
```

My equivalent R Markdown reprex file, which doesn't fail, is simply

````rmd
---
title: "tbl_cross reprex"
output: html_document
---

```{r}
library(gtsummary)
# Example 1 ----------------------------------
trial |>
  tbl_cross(row = trt, col = response) |>
  bold_labels()
```
````

If you think I should file this in the appropriate **gt** or Quarto repo instead do say.

**Comment by ddsjoberg** [comment]
Hello! Thank you for the report! Much appreciated!

I did a little investigating, and I think it's a regression in the gt's recent release when we request a blank column header be formatted with markdown syntax.

If you don't mind, I will report this to them, since I've been been in recent communication with the dev team?

````
---
title: "tbl_cross reprex"
format:
  html:
    embed-resources: true
---

Example 

```{r}
packageVersion("gt")

mtcars[1:3, 1:2] |> 
  gt::gt() |> 
  gt::cols_label(mpg = gt::md(""))
```
````

**Comment by remlapmot** [comment]
Please do report on to them.

**Comment by ddsjoberg** [comment]
What version of Quarto are you on? I am on v1.4.549

**Comment by ddsjoberg** [comment]
I am going to update and see if that fixes the issue

**Comment by ddsjoberg** [comment]
You can get the Quarto version with `quarto::quarto_version()` FYI

**Comment by ddsjoberg** [comment]
Note, Quarto rendering fails on most recent version as well v1.5.54

**Comment by ddsjoberg** [comment]
Again, thank you so much! I tagged you in the gt post.

I am prepping a gtsummary release now, and expect to send to CRAN in about 2 weeks.

I think I'll add some conditions during the print and remove the `gt::md()` when it's being applied to a blank string.

In the meantime, is it possible to downgrade the gt version?

**Comment by remlapmot** [comment]
> Note, Quarto rendering fails on most recent version as well v1.5.54

I also tested with the pre-release version of Quarto 1.6.1, and the error occurs with that also.

**Comment by remlapmot** [comment]
> Again, thank you so much! I tagged you in the gt post.
> 
> I am prepping a gtsummary release now, and expect to send to CRAN in about 2 weeks.
> 
> I think I'll add some conditions during the print and remove the `gt::md()` when it's being applied to a blank string.
> 
> In the meantime, is it possible to downgrade the gt version?

Super impressive to find the cause so fast.

Yes, in my case I can simply downgrade **gt** for the time being, with

```r
devtools::install_version('gt', '0.10.1', repos = "https://cran.rstudio.com/")
```

**Comment by ddsjoberg** [comment]
@remlapmot I think the change I've made in PR https://github.com/ddsjoberg/gtsummary/pull/1832 should work around the issue. Can you take a look before I merge it?

While this addresses this failure, it looks like there may be another bug to resolve in gt regarding the footnote marker placement. (https://github.com/rstudio/gt/issues/1773)
