### ISSUE TITLE
Bug Report: `tbl_survfit()` fails when `times` is an integer

### ISSUE THREAD

**Issue by DanChaltiel** [ddsjoberg/gtsummary#1867]
Hi,

It seems that `tbl_survfit()` fails when `times` is an integer.
This happens mostly when using the `:` operator.

Here is a reprex:

``` r
library(survival)
library(gtsummary)

tbl_survfit(
  survfit(Surv(ttdeath, death) ~ trt, trial),
  times = 1:2
)
#> Error in `tbl_survfit.list()`:
#> ! The `times` argument must be class <numeric> or empty, not an integer
#>   vector.
```

<sup>Created on 2024-07-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Ah, thank you so much for letting me know about this regression 🤦🏼🤦🏼🤦🏼 😭 

NOTE to self: Check for any numeric checks that should also allow integers in the updated error messaging.

``` r
inherits(1L, "numeric")
#> [1] FALSE
is.numeric(1L)
#> [1] TRUE
```

<sup>Created on 2024-07-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Update `check_class(times, "numeric")` to `check_class(times, c("numeric", "integer"))`, then we should be good to go. Also review the rest of the pkg for `check_class(x, "numeric")` to see if we need to update those as well.

**Comment by ddsjoberg** [comment]
Thanks again for the report @DanChaltiel ! Issue is resolved in dev
