### ISSUE TITLE
Bug Report: Unable to install gtsummary on R 4.1

### ISSUE THREAD

**Issue by fh-mthomson** [ddsjoberg/gtsummary#1870]
I'm seeing an error when trying to install `gtsummary 0.2.0` on Posit Workbench (Linux, R 4.1.3). Any suggestions?

```r
> install.packages('gtsummary')
Installing package into ‘/home/michael.thomson/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/gtsummary_2.0.0.tar.gz'
Content type 'application/x-gzip' length 1261006 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

* installing *source* package ‘gtsummary’ ...
** package ‘gtsummary’ successfully unpacked and MD5 sums checked
** using staged installation
** R
Error in parse(outFile) : 
  /tmp/RtmpyTWnJl/R.INSTALL1225570407f/gtsummary/R/inline_text.R:130:28: unexpected input
129:       cards::get_ard_statistics(cards, .column = "stat_fmt") |>
130:       glue::glue_data(.x = _
                                ^
ERROR: unable to collate and parse R files for package ‘gtsummary’
* removing ‘/home/michael.thomson/R/x86_64-pc-linux-gnu-library/4.1/gtsummary’
* restoring previous ‘/home/michael.thomson/R/x86_64-pc-linux-gnu-library/4.1/gtsummary’
Warning in install.packages :
  installation of package ‘gtsummary’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpW7xyjm/downloaded_packages’
```

Pointing to syntax in https://github.com/ddsjoberg/gtsummary/blob/b4d2c450909c93852225a872437851a70d157c4b/R/inline_text.R#L130

I'm using `glue` 1.7.0 (latest on CRAN).

Interim mitigation: 
```
devtools::install_version('gtsummary', '1.7.2')
```

**Comment by fh-mthomson** [comment]
Oddly, I've confirmed that I _am_ able to install via R 4.4.0 in Posit Workbench. 

I'm seeing 4.1 as supported 🤔 
https://github.com/ddsjoberg/gtsummary/blob/main/DESCRIPTION#L46

**Comment by ddsjoberg** [comment]
HI @fh-mthomson , thanks for the report! 

Originally the plan was to support 4.1 and greater. But doing a bit of investigation, I see that I've added the base R pipe's placeholder (`1:10 |> mean(x = _)`, which bumps the min version required to 4.2. Apologies for the oversight. I'll update the documentation to reflect the correct version requirement.

In the meantime, it's probably easiest to use gtsummary v1.7.2 until the R installation is updated.
