### ISSUE TITLE
Regression in v2.0.0 - slower in general, but some specific elements are much slower

### ISSUE THREAD

**Issue by gorkang** [ddsjoberg/gtsummary#1874]
A specific table was taking a long time with v2.0.0., so I checked which element was causing trouble.

Please see below a simple reprex with the code. I tried it with both versions:

v1.7.2:  
![Screenshot from 2024-07-28 20-46-55](https://github.com/user-attachments/assets/fb475713-4394-4be7-a98e-35a6cad1e041)

v2.0.0
![Screenshot from 2024-07-28 20-51-59](https://github.com/user-attachments/assets/900073a1-af53-41c1-94a9-8259cc11b43a)

---

As you can see, the last table takes 22s with v2.0.0 vs 8s with v1.7.2. In general, though, gtsummary is significantly slower.

```r
DF_final = ggplot2::mpg
OUT = microbenchmark::microbenchmark(
  SIMPLE = gtsummary::tbl_summary(DF_final),

  SIMPLE_CI = gtsummary::tbl_summary(DF_final) |>
    gtsummary::add_ci(),

  SIMPLE_BY = gtsummary::tbl_summary(DF_final, by = class),

  SIMPLE_BY_overall = gtsummary::tbl_summary(DF_final, by = class) |>
    gtsummary::add_overall(),

  SIMPLE_BY_overall_CI = gtsummary::tbl_summary(mpg, by = class) |>
    gtsummary::add_overall() |>
    gtsummary::add_ci(),

  times = 5
)
```

**Comment by ddsjoberg** [comment]
THanks, we're aware and will address.
