### ISSUE TITLE
tbl_summary: sorting of stratify variable

### ISSUE THREAD

**Issue by hr70** [ddsjoberg/gtsummary#1877]
Using package gtsummary version 2.0.0 under R version 4.4.0 (Windows), the order of the stratifying variable gets mixed up sometimes.
I have posted a question on stackoverflow concerning this, the answers suggested there might be a bug:
https://stackoverflow.com/questions/78811916/gtsummary-tbl-summary-sorting-of-stratify-variable

here's an example:
```
tbl_summary(data.frame(x = 1, y = LETTERS[1:9]), by = y) # ok
tbl_summary(data.frame(x = 1, y = LETTERS[1:10]), by = y) # strange
```

**Comment by Melkiades** [comment]
Thanks for posting! This looks like a bug also to me, and it is probably due to using a numerical sort

**Comment by lbdunk** [comment]
I am seeing this even when the by variable does not have 10+ levels:
```
cars_test <- mtcars %>%
  tibble::as_tibble() %>%
  dplyr::mutate(
    mpg20 = dplyr::if_else(mpg >= 20, TRUE, FALSE)
  )

gtsummary::tbl_summary(
  cars_test,
  include = cyl,
  by = mpg20
)

cars_test %>%
  dplyr::count(cyl, mpg20)
```
![image](https://github.com/user-attachments/assets/b82e3974-1204-42e1-8ff7-6abe92318ed8)

The FALSE and TRUE columns are switched.

**Comment by ddsjoberg** [comment]
Thanks for the addition @lbdunk . The `dplyr::count()` function returns results in the order they appear in the data frame. You can optionally add the `sort` argument to order the results, which would put FALSE before TRUE.

``` r
mtcars |> 
  tibble::as_tibble() |> 
  dplyr::mutate(
    mpg20 = dplyr::if_else(mpg >= 20, TRUE, FALSE)
  ) |> 
  dplyr::count(cyl, mpg20, sort = TRUE)
#> # A tibble: 4 × 3
#>     cyl mpg20     n
#>   <dbl> <lgl> <int>
#> 1     8 FALSE    14
#> 2     4 TRUE     11
#> 3     6 FALSE     4
#> 4     6 TRUE      3
```

<sup>Created on 2024-08-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Thanks for the addition @lbdunk . When we sort a logical variable, the FALSE level comes first, so this appears to be expected output?

``` r
sort(c(TRUE, FALSE))
#> [1] FALSE  TRUE
```

<sup>Created on 2024-08-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by lbdunk** [comment]
Sorry if I wasn't clear! It's not the order, they're just wrong:
![image](https://github.com/user-attachments/assets/7ef604c0-ae83-4bdf-b6a8-5e1b62a2a743)
![image](https://github.com/user-attachments/assets/f5951719-478e-4e68-8322-c32b42e4a2b3)

**Comment by ddsjoberg** [comment]
well 🤬 that is serious. I'll address and release an update as quickly as i can. thank you!
