### ISSUE TITLE
Bug Report: Issue during installation coming from: R/inline_text.R

### ISSUE THREAD

**Issue by samuele-mercan** [ddsjoberg/gtsummary#1878]
Encountered problems during the installation of gtsummary:

![inline_text_bug_report](https://github.com/user-attachments/assets/07a76dfc-0775-49b5-b4cc-fc6ff2eae6e2)

Changing the underscore at line 130 with a period resolved the issue.
Changing line 128-130 with this should solve it:

Previous:
`result <-
      cards::get_ard_statistics(cards, .column = "stat_fmt") |>
      glue::glue_data(.x = _, pattern)`
      
New
`result <-
      cards::get_ard_statistics(cards, .column = "stat_fmt") |>
      glue::glue_data(.x = ., pattern)`

**Comment by Melkiades** [comment]
Please avoid screenshots that are not searchable, but use {reprex} package. My installation from main is fine and that is placeholder that comes from {glue}. I think you have some issues with your environment or the installation of {glue}. See the following:
``` r
list(x = "string") |> 
  glue::glue_data(.x = _, "left {x} right")
#> left string right
```

<sup>Created on 2024-07-31 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
@samuele-mercan thanks for the post. The updated version of the package uses the base R pipe and placeholder which require R 4.2. I think that is your installation issue.
