### ISSUE TITLE
footnote number is displayed on own line when rendering in the Posit Cloud

### ISSUE THREAD

**Issue by klh281** [ddsjoberg/gtsummary#1879]
When using the posit cloud, the example table below prints inside the quarto notebook as expected. But when rendered, the footnote number is displayed on its own line (both in the table and in the footnote section).

```r
library(gtsummary)

# summarize the data with our package
table1 <-
  trial |> 
  tbl_summary(include = c(age, grade, response))

table1
```

**Comment by ddsjoberg** [comment]
It sounds like you're describing a bug in the gt package for Quarto. If so, feel free to comment on this post.

https://github.com/rstudio/gt/issues/1773

**Comment by klh281** [comment]
Thank you. Strangely, I don’t experience the problem when producing a gt table — only with gtsummary tables. With kindness, Kim

On Jul 31, 2024, at 1:34 PM, Daniel Sjoberg ***@***.***> wrote:


** Caution: EXTERNAL Sender **


It sounds like you're describing a bug in the gt package for Quarto. If so, feel free to comment on this post.

rstudio/gt#1773<https://github.com/rstudio/gt/issues/1773>

**Comment by ddsjoberg** [comment]
Ahh I see. FYI gtsummary tables are indeed printed with the gt package

**Comment by klh281** [comment]
Okay — I see now. It’s just when utilized with gt::md.

On Jul 31, 2024, at 1:34 PM, Daniel Sjoberg ***@***.***> wrote:


** Caution: EXTERNAL Sender **


It sounds like you're describing a bug in the gt package for Quarto. If so, feel free to comment on this post.

rstudio/gt#1773<https://github.com/rstudio/gt/issues/1773>
