### ISSUE TITLE
Bug Report: Binary variable (1/0) that is all 1s drops new line in tbl_summary

### ISSUE THREAD

**Issue by samrodgersmelnick** [ddsjoberg/gtsummary#1880]
Typically when I want to summarize a binary variable in tbl_summary, the variable name and the value are on the same line in the table. In most recent version, whenever the variable is all 1s (i.e., percentage is 100%), tbl_summary creates a new line under the variable name with a label of 1 and a value of 100%. Is this a bug or is there a new command I have to enter to prevent this from occurring. This bug is not present in other binary variables that do not add up to 100%.

```r
test_data <- tibble(ducks = c(1,1,1,0,0),
                    geese = c(1,1,1,1,1))

test_data |> tbl_summary()
```

**Comment by ddsjoberg** [comment]
Thanks for the post @samrodgersmelnick .

Can you check out the release notes for v2.0.0 as there were some changes related to this topic?

**Comment by samrodgersmelnick** [comment]
Aha. I see. I can hack it by calling the 100% variables as.logical() to get it all on one line. Thanks!
