### ISSUE TITLE
Bug Report: `inline_text(column)` argument doesn't work with fct by level names

### ISSUE THREAD

**Issue by stratopopolis** [ddsjoberg/gtsummary#1883]
Dear Mr. Sjoberg,
dear gtsummary Team,

I am creating a table by tbl_summary and use inline_text(), to use the results. Since an update using the colnames doesn't work, I am required to use "stat_1" instead. However, when I print the whole table, it shows the labels correctly.
This seems to be specific when using by= with factors
```r
 Children2 <- tibble(
      "MTS_specific" = as_factor(sample(c("specific","nonspecific"), 100,T)),
      "Age_INT" = sample(1:18, 100,T),
      "Geschlecht_FCT" = as_factor(sample(c("male","female"), 100,T)),
      "AK_Entl_DT" =sample(1:180, 100,T)
    )

    results2 <- Children2 |>
      select("Diagramm" = MTS_specific, AK_Entl_DT, Age_INT, "Gender"=Geschlecht_FCT) |>
      tbl_summary(by="Diagramm",
              )
    #This works:
    inline_text(results2, variable = "Age_INT", column = "stat_1", pattern= "{median}")

    #This used to work (and is desired, again)
    inline_text(results2, variable = "Age_INT", column = "nonspecific", pattern= "{median}")
```

**Comment by ddsjoberg** [comment]
Thanks for the report, much appreciated. I'll investigate, but may not be able to for 2 weeks. In the meantime, it may be best to use the previous release of the package?

**Comment by ddsjoberg** [comment]
@stratopopolis a fix is in PR https://github.com/ddsjoberg/gtsummary/pull/1885. Can you test with your data?
