### ISSUE TITLE
I can't see the table in viewer 

### ISSUE THREAD

**Issue by maxanes** [ddsjoberg/gtsummary#1892]
I'm using R version 4.4.0 (2024-04-24 ucrt) and the gtsummary package version 2.0. , all packages are updated.
Recently, I've encountered an issue with printing tables in the viewer. Can you provide any advice on how to resolve this problem?

**Comment by Melkiades** [comment]
Please read the template for adding issues. This is a user question and it should be asked in Stackoverflow

**Comment by olivroy** [comment]
FWIW, you should update to R 4.4.1 to fix this problem https://github.com/rstudio/rstudio/issues
