### ISSUE TITLE
Feature request: More adjustments for missing values

### ISSUE THREAD

**Issue by cmboeker** [ddsjoberg/gtsummary#1900]
Hi,
I tried to adapt the missing value row in the tbl_summary() table to my preferences and run into some barriers: I could not display the percentages of the missing data with TWO decimals exactly rounded between the second and the third digit behind the dot. It was also not possible to only italicize the missing values row. Further, the missing values seem not to be recognized as an individual, adjustable element and does not have an internal name like stat_0/stat_1. 
All alternatives, like creating my own function, working with dplyr or glue, did not lead to the desired outcome.

---

Therefore, I suggest to give the missing values an internal name: stat_miss.

And to add these functions:
all_missing()
label_style_missing()
italicize_cells()

As well as, make this possible:
italicize_levels(row = stat_miss)
italicize_cells(row = stat_miss)

---

Thank you for considering these adjustments! In case of questions, do not hesitate to contact me.

FYI, the code I ended up with:

R Studio 4.3.3

table <- df %>% 
  tbl_summary( 
    include = c(Age, Gender, BMI, BMI_categorical, Smoking, Q1_Score, Q2_TotalScore), 
    type = list(Age~'continuous2', BMI~'continuous2', 
                Q1_Score~'continuous2', Q2_TotalScore~'continuous2'), 
    by = Patients_randomisation, 
    missing = "always",
    missing_text = "Missing Values", 
    missing_stat = "{N_miss} ({p_miss}%)", 
    statistic=list(
      all_continuous2() ~ c("{mean} ({sd})", "{median} [{min}, {max}]"), 
      all_categorical() ~ "{n} ({p}%)"), 
    digits = list(
      all_continuous() ~ c(2, 2, 2, 2, 2), 
      all_categorical() ~ c(0,2)), 
    percent = "column" 
    )%>%
  modify_caption(caption = "**Baseline Characteristics**") %>% 
  modify_header(label = "**Variable**") %>% 
  bold_labels() %>% 
  add_n() %>% 
  add_overall() %>% 
  add_p() %>% 
  bold_p() %>% 
  modify_fmt_fun(p.value ~ label_style_pvalue(digits = 3))

**Comment by ddsjoberg** [comment]
At the moment, there is no argument in `tbl_summary()` that will change the formatting style of the percent missing in the Unknown row.

You can do it with a theme. I know it's not the easiest solution, but it's what we've got now. I'll consider the best way to add this type of functionality. To set expectations, this may not be looked at for a few months.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '2.0.0.9005'

# set theme changin the default percent formatting function
list("tbl_summary-fn:percent_fun" = label_style_number(scale = 100, digits = 2)) |> 
  set_gtsummary_theme()

tbl_summary(
  trial, 
  include = c(age, response),
  missing_stat = "{N_miss} ({p_miss}%)"
) |> 
  modify_table_styling(
    columns = label, 
    rows = row_type == "missing",
    text_format = "italic"
  ) |> 
  as_kable()
```

| **Characteristic** | **N = 200** |
|:-------------------|:-----------:|
| Age                | 47 (38, 57) |
| *Unknown*          | 11 (5.50%)  |
| Tumor Response     | 61 (31.61%) |
| *Unknown*          |  7 (3.50%)  |

<sup>Created on 2024-08-13 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
This is a new feature, and I was thinking about it more. You can change the default formatting of the proportion missing if you use named lists to change the formatting functions.

This is not documented anywhere, so we'll need to investigate this at some point and accurate document.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '2.0.0.9005'

tbl_summary(
  trial, 
  include = c(age, response),
  missing_stat = "{N_miss} ({p_miss}%)",
  digits = ~list(p = label_style_number(scale = 100, digits = 2),
                 p_miss = label_style_number(scale = 100, digits = 2))
) |> 
  modify_table_styling(
    columns = label, 
    rows = row_type == "missing",
    text_format = "italic"
  ) |> 
  as_kable()
```

| **Characteristic** | **N = 200** |
|:-------------------|:-----------:|
| Age                | 47 (38, 57) |
| *Unknown*          | 11 (5.50%)  |
| Tumor Response     | 61 (31.61%) |
| *Unknown*          |  7 (3.50%)  |

<sup>Created on 2024-08-13 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by cmboeker** [comment]
Thank you very much for the feedback! Both suggestions worked, however, when I define the digits for the percentages with ~list(), then I cannot define the digits for continuous values anymore. I tried instead to change the digits of all continuous variables with label_style_number, but this did not change the output.

Additionally, I was wondering whether I can also italicize the whole row with missing values, including the cells with the frequencies and percentages?

My current code:
table <- df %>% 
  tbl_summary( 
   include = c(Age, Gender, BMI, BMI_categorical, Smoking, Q1_Score, Q2_TotalScore),
type = list(Age~'continuous2', BMI~'continuous2', Q1_Score~'continuous2', Q2_TotalScore~'continuous2'), 
    by = Patients_randomization, 
    missing = "always", 
    missing_text = "Missing Values", 
    missing_stat = "{N_miss} ({p_miss}%)", 
    statistic=list(
      all_continuous2() ~ c("{mean} ({sd})", "{median} [{min}, {max}]"), 
      all_categorical() ~ "{n} ({p}%)"), 
    digits = ~list(
      p = label_style_number(scale=100, digits=2),
      p_miss = label_style_number(scale=100, digits=2)), 
    percent = "column"
    )%>%
  modify_caption(caption = "**Baseline Characteristics**") %>% 
  modify_header(label = "**Variable**") %>% 
  bold_labels() %>% 
  add_n() %>% 
  add_overall() %>% 
  add_p() %>% 
  bold_p() %>% 
  modify_fmt_fun(p.value ~ label_style_pvalue(digits = 3), 
  all_continuous() ~ label_style_number(digits=2)) %>%
  modify_table_styling(columns = label, rows = row_type == "missing", text_format = "italic") %>%
  modify_footnote(all_stat_cols() ~ NA) %>% 
  as_gt() %>% 
  cols_move_to_end(columns = "stat_0") %>%
  cols_move_to_end(columns = "p.value")

**Comment by ddsjoberg** [comment]
You can italicize all the columns by selecting all the columns in the modify_table_styling() function instead of just the label column
