### ISSUE TITLE
Bug Report: Ruler appears in the wrong place using `tbl_cross()` for Quarto html output

### ISSUE THREAD

**Issue by snhansen** [ddsjoberg/gtsummary#1904]
Consider the example below.

	---
	format: html
	---

	```{r}
	library(gtsummary)
	tbl_cross(trial, row = trt, col = response)
	```
When rendering this with Quarto, the horizontal ruler appears above "Tumor Response" and not below as it should. I'm not sure if this is an issue with `gtsummary`, `gt` og Quarto, so forgive me if I'm posting in the wrong place.

![image](https://github.com/user-attachments/assets/f764221b-32b3-4120-b92b-ad7863c69de0)

This is using `gtsummary` v. 2.0.0 and Quarto v. 1.5.56 on Windows.

**Comment by Melkiades** [comment]
@ddsjoberg, could it be the same issue as #1896?

**Comment by ddsjoberg** [comment]
> @ddsjoberg, could it be the same issue as #1896?

My guess this is just a gt table rendering with Quarto issue.

@snhansen can you test another table just using gt ? I think something like this would be sufficient.

```r
mtcars[1:3, 1:4] |> 
  gt::gt() |> 
  gt::tab_spanner(label = gt::md("Header"), columns = 2:3)
```

**Comment by snhansen** [comment]
@ddsjoberg: You're right, this seems like a gt issue. Your example renders like this:

![image](https://github.com/user-attachments/assets/08dc4f91-f63e-4f06-b2ad-cdab3d1cb64b)

Should I submit a bug report on the Quarto repo?

**Comment by ddsjoberg** [comment]
> Should I submit a bug report on the Quarto repo?

@snhansen I think that is a good plan! I would include an example of what the table looks like when it's rendered interactively, how it looks with R markdown, and then showing the bug with Quarto.

Thanks!
