### ISSUE TITLE
Bug Report: Errors in lapply function tbl_summary after updating

### ISSUE THREAD

**Issue by spiralparagon** [ddsjoberg/gtsummary#1915]
---

After updating to the most recent gtsummary, I'm receiving strange errors when using tbl_summary. I initially believed them to be due to spacing in variable names when using tbl_summary

```r
dems %>% tbl_summary(by = icu_dm_type)

The following errors were returned during tbl_summary():
Error in lapply(text, glue_cmd, .envir = .envir):
! Could not parse cli {} expression: No Diabetes.
Caused by error in parse(text = code, keep.source = FALSE):
! <text>:1:4: unexpected symbol
1: No Diabetes
       ^
```

But after renaming the variable with _ I'm instead receiving

```r
The following errors were returned during `tbl_summary()`:
Error in `lapply(text, glue_cmd, .envir = .envir)`:
! Could not evaluate cli `{}` expression: `No_Diabetes`.
Caused by error in `eval(expr, envir = envir)`:
! object 'No_Diabetes' not found
```

I haven't been able to locate where the problem is occuring

**Comment by ddsjoberg** [comment]
Thank you for the post @spiralparagon !

Can you please create a minimal reproducible example with code+data I can run on my machine. I am not replicating your error.

You can use `dput()` to post a subset of the needed data. If the data is proprietary, you can still use `dput()` but you'll then want to jigger/change the data slightly so that it still illustrates your issue, but is not really your data.

You can then use `reprex::reprex()` to render the example in a fresh environment to ensure the issue is not an interaction with something else in your env. reprex.tidyverse.com

**Comment by chris-rowland86** [comment]
Hello! Thank you for creating and maintaining such an amazing package! I honestly use it daily :)

I'm encountering the same issue. It seems to be specific to when the by variable is a factor as opposed to a character and the variable being summarized is continuous with only NA values for one of the factor levels.

Really appreciate your help!

``` r
# cohort passed to the by variable as character
by_var_as_char <- 
  data.table::data.table(
    by_var = c(
      rep("cohort_1", 3),
      rep("cohort_2", 3)),
    continuous_var = c(
      NA,
      NA,
      NA,
      1,
      2,
      3))

# cohort converted to factor
by_var_as_factor <-
  by_var_as_char[, .(by_var = forcats::as_factor(by_var),
                     continuous_var = continuous_var)]

# gtsummary table still renders when "by variable" is character
# returns warnings for no non-missing arguments to min and max
gtsummary::tbl_summary(
  by_var_as_char,
  by = by_var,
  type = continuous_var ~ "continuous",
  statistic = continuous_var ~ "{min}, {max}"
)
#> The following warnings were returned during `::()`, `gtsummary()`, and
#> `tbl_summary()`:
#> ! For variable `continuous_var` (`by_var = "cohort_1"`) and "min" statistic: no
#>   non-missing arguments to min; returning Inf
#> ! For variable `continuous_var` (`by_var = "cohort_1"`) and "max" statistic: no
#>   non-missing arguments to max; returning -Inf
```

<div id="fsibnuabnt" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;span class='gt_from_md'&gt;&lt;strong&gt;Characteristic&lt;/strong&gt;&lt;/span&gt;"><span class='gt_from_md'><strong>Characteristic</strong></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;span class='gt_from_md'&gt;&lt;strong&gt;cohort_1&lt;/strong&gt;&lt;br /&gt;&#10;N = 3&lt;/span&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><span class='gt_from_md'><strong>cohort_1</strong><br />
N = 3</span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;span class='gt_from_md'&gt;&lt;strong&gt;cohort_2&lt;/strong&gt;&lt;br /&gt;&#10;N = 3&lt;/span&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><span class='gt_from_md'><strong>cohort_2</strong><br />
N = 3</span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">continuous_var</td>
<td headers="stat_1" class="gt_row gt_center">Inf, -Inf</td>
<td headers="stat_2" class="gt_row gt_center">1.00, 3.00</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unknown</td>
<td headers="stat_1" class="gt_row gt_center">3</td>
<td headers="stat_2" class="gt_row gt_center">0</td></tr>
  </tbody>
  &#10;  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="3"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;"><sup>1</sup></span> <span class='gt_from_md'>Min, Max</span></td>
    </tr>
  </tfoot>
</table>
</div>

``` r

# when "by variable" is a factor gtsummary does not render
# instead returns error message that cohort_1 not found
gtsummary::tbl_summary(
  by_var_as_factor,
  by = by_var,
  type = continuous_var ~ "continuous",
  statistic = continuous_var ~ "{min}, {max}"
)
#> The following warnings were returned during `::()`, `gtsummary()`, and
#> `tbl_summary()`:
#> Error in "lapply(text, glue_cmd, .envir = .envir)": ! Could not evaluate cli `{}` expression: `cohort_1`.
#> Caused by error in `eval(expr, envir = envir)`:
#> ! object 'cohort_1' not found
```

<sup>Created on 2024-08-21 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
@chris-rowland86 thank you so much for the reproducible example! Much appreciated! Can you please test the code in the dev version of the package? `pak::pak("ddsjoberg/gtsummary")`

FYI The issue was a difference in how `cli::cli_format()` formatted a factor compared to other types.

**Comment by chris-rowland86** [comment]
Awesome! Thank you! 
I tried testing the dev version of the package but received the following error, when tried running
`pak::pak("ddsjoberg/gtsummary")`

![image](https://github.com/user-attachments/assets/55e489f6-6af2-4db1-9032-cbce8d1f3a09)

Not sure how to interpret this error message?

**Comment by ddsjoberg** [comment]
Hmmm 🤔 I am not sure why that pak code failed. I just tried on my machine and it works. Perhaps try this:

```r
devtools::install_github("ddsjoberg/gtsummary")
```

**Comment by chris-rowland86** [comment]
`pak::pak("ddsjoberg/gtsummary")` worked on my personal computer. 

My company computer has Zscaler security running - not sure if that firewalled the download? 
Anyway, am able to confirm that the dev version of gtsummary no longer causes this issue 😄 

Thank you SO MUCH for all the work you put into this package! It's AMAZINGGGG

**Comment by spiralparagon** [comment]
Thank you @chris-rowland86 for being able to repex something I couldn't without complex hoops, it seems it was the correct issue as the dev-update solved my error. And as always, my sincerest thank you @ddsjoberg for always being so helpful and quick to solve problems for this amazing package. You're the best!
