### ISSUE TITLE
Bug Report: incompatibility of selectors with `broom.helpers`

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#1916]
Variable selectors as `all_categorical()` have been rewritten in `gtsummary` and seems now incompatible with those in `broom.helpers`

``` r
library(gtsummary)

trial |> 
  tbl_summary(
    include = grade,
    statistic = all_categorical() ~ "{p}%"
  ) |> 
  as_kable()
```

| **Characteristic** | **N = 200** |
|:-------------------|:-----------:|
| Grade              |             |
| I                  |     34%     |
| II                 |     34%     |
| III                |     32%     |

``` r

library(broom.helpers)
#> 
#> Attachement du package : 'broom.helpers'
#> Les objets suivants sont masqués depuis 'package:gtsummary':
#> 
#>     all_categorical, all_continuous, all_contrasts, all_dichotomous,
#>     all_interaction, all_intercepts
trial |> 
  tbl_summary(
    include = grade,
    statistic = all_categorical() ~ "{p}%"
  ) |> 
  as_kable()
#> ✖ Cannot use selector 'all_categorical()' in this context.
#> Error in `as_kable()`:
#> ! Error processing `statistic` argument.
#> ! ℹ In argument: `all_categorical()`. Caused by error: ! Invalid syntax
#> ℹ Select among columns "grade"
```

<sup>Created on 2024-08-21 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

How could we update `broom.helpers` to restore compatibilities?

**Comment by ddsjoberg** [comment]
For sure we can update in broom.helpers to make them the same. The updated versions are much simpler, because we can just use `tidyselect::where()`, which was not available when we first wrote these.

**Comment by larmarange** [comment]
However, I guess we also need to update the process of selecting variables?

As I understand, you are note relying anymore on `.formula_list_to_named_list()` but to a new set of selectors functions from `cards`? https://insightsengineering.github.io/cards/latest-tag/reference/process_selectors.html

The selectors in `gtsummary` are looking information in specific `gtsummary` attributes. So I guess it has been to be populated somewhere, no?

**Comment by larmarange** [comment]
Note: to be explored, it seems that the selectors does not work properly in the `include` or `tbl_regression()`

``` r
library(gtsummary)

glm(response ~ age + grade, trial, family = binomial()) |>
  tbl_regression(
    exponentiate = TRUE
  ) |> 
  as_kable()
```

| **Characteristic** | **OR** | **95% CI** | **p-value** |
|:-------------------|:------:|:----------:|:-----------:|
| Age                |  1.02  | 1.00, 1.04 |    0.10     |
| Grade              |        |            |             |
| I                  |   —    |     —      |             |
| II                 |  0.85  | 0.39, 1.85 |     0.7     |
| III                |  1.01  | 0.47, 2.16 |    \>0.9    |

``` r

glm(response ~ age + grade, trial, family = binomial()) |>
  tbl_regression(
    exponentiate = TRUE,
    include = starts_with("Gr")
  ) |> 
  as_kable()
```

| **Characteristic** | **OR** | **95% CI** | **p-value** |
|:-------------------|:------:|:----------:|:-----------:|
| Grade              |        |            |             |
| I                  |   —    |     —      |             |
| II                 |  0.85  | 0.39, 1.85 |     0.7     |
| III                |  1.01  | 0.47, 2.16 |    \>0.9    |

``` r

glm(response ~ age + grade, trial, family = binomial()) |>
  tbl_regression(
    exponentiate = TRUE,
    include = all_categorical()
  ) |> 
  as_kable()
#> Error in if (result$label %in% c("Beta", "exp(Beta)")) {: l'argument est de longueur nulle

glm(response ~ age + grade, trial, family = binomial()) |>
  tbl_regression(
    exponentiate = TRUE,
    include = all_contrasts()
  ) |> 
  as_kable()
#> Error in if (result$label %in% c("Beta", "exp(Beta)")) {: l'argument est de longueur nulle

glm(response ~ age + grade, trial, family = binomial()) |>
  tbl_regression(
    exponentiate = TRUE,
    include = all_contrasts()
  ) |> 
  as_kable()
#> Error in if (result$label %in% c("Beta", "exp(Beta)")) {: l'argument est de longueur nulle

glm(response ~ age + grade, trial, family = binomial()) |>
  broom.helpers::tidy_plus_plus(
    include = all_contrasts()
  )
#> # A tibble: 0 × 18
#> # ℹ 18 variables: term <chr>, variable <chr>, var_label <chr>, var_class <chr>,
#> #   var_type <chr>, var_nlevels <int>, contrasts <chr>, contrasts_type <chr>,
#> #   reference_row <lgl>, label <chr>, n_obs <dbl>, n_event <dbl>,
#> #   estimate <dbl>, std.error <dbl>, statistic <dbl>, p.value <dbl>,
#> #   conf.low <dbl>, conf.high <dbl>
```

<sup>Created on 2024-08-21 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Addressed in  larmarange/broom.helpers#270

Thanks!
