### ISSUE TITLE
Bug Report: `add_ci()` is incorrect for row and cell proportions

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#1927]
Please have a look at the example below. `add_ci()` does not take into account the type of proportion and consider always proportions being column-proportions.

``` r
library(gtsummary)

trial  |> 
  tbl_summary(
    include = stage,
    by = response,
    percent = "column"
  ) |> 
  add_overall() |> 
  add_ci() |> 
  as_kable()
#> 7 missing rows in the "response" column have been removed.
```

| **Characteristic** | **Overall** N = 193 | **95% CI** | **0** N = 132 | **95% CI** | **1** N = 61 | **95% CI** |
|:-------------------|:-------------------:|:----------:|:-------------:|:----------:|:------------:|:----------:|
| T Stage            |                     |            |               |            |              |            |
| T1                 |      52 (27%)       |  21%, 34%  |   34 (26%)    |  19%, 34%  |   18 (30%)   |  19%, 43%  |
| T2                 |      52 (27%)       |  21%, 34%  |   39 (30%)    |  22%, 38%  |   13 (21%)   |  12%, 34%  |
| T3                 |      40 (21%)       |  15%, 27%  |   25 (19%)    |  13%, 27%  |   15 (25%)   |  15%, 38%  |
| T4                 |      49 (25%)       |  20%, 32%  |   34 (26%)    |  19%, 34%  |   15 (25%)   |  15%, 38%  |

``` r

trial  |> 
  tbl_summary(
    include = stage,
    by = response,
    percent = "row"
  ) |> 
  add_overall() |> 
  add_ci() |> 
  as_kable()
#> 7 missing rows in the "response" column have been removed.
```

| **Characteristic** | **Overall** N = 193 | **95% CI** | **0** N = 132 | **95% CI** | **1** N = 61 | **95% CI** |
|:-------------------|:-------------------:|:----------:|:-------------:|:----------:|:------------:|:----------:|
| T Stage            |                     |            |               |            |              |            |
| T1                 |      52 (100%)      |  21%, 34%  |   34 (65%)    |  19%, 34%  |   18 (35%)   |  19%, 43%  |
| T2                 |      52 (100%)      |  21%, 34%  |   39 (75%)    |  22%, 38%  |   13 (25%)   |  12%, 34%  |
| T3                 |      40 (100%)      |  15%, 27%  |   25 (63%)    |  13%, 27%  |   15 (38%)   |  15%, 38%  |
| T4                 |      49 (100%)      |  20%, 32%  |   34 (69%)    |  19%, 34%  |   15 (31%)   |  15%, 38%  |

``` r

trial  |> 
  tbl_summary(
    include = stage,
    by = response,
    percent = "cell"
  ) |> 
  add_overall() |> 
  add_ci() |> 
  as_kable()
#> 7 missing rows in the "response" column have been removed.
```

| **Characteristic** | **Overall** N = 193 | **95% CI** | **0** N = 132 | **95% CI** | **1** N = 61 | **95% CI** |
|:-------------------|:-------------------:|:----------:|:-------------:|:----------:|:------------:|:----------:|
| T Stage            |                     |            |               |            |              |            |
| T1                 |      52 (27%)       |  21%, 34%  |   34 (18%)    |  19%, 34%  |  18 (9.3%)   |  19%, 43%  |
| T2                 |      52 (27%)       |  21%, 34%  |   39 (20%)    |  22%, 38%  |  13 (6.7%)   |  12%, 34%  |
| T3                 |      40 (21%)       |  15%, 27%  |   25 (13%)    |  13%, 27%  |  15 (7.8%)   |  15%, 38%  |
| T4                 |      49 (25%)       |  20%, 32%  |   34 (18%)    |  19%, 34%  |  15 (7.8%)   |  15%, 38%  |

<sup>Created on 2024-08-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Thanks @larmarange ! That is how it was in previous versions too. But we did previously have a note warning users if they requested CIs with row or percent. From your example, it looks like the note didn't make the migration in v2.0. We can add it back.

**Comment by larmarange** [comment]
I completely forgot that point. I do agree that a warning would be relevant here.
