### ISSUE TITLE
Allow dichotomous variables in `tbl_continuous()` ?

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#1931]
There are many tables for analytic results that are the primary result among all subjects on the first line, followed by the same result stratified by another variable. I think allowing a dichotomous variable in `tbl_continuous()` would help this along.

More generally, adding an overall row to all tables could be useful.... 🤔

**Comment by larmarange** [comment]
Allowing to add an overall row to all tbl is a good idea.
