### ISSUE TITLE
knit to Word and spaces issues in version 2.0.1

### ISSUE THREAD

**Issue by fransoju** [ddsjoberg/gtsummary#1932]
I have two issues when I updated gtsummary from version 1.7.1 to 2.0.1.

1. Word can't open the document when I click on the "Knit to Word" option (but Writer can do it) with this simple script  :

```{r}
library(gtsummary)
tbl_summary(iris)
```
2. Moreover, it seems that variables could no more include spaces or accents like "Sepal Length" or "It's a variable" in version 2.0.1.

I had to install back my previous version (that works) with : install_version("gtsummary", version = "1.7.1", repos = "http://cran.us.r-project.org").

Thanks for your answer and your magic package!

**Comment by ddsjoberg** [comment]
HI @fransoju , thanks for the post.

1. I can't replicate this issue. I can open a file using Word
2. Are you referring to Word output only here? Can you make an example that I can run on my machine illustrating the issue you're reporting?


A couple of things to keep in mind:
- gtsummary does not perform the task of table drawing. In the v2.0 release, for Word output, we change the default printer from flextable to gt. 
- If the gt package is not drawing the table in the way you expect, you can explicitly call `gtsummary::as_flex_table()` on an individual table or set `theme_gtsummary_printer('flextable')` at the top of your R markdown/Quarto script.

**Comment by fransoju** [comment]
Thank you for your quick answer !

Yes I can open the document with Writer but not with Word.

But the main problem (the second one) is when I treat variables including spaces in their names :

![Issue with spaces](https://github.com/user-attachments/assets/919199dd-8320-4ba9-9a72-fc64ac22a119)

I don't have this issue with previous version. Any idea ?
Thanks.
Francois

**Comment by ddsjoberg** [comment]
@fransoju I can't replicate the issue with non-syntactic names. Can you make a proper reprex (reprex.tidyverse.com)?

``` r
library(gtsummary)

mtcars |> 
  dplyr::select(mpg, hp, wt) |> 
  dplyr::rename(`M P G` = mpg) |> 
  tbl_uvregression(
    y = `M P G`,
    method = lm
  ) |> 
  as_kable() # convert to kable to display on GH
```

| **Characteristic** | **N** | **Beta** |  **95% CI**  | **p-value** |
|:-------------------|:-----:|:--------:|:------------:|:-----------:|
| hp                 |  32   |  -0.07   | -0.09, -0.05 |   \<0.001   |
| wt                 |  32   |   -5.3   |  -6.5, -4.2  |   \<0.001   |

<sup>Created on 2024-08-27 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by fransoju** [comment]
Your code works well. But when I also rename hp into `H P`, it does not... Plese see :

```` r
``` r
library(gtsummary)

mtcars

mtcars |> 
  dplyr::select(mpg, hp, wt) |> 
  dplyr::rename(`M P G` = mpg) |>
  dplyr::rename(`H P` = hp) |>
  tbl_uvregression(
    y = `M P G`,
    method = lm
  ) |> 
  as_kable() # convert to kable to display on GH

#> Error in `as_kable()`:! There was an error constructing the formula for variable "H P". See
  message below.
✖ <text>:1:13: symbole inattendu 1: `M P G` ~ H P ^
Backtrace:
 1. gtsummary::as_kable(...)

<sup>Created on 2024-08-27 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
````

**Comment by ddsjoberg** [comment]
@fransoju thank you so much for the reprex! This should be taken care of in the dev version of the package. Would you please install it and confirm all is working as expected with your data?

**Comment by fransoju** [comment]
I just tried to install the r-devel version from: https://cloud.r-project.org/web/packages/gtsummary/index.html.
It was built 3 days ago. Is this the correct version ? If yes, it doesn't seem to work any better...
Thank you for your answer!

**Comment by ddsjoberg** [comment]
Ahh, I see. That is the current release from CRAN. You can install the dev version from this GitHub site. Try this code:

```r
pak::pkg_install("ddsjoberg/gtsummary", dependencies = TRUE)
```

Thank you!

**Comment by fransoju** [comment]
Thank you !!! It works !

**Comment by ddsjoberg** [comment]
@fransoju can you install the most recent version of cardx from GH and retry?
https://github.com/insightsengineering/cardx

**Comment by fransoju** [comment]
It works. Thanks !
