### ISSUE TITLE
Bug Report: Number formatting issues with `tbl_cross()`

### ISSUE THREAD

**Issue by DesiQuintans** [ddsjoberg/gtsummary#1943]
I've found these two issues in `tbl_cross()`:

1. The `digits =` argument doesn't seem to be respected. In the reprex below, I try to add 4 decimal places to the `{p}` statistic item with no effect.
2. In `statistic =`, the `{n}` flag is correctly styled with a big mark ("1,011") and so is `{N_nonmiss}`, but `{N}` is not (comes out as "3000").

Thank you for your work on an excellent package <3

``` r
library(gtsummary)

sessionInfo()$otherPkgs$gtsummary$Version
#> [1] "2.0.1"

set.seed(12345)

my_data <- 
    data.frame(
        states = sample(c(state.name[1:4], NA), size = 3000, replace = TRUE),
        fruits = sample(c("Apple", "Tomato"),   size = 3000, replace = TRUE)
    )

tbl_cross(
    my_data,
    row       = states,
    col       = fruits,
    statistic = "{n}/{N_nonmiss}/{N} ({p}%)",
    digits    = c(0, 0, 0, 4)
)
```

<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings gt_spanner_row">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col" id=""></th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" scope="colgroup" id="&lt;span class='gt_from_md'&gt;fruits&lt;/span&gt;">
        <span class="gt_column_spanner"><span class='gt_from_md'>fruits</span></span>
      </th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="2" colspan="1" scope="col" id="&lt;span class='gt_from_md'&gt;Total&lt;/span&gt;"><span class='gt_from_md'>Total</span></th>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;span class='gt_from_md'&gt;Apple&lt;/span&gt;"><span class='gt_from_md'>Apple</span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;span class='gt_from_md'&gt;Tomato&lt;/span&gt;"><span class='gt_from_md'>Tomato</span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">states</td>
<td headers="stat_1" class="gt_row gt_center"><br /></td>
<td headers="stat_2" class="gt_row gt_center"><br /></td>
<td headers="stat_0" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Alabama</td>
<td headers="stat_1" class="gt_row gt_center">303/1,504/3000 (10%)</td>
<td headers="stat_2" class="gt_row gt_center">329/1,496/3000 (11%)</td>
<td headers="stat_0" class="gt_row gt_center">632/3,000/3000 (21%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Alaska</td>
<td headers="stat_1" class="gt_row gt_center">313/1,504/3000 (10%)</td>
<td headers="stat_2" class="gt_row gt_center">273/1,496/3000 (9.1%)</td>
<td headers="stat_0" class="gt_row gt_center">586/3,000/3000 (20%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Arizona</td>
<td headers="stat_1" class="gt_row gt_center">322/1,504/3000 (11%)</td>
<td headers="stat_2" class="gt_row gt_center">288/1,496/3000 (9.6%)</td>
<td headers="stat_0" class="gt_row gt_center">610/3,000/3000 (20%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Arkansas</td>
<td headers="stat_1" class="gt_row gt_center">279/1,504/3000 (9.3%)</td>
<td headers="stat_2" class="gt_row gt_center">308/1,496/3000 (10%)</td>
<td headers="stat_0" class="gt_row gt_center">587/3,000/3000 (20%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unknown</td>
<td headers="stat_1" class="gt_row gt_center">287/1,504/3000 (9.6%)</td>
<td headers="stat_2" class="gt_row gt_center">298/1,496/3000 (9.9%)</td>
<td headers="stat_0" class="gt_row gt_center">585/3,000/3000 (20%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Total</td>
<td headers="stat_1" class="gt_row gt_center">1,504/1,504/3000 (50%)</td>
<td headers="stat_2" class="gt_row gt_center">1,496/1,496/3000 (50%)</td>
<td headers="stat_0" class="gt_row gt_center">3,000/3,000/3000 (100%)</td></tr>
  </tbody>
  &#10;  
</table>

<sup>Created on 2024-08-30 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
@DesiQuintans ! Thank you so much for reporting and the reproducible example. This should be fixed in dev. Can you take a look using your data?
