### ISSUE TITLE
Feature request: Add an ordinal variable type to tbl_summary()

### ISSUE THREAD

**Issue by BorgeJorge** [ddsjoberg/gtsummary#1947]
For example, I have a count variable that represents the number of times each patient was hospitalized in a given followup period, but I'd like to present it as the proportion and n of patients that had 0, 1, 2, or 3+ hospitalizations in the period. I can of course top-code the count variable and convert it to a factor, but I'd love it if gtsummary did the work for me! (I think this might be the only thing I miss about SAS having moved to R: the ability to specify a format like this in one fell swoop.)

Thanks for a great package!

**Comment by ddsjoberg** [comment]
Hi @BorgeJorge , Thanks for the post and the request.

In this case, the API to add this would probably be more complicated than it's worth to add to `tbl_summary()`. The {forcats} package usually contains all the helpers needed for these types of modifications (and implements them better than we could!). But i don't think it has a function to do what you're asking. If I were in your situation, i would write a function (similar to the one below) and keep it in your personal R package or a team R package, so you can easily reference adn use it in your work. (Then you won't be missing SAS 😉 )

``` r
library(gtsummary)

set.seed(1123)
df <- dplyr::tibble(ord = sample.int(n = 4, size = 100, replace = TRUE))

# create a function for ordinal categories
fct_ordinal_cat <- function(x, threshold) {
  # we expect x to be a vector of positive integers, and threshold to be a single threshold
  factor(
    ifelse(x < threshold, as.character(x), paste0(threshold, "+")),
    levels = c(seq_len(threshold - 1L), paste0(threshold, "+"))
  )
}

df |> 
  dplyr::mutate(ord_cat = fct_ordinal_cat(ord, 3L)) |> 
  tbl_summary() |> 
  as_kable()
```

| **Characteristic** | **N = 100** |
|:-------------------|:-----------:|
| ord                |             |
| 1                  |  25 (25%)   |
| 2                  |  23 (23%)   |
| 3                  |  33 (33%)   |
| 4                  |  19 (19%)   |
| ord_cat            |             |
| 1                  |  25 (25%)   |
| 2                  |  23 (23%)   |
| 3+                 |  52 (52%)   |

<sup>Created on 2024-09-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by BorgeJorge** [comment]
Perfect, thank you so much Daniel!

All best.
