### ISSUE TITLE
rOpenSci To Do

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#196]
We're considering submitting to rOPenSci.  Here's what we'd need to do before submission.  Entire process outlined in bookdown https://devguide.ropensci.org/building.html

- [x] 1.1.2 Creating metadata for your package:  Use the {codemetar} package @ddsjoberg 
- [x] 1.7 Documentation: Every function needs `@return` @ddsjoberg 
- [x] 1.7 Documentation: Add `#' @noRd` to internal functions @ddsjoberg 
- [x] 1.8.2 Automatic deployment of the documentation website @ddsjoberg 
    - this might be done...need to check next time we push to master
- [x] 1.8.3 Branding of authors: Add links to person websites for authors @ddsjoberg 
- [x] 1.9 Authorship: Add ORCID IDs @ddsjoberg 
- [x] 1.10 Testing: Figure out the {codecovr} error (checks are failing in codecovr, but not in `devtools::check()`) @karissawhiting 
- [x] 1.10 Testing: Check good practices with https://github.com/MangoTheCat/goodpractice/ @ddsjoberg 
- [x] Ensure this version plays well with BOTH tidyr 1.0 and the current version.

**Comment by karissawhiting** [comment]
Great idea! Need help with 1.7, or 1.10, or do you have it covered?

**Comment by ddsjoberg** [comment]
I put our names by the items we can work on!

**Comment by ddsjoberg** [comment]
Submitting Author: Daniel Sjoberg (@ddsjoberg)  
Repository: gtsummary
Version submitted:   TODO: submit the patch version or not?
Editor: TBD  
Reviewer 1: TBD  
Reviewer 2: TBD  
Archive: TBD  
Version accepted: TBD   

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: gtsummary
Title: Presentation-Ready Data Summary and Analytic Result
    Tables
Version: 1.1.1.9003
Authors@R: 
    c(person(given = "Daniel D.",
             family = "Sjoberg",
             role = c("aut", "cre"),
             email = "danield.sjoberg@gmail.com",
             comment = c(ORCID = "0000-0003-0862-2018")),
      person(given = "Margie",
             family = "Hannum",
             role = "aut",
             comment = c(ORCID = "0000-0002-2953-0449")),
      person(given = "Karissa",
             family = "Whiting",
             role = "aut",
             comment = c(ORCID = "0000-0002-4683-1868")),
      person(given = "Emily C.",
             family = "Zabor",
             role = "aut",
             comment = c(ORCID = "0000-0002-1402-4498")),
      person(given = "Michael",
             family = "Curry",
             role = "ctb",
             comment = c(ORCID = "0000-0002-0261-4044")),
      person(given = "Esther",
             family = "Drill",
             role = "ctb",
             comment = c(ORCID = "0000-0002-3315-4538")),
      person(given = "Jessica",
             family = "Flynn",
             role = "ctb",
             comment = c(ORCID = "0000-0001-8310-6684")))
Description: Creates presentation-ready tables summarizing data
    sets, regression models, and more. The code to create the tables is
    concise and highly customizable. Data frames can be summarized with
    any function, e.g. mean(), median(), even user-written functions.
    Regression models are summarized and include the reference rows for
    categorical variables. Common regression models, such as logistic
    regression and Cox proportional hazards regression, are automatically
    identified and the tables are pre-filled with appropriate column
    headers. The package is enhanced when the {gt} package is installed.
    Use this code to install: 'remotes::install_github("rstudio/gt")'.
License: MIT + file LICENSE
URL: http://www.danieldsjoberg.com/gtsummary/
BugReports: https://github.com/ddsjoberg/gtsummary/issues
Depends: 
    R (>= 3.4)
Imports: 
    broom (>= 0.5.1),
    broom.mixed (>= 0.2.3),
    crayon (>= 1.3.4),
    dplyr (>= 0.7.8),
    glue (>= 1.3.0),
    knitr (>= 1.21),
    magrittr (>= 1.5),
    purrr (>= 0.3.0),
    rlang (>= 0.3.1),
    stringr (>= 1.3.1),
    survival,
    tibble (>= 2.0.1),
    tidyr (>= 0.8.2),
    tidyselect (>= 0.2.5)
Suggests: 
    car (>= 3.0.2),
    covr (>= 3.2.1),
    curl (>= 3.3),
    geepack (>= 1.2.1),
    ggplot2 (>= 3.1.0),
    Hmisc (>= 4.2.0),
    lme4 (>= 1.1.18.1),
    remotes (>= 2.1.0),
    rmarkdown (>= 1.11),
    spelling (>= 2.0),
    testthat (>= 2.1.0),
    usethis (>= 1.5.0)
Enhances:
    gt (>= 0.1.0)
VignetteBuilder: 
    knitr
Encoding: UTF-8
Language: en-US
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 6.1.1
```


## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [x] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):


-   Who is the target audience and what are scientific applications of this package?  

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

## Technical checks

Confirm each of the following by checking the box.  This package:

- [ ] does not violate the Terms of Service of any service it interacts with. 
- [ ] has a CRAN and OSI accepted license.
- [ ] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme). 
- [ ] includes [documentation with examples for all functions](https://ropensci.github.io/dev_guide/building.html#documentation).
- [ ] contains a vignette with examples of its essential functions and uses.
- [ ] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [ ] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [ ] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:

<details>
 <summary>JOSS Options</summary>  

  - [ ] The package has an **obvious research application** according to [JOSS's definition](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)  
  
</details>

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:  

<details>
<summary>MEE Options</summary>  

- [ ] The package is novel and will be of interest to the broad readership of the journal. 
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [ ] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by ddsjoberg** [comment]
OK, submitted.  :)
