### ISSUE TITLE
Add 'profile' and 'bootstrap' methods to the add_ci function

### ISSUE THREAD

**Issue by dariorrr** [ddsjoberg/gtsummary#1963]
It would be great to add the option to specify the methods 'profile' and 'bootstrap' (in addition to 'wald') for the calculation of the confidence intervals in the `add_ci` function. This would make it more consistent with the options of the the `confint` function. 

Thank you

**Comment by ddsjoberg** [comment]
Thanks for the post @dariorrr 

A bootstrap method is currently underway. you can follow progress here: https://github.com/insightsengineering/cardx/pull/205

Can you provide a code example for calculating the profile CI and a reference?  If it does not require an additional dependency, we can consider adding it to the package.

**Comment by dariorrr** [comment]
Hi Daniel, 

To be more specific, what I am referring here are the CI from multilevel models calculated with lme4. What I a suggesting to implement in tbl_summary is the possibility to select the methods as done in the function `lme4::confint.merMod()`. 
```
confint(object, parm, level = 0.95,
	method = c("profile", "Wald", "boot"), zeta,
	nsim = 500,
        boot.type = c("perc","basic","norm"),
        FUN = NULL, quiet = FALSE,
	oldNames = TRUE, ...)
```

Reference: https://search.r-project.org/CRAN/refmans/lme4/html/confint.merMod.html

At the moment, tbl_summary add CI as if the method is set to 'Wald'. At least this what it looks like in my recent experience.

Thank you

**Comment by dariorrr** [comment]
Hi Daniel,

The issue I raised is wrong as it relates to the modelsummary package and
not to gtsummary. I am so sorry for the inconvenience.

Thank you for your great work

Best

Dario

**Comment by ddsjoberg** [comment]
If it helps, here's how to implement bootstrap https://www.danieldsjoberg.com/gtsummary/reference/custom_tidiers.html

And here's an example on how to use Wald CIs (which is easily modifiable to any method you prefer) https://www.danieldsjoberg.com/gtsummary/articles/gallery.html#wald-ci
