### ISSUE TITLE
Bug Report: Variable with all NA levels causes error

### ISSUE THREAD

**Issue by szimmer** [ddsjoberg/gtsummary#1973]
Per [discussion on Posit Community forum](https://forum.posit.co/t/why-tbl-summary-doesnt-work/191189), a error is yielded when a column consists entirely of missing data. This should be handled more gracefully

----------

``` r
library(tidyverse)
library(gtsummary)

set.seed(8675309)

mydf <- tibble(
  Group=rep(1:4, each=20),
  CatValid=as.factor(sample(letters[1:4], 80, replace=TRUE)),
  CatNA=factor(NA)
)

mydf %>%
  select(-CatNA) %>%
  tbl_summary(by="Group")
```

<div id="dxixguhicn" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="label"><span class='gt_from_md'><strong>Characteristic</strong></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="stat_1"><span class='gt_from_md'><strong>1</strong><br />
N = 20</span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="stat_2"><span class='gt_from_md'><strong>2</strong><br />
N = 20</span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="stat_3"><span class='gt_from_md'><strong>3</strong><br />
N = 20</span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="stat_4"><span class='gt_from_md'><strong>4</strong><br />
N = 20</span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">CatValid</td>
<td headers="stat_1" class="gt_row gt_center"><br /></td>
<td headers="stat_2" class="gt_row gt_center"><br /></td>
<td headers="stat_3" class="gt_row gt_center"><br /></td>
<td headers="stat_4" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    a</td>
<td headers="stat_1" class="gt_row gt_center">5 (25%)</td>
<td headers="stat_2" class="gt_row gt_center">3 (15%)</td>
<td headers="stat_3" class="gt_row gt_center">4 (20%)</td>
<td headers="stat_4" class="gt_row gt_center">4 (20%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    b</td>
<td headers="stat_1" class="gt_row gt_center">4 (20%)</td>
<td headers="stat_2" class="gt_row gt_center">8 (40%)</td>
<td headers="stat_3" class="gt_row gt_center">6 (30%)</td>
<td headers="stat_4" class="gt_row gt_center">4 (20%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    c</td>
<td headers="stat_1" class="gt_row gt_center">8 (40%)</td>
<td headers="stat_2" class="gt_row gt_center">4 (20%)</td>
<td headers="stat_3" class="gt_row gt_center">6 (30%)</td>
<td headers="stat_4" class="gt_row gt_center">6 (30%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    d</td>
<td headers="stat_1" class="gt_row gt_center">3 (15%)</td>
<td headers="stat_2" class="gt_row gt_center">5 (25%)</td>
<td headers="stat_3" class="gt_row gt_center">4 (20%)</td>
<td headers="stat_4" class="gt_row gt_center">6 (30%)</td></tr>
  </tbody>
  &#10;  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="5"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;"><sup>1</sup></span> <span class='gt_from_md'>n (%)</span></td>
    </tr>
  </tfoot>
</table>
</div>

``` r

mydf %>%
  tbl_summary(by="Group")
#> Error in names(df) <- repaired_names(c(names2(dimnames(x)), n), repair_hint = TRUE, : 'names' attribute [3] must be the same length as the vector [2]
```

<sup>Created on 2024-09-13 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Thank you @szimmer for the clear and minimal reprex!

We had already planned to add better messaging for factors with NA levels, but hadn't noted factors with _no_ levels. This will be updated here FYI https://github.com/insightsengineering/cards/issues/255

Having all NAs is ok when the levels of the factor are available.

``` r
library(gtsummary)
set.seed(8675309)

mydf <- dplyr::tibble(
  Group=rep(1:4, each=20),
  CatValid=as.factor(sample(letters[1:4], 80, replace=TRUE)),
  CatNA=factor(NA, levels = c("Hello", "There"))
)

tbl_summary(mydf, by = Group) |> 
  bold_labels() |> 
  as_kable()
```

| **Characteristic** | **1** N = 20 | **2** N = 20 | **3** N = 20 | **4** N = 20 |
|:-------------------|:------------:|:------------:|:------------:|:------------:|
| **CatValid**       |              |              |              |              |
| a                  |   5 (25%)    |   3 (15%)    |   4 (20%)    |   4 (20%)    |
| b                  |   4 (20%)    |   8 (40%)    |   6 (30%)    |   4 (20%)    |
| c                  |   8 (40%)    |   4 (20%)    |   6 (30%)    |   6 (30%)    |
| d                  |   3 (15%)    |   5 (25%)    |   4 (20%)    |   6 (30%)    |
| **CatNA**          |              |              |              |              |
| Hello              |   0 (NA%)    |   0 (NA%)    |   0 (NA%)    |   0 (NA%)    |
| There              |   0 (NA%)    |   0 (NA%)    |   0 (NA%)    |   0 (NA%)    |
| Unknown            |      20      |      20      |      20      |      20      |

<sup>Created on 2024-09-13 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
NOTE FOR gtsummary DEVS: Once the {cards} update is complete, add a unit test for the messaging in this situation.

**Comment by ddsjoberg** [comment]
Thanks again for the report. Here's what the error message users will see now.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '2.0.2'

mydf <- dplyr::tibble(
  Group=rep(1:4, each=20),
  CatValid=as.factor(sample(letters[1:4], 80, replace=TRUE)),
  CatNA=factor(NA)
)

mydf |> 
  tbl_summary(by="Group")
#> Error in `tbl_summary()`:
#> ! Factors with empty "levels" attribute are not allowed, which was
#>   identified in column "CatNA".
```

<sup>Created on 2024-09-27 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
