### ISSUE TITLE
Feature request: <Adding stats rows to the categorical variable summaries, specifically N_nonmissing / N_obs>

### ISSUE THREAD

**Issue by barnesmas** [ddsjoberg/gtsummary#1984]
I want to add the number of non-missing responses/number of total responses as a separate row on the top or the bottom of each variable in the tbl_summary.  I can do it the continuous2() variables by adding it as an element to the statistic argument, but this doesn't work for the categorical variables. It all has to be in one element, which clutters the table too much.

```
#This works:
tbl_summary(...,
type = list(all_continuous() ~ "continuous2", all_categorical() ~ "categorical"),
statistic = list(all_continuous() ~ 
                       c("{median} ({p25}, {p75})", 
                         "{mean} ± {sd}",
                         "{N_nonmiss} / {N_obs}") )

# this does not work 
tbl_summary(...,
type = list(all_continuous() ~ "continuous2", all_categorical() ~ "categorical"),                        
statistic = list(all_continuous() ~ 
                       c("{median} ({p25}, {p75})", 
                         "{mean} ± {sd}",
                         "{N_nonmiss} / {N_obs}"),
                     all_categorical() ~ c("{n} ({p}%)", 
                                           "{N_nonmiss} / {N_obs}"))
```
Error in `mutate()`:
ℹ In argument: `stat_display = assign_stat_display(...)`.
Caused by error in `pmap()`:
ℹ In index: 3.
Caused by error:
! The statistic requested for variable 'category' cannot have length greater than 1.
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by ddsjoberg** [comment]
Dear @barnesmas , thanks for the post.

You can get what you're after. It may be a bit confusing because these options are all phrased as reporting missing rather than non-missing.


``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '2.0.2.9002'

trial |> 
  tbl_summary(
    include = c(age, grade),
    by = trt, 
    type = all_continuous() ~ "continuous2",
    statistic = all_continuous() ~ c("{mean} ({sd})", "{median} ({p25}, {p75})"),
    missing = "always",
    missing_text = "n",
    missing_stat = "{N_nonmiss}"
  ) |> 
  bold_labels() |> 
  as_kable()
```

| **Characteristic** | **Drug A** N = 98 | **Drug B** N = 102 |
|:-------------------|:-----------------:|:------------------:|
| **Age**            |                   |                    |
| Mean (SD)          |      47 (15)      |      47 (14)       |
| Median (Q1, Q3)    |    46 (37, 60)    |    48 (39, 56)     |
| n                  |        91         |         98         |
| **Grade**          |                   |                    |
| I                  |     35 (36%)      |      33 (32%)      |
| II                 |     32 (33%)      |      36 (35%)      |
| III                |     31 (32%)      |      33 (32%)      |
| n                  |        98         |        102         |

<sup>Created on 2024-09-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by barnesmas** [comment]
Awesome! Is there a way to move the "missing" row to the top of each variable?

**Comment by ddsjoberg** [comment]
Yes, you can do that too. gtsummary tables are just printed data frames at the end of the day, so it's simple to make modifications like this by re-ordering the rows. See below.

It is on our radar to make this modification simpler. You can subscribe to updates for this issue to be notified when that change is implemented. https://github.com/ddsjoberg/gtsummary/issues/1952

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '2.0.2.9002'

trial |> 
  tbl_summary(
    include = c(age, grade),
    by = trt, 
    type = all_continuous() ~ "continuous2",
    statistic = all_continuous() ~ c("{mean} ({sd})", "{median} ({p25}, {p75})"),
    missing = "always",
    missing_text = "n / N",
    missing_stat = "{N_nonmiss} / {N_obs}"
  ) |> 
  # re-order the rows to put the n/N below the label
  modify_table_body(
    function(.x) .x |> 
      mutate(
        .by = variable,
        across(everything(), ~.[order(row_type != "label", row_type != "missing")])
      )
  ) |> 
  bold_labels() |> 
  as_kable()
```

| **Characteristic** | **Drug A** N = 98 | **Drug B** N = 102 |
|:-------------------|:-----------------:|:------------------:|
| **Age**            |                   |                    |
| n / N              |      91 / 98      |      98 / 102      |
| Mean (SD)          |      47 (15)      |      47 (14)       |
| Median (Q1, Q3)    |    46 (37, 60)    |    48 (39, 56)     |
| **Grade**          |                   |                    |
| n / N              |      98 / 98      |     102 / 102      |
| I                  |     35 (36%)      |      33 (32%)      |
| II                 |     32 (33%)      |      36 (35%)      |
| III                |     31 (32%)      |      33 (32%)      |

<sup>Created on 2024-09-17 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
