### ISSUE TITLE
Failure with dev glue

### ISSUE THREAD

**Issue by jennybc** [ddsjoberg/gtsummary#1989]
This issue is inspired by doing revdep checks for glue. In the next release of glue, which is _very soon_, `glue::glue()` will error when `.envir` is not an actual environment. `.envir` has always been documented to be an environment and I've been working to make this actually true.

I last did revdep checks for this in December 2023 and I opened issue or PRs everywhere that I could. So gtsummary's usage of this pattern must have arisen more recently.

`glue_data()` *does* officially accept something "list-ish" as `.x`. So you should switch to `glue_data(.x = list_ish_thing, ...)` as opposed to `glue(.envir = list_ish_thing, ...)` in many places here in this package. I haven't made a PR since there seem to be so many locations that need tweaking; I don't trust myself to get this right, quickly, in someone else's package.

Relevant links in glue:

https://github.com/tidyverse/glue/issues/308
https://github.com/tidyverse/glue/commit/e2b74ff17704261b5a7da25b4ebd2dec94740764
https://github.com/tidyverse/glue/issues/341

Here's what I'm currently seeing for gtsummary in glue's revdep checks:
https://github.com/tidyverse/glue/blob/main/revdep/problems.md#gtsummary

I think this breakage has some other indirect effects on gtsummary's revdeps, such as gtreg (cc @shannonpileggi ).

**Comment by ddsjoberg** [comment]
Thank you @jennybc for the heads up!

**Comment by ddsjoberg** [comment]
Welp, that was a surprisingly large number of off-label uses of `glue(.envir)` 😬 😆

**Comment by jennybc** [comment]
Ha! Yeah that's why you didn't get a PR from me 😄

**Comment by jennybc** [comment]
glue 1.8.0 has been accepted on CRAN now.

**Comment by ddsjoberg** [comment]
Thank you @jennybc for the update!  Much appreciated
