### ISSUE TITLE
Feature request: Integrate a 'censored' variable type into the tbl_summary function.

### ISSUE THREAD

**Issue by eusebe** [ddsjoberg/gtsummary#1993]
The `tbl_summary` function is incredibly useful for generating descriptive tables, even if the variables to describe are of different types. 

Unless I'm mistaken, the only types of variables the function supports are continuous and categorical variables. For example: 

```
trial |>
    select(age, grade, response, trt) |>
    tbl_summary(
        by = trt,
        label = list(age = "Patient Age"),
        type = all_continuous() ~ "continuous2",
        statistic = all_continuous() ~ c("{median} ({p25}, {p75})", "{min}, {max}")
    )
```
![image](https://github.com/user-attachments/assets/20603845-6b22-461f-b02d-59021ca57801)

When the variable to describe is censored, one must then turn to the more specialized `tbl_survfit` function. For example:

```
library(survival)
tbl_survfit(
    survfit(Surv(ttdeath, death) ~ trt, trial),
    times = c(12, 24),
    label_header = "**{time} Month**"
)
# or
tbl_survfit(
    trial,
    y = "Surv(ttdeath, death)",
    include = c(trt),
    times = c(12, 24), 
    label_header = "**{time} Month**"
)
```
![image](https://github.com/user-attachments/assets/2542aa60-674f-4408-9a62-72a7d9266a7d)

It would be really cool to allow censored variables to be handled by `tbl_summary`. For example, it would allow something like this:

```
trial$overall_survival <- Surv(trial$ttdeath, trial$death)
trial |>
    select(age, grade, response, overall_survival, trt) |>
    tbl_summary(
        by = trt,
        label = list(age = "Patient Age", overall_survival = "Overall survival"),
        type = all_continuous() ~ "continuous2",
        statistic = list(
            all_continuous() ~ c("{median} ({p25}, {p75})", "{min}, {max}")
            all_censored() ~ c("{t12} Month", "{t24} Month")
        )
    )
```
to produce something like this:

![image](https://github.com/user-attachments/assets/649fa05e-bb45-417c-bfd9-cf5edb6a2bb5)

(sorry for the poor quality of the last image).

**Comment by ddsjoberg** [comment]
Dear @eusebe , thanks for the post and the detailed example.

We probably won't include this natively in `tbl_summary()`, unfortunately. But we've just released functionality to add arbitrary statistics, which include survival results. We do this by leveraging Analysis Results Datasets. I've included an example below. If this is something you need regularly, you could functionalize is and re-use it.

``` r
library(survival)
library(cards)
library(gtsummary)
packageVersion("cards")
#> [1] '0.2.2.9009'

# first build your standard table
tbl_standard <- 
  trial |> 
  tbl_summary(by = trt, include = c(age, grade))

# build a table for the survival component
tbl_survival <- 
  # build an ARD for survival
  survfit(Surv(ttdeath, death) ~ trt, trial) |> 
  cardx::ard_survival_survfit(times = c(12, 24)) |> 
  # update the formatting function (requires dev version of cards, or you could do this via `mutate()`)
  cards::update_ard_fmt_fn(
    stat_names = c("estimate", "conf.low", "conf.high"),
    fmt_fn = label_style_sigfig(digits = 2, scale = 100)
  ) |> 
  dplyr::mutate(context = "categorical") |> # forcing the summary to a "category-like" format
  tbl_ard_summary(
    by = trt,
    label = list(time = "Survival Probability"),
    statistic = time ~ "{estimate}% (95% CI {conf.low}%, {conf.high}%)"
  )

tbl_survival |> 
  as_kable()
```

| **Characteristic**   |      **Drug A**       |      **Drug B**       |
|:---------------------|:---------------------:|:---------------------:|
| Survival Probability |                       |                       |
| 12                   | 91% (95% CI 85%, 97%) | 86% (95% CI 80%, 93%) |
| 24                   | 47% (95% CI 38%, 58%) | 41% (95% CI 33%, 52%) |

``` r

# stack the tables
list(tbl_standard, tbl_survival) |> 
  tbl_stack() |> 
  as_kable()
#> Column headers among stacked tables differ. Headers from the first table are
#> used.
#> ℹ Use `quiet = TRUE` to suppress this message.
```

| **Characteristic**   |   **Drug A** N = 98   |  **Drug B** N = 102   |
|:---------------------|:---------------------:|:---------------------:|
| Age                  |      46 (37, 60)      |      48 (39, 56)      |
| Unknown              |           7           |           4           |
| Grade                |                       |                       |
| I                    |       35 (36%)        |       33 (32%)        |
| II                   |       32 (33%)        |       36 (35%)        |
| III                  |       31 (32%)        |       33 (32%)        |
| Survival Probability |                       |                       |
| 12                   | 91% (95% CI 85%, 97%) | 86% (95% CI 80%, 93%) |
| 24                   | 47% (95% CI 38%, 58%) | 41% (95% CI 33%, 52%) |

<sup>Created on 2024-09-25 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
