### ISSUE TITLE
Bug Report: add_p() for tbl_survfit() when using argument type does not provide p-value

### ISSUE THREAD

**Issue by modosist** [ddsjoberg/gtsummary#2002]
Hi. It seems that `add_p` does not compute p-values for `tbl_survfit` when using `type` argument (value `survival` does not work as well; however, not passing `type` argument works fine). I'm using `gtsummary=2.0.2`.

```r
library(survival)
library(gtsummary)
library(tidyverse)

tbl_survfit(
  survfit(Surv(ttdeath, death) ~ trt, trial),
  times = c(12, 24),
  type="risk"
) %>%
    add_p()
```

The code does not crash, but gives error

```
The following errors were returned during `add_p()`:
✖ For variable `trt` and "p.value" statistic: subscript out of bounds
```

The `gtsummary` table with risk probabilities does not have p-value (although the column is present).

**Comment by ddsjoberg** [comment]
Dear @modosist , thank you for the report. much appreciated! the issue is now corrected on github and will go to cran in a couple of weeks.
