### ISSUE TITLE
all_categorical Calculation of percentage error

### ISSUE THREAD

**Issue by feilong695** [ddsjoberg/gtsummary#2007]
![9173338](https://github.com/user-attachments/assets/7224a871-3635-44e1-8494-4cc48216d31e)

Here's my code.

tb2 <- tbl_svysummary(NHANES_design,  
                      by = SMQ020,include = c( "RIDAGEYR", "RIAGENDR", 
                                                          "RIDRETH1", "DMDEDUC2", "DMDMARTL", "BMXBMI", 
                                                          "ALQ101", "LBDLYMNO", "LBXWBCSI"),
                      statistic = list(all_continuous()  ~ "{mean}± ({sd})",
                                       all_categorical() ~ "{n_unweighted} ({p}%)"),
                      missing = 'no') %>% 
  add_overall() %>%
  add_p(
    test = list(
      all_continuous() ~ "svy.t.test",
      all_categorical() ~ "svy.wald.test"
    )
  )  %>%
  add_n(statistic = "{N_nonmiss_unweighted}",
        col_label = "**N**",
        footnote = TRUE) 
That's why the different numbers have the same percentage which is obviously not true.

**Comment by ddsjoberg** [comment]
@feilong695 : please keep a few things in mind
1. The best place to look for help with the package is on stackoverflow.com, where a community of users can help you.
2. It seems you did not read the prompt before posting here: if you think you've found a bug you must include a minimal reproducible example (i.e. code+data we can all run on our machine that illustrates your issue).
3. That said, in your example, you are mixing unweighted counts and weighted percentages. Review the help file for details on appropriate use and if you think you still have a bug, please update your post with a minimal reproducible example and re-open this issue. https://www.danieldsjoberg.com/gtsummary/reference/tbl_svysummary.html#statistic-argument

**Comment by feilong695** [comment]
@ddsjoberg :Thank you for your patient response and guidance. I apologize for confusing weighted and unweighted p-values.
