### ISSUE TITLE
`glue_data()` error in gtsummary due to update in the glue package

### ISSUE THREAD

**Issue by robertprince** [ddsjoberg/gtsummary#2011]
tbl_summary() not working in gtsummary version 2.0.2

---

tbl_summary() not working since upgrading to gtsummary version 2.0.2

```r
library(gtsummary)

# summarize the data with our package
table1 <-
  trial |> 
  tbl_summary(include = c(age, grade, response))
```
Error in `dplyr::mutate()`:
ℹ In argument: `stat = as.character(...)`.
Caused by error in `glue_data()`:
! is.environment(.envir) is not TRUE
Run `rlang::last_trace()` to see where the error occurred.

**Comment by robby81** [comment]
can reproduce the same thing

**Comment by lvjustice** [comment]
Also getting the same error
`Error in `dplyr::mutate()`:
ℹ In argument: `df_stats = list(...)`.
Caused by error in `dplyr::mutate()`:
ℹ In argument: `stat = map(...)`.
Caused by error in `glue_data()`:
! is.environment(.envir) is not TRUE`

**Comment by ddsjoberg** [comment]
Hi All, Thank you for the posts.

Yesterday afternoon a new version the {glue} package was released, which included a breaking change that affected {gtsummary}. I think you all have installed {glue} in the last ~12 hours. The {gtsummary} package has already been updated to handle the change, and it will be available on CRAN in a few days.

In the meantime, you have a couple of options.
1. Install the latest version of gtsummary from GitHub with `pak::pkg_install("ddsjoberg/gtsummary", dependencies = TRUE)`.
2. Install the previous version of {glue} with `devtools::install_version("glue", version = "1.7.0")`

**Comment by adrientaudiere** [comment]
Thanks @ddsjoberg, for the reactivity and the solutions!

**Comment by barnesmas** [comment]
Yes Thanks! This was my issue as well.

**Comment by robertprince** [comment]
Thank you very much for resolving the issue in record time @ddsjoberg ! It allowed me to deliver my tables on time.

**Comment by lvjustice** [comment]
Thank you @ddsjoberg  - your your super quick response and for a wonderful R package

**Comment by mcomas** [comment]
Thank you very much!

**Comment by RHuebner1972** [comment]
> Hi All, Thank you for the posts.
> 
> Yesterday afternoon a new version the {glue} package was released, which included a breaking change that affected {gtsummary}. I think you all have installed {glue} in the last ~12 hours. The {gtsummary} package has already been updated to handle the change, and it will be available on CRAN in a few days.
> 
> In the meantime, you have a couple of options.
> 
> 1. Install the latest version of gtsummary from GitHub with `pak::pkg_install("ddsjoberg/gtsummary", dependencies = TRUE)`.
> 2. Install the previous version of {glue} with `devtools::install_version("glue", version = "1.7.0")`

Good morning!

I attempted both of these suggestions above. 

I have:
   R 4.4.1
   glue 1.8.0
   and the latest version of gtsummary from the link above.

Question: 

  Do I have to downgrade the glue version to 1.7.0 -- that is, do I have to apply both of these options above to get it to work? I'm trying to get a report out today that uses this amazing package.

Thanks!

**Comment by ddsjoberg** [comment]
@RHuebner1972 either option in isolation is sufficient

**Comment by ddsjoberg** [comment]
The updated version of the package is now on CRAN. Thanks for your patience.
