### ISSUE TITLE
Bug Report: tbl_summary not working after updating to R 4.4.1

### ISSUE THREAD

**Issue by SaraSousi** [ddsjoberg/gtsummary#2026]
---

tbl_summary and the other functions have been working fine, I update to the latest version of R, from 4.0.3 to 4.4.1 and the same code does not work and get the error below. I've been using the same code and re-running it and now it does not work, all dependent packages are up to date and loaded. 

```r
all_matched_data_TKR %>% select(AgeAcc) %>% tbl_summary()
#> Error in `dplyr::mutate()`:
#> ℹ In argument: `stat = as.character(...)`.
#> Caused by error in `glue_data()`:
#> ! is.environment(.envir) is not TRUE
```

**Comment by ddsjoberg** [comment]
Dear @SaraSousi , 

Thank you for your post. Please update your post with a reproducible example, aka a reprex. A reprex includes both data and code I can run on my machine that replicates your finding. Make the example as short as possible: the minimal amount of code to reproduce your finding and nothing more.

Take just a few minutes to review [reprex.tidyverse.org](https://reprex.tidyverse.org/) for detailed instructions on how to create a reprex.

I am going to go ahead and close this issue for now. But please do re-open the issue after you've added your reproducible example.

**Comment by ddsjoberg** [comment]
While creating your reproducible example and if you are updating your packages, please keep this issue in mind as well (https://github.com/ddsjoberg/gtsummary/issues/2011). FYI a new version of gtsummary is going to CRAN later today.
