### ISSUE TITLE
Bug Report: `add_ci.tbl_svysummary()` incorrect levels order

### ISSUE THREAD

**Issue by BLalloue** [ddsjoberg/gtsummary#2036]
Hello,

I think there's a problem managing the level order for factors in `add_ci.tbl_svysummary()`. The confidence intervals are not aligned on the lines corresponding to the point estimates and it seems that the same order (alphabetical order ?) is systematically used to display the CIs, even if the factor has levels ordered differently.

Here's a repex with first the normal behavior for a tibble and then the abnormal behavior on a survey object.

``` r
library(dplyr)
library(forcats)
library(survey)
library(gtsummary)

set.seed("123")

# generate sample data
testdata <- tibble(
    strata = sample(1:3, 100, replace = TRUE),
    factor = sample(c("A", "B", "C", "D", "E", NA), 100, replace = TRUE)
) %>% 
    mutate(
        factor = as.factor(factor),
        factor2 = fct_relevel(factor, "E", "A", "D"),
        fpc = case_when(
            strata == 1 ~ 100,
            strata == 2 ~ 200,
            strata == 3 ~ 300
        )
    )

# add_ci() for tbl_summary respects the level order specific to each factor -> WORKS
testdata %>% 
    tbl_summary(include = c(factor, factor2)) %>% 
    add_ci()
```

<div id="kaysjuvmkk" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="label"><span class='gt_from_md'><strong>Characteristic</strong></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="stat_0"><span class='gt_from_md'><strong>N = 100</strong></span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="ci_stat_0"><span class='gt_from_md'><strong>95% CI</strong></span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">factor</td>
<td headers="stat_0" class="gt_row gt_center"><br /></td>
<td headers="ci_stat_0" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    A</td>
<td headers="stat_0" class="gt_row gt_center">12 (15%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">8.5%, 26%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    B</td>
<td headers="stat_0" class="gt_row gt_center">18 (23%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">15%, 34%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    C</td>
<td headers="stat_0" class="gt_row gt_center">13 (17%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">9.5%, 27%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    D</td>
<td headers="stat_0" class="gt_row gt_center">17 (22%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">14%, 33%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    E</td>
<td headers="stat_0" class="gt_row gt_center">18 (23%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">15%, 34%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unknown</td>
<td headers="stat_0" class="gt_row gt_center">22</td>
<td headers="ci_stat_0" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">factor2</td>
<td headers="stat_0" class="gt_row gt_center"><br /></td>
<td headers="ci_stat_0" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    E</td>
<td headers="stat_0" class="gt_row gt_center">18 (23%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">15%, 34%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    A</td>
<td headers="stat_0" class="gt_row gt_center">12 (15%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">8.5%, 26%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    D</td>
<td headers="stat_0" class="gt_row gt_center">17 (22%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">14%, 33%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    B</td>
<td headers="stat_0" class="gt_row gt_center">18 (23%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">15%, 34%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    C</td>
<td headers="stat_0" class="gt_row gt_center">13 (17%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">9.5%, 27%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unknown</td>
<td headers="stat_0" class="gt_row gt_center">22</td>
<td headers="ci_stat_0" class="gt_row gt_center"><br /></td></tr>
  </tbody>
  &#10;  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="3"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> <span class='gt_from_md'>n (%)</span></td>
    </tr>
    <tr>
      <td class="gt_footnote" colspan="3"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span> <span class='gt_from_md'>CI = Confidence Interval</span></td>
    </tr>
  </tfoot>
</table>
</div>

``` r

# add_ci() for tbl_svysummary wrongly keeps the same level order for both factors (alphabetical order?) -> BUG ?
testsurvey <- svydesign(ids = ~ 1, strata = ~ strata, data = testdata)
#> Warning in svydesign.default(ids = ~1, strata = ~strata, data = testdata): No
#> weights or probabilities supplied, assuming equal probability
testsurvey %>% 
    tbl_svysummary(include = c(factor, factor2)) %>% 
    add_ci()
```

<div id="uzitfrqeyt" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="label"><span class='gt_from_md'><strong>Characteristic</strong></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="stat_0"><span class='gt_from_md'><strong>N = 100</strong></span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="ci_stat_0"><span class='gt_from_md'><strong>95% CI</strong></span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">factor</td>
<td headers="stat_0" class="gt_row gt_center"><br /></td>
<td headers="ci_stat_0" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    A</td>
<td headers="stat_0" class="gt_row gt_center">12 (15%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">8.8%, 25%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    B</td>
<td headers="stat_0" class="gt_row gt_center">18 (23%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">15%, 34%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    C</td>
<td headers="stat_0" class="gt_row gt_center">13 (17%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">9.8%, 27%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    D</td>
<td headers="stat_0" class="gt_row gt_center">17 (22%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">14%, 33%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    E</td>
<td headers="stat_0" class="gt_row gt_center">18 (23%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">15%, 34%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unknown</td>
<td headers="stat_0" class="gt_row gt_center">22</td>
<td headers="ci_stat_0" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">factor2</td>
<td headers="stat_0" class="gt_row gt_center"><br /></td>
<td headers="ci_stat_0" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    E</td>
<td headers="stat_0" class="gt_row gt_center">18 (23%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">8.8%, 25%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    A</td>
<td headers="stat_0" class="gt_row gt_center">12 (15%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">15%, 34%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    D</td>
<td headers="stat_0" class="gt_row gt_center">17 (22%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">9.8%, 27%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    B</td>
<td headers="stat_0" class="gt_row gt_center">18 (23%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">14%, 33%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    C</td>
<td headers="stat_0" class="gt_row gt_center">13 (17%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">15%, 34%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unknown</td>
<td headers="stat_0" class="gt_row gt_center">22</td>
<td headers="ci_stat_0" class="gt_row gt_center"><br /></td></tr>
  </tbody>
  &#10;  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="3"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> <span class='gt_from_md'>n (%)</span></td>
    </tr>
    <tr>
      <td class="gt_footnote" colspan="3"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span> <span class='gt_from_md'>CI = Confidence Interval</span></td>
    </tr>
  </tfoot>
</table>
</div>

``` r
# Same thing when using fpc (note how for level E of `factor2` the CI does not contains the estimate) -> BUG ?
testsurvey2 <- svydesign(ids = ~ 1, strata = ~ strata, fpc = ~fpc, data = testdata)
testsurvey2 %>% 
    tbl_svysummary(include = c(factor, factor2)) %>% 
    add_ci()
```

<div id="uhugtrqabq" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="label"><span class='gt_from_md'><strong>Characteristic</strong></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="stat_0"><span class='gt_from_md'><strong>N = 600</strong></span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="ci_stat_0"><span class='gt_from_md'><strong>95% CI</strong></span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">factor</td>
<td headers="stat_0" class="gt_row gt_center"><br /></td>
<td headers="ci_stat_0" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    A</td>
<td headers="stat_0" class="gt_row gt_center">69 (15%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">8.9%, 25%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    B</td>
<td headers="stat_0" class="gt_row gt_center">99 (22%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">14%, 32%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    C</td>
<td headers="stat_0" class="gt_row gt_center">78 (17%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">10%, 28%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    D</td>
<td headers="stat_0" class="gt_row gt_center">90 (20%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">13%, 30%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    E</td>
<td headers="stat_0" class="gt_row gt_center">115 (26%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">17%, 37%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unknown</td>
<td headers="stat_0" class="gt_row gt_center">149</td>
<td headers="ci_stat_0" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">factor2</td>
<td headers="stat_0" class="gt_row gt_center"><br /></td>
<td headers="ci_stat_0" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    E</td>
<td headers="stat_0" class="gt_row gt_center">115 (26%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">8.9%, 25%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    A</td>
<td headers="stat_0" class="gt_row gt_center">69 (15%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">14%, 32%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    D</td>
<td headers="stat_0" class="gt_row gt_center">90 (20%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">10%, 28%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    B</td>
<td headers="stat_0" class="gt_row gt_center">99 (22%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">13%, 30%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    C</td>
<td headers="stat_0" class="gt_row gt_center">78 (17%)</td>
<td headers="ci_stat_0" class="gt_row gt_center">17%, 37%</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unknown</td>
<td headers="stat_0" class="gt_row gt_center">149</td>
<td headers="ci_stat_0" class="gt_row gt_center"><br /></td></tr>
  </tbody>
  &#10;  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="3"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> <span class='gt_from_md'>n (%)</span></td>
    </tr>
    <tr>
      <td class="gt_footnote" colspan="3"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span> <span class='gt_from_md'>CI = Confidence Interval</span></td>
    </tr>
  </tfoot>
</table>
</div>

<sup>Created on 2024-10-09 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessionInfo()
#> R version 4.4.1 (2024-06-14 ucrt)
#> Platform: x86_64-w64-mingw32/x64
#> Running under: Windows 10 x64 (build 19044)
#> 
#> Matrix products: default
#> 
#> 
#> locale:
#> [1] LC_COLLATE=French_France.utf8  LC_CTYPE=French_France.utf8   
#> [3] LC_MONETARY=French_France.utf8 LC_NUMERIC=C                  
#> [5] LC_TIME=French_France.utf8    
#> 
#> time zone: Europe/Paris
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] grid      stats     graphics  grDevices utils     datasets  methods  
#> [8] base     
#> 
#> other attached packages:
#> [1] gtsummary_2.0.3 survey_4.4-2    survival_3.7-0  Matrix_1.7-0   
#> [5] forcats_1.0.0   dplyr_1.1.4    
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_4.4.1    tidyselect_1.2.1  reprex_2.1.1      Rcpp_1.0.13      
#>  [5] xml2_1.3.6        tidyr_1.3.1       splines_4.4.1     yaml_2.3.10      
#>  [9] fastmap_1.2.0     lattice_0.22-6    R6_2.5.1          commonmark_1.9.2 
#> [13] cards_0.3.0       generics_0.1.3    knitr_1.48        backports_1.5.0  
#> [17] cardx_0.2.1       tibble_3.2.1      DBI_1.2.3         pillar_1.9.0     
#> [21] rlang_1.1.4       utf8_1.2.4        broom_1.0.7       xfun_0.48        
#> [25] sass_0.4.9        fs_1.6.4          cli_3.6.3         withr_3.0.1      
#> [29] magrittr_2.0.3    digest_0.6.37     rstudioapi_0.16.0 markdown_1.13    
#> [33] lifecycle_1.0.4   vctrs_0.6.5       evaluate_1.0.0    glue_1.8.0       
#> [37] mitools_2.4       gt_0.11.1.9000    fansi_1.0.6       rmarkdown_2.28   
#> [41] purrr_1.0.2       tools_4.4.1       pkgconfig_2.0.3   htmltools_0.5.8.1
```

</details>

Thank you for all your work and for your help!

**Comment by ayogasekaram** [comment]
Hey @ddsjoberg! I investigated this issue and I believe the reorder comes from gtsummary. I ran ard_categorical_ci() from cardx on the `factor` and `factor2`, the level orders are correct and the ci values match the levels.

**Comment by ddsjoberg** [comment]
Thank you @BLalloue for reporting!! Also, thank you @ayogasekaram for looking into the source.

I took a look and the `group_map()` in `brdg_add_ci()` is re-ordering the survey results alphabetically for survey results. This happens to survey data and not typical data frames because the survey package does not retain variables types (like factors) when the CIs are calculated, and so what was formerly a factor gets sorted like a character value.  There are two ways to approach a solution:
1. In {cardx}, assess whether the original class/type of a variable can be forced back onto the variable.
2. Update the `group_map()` section of code to ensure re-ordering is reset after calculation.

I think the first proposal would be best, but also the most difficult because it would also involve updates to the `ard_categorical()` survey S3 method. So we'll go with the second.

**Comment by ddsjoberg** [comment]
Thank you @BLalloue for the lovely reproducible example! If you could please install the dev version of gtsummary from github and check your use case with the update to ensure the bug is fixed, it would be greatly appreciated.

**Comment by BLalloue** [comment]
Thank you very much for your reply and quick update!
I no longer have any problems either with my repex or with my use case when I use the dev version.
