### ISSUE TITLE
Bug Report: <Describe bug> tbl_summary label argument does not work by default

### ISSUE THREAD

**Issue by Baky-cisse** [ddsjoberg/gtsummary#2040]
---

After the new updates, the label argument of tbl_summary no long retrieves the label of the column in the data table by default, even if the column is labelled. 

```r
var_label(bdd1$class_age ) <- "Classe d'âge"

desc1 <- bdd1 %>% 
  tbl_summary(, include = c(class_age),
              statistic = list(all_continuous() ~ "{median} ({min}-{max}) | {mean} ({sd})",
                               all_categorical() ~ "{n} ({p}%)"),
              digits = list(all_continuous() ~ 2, all_categorical() ~ c(0,1)), sort = all_categorical() ~ "frequency",
              missing_text = "(Données Manquantes)") %>% bold_labels()

desc1 
```

**Comment by ddsjoberg** [comment]
Thank you for your post. Please update your post with a reproducible example, aka a reprex. A reprex includes both data and code I can run on my machine that replicates your finding. Make the example as short as possible: the minimal amount of code to reproduce your finding and nothing more.

Take just a few minutes to review [reprex.tidyverse.org](https://reprex.tidyverse.org/) for detailed instructions on how to create a reprex.

I am going to go ahead and close this issue for now. But please do re-open the issue after you've added your reproducible example.
