### ISSUE TITLE
Feature request: tbl_survfit

### ISSUE THREAD

**Issue by kzkzmr** [ddsjoberg/gtsummary#2041]
Thanks for the great package.
It would be very beneficial if the following features were implemented.

set.seed(1234)
n <- 20
x <- rbinom(n, 1, 0.5)
y0 <- rexp(n)
y1 <- y0 * exp(0.5 + x)
y2 <- y0 * exp(0.5 - 2 * x)
e <- numeric(n) + 1

sf1 <- survfit(Surv(y1, e) ~ x)
sf2 <- survfit(Surv(y2, e) ~ x)

summary(sf1, times = 1:2)
tbl_survfit(sf1, times = 1:2)

summary(sf2, times = 1:2, extend = TRUE)
#Want to show "— (—, —)" at all time point for x = 1 but error returns
tbl_survfit(sf2, times = 1:2)

**Comment by ddsjoberg** [comment]
Thanks for the suggestion @kzkzmr 

If you install the development version of the cardx package, you'll now see this represented in the output. For these out-of-observation estimates, the survival package returns an estimate of 0 which you will see in the table as well.

``` r
packageVersion("cardx") # https://github.com/insightsengineering/cardx
#> [1] '0.2.1.9009'
library(gtsummary)
library(survival)

set.seed(1234)
n <- 20
x <- rbinom(n, 1, 0.5)
y0 <- rexp(n)
y1 <- y0 * exp(0.5 + x)
y2 <- y0 * exp(0.5 - 2 * x)
e <- numeric(n) + 1

sf1 <- survfit(Surv(y1, e) ~ x)
sf2 <- survfit(Surv(y2, e) ~ x)

summary(sf2, times = 1:2, extend = TRUE)
#> Call: survfit(formula = Surv(y2, e) ~ x)
#> 
#>                 x=0 
#>  time n.risk n.event survival std.err lower 95% CI upper 95% CI
#>     1      4       5    0.444   0.166        0.214        0.923
#>     2      0       4    0.000     NaN           NA           NA
#> 
#>                 x=1 
#>  time n.risk n.event survival std.err lower 95% CI upper 95% CI
#>     1      0      11        0     NaN           NA           NA
#>     2      0       0        0     NaN           NA           NA
tbl_survfit(sf2, times = 1:2) |> 
  as_kable()
```

| **Characteristic** |   **Time 1**   | **Time 2** |
|:-------------------|:--------------:|:----------:|
| x                  |                |            |
| 0                  | 44% (21%, 92%) | 0% (—, —)  |
| 1                  |   0% (—, —)    | 0% (—, —)  |

<sup>Created on 2024-10-25 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
