### ISSUE TITLE
Feature request: add and add_p() and add_q() methods to tbl_strata()

### ISSUE THREAD

**Issue by cruzki** [ddsjoberg/gtsummary#2042]
I am trying to compare the answers of a survey with two stratus by different variables. I am successfully manage to get the table with all the indicators I would like for each of the stratus but I would love to be able to put in the same table the result of a p-value between the overall columns of the two stratus the same way I can do for each strata using add_p() and add_q() (namely, inside the tbl_summary()). See below for an example of what I get:

I obviously am able to get the results just using the by="${strata}" parameter in tbl_summary() but I would love to be able to get everything in the same table. Namely, to have these two screenshot "cbinded" (please note that the overall numbers does not agree because NA in some variables).

![imagen](https://github.com/user-attachments/assets/43dbe835-2ede-4d4c-8782-202538872195)
![imagen](https://github.com/user-attachments/assets/3d0f5f3b-8b9b-4c69-bb03-3a801b3542ad)

The code should be something like:

tbl_strata(
    strata = ${variable to stratification},
    .tbl_fun =
      ~ .x |>
        tbl_summary(by = ${factor to assess}, missing = "ifany") |>
        modify_header(label = "**Dimension**") |>
        add_overall() |>  
        add_p()  |>
        add_q() , 
    .header = "**{strata}**, N = {n}"
  )  |> add_p() |> add_q()

**Comment by ddsjoberg** [comment]
Thanks for the post @cruzki 

We unfortunately cannot include `add_p()` methods for `tbl_strata()` results. The details for that are here: https://github.com/ddsjoberg/gtsummary/issues/1629

Regarding your desire to "cbind" the two tables, I think `tbl_merge()` will do just that. 

Happy porgramming!
