### ISSUE TITLE
Bug Report: New line in header not present in Quarto PDF output

### ISSUE THREAD

**Issue by 10b14224cc** [ddsjoberg/gtsummary#2047]
Consider the following MWE:

````
---
title: "Title"
format:
  pdf: default
---

\newpage

# Section 1

```{r}
#| echo: false
#| warning: false
#| label: tbl-label
#| tbl-cap: "**Table caption**"
library(tidyverse)
library(gtsummary)
trial2 <- trial |> select(trt, age, grade)
trial2 |>
  tbl_summary(by = trt) |>
  add_p()
```
````

Compile it to html with quarto:
```
quarto render main.qmd --to html
```

You get:
![image](https://github.com/user-attachments/assets/4137d841-443b-4437-a714-17bf0e7b7e2e)

Not compile to PDF:
```
quarto render main.qmd --to pdf
```

The number of observations are in the same line of the column headers:
![image](https://github.com/user-attachments/assets/8ceadc62-b72b-424f-9e54-dacc61d29917)

This clutters the column headers and we risk that the page width is not enough to hold the table width.

Even worse, the HTML "preview" is not representative of the PDF output anymore.

**Comment by ddsjoberg** [comment]
Thanks for the post @10b14224cc 

The gt package doesn't respect the standard line breaker. So we are stripping it when exporting to PDF.

See the note here: https://www.danieldsjoberg.com/gtsummary/reference/as_gt.html#note

**Comment by 10b14224cc** [comment]
So I have to open a bug report against the gt package?

**Comment by ddsjoberg** [comment]
They are working on a universal linebreak syntax for all output types now in the gt package (https://github.com/rstudio/gt/issues/1767).

We're only removing the linebreak `\n`, you can try injecting a latex-specific break. I don't personally need PDF output, so I haven't tested it much, but maybe something like `modify_header(all_stat_cols() ~ "**{level}**  \linebreak N = {n}")`. But I am not sure latex code injected like this is evaluated or if gt escapes it.

Another alternative is to export your table to PDF via kableExtra with `as_kable_extra()`, which does respect the line break but comes with other limitations. For the moment, there is no silver bullet that is the absolute best table-drawing package for all output types (although, I think gt will be there soon).

**Comment by 10b14224cc** [comment]
Can't we just put the `N` in another row?

**Comment by 10b14224cc** [comment]
The PR I submitted allows you to do this:

````
---
title: "Title"
format:
  pdf:
    header-includes:
      \usepackage{makecell}
---

\newpage

# Section 1

```{r}
#| echo: false
#| output: false
library(tidyverse)
library(gtsummary)
```

```{r}
#| label: tbl-label
#| echo: false
#| output: true
#| tbl-cap: "**Table caption**"
trial2 <- trial |> select(trt, age, grade)
trial2 |>
  tbl_summary(by = trt) |>
  modify_header(all_stat_cols() ~ " \\makecell{\\textbf{[level]}\\\\N = [n]}",
                glue_open="[", 
                glue_close="]") |>
  add_p() |>
  knitr::kable(format="pipe", escape=FALSE)
```
````

and obtain this:

![image](https://github.com/user-attachments/assets/8e4dcf19-ba15-4929-9de5-fc880d26e588)

Still not perfect since there are "NA" in the "Grade" row.

I don't know how to remove them ...

**Comment by 10b14224cc** [comment]
I came up with the following multi-output solution.

It's really ugly but at least it works.

[gt::as_latex] is latex-excaping the characters, so we need to revert that.

And don't ask me why we need so many `\` to match a single latex `\` because I don't know....

````
---
title: "Title"
format:
  pdf:
    header-includes:
      \usepackage{makecell}
    keep-tex: true
    keep-md: true
  html:
    default
---

\newpage

# Section 1

```{r}
#| echo: false
#| output: false
library(tidyverse)
library(gtsummary)
library(gt)
```

```{r, results='asis'}
#| label: tbl-label
#| echo: false
#| output: asis
#| tbl-cap: "**Table caption**"
trial2 <- trial |> select(trt, age, grade)
options(knitr.kable.NA = '')
if(knitr::is_latex_output()) {
  fmtstr <- " \\makecell{\\textbf{[level]} \\\\\\\\ N = [n]}"
  convfnc <- function(data) {
    data <- gt::as_latex(data) %>% as.character()
    data <- stringr::str_replace_all(data,"\\\\textbackslash\\{\\}","\\\\")
    data <- stringr::str_replace_all(data,"\\\\\\{","{")
    data <- stringr::str_replace_all(data,"\\\\\\}","}")
    return(data)
  }
} else if (knitr::is_html_output()) {
  fmtstr <- "**[level]** <br/> N = [n]"
  convfnc <- gt::as_raw_html
} else {
  fmtstr <- "**[level]** \n N = [n]"
  convfnc <- gt::as_gtable
}
trial2 |>
  tbl_summary(by = trt) |>
  modify_header(all_stat_cols() ~ fmtstr,
                glue_open="[", 
                glue_close="]") |>
  add_p() |>
  as_gt() |> 
  convfnc() |>
  cat()
```
````

**Comment by ddsjoberg** [comment]
> You will need the https://github.com/ddsjoberg/gtsummary/pull/2048, because we need to output curly braces without glue processing them.

You can get away without using the PR by doubling up the curly brackets.

``` r
glue::glue("{{dont_evaluate_me}}")
#> {dont_evaluate_me}
```

<sup>Created on 2024-10-27 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

> And don't ask me why we need so many \ to match a single latex \ because I don't know....

Welcome to the hell that is R+latex 😈 🔥 So much escaping...

**Comment by 10b14224cc** [comment]
Oh ok that worked.

Changed the source code.

How can I target those superscripts?

![image](https://github.com/user-attachments/assets/622bfd33-8f3e-498c-ab9a-d374f9ef92f7)

They get put outside the makecell:

```
\makecell{\textbf{Drug A} \\ N = 98}\textsuperscript{\textit{1}}
```

**Comment by ddsjoberg** [comment]
I am not sure how to fix that. But I think there is a gt function to move the placement of the footnote to the beginning, and a few other options as well. 

It seems your original issue is resolved, so I am going to go ahead and close this issue. Happy Coding!

**Comment by ddsjoberg** [comment]
and it will, as soon as it's supported in gt. on top of that, there are other table printers available with gtsummary that do not require any hacks
