### ISSUE TITLE
 tbl_summary - improve dichotomous value passing 2

### ISSUE THREAD

**Issue by andresimi** [ddsjoberg/gtsummary#2049]
I think when the variables are dichotomous, and we select to display only the 1 values, when there is none, the table should display missing or 0 (0%).  The way that is when there is no 1 values show this message:

> " A value of 1 was passed, but must be one of 0.
> To summarize this value, make the column a factor and include 1 as a level."

Thank you!

**Comment by ddsjoberg** [comment]
I don't really understand your request. Please update your post with an example of current behaviour and what your suggesting as a change.

**Comment by ddsjoberg** [comment]
Please feel free to re-open this issue when you've updated your post. Thanks!
