### ISSUE TITLE
Bug Report: Mismatched estimates and CIs with add_ci after tbl_svysummary

### ISSUE THREAD

**Issue by louisahsmith** [ddsjoberg/gtsummary#2052]
When adding confidence intervals to a table created with `tbl_svysummary()` that is stratified by a factor variable, the confidence intervals can get attached to the wrong column. This seems to be related to <https://github.com/ddsjoberg/gtsummary/issues/2036> but is not fixed in version 2.0.3.9003. 

```r
data(api, package = "survey")

survey::svydesign(id = ~dnum, weights = ~pw, data = apiclus1, fpc = ~fpc) |>
    tbl_svysummary(by = "both", include = c(stype)) |>
    add_ci(pattern = "{stat} ({ci})")

apiclus1 <- apiclus1 |> mutate(both2 = factor(both, levels = c("Yes", "No")))

survey::svydesign(id = ~dnum, weights = ~pw, data = apiclus1, fpc = ~fpc) |>
    tbl_svysummary(by = "both2", include = c(stype)) |>
    add_ci(pattern = "{stat} ({ci})")
```

**Comment by ddsjoberg** [comment]
Thank you so much for the report, much appreciated. Can you install the dev version of {cardx} and try again? `devtools::install_remote("insightsengineering/cardx@restore-types")`. That branch is still a work in progress, but I think it should address this issue.

**Comment by louisahsmith** [comment]
That seems to have fixed it! Thanks!
