### ISSUE TITLE
Feature request: estimate_fun list of formulas in tbl_regression

### ISSUE THREAD

**Issue by MauKappel** [ddsjoberg/gtsummary#2058]
Would it be possible for the `estimate_fun` in `tbl_regression` to take a list of formulas like the `estimate_fun` in `add_difference` instead of one function?

```
glm(response ~ age + grade, trial, family = binomial()) |>
    tbl_regression(exponentiate = TRUE,
                   estimate_fun = list(age ~ label_style_ratio(digits = 3)))
```

Thanks!

**Comment by ddsjoberg** [comment]
I will probably keep it as it is as to not introduce a breaking change in an argument that has been around for many many years. In case you're not already aware, you can get similar functionality with `modify_fmt_fn()`. But I'll keep this issue open for a while and consider it further.
 
https://www.danieldsjoberg.com/gtsummary/reference/modify_fmt_fun.html?q=modify_fmt#ref-usage

**Comment by ddsjoberg** [comment]
Hi @MauKappel ! Thank you for the post and the suggestion. As I mentioned above, we'll keep the syntax the way it is as to not introduce a breaking change. Happy Programming!
