### ISSUE TITLE
Weighting-option for `tbl_summary()`?

### ISSUE THREAD

**Issue by strengejacke** [ddsjoberg/gtsummary#2088]
We often have frequency weights in our data, and usually report the weighted data. It would be great to have an option to include weights in `tbl_summary()`, e.g.:

``` r
# unweighted
datawizard::data_tabulate(d, select = "age3")
#> age3 (age3) <categorical>
#> # total N=3246 valid N=3246
#> 
#> Value |    N | Raw % | Valid % | Cumulative %
#> ------+------+-------+---------+-------------
#> 18-40 |  899 | 27.70 |   27.70 |        27.70
#> 41-60 | 1239 | 38.17 |   38.17 |        65.87
#> >60   | 1108 | 34.13 |   34.13 |       100.00
#> <NA>  |    0 |  0.00 |    <NA> |         <NA>

# weighted
datawizard::data_tabulate(d, select = "age3", weights = "weightbe")
#> age3 (age3) <categorical>
#> # total N=3246 valid N=3246 (weighted)
#> 
#> Value |    N | Raw % | Valid % | Cumulative %
#> ------+------+-------+---------+-------------
#> 18-40 | 1078 | 33.21 |   33.21 |        33.21
#> 41-60 | 1103 | 33.98 |   33.98 |        67.19
#> >60   | 1065 | 32.81 |   32.81 |       100.00
#> <NA>  |    0 |  0.00 |    <NA> |         <NA>
```

**Comment by larmarange** [comment]
Could you clarify the meaning of these weights? 

If your weights represent a number of observations, like in `as.data.frame(Titanic)`, you could simply use `dplyr::uncount()` before calling `tbl_summary()`. 

If your weights reprent survey weights / sampling weights, i.e. a weight that is needed to correct your estimates but do not represent actual number of observations, you should use `survey::svydesign()` to define your weights and then call `tbl_svysummary()`. More information: https://www.danieldsjoberg.com/gtsummary/reference/tbl_svysummary.html

It is particularly important when p-values or confidence intervals have to be computed later on with `add_p()` or `add_ci()`.

**Comment by strengejacke** [comment]
It's a frequency weight variable, what you provide in regression models (see `weights` argument in `lm()` and similar). The mean value of that variable usually is ~1.

It's basically the difference between `table(x)` and `xtabs(weights ~ x)`.

**Comment by strengejacke** [comment]
``` r
data(mtcars)
set.seed(123)
mtcars$weight <- rnorm(nrow(mtcars), 1, .3)

table(mtcars$cyl)
#> 
#>  4  6  8 
#> 11  7 14

round(xtabs(mtcars$weight ~ mtcars$cyl))
#> mtcars$cyl
#>  4  6  8 
#> 10  8 14
```

<sup>Created on 2024-11-29 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
``` r
data(mtcars)
library(gtsummary)
set.seed(123)
mtcars$weight <- rnorm(nrow(mtcars), 1, .3)

table(mtcars$cyl)
#> 
#>  4  6  8 
#> 11  7 14

mtcars |> 
  tbl_summary(include = cyl) |> 
  as_kable()
```

| **Characteristic** | **N = 32** |
|:-------------------|:----------:|
| cyl                |            |
| 4                  |  11 (34%)  |
| 6                  |  7 (22%)   |
| 8                  |  14 (44%)  |

``` r

round(xtabs(mtcars$weight ~ mtcars$cyl))
#> mtcars$cyl
#>  4  6  8 
#> 10  8 14

mtcars |> 
  srvyr::as_survey(weight = weight) |> 
  tbl_svysummary(include = cyl) |> 
  as_kable()
```

| **Characteristic** | **N = 32** |
|:-------------------|:----------:|
| cyl                |            |
| 4                  |  10 (31%)  |
| 6                  |  8 (25%)   |
| 8                  |  14 (44%)  |

<sup>Created on 2024-11-29 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Looks great!

**Comment by strengejacke** [comment]
Ok, I see the logic behind the interface. Would you think it makes sense adding a function in gtsummary, which does not rely on the srvyr package? From a user perspective, you would need to know that package and that you have to do it this way. It would be clearer to have a function in gtsummary.

**Comment by ddsjoberg** [comment]
It would unfortunately be a big change to cut out the survey objects for simple and/or complicated weighting schemes. We do have a FAQ, would like to add a post to increase the findability of this solution?
https://www.danieldsjoberg.com/gtsummary/articles/gallery.html
