### ISSUE TITLE
Feature request: <Include Missing Values in Total Percentage of Column>

### ISSUE THREAD

**Issue by cmboeker** [ddsjoberg/gtsummary#2093]
The tbl-table provides unfortunately no argument to include missing values percentages into the total percentage.

I created a tbl-table and used the argument percent = column, which would then display a sample of 140 like this:
Female   72 (56.25 %)
Male      56 (43.75 %)
Missing 12 (8.57 %)

Hereby, the missing values are in proportion to the full sample (N=140). However, Female and Male are in proportion to the full cases (n=128).

For some publications it is important to include the missing values in the total percentages calculation. Therefore, I propose an additional percent option (e.g., "total_column"), which then would display the sample of 140 like this:
Female   72 (51.43 %)
Male      56 (40.00 %)
Missing 12 (8.57 %)

Thank you for considering this addition :)

**Comment by larmarange** [comment]
When you need to include missing values as an explicit level, you could simply apply `forcats::fct_na_value_to_level()` to your factor before calling `tbl_summary()`  cf. https://forcats.tidyverse.org/reference/fct_na_value_to_level.html

Regards

**Comment by cmboeker** [comment]
@larmarange Thank you for the suggestion to use fct_na_value_to_level(). With this function, the missing values and other levels may show 100% in total, however, when the missing values are levels they are included in the group testing and p-value turns out distorted.

@ddsjoberg Therefore, I still suggest a feature that would integrate missing values in the total percentages but exclude them from the group tests.

**Comment by ddsjoberg** [comment]
Thanks for the followup @cmboeker . I am in alignment with @larmarange on this one. These tables are often meant to compare the distributions between groups for the observed data. And just like with a continuous variable, you cannot include  missing obs in the calculation of the mean, we don't include missing data in the tabulation of n. 

You can of course change this behaviour as @larmarange illustrated, but it's hard to image a scenario when one would want to include the missing rates in the primary table, but not include them in the comparison. Regardless, if that is something you would like to do it is possible by wrapping the functions that calculate the p-values to remove your missing obs before calculating, or by creating two tables and merging them.
