### ISSUE TITLE
Translation to portuguese.

### ISSUE THREAD

**Issue by abreu-uma** [ddsjoberg/gtsummary#2101]
Translation: In portuguese, instead of "Confidence Interval", should be "Intervalo de Confiança". Also, p-value we write valor-p (with the hifen), not just valor p.  The site "https://www.spestatistica.pt/glossario" is a good reference for translations from english to portuguese and vice-versa. Thanks

**Comment by ddsjoberg** [comment]
Thanks @abreu-uma !

Is there somewhere you're seeing the incorrect translation for confidence interval? It looks correct to me, or are you suggesting it be capitalized? (I'll add the hyphen for the p-values)

```r
library(gtsummary)

theme_gtsummary_language("pt")
lm(mpg ~ cyl, mtcars) |> 
  tbl_regression()
```

![image](https://github.com/user-attachments/assets/59eb7670-f8db-4045-9561-07d9754f468a)

**Comment by ddsjoberg** [comment]
FYI, the pull request #2103 will auto-close this issue, but please reopen if there are corrections to be made. Please install the dev version of the package to test the updated translations.

**Comment by abreu-uma** [comment]
Hi,

I had the code:

glm(response ~ age + grade, trial, family = binomial) %>%
tbl_regression(exponentiate = TRUE)

with the data trial from your site (https://github.com/ddsjoberg/gtsummary/blob/main/data/trial.rda) and it returned Confidence interval instead of Intervalo de confiança. But now it’s working fine.

Thanks,
Abreu

De: Daniel Sjoberg ***@***.***>
Enviada: 18 de dezembro de 2024 01:01
Para: ddsjoberg/gtsummary ***@***.***>
Cc: Ana Maria Abreu ***@***.***>; Mention ***@***.***>
Assunto: Re: [ddsjoberg/gtsummary] Translation to portuguese. (Issue #2101)

Não costuma receber e-mails de ***@***.******@***.***>. Saiba por que motivo isto é importante<https://aka.ms/LearnAboutSenderIdentification>

Thanks @abreu-uma<https://github.com/abreu-uma> !

Is there somewhere you're seeing the incorrect translation for confidence interval? It looks correct to me, or are you suggesting it be capitalized? (I'll add the hyphen for the p-values)

library(gtsummary)



theme_gtsummary_language("pt")

lm(mpg ~ cyl, mtcars) |>

  tbl_regression()

image.png (view on web)<https://github.com/user-attachments/assets/59eb7670-f8db-4045-9561-07d9754f468a>
