### ISSUE TITLE
Bug Report: `tbl_svysummary()` error for all NA factors

### ISSUE THREAD

**Issue by BLalloue** [ddsjoberg/gtsummary#2104]
Hi, 

I have what seems to be an abnormal error when I use `tbl_svysummary()` on a factor that contains only NAs.

Instead of displaying a table with all levels at n=0 (or NA according to the statistic) and the total number of missing values, like with `tbl_summary()`, I get the following error : "Only columns of class <logical> and <factor> can be tabulated when all values."

If I understand the message correctly, since I tried to tabulate a factor column `tbl_svysummary()` should be able to manage it, but it seems the type is not recognized. 

Here's a repex with first the results without error when using `tbl_summary()` and then with the error message on a survey object.
``` r
library(dplyr)
library(forcats)
library(survey)
library(gtsummary)

set.seed("123")

# generate sample data
testdata <- tibble(
    strata = sample(1:3, 100, replace = TRUE),
    factor = sample(NA, 100, replace = TRUE)
) %>% 
    mutate(
        factor = fct_expand(as.factor(factor), "Yes", "No"),
        fpc = case_when(
            strata == 1 ~ 100,
            strata == 2 ~ 200,
            strata == 3 ~ 300
        )
    )

# tbl_summary() -> WORKS
testdata %>% 
    tbl_summary(
        include = factor,
        type = factor ~ "categorical"
        ) 
```

<div id="hnumbkmnfy" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="label"><span class='gt_from_md'><strong>Characteristic</strong></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="stat_0"><span class='gt_from_md'><strong>N = 100</strong></span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">factor</td>
<td headers="stat_0" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Yes</td>
<td headers="stat_0" class="gt_row gt_center">0 (NA%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    No</td>
<td headers="stat_0" class="gt_row gt_center">0 (NA%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unknown</td>
<td headers="stat_0" class="gt_row gt_center">100</td></tr>
  </tbody>
  &#10;  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="2"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> <span class='gt_from_md'>n (%)</span></td>
    </tr>
  </tfoot>
</table>
</div>

I was expecting to get a result similar to this table with tbl_svysummary, however I got the following results:
``` r

# Create the survey object
testsurvey <- svydesign(ids = ~ 1, strata = ~ strata, data = testdata)
#> Warning in svydesign.default(ids = ~1, strata = ~strata, data = testdata): No
#> weights or probabilities supplied, assuming equal probability

# `factor` is correctly typed as a factor in the survey object
is.factor(testsurvey$variables$factor)
#> [1] TRUE

# tbl_svysummary() -> ERROR
testsurvey %>% 
    tbl_svysummary(include = factor)
#> Error in `tbl_svysummary()`:
#> ! Column "factor" is all missing and cannot be tabulated.
#> ℹ Only columns of class <logical> and <factor> can be tabulated when all values
#>   are missing.

# Same error when the type is explicitely set
testsurvey %>% 
    tbl_svysummary(
        include = factor,
        type = factor ~ "categorical")
#> Error in `tbl_svysummary()`:
#> ! Column "factor" is all missing and cannot be tabulated.
#> ℹ Only columns of class <logical> and <factor> can be tabulated when all values
#>   are missing.
```

<sup>Created on 2024-12-18 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessionInfo()
#> R version 4.4.1 (2024-06-14 ucrt)
#> Platform: x86_64-w64-mingw32/x64
#> Running under: Windows 10 x64 (build 19045)
#> 
#> Matrix products: default
#> 
#> 
#> locale:
#> [1] LC_COLLATE=French_France.utf8  LC_CTYPE=French_France.utf8   
#> [3] LC_MONETARY=French_France.utf8 LC_NUMERIC=C                  
#> [5] LC_TIME=French_France.utf8    
#> 
#> time zone: Europe/Paris
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] grid      stats     graphics  grDevices utils     datasets  methods  
#> [8] base     
#> 
#> other attached packages:
#> [1] gtsummary_2.0.4 survey_4.4-2    survival_3.8-3  Matrix_1.7-1   
#> [5] forcats_1.0.0   dplyr_1.1.4    
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_4.4.1    tidyselect_1.2.1  reprex_2.1.1      Rcpp_1.0.13-1    
#>  [5] xml2_1.3.6        tidyr_1.3.1       splines_4.4.1     yaml_2.3.10      
#>  [9] fastmap_1.2.0     lattice_0.22-6    R6_2.5.1          commonmark_1.9.2 
#> [13] cards_0.4.0       generics_0.1.3    knitr_1.49        cardx_0.2.2      
#> [17] tibble_3.2.1      DBI_1.2.3         pillar_1.10.0     rlang_1.1.4      
#> [21] xfun_0.49         sass_0.4.9        fs_1.6.5          cli_3.6.3        
#> [25] withr_3.0.2       magrittr_2.0.3    digest_0.6.37     rstudioapi_0.17.1
#> [29] markdown_1.13     lifecycle_1.0.4   vctrs_0.6.5       evaluate_1.0.1   
#> [33] glue_1.8.0        mitools_2.4       gt_0.11.1         rmarkdown_2.29   
#> [37] purrr_1.0.2       tools_4.4.1       pkgconfig_2.0.3   htmltools_0.5.8.1
```

</details>

Thank you for any help you can give me, and thanks for all your work!

**Comment by ddsjoberg** [comment]
Thanks for letting us know @BLalloue ! You can install the dev version of cardx and you should now be able to tabulate factor variables with all missing values.
https://github.com/insightsengineering/cardx
