### ISSUE TITLE
Add a `filter` option

### ISSUE THREAD

**Issue by rc6374** [ddsjoberg/gtsummary#2106]
Hi,

I would like to add a conditional filter on an included variable (depending on another variable) so that the statistics calculated with tbl_summary() only affect this variable. 

For example (below), I would like the population used to calculate `SEX` statistics to be `AGEGR1` patients `"<65"`. It could go something like this:

```r
library(gtsummary)

# Data
ADAE_subset <- cards::ADAE |>
  dplyr::filter(
    AESOC %in% unique(cards::ADAE$AESOC)[1:5],
    AETERM %in% unique(cards::ADAE$AETERM)[1:5]
  ) |>
  dplyr::select(TRTA, AGEGR1, SEX, RACE)

# Table 1
Table1 <- ADAE_subset |>
  tbl_summary(by = TRTA, 
              include = c(AGEGR1, SEX[AGEGR1 == "<65"], RACE), # in the "include" parameter
              label = (SEX ~ "(If Pooled Age Group 1 < 65) Sex"))
# OR
Table1 <- ADAE_subset |>
  tbl_summary(by = TRTA, 
              include = c(AGEGR1, SEX, RACE),
              filter = (SEX ~ AGEGR1 == "<65"), # in a new "filter" parameter
              label = (SEX ~ "(If Pooled Age Group 1 < 65) Sex"))
``` 

I definitely think that this option can be very useful.

Thanks!

**Comment by ddsjoberg** [comment]
HI @rc6374 , thanks for the thoughtful post! It's an interesting idea for sure.

In the package, we've leaned into tidyselect notation heavily, which would not allow for this type of notation unfortunately (that said, I do love the tidyselect syntax).

But you can still get the tables you're after pretty easily by constructing two tables: one that has been subset and one that has not, then use `tbl_stack()` to combine them.

**Comment by rc6374** [comment]
Hi @ddsjoberg,

So far, I've been using the `tbl_stack()` command to do this and it works very well as long as the number of filters is small. Sometimes, however, it gets very difficult when the number of different filters increases. That's how I came up with the idea of a filter parameter. 

If such a function is introduced one day, be sure that I'll be the first to test it (tidyselect developers, we are counting on you too)!

For now, thank you for your great work!

**Comment by ddsjoberg** [comment]
Thanks again for the post!!
