### ISSUE TITLE
Bug Report: spanner wrong in docx rendering

### ISSUE THREAD

**Issue by raffaem** [ddsjoberg/gtsummary#2109]
Consider the following Quarto MWE:

````r
---
title: "Title"
format:
  pdf: default
  docx: default
---

```{r}
#| label: tbl-bug
#| echo: false
#| output: true
mod1 <- gtsummary::tbl_regression(lm(mpg ~ wt, data = mtcars))
mod2 <- gtsummary::tbl_regression(lm(mpg ~ wt+gear, data = mtcars))
spanner <- c("Model 1", "Model2")
gtsummary::tbl_merge(list(mod1, mod2), tab_spanner=spanner)
```
````

This is how is rendered in PDF (good):

![Screenshot_20241220_183157](https://github.com/user-attachments/assets/ff977463-d117-4320-bacf-92a82d3f0cfe)

This is how it is rendered in docx.
The spanner is wrong, as the first header covers only one column instead of 3:

![Screenshot_20241220_183242](https://github.com/user-attachments/assets/7201738f-a53b-413f-8d8f-54488ee698c3)

**Comment by ddsjoberg** [comment]
Thanks for the post @raffaem !

If you don't include the `#| label: tbl-bug` tag, the table renders properly. This looks like a Quarto+gt bug to me?

````r
---
title: "Untitled"
format: docx
---

## Quarto

```{r}
library(gtsummary)
packageVersion("gtsummary")

list(
  tbl_regression(lm(mpg ~ wt, data = mtcars)),
  tbl_regression(lm(mpg ~ wt+gear, data = mtcars))
) |> 
  tbl_merge(tab_spanner=c("Model 1", "Model2"))
```
````

![image](https://github.com/user-attachments/assets/9eab6b13-5608-4fec-837c-048b66518d7a)

**Comment by raffaem** [comment]
So how can I  get the gt code to reproduce that table, so I can report it upstream?

**Comment by ddsjoberg** [comment]
You can use `as_gt(return_calls = TRUE)`, but that will give you a lot of extra code. Probably best to just use a small dummy example and add two spanning headers with `gt::tab_spanner()`

```r
list(
  tbl_regression(lm(mpg ~ wt, data = mtcars)),
  tbl_regression(lm(mpg ~ wt+gear, data = mtcars))
) |> 
  tbl_merge(tab_spanner=c("Model 1", "Model2")) |> 
  as_gt(return_calls = TRUE)
```

**Comment by raffaem** [comment]
https://github.com/rstudio/gt/issues/1898
