### ISSUE TITLE
Bug Report: Doesn't report fixest IV estimates

### ISSUE THREAD

**Issue by raffaem** [ddsjoberg/gtsummary#2110]
Consider the following model:

```
gtsummary::tbl_regression(fixest::feols(mpg~disp|cyl|wt~qsec, data=mtcars))
```

It results in:

![Screenshot_20241221_192708](https://github.com/user-attachments/assets/13a3f519-68f4-4c89-998f-daa158472155)

The coefficient on the endogenous regression `wt` is not shown.

~~If you don't have exogenous regressors, it will even crash:~~

[WRONG EXAMPLE. SEE COMMENT FOR CORRECT ONE]

**Comment by ddsjoberg** [comment]
Your second example fails in the `feols()` function FYI

``` r
fixest::feols(1~disp|cyl|wt~qsec, data=mtcars)
#> Error in fixest::feols(1 ~ disp | cyl | wt ~ qsec, data = mtcars): The right hand side of the formula (1) contains no variable!
```

<sup>Created on 2024-12-21 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

@larmarange is this something you'd like to support in `broom.helpers`? The broom tidier updates the column name, which is probably why it's being omitted.

``` r
mod <- fixest::feols(mpg~disp|cyl|wt~qsec, data=mtcars) 
mod
#> TSLS estimation - Dep. Var.: mpg
#>                   Endo.    : wt
#>                   Instr.   : qsec
#> Second stage: Dep. Var.: mpg
#> Observations: 32
#> Fixed-effects: cyl: 3
#> Standard-errors: Clustered (cyl) 
#>         Estimate Std. Error  t value Pr(>|t|) 
#> fit_wt -0.989650   0.461702 -2.14348  0.16530 
#> disp   -0.018622   0.010407 -1.78946  0.21543 
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 2.57839     Adj. R2: 0.783086
#>                 Within R2: 0.293843
#> F-test (1st stage), wt: stat = 11.4   , p = 0.002083, on 1 and 29 DoF.
#>             Wu-Hausman: stat =  1.7829, p = 0.193368, on 1 and 26 DoF.

mod |> broom::tidy()
#> # A tibble: 2 × 5
#>   term   estimate std.error statistic p.value
#>   <chr>     <dbl>     <dbl>     <dbl>   <dbl>
#> 1 fit_wt  -0.990     0.462      -2.14   0.165
#> 2 disp    -0.0186    0.0104     -1.79   0.215
mod |> gtsummary::tbl_regression() |> gtsummary::as_kable()
```

| **Characteristic** | **Beta** | **95% CI**  | **p-value** |
|:-------------------|:--------:|:-----------:|:-----------:|
| disp               |  -0.02   | -0.06, 0.03 |     0.2     |

<sup>Created on 2024-12-21 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by raffaem** [comment]
> Your second example fails in the `feols()` function FYI

Sorry the correct example is this:

```
> gtsummary::tbl_regression(fixest::feols(disp~1|cyl|wt~qsec, data=mtcars))
Error in if (result$label %in% c("Beta", "exp(Beta)")) { : 
  argument is of length zero
```

**Comment by raffaem** [comment]
> The broom tidier updates the column name, which is probably why it's being omitted.

The variable is changed from `wt` to `fit_wt` in fixest directly

**Comment by ddsjoberg** [comment]
@raffaem It looks like Joseph may be away for the holidays. Could you please post this to the broom.helpers repository? The issue arises in the broom.helpers::tidy_plus_plus() function, which is used by gtsummary

``` r
fixest::feols(disp~1|cyl|wt~qsec, data=mtcars) |> 
  broom.helpers::tidy_plus_plus()
#> # A tibble: 0 × 17
#> # ℹ 17 variables: term <chr>, variable <chr>, var_label <chr>, var_class <chr>,
#> #   var_type <chr>, var_nlevels <int>, contrasts <chr>, contrasts_type <chr>,
#> #   reference_row <lgl>, label <chr>, n_obs <dbl>, estimate <dbl>,
#> #   std.error <dbl>, statistic <dbl>, p.value <dbl>, conf.low <dbl>,
#> #   conf.high <dbl>

fixest::feols(mpg~disp|cyl|wt~qsec, data=mtcars) |> 
  broom.helpers::tidy_plus_plus()
#> # A tibble: 1 × 17
#>   term  variable var_label var_class var_type   var_nlevels contrasts
#>   <chr> <chr>    <chr>     <chr>     <chr>            <int> <chr>    
#> 1 disp  disp     disp      numeric   continuous          NA <NA>     
#> # ℹ 10 more variables: contrasts_type <chr>, reference_row <lgl>, label <chr>,
#> #   n_obs <dbl>, estimate <dbl>, std.error <dbl>, statistic <dbl>,
#> #   p.value <dbl>, conf.low <dbl>, conf.high <dbl>
```

<sup>Created on 2024-12-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
Hi

Quick trick: simply add `intercept = TRUE`.

``` r
library(fixest)
library(gtsummary)

mod <- fixest::feols(mpg~disp|cyl|wt~qsec, data=mtcars) 

mod |> 
  tbl_regression(intercept = TRUE) |> 
  as_kable()
```

| **Characteristic** | **Beta** | **95% CI**  | **p-value** |
|:-------------------|:--------:|:-----------:|:-----------:|
| fit_wt             |  -0.99   |  -3.0, 1.0  |     0.2     |
| disp               |  -0.02   | -0.06, 0.03 |     0.2     |

<sup>Created on 2024-12-25 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

When a variable is not identified as `fit_wt`, it is by default classified as an intercept, and by default, intercepts are not included in the table.

Now we could improve `broom.helpers`. However, I'm not sure yet what should be the expected behaviour. I'm not very familiar with Instrumental variables. As I understood it, but I may be wrong, `fit_wt` is not the variable `wt` but predictions of the variable `wt`. So, what should be the variable label attached to it? The same as `wt`? Could a categorical variable be used as instrumental?

The easy approach would be to detect all variables with the `fit_` prefix, to populate the `var_type` column with `"instrumental"` (as we do with `"ran_pars"` and `"ran_vals"` terms for mixed models) and simply let users define manually appropriate labels for such terms.

**Comment by ddsjoberg** [comment]
Ahh, that makes sense, thanks for the clarification @larmarange ! I haven't used an IV model outside of grad school, so i don't have a strong opinion (or informed) on how this is handled.

**Comment by larmarange** [comment]
Hi

I have added support of instrumental variables in `broom.helpers`.  https://github.com/larmarange/broom.helpers/pull/279

By default, a suffix is added to the label of such variables. It could be controlled with `instrumental_suffix`.

``` r
library(fixest)
library(gtsummary)

mod <- fixest::feols(mpg ~ disp | cyl | wt ~ qsec, data = mtcars) 

mod |> 
  tbl_regression(intercept = TRUE) |> 
  as_kable()
```

| **Characteristic** | **Beta** | **95% CI**  | **p-value** |
|:-------------------|:--------:|:-----------:|:-----------:|
| fit_wt             |  -0.99   |  -3.0, 1.0  |     0.2     |
| disp               |  -0.02   | -0.06, 0.03 |     0.2     |

``` r

mod |> 
  tbl_regression(intercept = TRUE, instrumental_suffix = NULL) |> 
  as_kable()
```

| **Characteristic** | **Beta** | **95% CI**  | **p-value** |
|:-------------------|:--------:|:-----------:|:-----------:|
| fit_wt             |  -0.99   |  -3.0, 1.0  |     0.2     |
| disp               |  -0.02   | -0.06, 0.03 |     0.2     |

``` r

mod <- fixest::feols(mpg ~ disp | 1 | factor(cyl) ~ qsec, data = mtcars) 

mod |> 
  tbl_regression(intercept = TRUE, instrumental_suffix = " (IV)") |> 
  as_kable()
```

| **Characteristic** | **Beta** |          **95% CI**           | **p-value** |
|:-------------------|:--------:|:-----------------------------:|:-----------:|
| (Intercept)        |   0.00   | -3,666,135,467, 3,666,135,467 |    \>0.9    |
| fit_factor(cyl)6   |   160    | -7,551,389,685, 7,551,390,005 |    \>0.9    |
| fit_factor(cyl)8   |   -8.0   | -2,037,757,248, 2,037,757,232 |    \>0.9    |
| disp               |   0.25   |    -12,594,331, 12,594,332    |    \>0.9    |

<sup>Created on 2024-12-27 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Awesome, looks great
