### ISSUE TITLE
tbl_summary not accepting variable names with spaces/symbols

### ISSUE THREAD

**Issue by margarethannum** [ddsjoberg/gtsummary#212]
Sometimes data will have "messy" variable names (i.e. with spaces or symbols) that we can normally refer to with backticks (e.g. `trt example` as \`trt example\`)

Unfortunately the recent update to {gtsummary} does not appear totally compatible with these kinds of variables! 

See below for examples. 

``` r
library(gtsummary)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

# make new messy variable name 
trial2 <-
  trial %>%
  mutate(`trt example` = trt)

# doesn't recognize variable and thus doesn't make table 
trial2 %>%
  tbl_summary(by = `trt example`)
#> Error in tbl_summary_input_checks(data, by, label, type, value, statistic, : '`trt example`' not a column in 'data'.
    

# doesn't recognize variable and thus doesn't make new label
trial2 %>%
  tbl_summary(label = list(vars(`trt example`) ~ "treat")
  )
```

<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#iepqumicww .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  /* table.background.color */
  width: auto;
  /* table.width */
  border-top-style: solid;
  /* table.border.top.style */
  border-top-width: 2px;
  /* table.border.top.width */
  border-top-color: #A8A8A8;
  /* table.border.top.color */
  border-bottom-style: solid;
  /* table.border.bottom.style */
  border-bottom-width: 2px;
  /* table.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* table.border.bottom.color */
}

#iepqumicww .gt_heading {
  background-color: #FFFFFF;
  /* heading.background.color */
  border-bottom-color: #FFFFFF;
}

#iepqumicww .gt_title {
  color: #333333;
  font-size: 125%;
  /* heading.title.font.size */
  padding-top: 4px;
  /* heading.top.padding - not yet used */
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#iepqumicww .gt_subtitle {
  color: #333333;
  font-size: 85%;
  /* heading.subtitle.font.size */
  padding-top: 0;
  padding-bottom: 4px;
  /* heading.bottom.padding - not yet used */
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#iepqumicww .gt_bottom_border {
  border-bottom-style: solid;
  /* heading.border.bottom.style */
  border-bottom-width: 2px;
  /* heading.border.bottom.width */
  border-bottom-color: #D3D3D3;
  /* heading.border.bottom.color */
}

#iepqumicww .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  padding-top: 4px;
  padding-bottom: 4px;
}

#iepqumicww .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  /* column_labels.background.color */
  font-size: 16px;
  /* column_labels.font.size */
  font-weight: initial;
  /* column_labels.font.weight */
  vertical-align: middle;
  padding: 5px;
  margin: 10px;
  overflow-x: hidden;
}

#iepqumicww .gt_columns_top_border {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#iepqumicww .gt_columns_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#iepqumicww .gt_sep_right {
  border-right: 5px solid #FFFFFF;
}

#iepqumicww .gt_group_heading {
  padding: 8px;
  /* row_group.padding */
  color: #333333;
  background-color: #FFFFFF;
  /* row_group.background.color */
  font-size: 16px;
  /* row_group.font.size */
  font-weight: initial;
  /* row_group.font.weight */
  border-top-style: solid;
  /* row_group.border.top.style */
  border-top-width: 2px;
  /* row_group.border.top.width */
  border-top-color: #D3D3D3;
  /* row_group.border.top.color */
  border-bottom-style: solid;
  /* row_group.border.bottom.style */
  border-bottom-width: 2px;
  /* row_group.border.bottom.width */
  border-bottom-color: #D3D3D3;
  /* row_group.border.bottom.color */
  vertical-align: middle;
}

#iepqumicww .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  /* row_group.background.color */
  font-size: 16px;
  /* row_group.font.size */
  font-weight: initial;
  /* row_group.font.weight */
  border-top-style: solid;
  /* row_group.border.top.style */
  border-top-width: 2px;
  /* row_group.border.top.width */
  border-top-color: #D3D3D3;
  /* row_group.border.top.color */
  border-bottom-style: solid;
  /* row_group.border.bottom.style */
  border-bottom-width: 2px;
  /* row_group.border.bottom.width */
  border-bottom-color: #D3D3D3;
  /* row_group.border.bottom.color */
  vertical-align: middle;
}

#iepqumicww .gt_striped {
  background-color: #8080800D;
}

#iepqumicww .gt_from_md > :first-child {
  margin-top: 0;
}

#iepqumicww .gt_from_md > :last-child {
  margin-bottom: 0;
}

#iepqumicww .gt_row {
  padding: 8px;
  /* row.padding */
  margin: 10px;
  border-bottom-style: solid;
  border-bottom-width: thin;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#iepqumicww .gt_stub {
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#iepqumicww .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  /* summary_row.background.color */
  padding: 8px;
  /* summary_row.padding */
  text-transform: inherit;
  /* summary_row.text_transform */
}

#iepqumicww .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  /* grand_summary_row.background.color */
  padding: 8px;
  /* grand_summary_row.padding */
  text-transform: inherit;
  /* grand_summary_row.text_transform */
}

#iepqumicww .gt_first_summary_row {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#iepqumicww .gt_first_grand_summary_row {
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#iepqumicww .gt_table_body {
  border-top-style: solid;
  /* table_body.border.top.style */
  border-top-width: 2px;
  /* table_body.border.top.width */
  border-top-color: #D3D3D3;
  /* table_body.border.top.color */
  border-bottom-style: solid;
  /* table_body.border.bottom.style */
  border-bottom-width: 2px;
  /* table_body.border.bottom.width */
  border-bottom-color: #D3D3D3;
  /* table_body.border.bottom.color */
}

#iepqumicww .gt_footnotes {
  border-top-style: solid;
  /* footnotes.border.top.style */
  border-top-width: 2px;
  /* footnotes.border.top.width */
  border-top-color: #D3D3D3;
  /* footnotes.border.top.color */
}

#iepqumicww .gt_footnote {
  font-size: 90%;
  /* footnote.font.size */
  margin: 0px;
  padding: 4px;
  /* footnote.padding */
}

#iepqumicww .gt_sourcenotes {
  border-top-style: solid;
  /* sourcenotes.border.top.style */
  border-top-width: 2px;
  /* sourcenotes.border.top.width */
  border-top-color: #D3D3D3;
  /* sourcenotes.border.top.color */
}

#iepqumicww .gt_sourcenote {
  font-size: 90%;
  /* sourcenote.font.size */
  padding: 4px;
  /* sourcenote.padding */
}

#iepqumicww .gt_center {
  text-align: center;
}

#iepqumicww .gt_left {
  text-align: left;
}

#iepqumicww .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#iepqumicww .gt_font_normal {
  font-weight: normal;
}

#iepqumicww .gt_font_bold {
  font-weight: bold;
}

#iepqumicww .gt_font_italic {
  font-style: italic;
}

#iepqumicww .gt_super {
  font-size: 65%;
}

#iepqumicww .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>

<div id="iepqumicww" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_left" rowspan="1" colspan="1">

<strong>Characteristic</strong><sup class="gt_footnote_marks">1</sup>

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_center" rowspan="1" colspan="1">

<strong>N = 200</strong>

</th>

</tr>

<body class="gt_table_body">

<tr>

<td class="gt_row gt_left">

Treatment Randomization

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped" style="text-align: left; text-indent: 10px;">

Drug

</td>

<td class="gt_row gt_center gt_striped">

107 (54%)

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

Placebo

</td>

<td class="gt_row gt_center">

93 (46%)

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

Age, yrs

</td>

<td class="gt_row gt_center gt_striped">

46 (37, 57)

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

Unknown

</td>

<td class="gt_row gt_center">

9

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

Marker Level, ng/mL

</td>

<td class="gt_row gt_center gt_striped">

0.69 (0.22, 1.41)

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

Unknown

</td>

<td class="gt_row gt_center">

9

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

T Stage

</td>

<td class="gt_row gt_center gt_striped">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

T1

</td>

<td class="gt_row gt_center">

51 (26%)

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped" style="text-align: left; text-indent: 10px;">

T2

</td>

<td class="gt_row gt_center gt_striped">

49 (24%)

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

T3

</td>

<td class="gt_row gt_center">

42 (21%)

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped" style="text-align: left; text-indent: 10px;">

T4

</td>

<td class="gt_row gt_center gt_striped">

58 (29%)

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Grade

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped" style="text-align: left; text-indent: 10px;">

I

</td>

<td class="gt_row gt_center gt_striped">

67 (34%)

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

II

</td>

<td class="gt_row gt_center">

58 (29%)

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped" style="text-align: left; text-indent: 10px;">

III

</td>

<td class="gt_row gt_center gt_striped">

75 (38%)

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Tumor Response

</td>

<td class="gt_row gt_center">

83 (43%)

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped" style="text-align: left; text-indent: 10px;">

Unknown

</td>

<td class="gt_row gt_center gt_striped">

9

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Patient Died

</td>

<td class="gt_row gt_center">

107 (54%)

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

Months to Death/Censor

</td>

<td class="gt_row gt_center gt_striped">

22.4 (15.4, 24.0)

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Treatment Randomization

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped" style="text-align: left; text-indent: 10px;">

Drug

</td>

<td class="gt_row gt_center gt_striped">

107 (54%)

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

Placebo

</td>

<td class="gt_row gt_center">

93 (46%)

</td>

</tr>

</body>

<tfoot>

<tr class="gt_footnotes">

<td colspan="2">

<p class="gt_footnote">

<sup class="gt_footnote_marks">
<em>1</em>
</sup>

Statistics presented: n (%); median (IQR)
<br />

</p>

</td>

</tr>

</tfoot>

</table>

</div>

<sup>Created on 2019-08-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
c6760852685233e97b1cf44dd8a44501b71467a6

Update addressing this issue added, and a couple unit tests ensuring no errors were added as well.
