### ISSUE TITLE
Script to create *.Rd figures is broken for add_p()

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#214]
@karissawhiting the `create_doc_images.R` script is amazing (obviously).  We recently updated `add_p()` to accept S3 method functions that accept user-defined tests.  We added an example of this to the documentation, but the update broke `create_doc_images.R`.  Whenever you have a chance, can you take a look?  There's no rush on this one.

![image](https://user-images.githubusercontent.com/26774684/63232560-eb946f80-c1f6-11e9-8c9c-cad87c91689e.png)

**Comment by ddsjoberg** [comment]
I think this is fixed in update to #226. Need to double check

**Comment by ddsjoberg** [comment]
Let's update the parsing code to use `Rd2roxygen::parse_file()`.  The input is the Rd file, and it returns a named list.  The names are the sections, and the value is the section content.  so much easier !

**Comment by karissawhiting** [comment]
This function is great! Down to overhaul `create_doc_images.R` to utilize this.
