### ISSUE TITLE
factor variables not correctly labeled in tbl_summary

### ISSUE THREAD

**Issue by emilyvertosick** [ddsjoberg/gtsummary#221]
``` r
library(tidyverse)
#> Warning: package 'tibble' was built under R version 3.6.1
#> Warning: package 'dplyr' was built under R version 3.6.1
library(gtsummary)

# Stage and grade not correctly labelled
tbl_summary(
  trial %>%
    filter(trt == "Drug") %>%
    select(age, marker, stage, grade, response)
)
```
![image](https://user-images.githubusercontent.com/49212917/64286467-87c6b200-cf2b-11e9-8ea9-52a1a2d9dc3d.png)

``` r

# Taking out the filter statement fixes the problem
tbl_summary(
  trial %>%
    select(age, marker, stage, grade, response)
)
```
![image](https://user-images.githubusercontent.com/49212917/64286427-71b8f180-cf2b-11e9-8aa8-8412754efa77.png)

<sup>Created on 2019-09-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
I am not sure why, but the `dplyr::filter()` is stripping the label before the data frame is passed to `tbl_summary()`

``` r
library(gtsummary)
#> Warning: package 'gtsummary' was built under R version 3.6.1

trial %>%
  dplyr::filter(trt == "Drug") %>%
  dplyr::select(age, marker, stage, grade, response) %>%
  purrr::map(~attr(.x, "label"))
#> $age
#> [1] "Age, yrs"
#> 
#> $marker
#> [1] "Marker Level, ng/mL"
#> 
#> $stage
#> NULL
#> 
#> $grade
#> NULL
#> 
#> $response
#> [1] "Tumor Response"
```

<sup>Created on 2019-09-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

There is really nothing we can do about that
@emilyvertosick
