### ISSUE TITLE
Update broom::tidy to use broom::confint_tidy

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#229]
If use `broom::confint_tidy` rather than `broom::tidy` we can pass arguments to `confint()` to calculate different types of CIs.

For example, `confint_tidy(m, func = stats::confint.default)` will give Wald confidence intervals for a GLM.

``` r
library(gtsummary)

m <- glm(response ~ age + grade, trial, family = binomial(link = "logit")) 

broom::tidy(m, conf.int = TRUE)
#> # A tibble: 4 x 7
#>   term        estimate std.error statistic p.value conf.low conf.high
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>
#> 1 (Intercept)  0.0882     0.533      0.165   0.869  -0.961     1.14  
#> 2 age         -0.00280    0.0105    -0.266   0.790  -0.0236    0.0179
#> 3 gradeII     -0.467      0.384     -1.22    0.224  -1.23      0.282 
#> 4 gradeIII    -0.213      0.364     -0.585   0.558  -0.929     0.500
broom::confint_tidy(m)
#> # A tibble: 4 x 2
#>   conf.low conf.high
#>      <dbl>     <dbl>
#> 1  -0.961     1.14  
#> 2  -0.0236    0.0179
#> 3  -1.23      0.282 
#> 4  -0.929     0.500
```

<sup>Created on 2019-09-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
This can't be implemented quite yet (or at least not for all models).  The `confint_tidy()` function is only exported by {broom} and not {broom.mixed}.

We could implement a version where we include an argument `contint_args =` to `tbl_regression()`.  If `broom::tidy()` is used we could split into `broom::tidy()` and `broom::confint_tidy()`.  

Otherwise, we would just use `broom.mixed::tidy()`.  If a user supplied something in `contint_args =`  would print a note saying the argument is ignored.

**Comment by michaelcurry1123** [comment]
here is a way to pull out methods for each function and package without loading them: 
```
f1 <- function(x,y){
 x1 <- as.vector(do.call("methods", list(substitute(x::y))))
 x2 <- substr(x1,6,nchar(x1))
 return(x2)
}
f1(broom,tidy)
```

This will help determine which functions have which methods .

**Comment by ddsjoberg** [comment]
Perhaps we can add another function, `modify_ci()` to update the ci method.  I think I prefer the idea of modifying the CI later rather than adding more arguments to `tbl_regression()`

**Comment by margarethannum** [comment]
I like the idea of creating a new function, although I could also see having a "confint_fun" argument (similar to the new "tidy_fun" argument) within `tbl_regression()` that would run instead wasting computing time on the default CI. 

https://stackoverflow.com/questions/53091552/fast-wald-confidence-intervals-for-a-glm-with-broom-in-r

**Comment by ddsjoberg** [comment]
The computation time is a v good point, @margarethannum .

What do you think of providing an example to users where they create their own tidy function utilizing `contint_tidy()`, and pass it to `tudy_fun=`?  We can avoid adding additional arguments, we don't have to add more checks that the `confint_tidy()` function works for whatever object they've passed....but it is more intense on the user side.

For example, 
```r
tbl_regerssion(
  x = mod1,
  tidy_fun = function(x, ...) cbind(tidy(x, conf.int = FALSE, ...), confint_tidy(x, func = stats::confint.default))
)

```

**Comment by margarethannum** [comment]
I think this is a great solution! And I'm ultra-happy about the `tidy_fun=` update... makes things so flexible...

**Comment by ddsjoberg** [comment]
OK, here is a working example!

In the new tidy function, we need the `...` to be able to pass the `exponentiate=` argument.  One tricky bit is that we have `conf.int = TRUE` hard coded as being passed to the `tidy()` function (regardless if it's broom, or user supplied).  Because of this there will currently be computation waste calculating the CIs for the default method first.  I am not sure what the best solution is at the moment.  Thoughts?  At minimum, we can let Christine know that this is now possible.

``` r
library(tidyverse)
library(gtsummary)

mod1 <- lm(age ~ grade + marker, trial)

# this tidier uses a Wald method for calculating the CIs
my_tidy <- function(x, ...) {
  bind_cols(
    broom::tidy(x, ...) %>% dplyr::select(-dplyr::starts_with("conf.")),
    broom::confint_tidy(x, func = stats::confint.default)
  )
}

# Wald CI calculation
my_tidy(mod1)
#> # A tibble: 4 x 7
#>   term        estimate std.error statistic  p.value conf.low conf.high
#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
#> 1 (Intercept)  46.1         2.29   20.1    2.26e-47    41.6      50.5 
#> 2 gradeII       0.636       2.70    0.236  8.14e- 1    -4.65      5.92
#> 3 gradeIII      2.39        2.64    0.906  3.66e- 1    -2.79      7.57
#> 4 marker       -0.0379      1.28   -0.0296 9.76e- 1    -2.55      2.47
# Default CI
broom::tidy(mod1, conf.int = TRUE)
#> # A tibble: 4 x 7
#>   term        estimate std.error statistic  p.value conf.low conf.high
#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
#> 1 (Intercept)  46.1         2.29   20.1    2.26e-47    41.5      50.6 
#> 2 gradeII       0.636       2.70    0.236  8.14e- 1    -4.68      5.96
#> 3 gradeIII      2.39        2.64    0.906  3.66e- 1    -2.82      7.61
#> 4 marker       -0.0379      1.28   -0.0296 9.76e- 1    -2.57      2.49

# Wald CI
tbl_regression(
  x = mod1,
  tidy_fun = my_tidy,
  estimate_fun = partial(style_sigfig, digits = 4)
)
```

![image](https://user-images.githubusercontent.com/26774684/71114575-150dd980-219e-11ea-84f0-7e1ee47711ca.png)

``` r

# default CI
tbl_regression(
  mod1,
  estimate_fun = partial(style_sigfig, digits = 4)
)
```

![image](https://user-images.githubusercontent.com/26774684/71114616-248d2280-219e-11ea-90a4-3b851cbad575.png)


<sup>Created on 2019-12-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
- [ ] Update the vetted models help file with instructions about passing a user-defined tidier (e.g. must have arguments exponentiate and conf.level, etc.
- [ ]  Add example to the table gallery
