### ISSUE TITLE
tbl_regression error with coxph model built from formula object passed by "map"

### ISSUE THREAD

**Issue by emilyvertosick** [ddsjoberg/gtsummary#231]
If you are creating Cox models using "coxph" within "purrr::map" and you pass the formula to "coxph" as a formula object, tbl_regression cannot parse this and gives an error.

If you store the formula as a character object, and wrap it in "as.formula" in the "coxph" command, there is no error.

This also does not happen with a logistic glm model.

``` r
library(tidyverse)
#> Warning: package 'ggplot2' was built under R version 3.6.1
#> Warning: package 'tibble' was built under R version 3.6.1
#> Warning: package 'dplyr' was built under R version 3.6.1
library(gt)
library(gtsummary)
library(survival)

# Set up map statement to create different models
trial_map <-
  tibble(grade = c("I", "II", "III")) %>%
  mutate(df_model = map(grade, ~ trial %>% filter(grade == ..1)))

# Logistic model example

# Save out formulas
trial_glm_map <-
  trial_map %>%
  mutate(
    mv_formula_char = "death ~ trt + age + marker",
    mv_formula = map(1, ~ as.formula("death ~ trt + age + marker"))
  )

# If you pass it as a character, then it works
trial_glm_char <-
  trial_glm_map %>%
  mutate(
    mv_model_char =
      map2(
        mv_formula_char, df_model,
        ~ glm(as.formula(..1), data = ..2, family = "binomial")
      ),
    mv_tbl_char =
      map(
        mv_model_char,
        ~ tbl_regression(..1, exponentiate = TRUE)
      )
  )

# If you pass it as a formula, it works with logistic glm model
trial_glm_form <-
  trial_glm_map %>%
  mutate(
    mv_model_form =
      map2(
        mv_formula, df_model,
        ~ glm(..1, data = ..2, family = "binomial")
      ),
    mv_tbl_form =
      map(
        mv_model_form,
        ~ tbl_regression(..1, exponentiate = TRUE)
      )
  )

# Cox model example

# Save out formulas
trial_cox_map <-
  trial_map %>%
  mutate(
    mv_formula_char = "Surv(ttdeath, death) ~ trt + age + marker",
    mv_formula = map(1, ~ as.formula("Surv(ttdeath, death) ~ trt + age + marker"))
  )

# If you pass it as a character, then it works
trial_cox_char <-
  trial_cox_map %>%
  mutate(
    mv_model_char =
      map2(
        mv_formula_char, df_model,
        ~ coxph(as.formula(..1), data = ..2)
      ),
    mv_tbl_char =
      map(
        mv_model_char,
        ~ tbl_regression(..1, exponentiate = TRUE)
      )
  )

# If you pass it as a formula, it does not
trial_cox_form <-
  trial_cox_map %>%
  mutate(
    mv_model_form =
      map2(
        mv_formula, df_model,
        ~ coxph(..1, data = ..2)
      ),
    mv_tbl_form =
      map(
        mv_model_form,
        ~ tbl_regression(..1, exponentiate = TRUE)
      )
  )
#> Error in model.frame.default(formula = Surv(ttdeath, death) ~ trt + age + : the ... list contains fewer than 2 elements
```

<sup>Created on 2019-09-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by margarethannum** [comment]
@ddsjoberg  and I just discussed, and think it has to do with the Cox model environment not saving the global environment the same way as some other models do (like `glm()`, which you pointed out works with both character and formula input in this use case). Since `tbl_regression()` pulls some information out of the formula call using the base `model.frame()` method, and that seems to be incompatible with the mapped-formula input. 

Using the models from your example, try to pull out the model.frame to see the difference:
```
> head(model.frame(trial_glm_form$mv_model_form[[1]]))
  death     trt age marker
1     0    Drug  23  0.160
2     0    Drug  31  0.277
3     1    Drug  31  0.144
4     1 Placebo  42  0.513
5     0    Drug  63  0.060
6     1 Placebo  21  0.258
```

```
> head(model.frame(trial_cox_form$mv_model_form[[1]]))
Error in model.frame.default(formula = Surv(ttdeath, death) ~ trt + age +  : 
  the ... list contains fewer than 2 elements
```

Not sure if there is a quick way to work around this since it's not a gtsummary error; what do you think if we add a check to Cox models to ensure compatible input?

**Comment by ddsjoberg** [comment]
@emilyvertosick @margarethannum perhaps we could submit an issue on the survival GitHub page, just to show that standard modeling functions work, but not `coxph()`?

In the meantime, do you think it would be worth adding a check that `model.frame()` doesn't throw an error, and if it does print a message (as opposed to this add error)?

**Comment by ddsjoberg** [comment]
Hi @margarethannum @emilyvertosick 

I added this note when there is an error calling `model.frame()`.  One concern is that `model.frame()` is called very early (e.g. before broom::tidy() and other functions that are executed on the model object), and there are other reasons `model.frame()` could throw an error, for example if the user didn't pass a model object.  Regardless of the error, they will see this message.  But the actual error message is still printed below.  

What do you think?  Does it need to be modified?

``` r
library(tidyverse)
library(gtsummary)
library(survival)

# Set up map statement to create different models
tibble(grade = c("I", "II", "III")) %>%
  mutate(df_model = map(grade, ~ trial %>% filter(grade == ..1))) %>%
  mutate(
    mv_formula_char = "Surv(ttdeath, death) ~ trt + age + marker",
    mv_formula = map(1, ~ as.formula("Surv(ttdeath, death) ~ trt + age + marker")),
    mv_model_form =
      map2(
        mv_formula, df_model,
        ~ coxph(..1, data = ..2)
      ),
    mv_tbl_form =
      map(
        mv_model_form,
        ~ tbl_regression(..1, exponentiate = TRUE)
      )
  )
 
#> ✖ `tbl_regression()` utilizes `stats::model.frame()` which returned an error when called.
#>   This can occur when model objects are created within a functional programming framework,
#>   such as `lappy()` and `purrr::map()`. While regression model functions `lm()` and `glm()`
#>   do not return errors in this setting, not all regression modeling functions have been written
#>   with the same robustness. Please review the GitHub issue linked below for a possible solution.
#>   https://github.com/ddsjoberg/gtsummary/issues/231
#> Error in model.frame.default(formula = Surv(ttdeath, death) ~ trt + age + : the ... list contains fewer than 2 elements
```

<sup>Created on 2019-09-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
Updated error message incorporated in PR #233

**Comment by zabore** [comment]
I'm having this issue trying to pass a single model object fit with icenReg::ic_sp(). I wrote a custom tidier knowing that would be needed, but am getting this model.frame() error still and this solution doesn't help. Was there ever a more general solution to this issue?

**Comment by ddsjoberg** [comment]
Hmmm, can you post an example? I think we've been able to get them all working...perhaps I should update this post too...

**Comment by zabore** [comment]
Sure! Here's a dummy example. It was definitely helpful having the error message point me here.

```r
library(icenReg)
library(gtsummary)
library(dplyr)
set.seed(20201005)

# make up some interval censored data 
trial2 <-
  trial %>% 
  mutate(
    lint = case_when(
      death == 1 ~ runif(200) + 2,
      death == 0 ~ ttdeath
    ),
    rint = case_when(
      death == 1 ~ ttdeath,
      death == 0 ~ Inf
    )
  )

# fit the interval-censored survival model with icenReg::ic_sp()
mod1 <-
  ic_sp(
    Surv(lint, rint, type = "interval2") ~ trt,
    model = "ph",
    bs_samples = 3,
    data = trial2
    )

# Write a custom tidier
tidy_ic_sp <- function(x, exponentiate =  FALSE, conf.level = 0.95, ...) {
  tidy <-
    tibble(
    term = names(x[["coefficients"]]),
    estimate = x[["coefficients"]],
    std.error = sqrt(diag(x[["var"]])),
    statistic = summary(x)$summaryParameters[, "z-value"],
    p.value = summary(x)$summaryParameters[, "p"],
    conf.low = confint(x, level = conf.level)[, 1],
    conf.high = confint(x, level = conf.level)[, 2]
    )
  
  if (exponentiate == TRUE)
    tidy <- dplyr::mutate_at(tidy, vars(estimate, conf.low, conf.high), exp)
  
  tidy
}

# check that the custom tidier works
tidy_ic_sp(mod1, exponentiate = TRUE)


#> A tibble: 1 x 7
#>  term      estimate std.error statistic p.value conf.low conf.high
#>  <chr>       <dbl>    <dbl>    <dbl>  <dbl>    <dbl>      <dbl>
#>1 trtDrug B   1.17      0.232      0.690   0.490      0.745          1.85

# and pass to gtsummary::tbl_regression()
tbl_regression(
  mod1,
  exponentiate = TRUE,
  tidy_fun = tidy_ic_sp
)

#> x There was an error calling `stats::model.frame(x)`.
#>   
#>   Most likely, this is because the argument passed in `x =` was
#>   misspelled, does not exist, or is not a regression model.
#>   
#>   Rarely, this error may occur if the model object was created within
#>   a functional programming framework (e.g. using `lappy()`, `purrr::map()`, etc.).
#>   Review the GitHub issue linked below for a possible solution.
#>   https://github.com/ddsjoberg/gtsummary/issues/231
#>   [Copied to clipboard]
#> Error: Error in Surv(lint, rint, type = "interval2"): object 'lint' not found
```

**Comment by ddsjoberg** [comment]
@zabore This error is something a bit different from what is described on this post.  The problem here is that the `ic_sp()` model doesn't have a method defined for `model.frame()`.  We can solve it by writing a somewhat silly method that just returns the original data frame.

This will work now, but I should warn you that current dev version the model will also need a `term()` method. So this solution is note 100% future proof, but the same approach will work by defining your own term method. 

``` r
library(icenReg)
library(gtsummary)
library(dplyr)

set.seed(20201005)

# make up some interval censored data 
trial2 <-
  trial %>% 
  mutate(
    lint = case_when(
      death == 1 ~ runif(200) + 2,
      death == 0 ~ ttdeath
    ),
    rint = case_when(
      death == 1 ~ ttdeath,
      death == 0 ~ Inf
    )
  )

# fit the interval-censored survival model with icenReg::ic_sp()
mod1 <-
  ic_sp(
    Surv(lint, rint, type = "interval2") ~ trt,
    model = "ph",
    bs_samples = 3,
    data = trial2
  ) 

# there is no method for this model type
model.frame(mod1)
#> Error in Surv(lint, rint, type = "interval2"): object 'lint' not found

# make a silly method that just returns the original object
model.frame.ic_ph <- function(x) trial2

# Write a custom tidier
tidy_ic_sp <- function(x, exponentiate =  FALSE, conf.level = 0.95, ...) {
  tidy <-
    tibble(
      term = names(x[["coefficients"]]),
      estimate = x[["coefficients"]],
      std.error = sqrt(diag(x[["var"]])),
      statistic = summary(x)$summaryParameters[, "z-value"],
      p.value = summary(x)$summaryParameters[, "p"],
      conf.low = confint(x, level = conf.level)[, 1],
      conf.high = confint(x, level = conf.level)[, 2]
    )
  
  if (exponentiate == TRUE)
    tidy <- dplyr::mutate_at(tidy, vars(estimate, conf.low, conf.high), exp)
  
  tidy
}

# check that the custom tidier works
tidy_ic_sp(mod1, exponentiate = TRUE)
#> # A tibble: 1 x 7
#>   term      estimate std.error statistic p.value conf.low conf.high
#>   <chr>        <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>
#> 1 trtDrug B     1.17     0.232     0.690   0.490    0.745      1.85

# and pass to gtsummary::tbl_regression()
tbl_regression(
  mod1,
  exponentiate = TRUE,
  tidy_fun = tidy_ic_sp
) %>%
  as_kable() # converting to kable so it renders in github
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>exp(Beta)</strong></th>
<th style="text-align: left;"><strong>95% CI</strong></th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Chemotherapy Treatment</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Drug A</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Drug B</td>
<td style="text-align: left;">1.17</td>
<td style="text-align: left;">0.75, 1.85</td>
<td style="text-align: left;">0.5</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by zabore** [comment]
Okay I see. Thank you! I wonder if the error message should include a bit about checking if a model.frame() and term() method are defined for the model of interest?

**Comment by ddsjoberg** [comment]
this section of code has been exported to a new package in the gtsummary dev version called broom.helpers. https://github.com/larmarange/broom.helpers

This is the updated message that includes a note about

![image](https://user-images.githubusercontent.com/26774684/95241339-9bea7c00-07db-11eb-9629-10b7dec14ba3.png)

**Comment by zabore** [comment]
Awesome! That makes a lot of sense to me.
