### ISSUE TITLE
Add as_tibble() function

### ISSUE THREAD

**Issue by jeanmanguy** [ddsjoberg/gtsummary#245]
Hi,

In many cases exporting the table to latex/pdf is enough but sometimes journals require tables in CSV or even in excel formats. I wonder if it's possible to add the support for {openxlsx}. As far as I know it is not possible with knitr::kable.

**Comment by ddsjoberg** [comment]
Hi @jeanmanguy !

I don't have any plans to support direct output to excel via {openxlsx} at this time.  We are focused primarily on support for {gt}.  BUT, I think the author of {gt} did say in a talk at RStudio Conference earlier this year they plan support excel sometime in the future (the video of the talk is on the conference website if you're interested).

In the meantime, you could use something like the function below.  It'll take any gtsummary object and convert it to a data frame or tibble (these are just the last few lines of the `as_kable()` function).  From there you can output in any format you'd like!  Would this work for you?  If so, I can add to my list to create a generic `as_tibble()` function that would convert the gtsummary tables to data frames and add it to the package.

``` r
library(gtsummary)
library(tidyverse)

# convert tbl_summary into standard tibble/data frame
gtsummary_to_tibble <- function(x) {
  # saving vector of column labels
  col_labels <-
    x$table_header %>%
    filter(hide == FALSE) %>%
    pull(label)
  
  x$kable_calls %>%
    # removing NULL elements
    compact() %>%
    glue::glue_collapse(sep = " %>% ") %>%
    # converting strings into expressions to run
    parse(text = .) %>%
    eval() %>%
    # performing final modifcations prior to returning tibble object
    mutate_all(~ ifelse(is.na(.), "", .)) %>%
    rlang::set_names(col_labels)
}
trial[c("trt", "age", "grade")] %>%
  tbl_summary(by = trt) %>% 
  gtsummary_to_tibble()
#> # A tibble: 6 x 3
#>   `**Characteristic**` `**Drug**, N = 107` `**Placebo**, N = 93`
#>   <chr>                <chr>               <chr>                
#> 1 Age, yrs             47 (39, 58)         45 (36, 54)          
#> 2 Unknown              6                   3                    
#> 3 Grade                ""                  ""                   
#> 4 I                    38 (36%)            29 (31%)             
#> 5 II                   34 (32%)            24 (26%)             
#> 6 III                  35 (33%)            40 (43%)
```

<sup>Created on 2019-10-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jeanmanguy** [comment]
Hi @ddsjoberg,

Thank you,  Ididn't know about the talk, but yes the support of excel would be neat, I crafted my case-specific functions to print tables like {gtsummary}'s with {openxlsx} and that's very painful to do.

That's an interesting solution. It may need some more work to remove the markdown formatting but it may be easier to use than the output of `as_gt()`. At least i could be written to a CSV file, and finish the formatting by hand in Excel if a journal asks.

**Comment by ddsjoberg** [comment]
@jeanmanguy I'll add it to the to do list for the package, and track it here, so you'll know when it's ready.

If you remove the `rlang::set_names(col_labels)` from the last line, it won't add the markdown-formatted headers. But you'll be left with the bare column names.

**Comment by jeanmanguy** [comment]
Thank you. 

If you use `bold_p` it also adds markdown symbols in the tibble (strangely different signs than in the header `**` vs `__`)

**Comment by ddsjoberg** [comment]
Added to the master branch in PR #246
