### ISSUE TITLE
tbl_regression handling of tidiers

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#247]
There are two primary functions that contain tidiers that are used in gtsummary: `broom::tidy()` and `broom.mixed::tidy()`.

But broom recommends that if possible the tidier for an object stays in the package that creates the object.  To make our package generalizable, we could add an argument to pass the tidier function.

I am thinking ahead to when our competing risks package is ready.  The tidier will live in the same package, and therefore would not be discoverable by gtsummary.

```r
tbl_regression(
  x = model1,
  tidy_fun = riskybiz::tidy
)
```

In the same vein of making this generalizable, rather than hard-coding which tidier to use (broom vs broom.mixed), I wonder if we can list the methods available and broom and broom.mixed and match it to the object passed by the user.  This would allow the package to support the methods in broom.mixed we haven't hard-coded yet.

**Comment by ddsjoberg** [comment]
From @michaelcurry1123 

here is a way to pull out methods for each function and package without loading them: 
```
f1 <- function(x,y){
 x1 <- as.vector(do.call("methods", list(substitute(x::y))))
 x2 <- substr(x1,6,nchar(x1))
 return(x2)
}
f1(broom,tidy)
```

This will help determine which functions have which methods .

**Comment by ddsjoberg** [comment]
Perhaps there is a way we can 
1. Check if the object has a `broom::tidy()` method.
1. Check if the object has a `broom.mixed::tidy()` method.
1. Check if the object has any `tidy()` method in the search path.  

Then we would not have add an additional argument to the function?

**Comment by margarethannum** [comment]
How would we feel about having the user specify a tidier and any additional arguments for that tidier? (and just have those be "NULL" if they want to use our default). 

I've been thinking through  the problem and think it's possible for us to just use 

```
    tidy_bit <- do.call("tidy",
                        args = list(x, exponentiate = exponentiate,
                                    conf.level = conf.level, conf.int = T)
                        # we can optionally add a "tidy.args" argument to the main
                        # function down the line to allow for additional args?
                        )
```

I implemented the changes in https://github.com/margarethannum/gtsummary/tree/247-tidier-search-update and it does work with `riskybiz::tidy`.

**Comment by margarethannum** [comment]
So in this way it doesn't even really require the user to specify although if they do specify it may help with some of the checks and if they need additional arguments for whatever tidier they use.

**Comment by ddsjoberg** [comment]
Nice! My first reaction is that I would only want one input for the tidier function, and leave out an additional argument for the tidier arguments...just to keep the number of arguments low.  The user can still pass other arguments in their tidiers with `tidy_fun = purrr::partial(riskybiz::tidy, other = "args")`.  
What do you think?  Let's discuss after seminar today?

**Comment by margarethannum** [comment]
#315
