### ISSUE TITLE
No variable label for logical variables.

### ISSUE THREAD

**Issue by jwilliman** [ddsjoberg/gtsummary#248]
This package looks great! 

Currently, if a logical variable is included in the regression it's name is replaced with NA in the output table. This occurs with `kable` or `gt` style of output. It does not seem to depend if the variable is labelled or not, and can't be overridden by the `label` option. 

```r

library(survival)
library(gtsummary)

data(trial)
trial$drug = trial$trt == "Drug"

m1 = glm(response ~ age + stage + grade + trt, trial, family = binomial(link = "logit"))
tbl_regression(m1)

m2 = glm(response ~ age + stage + grade + drug, trial, family = binomial(link = "logit"))
tbl_regression(m2)

attr(trial$drug, "label") <- "Drug"
m3 = glm(response ~ age + stage + grade + drug, trial, family = binomial(link = "logit"))
tbl_regression(m3)
tbl_regression(m3, label = list("drug" ~ "Drug"))

m4 = glm(response ~ age + stage + grade + factor(drug), trial, family = binomial(link = "logit"))
tbl_regression(m4, label = list("factor(drug)" ~ "Drug"))

```

Cheers :)

**Comment by ddsjoberg** [comment]
@jwilliman !  Thank you so much for the bug report and the reprex!  Much much appreciated!

I just pushed an update that should fix this labeling bug.
