### ISSUE TITLE
New function tbl_crosstab() ?

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#257]
Should we create a new function that simply cross tabulates data and prints in a nicely formatted table?

There would be a lot of overlap with `tbl_summary()` but there are certainly times a need a more basic  cross tab table that is not possible with  `tbl_summary()` .  Something to think on....

**Comment by michaelcurry1123** [comment]
I know I commented on this in slack but the janitor package has an `adorn_crosstab()` function that has this functionality.  https://cran.r-project.org/web/packages/janitor/janitor.pdf . I think it integrates well tidyverse.

**Comment by ddsjoberg** [comment]
@michaelcurry1123 the janitor package's functions are pretty great, and the results are pretty close to what anyone would need. I didn't see easy ways to modify the statistics presented (rounding, etc.).

@karissawhiting you mentioned wanting this functionality recently.  Would janitor be good enough for what you need?

One possible solution that would be pretty easy to implement, would be to add a function `add_margin()` that would
- Check the input is indeed an n by m table.
- Run `add_overall()` to add the row margins
- Calculate the column margins and add those statistics as well.

We could include an option whether to add row AND column margins, or either one only.  We could right it in such a way that it would already be compatible with `inline_text()`.

**Comment by michaelcurry1123** [comment]
@karissawhiting @ddsjoberg  if the janitor package isn't sufficient we might be able to modify the functions to add in additional functionality (e.g. modify stats or rounding and append on methods so that gtsummary accepts them?)  this is more of a question than anything else.

**Comment by karissawhiting** [comment]
@ddsjoberg @michaelcurry1123 these janitor options are great! Sidenote: It looks like `adorn_crosstab()` is deprecated in favor of `tabyl()` plus the `adorn_*()` functions.  

I do still think there would be value in adding crosstable functionality to gtsummary. This would allow users to leverage some existing gtsummary features for their crosstables, like `inline_text()` and the use of labelled data. 

I like the solution Dan proposed. Additionally, I think we could consider adding a wrapper function with those options as default that also adds a `tab_spanner()`.

**Comment by karissawhiting** [comment]
Discussed with @ddsjoberg , and decided to make a simple wrapper function `tbl_cross()` with arguments to chose margin totals to calculate (col, row, both), what types of percents to display (cell, row, col), and whether or not to include missing values. 

This will use `tbl_summary` and `add_overall()`with some light gt customization for default display.

**Comment by ddsjoberg** [comment]
Merged in https://github.com/ddsjoberg/bstfun/pull/1
