### ISSUE TITLE
include figures in {gtsummary} help files

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#27]
The gt output tables don't display in the online help files.

Look at the gt package help pages to see who they display their examples.  It looks like they are displaying image files.
Perhaps one solution is to add all the code to create the tables in the data-raw folder, and use code to save image of the tables.  The help files will then import the images.

**Comment by ddsjoberg** [comment]
Updates to the {gt} package that will hopefully will be live soon, will help make the documentation of {gtsummary} results much easier.
https://github.com/rstudio/gt/pull/257

**Comment by ddsjoberg** [comment]
Is there a way to incorporate the examples in the README.rmd file in this automated process?

**Comment by karissawhiting** [comment]
Yes, that should be doable.
