### ISSUE TITLE
tbl_summary: Allow by variable to have missing values

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#279]
I have found it annoying that the `by=` argument variable cannot have missing values.
1. Should we exclude missing values and print a note about the number of obs dropped?
2. Should we make an explicit missing category and include them?

I am leaning towards 1, and printing a note saying to use `fct_explicit_na()` is user wants to include a column for missing values.  Removing by hand is particularly annoying you've labelled your data, and the filter deletes the labels.

@margarethannum @karissawhiting thoughts?

**Comment by karissawhiting** [comment]
I also like option 1! Agree the function should run even with NA's.
