### ISSUE TITLE
add_p(): When p value can't be calculated, "Error" is thrown but function evaluates anyway

### ISSUE THREAD

**Issue by karissawhiting** [ddsjoberg/gtsummary#283]
When a p-value can't be calculated "Error" is thrown to user but function continues to evaluate and table is still rendered. This is helpful, but I would expect the function to stop when "Error" is thrown. We could consider removing "Error" from the warning message.

**Comment by ddsjoberg** [comment]
@karissawhiting 

Here is the the language that is printed when `add_p()` encounters an error or warning, which is printed as a message.

```r
  # printing warning and errors as message
  warning = function(w) {
    message(glue("Warning in 'add_p()' for variable '{variable}' ",
                 "and test '{test}', p-value omitted:\n", as.character(w)))
    return(NULL)
  },
  error = function(e) {
    message(glue("Error in 'add_p()' for variable '{variable}' ",
                 "and test '{test}', p-value omitted:\n", as.character(e)))
    return(NULL)
  })
```

Perhaps better wording would be, "There was an error calculating the p-value for {variable} (printed below), and the associated p-value has been omitted from the output."

Does that sound ok to you?

**Comment by ddsjoberg** [comment]
@karissawhiting do you want to do this for v1.2.4?

**Comment by karissawhiting** [comment]
Sure!

**Comment by ddsjoberg** [comment]
I think this section of code should be updated to use `withCallingHandlers()` for handling warnings and messages and `tryCatch()` for the errors.  I just got done reading the condition handling chapter of Advanced R for my team's book club haha https://adv-r.hadley.nz/conditions.html

One annoying thing that is happening now with `tryCatch()` for the warnings, is that the p-values are not  included in the output.  But it's common that chisq.test throws a warning about a mis-estimation when cell counts are low, and the p-value is not included.  It would be better to get the warning and have the p-value printed as well. `tryCatch()` stops running the moment it encounters the error/warning/message making the p-value unavailable, while `withCallingHandlers()` continues to evaluate after the condition is encountered.

**Comment by karissawhiting** [comment]
It looks like `WithCallingHandlers()` along with `invokeRestart("muffleWarning")` does the trick. PR coming shortly. 

Just noting here that we also discussed using `purrr::safely()`/ `purrr::quietly()` as another way to handle this issue and can try that if the first way doesn't work as expected.
