### ISSUE TITLE
tbl_uvregression() - Error when NSE arguments passed in method.args

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#322]
When non-standard evaluation elements are passed in `method.args=` an error occurs in `tbl_uvregression()`.  Rather than passing `method.args` to the function passed in `method=`, the input needs to be captured (likely with `rlang::enexpr()`, or a related quoting function) and later unquoted when they are passed.

``` r
library(gtsummary)

# error for tbl_uvregression
na.omit(trial) %>%
  tbl_uvregression(
    y = age, 
    method = geepack::geeglm,
    method.args = list(
      id = response,
      corstr = "exchangeable"
    )
  )
#> Error in as.list.environment(environment()): object 'response' not found
```
<sup>Created on 2019-12-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

While the bug is being fixed, users may create a list of univariate regression models, then stack the results with `tbl_stack()`.
```r
df_results <-
  tibble(
    covariates = c("marker", "grade"),         # list of covariates
    formula = str_glue("age ~ {covariates}"),  # character formula
    model = map(                               # build univariate model
      formula,
      ~geepack::geeglm(
        as.formula(.x),
        data = na.omit(trial),
        id = response,
        corstr = "exchangeable"
      ) %>%
        tbl_regression()                       # creating gtsummary model object
    )
  )

tbl_stack(df_results$model)
```

**Comment by stephaniegail** [comment]
Hi,  

We are having a different issue with the same combination of functions.  We are trying to run:

trial %>% 
  select(response, age, stage) %>% 
  tbl_uvregression(
    method= geepack::geeglm,
    method.args = list (family=binomial, id = stage, corstr="ar1"),
    y = response,
    exponentiate = TRUE,
    pvalue_fun = ~style_pvalue(.x,digits=2)
  )


And getting the following error:

Error in `mutate()`:
! Problem while computing `model = map(...)`.
Caused by error in `vapply()`:
! values must be length 1,
 but FUN(X[[1]]) result is length 2
Run `rlang::last_error()` to see where the error occurred.

> rlang::last_error()
<error/dplyr:::mutate_error>
Error in `mutate()`:
! Problem while computing `model = map(...)`.
Caused by error in `vapply()`:
! values must be length 1,
 but FUN(X[[1]]) result is length 2
---
Backtrace:
  1. trial %>% select(response, age, stage) %>% ...
 42. glue `<fn>`("v5")
 44. cli .transformer(expr, env)
 46. cli:::inline_generic(app, val, style = style)
 47. cli:::vcapply(xx, fmt)
 48. base::vapply(X, FUN, FUN.VALUE = character(1), ..., USE.NAMES = USE.NAMES)
Run `rlang::last_trace()` to see the full context.

Any help would be much appreciated!

Best,
Stephanie

**Comment by ddsjoberg** [comment]
Hi @stephaniegail , it doesn't seem that this particular model can be estimated by geepack. Can you update the example?

``` r
library(gtsummary)
#> #Uighur
packageVersion("gtsummary")
#> [1] '1.6.0'

geepack::geeglm(response ~ age, data = trial, family = binomial, id = stage, corstr = "ar1")
#> Error in geese.fit(xx, yy, id, offset, soffset, w, waves = waves, zsca, : nrow(zsca) and length(y) not match
```

<sup>Created on 2022-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by stephaniegail** [comment]
My apologies, this works:

> m1 <- geeglm(response ~ grade, data=trial,family=binomial(link="logit"), id=stage, corstr="ar1")
> m1

Call:
geeglm(formula = response ~ grade, family = binomial(link = "logit"), 
    data = trial, id = stage, corstr = "ar1")

Coefficients:
(Intercept)     gradeII    gradeIII 
-0.76426663 -0.09938336  0.07789280 

Degrees of Freedom: 193 Total (i.e. Null);  190 Residual

Scale Link:                   identity
Estimated Scale Parameters:  [1] 0.9999565

Correlation:  Structure = ar1    Link = identity 
Estimated Correlation Parameters:
    alpha 
0.1100954 

Number of clusters:   143   Maximum cluster size: 4 

> tbl_regression(m1)
Characteristic | log(OR)1 | 95% CI1 | p-value
-- | -- | -- | --
Grade |   |   |  
I | — | — |  
II | -0.10 | -0.86, 0.67 | 0.8
III | 0.08 | -0.64, 0.79 | 0.8
1 OR = Odds Ratio, CI = Confidence Interval

#But this doesn't:

> tbl_uvregression(m1)
Error: `data` argument must be a data frame or survey object.

So how can we pass in the "link='logit'" argument?
Thanks,
Stephanie

**Comment by ddsjoberg** [comment]
Hi @stephaniegail , Please review the `tbl_uvregression()` help file for details on its use. You've passed a model object, and as the error message indicates, you must pass a data frame.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.6.0'

geepack::geeglm(
  response ~ grade, 
  data = trial, 
  family = binomial(link="logit"), 
  id = stage, 
  corstr = "ar1"
) %>%
  tbl_regression(exponentiate = TRUE) %>%
  as_kable() # convert to kable to display on GH
```

| **Characteristic** | **OR** | **95% CI** | **p-value** |
|:-------------------|:------:|:----------:|:-----------:|
| Grade              |        |            |             |
| I                  |   —    |     —      |             |
| II                 |  0.91  | 0.42, 1.95 |     0.8     |
| III                |  1.08  | 0.53, 2.21 |     0.8     |

``` r
trial %>%
  tbl_uvregression(
    y = response, 
    method = geepack::geeglm,
    method.args = list(family = binomial(link="logit"), id = stage, corstr = "ar1"), 
    include = grade,
    exponentiate = TRUE
  ) %>%
  as_kable() # convert to kable to display on GH
```

| **Characteristic** | **N** | **OR** | **95% CI** | **p-value** |
|:-------------------|:-----:|:------:|:----------:|:-----------:|
| Grade              |  193  |        |            |             |
| I                  |       |   —    |     —      |             |
| II                 |       |  0.91  | 0.42, 1.95 |     0.8     |
| III                |       |  1.08  | 0.53, 2.21 |     0.8     |

<sup>Created on 2022-06-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by zaihra** [comment]
Hi 
I tried running the below code below for "trial dataset" ( as I was getting error for my own data set) 
data(trial)
str(trial)
trial %>%
  select(response, age, grade) %>%
  tbl_uvregression(
    method = glm,
    y = response,
    method.args = list(family = binomial),
    exponentiate = TRUE,
    pvalue_fun = ~style_pvalue(.x, digits = 2)
  ) %>%
  add_global_p() %>%  # add global p-value 
  add_nevent() %>%    # add number of events of the outcome
  add_q() %>%         # adjusts global p-values for multiple testing
  bold_p() %>%        # bold p-values under a given threshold (default 0.05)
  bold_p(t = 0.10, q = TRUE) %>% # now bold q-values under the threshold of 0.10
  bold_labels()
it still gives below error.
Error in select(., response, age, grade) : 
  unused arguments (response, age, grade)

 Creating univariate regression tables using various datasets was working for me on a different computer  until a day ago so not sure what happened on my laptop. I have update R RStudio and all packages, but no matter what dataset I use, it spits above error.

Please advice.

Thanks

**Comment by ddsjoberg** [comment]
Dear @zaihra, The error appears in the `select()` call before you run any gtsummary functions. Please re-post including a _minimal_ reproducible example (aka a reprex). https://reprex.tidyverse.org/

**Comment by zaihra** [comment]
Hi Dan @ddsjoberg ,
I can't share any details of my data since its patient related stuff, however, I  tried to reproduce the error using trial data form the package.
require(gtsummary)
require(tidyverse)

data(trial)
str(trial)
trial %>%
  select(response, age, grade) %>%
  tbl_uvregression(
    method = glm,
    y = response,
    method.args = list(family = binomial),
    exponentiate = TRUE,
    pvalue_fun = ~style_pvalue(.x, digits = 2)
  ) %>%
  add_global_p() %>%  # add global p-value 
  add_nevent() %>%    # add number of events of the outcome
  add_q() %>%         # adjusts global p-values for multiple testing
  bold_p() %>%        # bold p-values under a given threshold (default 0.05)
  bold_p(t = 0.10, q = TRUE) %>% # now bold q-values under the threshold of 0.10
  bold_labels()
```


I checked the str of trial is nibble ( and it has worked always until yesterday, the only difference today is I am using my MacBook instead of iMac. But I am at my wits end.
The error sticks around no matter which data set I use. 
tibble [200 × 8] (S3: tbl_df/tbl/data.frame)
 $ trt     : chr [1:200] "Drug A" "Drug B" "Drug A" "Drug A" ...
  ..- attr(*, "label")= chr "Chemotherapy Treatment"
 $ age     : num [1:200] 23 9 31 NA 51 39 37 32 31 34 ...
  ..- attr(*, "label")= chr "Age"
 $ marker  : num [1:200] 0.16 1.107 0.277 2.067 2.767 ...
  ..- attr(*, "label")= chr "Marker Level (ng/mL)"
 $ stage   : Factor w/ 4 levels "T1","T2","T3",..: 1 2 1 3 4 4 1 1 1 3 ...
  ..- attr(*, "label")= chr "T Stage"
 $ grade   : Factor w/ 3 levels "I","II","III": 2 1 2 3 3 1 2 1 2 1 ...
  ..- attr(*, "label")= chr "Grade"
 $ response: int [1:200] 0 1 0 1 1 0 0 0 0 0 ...
  ..- attr(*, "label")= chr "Tumor Response"
 $ death   : int [1:200] 0 0 0 1 1 1 0 1 0 1 ...
  ..- attr(*, "label")= chr "Patient Died"
 $ ttdeath : num [1:200] 24 24 24 17.6 16.4 ...
  ..- attr(*, "label")= chr "Months to Death/Censor"
 **Error in select(., response, age, grade) : 
unused arguments (response, age, grade)**

**Comment by ddsjoberg** [comment]
@zaihra: 
Please review the reprex site and post a proper reprex (aka it runs in a fresh environment, copies the results to your clipboard which can be copied directly into a github issue). Also, ensure the example is minimal, meaning it contains no extraneous code that is not needed to illustrate your issue. From the text of your error message, it looks like this would be `trial %>% select()` only---meaning the error occurs before you try to run a single function from gtsummary.

**Comment by zaihra** [comment]
trial %>%
  select(response, age, grade) %>%
  tbl_uvregression(
    method = glm,
    y = response,
    method.args = list(family = binomial),
    exponentiate = TRUE,
    pvalue_fun = ~style_pvalue(.x, digits = 2)
  ) %>%
  add_global_p() %>%  # add global p-value 
  add_nevent() %>%    # add number of events of the outcome
  add_q() %>%         # adjusts global p-values for multiple testing
  bold_p() %>%        # bold p-values under a given threshold (default 0.05)
  bold_p(t = 0.10, q = TRUE) %>% # now bold q-values under the threshold of 0.10
 bold_labels()

**Comment by ddsjoberg** [comment]
@zaihra did you review the reprex website? This is not a proper reprex. You can Google to find video explainers if reprex too if you found the website unclear. Is this the absolute minimal amount of code to illustrate the error you're seeing? I suspect it is not.

**Comment by zaihra** [comment]
@ddsjoberg Thanks a lot for helping me out Dan, I really appreciate it. I tried reading reprex, but I am not sure if I understand it very well.  When I follow what's in the tutorial and comment bold_lables (), i.e. , last line of my code it compiles but no output table is produced.  It spits what you see below the code and the below msg

.
#> Error in eval(expr, envir, enclos): object '.' not found

`
trial %>%
  select(response, age, grade) %>%
  tbl_uvregression(
    method = glm,
    y = response,
    method.args = list(family = binomial),
    exponentiate = TRUE,
    pvalue_fun = ~style_pvalue(.x, digits = 2)
  ) %>%
  add_global_p() %>%  # add global p-value 
  add_nevent() %>%    # add number of events of the outcome
  add_q() %>%         # adjusts global p-values for multiple testing
  bold_p() %>%        # bold p-values under a given threshold (default 0.05)
  bold_p(t = 0.10, q = TRUE) %>% # now bold q-values under the threshold of 0.10
# bold_labels()
`
reprex()
## ℹ Non-interactive session, setting `html_preview = FALSE`.
## ℹ Rendering reprex...
## CLIPR_ALLOW has not been set, so clipr will not run interactively


********************
If I dont comment bold_labels() I get the attached  error and it wont even compile
[Error in select.docx](https://github.com/ddsjoberg/gtsummary/files/9944738/Error.in.select.docx)

**Comment by ddsjoberg** [comment]
@zaihra what do you see if you run only the first two lines, the 'trial %>% select()' portion?

**Comment by zaihra** [comment]
@ddsjoberg 
Error in select(., response, age, grade) : 
  unused arguments (response, age, grade)

**Comment by ddsjoberg** [comment]
@zaihra this suggests the error occurs **before** you run any gtsummary functions. This is not an issue using the gtsummary package.

**Comment by zaihra** [comment]
@ddsjoberg I figured the issue. This error occurs because I was attempting to use the select() function from the dplyr package in R but also had the MASS package loaded.
Thank you so much for your time and help. I really appreciate it.
