### ISSUE TITLE
tbl_regression does not work with rcspline.eval(inclx = TRUE)

### ISSUE THREAD

**Issue by emilyvertosick** [ddsjoberg/gtsummary#337]
When using rcspline.eval to create splines within the formula, tbl_regression does not work if specifying "inclx = TRUE". It does work correctly if the inclx option is omitted or set to FALSE.

``` r
library(tidyverse)
library(gtsummary)
library(Hmisc)
#> Loading required package: lattice
#> Loading required package: survival
#> Loading required package: Formula
#> 
#> Attaching package: 'Hmisc'
#> The following objects are masked from 'package:dplyr':
#> 
#>     src, summarize
#> The following objects are masked from 'package:base':
#> 
#>     format.pval, units

model4a <-
  glm(response ~ grade + rcspline.eval(marker, nk = 4, norm = 0),
      data = trial[c("response", "grade", "marker")] %>% na.omit(),
      family = "binomial")

model4a %>% tbl_regression(exponentiate = TRUE)
```

![image](https://user-images.githubusercontent.com/49212917/72089194-96f2ad80-32d9-11ea-809b-0974e462afa3.png)

``` r


model4b <-
  glm(response ~ grade + rcspline.eval(marker, nk = 4, norm = 0, inclx = TRUE),
      data = trial[c("response", "grade", "marker")] %>% na.omit(),
      family = "binomial")

model4b %>% tbl_regression(exponentiate = TRUE)
#> Warning in regularize.values(x, y, ties, missing(ties)): collapsing to unique
#> 'x' values

#> Warning in regularize.values(x, y, ties, missing(ties)): collapsing to unique
#> 'x' values
#> Error in approx(sp$y, sp$x, xout = cutoff): need at least two non-NA values to interpolate
```

<sup>Created on 2020-01-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
I came across a similar issue recently.  It seems to be an issue using `rcspline.eval()` and calculating the confidence intervals with the base R function `confint()` (which is what `broom::tidy()` is using in the background).  Below is an example of the same issue using `glm()`.

The question now, I presume, is what we should do about it.  A couple of things come to mind:
1. We could check the formula of the input model for functions (any function), and print a message that we recommend that all values are calculated in the data frame before passing it to modeling object.  This could help catch future errors with other functions we don't even use!  Recipes doesn't allow functions in the formulas either (albeit, a different reason).
  ``` r
  recipes::recipe(Species ~ Sepal.Length + log(Sepal.Width), data = iris)
  #> Error: No in-line functions should be used here; use steps to define baking actions
  ```

2. We could catch errors when running the `tidy()` function, and print a message saying there was an error in the tidier, and you need to figure it out.

3. Any other ideas @emilyvertosick @margarethannum @karissawhiting 




``` r
library(gtsummary)
library(Hmisc)

glm(response ~ grade + rcspline.eval(marker, nk = 4, norm = 0, inclx = TRUE), 
    trial,
    family = binomial) %>% 
  confint()
#> Waiting for profiling to be done...
#> Warning in regularize.values(x, y, ties, missing(ties)): collapsing to unique
#> 'x' values

#> Warning in regularize.values(x, y, ties, missing(ties)): collapsing to unique
#> 'x' values
#> Error in approx(sp$y, sp$x, xout = cutoff): need at least two non-NA values to interpolate
```

<sup>Created on 2020-01-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
