### ISSUE TITLE
Documentation updates/website improvement

### ISSUE THREAD

**Issue by margarethannum** [ddsjoberg/gtsummary#340]
I'm working on various updates to the documentation to improve the website. 

- [x] Modify README language so website homepage (hopefully) performs better with search engines
- [x] Add bullets to homepage to describe various functionality in a readible way
- [x] Be selective on where technical descriptions are included (move away from top of homepage - relegate to other sections)
- [x] Add more cross-linking within the site
- [x] Update README to remove the `<img src...>` and create the table examples on the spot (now that that functionality is capable)

- [x] Add "bare bones" table to homepage to show the simplest capability

**Comment by margarethannum** [comment]
- [ ] Create a "style" family of functions? (so we can link to `style_percent`, `style_pvalue` etc

- [ ] Remove standard eval functions from References since they are deprecated

- [ ] Decide on a good place to include an example of using the {labelled} package (& if it's necessary in our documentation)

- [ ] Design & include a cute workflow diagram?

**Comment by ddsjoberg** [comment]
@margarethannum Another documentation item that we could update, it removing some unnecessary items from the Reference page on the pkgdown page.  Like these S3 functions..what do you think?
![image](https://user-images.githubusercontent.com/26774684/72227725-e51fdf00-356d-11ea-91e1-47cae834a245.png)

**Comment by ddsjoberg** [comment]
@margarethannum The roxygen documentation recommends we document any options the package uses in the package level Rd file. (https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html)  We have the global variable vignette, but do you think we should include reference to the vignette in the Rd file?

**Comment by margarethannum** [comment]
@ddsjoberg as discussed let's keep the S3 methods there for now to avoid a lot of red messages later when the build is happening. 

Regarding global options: I've looked at package documentation for a few packages (dplyr, forcats, tidyr) and I only see one example of a global package option being listed on the package rd! So I think fine to leave out for now unless you feel very strongly.
