### ISSUE TITLE
Add 'difftime' to accepted classes in 'tbl_summary()'

### ISSUE THREAD

**Issue by oranwutang** [ddsjoberg/gtsummary#343]
Hi,

I have a dataframe where I calculated (via mutate(newVariable=difftime(datetime1, datetime2, "mins"))) a variable whith the difference between two datetimes columns, that variable is stored in the tibble with class "difftime" and an attribute specifiying "mins". 

If you try to get a tbl_summary() of that variable you get the following error:

"Error: All columns in a tibble must be 1d or 2d objects:
"* Column `stat` is NULL""

I solved it by passing the new variable to as.numeric() and it worked perfectly, obviously with the consequent loss of attributes from the column

I'm opening the issue in order to ask you that if tbl_summary() encounters with this kind of situation then it should at least give a better information about the problem to the user (something like: "you cannot pass columns with attributes to this function") or in the best case parse the column to numeric without extra intervention from the user.

Thanks in advance, and congratulations for this great package!

**Comment by ddsjoberg** [comment]
Hi @oranwutang !

At the moment the package supports columns of class 'character', 'factor', 'numeric', 'logical', or 'integer'.  It's not a problem to add the class 'difftime'.  

``` r
library(tidyverse)
library(lubridate)
library(gtsummary)

df <-
  tibble(
  date1 = seq(as_date("2000-01-01"), as_date("2010-01-01"), by = 1500),
  date2 = seq(as_date("2005-01-01"), as_date("2015-01-01"), by = 1500),
  diff = difftime(date2, date1)
) 
class(df$diff)
#> [1] "difftime"

tbl_summary(df)
#> Column(s) 'date1', 'date2', and 'diff' omitted from output. Expecting class 'character', 'factor', 'numeric', 'logical', or 'integer'.
#> Error: All columns in a tibble must be 1d or 2d objects:
#> * Column `stat` is NULL
```

<sup>Created on 2020-01-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
OK @oranwutang !  This update is in the dev version of the package on GitHub.  If you could install the package from GitHub and report back if it's working as you expected, it would much appreciated 🔥

**Comment by oranwutang** [comment]
Hi @ddsjoberg, I have tried with the dev version and it works properly.

Thanks for your quick response and for solving the issue!

Best regards
