### ISSUE TITLE
UTF-8 Characters 

### ISSUE THREAD

**Issue by oranwutang** [ddsjoberg/gtsummary#352]
Hi,

When creating tbl_summary() tables for knitting to word (rtf), UTF-8 characters are not represented correctly, i.e. "Isquémico" is converted to "IsquÃ©mico". This is specially problematic for non-english users, all characters of spanish alphabet  (á, é, í, ó, ú, ñ) are converted wrongly.

It would be great if you could solve this...

Thanks in advance!

**Comment by ddsjoberg** [comment]
Hi @oranwutang , gtsummary uses the gt package to print.  Is the encoding also an issue in the gt package, or only in gtsummary?

**Comment by oranwutang** [comment]
Hi @ddsjoberg , I have never used gt, per your request I have given a try right now, it seems that gt uses a function (as_rtf()) to convert gt tables to rtf documents, and as you supposed there's where troubles comes, gt tables in rtf format doesn't print UTF-8 characters correctly, so I guess that you're gonna tell me to open an issue there, isn't it? ;)

**Comment by oranwutang** [comment]
I've found there is an issue about this trouble:

https://github.com/rstudio/gt/issues/227

**Comment by oranwutang** [comment]
And also here:

https://github.com/rstudio/gt/pull/436

But I don't know if it is already solved

**Comment by ddsjoberg** [comment]
@oranwutang The gt package is amazing!  But one drawback is that it is still under development.  If you can, stick with html output with gt.  It's highly developed and easy to customize.  The rtf is not as highly developed, however.  But it's on it's way, and I think it will get there soon!  One of the goals (as  I understand), is to create a unified language for output into html, rtf, and pdf.  I am excited for its release!

If you need output in Word, look into using the `kable::knitr()` output from gtsummary.  
http://www.danieldsjoberg.com/gtsummary/articles/global_options.html#printing

You can pipe any gtsummary object into the `as_kable()` function, and the object will be converted.  The kable output does not support footnotes and spanning headers, but it still looks great.
