### ISSUE TITLE
Change tbl_summary() Headers

### ISSUE THREAD

**Issue by oranwutang** [ddsjoberg/gtsummary#358]
Hi,

This is just a question, is there a way to change the headers of a summary tbl? i.e. change "Characteristic" for "Feature".

Thanks in advance!

**Comment by oranwutang** [comment]
I found it! It is using cols_label()...

Sorry!

**Comment by ddsjoberg** [comment]
@oranwutang no problem!  you can also use `gtsummary::modify_header()` which can be useful if you need to report the the level of the `by=`, or the Ns.
