### ISSUE TITLE
bold_labels() doesn't work when knitting to PDF

### ISSUE THREAD

**Issue by oranwutang** [ddsjoberg/gtsummary#359]
Hi, 

When using bold_labels() while knitting to pdf the resulting table doesn't show the labels in bold type, instead it perfectly works when knitting to html. 

I don't think this a gt's issue because gt is capable of correctly render the headers of the table in bold type, there should be a way that this work when the desired result is a pdf file.

I've been scanning the structure of a dummy tbl_summary but I can't find where is specified the format of the labels rows.

Do you think that there is a possible solution?

Thanks in advance!

**Comment by ddsjoberg** [comment]
@oranwutang can you give an example code that I can run, where a cell is bold in gt PDF output, and then code a can run using gtsummary with `bold_labels()` that is not working?

**Comment by ddsjoberg** [comment]
take a look at the `.$gt_calls()` object for the gt code that bolds the labels.

**Comment by oranwutang** [comment]
Surely, here is a reprex

```{r}
library(gtsummary)
library(gt)
library(magrittr)

college_degree <- sample(c("Yes", "No"), 50, replace = TRUE, prob = c(0.3, 0.7))

income <- sample(c("Low", "Medium", "High"), size = 50, replace = TRUE)

incomes <- data.frame(college_degree, income)

incomes %>% tbl_summary() %>% bold_labels()
```

If you knit it to html you obtain:

![htmlTable](https://user-images.githubusercontent.com/6965617/72934086-51b38e80-3d63-11ea-8fcf-d7d14fdc1152.png)


And if you knit to pdf:

![pdfTable](https://user-images.githubusercontent.com/6965617/72934106-5bd58d00-3d63-11ea-9912-cd9dd88bb1be.png)

As you can see in html output "college_degree" and "income" labels are in bold type meanwhile in the pdf output they are not, although columns headers ("Characteristic" and "N = 50") are bold indeed.

I mean that if gt (and gtsummary) are able to show column headers as bold in PDF, they should be able to show rows labels bold as well.

I hope I am being clear with this query (my english is not so good, sorry 🐱‍👤)...

Thanks for your interest!

**Comment by ddsjoberg** [comment]
Hi @oranwutang !  You're very clear!! 💯 

Try printing a table with the gt package where you bold a cell.  If we see that gt does indeed support bolding cells in the body of the table, then I can look into the reason gtsummary is not applying the bold weight.

My guess is that it is not yet supported in gt.  From the gt site, they are working on PDF and RTF output.  "Currently, gt supports HTML output, with LaTeX and RTF planned for the future."

This code should get you started bolding cells in a table using gt
```r
head(trial) %>% 
  gt::gt() %>% 
  gt::tab_style(style = gt::cell_text(weight = 'bold'), locations = gt::cells_body(columns = gt::vars(trt)))
```

**Comment by ddsjoberg** [comment]
hi @oranwutang !  I did a small test, and the bolding of cells within a table must be a feature that has not yet been implemented for PDF output in gt.

![image](https://user-images.githubusercontent.com/26774684/73082672-e7e8d100-3e97-11ea-8aa5-12bbddddafe1.png)

**Comment by oranwutang** [comment]
Hi @ddsjoberg, I also tried but I couldn't find the way, I have opened an issue about it on gt's github page but they haven't answered so far. 

Thanks for your interest!
