### ISSUE TITLE
tbl_regression - sample size incorrect with time-dependent covariates

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#36]
Imported biostatR issue

If you use a long dataset for analysis of time-dependent covariates and pass the model results to fmt_regression, the sample size is the number of rows in the dataset rather than the number of unique observations in the data.

**Comment by ddsjoberg** [comment]
@zabore there are a few other model types where the N presented could be misleading; for example, GEE and random effects.  Do you think we should just remove showing N as default in the output?  The N that is returned along with the formatted object will always be the number of observations.

**Comment by zabore** [comment]
Hm, in that case it is probably easiest to take it out. It's too bad because I like that feature for regular MV models, and I like having the N in uni_regression for each variable too.

**Comment by ddsjoberg** [comment]
We decided to keep reporting the N by default, and added the following note to the `tbl_regression()` documentation:

![image](https://user-images.githubusercontent.com/26774684/55994006-919b0080-5c7e-11e9-9ebb-e5b39b904531.png)
