### ISSUE TITLE
The `cells_data()` function is deprecated Warning Message

### ISSUE THREAD

**Issue by oranwutang** [ddsjoberg/gtsummary#362]
Hi, using tbl_summary() always promt the same warning message (take a look at the reprex below): "`cells_data()` function is deprecated and will soon be removed * Use the `cells_body()` function instead"

Just in case you were not aware about it...

Best regards!

``` r
library(gtsummary)
library(gt)
library(magrittr)

college_degree <- sample(c("Yes", "No"), 50, replace = TRUE, prob = c(0.3, 0.7))

income <- sample(c("Low", "Medium", "High"), size = 50, replace = TRUE)

incomes <- data.frame(college_degree, income)

incomes %>% tbl_summary() %>% bold_labels()
#> Warning: The `cells_data()` function is deprecated and will soon be removed
#>  * Use the `cells_body()` function instead

#> Warning: The `cells_data()` function is deprecated and will soon be removed
#>  * Use the `cells_body()` function instead
```
<sup>Created on 2020-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
hi @oranwutang !  thanks for the report!  this has been addressed the dev version of gtsummary!
