### ISSUE TITLE
combine_terms() errs when in apply/map

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#363]
We know there are issues when regression models are created within an apply/map framework, and that is later applied to `tbl_summary()`, because not all regression modeling functions save the calling environment.  @emilyvertosick reported an error when `combine_terms()` is called in the same setting when `tbl_regression()` was created in the apply or mapping setting.  The difference is that we can modify `tbl_regression()`!  The error below results when we try to re-run `tbl_summary()` on the updated model object as a part of `combine_terms()`.

We do save the function inputs for `tbl_regression()` in `.$inputs`.  Perhaps we could do something like this:
```r
tbl_args <- x$inputs
tbl_args$x <- updated_model_obj
do.call(tbl_regression, tbl_args )
```

Example code that errors

``` r
library(tidyverse)
library(gtsummary)

tibble(outcome = "marker", exp = FALSE, test = "F") %>%
  mutate(
    mod = map(outcome, 
              ~glm(formula = str_glue("{.x} ~ age + stage") %>% as.formula(),
                   data = trial, family = gaussian)),
    tbl = map2(mod, exp, ~tbl_regression(.x, exponentiate = .y)),
    tbl2 = map2(
      tbl, test, ~combine_terms(..1, formula_update = . ~ . - stage, test = ..2)
    )
  )
#> Error in ifelse(exponentiate == TRUE, style_ratio, style_sigfig): object '.y' not found
```

<sup>Created on 2020-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by margarethannum** [comment]
Merged as part of #375. Closing issue so there's no confusion at hackathon.
