### ISSUE TITLE
Table's footer should be optional

### ISSUE THREAD

**Issue by oranwutang** [ddsjoberg/gtsummary#364]
Hi again,

There are some situations where the footer of the table seems to be redundant, i.e. when all of the data is presented as percentages and it is unnecesary to explain that in the footer:

```r
library(gtsummary)
library(gt)
library(magrittr)

set.seed(12358)
college_degree <- sample(c("Yes", "No"), 50, replace = TRUE, prob = c(0.3, 0.7))
income <- sample(c("Low", "Medium", "High"), size = 50, replace = TRUE)
incomes <- data.frame(college_degree, income)

incomes  %>%tbl_summary() 
```
![wfooter](https://user-images.githubusercontent.com/6965617/73087148-58acdf00-3ed2-11ea-9ab9-45e6b01dd275.png)

Additionally if you render the table to pdf the footer will always be misaligned with the table:
![wfooterPDF](https://user-images.githubusercontent.com/6965617/73087511-e38dd980-3ed2-11ea-946f-043d927e60d2.png)

So I propose that there should be an option to supress the footer, maybe as an argument inside tbl_summary(), something like: tbl_summary(footer=FALSE).

In the meantime, I have made a (not so elegant) function to suppress the footer, that can be inserted within the tbl_summary "pipeline":

```r
library(gtsummary)
library(gt)
library(magrittr)

unFooter <- function(x) {
  x[["gt_calls"]][["tab_footnote"]] <- NULL
  return(x)
}

set.seed(12358)
college_degree <- sample(c("Yes", "No"), 50, replace = TRUE, prob = c(0.3, 0.7))
income <- sample(c("Low", "Medium", "High"), size = 50, replace = TRUE)
incomes <- data.frame(college_degree, income)

incomes  %>%tbl_summary() %>% bold_labels %>% unFooter() 
```
![unFooted](https://user-images.githubusercontent.com/6965617/73087826-6747c600-3ed3-11ea-964f-d2e1e766d3d3.png)

Although this works perfectly for me, I think that it is more elegant to have an option within tbl_summary to suppress the footer so the footer "request" is not passed to gt().

What do you think?

Thanks in advance!

**Comment by margarethannum** [comment]
Hi Oran, 

We've actually included the functionality to include/exclude parts of the {gt} call (such as footnotes, headers, etc) as part of the[ `as_gt()`](http://www.danieldsjoberg.com/gtsummary/reference/as_gt.html) function! 

You can check out the  [`tbl_summary()` vignette "Advanced Customization" section ](http://www.danieldsjoberg.com/gtsummary/articles/tbl_summary.html#advanced) for an example of this precise case where a table is printed without a footnote. 

I've also included code below to reflect what you would need in your example. 

```
library(gtsummary)
library(dplyr)
library(gt)

set.seed(12358)
college_degree <- sample(c("Yes", "No"), 50, replace = TRUE, prob = c(0.3, 0.7))
income <- sample(c("Low", "Medium", "High"), size = 50, replace = TRUE)
incomes <- data.frame(college_degree, income)

incomes %>% tbl_summary() %>% as_gt(exclude = "tab_footnote")
```
![image](https://user-images.githubusercontent.com/29231686/73097033-34daa080-3eb4-11ea-823b-fc2496111887.png)

Note if you are using the dev version of {gtsummary} we recommend using the format
 `as_gt(include = -tab_footnote)`. @ddsjoberg has been making a lot of improvements for the next release to make the selectors work more like you would expect in something like `dplyr::select()`.

**Comment by oranwutang** [comment]
Thanks Margaret!
