### ISSUE TITLE
Any plans to enable gtsummary to work with models estimated with rstanarm?

### ISSUE THREAD

**Issue by davidkane9** [ddsjoberg/gtsummary#391]
Right now, gtsummary does not work with rstanarm models:

``` r
library(rstanarm)
#> Loading required package: Rcpp
#> rstanarm (Version 2.19.2, packaged: 2019-10-01 20:20:33 UTC)
#> - Do not expect the default priors to remain the same in future rstanarm versions.
#> Thus, R scripts should specify priors explicitly, even if they are just the defaults.
#> - For execution on a local, multicore CPU with excess RAM we recommend calling
#> options(mc.cores = parallel::detectCores())
#> - bayesplot theme set to bayesplot::theme_default()
#>    * Does _not_ affect other ggplot2 plots
#>    * See ?bayesplot_theme_set for details on theme setting
library(gtsummary)

z <- stan_glm(mpg ~ cyl, data = mtcars, refresh = 0)
tbl_summary(z)
#> Error in UseMethod("ungroup"): no applicable method for 'ungroup' applied to an object of class "c('stanreg', 'glm', 'lm')"
```

<sup>Created on 2020-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
Hello @davidkane9 ! Thanks for the question, and thank you x1000 for the reprex! 👏 

We can likely add support!  We use `broom::tidy()` to perform the initial cleaning up of the model results.  I see below that `tidy()` does have a method for `stan_glm()`.  But there is a bit of a difference....`tbl_regression()` is expecting a confidence interval/region and a p-value column, and the tidy function doesn't return them the model (which can be fine in your case, but it's just what the function is expecting at the moment.).

What would you like the the output to look like?  I don't use Baysian models in my work and would need some guidance to get the reporting right. The `tbl_regression()` does allow for custom tidy function passed via the `tidy_fun=` argument.  You can read a bit about that here: 
http://www.danieldsjoberg.com/gtsummary/reference/tidy_vetted.html

``` r
library(rstanarm)
library(gtsummary)

z_stan <- stan_glm(mpg ~ cyl, data = mtcars, refresh = 0)
broom::tidy(z_stan, conf.int = TRUE)
#> # A tibble: 2 x 3
#>   term        estimate std.error
#>   <chr>          <dbl>     <dbl>
#> 1 (Intercept)    37.8      2.17 
#> 2 cyl            -2.86     0.336

z_lm <- lm(mpg ~ cyl, data = mtcars)
broom::tidy(z_lm, conf.int = TRUE)
#> # A tibble: 2 x 7
#>   term        estimate std.error statistic  p.value conf.low conf.high
#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
#> 1 (Intercept)    37.9      2.07      18.3  8.37e-18    33.6      42.1 
#> 2 cyl            -2.88     0.322     -8.92 6.11e-10    -3.53     -2.22

tbl_regression(z_lm)
```
![image](https://user-images.githubusercontent.com/26774684/75075927-e5948980-54cc-11ea-837e-ea7fe31a441b.png)

Perhaps we could update to only include a p-value when a p-value is returned from the tidy() function.  Anyway, would love to see how the results from this model is typically reported in the literature, and assess whether it is something we can support!

**Comment by davidkane9** [comment]
The raw print and summary methods for each rstanarm object are quite reasonable.

``` r
library(rstanarm)
#> Loading required package: Rcpp
#> rstanarm (Version 2.19.2, packaged: 2019-10-01 20:20:33 UTC)
#> - Do not expect the default priors to remain the same in future rstanarm versions.
#> Thus, R scripts should specify priors explicitly, even if they are just the defaults.
#> - For execution on a local, multicore CPU with excess RAM we recommend calling
#> options(mc.cores = parallel::detectCores())
#> - bayesplot theme set to bayesplot::theme_default()
#>    * Does _not_ affect other ggplot2 plots
#>    * See ?bayesplot_theme_set for details on theme setting
library(gtsummary)

z <- stan_glm(mpg ~ cyl, data = mtcars, refresh = 0)
print(z)
#> stan_glm
#>  family:       gaussian [identity]
#>  formula:      mpg ~ cyl
#>  observations: 32
#>  predictors:   2
#> ------
#>             Median MAD_SD
#> (Intercept) 37.9    2.1  
#> cyl         -2.9    0.3  
#> 
#> Auxiliary parameter(s):
#>       Median MAD_SD
#> sigma 3.3    0.4   
#> 
#> ------
#> * For help interpreting the printed output see ?print.stanreg
#> * For info on the priors used see ?prior_summary.stanreg
summary(z)
#> 
#> Model Info:
#>  function:     stan_glm
#>  family:       gaussian [identity]
#>  formula:      mpg ~ cyl
#>  algorithm:    sampling
#>  sample:       4000 (posterior sample size)
#>  priors:       see help('prior_summary')
#>  observations: 32
#>  predictors:   2
#> 
#> Estimates:
#>               mean   sd   10%   50%   90%
#> (Intercept) 37.8    2.1 35.1  37.9  40.5 
#> cyl         -2.9    0.3 -3.3  -2.9  -2.4 
#> sigma        3.3    0.4  2.8   3.3   3.9 
#> 
#> Fit Diagnostics:
#>            mean   sd   10%   50%   90%
#> mean_PPD 20.1    0.8 19.0  20.1  21.2 
#> 
#> The mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help('summary.stanreg')).
#> 
#> MCMC diagnostics
#>               mcse Rhat n_eff
#> (Intercept)   0.0  1.0  2970 
#> cyl           0.0  1.0  3008 
#> sigma         0.0  1.0  3274 
#> mean_PPD      0.0  1.0  3643 
#> log-posterior 0.0  1.0  1457 
#> 
#> For each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).
```

<sup>Created on 2020-02-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Anything like that, but which looked nice in an Rmd, would be great! If you were only doing one, I would do the summary() method.

**Comment by ddsjoberg** [comment]
Our primary goal with gtsummary is to create tables that a ready for publication in an applied journal, which of course contain far less information than what is being printed in the summaries above.

I think for what you're looking for, you can print result summaries with the gt package of with `knitr::kable()`.  For example, the code chunk below would print nicely in an R markdown.

```r
library(rstanarm)
library(broom)

z <- stan_glm(mpg ~ cyl, data = mtcars, refresh = 0)
print(z)

glance(z) %>% gt::gt()
tidy(z) %>% gt::gt()
summary(z) %>% as.data.frame() %>% tibble::rownames_to_column() %>% gt()
```

You could also look take a look at the printr package.  It will automatically print rectangle objects (e.g. data frame, tibbles, matrices) with `knitr::kable()` in R markdown documents.

**Comment by davidkane9** [comment]
Thanks for this advice!

> Our primary goal with gtsummary is to create tables that a ready for publication in an applied journal

This is exactly what I am looking for! Or, to be more precise, I want to help my students create such tables for their papers. The gtsummary package is great for that! But I have some students who estimate their models with rstanarm. I just hope they can use gtsummary for that in just the same way that they use gtsummary for creating tables for models which they estimate with lm. I hope to avoid teaching them workarounds like working directly with kable and gt.

**Comment by ddsjoberg** [comment]
Great!  Is there a way to get `broom::tidy()` to return what you need to display in a table?  We use that function in the background to prepare (aka tidy up) the model summary results before processing it with gtsummary (i.e. adding reference rows, add variable labels, footnotes, etc.).

If `broom::tidy()` does NOT give you what you need, you can still use gtsummary using the `tidy_fun=` argument in `tbl_regression()`.  You would need to write a custom tidier.  This help file has more information on writing a custom tidy function.
http://www.danieldsjoberg.com/gtsummary/reference/tidy_vetted.html

**Comment by davidkane9** [comment]
> Is there a way to get broom::tidy() to return what you need to display in a table?

It already does. Example:

``` r
library(rstanarm)
#> Loading required package: Rcpp
#> rstanarm (Version 2.19.2, packaged: 2019-10-01 20:20:33 UTC)
#> - Do not expect the default priors to remain the same in future rstanarm versions.
#> Thus, R scripts should specify priors explicitly, even if they are just the defaults.
#> - For execution on a local, multicore CPU with excess RAM we recommend calling
#> options(mc.cores = parallel::detectCores())
#> - bayesplot theme set to bayesplot::theme_default()
#>    * Does _not_ affect other ggplot2 plots
#>    * See ?bayesplot_theme_set for details on theme setting
library(broom)
library(gtsummary)

z <- stan_glm(mpg ~ cyl, data = mtcars, refresh = 0)
broom::tidy(z)
#> # A tibble: 2 x 3
#>   term        estimate std.error
#>   <chr>          <dbl>     <dbl>
#> 1 (Intercept)    37.9      2.03 
#> 2 cyl            -2.88     0.316
```

<sup>Created on 2020-03-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
I have added this to our to do list.  You can follow the progress on Issue #407

**Comment by ddsjoberg** [comment]
Hi @davidkane9 !

FYI, In the development version of gtsummary, we now support models like your example.  We're expecting to send this version to CRAN within the next month.

Thank you for posting your example!

```r
library(rstanarm)
library(gtsummary)

z <- stan_glm(response ~ age + grade, data = trial, 
              refresh = 0, family = binomial)
tbl_regression(z, exponentiate = TRUE)
```
![image](https://user-images.githubusercontent.com/26774684/78381917-0956ef00-75a4-11ea-8c17-56749f1f82c2.png)
