### ISSUE TITLE
Add `as_kable_extra()` function?

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#394]
@margarethannum @karissawhiting 
Hmmmm it would be relatively easy to add a `as_kable_extra()` function for HTML output

```r
as_kable() %>%
  add_indent(...) %>% # indent non-label rows
  add_header_above(...) %>% # add spanning headers
  footnote(...) # add footnotes
```
Pros:
- Users are already familiar with kableExtra making it easy for them to use
- If users can get up and going with something they already know, it could make users more amenable to using gtsummary.
- kableExtra is on CRAN, and is entirely stable.  A stable package that is known to users can be more amenable to users over gt which is not yet on CRAN.  gt could continue to make minor changes to the API for HTML output

Cons:
- HTML output with gt is better, and we should encourage its use!
- Is one more output type confusing?
- There is that weird bug with kableExtra that causes formatting issues with kable objects in Word....is there a chance we could be introducing a problem into our package? @margarethannum you are familiar with this bug, right?  What do you think?

What do you think?

**Comment by karissawhiting** [comment]
I kind of think of {kableExtra} custom html features as being more equivalent to the {gt} custom features that a user can add on top of their base kable or gt table after the fact. 

However, if you can't currently access things like footnotes and spanning headers from kable output, I think I'm in favor of adding `as_kable_extra()` function if it is fairly straightforward to add.
