### ISSUE TITLE
Update default printing for R Markdown

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#396]
there have only been a few early engagements with the package in the last week, and a couple of them have been confused by printing.  I am thinking of writing up a small vignette on gtsummary+R markdown.  When someone asks a question about printing, I want to refer them to the vignette.  I also want the vignette to (kindly) say, if you're using gt printing with PDF or RTF, please don't post questions about the output.

What do you think of even changing the default print engine for PDF and DOC output?
- HTML -> gt
- PDF -> kable with note that PDF is still underdevelopment, falling back to kable, if you want gt then use as_gt() in script
- RTF -> gt (perhaps with note perhaps that RTF is under development)
- DOC -> kable with note that gtsummary was developed for gt and HTML

I think there are a lot of people using PDF output and it's confusing, and this would be a way to cut off questions before they come at us?

**Comment by karissawhiting** [comment]
I think a vignette will greatly limit confusion on the issue. I also agree that the proposed updated print engine defaults will help users get the output they are looking for quicker for DOC and PDF.

**Comment by ddsjoberg** [comment]
A version of this is merged, but we should re-visit before the next release
