### ISSUE TITLE
Improve messaging on tbl_survival() when a survival probability is not reached 

### ISSUE THREAD

**Issue by karissawhiting** [ddsjoberg/gtsummary#399]
When you input a single probability in `tbl_survival(probs = X)` but `X` probability is not reached (using`survfit()` to estimate) you get the following error:

``` r
library(tibble)
library(survival)
library(gtsummary)

df <- tribble(
  ~time, ~status,
  1, 0, 
  2, 1, 
  3, 0, 
  8, 0
)

fit <- survfit(Surv(time, status) ~ 1, data = df)


# make this error better?
fit %>%
  tbl_survival(probs = .5)
#> Error: must be a character vector, not a logical vector
```
Interestingly, when you enter more than 1 arg, it works and gives a dashed line:

```
# this works
fit %>%
  tbl_survival(probs = c(.1, .5))
```

If I ask for a probability that has not been reached, I think I would expect that `tbl_survival()` output the table with NA or --- in both the above cases. 

If we don't think it is appropriate to output a table with no value, we could just add an informative error message.

**Comment by ddsjoberg** [comment]
@karissawhiting is this something you want to do? or just skip it and focus on tbl_survfit?

**Comment by karissawhiting** [comment]
Down to focus on tbl_survfit(). This seems to work fine with the new function!
