### ISSUE TITLE
Method used in car::Anova not the same as anova() for lme4::lmer() models.

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#406]
Perhaps we should not use `car::Anova()` and just use the more common `anova()`?

The following unit test for `lm4::lmer()` is not included at the moment because of this discrepancy 

```r
  # expect_equivalent(
  #   tbl_lmer_lin3$table_body %>% filter(variable == "trt") %>% pull(p.value),
  #   car::Anova(mod_lmer_lin, type = "III") %>%
  #     as.data.frame() %>%
  #     tibble::rownames_to_column() %>%
  #     filter(rowname == "trt") %>%
  #     pull(`Pr(>Chisq)`)
  # )
```

**Comment by michaelcurry1123** [comment]
@ddsjoberg  is one p-value based on the chi square and the other based on an F statistic?

**Comment by ddsjoberg** [comment]
i am not sure what the differences are @michaelcurry1123 . We recently set up a structure for checking all calculations for vetted models using `tbl_regression()`, and saw during the checks that the methods matched for all the model types except lme4.

I think the best way forward it to replace the `car::Anova()` with `stats::anova()`, but it'll likely be a combination of `stats::update()` then `stats::anova()`.  There will be a few kinks to work out, e.g. when there are different patterns of missing data.

It will also be nice to remove the car dependency.

We should write our helper function to calculate the p-value generally so it can also be used by combine terms (which will include more than one term in removed from the model).

**Comment by ddsjoberg** [comment]
we have previously depended on model.frame() function to get the data frame from the model object....but this can be tricky because we're depending on whatever S3 method that package owner wrote for model.frame.  Sometime it would return the entire data frame, sometimes it would return just the variables in the model, and sometime it would be just the variables in the model with missing obs dropped.
But if we extract the call from the model object and get the formula and data args from there, we can run model.frame.formula() for every model and get the same output (which is just vars in model, with missing obs omitted).

**Comment by ddsjoberg** [comment]
we are now printing the methods used, and will leave it up to the user to know what the methods are
