### ISSUE TITLE
Allow label/level bolding and italicizing to work on cols in tbl_cross() 

### ISSUE THREAD

**Issue by karissawhiting** [ddsjoberg/gtsummary#442]
Functions to bold and italicize levels/labels only work on row variables and not column variables in `tbl_cross()`. 

Example:
```r
trial %>% tbl_cross(trt, response) %>% italicize_levels()
``` 
This may require making these formatting functions into method functions.

**Comment by ddsjoberg** [comment]
@karissawhiting is this something you'd still like to implement?

**Comment by karissawhiting** [comment]
Sure! Is this a good hackathon task I can take on?

**Comment by karissawhiting** [comment]
Does the below seem a reasonable way to adjust `bold_levels()` for class = `tbl_cross` ? Should I be using `modify_table_styling()` for the header text adjustments instead?

```r 
bold_levels.tbl_cross <- function(x) {
  
  updated_call_list <- c(x$call_list, list(bold_levels = match.call()))
  
  # input checks ---------------------------------------------------------------

  if (!"row_type" %in% x$table_styling$header$column) {
    cli::cli_alert_warning("{.code bold_levels()} cannot be used in this context.")
    return(x)
  }
  
  # bold levels ----------------------------------------------------------------
  x <-
    modify_table_styling(
      x,
      columns = .first_unhidden_column(x),
      rows = .data$row_type != "label",
      text_format = "bold"
    ) %>% 
    modify_header(
      c(starts_with("stat_"), -any_of("stat_0")) ~ "**{level}**")


  x$call_list <- updated_call_list
  
  x
}

bold_levels.tbl_cross(tbl_cross_ex2)
```

If that looks reasonable, I will turn `bold_levels` and `italicize level` into method functions and implement.

**Comment by ddsjoberg** [comment]
Looks mostly good.
1. If we make these functions methods, all of the bold/italicize level/label functions should be methods.
2. `modify_header(c(starts_with("stat_"), -any_of("stat_0")) ~ "**{level}**")` the functions shouldn't change any headers.
3. The function can just run `bold_labels.gtsummary()` to bold the rows in the table and then the other modifications for the headers.

Thanks!
