### ISSUE TITLE
extending tbl_summary to survey design objects

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#460]
`tbl_regression()` works well with `svyglm()` results.

However, it's not possible to generate basic stats from `tbl_summary` with a survey design object.

Would it possible to consider extending `tbl_summary()` to survey designs or to develop a `tbl_svysummary()` for these objects?

Regards

**Comment by ddsjoberg** [comment]
Hi @larmarange ! I think that is a great suggestion.

I don't use survey methods, so I may not be the best to write the function. But I'll add it to the list of items to do! And of course you're interested,w e can work together :)

**Comment by ddsjoberg** [comment]
I did some reading about survey design objects, and now I am convinced I am not the one to write the function.  I don't want to mess it up!  I'll leave this open in case anyone volunteers.
