### ISSUE TITLE
Suggestion: Add additional statistics columns

### ISSUE THREAD

**Issue by joelgautschi** [ddsjoberg/gtsummary#463]
As far as I understand `tbl_summary()` allows one column for statistics (with the possibility of multiple statistics in this column). However, sometimes you would like to report more statistics than there is room for in a column (e.g. besides mean, sd, also the median, iqr, 95%-ci etc.). Being able to add more columns would make it possible to do that. However, I do not know, if the restriction to one column for statistics is done on purpose 'by design'.

Or is the idea to use `tbl_merge()` to to this? If yes, maybe the documentation could be enhanced for common use cases for summary statistics.

**Comment by ddsjoberg** [comment]
Hello @joelgautschi ! Thanks for the comment.  You're right, this is something that is meant to be done with `tbl_merge()`. And I like your suggestion of making this more clear in the documentation! 
- [ ] Add example in [table gallery](http://www.danieldsjoberg.com/gtsummary/articles/gallery.html) adding an additional statistics column.
- [ ] Add reference to the table gallery in the `tbl_summary()` documentation and mention adding column on stats.
```r
library(gtsummary)

# define function for lower and upper bounds of the mean CI
ll <- function(x) t.test(x)$conf.int[1]
ul <- function(x) t.test(x)$conf.int[2]

t1 <-
  trial %>%
  dplyr::select(age, marker) %>%
  tbl_summary(statistic = all_continuous() ~ "{mean} ({sd})",
              missing = "no") 

t2 <-
  trial %>%
  dplyr::select(age, marker) %>%
  tbl_summary(statistic = all_continuous() ~ "{ll}, {ul}",
              missing = "no")

tbl_merge(list(t1, t2))
```
One can use `modify_header()` etc to improve the column titles.

**Comment by ddsjoberg** [comment]
HI @joelgautschi !  FYI, there is a  new function `add_stat()` making it easier to add a new column with any statistic you'd like.  Thank you for the suggestion!
http://www.danieldsjoberg.com/gtsummary/reference/add_stat.html
