### ISSUE TITLE
Enhancement: as_huxtable() method

### ISSUE THREAD

**Issue by hughjonesd** [ddsjoberg/gtsummary#469]
This would complement the existing `as_gt`, `as_flextable` methods:

https://github.com/hughjonesd/huxtable

Interested in a pull request?

**Comment by ddsjoberg** [comment]
Hello @hughjonesd !  A PR would be wonderful! huxtable was on my to do list, and I haven't gotten a chance to write the function.  It'll be a wonderful addition :)

If the `as_huxtable()`  function follows the same outline as `as_gt()`, `as_flextable()`, `as_kable()` that will fit perfectly.  Here's a brief outline of the internals of gtsummary objects http://www.danieldsjoberg.com/gtsummary/articles/gtsummary_definition.html

Briefly, let `x` be a gtsummary table.  It's a named list.  `x$table_body` is the table that is printed, and the instructions to print it are saved in `x$table_header`.  We convert the instructions in `x$table_header` into the R code expressions that print the table.

Thank you!  Looking forward to it, and I am happy to discuss at any time if it'll help.

**Comment by ddsjoberg** [comment]
Merged with #479
