### ISSUE TITLE
Feature request - compact docx output from gtsummary and flextable

### ISSUE THREAD

**Issue by moleps** [ddsjoberg/gtsummary#482]
The standard output from gtsummary using gtsummary::as_flextable results in rather  "airy" tables that often span multiple pages. Please see [https://stackoverflow.com/questions/61532704/table-generation-in-rmarkdown-using-gtsummary-and-flextable](url) as background for request. Automatic generation of indented and compact publication ready tables would be a real time-saver without having to resort to custom styles in word.

**Comment by ddsjoberg** [comment]
Hi @moleps! Thanks for creating the issue!  Full disclosure, I am not an experienced flextable user!

I love the idea of the `theme_gtsummary_compact()` applying to flextable output as well, and it'll be something I use as well.  What do you think the best sequence of flextable calls should be to produce the compact table?

After a gtsummary object is convert into a tibble and formatting applied to the columns, these are the default flextable commands executed on the tibble.
![image](https://user-images.githubusercontent.com/26774684/80830163-816e0000-8bb6-11ea-8a61-a6489fbbe7b9.png)

Like the discussed on the SO question, the order matters with flextable. Was reducing the font size and reducing the padding enough to get the table you're looking for?

**Comment by moleps** [comment]
Unfortunately, I have not been able to use any of the flextable:: commands to decrease the white space between rows. However, I did manage to create word style and when knitting to word it turns out very compact and with the desired indentation. 

I´ve come across a couple of suspected minor errors - please see attached pdf for samples in docx and html


1) tbl_merge(tbls = list(pp,uv,mv),tab_spanner = c("**Dead**","**Univariate**","**Multivariate**")) --works beautifully in html, but the univariate and multivariate tbl headers are interchanged after as_flextable

2) Using tbl_uvregression and the hide_n option. If hide_n is set to False it renders correctly in html, but in as_flextable all the value rows are given NA values.

[tbl.pdf](https://github.com/ddsjoberg/gtsummary/files/4566773/tbl.pdf)

**Comment by ddsjoberg** [comment]
🙌 THANK YOU for letting me know about the formatting issues!  I just pushed some updates that should address the problem. #484 

I couldn't get the output as compact as I was hoping either.  For now, I can just make the font smaller and set the padding to zero in the compact theme.  But I do think the best thing is to do as you suggested and create a template. If you find a programmatic solution, would love to hear it! :)

**Comment by ddsjoberg** [comment]
@moleps I tried to accomplish the same compact tables using huxtables instead of flaxtables.  Unfortunately, the tables came out pretty similar. (see attached).  I am going to close the issue for now.
[flextable_example.docx](https://github.com/ddsjoberg/gtsummary/files/4569345/flextable_example.docx)

**Comment by moleps** [comment]
Wow - you are indeed very quick in sorting out issues. I´ll stick to the template way of doing things then. Really appreciate your efforts. After upgrading again to the development version the issue of tbl merging column titles and NA printing seem to be rectified. It works allright as long as I run the .rmd file, but the same file that runs correctly in "normal" mode throws the following error when I try to knit:

Quitting from lines 15-39 (Untitled.Rmd) 
Error in flextable::flextable(cc) : duplicated col_keys
Calls: <Anonymous> ... as_flextable -> as_flextable.huxtable -> <Anonymous>
Execution halted

I believe it points back to the following function:
tbdoc <- function(tb){
  gtsummary::as_flextable(tb) %>% font(fontname = "Tahoma",part = "all") %>% fontsize(size=6.5,part="all") %>%  fit_to_width(max_width = 10) %>% height_all(height=.18)
}


 I have no idea where the as_flextable.huxtable comes from. Cant seem to find it in the environment.

**Comment by ddsjoberg** [comment]
Thank you @moleps ! The report is much appreciated! I am having trouble replicating the error. Can you give me some code I can run? 🕺

**Comment by moleps** [comment]
Sorry-cant share the dataset and cant reproduce the error with other datasets. Strange thing is that it works allright using rmarkdown::render, just not when I press the knit button. Anyways- dont worry about it. Thanks and keep up the excellent work.

**Comment by ddsjoberg** [comment]
OK, if you have it happen again, please do submit a reprex!  Or if you have other ideas for improvements to the tables!
