### ISSUE TITLE
Discrete/Continuous variable treatment and redefining statistics bug

### ISSUE THREAD

**Issue by khizzr** [ddsjoberg/gtsummary#502]
Hi. 
I am working with survey data with some variables representing sums of Likert-scale measurements, ranging 1-12.
When I try to show summary table for two data classes, tbl_summary treat the variable as discrete.
I will illustrate that on titanic where the variable has only three classes, just for the sake of example.
```r 
titanic::titanic_train %>% 
   select(Pclass,Sex) %>% 
   tbl_summary(by=Sex)
```
Now, if I try to specify directly that I want e.g. mean and sd for all numeric variables, as in the documentation:
```r
titanic::titanic_train %>% 
    select(Pclass,Sex) %>% 
    tbl_summary(by=Sex, statistic = list(all_numeric() ~ "{mean} ({sd})"))
```
I get an error:
` Error: glue cannot interpolate functions into strings. * object 'mean' is a function.`

**Comment by ddsjoberg** [comment]
Hi @khizzr !  Thank you for the comment!

First, here's the code to get the results you'd like.  You need to specify the summary type of the variable, to get `Pclass` to be summarized as a continuous variable.
```r
titanic::titanic_train %>% 
  select(Pclass,Sex) %>%
  tbl_summary(
    by = Sex, 
    type = Pclass ~ "continuous",
    statistic = list(all_numeric() ~ "{mean} ({sd})")
  )
```

Second, I think that a better error message is in order here, when summary statistics not compatible with categorical data are requested!  I'll leave this issue open until the updated error message has been implemented.

**Comment by ddsjoberg** [comment]
TO DO:
- [ ] For categorical variables, ensure all stats wrapped in `{}` are compatible with categorical variables.
- [ ] For continuous variables, ensure all stats wrapper in `{}` are indeed functions.
