### ISSUE TITLE
tbl_summary evaluates names of columns not required for its current task

### ISSUE THREAD

**Issue by oranwutang** [ddsjoberg/gtsummary#504]
Hi gtsummary team!

I don't know if this is exactly an (important) issue, but I've found that if a dataframe has repeated column names (I know, repeated names shouldn't exist, but... they do!) tbl_summary gives an error when you try to use it even if selected columns from that dataframe don't include those with repeated names (see reprex below).

The thing is, why is tbl_summary evaluating the names of the columns beyond the selected subset of variables? Don't you think that with big dataframes this behaviour could result in a loss of efficiency?

Best regards!
---

``` r
library(tidyverse)
library(gtsummary)

df <- data.frame(
         ZIP = c(98752L, 289745L, 19872L, 98431L),
        COPD = c(1L, 1L, 0L, 1L),
       Smoke = c(1L, 1L, 0L, 1L),
        Surv = c(1L, 1L, 0L, 1L),
       Treat = c(0L, 0L, 1L, 1L),
        Surv = c(1L, 1L, 0L, 1L)
)

df
#>      ZIP COPD Smoke Surv Treat Surv.1
#> 1  98752    1     1    1     0      1
#> 2 289745    1     1    1     0      1
#> 3  19872    0     0    0     1      0
#> 4  98431    1     1    1     1      1

colnames(df) <- str_replace(string = colnames(df), pattern = ".1", replacement = "")

df
#>      ZIP COPD Smoke Surv Treat Surv
#> 1  98752    1     1    1     0    1
#> 2 289745    1     1    1     0    1
#> 3  19872    0     0    0     1    0
#> 4  98431    1     1    1     1    1

df %>% select(ZIP:Smoke) %>% tbl_summary()
#> Error: Column `Surv` must have a unique name
```

<sup>Created on 2020-05-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
Hi @oranwutang !

When I run the code you provided, I get the expected table with no error:
![image](https://user-images.githubusercontent.com/26774684/82844598-12cb4c00-9eaf-11ea-9116-4d986a8e19c4.png)

I am running the new dplyr, which will be released next week as dplyr 1.0.
```r
> packageVersion("dplyr")
[1] ‘0.8.99.9002’
```

What version of dplyr are you using?  Can you confirm the error is not from `select()`?  I don't know how `tbl_summary()` could throw this error because the data set passed doesn't have any columns called `Surv`?

**Comment by oranwutang** [comment]
You're right, the trouble is with the select() function, I should have tried first `df %>% select(ZIP:Smoke)` there is where the error is.

Sorry for bothering...

**Comment by ddsjoberg** [comment]
No bother at all!!
