### ISSUE TITLE
CRAN Check Failure for Upcoming broom Release

### ISSUE THREAD

**Issue by simonpcouch** [ddsjoberg/gtsummary#505]
Hi there! The broom dev team just ran reverse dependency checks on the upcoming 0.7.0 release of the package and found new errors/test failures for this package. I've pasted the results below, which seem to result from broom no longer exporting the `confint_tidy()` function (for maintainability purposes.)

*   checking examples ... ERROR
    ```
    ...
    > ### Title: Vetted tidy models
    > ### Aliases: vetted_models
    > ### Keywords: internal
    > 
    > ### ** Examples
    > 
    > my_tidy <- function(x, exponentiate =  FALSE, conf.level = 0.95, ...) {
    +   tidy <-
    +     dplyr::bind_cols(
    +       broom::tidy(x, conf.int = FALSE),
    +       broom::confint_tidy(x, func = stats::confint.default, conf.level = conf.level)
    +     )
    +   # exponentiating, if requested
    +   if (exponentiate == TRUE)
    +     tidy <- dplyr::mutate_at(vars(estimate, conf.low, conf.high), exp)
    + }
    > 
    > lm(age ~ grade + response, trial) %>%
    +   my_tidy()
    Error: 'confint_tidy' is not an exported object from 'namespace:broom'
    Execution halted
    ```

I've pasted the most recently exported function definition below as a place to start from in making the necessary fixes—mostly just the base `confint` function with some extra checks.🙂

```
confint_tidy <- function(x, conf.level = .95, func = stats::confint, ...) {
  # avoid "Waiting for profiling to be done..." message for some models
  ci <- suppressMessages(func(x, level = conf.level, ...))

  # protect against confidence intervals returned as named vectors
  if (is.null(dim(ci))) {
    ci <- matrix(ci, nrow = 1)
  }

  # remove rows that are all NA. *not the same* as na.omit which checks
  # for any NA.
  all_na <- apply(ci, 1, function(x) all(is.na(x)))
  ci <- ci[!all_na, , drop = FALSE]
  colnames(ci) <- c("conf.low", "conf.high")
  as_tibble(ci)
}
```

We hope to submit this new version of the package to CRAN in the coming weeks. If you encounter any problems fixing these issues, please feel free to reach out!

**Comment by ddsjoberg** [comment]
@simonpcouch ! Thank for the heads up and kindly for the internals of `confint_tidy()`!  I'll be sure to make this update, and release soon as well.
