### ISSUE TITLE
Translation of labels to other languages

### ISSUE THREAD

**Issue by oranwutang** [ddsjoberg/gtsummary#511]
Hi!

I've been spending a lot of time trying to translate to spanish some of the predetermined labels or footers that appears on tables made with gtsummary.

I've used some workaorunds more or less like:

```r
nice_table <- some_data %>%
 tbl_summary()

nice_table[[2]] <- nice_table[[2]] %>% 
  mutate(footnote=str_replace(footnote, pattern = "Statistics presented:", replacement = 
 "Estadísticos:"),  
  footnote=str_replace(footnote, pattern = "median", replacement = "mediana:"))

nice_table %>% 
  as_gt() %>% 
  tab_options(table.font.size = 12) %>%
  cols_label("label"=md("**Característica**") #Here I'm translating the "Characteristics" header
```
So I was guessing that if you are interested, gtsummary could have an option to offer those labels in spanish. 

I don't have the programming level (or knowledge) to make this by a pull request but if you give me a list with all of the possible labels or footnotes that gtsummary displays then I'll give you the translations to spanish so you can modify the code to add the translations.

Finally the user could select the language to be displayed passing an argument in a way such tbl_summary(lan="spanish|español").

I'm sure that this could be a great feature for your package and that the +400 millions of spanish speakers will surely appreciate it! ;)

Thanks for your attention and best regards!

**Comment by ddsjoberg** [comment]
Hi @oranwutang !  This is a great suggestion!! LOVE IT!

I think the best way to implement this is with themes (http://www.danieldsjoberg.com/gtsummary/dev/articles/themes.html). They will be released in the next version of gtsummary.  Essentially, it's a way to change a bunch of gtsummary settings all at once.  We currently have themes to style your summary table according to JAMA's reporting guidelines. Another theme to print tables more compactly (smaller font size, reduced cell padding).  Including a theme to set languages is a fabulous fit!

I think we can call the theme `theme_gtsummary_language("es")`. This will make it generic, so other languages may be added later.

Here's what we'll need to do:
1. Identify all headers, footnotes, and other text that may appear in gtsummary tables, and provide translations into Spanish.
1. Here is where the function names are converted into their English names to be added to the footnote.  https://github.com/ddsjoberg/gtsummary/blob/f3ca5edbd85d7cd4bbce58242f3372bf33ae32bc/R/utils-tbl_summary.R#L657 We will need Spanish translations for each of them.

In the meantime, you may want to check out a new function for updating footnotes in the dev version http://www.danieldsjoberg.com/gtsummary/dev/reference/modify_footnote.html

**Comment by oranwutang** [comment]
Oh I'm glad that you like the idea!

Please give me a couple of days for getting this done.

Best regards!

**Comment by ddsjoberg** [comment]
Hi @oranwutang !

I am thinking that something simple for the translations would be appropriate for this task.

If you begin to fill in the translations in the attached excel file, I can make the updates to on the internals to begin to allows for translations.

[gtsummary_translations.xlsx](https://github.com/ddsjoberg/gtsummary/files/4703932/gtsummary_translations.xlsx)

**Comment by oranwutang** [comment]
Hi @ddsjoberg!

Here I'm sending you the file with the translated labels, I've added others that I have found while using gtsummary.

Also, I added all the possible translations that you can find in spanish for "Yes/No", It will be very very nice if gtsummary detects it as I think it does here:

[]https://github.com/ddsjoberg/gtsummary/blob/f3ca5edbd85d7cd4bbce58242f3372bf33ae32bc/R/utils-tbl_summary.R#L60

Please let me know if I can be of any further help.

Your idea of using themes for making gtsummary polyglot is really good, I'm eager to see this working.

Best regards!

[gtsummary_translations.xlsx](https://github.com/ddsjoberg/gtsummary/files/4705415/gtsummary_translations.xlsx)

**Comment by oranwutang** [comment]
Pull request sent #512
