### ISSUE TITLE
Return all columns of `broom::tidy()` in `x$table_body`

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#516]
Recently, I was just playing with `parse_fit()` which is an internal function:

```r
> mod <- glm(response ~ age * grade, trial, family = binomial(link = "logit"))
> gtsummary:::parse_fit(mod, broom::tidy(mod, conf.int = TRUE, exponentiate = TRUE), NULL, NULL)
# A tibble: 9 x 10
  variable    var_type    row_ref row_type label                N estimate conf.low conf.high p.value
  <chr>       <chr>       <lgl>   <chr>    <chr>            <int>    <dbl>    <dbl>     <dbl>   <dbl>
1 (Intercept) continuous  NA      label    (Intercept)        183    0.148   0.0203     0.833  0.0411
2 age         continuous  NA      label    Age, yrs           183    1.03    0.990      1.07   0.182 
3 grade       categorical NA      label    Grade              183   NA      NA         NA     NA     
4 grade       categorical TRUE    level    I                  183   NA      NA         NA     NA     
5 grade       categorical FALSE   level    II                 183    1.53    0.0925    25.3    0.765 
6 grade       categorical FALSE   level    III                183    1.45    0.0950    22.3    0.789 
7 age:grade   interaction NA      label    Age, yrs * Grade   183   NA      NA         NA     NA     
8 age:grade   interaction NA      level    Age, yrs * II      183    0.988   0.934      1.04   0.669 
9 age:grade   interaction NA      level    Age, yrs * III     183    0.993   0.941      1.05   0.786 
```

It's a nice way to get  broom results with additional rows (i.e. reference terms) and nice labels, for example for a custom forest plot.

I was wondering if it could be worth that `gtsummary` could export a function built on the package's internal function to produce a tibble for the results. Compared to the output of `parse_fit()` it could be nice in such function to keep all columns produced by `broom::tidy()`, and maybe to keep the original `term` columns (for non reference rows).

**Comment by ddsjoberg** [comment]
Hi @larmarange!

The output from `parse_fit()` and the `x$table_body()` data frame are pretty similar. I've had an idea peculating recently that would return all columns from `broom::tidy()` to `x$table_body()`.  We would allow users to print any of the columns returned from `broom::tidy()` in `tbl_regression()` output.  I think once this update is made, you could use `x$table_body` and we wouldn't need to export a new function. Is that correct?

**Comment by larmarange** [comment]
It would be great. 

And yes, if everything is directly available in `x$table_body`, no need for exporting a specific function.

**Comment by ddsjoberg** [comment]
@larmarange , the columns from tidy are now in x$table_body!

**Comment by larmarange** [comment]
Thanks a lot
