### ISSUE TITLE
Compatibilty of tbl_regression() with nnet::multinom()

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#517]
Currently, `tbl_regression()` do not handle properly multinomial regression done with `nnet::multinom()` due to the fact that there are several series of odds ratio (for each level of the outcome variable).

```r
library(nnet)
library(gtsummary)
mod <- multinom(Species ~ ., data = iris)
#> # weights:  18 (10 variable)
#> initial  value 164.791843 
#> iter  10 value 16.177348
#> iter  20 value 7.111438
#> iter  30 value 6.182999
#> iter  40 value 5.984028
#> iter  50 value 5.961278
#> iter  60 value 5.954900
#> iter  70 value 5.951851
#> iter  80 value 5.950343
#> iter  90 value 5.949904
#> iter 100 value 5.949867
#> final  value 5.949867 
#> stopped after 100 iterations
as_tibble(tbl_regression(mod))
#> # A tibble: 8 x 4
#>   `**Characteristic**` `**Beta**` `**95% CI**` `**p-value**`
#>   <chr>                <chr>      <chr>        <chr>        
#> 1 Sepal.Length         -5.5       -182, 171    >0.9         
#> 2 Sepal.Length         -7.9       -184, 168    >0.9         
#> 3 Sepal.Width          -8.7       -317, 299    >0.9         
#> 4 Sepal.Width          -15        -323, 293    >0.9         
#> 5 Petal.Length         14         -104, 132    0.8          
#> 6 Petal.Length         24         -95, 142     0.7          
#> 7 Petal.Width          -3.1       -92, 86      >0.9         
#> 8 Petal.Width          15         -75, 105     0.7
```

**Comment by ddsjoberg** [comment]
thanks @larmarange !

What would you like the results to look like?  Essentially, we're printing the estimate, conf.low, conf.high, and p.value columns from `broom::tidy()`.  You can pass a custom tidier using the `tidy_fun=` argument.
http://www.danieldsjoberg.com/gtsummary/dev/reference/vetted_models.html#custom-tidiers

``` r
library(nnet)
mod <- multinom(Species ~ ., data = iris)
#> # weights:  18 (10 variable)
#> initial  value 164.791843 
#> iter  10 value 16.177348
#> iter  20 value 7.111438
#> iter  30 value 6.182999
#> iter  40 value 5.984028
#> iter  50 value 5.961278
#> iter  60 value 5.954900
#> iter  70 value 5.951851
#> iter  80 value 5.950343
#> iter  90 value 5.949904
#> iter 100 value 5.949867
#> final  value 5.949867 
#> stopped after 100 iterations
broom::tidy(mod, conf.int = TRUE)
#> # A tibble: 10 x 8
#>    y.level    term      estimate std.error statistic p.value  conf.low conf.high
#>    <chr>      <chr>        <dbl>     <dbl>     <dbl>   <dbl>     <dbl>     <dbl>
#>  1 versicolor (Interce~ 1.31e+ 8      35.0    0.534    0.593 2.24e- 22  7.67e 37
#>  2 versicolor Sepal.Le~ 4.26e- 3      89.9   -0.0607   0.952 1.30e- 79  1.40e 74
#>  3 versicolor Sepal.Wi~ 1.65e- 4     157.    -0.0554   0.956 3.50e-138  7.81e129
#>  4 versicolor Petal.Le~ 1.54e+ 6      60.2    0.237    0.813 8.94e- 46  2.64e 57
#>  5 versicolor Petal.Wi~ 4.52e- 2      45.5   -0.0681   0.946 8.61e- 41  2.37e 37
#>  6 virginica  (Interce~ 4.45e-11      35.8   -0.666    0.505 1.60e- 41  1.24e 20
#>  7 virginica  Sepal.Le~ 3.62e- 4      89.9   -0.0881   0.930 1.06e- 80  1.23e 73
#>  8 virginica  Sepal.Wi~ 2.11e- 7     157.    -0.0978   0.922 3.84e-141  1.16e127
#>  9 virginica  Petal.Le~ 1.89e+10      60.5    0.391    0.696 6.39e- 42  5.56e 61
#> 10 virginica  Petal.Wi~ 3.74e+ 6      45.9    0.330    0.742 2.98e- 33  4.70e 45
```

<sup>Created on 2020-06-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
With a multinomial model, we have two sets of odds ratio: one for "versicolor vs. setosa" and one for "virginica vs. setosa" that could be identified through the `y.level` column provided by broom.

They are two possibilities to present such table:

- using 2 x 3 columns (like comparing two models with `tbl_merge()`
- or using row group, by presenting one on top of the second

It requires in all cases that the y.level pass through the tidiers.

**Comment by larmarange** [comment]
As mentioned in #516, if  all columns from `broom::tidy()` are passed to `x$table_body`, it would made things much easier.

**Comment by ddsjoberg** [comment]
I think this table would work well for a multinomial outcome.

(I think you need the dev version of gtsummary to use the `group_header=` argument in `tbl_stack()`.  We're releasing this version this week.)

```r
library(nnet)
library(gtsummary)
mod <- multinom(Species ~ ., data = iris)
broom::tidy(mod)

# table with versicolor coefs
tbl1 <- tbl_regression(
  mod, 
  tidy_fun = function(x, ...) broom::tidy(x, ...) %>% dplyr::filter(y.level == "versicolor")
)

# table with virginica coefs
tbl2 <- tbl_regression(
  mod, 
  tidy_fun = function(x, ...) broom::tidy(x, ...) %>% dplyr::filter(y.level == "virginica")
)

# stack both tables together
tbl_stack(list(tbl1, tbl2), group_header = c("versicolor", "virginica"))
```

![image](https://user-images.githubusercontent.com/26774684/83535974-a78e0500-a4c0-11ea-8d71-eb6f689a50d5.png)

**Comment by larmarange** [comment]
yes. this table would work.

Just a quick question, do you think that this treatment could be integrated directly in `tbl_regression()`.

If as an advanced user I'm able to manage such trick, it would not be the case for many of my students. Ideally, it would be great for them to do directly `tbl_regression(mod)` to get this result.

**Comment by larmarange** [comment]
Anyway, thanks again for your quick answers

**Comment by ddsjoberg** [comment]
It would take a big restructuring of the internals, but it is possible.  I'll leave this open and think about the best way it could be implemented.

**Comment by larmarange** [comment]
thank you

**Comment by ddsjoberg** [comment]
FYI, I started the implementation of this. here https://github.com/ddsjoberg/gtsummary/pull/606

Could still be a while off before is merged, but it's coming!

**Comment by sdkauer** [comment]
This is fantastic! Thanks so much. I'm learning as I go and have this code working like a dream and even managed to merge rather than stack, which looks great. 
I would ideally love relative risk ratios rather than coefficients.  I've been trying to figure it out but I am stumped. Any help would be appreciated!

**Comment by ddsjoberg** [comment]
@sdkauer , use the `exponentiate = TRUE` argument to get odds ratios.  You'll find more details about this on the broom package website!

**Comment by sdkauer** [comment]
Well isn't that simple! Thanks so much - ddsjoberg! This is perfect.

**Comment by ddsjoberg** [comment]
Closing this issue and will add it when i add the method for mice models....tracking in issue #645
