### ISSUE TITLE
huxtable default printing?

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#518]
Hi @hughjonesd !

Since we added huxtable printing support, I've seen these odd default printing with huxtable notes appearing (reprex below).  Have you seen anything like this before?

Thanks!

``` r
library(gtsummary)
lm(age ~ marker + grade, trial) %>%
  tbl_regression() %>%
  purrr::pluck("table_body") 
#> Warning in knit_print.huxtable(ht): Unrecognized output format "markdown". Using `to_screen` to print huxtables.
#> Set options("huxtable.knitr_output_format") manually to "latex", "html", "rtf", "docx", "pptx", "md" or "screen".
```

+-----------------------------------------------------------------------
¦ variable var\_type row\_ref row\_type label N estimate  
+-----------------------------------------------------------------------
¦ marker continuo label Marker 179 -0.0379  
¦ us Level,  
¦ ng/mL  
¦ grade categori label Grade 179        
¦ cal  
¦ grade categori TRUE level I 179        
¦ cal  
¦ grade categori FALSE level II 179 0.636   
¦ cal  
¦ grade categori FALSE level III 179 2.39    
¦ cal  
+-----------------------------------------------------------------------

Column names: variable, var\_type, row\_ref, row\_type, label, N, estimate,
conf.low, conf.high, ci, p.value

7/11 columns shown.

<sup>Created on 2020-06-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hughjonesd** [comment]
Hmm, if I run that reprex I just get a tibble, no complaints from huxtable, does it need an `as_huxtable`? Is this in a particular kind of markdown document?

**Comment by ddsjoberg** [comment]
Thank you for checking it out, @hughjonesd !  This is the direct output from `reprex::reprex()` (which is a type of markdown, but I don't know the precise type), and it's trying to print the data frame at the end as a huxtable rather than a data frame.

I'll keep an eye out, and post here if I see it again.  In other examples, running the code 2 or 3 times reverting the printing to proper print methods (but this example did not).

**Comment by hughjonesd** [comment]
I suspect the answer will be to set `options(huxtable.knit_print_df=FALSE)`. In other words, this has nothing to do with the huxtable code in your package; it comes from loading the huxtable package, which then tries to pretty-print your data frame. See `?"huxtable-options"`.

**Comment by hughjonesd** [comment]
... which in turn makes me think this option is a bit too aggressive. It makes sense for the end user, but not if other packages are loading huxtable – too likely to confuse the user. I might set it in `.onLoad()` rather than `.onAttach()`.

**Comment by ddsjoberg** [comment]
Ah, gotcha @hughjonesd ! Sounds like a reasonable update to make moving the option to onAttach.  Have you planned a release already?  I'll be watching for it!  Thanks!

**Comment by hughjonesd** [comment]
Shortly. I'm getting a bit of publicity out there to see if some people try
& test it. See
https://hughjonesd.github.io/whats-new-in-huxtable-5.0.0.html

**Comment by ddsjoberg** [comment]
Nice! Looks like some great features in the next release!  Are there any breaking changes I should be concerned about? 😆
@hughjonesd

**Comment by hughjonesd** [comment]
See the NEWS file

David

**Comment by ddsjoberg** [comment]
Confirmed this issue has been resolved in the dev version of huxtable. 

We need to update `as_huxtable.gtsummary()` when the new version of huxtable is released.  The current code used with the dev version of huxtable results in some formatting issues:
![image](https://user-images.githubusercontent.com/26774684/83682750-5bbb8880-a5b2-11ea-9547-9659978bab41.png)

**Comment by hughjonesd** [comment]
Tell me what you want it to look like. I see the Grade III doesn't look nicely aligned. My thought would be to right align everything, as a first shot.

**Comment by ddsjoberg** [comment]
Thanks @hughjonesd for taking a look! I started making the needed update in PR #520. I think the alignment issue was due to the changed default in hux() that included the column name in the output.

But I did get an error with PDF output. But I'm not sure if this is related to my latex setup.
