### ISSUE TITLE
More flexibility for the label argument

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#523]
Maybe something you could consider, it's allowing more flexibility for the label argument, allowing to provide a named vector, i.e. something like `label = c(age = "Age in years", sex = "Sex of interviewee")`.

A code like the following example could transform such named vector into a list of formula.

```r
  # transform label from a named vector to a list of formulas
  if (!is.null(label) && is.character(label))
    label <- unname(mapply(
      FUN = function(n, l){formula(paste0(n, " ~ \"", l, "\""))}, 
      names(label), 
      label
    ))
```

**Comment by ddsjoberg** [comment]
Hi @larmarange !

We do allow for a named list in place of the formula notation.  
```r
label = list(age = "Age in years", sex = "Sex of interviewee")
```
The only caveat for using the named list instead of the formula notation is that the names are not checked, meaning that if you spell the variable name wrong you won't get an error.

``` r
library(gtsummary)
tbl <- trial[c("age", "trt")] %>%
  tbl_summary(label = list(not_a_variable = "not a variable"))

tbl <- trial[c("age", "trt")] %>%
  tbl_summary(label = list(not_a_variable ~ "not a variable"))
#> Error: Error in `label=` argument input. Select from 'age', 'trt'
```

<sup>Created on 2020-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
I should also say that this applies to all arguments that take a list of formulas...they can be replaced with named lists.

**Comment by larmarange** [comment]
Thank you very much for the clarifications.

I'm still thinking that allowing `label = c(age = "Age in years", sex = "Sex of interviewee")` could be a convenient good addition but would understand if you do not want to implement it.

**Comment by ddsjoberg** [comment]
All of the arguments throughout the package that follow this structure are processed in the same place, so I'll likely leave it as is accepting a named list, but not a named vector.  But I do highly appreciate all the great suggestions you've had!
