### ISSUE TITLE
tbl_stack with named list

### ISSUE THREAD

**Issue by matthieu-faron** [ddsjoberg/gtsummary#524]
Hi, thank you for the great functions in gtsummary.

I frequently uses the survminer packages to perform survival analysis. The survminer::surv_fit() functions return a list of survfit object which is useful sometimes (different formulas on the same dataset or same formula on different datasetc etc...).

Was trying to calculate both Overall and Disease-free survival on the same datasets, via surv_fit() on a list of formula then map(x, tbl_survfit) %>% tbl_stack() on the results (see example below).
But when the x list has names (like after map() or lapply() ) setting group_header argument won't work. I thinks this is because in tbl_stack() the imap_dfr() is short hand for map2(x, names(x), ...) if x has names, or map2(x, seq_along(x), ...) if it does not. So the function calls depends if the list has names or not

I guess replacing :
```r
 else if (!is.null(group_header)) {
    results$table_body <- imap_dfr(tbls, ~pluck(.x, "table_body") %>% 
      mutate(groupname_col = group_header[.y])) %>% group_by(.data$groupname_col)
  } 
```
With :

```r
 else if (!is.null(group_header)) {
    results$table_body <-map2_dfr(tbls, seq_along(tbls), ~pluck(.x, "table_body") %>% 
      mutate(groupname_col = group_header[.y])) %>% group_by(.data$groupname_col)
  } 
```
Will allows to use both named and unnamed list

A short reprex
```r
library(survminer)
library(gt_summary)
library(tidyverse)

## Separate regression

fit1 <- survfit(Surv(ttdeath, death) ~ trt, trial)
fit2 <- survfit(Surv(ttdeath, death) ~ stage, trial)


tbl_ex1 <- tbl_survfit( fit1, times = c(12, 24))
tbl_ex2 <- tbl_survfit(fit2,  times = c(12, 24))

tbl_stack(list(tbl_ex1, tbl_ex2), group_header = c("Treatment", "Stage"))


## List of regression

flist <- list(treatment = Surv(ttdeath, death) ~ trt,
              stage = Surv(ttdeath, death) ~ stage
)

fit_all <- survminer::surv_fit(flist, data = trial)

## don't works
map(fit_all, ~ tbl_survfit(., time = c(12,24))) %>% tbl_stack(group_header = c("Treatment", "Stage"))

## works
map(fit_all, ~ tbl_survfit(., time = c(12,24))) %>% set_names(NULL) %>% tbl_stack(group_header = c("Treatment", "Stage"))
```

Thanks again for the great work on gt_summary !

**Comment by karissawhiting** [comment]
Thanks for pointing this out @matthieu-faron ! I agree this should allow either named or unnamed lists.

I will take a look at this issue at the end of the week, or feel free to submit a PR.

**Comment by ddsjoberg** [comment]
@matthieu-faron thank you for this report and the details example! I used your code to update, and everything works perfectly.  this update will be included in the next CRAN release!
