### ISSUE TITLE
Resolving problem: There was an error in 'add_p()' 

### ISSUE THREAD

**Issue by DeFilippis** [ddsjoberg/gtsummary#529]
For one of my variables in my model (education), I'm getting an error when I run the basic `tbl_summary` command.  

```
There was an error in 'add_p()' for variable 'education', p-value omitted:
Error in stats::fisher.test(data[[variable]], as.factor(data[[by]])): FEXACT error 7(location). LDSTP=18540 is too small for this problem,
  (pastp=151.714, ipn_0:=ipoin[itp=431]=15061, stp[ipn_0]=151.645).
Increase workspace or consider using 'simulate.p.value=TRUE'
```

I'm not sure how to diagnose this issue.  Do you have recommendations on how to fix this, or how to activate the flag 'simulate.p.value=TRUE' from within `gtsummary`? It seems to be coming from another library.

**Comment by ddsjoberg** [comment]
Hi @DeFilippis , 

To diagnose the issue, I would try to run `fisher.test()` on your data before passing it to `tbl_summary()`.  That way you'll have full access to the data and error when it occurs.

If you need to use a non-default version of a function, you'll need to pass a custom function to `add_p()`.  The last example in the `add_p()` help file will walk you through the process. http://www.danieldsjoberg.com/gtsummary/reference/add_p.tbl_summary.html

Yours will look something like this perhaps:
```r
my_fisher <- function(data, variable, by, ...) {
  result <- list()
  result$p <- stats::fisher.test(data[[variable]], as.factor(data[[by]], simulate.p.value=TRUE)$p.value
  result$test <- "Fisher's exact test"
  result
}

trial[c("response", "trt")] %>%
  tbl_summary(by = trt) %>%
  add_p(test = education ~ "my_fisher")
```

**Comment by MostafaGhaderian** [comment]
Thank you so very much.
