### ISSUE TITLE
Is it possible to change the text "Unkonwn" for missing observations?

### ISSUE THREAD

**Issue by zeyunlu** [ddsjoberg/gtsummary#532]
So for missing observations, we have default text "Unknown", is it possible to change to other text, such as "Missing" or "N/A"?

Also, for rows of "Unknown", currently it only shows the number of missing observations, is it possible to show N(%) something like the statistic of continuous variable?

Thanks!

**Comment by ddsjoberg** [comment]
Hi @zeyunlu ,

1. Use the `tbl_summary(missing_text=)` argument to change the text for the missing row.
2. You may use `{N_obs}`, `{N_miss}`, `{N_nonmiss}`, `{p_miss}`, `{p_nonmiss}` to report number of missing/non-missing along with percentages, but they cannot be added to the "Unknown" row.  The N (%) presentation was very confusing for categorical variables, and we've currently don't have an option to change it.  You can also use the `add_n()` function to report on the number of missing/non-missing. 

Review the website for details.
http://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html

Also, please use GitHub Issues to report bugs. The gtsummary team is very happy to assist with questions, and stackoverflow.com is the best venue for that! Use the gtsummary tag when you post a question, and the gtsummary authors will be notified of the post!
