### ISSUE TITLE
Data with "Yes" and "No" factor levels cannot correctly display

### ISSUE THREAD

**Issue by zeyunlu** [ddsjoberg/gtsummary#533]
If we run following codes, "Yes" and "No" cannot be correctly displayed.

I'm not sure if it is a bug or it is intentionally programmed like this.

It would be great if we are able to use "Yes" and "No" as data factor levels

```r
tmp <- data.frame(v1 = factor(sample(c("Yes", "No"), 100, replace = TRUE)),
  v2 = factor(sample(c("Yes", "No"), 100, replace = TRUE)))

tbl_summary(tmp)

tmp2 <- data.frame(v1 = factor(sample(c("1", "2"), 100, replace = TRUE)),
  v2 = factor(sample(c("Y", "N"), 100, replace = TRUE)))

tbl_summary(tmp2)
```

**Comment by ddsjoberg** [comment]
Review the `tbl_summary(type=)` documentation for details on default printing. The default is to print yes/no as dichotomous variables, and all defaults can be updated. 
http://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html#type-argument

Happy Coding!
