### ISSUE TITLE
add an option to customize "Overall" header when using add_overall()

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#536]
When using `add_overall()` in a non-English table, it would be nice to have a very easy way to change the text of the header, something like `tbl %>% add_overall(header = "Total")`

**Comment by ddsjoberg** [comment]
Hi @larmarange , I like your suggestion!  In the meantime, you can use:
```r
trial %>%
  tbl_summary(by = trt) %>%
  add_overall() %>%
  modify_header(stat_0 = "**Total**")
```

**Comment by larmarange** [comment]
Hi @ddsjoberg   thanks for the feedback

Yes, I noted the possibility of using `modify_header()`. This last function allows deep customization, but not very intuitive when change changing the label. For example, in the example you provided, we lost the total number of observations.

**Comment by ddsjoberg** [comment]
1. You can maintain the the N with 
```r
trial %>%
  tbl_summary(by = trt) %>%
  add_overall() %>%
  modify_header(stat_0 = "**Total** (N =  {N})")
```

2. We'll soon be releasing a language theme, where all the default printing can be in the language of your choice.  At the moment, it only supports Spanish, but it'll be pretty easy to add French!

**Comment by larmarange** [comment]
Let me know. I would be happy to contribute to add French

**Comment by ddsjoberg** [comment]
Thank you! The Spanish is under review at the moment, and when it's done we'll be ready to add other languages.

**Comment by ddsjoberg** [comment]
Hello @larmarange !

We added a French theme, and it's in dev version of gtsummary now.  Would you mind checking it out?
http://www.danieldsjoberg.com/gtsummary/dev/reference/theme_gtsummary.html
http://www.danieldsjoberg.com/gtsummary/dev/articles/themes.html

**Comment by larmarange** [comment]
I will look at it with pleasure.

Just before, I need to finalize a first draft of compatibility of  tbl_summary() with survey objects

**Comment by ddsjoberg** [comment]
Awesome! That'll be great!
Here is each translation in a CSV file if that is easier to peruse https://github.com/ddsjoberg/gtsummary/blob/master/data-raw/gtsummary_translated.csv

**Comment by ddsjoberg** [comment]
added 7/1/2020
