### ISSUE TITLE
Should flextable and huxtable both be moved to Suggests?

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#546]
gtsummary has many dependencies. We are importing both flextable and huxtable for the singular purpose of getting their generic function `as_flextable()` and `as_huxtable()`. If just changed the names of our functions that convert these objects to something else, we could make these packages optional, and only prompt their installation for the users who need this functionality.

**Comment by ddsjoberg** [comment]
This may be a solution to register the generic conditionally without needing to depend on the package.
https://community.rstudio.com/t/write-s3-methods-for-generics-from-other-packages-without-importing-that-package/8884/4

**Comment by hughjonesd** [comment]
I think that since R 3.6.0, you can do this without any hacks: https://github.com/r-lib/roxygen2/issues/796

**Comment by ddsjoberg** [comment]
Ahh, thanks @hughjonesd !!
