### ISSUE TITLE
Add column

### ISSUE THREAD

**Issue by tormodb** [ddsjoberg/gtsummary#552]
Please do not use this form to ask a question, or ask for assistance. Instead, ask on <https://stackoverflow.com/> using the gtsummary tag.

**Is your feature request related to a problem? Please describe.**
I often would like to add effect size measures to tables created with `tbl_summary`. These would vary depending on the type of data and test conducted (e.g. _Cohen's d_, _Cramer's V_ etc). 

**Describe the solution you'd like**
I would like to have table summary calculate effect sizes (e.g. `add_effectsize()`). Alternatively, I would be happy with some way of adding a column with these data to the table generated with tbl_summary.  

**Describe alternatives you've considered**
I have manually added this information to the object crated from table summary (i.e. written directly to `.$table_body `and `.$meta_data`). This is cumbersome, and I have not found a way to add to `.$table_header`. 

**Additional context**

**Comment by ddsjoberg** [comment]
HI @tormodb !

We recently added the `add_stat()` function that allows you to add any statistic you'd like.  Here's an example adding Cohen's D.
http://www.danieldsjoberg.com/gtsummary/reference/add_stat.html

```r
library(tidyverse)
library(gtsummary)

# function to calculate and format the Cohen's D with confidence interval
my_EStest <- function(data, variable, by, ...) {
  # Cohen's D
  d <- effsize::cohen.d(data[[variable]] ~ as.factor(data[[by]]), 
                   conf.level=.90, pooled=TRUE, paired=FALSE, 
                   hedges.correction=TRUE)

  # Formatting statistic with CI
  est <- style_sigfig(d$estimate)
  ci <- style_sigfig(d$conf.int) %>% paste(collapse = ", ")

  # returning estimate with CI together
  str_glue("{est} ({ci})")
}

add_ES <-
  trial %>%
  select(trt, age) %>%
  tbl_summary(by = trt, missing = "no",
              statistic = list(all_continuous() ~ "{mean} ({sd})"),
              digits = list(all_continuous() ~ c(1,1))) %>%
  add_p(test = everything() ~ t.test) %>%
  add_stat(
    fns = everything() ~ my_EStest, # add Cohen's D for all variables
    header = "**ES (90% CI)**"
  ) %>%
  modify_footnote(add_stat_1 ~ "Cohen's D (90% CI)")
```
![image](https://user-images.githubusercontent.com/26774684/85858891-57862380-b78a-11ea-9508-c7e1b358c8e2.png)

**Comment by tormodb** [comment]
Wow - this package is fantastic, thank you so much! 

Could this approach generalize to a table with more variables where some are categorical and other continuous? I see that add stat has a `fns = everything()` argument. Can I pass `continuous` or `categorical` here, like I can for `statistic`?

**Comment by ddsjoberg** [comment]
You're exactly right. If you wanted all continuous variables to show Cohen's D (via the `my_EStest()` function), and categorical variables to have another summary (via a function called `cat_fun()`, for example), you would use this code:

```r
add_stat(
  fns = list(
    all_continuous() ~ my_EStest, 
    all_categorical() ~ cat_fun
  ),
  header = "**My Column Header**"
)
``` 

Happy Coding!
