### ISSUE TITLE
Should add_global_p() use type II by default?

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#553]
Currently, `add_global_p()` use type-III approach for calculating global p-values.

When there is nos interaction, type 2 and 3 are almost equivalent. 

If there are interactions, in general, if there is no significant interaction effect, then type II is more powerful, and follows the principle of marginality. If an interaction is present, then type II is inappropriate while type III can still be used, but results need to be interpreted with caution. BUT **it is necessary to set the contrasts option in R**. Because the multi-way ANOVA model is over-parameterised, it is necessary to choose a contrast setting that sums to zero, otherwise, the ANOVA analysis will give incorrect results with respect to the expected hypothesis. (**The default contrasts type does not satisfy this requirement**.)

cf. https://mcfromnz.wordpress.com/2011/03/02/anova-type-iiiiii-ss-explained/

Considering that less advanced users will use default contrasts and usually models without interaction, should it be better to use type II as a default value and let advance users switch to type III?

To be noted, it is currently not possible to change the type of p-value in `add_global_p()`

**Comment by ddsjoberg** [comment]
oh boy, I haven't thought about the SS types in years! 😆 

In my field, type III is the most common (despite the good argument you've made above!), so I prefer to keep type III the default. But we should allow users to request type 2 should they need it!  That will be a very easy fix, thankfully. And we can update the themes to allow users to change the default to type II if that is their preference.
