### ISSUE TITLE
using gtsummary in jamovi modules

### ISSUE THREAD

**Issue by sbalci** [ddsjoberg/gtsummary#563]
Dear Developers,

I liked the output of gtsummary, and thought it may be good to add into a jamovi module. I used it to generate Table One and Cross Tables. With each analysis appropriate citation are given. 

https://sbalci.github.io/ClinicoPathJamoviModule/

Please let me know if you have comments or suggestions. 

Best wishes

<img width="1240" alt="Ekran Resmi 2020-07-06 12 31 45" src="https://user-images.githubusercontent.com/7208830/86578746-f8dc5900-bf84-11ea-8e1b-314f58110c3d.png">

<img width="1235" alt="Ekran Resmi 2020-07-06 12 32 22" src="https://user-images.githubusercontent.com/7208830/86578755-fbd74980-bf84-11ea-8efb-db0f1f280eba.png">

**Comment by ddsjoberg** [comment]
Hi @sbalci !

The application looks great.  Couple of questions/comments:

1. What is the default output format? It looks like it's not reading the bold weight correctly.  We can update to be respected.

1. gtsummary guesses the type of data (continuous/categorical/dichotomous). Is there a way to change the default?

1. Can we add the ability to change the variable label?

1. In the second table, it looks like the N, p-value, and q-value is being added by default.  Those should be options.

1. It looks like the first table is using `bold_labels()`.  That should also be an option.

Fantastic work!

**Comment by sbalci** [comment]
Hi @ddsjoberg

Thank you very much. I am glad you liked it. I have selected arguments for my taste. Actually many could be made optional.

You may also see jamovi https://www.jamovi.org development guide here: https://dev.jamovi.org 

For the comments: 

1) The output format can be changed. But there is not a markdown output. Here I have used html output.
I have used the code from your documentation,  it is here: https://github.com/sbalci/ClinicoPathJamoviModule/blob/master/R/crosstable.b.R#L211

I found `gtsummary::as_kable_extra()`useful and used it.

I think here the markdown is not converted correctly in the output. 

2) The variables can be changed from jamovi menu. When user changes the data type, then the output of table changes.

<img width="728" alt="Ekran Resmi 2020-07-06 17 12 20" src="https://user-images.githubusercontent.com/7208830/86602824-e590b400-bfab-11ea-9640-e2548cf36442.png">
 

3) Variable label can also be changed as variable type.

4) N, p-value, and q-value can be made optional. I will add options in later releases. Especially q-value is nearly never used in clinical and pathology studies. So it may cause questions in the users.

5) Actually I would like the variable names to be bold also. But it is a matter of taste. I can add that argument as option.

**Comment by ddsjoberg** [comment]
Hello @sbalci !

This is all super interesting!  Good luck in your development!  If you ever have feature requests for gtsummary, please feel free to reach out. Happy Coding! 🕺 


> Hi @ddsjoberg
> 
> Thank you very much. I am glad you liked it. I have selected arguments for my taste. Actually many could be made optional.
> 
> You may also see jamovi https://www.jamovi.org development guide here: https://dev.jamovi.org
> 
> For the comments:
> 
> 1. The output format can be changed. But there is not a markdown output. Here I have used html output.
>    I have used the code from your documentation,  it is here: https://github.com/sbalci/ClinicoPathJamoviModule/blob/master/R/crosstable.b.R#L211
> 
> I found `gtsummary::as_kable_extra()`useful and used it.
> 
> I think here the markdown is not converted correctly in the output.
> 
> 1. The variables can be changed from jamovi menu. When user changes the data type, then the output of table changes.
> 
> <img alt="Ekran Resmi 2020-07-06 17 12 20" width="728" src="https://user-images.githubusercontent.com/7208830/86602824-e590b400-bfab-11ea-9640-e2548cf36442.png">
> 
> 1. Variable label can also be changed as variable type.
> 2. N, p-value, and q-value can be made optional. I will add options in later releases. Especially q-value is nearly never used in clinical and pathology studies. So it may cause questions in the users.
> 3. Actually I would like the variable names to be bold also. But it is a matter of taste. I can add that argument as option.
