### ISSUE TITLE
Add feature for multiple comparissons

### ISSUE THREAD

**Issue by CodieMonster** [ddsjoberg/gtsummary#570]
Hey,
I find your package very helpfull and well-made.
I however have two suggestions for features that could improve the overall experience and application potential.
I am working on a dataset that contain three patient groups. I have read the documentation, and there seems to be no way to compare multiple groups by t-test/wilcox-test. The only way to compare multiple groups is by Kruskall-Wallis test, however this is not always suitable. So if you could add a feature that adds multiple columns for each t-test comparisson, it would be very help for myself and other users, I believe.
I also think you should add welch test to possible tests that can be perform, as I only see t.test at the moment - and its not specified if its a regular t.test.

Thank you very much for the package you made.

**Comment by ddsjoberg** [comment]
Hi @CodieMonster ! Thank you for the comment!

> I have read the documentation, and there seems to be no way to compare multiple groups by t-test/wilcox-test.

Those tests only compare two groups.  The generalized versions of these tests to allow for comparison of 3 or more groups are ANOVA and the Kruskall-Wallis (both available within the package).

> So if you could add a feature that adds multiple columns for each t-test comparison, it would be very help for myself and other users, I believe.

I think what you're referring to is pairwise comparisons after ANOVA?  Is that correct? Out-of-the-box support of this is out-of-scope at the moment, but it is possible to get what you're looking for.  You can use the `add_stat()` function to add _any_ statistic you like to a `tbl_summary()` table.  There is another alternative that is outlined in the table gallery http://www.danieldsjoberg.com/gtsummary/articles/gallery.html#summary-tables-1
![image](https://user-images.githubusercontent.com/26774684/87067841-a13b2900-c1e2-11ea-94cc-4fab94159b39.png)

**Comment by CodieMonster** [comment]
Thank for you quick and promt comment! I will try what you suggested. I also have another question regarding:


set_gtsummary_theme<http://www.danieldsjoberg.com/gtsummary/reference/set_gtsummary_theme.html>(theme_gtsummary_journal<http://www.danieldsjoberg.com/gtsummary/reference/theme_gtsummary.html>(journal = "jama"))


Does this offer themes for other journals than Jama?


________________________________
Fra: Daniel Sjoberg <notifications@github.com>
Sendt: torsdag, juli 9, 2020 6:49 pm
Til: ddsjoberg/gtsummary
Kopi: CodieMonster; Mention
Emne: Re: [ddsjoberg/gtsummary] Add feature for multiple comparissons (#570)


Hi @CodieMonster<https://github.com/CodieMonster> ! Thank you for the comment!

I have read the documentation, and there seems to be no way to compare multiple groups by t-test/wilcox-test.

Those tests only compare two groups. The generalized versions of these tests to allow for comparison of 3 or more groups are ANOVA and the Kruskall-Wallis (both available within the package).

So if you could add a feature that adds multiple columns for each t-test comparison, it would be very help for myself and other users, I believe.

I think what you're referring to is pairwise comparisons after ANOVA? Is that correct? Out-of-the-box support of this is out-of-scope at the moment, but it is possible to get what you're looking for. You can use the add_stat() function to add any statistic you like to a tbl_summary() table. There is another alternative that is outlined in the table gallery http://www.danieldsjoberg.com/gtsummary/articles/gallery.html#summary-tables-1
[image]<https://user-images.githubusercontent.com/26774684/87067841-a13b2900-c1e2-11ea-94cc-4fab94159b39.png>

**Comment by ddsjoberg** [comment]
This is a brand new feature, and only includes JAMA at the moment.  Once there is feedback from users, we can begin to add others.

**Comment by hao203** [comment]
> 

Hi, ddsjoberg 
I can not find your example in table gallery.
Would you please give us another link?
Thanks!

**Comment by ddsjoberg** [comment]
@hao203 is this what you're looking for ?
https://stackoverflow.com/questions/70129472

**Comment by hao203** [comment]
> 

Yes, really helpful.
