### ISSUE TITLE
Add N at risk and N events to tbl_survfit

### ISSUE THREAD

**Issue by michaelcurry1123** [ddsjoberg/gtsummary#573]
`tbl_survival` might benefit from also displaying, N at risk, N events, and maybe N censored at a specific time or probability

A possible solution would be to add an argument that looked like `N_counts = c('none','risk','event','censored','all')` and allows the user to pick any combination of the inputs above to show specific counts at a time or probability. 

It is possible to build a table with these inputs from `broom::tidy` but it is more cumbersome than having an input argument to tbl_survival.

**Comment by ddsjoberg** [comment]
hey hey @michaelcurry1123 ! is this something you're still interested in working on?

**Comment by michaelcurry1123** [comment]
@ddsjoberg  hello! I think I will forgo this one. Thanks!
