### ISSUE TITLE
Can I append superscript numbers alongside P values (and not in header) in the p.value column such that I know which statistical test correspond with each P value

### ISSUE THREAD

**Issue by JesseRop** [ddsjoberg/gtsummary#576]
``` r
library(officer)
library(dplyr)
#> Warning: package 'dplyr' was built under R version 3.6.3
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(gtsummary)
#> Warning: package 'gtsummary' was built under R version 3.6.3

trial %>%
  select(trt, response, age, stage, marker, grade) %>%
  tbl_summary(
    by = trt,
    type = list(c(response, grade) ~ "categorical"), # select by variables in c()
    statistic = list(all_continuous() ~ "{mean} ({sd})",
                     all_categorical() ~ "{p}%") # select by summary type
  ) %>%
  add_p(test = list(contains("response") ~ "fisher.test", # select using functions in tidyselect
                    all_continuous() ~ "t.test"))
```
![image](https://user-images.githubusercontent.com/26774684/87840016-7ea4b200-c86b-11ea-93cc-55167c50d11b.png)

<sup>Created on 2020-07-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
HI @JesseRop ! Thanks for the comment.  This would be a great feature to add in the future. In the meantime, you can use this little function I put together to get the output you're looking for.  Hope this helps.

```r
library(gtsummary)

# this function adds footnotes to each pvalue of the test performed
add_p_footnotes <- function(x) {
  # grouping data, one line per type of test performed
  prep_to_create_code <-
    x$meta_data %>%
    filter(!is.na(stat_test_lbl) & stat_test_lbl != "") %>%
    select(variable, stat_test_lbl) %>%
    dplyr::group_nest(stat_test_lbl)
  
  # other calls to apply to x
  prepping_calls <-
    list(rlang::expr(modify_footnote(x, p.value ~ NA_character_)), 
         rlang::expr(as_gt()))
  
  # creating then executing code to add footnotes to each p-value
  map2(
    prep_to_create_code$stat_test_lbl, 
    prep_to_create_code$data, 
    function(x, y) {
      rlang::expr(
        gt::tab_footnote(
          footnote = !!x,
          locations = gt::cells_body(
            columns = vars(p.value),
            rows = variable %in% !!y$variable & row_type == "label"
          )
        )
      )
    }
  ) %>%
    # concatenating expressions with %>% between each of them
    {c(prepping_calls, .)} %>%    
    reduce(function(x, y) expr(!!x %>% !!y)) %>%
    # evaluating expressions
    eval()
}


trial %>%
  select(trt, response, age, stage, marker, grade) %>%
  tbl_summary(
    by = trt,
    type = c(response, grade) ~ "categorical",
    statistic = list(all_continuous() ~ "{mean} ({sd})", 
                     all_categorical() ~ "{p}%") 
  ) %>%
  add_p(
    test = list(response ~ "fisher.test", all_continuous() ~ "t.test")
  ) %>%
  add_p_footnotes()
```

![image](https://user-images.githubusercontent.com/26774684/87840093-d5aa8700-c86b-11ea-9d50-ac91dc1aa92f.png)

**Comment by JesseRop** [comment]
Many thanks for creating this very helpful package and for the speedy response, @ddsjoberg !
I can replicate your example but can't convert it to flextable format using as_flextable since the second object is of the 'list' and not 'gtsummary' class. I will be grateful for assistance with this. 

When I add 
```
%>%  as_flextable()
```
 I get this error 'Error in UseMethod("as_flextable") : 
  no applicable method for 'as_flextable' applied to an object of class "c('gt_tbl', 'list')"'

**Comment by ddsjoberg** [comment]
In the solution I posted, the gtsummary object was converted to a gt table and the footnotes added. Because it has already been converted to a gt table, it cannot then coerced to a flextable.

The solution above essentially takes a gtsummary object, removes the current footnote, converts to gt table, and then adds the footnotes with the `gt::tab_footnote()` function.

You can update the function I wrote replacing `as_gt()` with `as_flextable()`, and `gt::tab_footnote()` with the equivalent from the flextable package. j Do you want to give the update a try? I can likely assist if needed, in the next two weeks. Happy Coding! 🕺 

FYI, the `gtsummary::as_flextable()` function is experimental in the current version. In the next release it is graduating from Experimental status with a slight change to the API. In the current version, you need to run `tbl_summary(trial) %>% gtsummary::as_flextable()`, but in the next version you'll need to run `tbl_summary(trial) %>% flextable::as_flextable()`.

**Comment by JesseRop** [comment]
Many thanks for the guidance, @ddsjoberg 

I have updated the code as advised but I am not able to produce the desired output. The footnote ref_symbol is 1 for all the p values

```
library(gtsummary)
library(flextable)
library(dplyr)
library(purrr)

add_p_footnotes <- function(x) {
  # grouping data, one line per type of test performed
  prep_to_create_code <-
    x$meta_data %>%
    dplyr::filter(!is.na(stat_test_lbl) & stat_test_lbl != "") %>%
    dplyr::select(var_label, stat_test_lbl) %>%
    dplyr::group_nest(stat_test_lbl)
  
  # other calls to apply to x
  prepping_calls <-
    list(rlang::expr(modify_footnote(x, p.value ~ NA_character_)), 
         rlang::expr(gtsummary::as_flextable()))
  
  
  # creating then executing code to add footnotes to each p-value
  map2(
    prep_to_create_code$stat_test_lbl, 
    prep_to_create_code$data, 
    function(x, y) {
      rlang::expr(
        flextable::footnote(
          value = as_paragraph(c(!!x)),
          j = "p.value",
          i = ~ label %in% !!y$var_label,
          ref_symbols = base::which(!!x %in% prep_to_create_code$stat_test_lbl)
        )
      )
    }
  ) %>%
    # concatenating expressions with %>% between each of them
    {c(prepping_calls, .)} %>%    
    purrr::reduce(function(x, y) expr(!!x %>% !!y)) %>%
    # evaluating expressions
    eval()
}


ft <- trial %>%
  dplyr::select(trt, response, age, stage, marker, grade) %>%
  tbl_summary(
    by = trt,
    type = c(response, grade) ~ "categorical",
    statistic = list(all_continuous() ~ "{mean} ({sd})", 
                     all_categorical() ~ "{p}%") 
  ) %>%
  add_p(
    test = list(response ~ "fisher.test", all_continuous() ~ "t.test")
  ) %>%
  add_p_footnotes()

ft

```

![image](https://user-images.githubusercontent.com/18431376/87876571-a158d700-c9e1-11ea-8a11-679e182ceedc.png)

**Comment by ddsjoberg** [comment]
@JesseRop I added the function (`gts_add_p_footnotes()`) in a pull request to the bstfun package here: https://github.com/ddsjoberg/bstfun/pull/11

You can install the package with `remotes::install_github("ddsjoberg/bstfun@gts_add_p_footnotes")`

Happy Coding 👯‍♂️
