### ISSUE TITLE
tbl_stack of 2 tbl_summary objects with different N

### ISSUE THREAD

**Issue by JesseRop** [ddsjoberg/gtsummary#577]
This is an issue related to #234 (https://github.com/ddsjoberg/gtsummary/pull/234) but for tbl_stack.
Stacking 2 tbl_summary objects with different numbers result only the Ns of the first object being displayed in the header. Kindly inform if it is possible to have the 2 stacked objects with separate Ns for instance in the "group_header " rows separating the stacked tables?

``` r
library(survival)
#> Warning: package 'survival' was built under R version 3.6.3
library(gtsummary)
#> Warning: package 'gtsummary' was built under R version 3.6.3

# make dataset that is arbitrarily different size
trial2 <- trial %>%
  dplyr::filter(age > 30)

t1 <- trial %>%
  select(response, trt, grade, age) %>%
  tbl_summary(by = trt) %>% 
  add_p(pvalue_fun = function(x) style_pvalue(x, digits = 2)) %>% 
  add_stat_label()

t1
```

<div id="muturdlnmn" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

<strong>Characteristic</strong>

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>Drug A</strong>, N = 98

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>Drug B</strong>, N = 102

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>p-value</strong><sup class="gt_footnote_marks">1</sup>

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

Tumor Response, n (%)

</td>

<td class="gt_row gt_center">

28 (29%)

</td>

<td class="gt_row gt_center">

33 (34%)

</td>

<td class="gt_row gt_center">

0.64

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

Unknown

</td>

<td class="gt_row gt_center">

3

</td>

<td class="gt_row gt_center">

4

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Grade, n (%)

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

0.87

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

I

</td>

<td class="gt_row gt_center">

35 (36%)

</td>

<td class="gt_row gt_center">

33 (32%)

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

II

</td>

<td class="gt_row gt_center">

32 (33%)

</td>

<td class="gt_row gt_center">

36 (35%)

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

III

</td>

<td class="gt_row gt_center">

31 (32%)

</td>

<td class="gt_row gt_center">

33 (32%)

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Age, yrs, median (IQR)

</td>

<td class="gt_row gt_center">

46 (37, 59)

</td>

<td class="gt_row gt_center">

48 (39, 56)

</td>

<td class="gt_row gt_center">

0.72

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

Unknown

</td>

<td class="gt_row gt_center">

7

</td>

<td class="gt_row gt_center">

4

</td>

<td class="gt_row gt_center">

</td>

</tr>

</tbody>

<tfoot>

<tr class="gt_footnotes">

<td colspan="4">

<p class="gt_footnote">

<sup class="gt_footnote_marks">
<em>1</em>
</sup>

Statistical tests performed: chi-square test of independence; Wilcoxon rank-sum test
<br />

</p>

</td>

</tr>

</tfoot>

</table>

</div>

``` r

# table with different sample size
t2 <- trial2 %>%
  select(response, trt, grade, age) %>%
  tbl_summary(by = trt) %>% 
  add_p(pvalue_fun = function(x) style_pvalue(x, digits = 2)) %>% 
  add_stat_label()

t2
```

<div id="jztermsvuw" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

<strong>Characteristic</strong>

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>Drug A</strong>, N = 83

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>Drug B</strong>, N = 88

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>p-value</strong><sup class="gt_footnote_marks">1</sup>

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

Tumor Response, n (%)

</td>

<td class="gt_row gt_center">

26 (32%)

</td>

<td class="gt_row gt_center">

28 (33%)

</td>

<td class="gt_row gt_center">

> 0.99
> 
> </td>
> 
> </tr>
> 
> <tr>
> 
> <td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">
> 
> Unknown
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 2
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 4
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> </td>
> 
> </tr>
> 
> <tr>
> 
> <td class="gt_row gt_left">
> 
> Grade, n (%)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 0.81
> 
> </td>
> 
> </tr>
> 
> <tr>
> 
> <td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">
> 
> I
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 30 (36%)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 28 (32%)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> </td>
> 
> </tr>
> 
> <tr>
> 
> <td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">
> 
> II
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 26 (31%)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 31 (35%)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> </td>
> 
> </tr>
> 
> <tr>
> 
> <td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">
> 
> III
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 27 (33%)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 29 (33%)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> </td>
> 
> </tr>
> 
> <tr>
> 
> <td class="gt_row gt_left">
> 
> Age, yrs, median (IQR)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 48 (38, 60)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 49 (43, 57)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 0.55
> 
> </td>
> 
> </tr>
> 
> </tbody>

<tfoot>

<tr class="gt_footnotes">

<td colspan="4">

<p class="gt_footnote">

<sup class="gt_footnote_marks">
<em>1</em>
</sup>

Statistical tests performed: chi-square test of independence; Wilcoxon rank-sum test
<br />

</p>

</td>

</tr>

</tfoot>

</table>

</div>

``` r

# stacked table
t <- tbl_stack(
  tbls = list(t1, t2),
  group_header = c("All", "Over 30")
)

t
```

<div id="zvnrrhngrs" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

<strong>Characteristic</strong>

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>Drug A</strong>, N = 98

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>Drug B</strong>, N = 102

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

<strong>p-value</strong><sup class="gt_footnote_marks">1</sup>

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr class="gt_group_heading_row">

<td colspan="4" class="gt_group_heading">

All

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Tumor Response, n (%)

</td>

<td class="gt_row gt_center">

28 (29%)

</td>

<td class="gt_row gt_center">

33 (34%)

</td>

<td class="gt_row gt_center">

0.64

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

Unknown

</td>

<td class="gt_row gt_center">

3

</td>

<td class="gt_row gt_center">

4

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Grade, n (%)

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

</td>

<td class="gt_row gt_center">

0.87

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

I

</td>

<td class="gt_row gt_center">

35 (36%)

</td>

<td class="gt_row gt_center">

33 (32%)

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

II

</td>

<td class="gt_row gt_center">

32 (33%)

</td>

<td class="gt_row gt_center">

36 (35%)

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

III

</td>

<td class="gt_row gt_center">

31 (32%)

</td>

<td class="gt_row gt_center">

33 (32%)

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Age, yrs, median (IQR)

</td>

<td class="gt_row gt_center">

46 (37, 59)

</td>

<td class="gt_row gt_center">

48 (39, 56)

</td>

<td class="gt_row gt_center">

0.72

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">

Unknown

</td>

<td class="gt_row gt_center">

7

</td>

<td class="gt_row gt_center">

4

</td>

<td class="gt_row gt_center">

</td>

</tr>

<tr class="gt_group_heading_row">

<td colspan="4" class="gt_group_heading">

Over 30

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Tumor Response, n (%)

</td>

<td class="gt_row gt_center">

26 (32%)

</td>

<td class="gt_row gt_center">

28 (33%)

</td>

<td class="gt_row gt_center">

> 0.99
> 
> </td>
> 
> </tr>
> 
> <tr>
> 
> <td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">
> 
> Unknown
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 2
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 4
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> </td>
> 
> </tr>
> 
> <tr>
> 
> <td class="gt_row gt_left">
> 
> Grade, n (%)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 0.81
> 
> </td>
> 
> </tr>
> 
> <tr>
> 
> <td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">
> 
> I
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 30 (36%)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 28 (32%)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> </td>
> 
> </tr>
> 
> <tr>
> 
> <td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">
> 
> II
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 26 (31%)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 31 (35%)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> </td>
> 
> </tr>
> 
> <tr>
> 
> <td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">
> 
> III
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 27 (33%)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 29 (33%)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> </td>
> 
> </tr>
> 
> <tr>
> 
> <td class="gt_row gt_left">
> 
> Age, yrs, median (IQR)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 48 (38, 60)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 49 (43, 57)
> 
> </td>
> 
> <td class="gt_row gt_center">
> 
> 0.55
> 
> </td>
> 
> </tr>
> 
> </tbody>

<tfoot>

<tr class="gt_footnotes">

<td colspan="4">

<p class="gt_footnote">

<sup class="gt_footnote_marks">
<em>1</em>
</sup>

Statistical tests performed: chi-square test of independence; Wilcoxon rank-sum test
<br />

</p>

</td>

</tr>

</tfoot>

</table>

</div>

<sup>Created on 2020-07-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
HI @JesseRop !

I am generally in favor of these kinds of consistency checks.  The issue we'd encounter implementing something like this is that `tbl_stack()` is a general function that accepts any type of {gtsummary} object (and this includes objects outside the package that follow the general gtsummary structure with class gtsummary).  Because there are may different type of objects that can be stacked, adding checks can be tricky.

For this example, I would recommend removing the Ns from the header like in the example below.  Happy Coding! 🕺 

```r
t1 <- 
  trial %>% 
  select(age, grade, trt) %>% 
  tbl_summary(by = trt, missing = "no") %>%
  add_n() %>%
  modify_header(stat_by = "**{level}**")
t2 <- 
  trial %>%
  filter(age >= 30) %>%
  select(age, grade, trt) %>% 
  tbl_summary(by = trt, missing = "no") %>%
  add_n()

tbl_stack(list(t1, t2), group_header = c("All Patients", "Over 30"))
```

![image](https://user-images.githubusercontent.com/26774684/87854355-65d5e400-c8df-11ea-9240-4db860113b12.png)
