### ISSUE TITLE
tbl_survival does not handle escape characters in variable levels 

### ISSUE THREAD

**Issue by michaelcurry1123** [ddsjoberg/gtsummary#59]
```
library(survival)
library(gtsummary)
library(dplyr)
lung2 <- mutate(lung, s2 = ifelse(sex == 1, "1\2", "2/3"))
tbl_survival(lung2, Surv(time,status)~s2, times = c(500,540))

```

If you look at the output you will see that the function does not print "1\2" but prints 1 and a special character. 

![image](https://user-images.githubusercontent.com/30420015/56046804-1551fd00-5d12-11e9-9384-ece20a49f471.png)

**Comment by ddsjoberg** [comment]
Hmmmm, I am not sure what to do about this.  I looked to see what ggplot did if you use `s2` as a stratification variable.  It prints differently by ignoring the special characters.  I am not sure what the ideal output should be?  What do you think it should look like?  I am inclined to just leave it as is?

```
library(survival)
library(gtsummary)
library(dplyr)
library(ggplot2)
lung2 <- mutate(lung, s2 = ifelse(sex == 1, "1\2", "2/3"))
f =  survfit(Surv(time,status)~s2, lung2)
tbl_survival(f, times = c(500,540))

lung2 %>%
  ggplot(aes(x = time, y = age, color = s2)) +
  geom_smooth()
```
![image](https://user-images.githubusercontent.com/26774684/56084850-a6ef6680-5e07-11e9-8a9c-6b3322624b88.png)

**Comment by ddsjoberg** [comment]
Decided to leave it as is
