### ISSUE TITLE
Issues when names of variables contain spaces

### ISSUE THREAD

**Issue by gorkang** [ddsjoberg/gtsummary#609]
If the names of variables are like `name of variable` instead of `name_of_variable`, only the levels appear in the table. See reproducible example below. 

```
library(gtsummary)
library(tidyverse)

DF = trial
  
mod1 <- lm(age ~ marker * grade, DF)
tbl_regression(mod1) %>% 
  bold_labels() %>% 
  italicize_levels()

```
![Rplot1](https://user-images.githubusercontent.com/6491790/89527054-b5a91c00-d7b6-11ea-890b-20d0bd1cbd9d.png)

```
DF = trial %>% mutate(`grade of kids` = grade)

mod2 <- lm(age ~ marker * `grade of kids`, DF)
tbl_regression(mod2) %>% 
  bold_labels() %>% 
  italicize_levels()
```

![Rplot2](https://user-images.githubusercontent.com/6491790/89527059-b772df80-d7b6-11ea-898d-3e3078d3ec56.png)

**Comment by ddsjoberg** [comment]
Hi @gorkang ! Thank you for letting us know!

We are aware there are parsing issues with non-standard names.  Parsing the terms is actually pretty difficult! BUT, @larmarange is looking into some updates will you result in more robust parsing, and will likely solve this issue of unconventional names!

I am going to go ahead and close this issue for now, but please do continue to let us know of any odd behavior you come across! 🕺

**Comment by qfazille** [comment]
I don't know if related but I get the same kind of output error when using glm model from `caret `package :

````
library(gtsummary)
library(tidyverse)
library(caret)

DF <- trial
DF$death <- as.factor(ifelse(DF$death, "yes", "no"))
DF$death <- relevel(DF$death, "no")
DF <- DF[which(!is.na(DF$age)),]

mod1 <- glm(death ~ age + stage + grade, data = DF, family = binomial())

# Works
tbl_regression(mod1) %>% 
  bold_labels() %>% 
  italicize_levels()
````

![works](https://user-images.githubusercontent.com/26872734/89995303-99f7b700-dc89-11ea-8c9e-c5896ab580fc.PNG)


````
tr <- train(
  form = death ~ age + stage + grade,
  data = DF,
  trControl = trainControl(method = "repeatedcv", number = 5, classProbs = TRUE, summaryFunction = twoClassSummary, repeats = 1),
  metric = "ROC",
  method = "glm",
  family = "binomial",
  trace = F
)
mod2 <- tr$finalModel

# Doesn't works
tbl_regression(mod2) %>% 
  bold_labels() %>% 
  italicize_levels()
````

![dontwork](https://user-images.githubusercontent.com/26872734/89995328-9f550180-dc89-11ea-9531-5d7346b9aa11.PNG)

**Comment by ddsjoberg** [comment]
The issue with caret is a bit different. gtsummary peaks into the `model.frame()` results to get variable names from the data that it them matches to the model terms.  But caret pre-processes the data, and creates the dummy variables for the categorical terms in the model.

```r
![image](https://user-images.githubusercontent.com/26774684/90018752-6b72df80-dc7b-11ea-8dc5-c8b6f0147162.png)
```

When we match the column names to the terms, we find the exact matches rather than being able to match the grade terms together etc.

**Comment by ddsjoberg** [comment]
@gorkang FYI, we just completed a big overhaul to the internals of `tbl_regression()` that should address variables with non-standard names.  Check it out!

```r
remotes::install_github("ddsjoberg/gtsummary")

DF = trial %>% mutate(`grade of kids` = grade)

mod2 <- lm(age ~ marker * `grade of kids`, DF)
tbl_regression(mod2) %>% 
  bold_labels() %>% 
  italicize_levels()
```

![image](https://user-images.githubusercontent.com/26774684/95226092-87ea4e80-07ca-11eb-91c1-279f941286af.png)

**Comment by gorkang** [comment]
Thanks for the heads up! Works great so far.
