### ISSUE TITLE
Integer values are compiled as categorical values.

### ISSUE THREAD

**Issue by juseer** [ddsjoberg/gtsummary#612]
Please do not use this form to ask a question, or ask for assistance. Instead, ask on <https://stackoverflow.com/> using the gtsummary tag.

If you have found a bug, please briefly describe your problem and what output you expect.

INCLUDE a *minimal* reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem.
Trying to compile a statistical table from a simple data frame `foo_df`. Please see the code appended. However, the integer values were treated as categorical. ![Screen Shot 2020-08-07 at 11 27 37 AM](https://user-images.githubusercontent.com/63944128/89667557-f6ca2a80-d8a1-11ea-801c-b3a10d9de1eb.png)

```r
# insert reprex here
> foo_df
# A tibble: 8 x 6
  id     `S-1` `S-2` `S-3` `S-4` `S-5`
  <chr>  <int> <int> <int> <int> <int>
1 2020pl   222   241   280   237   138
2 2020pl   209   245   260   242   144
3 2020pl   213   241   279   242   136
4 2020pl   217   235   271   239   141
5 2020pl   209   243   284   242   136
6 2020pl   217   246   286   241   140
7 2020pl   219   239   287   249   146
8 2020pl   217   217   266   240   145



tbl_summary(by = id, 
              missing = "no",
              digits = list(all_continuous() ~ c(0, 0, 1, 1, 3)),
              statistic = list(all_continuous() ~ 
                                 "{min} ~ {max} \n {mean}±{sd} [{cv}]")) %>% 
  add_stat(
    fns = everything() ~ cal_cv,  # compute plate to plate cv using cal_cv()
    fmt_fun = NULL, # fn returns and chr, so no formatting function needed
    header = "**%CV**",       # column header
    footnote = "Coefficient of variation") %>%	
  modify_footnote(starts_with("stat_") ~ "Range and mean±SD [cv]")  
stats_summary_table
```

**Comment by ddsjoberg** [comment]
hello @juseer !

the `tbl_summary()` function does its best to assess how to summarize the data. If a column only has a few unique values, then it assumes the best summary is as a categorical variable. If you'd like to change the default type from categorical to continuous, use the `type=` arguments.

Happy programming 🕺

**Comment by juseer** [comment]
Thank you.
`type = list(all_numeric() ~ "continuous")` resolves the issue.
