### ISSUE TITLE
Create a {learnr} tutorial for using {gtsummary}

### ISSUE THREAD

**Issue by karissawhiting** [ddsjoberg/gtsummary#621]
I think it would be really cool to leverage the {learnr} package to make an interactive gtsummary tutorial, sort of like an enhanced vignette.

I played around with the package and it seems like it would be fairly straightforward to make something simple. I'm not sure the best way to host/share it. It looks like it could [live in the package itself as another type of vignette](https://rstudio.github.io/learnr/publishing.html#r-package). I'm looking for examples of other packages that use this and will post if I find. 

If we can get something up and running in the next two weeks it might be nice to share at R/Medicine and tailor the material to what we decide to discuss there.

**Comment by michaelcurry1123** [comment]
@karissawhiting  hey if you wanted help or want someone to bounce ideas off of for this I am happy to help!

**Comment by ddsjoberg** [comment]
@karissawhiting @michaelcurry1123 FYI i started a tutorial in preparation for the Kasier presentation/workshop.
https://github.com/ddsjoberg/gtsummary/tree/learnr

If you have any ideas about how to make it extra amazing, please share! At the moment, I am modelling if off the vignettes (and copying much of the code).

**Comment by ddsjoberg** [comment]
this has been on the list for a while and I don't think i'll ever get to it 🤷🏼 if anyone wants to build it, please feel free!
