### ISSUE TITLE
Updates for `add_n()` and `add_nevent()` for regression tables.

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#626]
Add arguments to optionally add the N or the number of events to the categorical variable level (example taken from the table gallery)

![image](https://user-images.githubusercontent.com/26774684/90637325-d8492500-e1f9-11ea-83ec-ca5f8bc5ea69.png)

**Comment by larmarange** [comment]
Should this computation be considered in broom.helpers? Clearly, a method will be required as it could differ according to the type of model

**Comment by larmarange** [comment]
As I can see, there is some challenges in computing it but I guess it will be possible to take advantages of `broom.helpers` mechanism.

To be discussed, what should be the value of `n`:

- for continuous variables, the number of observations
- for categorical variables (including reference row) the number of observations at that level (only sum and treatment contrasts)
- for interaction term: the number of observations concerned by the interaction (depends if it includes categorical variables or not)

When weights are used, `n` should take into account these weights. Should we also return `n_unweighted`?

Maybe certain specific cases will require discussion:

- for a Cox model with several rows per individual, should `n` be equal to the number of rows (easiest) or the number of individuals (more complex)?
- for mix models / GEE models with repeated observations, same question.

In addition, I guess we should also compute n_events for logistic models, poisson models and Cox models.

**Comment by larmarange** [comment]
For `n_events`, should it be computed separately per categorical term?

**Comment by larmarange** [comment]
Note: maybe something to check here https://github.com/ddsjoberg/gtsummary/blob/6a7ea4751eac5889bf9deaf78fdaa5324f177cbb/R/add_nevent.R#L100

In a logistic model, you can provide a factor with 3 or 4 levels. All except the first one will be considered as an event. Here, you check only last terms.

Here, the computed number of events seems to be only the total number of events, not the number of events per modality.

**Comment by ddsjoberg** [comment]
1. If the Ns are something that you want to use for the GGally, we should discuss the best strategy.  If not, then I think it's easiest to keep in gtsummary.  Within gtsummary, this is a simple `tbl_summary()` with counts, and merging the `.$table_body`....perhaps we could implement in broom.helpers using `tbl_summary()`.
1. I am in favor of merely reporting Ns as the number of observations. There are so many types of models, and the sought after Ns can be so different (even for the exact same model type).
1. Definitely `add_nevent()` could use more work.

**Comment by larmarange** [comment]
Not a real need for `ggcoef_model`

However, in some specific cases, more for personal treatment, it could be useful to identify the number of observations and events for interaction terms, taking into account the type of contrasts, the different type of syntax (e.g. cbind syntax for logistics models) etc.

I started to explore it as it is a good challenge and a good opportunity to better understand models objects.

Here a first very preliminary draft for glm objects. https://github.com/larmarange/broom.helpers/pull/64

So far, I'm thinking that it could be something to explore but not to implement in the next release of broom.helpers, in order to get more time for play testing

**Comment by larmarange** [comment]
Note: in https://github.com/larmarange/broom.helpers/pull/64, you can see in the examples some complex model syntax and the obtained results

**Comment by ddsjoberg** [comment]
Merged in https://github.com/ddsjoberg/gtsummary/pull/762
