### ISSUE TITLE
Standard error instead of CI in tbl_regression?

### ISSUE THREAD

**Issue by alexis-catherine** [ddsjoberg/gtsummary#637]
I get the sense from poking around in documentation there might be a way to do this manually, but I'd like to be able to swap the CI column in the tbl_regression for a standard error column. The journals in my field tend to expect SE instead of CI, and it would be amazing to be able to set something like add_CI = F and add_SE = T.

**Comment by ddsjoberg** [comment]
Hi @alexis-catherine !  What is one of the top journals in your field that prefers the tables this way?  We can implement a theme for the journal and format all the output following their guidelines!  I haven't implemented this yet, but it's been something in the back of my mind for months now.

We're about to do a big refactoring of the internals and I'll implement this for you 🕺

**Comment by ddsjoberg** [comment]
HI @alexis-catherine , 

FYI, I made the update that can help you make the tables you need.  There is a code example below. I know the code isn't the easiest to follow in its current form. But if you provide a journal's reporting guidelines, we can wrap this up in a theme to can it easily accessible. 

The update is in this pull request and will make it's way to CRAN in the next release
https://github.com/ddsjoberg/gtsummary/pull/606

```r
  glm(response ~ age + grade, trial, family = binomial) %>%
  tbl_regression(exponentiate = TRUE) %>%
  # add standard error, test statistic
  modify_header(
    statistic = "**Statistic**",
    std.error = "**SE**"
  ) %>%
  # hide confidence interval
  modify_table_header(
    column = "ci", 
    hide = TRUE, 
    missing_emdash = NA_character_,
    footnote_abbrev = NA_character_
  )
```

![image](https://user-images.githubusercontent.com/26774684/92049065-560f4380-ed57-11ea-91b1-1eea20392298.png)

Happy Coding! 👯

**Comment by ddsjoberg** [comment]
Hi @alexis-catherine !

FYI, in the dev version of the package, you can now very easily choose to report the SE instead of the CI.

```r
library(gtsummary)

# set columns to display in tbl_regression
list("tbl_regression-chr:tidy_columns" = c("estimate", "std.error", "p.value")) %>%
  set_gtsummary_theme()

glm(response ~ age + grade, trial, family = binomial) %>%
  tbl_regression(exponentiate = TRUE)
```
![image](https://user-images.githubusercontent.com/26774684/95414597-3e018580-08fc-11eb-9449-6e8f72f4ff77.png)

We can implement a theme for the journal that requests output in this format. See others here: http://www.danieldsjoberg.com/gtsummary/reference/theme_gtsummary.html
