### ISSUE TITLE
tbl_survival to handle cuminc from cmprsk package

### ISSUE THREAD

**Issue by michaelcurry1123** [ddsjoberg/gtsummary#64]
This will allow people to get cumulative incidence for competing risks for each event.

**Comment by ddsjoberg** [comment]
I think that is a very good idea!  I can make `tbl_survival` a generic to accept survfit objects and cumin objects.

**Comment by ddsjoberg** [comment]
I'll update `tbl_survival()` to be an S3 generic, and create `tbl_survival.survfit()`.  @michaelcurry1123  would you be interested in writing `tbl_survival.cuminc()`?

We'll also need to update `inline_text.tbl_survival()` or ensure the output from `tbl_survival.survfit()` and `tbl_survival.cuminc()` are identical so the current version of `inline_text.tbl_survival()` will still work properly.

**Comment by michaelcurry1123** [comment]
@ddsjoberg  Yes I am interested in that. I know `tidy::broom` does not support cuminc objects but I do have a function that might help.

**Comment by ddsjoberg** [comment]
Nice!  I created this branch for the update:
https://github.com/ddsjoberg/gtsummary/tree/tbl_survival-cuminc

I made the `tbl_survival` S3 generic.

**Comment by ddsjoberg** [comment]
Rather than update that branch I mentioned above, can you fork and make the update on your fork?

**Comment by ddsjoberg** [comment]
for now, let's only support a single stratification level
