### ISSUE TITLE
Is gtsummary compatible with tidymodels and workflows?

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#647]
@zabore have you ever tried?

**Comment by zabore** [comment]
I haven't!

**Comment by ddsjoberg** [comment]
OK!  I'll test them out....sometime!

**Comment by zabore** [comment]
I want to play around with workflows too so when I do, I will test with gtsummary as well.

**Comment by ddsjoberg** [comment]
hey hey @zabore ! I made a small update that I think handles tidymodels (here https://github.com/ddsjoberg/gtsummary/pull/892). Do you have time to take a look? I don't know much about tidymodels 😨

**Comment by zabore** [comment]
Yes, I can review it!
