### ISSUE TITLE
`style_ratio()` rounding bug near one

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#651]
``` r
library(gtsummary)

c(0.99, 1.1) %>%
  style_ratio()
#> [1] "1.0"  "1.10"
```

<sup>Created on 2020-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
@zabore could you review this one as well? It's almost the same as the last PR you reviewed.

**Comment by zabore** [comment]
Yes, will do!
