### ISSUE TITLE
print gtsummary table

### ISSUE THREAD

**Issue by juseer** [ddsjoberg/gtsummary#656]
Please do not use this form to ask a question, or ask for assistance. Instead, ask on <https://stackoverflow.com/> using the gtsummary tag.

If you have found a bug, please briefly describe your problem and what output you expect.

INCLUDE a *minimal* reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

When gtsummary table is not on the first level of if statement, it cannot be knitted in Rmarkdown. Per this blog (https://yihui.org/en/2017/06/top-level-r-expressions/), user should use print() to knit it. However, print gtsummary table will print code.
![Screen Shot 2020-09-16 at 7 44 20 PM](https://user-images.githubusercontent.com/63944128/93406343-08193600-f855-11ea-9cd3-6bc7e4e81b46.png)

```r
if (var == TRUE) {
p <- ggplot (data...)
print(p)
table <- tbl_summary(dat ...)
print(table)

} else {warning("...")}
```

**Comment by ddsjoberg** [comment]
The solution for this is the same for any kind of gt table, including gtsummary tables.  You'll need to include `results='asis'` in the markdown chunk header

````r
```{r print_example, results = 'asis'}
for (i in 1) {
  print(gt::gt(mtcars))
}
```
````

I should probably add a note about this in the R markdown vignette!   I'll keep this open until it's added.  In the meantime, please do let me know if you have any other questions! 🕺
