### ISSUE TITLE
Check magrittr 2.0 compatibility 

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#661]
magrittr 2.0 will be released in Oct https://www.tidyverse.org/blog/2020/08/magrittr-2-0/

We need to ensure that gtsummary is compatible with both v2.0 and  <v2.0.

1. Install magrittr 2.0
2. Run R Cmd Checks, review for any errors, warnings, or notes.
3. Resolve any errors, warnings, or notes and ensure compatibility with both v2.0 and  <v2.0.

**Comment by ddsjoberg** [comment]
Does anyone want to do this check? @michaelcurry1123 @karissawhiting @zabore ?

**Comment by michaelcurry1123** [comment]
@ddsjoberg I can

**Comment by michaelcurry1123** [comment]
@ddsjoberg here are the warnings and notes I get:

> checking R/sysdata.rda ... OK
>    WARNING
>   'qpdf' is needed for checks on size reduction of PDFs
> 
> > checking for future file timestamps ... NOTE
>   unable to verify current time
> 
> 0 errors v | 1 warning x | 1 note x
> Error: R CMD check found WARNINGs
> Execution halted
> 
> Exited with status 1.
>

**Comment by ddsjoberg** [comment]
OK! Looks like no issues! Thank you for checking!
