### ISSUE TITLE
select() vs select_()

### ISSUE THREAD

**Issue by Marsus1972** [ddsjoberg/gtsummary#665]
I get this message after trying to run the tbl_summary function. 

Error in UseMethod("select_") : 
  no applicable method for 'select_' applied to an object of class "function"
In addition: Warning message:
`select_()` is deprecated as of dplyr 0.7.0.
Please use `select()` instead.

How do I solve this? 

Many thanks in advance

**Comment by ddsjoberg** [comment]
@Marsus1972 thank you for reporting a potential bug. Please provide a reprex of the issue you're experiencing. https://www.tidyverse.org/help/

**Comment by ddsjoberg** [comment]
@Marsus1972 I suspect there is syntax error in your code. BUT, the resulting error is not informative.  I am going to ahead and close this issue.  Please do open it again once you've prepared a reproducible example, and I can look into improving the error messaging.
