### ISSUE TITLE
tbl_svysummary issue?

### ISSUE THREAD

**Issue by angelgar** [ddsjoberg/gtsummary#667]
Hi,

Thank you so much for all the awesome work you've all have put into this!

The tbl_svysummary function outputs the weighted N's on the header of the table, even if you ask for the unweighted N's. This is a little bit confusing and might be better if the header follows the same statistics reported elsewhere. 

Angel 

I.e. header of:

```r
my_data %>%
tbl_svysummary(by = cat, 
            statistic = list(all_categorical() ~ "{n_unweighted} ({p}%)"),
            digits = all_categorical() ~ c(0,1)) %>% 
  add_overall() %>% add_p()
```

is the same as : 

```r
my_data %>%
tbl_svysummary(by = cat, 
            statistic = list(all_categorical() ~ "{n} ({p}%)"),
            digits = all_categorical() ~ c(0,1)) %>% 
  add_overall() %>% add_p()
```

**Comment by ddsjoberg** [comment]
Hi @angelgar !

Thanks for the kind note and posting!

It's an interesting thought, and I need to think on it more.  My first reaction is that it is v difficult to guess a users intention when using `"{n_unweighted}"`, and I would be nervous to change default table behavior based on our guess. I don't use survey data, which makes me more reluctant to make changes as I am not steeped in the typical usage. I think simply having default headers without changing the behaviour based on other user input would be more clear to all users?  What do you think?  Also, with `tbl_svysummary()`'s flexible input for the stats to display, it introduces an additional hurdle for intuiting users' intent?
In the meantime, here's a pretty straightforward way to update the header!

``` r
library(gtsummary)
data(api, package = "survey")

survey::svydesign(id = ~dnum, weights = ~pw, data = apiclus1, fpc = ~fpc) %>%
  tbl_svysummary(
    include = c(cname, both),
    by = both,
    statistic = all_categorical() ~ "{n_unweighted} ({p}%)"
  ) %>%
  modify_header(stat_by = "**{level}** N = {n_unweighted}") %>%
  as_kable() # convert to kable, so table renders in reprex
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>No</strong> N = 50</th>
<th style="text-align: left;"><strong>Yes</strong> N = 133</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">cname</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Alameda</td>
<td style="text-align: left;">2 (4.0%)</td>
<td style="text-align: left;">9 (6.8%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fresno</td>
<td style="text-align: left;">0 (0%)</td>
<td style="text-align: left;">4 (3.0%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kern</td>
<td style="text-align: left;">1 (2.0%)</td>
<td style="text-align: left;">1 (0.8%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Los Angeles</td>
<td style="text-align: left;">4 (8.0%)</td>
<td style="text-align: left;">11 (8.3%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mendocino</td>
<td style="text-align: left;">4 (8.0%)</td>
<td style="text-align: left;">0 (0%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Merced</td>
<td style="text-align: left;">1 (2.0%)</td>
<td style="text-align: left;">3 (2.3%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Orange</td>
<td style="text-align: left;">3 (6.0%)</td>
<td style="text-align: left;">13 (9.8%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Plumas</td>
<td style="text-align: left;">5 (10%)</td>
<td style="text-align: left;">4 (3.0%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">San Diego</td>
<td style="text-align: left;">15 (30%)</td>
<td style="text-align: left;">40 (30%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">San Joaquin</td>
<td style="text-align: left;">11 (22%)</td>
<td style="text-align: left;">26 (20%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Santa Clara</td>
<td style="text-align: left;">4 (8.0%)</td>
<td style="text-align: left;">22 (17%)</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-10-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
Hi @angelgar !  Any additional thoughts here?  The more I am thinking on it, I don't think the default should header should be modified.  But I do think we should make it easier for users to add unweighted Ns to the table header.  

Feel free to re-open this issue to continue the conversation!
