### ISSUE TITLE
Give `modify_header()` access to unweighted Ns after `tbl_svysummary()`

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#668]
When using `modify_header()` after `tbl_svysummary(by=)`, users can access the weighted and unweighted Ns using `modify_header(stat_by=)`.  But when there is no `by=` argument, the unweighted statistics are not available

cc @angelgar

``` r
library(gtsummary)
data(api, package = "survey")

survey::svydesign(id = ~dnum, weights = ~pw, data = apiclus1, fpc = ~fpc) %>%
  tbl_svysummary(
    include = c(cname, both),
    by = both,
    statistic = all_categorical() ~ "{n_unweighted} ({p}%)"
  ) %>%
  modify_header(stat_by = "**{level}** N = {n_unweighted}") %>%
  as_kable() # convert to kable, so table renders in reprex
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>No</strong> N = 50</th>
<th style="text-align: left;"><strong>Yes</strong> N = 133</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">cname</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Alameda</td>
<td style="text-align: left;">2 (4.0%)</td>
<td style="text-align: left;">9 (6.8%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fresno</td>
<td style="text-align: left;">0 (0%)</td>
<td style="text-align: left;">4 (3.0%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kern</td>
<td style="text-align: left;">1 (2.0%)</td>
<td style="text-align: left;">1 (0.8%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Los Angeles</td>
<td style="text-align: left;">4 (8.0%)</td>
<td style="text-align: left;">11 (8.3%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mendocino</td>
<td style="text-align: left;">4 (8.0%)</td>
<td style="text-align: left;">0 (0%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Merced</td>
<td style="text-align: left;">1 (2.0%)</td>
<td style="text-align: left;">3 (2.3%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Orange</td>
<td style="text-align: left;">3 (6.0%)</td>
<td style="text-align: left;">13 (9.8%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Plumas</td>
<td style="text-align: left;">5 (10%)</td>
<td style="text-align: left;">4 (3.0%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">San Diego</td>
<td style="text-align: left;">15 (30%)</td>
<td style="text-align: left;">40 (30%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">San Joaquin</td>
<td style="text-align: left;">11 (22%)</td>
<td style="text-align: left;">26 (20%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Santa Clara</td>
<td style="text-align: left;">4 (8.0%)</td>
<td style="text-align: left;">22 (17%)</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-10-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by angelgar** [comment]
Amazing! thank you :)
