### ISSUE TITLE
Support for indenting blocks of variables

### ISSUE THREAD

**Issue by aghaynes** [ddsjoberg/gtsummary#669]
It's often useful to group similar sets of variables together under headings (e.g. demographics might contain age, sex, ..., lab values would contain blood values etc). 

Is it possible to do this with gtsummary so that something like the following is returned? 

(I know that as_tibble strips the leading spaces away, but it was the easiest way to demostrate what I mean)

```
> dat %>% 
+   select(AgeInYears, Gender, BodyMassIndex, CreatininePreOpMol, HemoglobinPreOp,
+          Lactate, Platelet) %>%
+   tbl_summary(missing_text = "Missing", missing = "no") %>%
+   add_blocks(list(Demographics = c("AgeInYears", "Gender", "BodyMassIndex"), # how it might be defined
+                   "Lab values" = c("CreatininePreOpMol", "HemoglobinPreOp",
+                                    "Lactate", "Platelet"))) %>%
+   as_tibble()
# A tibble: 11 x 2
  `**Characteristic**` `**N = 120**`    
  <chr>                <chr>            
Demographics
  AgeInYears           56 (47, 64)      
  Gender               NA               
    Female             24 (20%)         
    Male               96 (80%)         
  BodyMassIndex        24.9 (21.9, 27.9)
Lab values
  CreatininePreOpMol   138 (99, 189)    
  HemoglobinPreOp      12 (11, 14)      
  Lactate              1.10 (0.95, 1.80)
  Platelet             176 (136, 230)
```

**Comment by ddsjoberg** [comment]
Hi @aghaynes ! Thanks for the suggestion!

Would this solution work for you?

```r
library(gtsummary)

tt <-
  trial %>%
  select(trt, response, age) %>%
  tbl_summary(by = trt, missing = "no") %>%
  italicize_labels()

# stacking two tbl_summary objects with header between
tbl_stack(list(tt, tt), group_header = c("Demographics", "Lab Values")) 
```

![image](https://user-images.githubusercontent.com/26774684/95224055-422c8680-07c8-11eb-9f67-9d18d2eb9fc5.png)

**Comment by aghaynes** [comment]
Hi! Thanks for thinking about this!

I think it'd be clearer with indents though (that's certainly the norm)... I suppose a work around might be to adapt the labels? (although then the factor labels would need adapting too...)

**Comment by ddsjoberg** [comment]
One of the great things about the gtsummary package, is that you can use the many many many formatting functions in gt to modify your table.  A gtsummary table is essentially a nice print of the internal data frame `x$table_body`, and you can add additional gt commands to meet your needs (http://www.danieldsjoberg.com/gtsummary/articles/tbl_summary.html#advanced-customization).  The example above can be further customized (including adding indentation) using the outline below.

```r
library(gtsummary)
library(gt)

tt <-
  trial %>%
  select(trt, response, age) %>%
  tbl_summary(by = trt, missing = "no") 

# stacking two tbl_summary objects with header between
tbl_stack(list(tt, tt), group_header = c("Demographics", "Lab Values")) %>%
  # adding additional gt commands to indent
    <gt functions for indenting!>

```

**Comment by ddsjoberg** [comment]
Hey hey @aghaynes ! It's been a while, for sure! 

I wanted to let you know that indenting rows has been migrated into gtsummary, so you do not need to convert your gtsummary table to gt and add indentation instructions from there. This is in the dev version being released in a few days.

```r
library(gtsummary)

tt <-
  trial %>%
  select(trt, response, age) %>%
  tbl_summary(by = trt, missing = "no") 

# stacking two tbl_summary objects with header between
tbl_stack(list(tt, tt), group_header = c("Demographics", "Lab Values")) %>%
  # pass indentation instructions
  modify_table_styling(
    columns = label,
    text_format = "indent",
    rows = !is.na(variable)
  )
```
![image](https://user-images.githubusercontent.com/26774684/114398057-5a150680-9b6d-11eb-8258-8b528cafa258.png)

**Comment by aghaynes** [comment]
Thats cool! Thanks @ddsjoberg! I will be trying it out soon i'm sure!
