### ISSUE TITLE
row proportions in tbl_summary() or several variables for `rows` in tbl_cross()

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#670]
Hi @ddsjoberg 

today, during a training session, I had the following problems: how to display row proportions when using `tbl_summary` with a `by` variable? It's not possible yet and I understand it could be difficult to implement due to the nature of tbl_summary()

An alternative could be to use tbl_cross(). However, so far, it is not allowed to define several variables for `row` parameter. Would it be possible to think about allowing such thing?

Best regards

**Comment by ddsjoberg** [comment]
Hi @larmarange !

We have the `tbl_summary(percent=)` argument.  Would that solve your problem?

``` r
library(gtsummary)

trial %>%
  select(trt, grade, response) %>%
  tbl_summary(
    by = trt, 
    percent = "row"
  ) %>%
  as_kable() # convert to kable so table renders properly in reprex on github
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>Drug A</strong>, N = 98</th>
<th style="text-align: left;"><strong>Drug B</strong>, N = 102</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grade</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">I</td>
<td style="text-align: left;">35 (51%)</td>
<td style="text-align: left;">33 (49%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">II</td>
<td style="text-align: left;">32 (47%)</td>
<td style="text-align: left;">36 (53%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">III</td>
<td style="text-align: left;">31 (48%)</td>
<td style="text-align: left;">33 (52%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tumor Response</td>
<td style="text-align: left;">28 (46%)</td>
<td style="text-align: left;">33 (54%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">4</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
I'm stupid. It was in front of me.

Thanks
