### ISSUE TITLE
Printing table in .md

### ISSUE THREAD

**Issue by ctlamb** [ddsjoberg/gtsummary#671]
I am using gt() to print nice tables for my GitHub repository README.md. On my .Rmd the tables print nice in Rstudio, but when I convert to .md and upload to GitHub I end up with a long string of HTML before the table. I'm sure it's a simple fix but I haven't been able to troubleshoot. Thanks
![Screen Shot 2020-10-06 at 11 16 35 AM](https://user-images.githubusercontent.com/34384805/95237936-0ee8f800-07c6-11eb-9876-3fa7d3244ebf.png)
![Screen Shot 2020-10-06 at 11 16 41 AM](https://user-images.githubusercontent.com/34384805/95237946-13151580-07c6-11eb-8ffa-c714883626fe.png)

**Comment by ddsjoberg** [comment]
Hi @ctlamb ! I think you meant to post this on the gt repository? https://github.com/rstudio/gt
