### ISSUE TITLE
Tidier for `ic_sp()` models?

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#672]
Q for @zabore : Is the tidier you wrote for `icenReg::ic_sp()` models pretty general for that model type? If so, we can add that tidier to gtsummary (http://www.danieldsjoberg.com/gtsummary/dev/reference/custom_tidiers.html), then implement a method function `tbl_regression.ic_sp()` that would call this tidier by default....then your models would just work (with the limitations noted above)

**Comment by zabore** [comment]
Yes it's pretty general already, but I will clean it up some and add it!

**Comment by ddsjoberg** [comment]
Great! Add the new tidier to `custom_tidiers.R` and the new `tbl_regression()` method to `tbl_regression_methods.R`

**Comment by ddsjoberg** [comment]
hey hey! if this is a model you use and want to add the tidier to the pkg let me know!

**Comment by zabore** [comment]
I completely forgot about this, sorry! If I get time I may still add this. Thanks!
