### ISSUE TITLE
Allowing add_overall to include missing by group 

### ISSUE THREAD

**Issue by CarolineXGao** [ddsjoberg/gtsummary#676]
The add_overall seems to only include data of non-missing "by" group.  Is it possible to allow users to choose whether to include total population stats or population stats with non-missing "by" group? 

Many thanks 

Caroline

**Comment by ddsjoberg** [comment]
Hi @CarolineXGao ! Thank you for the note.

The number missing observations is a variable-specific statistic and is often different for every variable in the table.  The headers are there to show information for the entire dataset.

Using the `modify_header()` function you can definitely add any N you wish to the header to fit your situation.

**Comment by ddsjoberg** [comment]
I am going to go ahead and close this issue. If you'd like to continue the conversation, please feel free to re-open!
