### ISSUE TITLE
Adding a no_reference_row option to `tbl_regression()`

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#678]
Recently, a `no_reference_row` has been added to `broom.helpers::tidy_add_reference_rows()`, allowing to not add a reference row to categorical variables (including those with 3 modalities or more). It does not impact the computation of a header row.

It is not crucial but could be an option to add to `tbl_regression()`

**Comment by ddsjoberg** [comment]
Nice!

I see two primary avenues to add this functionality (I am just adding my raw thoughts here...need to think on it more.)

1. Add the `no_reference_row` argument to `tbl_regression()` and `tbl_uvregression()`.
    - I don't think many users will utilize the argument? I want to keep the number of arguments to as few as possible. When I see a new function, if there are too many args, it can be overwhelming.

1. Add a new function that strips the reference row: `tbl_regression() %>% remove_reference_row(<list variables>)`
    - New functions are often less discoverable by users.  
    - This would fit with another function I have been thinking about for `tbl_summary()` that would remove the the header row for a categorical variable.
    - Maybe there could be a single function that removes types of rows `remove_row(variable = trt, type = c("reference", "header"))`

**Comment by larmarange** [comment]
I see your point of view.

Maybe the second option is easier to follow and much more inline with the philosophy of gtsummary.
