### ISSUE TITLE
Compared with non-parametric test, but variables are normally distributed

### ISSUE THREAD

**Issue by j-tamad** [ddsjoberg/gtsummary#693]
Please do not use this form to ask a question, or ask for assistance. Instead, ask on <https://stackoverflow.com/> using the gtsummary tag.

If you have found a bug, please briefly describe your problem and what output you expect.

INCLUDE a *minimal* reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem.
I tested variables for normality using the Shapiro test and they were all normal (non significant P) but the tables were generalted with non-parametric tests. How does the software determine normality? Thanks. It's a large private dataset in .sav, I can't do a reprex
```r
# insert reprex here
```

**Comment by larmarange** [comment]
Because, by default, `add_p()` use non-parametric tests. If you want another type of tests, you have to specify it manually. Please refer to the relevant documentation : http://www.danieldsjoberg.com/gtsummary/reference/add_p.tbl_summary.html
