### ISSUE TITLE
Scientific Notation for regression outputs 

### ISSUE THREAD

**Issue by Uriahf** [ddsjoberg/gtsummary#698]
Hi! Great package first of all!

I wonder if there's a possibility to add an option for a scientific e notation for regression outputs, sometimes I get really small coefficients and alot of "0.00" do not seem to be very informative nor aesthetic. 

Thanks!

Uriah

**Comment by ddsjoberg** [comment]
Hello, 

You can use the `tbl_regression(estimate_fun=)` argument to change the formatting function.  Example below:

``` r
library(gtsummary)

# update the estimate formatting function to sci notation
lm(marker ~ age, trial) %>%
  tbl_regression(estimate_fun = function(x) format(x, digits = 2, scientific = TRUE)) %>%
  as_kable() # convert to kable to display on github
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>Beta</strong></th>
<th style="text-align: left;"><strong>95% CI</strong></th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: left;">-2e-04</td>
<td style="text-align: left;">-9.1e-03, 8.7e-03</td>
<td style="text-align: left;">&gt;0.9</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
Does this answer your question @Uriahf ?

**Comment by Uriahf** [comment]
Yes! That's exactly what I needed, thanks!
