### ISSUE TITLE
Choose order of "by=" variable categories

### ISSUE THREAD

**Issue by anaavu** [ddsjoberg/gtsummary#700]
This is a feature request for how by= category variables are ordered in the header. Say I have a variable Height, whose values I group into three categories Tall, Short, Medium. If I create a gtsummary tbl_summary with Height in the by parameter, in the heading, Tall, Short and Medium will be ordered alphabetically (Medium, Short, Tall). 
This isn't totally intuitive for the reader. Worst case, I can add to the category names "1-Short", "2-Medium", "3-Tall". Instead, it would be awesome to have the option to sort these the way the writer sees fit. (e.g. tbl_summary(by=(height, sort=list(short, medium, tall))) )
Please see screenshot below
![image](https://user-images.githubusercontent.com/38015110/100130097-2a23cb80-2e37-11eb-9219-fb622e68d408.png)

**Comment by ddsjoberg** [comment]
Hello @anaavu !

One of the nice things about gtsummary is that the first argument is the data frame, so you can easily make modifications just prior to piping the data frame to `tbl_summary()`.

In your case, the {forcats} package has so many functions that can change the ordering of a variable.  One that I use often is `fct_rev()`, which reverses the order. In this case, you'll want to use `fct_relevel()` to manually change the ordering.

``` r
library(gtsummary)
library(tidyverse)

trial %>%
  select(grade, age) %>%
  mutate(grade = factor(grade) %>% fct_relevel(c("III", "II", "I"))) %>%
  tbl_summary(by = grade) %>%
  as_kable() # exporting as kable so table renders in github
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>III</strong>, N = 64</th>
<th style="text-align: left;"><strong>II</strong>, N = 68</th>
<th style="text-align: left;"><strong>I</strong>, N = 68</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: left;">47 (38, 58)</td>
<td style="text-align: left;">48 (37, 57)</td>
<td style="text-align: left;">47 (37, 56)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">2</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-11-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
Ooops, sorry, didn't mean to close the issue. Please do let me know if this solves your problem

**Comment by anaavu** [comment]
Oh my gosh, good point, I didn't think about this! Thank you!!

**Comment by anaavu** [comment]
Your package is perfection, by the way.
