### ISSUE TITLE
add support for gt captions / bookdown crossrefs

### ISSUE THREAD

**Issue by jjallaire** [ddsjoberg/gtsummary#701]
The gt package now supports adding captions to tables: https://github.com/rstudio/gt/pull/689

This means that gt tables can be cross-referenced from bookdown. It would be great if gtsummary exposed the `caption` as well.

**Comment by ddsjoberg** [comment]
That is fantastic!  I'll add it before the next release.  Thanks for letting me know.

Note to self: Likely easiest to add `gtsummary::as_gt(...)` argument and pass the dots to `gt::gt(...)`

**Comment by ddsjoberg** [comment]
I will close this issue after gt makes their next release, and will update the `tbl_summary()` vignette to include an example using captions.

**Comment by ddsjoberg** [comment]
Thinking out loud: Should I add an `add_caption()` function that will add the caption to output formats that support captions?

Pros:
1. Would have consistent syntax for adding captions regardless if the user exports the gtsummary tables with `as_gt()`, or `as_kable()`, `as_flex_table()`, `as_hux_table()`, etc..
2. I don't think most users know about converting gtsummary objects to gt with `as_gt()`. A new function may make adding table captions for accessible.

Cons:
1. Export types that don't support captions (e.g. `as_tibble()`) will silently ignore the captions.....I don't think this is a big deal. Other attributes, such as spanning headers, are ignored when exported to an unsupported type.

**Comment by jjallaire** [comment]
Yes, I strongly agree w/ the idea of `add_caption()` (makes the feature much easier to learn and use).

**Comment by ddsjoberg** [comment]
Thank you @jjallaire for posting the issue and the feedback. 👩‍💻 

Merged pull request with new function `modify_caption()`.  The `modify_*()` prefix fit well with other similar functions `modify_header()`, `modify_footnote()`, etc..

Help file on pkgdown dev site here:
http://www.danieldsjoberg.com/gtsummary/dev/reference/modify.html

Will again keep this issue open until the next gt release and will add an example to a vignette.

**Comment by jjallaire** [comment]
Okay, sounds great!
