### ISSUE TITLE
tbl_svysummary: Missing levels in `by=` result in changed p-value?

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#702]
Hey @larmarange ! I hope you're well!

I was adding more unit tests for `tbl_svysummary()` and came across something curious.  When the variable specified in `tbl_svysummary(by=)` has missing values, they are deleted with this line of code: `data <- data[!is.na(data$variables[[by]]), ]` and we print a note mentioning the dropped observations.

But when we run `survey::svychisq(..., statistic = "F")` on a dataset with missing values, we get a different answer than when we use the smaller dataset with missing obs removed.  Example below.  Is this behavior ok?

``` r
library(tidyverse)

strial <- survey::svydesign(data = gtsummary::trial, ids = ~ 1, weights = ~1)
strial_subset <- strial[!is.na(strial$variables[["response"]]), ]

p1 <- survey::svychisq(~trt + response, strial, statistic = "F")$p.value %>% set_names(NULL)
p2 <- survey::svychisq(~trt + response, strial_subset, statistic = "F")$p.value %>% set_names(NULL)
p2 - p1
#> [1] 2.611943e-05
```

<sup>Created on 2020-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
It seems that there is a difference in the computation of the number of degrees of freedom.

```
> survey::svychisq(~trt+response, strial_subset)

	Pearson's X^2: Rao & Scott adjustment

data:  survey::svychisq(~trt + response, strial_subset)
F = 0.39163, ndf = 1, ddf = 192, p-value = 0.5322

> survey::svychisq(~trt+response, strial)

	Pearson's X^2: Rao & Scott adjustment

data:  survey::svychisq(~trt + response, strial)
F = 0.39163, ndf = 1, ddf = 199, p-value = 0.5322
```

I'm not sure if it is appropriate. Maybe it could be worth to ask the authors of `survey`

**Comment by ddsjoberg** [comment]
Perhaps an easy fix would be to rather than deleting the missing observations, make the missing level explicit `data$variables[[by]] <- factor(data$variables[[by]]) %>% forcats::fct_explicit_na()`?

**Comment by larmarange** [comment]
True. At least things will be clearly visible, up to the user to remove the NA if needed

**Comment by ddsjoberg** [comment]
Having thought about this more, I am leaning toward keeping it as it already is. I don't like the idea of forcing the NA columns to appear, likely a big breaking change for users.  Moreover, we're printing a clear message that the missing `by=` rows are being dropped.....
