### ISSUE TITLE
Error when felm model%>%tbl_regression()

### ISSUE THREAD

**Issue by IsadoraBM** [ddsjoberg/gtsummary#712]
`Error: Error in terms.formula(form, ...): 'data' argument is of the wrong type ` output

**Comment by ddsjoberg** [comment]
Hello, thanks for the report. Please provide a reproducible example and we can troubleshoot.

**Comment by ddsjoberg** [comment]
Hello again,  The {lfe} package was removed from CRAN.  Is this package going to be supported going forward?

**Comment by IsadoraBM** [comment]
Hi Daniel,

I don't maintain lfe. Seems like the issue was the saved model wasn't loading correctly, after rerunning it gtsummary worked as expected. Sorry about that.

**Comment by larmarange** [comment]
It seems that `lfe` team is working on correcting the package to be back on CRAN: https://github.com/sgaure/lfe/issues/41

Dear @ddsjoberg 

I just tested quickly if `broom.helpers` was working correctly with `felm` models. There were some errors and I made the code of `broom.helpers` more generic.

Dear @IsadoraBM 

`gtsummary::tbl_regression` now relies on `broom.helpers`. Could you please test the development version of th epackage to see if the produced tables are correct. I am not very familiar with `felm` models. cf. https://github.com/larmarange/broom.helpers/issues/79

**Comment by IsadoraBM** [comment]
Sure, I'll update you in the next few days!

Isadora Borges Monroy

McGill University, Centre for the Study of Democratic Citizenship

________________________________
