### ISSUE TITLE
Allow returning multiple values for multinomial variables with add_p and add_stat

### ISSUE THREAD

**Issue by JeremyPasco** [ddsjoberg/gtsummary#714]
**The idea**

I am looking for a way to use chi square or fisher tests on multinomial variables. Let's say I have a group variable (A or B) and an exposure variable (X, Y Z).

I'd like to compare Y and Z exposure with X between groups, which would generate a table like :

| Characteristic | Group A | Group B | OR | 95 CI | p.value |
|---|---|---|---|---|---|
|Exposure| | | |
|  X  |  75 | 23 | - | - | - |
|  Y  |  19 | 41 |1.5 | 1.1, 1.7 | 0.04 |
|  Z  |  103 | 81 | 2.7 | 2.5, 2.9 | 0.03 |

(random values here)

**Imagined solutions**
Similar tables are already possible with a tbl_uvregression() call (first level used as reference). At first I thought I should create a custom vetted model working with it. But it sounds wrong since it has nothing to do with a regression.

Other idea : allowing add_stat to display multiple p.values for a multinomial variable like this:

```r
my_fisher <- function(data, variable, by, ...) {
  # for example purpose only :
  list(
    X = list(or = NULL, ci = NULL, p=NULL), 
    Y = list(or = 1.5, ci = "1.1, 1.7", p=0.04), 
    Z = list(or = 2.7, ci = "2.5, 2.9", p=0.03) 
   )
}

my_data %>%
  select(group, exposure) %>%
  tbl_summary(by = group) %>%
  add_stat(
    fns = everything() ~ my_fisher,
)
```

For now it's not possible because add_stat is expecting my_fisher to return only one value. Would it be possible to allow returning multiple columns (or, ci and p here) and multiple rows (X, Y and Z here)?

**Comment by JeremyPasco** [comment]
Other idea: since tbl_uvregression seems to me the "shortest" way to do it with a new vetted model, it could be used for any kind of non-regression model. If that's true, would it make sense to rename them into or create new functions called tbl_uvmodel() and tbl_model() ?

**Comment by ddsjoberg** [comment]
HI @JeremyPasco !

Thanks for the post!  I am not sure what you're looking for.  Can you create a table of what you'd like the output to look like, and annotate each of the statistics presented? I think a simple dummy data set would help too, or please put your example in context of the trial dataset included in the gtsummary package. Sorry for being dense here!

**Comment by ddsjoberg** [comment]
This code replicates the table you have, but you're looking for something else, correct?

``` r
library(gtsummary)

tbl_reg <- 
  trial %>%
  tbl_uvregression(
    y = response, 
    include = grade, 
    method = glm,
    method.args = list(family = binomial),
    exponentiate = TRUE,
    hide_n = TRUE
  )

tbl_sum <-
  trial %>%
  select(response, grade) %>%
  tbl_summary(by = response, 
              statistic = everything() ~ "{n}")

tbl_merge(list(tbl_sum, tbl_reg)) %>%
  modify_spanning_header(everything() ~ NA) %>%
  as_kable() # convert to kable to show on github
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>0</strong>, N = 132</th>
<th style="text-align: left;"><strong>1</strong>, N = 61</th>
<th style="text-align: left;"><strong>OR</strong></th>
<th style="text-align: left;"><strong>95% CI</strong></th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grade</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">I</td>
<td style="text-align: left;">46</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">II</td>
<td style="text-align: left;">44</td>
<td style="text-align: left;">19</td>
<td style="text-align: left;">0.95</td>
<td style="text-align: left;">0.45, 2.00</td>
<td style="text-align: left;">0.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">III</td>
<td style="text-align: left;">42</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">1.10</td>
<td style="text-align: left;">0.52, 2.29</td>
<td style="text-align: left;">0.8</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by JeremyPasco** [comment]
Hi, thank you for your quick answer!
I will quickly provide a more detailed example if needed, but your reprex is exactly the idea: I'd like to be able to follow such steps (merging a tbl_regression and a tbl_summary) BUT the p-values have to be processed by fisher.test calls.

So your tbl_reg would be instead something like:

```r
tbl_reg <- 
  trial %>%
  tbl_uvregression(
    y = response, 
    include = grade, 
    method = my_fisher,
    exponentiate = TRUE,
    hide_n = TRUE
  )
```

And then I have to create the `my_fisher` function that would test 2 contingency tables:

| | 0 | 1 |
|- |-|-|
| I | 46 | 21 |
| II | 44 | 19 |

This first Fisher test would give the first p-value (0.9).

An the second contingency table :

| | 0 | 1 |
|-|-|-|
| I | 46 | 21 |
| III | 42 | 21 |

Giving the 0.8 p-value.

I managed to create such function, but it feels wrong since i'm pushing a fisher test inside a regression. Is it still the way to go ?

**Comment by ddsjoberg** [comment]
Ok, so you don't actually want odds ratios, and they were included just for illustration because it has the p-values where you want them.

In the dev version of gtsummary (will be released to CRAN next week), we have a function that will allow you to merge in values to any gtsummary table. i've included an example below how you can merge your p-values with the summary table.

``` r
# remotes::install_github("ddsjoberg/gtsummary")
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.3.5.9013'

# base summary table
tbl_sum <-
  trial %>%
  select(response, grade) %>%
  tbl_summary(by = response, 
              statistic = everything() ~ "{n}")

# construct a data frame with the p-values you want to include
tbl_of_pvalues <- 
  tibble::tibble(variable = rep_len("grade", 2),
                 label = c("II", "III"),
                 p.value = c(0.25, 0.0001))
tbl_of_pvalues
#> # A tibble: 2 x 3
#>   variable label p.value
#>   <chr>    <chr>   <dbl>
#> 1 grade    II     0.25  
#> 2 grade    III    0.0001

tbl_sum %>%
  # merge the p-values into the table_body
  modify_table_body(
    dplyr::left_join,
    tbl_of_pvalues,
    by = c("variable", "label")
  ) %>%
  # print the new column with header, and style the p-values
  modify_table_header(
    p.value, 
    hide = FALSE, 
    label = "**p-value**",
    fmt_fun = style_pvalue
  ) %>%
  as_kable() # convert to kable to display on github
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>0</strong>, N = 132</th>
<th style="text-align: left;"><strong>1</strong>, N = 61</th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grade</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">I</td>
<td style="text-align: left;">46</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">II</td>
<td style="text-align: left;">44</td>
<td style="text-align: left;">19</td>
<td style="text-align: left;">0.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">III</td>
<td style="text-align: left;">42</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'll need to think more about how and if `add_stat()` could be updated to return a tibble of results for categorical variables.

**Comment by JeremyPasco** [comment]
Well, I need size effect (here OR), its confidence interval and the p-value. That's why I was wondering if add_stat could return more than one statistic at a time, and for each level of a categorical variable.

Thank you for the last example, I'll follow it until an eventual update on add_stat 👍
