### ISSUE TITLE
tbl_uvregression() does not work with custom contrasts

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#715]
Just a quick test, but currently `tbl_uvregression()` cannot handle different types of contrasts.

``` r
library(gtsummary)

d <- trial

glm(response ~ grade, family = binomial, data = d)
#> 
#> Call:  glm(formula = response ~ grade, family = binomial, data = d)
#> 
#> Coefficients:
#> (Intercept)      gradeII     gradeIII  
#>    -0.78412     -0.05563      0.09097  
#> 
#> Degrees of Freedom: 192 Total (i.e. Null);  190 Residual
#>   (7 observations deleted due to missingness)
#> Null Deviance:       240.8 
#> Residual Deviance: 240.7     AIC: 246.7
d %>%
  tbl_uvregression(
    method = glm,
    include = c("response", "grade"),
    y = response,
    method.args = list(family = binomial),
    exponentiate = TRUE
  ) %>%
  as_kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>N</strong></th>
<th style="text-align: left;"><strong>OR</strong></th>
<th style="text-align: left;"><strong>95% CI</strong></th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grade</td>
<td style="text-align: left;">193</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">I</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">II</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0.95</td>
<td style="text-align: left;">0.45, 2.00</td>
<td style="text-align: left;">0.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">III</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">1.10</td>
<td style="text-align: left;">0.52, 2.29</td>
<td style="text-align: left;">0.8</td>
</tr>
</tbody>
</table>

``` r
contrasts(d$grade) <- "contr.sum"
glm(response ~ grade, family = binomial, data = d)
#> 
#> Call:  glm(formula = response ~ grade, family = binomial, data = d)
#> 
#> Coefficients:
#> (Intercept)       grade1       grade2  
#>    -0.77234     -0.01178     -0.06741  
#> 
#> Degrees of Freedom: 192 Total (i.e. Null);  190 Residual
#>   (7 observations deleted due to missingness)
#> Null Deviance:       240.8 
#> Residual Deviance: 240.7     AIC: 246.7
d %>%
  tbl_uvregression(
    method = glm,
    include = c("response", "grade"),
    y = response,
    method.args = list(family = binomial),
    exponentiate = TRUE
  ) %>%
  as_kable()
#> Error: Problem with `mutate()` input `tbl`.
#> x Error in `include=` argument input. Select from '(Intercept)', 'grade1', 'grade2'
#> i Input `tbl` is `map2(...)`.

contrasts(d$grade) <- "contr.treatment"
glm(response ~ grade, family = binomial, data = d)
#> 
#> Call:  glm(formula = response ~ grade, family = binomial, data = d)
#> 
#> Coefficients:
#> (Intercept)      gradeII     gradeIII  
#>    -0.78412     -0.05563      0.09097  
#> 
#> Degrees of Freedom: 192 Total (i.e. Null);  190 Residual
#>   (7 observations deleted due to missingness)
#> Null Deviance:       240.8 
#> Residual Deviance: 240.7     AIC: 246.7
d %>%
  tbl_uvregression(
    method = glm,
    include = c("response", "grade"),
    y = response,
    method.args = list(family = binomial),
    exponentiate = TRUE
  ) %>%
  as_kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>N</strong></th>
<th style="text-align: left;"><strong>OR</strong></th>
<th style="text-align: left;"><strong>95% CI</strong></th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grade</td>
<td style="text-align: left;">193</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">I</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">II</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0.95</td>
<td style="text-align: left;">0.45, 2.00</td>
<td style="text-align: left;">0.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">III</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">1.10</td>
<td style="text-align: left;">0.52, 2.29</td>
<td style="text-align: left;">0.8</td>
</tr>
</tbody>
</table>

``` r
contrasts(d$grade) <- contr.treatment(3)
glm(response ~ grade, family = binomial, data = d)
#> 
#> Call:  glm(formula = response ~ grade, family = binomial, data = d)
#> 
#> Coefficients:
#> (Intercept)       grade2       grade3  
#>    -0.78412     -0.05563      0.09097  
#> 
#> Degrees of Freedom: 192 Total (i.e. Null);  190 Residual
#>   (7 observations deleted due to missingness)
#> Null Deviance:       240.8 
#> Residual Deviance: 240.7     AIC: 246.7
d %>%
  tbl_uvregression(
    method = glm,
    include = c("response", "grade"),
    y = response,
    method.args = list(family = binomial),
    exponentiate = TRUE
  ) %>%
  as_kable()
#> Error: Problem with `mutate()` input `tbl`.
#> x Error in `include=` argument input. Select from '(Intercept)', 'grade2', 'grade3'
#> i Input `tbl` is `map2(...)`.

contrasts(d$grade) <- contr.treatment(3, base = 2)
glm(response ~ grade, family = binomial, data = d)
#> 
#> Call:  glm(formula = response ~ grade, family = binomial, data = d)
#> 
#> Coefficients:
#> (Intercept)       grade1       grade3  
#>    -0.83975      0.05563      0.14660  
#> 
#> Degrees of Freedom: 192 Total (i.e. Null);  190 Residual
#>   (7 observations deleted due to missingness)
#> Null Deviance:       240.8 
#> Residual Deviance: 240.7     AIC: 246.7
d %>%
  tbl_uvregression(
    method = glm,
    include = c("response", "grade"),
    y = response,
    method.args = list(family = binomial),
    exponentiate = TRUE
  ) %>%
  as_kable()
#> Error: Problem with `mutate()` input `tbl`.
#> x Error in `include=` argument input. Select from '(Intercept)', 'grade1', 'grade3'
#> i Input `tbl` is `map2(...)`.
```

<sup>Created on 2020-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
Several options:

- update the documentation to specify the limitation of the current functions
- update function code to handle the different cases (could be tricky, cf. development of `broom.helpers`)
- update the function to use internally `broom.helpers` who can handle the different types of contrasts

**Comment by ddsjoberg** [comment]
I think this is all squared away in the dev version? 

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.3.5.9013'

d <- trial

contrasts(d$grade) <- contr.treatment(3)
d %>%
  tbl_uvregression(
    method = glm,
    include = c("response", "grade"),
    y = response,
    method.args = list(family = binomial),
    exponentiate = TRUE
  ) %>%
  as_kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>N</strong></th>
<th style="text-align: left;"><strong>OR</strong></th>
<th style="text-align: left;"><strong>95% CI</strong></th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grade</td>
<td style="text-align: left;">193</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">I</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">II</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0.95</td>
<td style="text-align: left;">0.45, 2.00</td>
<td style="text-align: left;">0.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">III</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">1.10</td>
<td style="text-align: left;">0.52, 2.29</td>
<td style="text-align: left;">0.8</td>
</tr>
</tbody>
</table>

``` r

contrasts(d$grade) <- contr.treatment(3, base = 2)
d %>%
  tbl_uvregression(
    method = glm,
    include = c("response", "grade"),
    y = response,
    method.args = list(family = binomial),
    exponentiate = TRUE
  ) %>%
  as_kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>N</strong></th>
<th style="text-align: left;"><strong>OR</strong></th>
<th style="text-align: left;"><strong>95% CI</strong></th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grade</td>
<td style="text-align: left;">193</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">I</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">1.06</td>
<td style="text-align: left;">0.50, 2.24</td>
<td style="text-align: left;">0.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">II</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">III</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">1.16</td>
<td style="text-align: left;">0.55, 2.47</td>
<td style="text-align: left;">0.7</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
Great !!!

I should have tested the dev version !!!

**Comment by ddsjoberg** [comment]
YAY! I think it's typically safe to assume I have messed up something with the contrasts!!! 😆 😆 😆
