### ISSUE TITLE
Add VIFs for regression tables

### ISSUE THREAD

**Issue by storopoli** [ddsjoberg/gtsummary#717]
Hello, guys!

Great work with the package!

I am missing an option to report VIFs of all variables inside a tbl_regression() and also in a tbl_merge().

I went through the whole documentation and searched in Issues and could not find a function. Am I missing anything?

**Comment by ddsjoberg** [comment]
The tbl_regression() function uses broom::tidy() to perform any initial summarizing of the model object.  If you would like to include VIF, then you'll need create a new tidy function that includes the VIF.

Below is a simple example (you would need to update the tidy function if you hade categorical variables, for example).

```r
library(gtsummary)

model <- lm(hp ~ mpg + cyl, mtcars)

# build tidier with VIF
tidy_with_vif <- function(x, ...) {
  broom::tidy(x, ...) %>%
    # merge in the VIF values
    left_join(
      car::vif(model) %>% 
        enframe("term", "vif"),
      by = "term"
    )
}

tbl_regression(model, tidy_fun = tidy_with_vif) %>%
  # add column header
  modify_header(vif ~ "**VIF**") %>%
  # convert to gt to add a formatting function for VIF
  as_gt() %>%
  gt::fmt(columns = vars(vif), fns = style_sigfig)
```
![image](https://user-images.githubusercontent.com/26774684/102655223-eecba280-413f-11eb-85c8-3ef38f85bdfc.png)

**Comment by ddsjoberg** [comment]
@storopoli if this solves your problem, please feel free to close the issue.  If not, let me know!

**Comment by storopoli** [comment]
Dear @ddsjoberg  I've tried your solution together with the standardized coefficients inside `tidy_fun` argument.

```r
m_1 <- tbl_regression(model_1, tidy_fun = list(tidy_standardize, tidy_with_vif)) %>%
  bold_labels() %>%
  italicize_levels() %>% 
  add_glance_source_note(include = c(r.squared, adj.r.squared)) %>%
  modify_header(list(estimate ~ "**Std. Beta**", vif ~ "**VIF**"))
```

I've got the following error:
```r
`Error: Inputs `estimate_fun`, `pvalue_fun`, `tidy_fun` must be functions.`
```

**Comment by ddsjoberg** [comment]
Dear @storopoli , as the error indicated `tidy_fun=` must be a tidying function, not a list.  If you wish to combine them, you'll need to compose a tidy function that both standardizes the coefs and adds the VIF.  

In the VIF tidier I wrote, you can likely just replace `broom::tidy()` with `tidy_standardize()`. Test your tidier outside of `tbl_regression()` first.

**Comment by storopoli** [comment]
I've updated the `tidy_with_vif()` function to
```r
# build tidier with VIF
tidy_with_vif <- function(x, ...) {
  tidy_standardize(x, ...) %>%
    # merge in the VIF values
    left_join(
      car::vif(x) %>%    # changed model -> x
        enframe("term", "vif"),
      by = "term"
    )
}
```

Here is the output:
``` r
tidy_with_vif(model_2)
Estimating standardized coefs with
`effectsize::standardize_parameters(model = x, ci = 0.95)`
Error: `x` must not have more than one dimension. `length(dim(x))` must be zero or one, not 2.
```

**Comment by ddsjoberg** [comment]
1. What have you done to debug the function you wrote?
2. You'll need to provide a reproducible example, otherwise I can't assist.

**Comment by storopoli** [comment]
Finally, I've managed to reproduce. It has something do to with factor (char) variables in the regression model.

``` r
library(gtsummary)
library(tidyverse)

n <- 100

df <- tibble(
  x = rnorm(n),
  y = rnorm(n, mean = 1, sd = 10),
  z = sample(c("A", "B", "C"), n, replace = T)
)

model <- lm(y ~ x + z, df)

# build tidier with VIF
tidy_with_vif <- function(x, ...) {
  tidy_standardize(x, ...) %>%
    # merge in the VIF values
    left_join(
      car::vif(x) %>% 
        enframe("term", "vif"),
      by = "term"
    )
}

tbl_regression(model, tidy_fun = tidy_with_vif) %>%
  # add column header
  bold_labels() %>%
  italicize_levels() %>% 
  add_glance_source_note(include = c(r.squared, adj.r.squared)) %>%
  modify_header(list(estimate ~ "**Std. Beta**", vif ~ "**VIF**")) %>% 
  # convert to gt to add a formatting function for VIF
  as_gt() %>%
  gt::fmt(columns = vars(vif), fns = style_sigfig)
#> Estimating standardized coefs with
#> `effectsize::standardize_parameters(model = x, ci = 0.95)`
#> x There was an error calling `tidy_fun`.
#>   Most likely, this is because the argument passed in `tidy_fun=` 
#>   was
#>   misspelled, does not exist, is not compatible with your object, 
#>   or was missing necessary arguments. See error message below.
#> Error: Error: `x` must not have more than one dimension. `length(dim(x))` must be zero or one, not 2.
```

<sup>Created on 2020-12-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
```r
# install dev version
remotes::install_github("ddsjoberg/gtsummary")
library(tidyverse)
library(gtsummary)

model1 <- lm(hp ~ mpg + factor(cyl), mtcars)

# put VIF results in data frame
vif_to_tibble <- function(x) {
  vif <- car::vif(x)
  
  if (!is.matrix(vif)) 
    result <- 
      car::vif(x) %>% 
      enframe("variable", "vif") 
  else 
    result <-
      car::vif(x) %>% 
      as.data.frame() %>%
      rownames_to_column(var = "variable") %>%
      as_tibble() %>%
      select(variable, vif = GVIF)
   return(result %>% mutate(row_type = "label")) 
} 

tbl_regression(model1, tidy_fun = tidy_standardize) %>%
  # merge in VIF stats
  modify_table_body(
    dplyr::left_join, 
    vif_to_tibble(model1),
    by = c("variable", "row_type")
  ) %>%
  # add column header
  modify_header(vif ~ "**VIF**") %>%
  # convert to gt to add a formatting function for VIF
  as_gt() %>%
  gt::fmt(columns = vars(vif), fns = style_sigfig)
```

![image](https://user-images.githubusercontent.com/26774684/102661397-b9788200-414a-11eb-8464-83b4ebe3317e.png)

**Comment by storopoli** [comment]
WOW perfect!

Do you accept donations? I wanna buy you a cup of coffee...

I even did some fancy stuff

```r
tables_reg <- models %>% 
  map(~ tbl_regression(., tidy_fun = tidy_standardize) %>%
  bold_labels() %>%
  italicize_levels() %>% 
  add_glance_source_note(include = c(r.squared, adj.r.squared)) %>%
  # merge in VIF stats
  modify_table_body(
    dplyr::left_join, 
    vif_to_tibble(.x),
    by = c("variable", "row_type")
  ) %>%
  # add column header
  modify_header(list(estimate ~ "**Std. Beta**", vif ~ "**VIF**")))

tbl_merge(
  tables_reg)
```

**Comment by storopoli** [comment]
`vif_to_tibble()` will be included in a future release?

**Comment by ddsjoberg** [comment]
> `vif_to_tibble()` will be included in a future release?

Oh no, that was just for you!

**Comment by larmarange** [comment]
To be honest, I'm thinking that a add_vif function would be a good idea. With an option to choose between gvif orGVIF^(1/(2*Df)) .

It would be relevant to sensitivities student about the issue of multi colinearity

**Comment by ddsjoberg** [comment]
@larmarange @storopoli 

thanks for the input! before we implement anything, let's brainstorm the best implementation...
1. Should it be implemented as it's own function, `add_vif()`?
2. We can generalize the `add_stat()` function (currently only works with `tbl_summary()`). We can allow users to more easily submit custom stats and include methods such as VIF internally they can select from.
3. Something else?

Anyway, those are my initial thoughts about implementation.  What do you think?

**Comment by storopoli** [comment]
From my point of view, VIFs are very important measures in regression models. I barely use the q statistics for False-Discovery rate (FDR). I use VIFs all the time. Since, {gtsummary} has a function dedicated to q values `add_q()`, I think VIFs should be on the same level and have a dedicated function `add_vif()`.

But @ddsjoberg from your point view (and this depends where you see your package going in the future) we could have two broad approaches:

1. "Granulize" everything and keep all functions specific to every little detail or extra implementation. Example:
```r
tbl_regression(model) %>%
  bold_labels() %>%
  italicize_levels() %>%
  add_q() %>%
  add_vif() %>%
  ...
````

2. Generalize everything and keep the basic stuff in functions and the little details and extra implementation inside big general functions. Example:
```r
tbl_regression(model) %>%
  bold_labels() %>%
  italicize_levels() %>%
  add_stat(c("q", "vif"))
```

I think that option 1 is better, because it is how the package is structured now. Option 2 demands a full overhaul.

**Comment by ddsjoberg** [comment]
Hi @larmarange @storopoli , Overall, gtsummary has been about preparing tables that will be published. I've tried to draw a line between exploring your data and models and the final product to keep the focus of the package more narrow. In the areas I work, VIF would be used to explore models and would not be published in the final manuscript. I am not sure if this is true in other fields as well; regardless, I added a PR to include the function.

**Comment by storopoli** [comment]
@ddsjoberg I research mostly on management and broad social sciences. I am currently the Editor of the Iberoamerican Journal of Strategic Management and I enforce that every regression model with more than 3 variables must be supplied with a multicollinearity test (VIFs).

**Comment by larmarange** [comment]
> Hi @larmarange @storopoli , Overall, gtsummary has been about preparing tables that will be published. I've tried to draw a line between exploring your data and models and the final product to keep the focus of the package more narrow. In the areas I work, VIF would be used to explore models and would not be published in the final manuscript. I am not sure if this is true in other fields as well; regardless, I added a PR to include the function.

I understand your point of view.  I'm teaching R to students in social science, who have not a coding background. Now, I'm teaching them directly `gtsummary` as this is the easiest way to obtain the results they need.  Even before publication when performing preliminary analysis, `gtsummary` is useful to display the results. In particular, before knowing R markdown, the option `compile reports` in RStudio is very useful to obtain a simple report of codes + results.

In that sense, having `add_vif()` would be very useful (based on `car:::vif()` which is the most generic) for non advanced users. And I agree with @storopoli  that some journals now ask for VIF (eventually in supplementary material).

`add_stat()` remains crucial for allowing advanced users to perform specific analysis (and for example for using other functions to compute VIF), but having a basic function for the main usage would be really great.

**Comment by ddsjoberg** [comment]
Thank you both for your comments....much appreciated!

The pull request is here with the completed function
https://github.com/ddsjoberg/gtsummary/pull/720
