### ISSUE TITLE
Allow grouping by multiple variables

### ISSUE THREAD

**Issue by kmdono02** [ddsjoberg/gtsummary#736]
**Is your feature request related to a problem? Please describe.**
I'd like to use the gtsummary to create summary statistics tables where two (or more) variables are used to group.  Currently only one grouping variable is supported.

**Describe the solution you'd like**
Add nested group support using 2 or more variables.  An example would be what is done using the tableone package.  See
https://cran.r-project.org/web/packages/tableone/vignettes/introduction.html 
multiple group summaries section.

**Describe alternatives you've considered**
Using the tableone package instead of gtsummary, though I really like the gtsummary package in every other function.

**Comment by ddsjoberg** [comment]
Hey @kmdono02 , thanks for the comment.

FYI, something is in the works, but I haven't settled on the best implementation of it.
https://github.com/ddsjoberg/gtsummary/pull/726

**Comment by ddsjoberg** [comment]
Duplicate issue https://github.com/ddsjoberg/gtsummary/issues/679
