### ISSUE TITLE
Update `add_n()` and `add_nevent()` for regression models

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#744]
broom.helpers now returns the Ns and event Ns for regression models.
1. Update the methods for `tbl_regression()` and `tbl_uvregression()` to use the columns added to the tidy tibbles.
2. Add an option to either add overall Ns or Ns to each variable level.

**Comment by larmarange** [comment]
Let me know if you need any update on `broom.helpers` side
