### ISSUE TITLE
Create an add_stats() function to allow function returning multiple statistics for each variable/categorical level

### ISSUE THREAD

**Issue by JeremyPasco** [ddsjoberg/gtsummary#746]
**Behavior expected**
For now, `add_stat()` accepts a function parameter that must return a vector, containing a unique statistic for each variable and/or each categorical level of a summary.

Since many statistical functions generate multiple statistics at once (ie: size effect, residuals, p-values), it could be useful to allow a function parameter to return a dataframe instead of a vector (columns would be for statistics and rows for variables).

**Current workaround**:
One way to do it is to call multiple times `add_stat()` with slightly different function to return a different statistic, but it can be very costly since it runs multiple times the same statistical test on the same data:

``` r
library(gtsummary)

# fn returns t-test t-statistic ONLY
my_ttest_t <- function(data, variable, by, ...) {
  t.test(data[[variable]] ~ as.factor(data[[by]]))$statistic
}

# fn returns t-test p-value ONLY
my_ttest_p <- function(data, variable, by, ...) {
  t.test(data[[variable]] ~ as.factor(data[[by]]))$p.value
}

add_stat_ex1 <- trial %>%
  select(trt, age, marker) %>%
  tbl_summary(by = trt, missing = "no") %>%
  # Adding t-statistics and p-values from t.test
  add_stat(
    fns = everything() ~ my_ttest_t,  # all variables compared with with t-test
    header = "**t (Student)**"
  ) %>% 
  add_stat(
    fns = everything() ~ my_ttest_p,  # all variables compared with with t-test (AGAIN)
    header = "**P-value**",
    fmt_fun = style_pvalue            # format p-values with style_pvalue()
  )
```

<sup>Created on 2021-01-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Solution proposed**
I propose to create an `add_stats()` function (note the plural form) that would allow returning multiple statistics for each variable/categorical level like this:

``` r
library(gtsummary)

# fn returns t-test t-statistic AND pvalue
my_ttest <- function(data, variable, by, ...) {
  result <- t.test(data[[variable]] ~ as.factor(data[[by]]))
  
  list(
    t = result$statistic,
    p.value = result$p.value
  )
}

add_stat_ex1 <- trial %>%
  select(trt, age, marker) %>%
  tbl_summary(by = trt, missing = "no") %>%
  # Adding t-statistics and p-values from t.test
  add_stats(
    fns = everything() ~ my_ttest,  # all variables compared with with t-test
    fmt_fun = list(
        t = NULL,                   # no styling for t-statistics
        p.value = style_pvalue,     # format p-values with style_pvalue()
      ),
    header = list(                  # new column headers
      t = "**t (Student)**",
      t = "**P-value**"
    )
  )
```

<sup>Created on 2021-01-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
Thank you for putting this together ☺️ I've started putting something together in the referenced pull request.
