### ISSUE TITLE
add `p.value` to `tidy_fun = tidy_standardize` in `tbl_regression`

### ISSUE THREAD

**Issue by storopoli** [ddsjoberg/gtsummary#753]
Hello, could we have an implementation of p-values to standardized coefficients while using `tidy_fun = tidy_standardize` inside `tbl_regression`.

For example, raw coefficients are supplied by `tbl_regression`:

``` r
library(gtsummary)
    gtsummary::tbl_regression(lm(mpg ~ hp, data = mtcars)) %>% 
        bold_p()
#> Warning: The `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
```

<div id="zopreqcsgk" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_left">hp</td>
      <td class="gt_row gt_center">-0.07</td>
      <td class="gt_row gt_center">-0.09, -0.05</td>
      <td class="gt_row gt_center" style="font-weight: bold;"><0.001</td>
    </tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table></div>

<sup>Created on 2021-01-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

but they are not possible with `tidy_fun = tidy_standardize` in `tbl_regression`:

``` r
library(gtsummary)
#> #Uighur
gtsummary::tbl_regression(lm(mpg ~ hp, data = mtcars), tidy_fun = tidy_standardize) %>% 
  bold_p()
#> tidy_standardize(): Estimating standardized coefs with
#> `effectsize::standardize_parameters(model = x, ci = 0.95)`
#> Error: There is no p-value column. `x$table_body` must have a column called 'p.value'
```

<sup>Created on 2021-01-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

## Problem with `effectsize::standardize_parameters`:

The problem is that `effectsize::standardize_parameters` does not return a column for `p.value`:

``` r
effectsize::standardize_parameters(lm(mpg ~ hp, data = mtcars))
#> # Standardization method: refit
#> 
#> Parameter   | Coefficient (std.) |         95% CI
#> -------------------------------------------------
#> (Intercept) |          -3.15e-17 | [-0.23,  0.23]
#> hp          |              -0.78 | [-1.01, -0.54]
```

<sup>Created on 2021-01-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

## Possible solution with `broom.helpers::tidy_plus_plus`

We could use `broom.helpers::tidy_plus_plus` and do a `left_join` or some other manipulation to add a `p.value` column, since `broom.helpers::tidy_plus_plus` does supply a `p.value` column. Also `p.values` are invariant to coefficients transformations.

``` r
broom.helpers::tidy_plus_plus(lm(mpg ~ hp, data = mtcars))
#> # A tibble: 1 x 16
#>   term  variable var_label var_class var_type var_nlevels contrasts
#>   <chr> <chr>    <chr>     <chr>     <chr>          <int> <chr>    
#> 1 hp    hp       hp        numeric   continu…          NA <NA>     
#> # … with 9 more variables: contrasts_type <chr>, reference_row <lgl>,
#> #   label <chr>, estimate <dbl>, std.error <dbl>, statistic <dbl>,
#> #   p.value <dbl>, conf.low <dbl>, conf.high <dbl>
```

<sup>Created on 2021-01-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by ddsjoberg** [comment]
Do you know why `effectsize::standardize_parameters()` chose not to report it?

**Comment by storopoli** [comment]
I'm not sure, but I think that the functions from `effectsize` were not supposed to report p-values. I don't see any mention in the [`effectsize` package website](https://easystats.github.io/effectsize/articles/standardize_parameters.html) -- just a brief one in `correlation::correlation()`.

**Comment by ddsjoberg** [comment]
Just an FYI, I am going on parental leave starting Friday....I won't have time to look at this until a return in 5 weeks

**Comment by storopoli** [comment]
No problem, take your time.

Congratulations! 🎉

**Comment by ddsjoberg** [comment]
But you can write you own tidier and use it without any updates

```r
storopoli_tidier <- function(x, ...) {
  broom <-
    broom::tidy(x, ...) %>%
    select(term, p.value)
  
  gtsummary::tidy_standardize(x, ...) %>%
    dplyr::left_join(broom, by = "term")
}
```
This (or something similar) should work for you, e.g. `tbl_regression(x, tidy_fun = storopoli_tidier)`

**Comment by ddsjoberg** [comment]
hey hey @storopoli !

I never envisioned gtsummary as a place to store tidiers for various model types. We do now export a re-packaged tidier for a standardized model and a bootstrapped model. We take each of these tidiers directly from teh source package without any modification except the column names. I don't want to make them more complex than this because I don't want to be responsible for maintaining them in the future.

The documentation shows an example how to get the p-value in the table, and the above tidier will also work. For now, that will have to suffice. Best, Daniel

**Comment by storopoli** [comment]
Sure @ddsjoberg thanks a lot for the `storopoli_tidier()` and the effort...
