### ISSUE TITLE
theme_gtsummary_mean_sd() should also change the defaut test in tbl_svysummary()

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#758]
`theme_gtsummary_mean_sd()` change the default test for add_p.tbl_summary and continuous variable for a test comparing means.

Similar change should be done for add_p.tbl_svymmary (default test for continuous variable being a t-test.

**Comment by ddsjoberg** [comment]
Hey @larmarange ! When a by variable has 3+ levels, what test should be used for continuous variables when the theme is set?

**Comment by larmarange** [comment]
You can still use `svyttest()`. In fact, it's a wrapper around `svyglm()` and therefore can handle 3+ groups.

``` r
library(survey)
#> Le chargement a nécessité le package : grid
#> Le chargement a nécessité le package : Matrix
#> Le chargement a nécessité le package : survival
#> 
#> Attachement du package : 'survey'
#> The following object is masked from 'package:graphics':
#> 
#>     dotchart
library(gtsummary)
design <- svydesign(ids = ~1, weights = ~1, data = trial)
svyttest(marker ~ stage, design)
#> 
#>  Design-based t-test
#> 
#> data:  marker ~ stage
#> t = 2.2153, df = 186, p-value = 0.02796
#> alternative hypothesis: true difference in mean is not equal to 0
#> 95 percent confidence interval:
#>  0.04599717 0.75223541
#> sample estimates:
#> difference in mean 
#>          0.3991163
```

<sup>Created on 2021-02-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by ddsjoberg** [comment]
Gotcha, thanks!
