### ISSUE TITLE
{gt} changing name of cell_styles() function

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#78]
The {gt} package is renaming one of the functions used in {gtsummary}. (from `cell_styles()` to `cell_text()`) https://github.com/rstudio/gt/issues/258

When this update goes through, we'll need to update our code.  As of this moment, the `cell_styles()` function is used in:
The bolding/italicizing of labels/levels functions,
`tab_style_bold_p()`,
`tbl_merge()`,
`tbl_regression()`,
`tbl_summary()`,
`tbl_uvregression()`

**Comment by rich-iannone** [comment]
Sorry about this drastic change, but it'll see `cells_styles()` largely become `cell_text()` (text styles), `cell_fill()` will be added (bkgd_color from `cells_styles()` will become `color` in this function), and there will a new helper function called `cell_borders()`. Oh, and all of the remaining args in the new `cell_text()` function won't have the leading `text_` in them.

If using a multiple of these helpers with `style` in `tab_style()`, then we enclose the calls in a `list()`. Here's an example:

```r
exibble %>%
  gt() %>%
  tab_style(
    style = list(
      cell_borders(selection = c("[", "]"), color = "green", style = "solid", weight = px(3)),
      cell_fill(color = "lightgray"),
      cell_text(color = "steelblue", font = "HelveticaNeue")
      ),
    locations = cells_data(columns = vars(row, char)))
```

Once the PR is underway, I'll reference this issue.

**Comment by ddsjoberg** [comment]
Hi @rich-iannone !  Thank you for the response!  It'll be super easy to update these few functions once the PR is done, so no worries about changing the name.  I think the update will make the `tab_style` function more intuitive.

BTW, I love the {gt} package!  It is amazing, and thank you for creating it!

**Comment by ddsjoberg** [comment]
PS @rich-iannone I didn't realize when I copied the {gt} issue url into this issue, it would add a note on your side.  Sorry if I caused a bother! :maple_leaf:

**Comment by rich-iannone** [comment]
No note was created on the gtside! I just noticed this project in the GitHub activity feed today and I thought I’d check it out. 

BTW, all of this is lookin’ good!

**Comment by ddsjoberg** [comment]
gt and gtsummary were updated
https://github.com/ddsjoberg/gtsummary/pull/170
