### ISSUE TITLE
value parameter in tbl_summary doesn't work on an empty category

### ISSUE THREAD

**Issue by JeremyPasco** [ddsjoberg/gtsummary#780]
### Expected behavior:

Setting the value parameter of tbl_summary on a category should display only this category, even if this category has a null count.

### Actual behavior

On categorical variables, setting the value parameter on a non represented category does nothing.

### Reprex

``` r
library(tidyverse)
library(gtsummary)

x <- trial %>% 
  transmute(
    trt = fct_expand(trt, 'Drug C')
  )

tbl_summary(x) # display all categories: OK
tbl_summary(x, value = trt ~ "Drug A") # display only Drug A: OK
tbl_summary(x, value = trt ~ "Drug C") # display all categories: wrong
```
<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

By this third summary, I expected one row with : `Drug C      0 (0%)`

**Comment by ddsjoberg** [comment]
😱 thank you so much for the report!
