### ISSUE TITLE
Feature request: Collapse infrequent levels of categorical variable in `tbl_summary()`

### ISSUE THREAD

**Issue by maia-sh** [ddsjoberg/gtsummary#781]
Thank you for this wonderful package!

**Context**
I have a categorical variable with many (20+) levels, including some with very low {n}. `tbl_summary()` includes one row for each level, which produces a very long table. I would like to be able to summarize the variable, collapsing the most infrequent categories as "Other". I was not able to find an option for collapsing the variable.

**Current alternative**
I have a workaround implementation by creating the variable with the collapsed group, before piping to `tbl_summary()` (shown below under "Reprex/screenshot")

**Proposed implementation**
I could see this implemented as an argument to `tbl_summary()`offering various options to collapse on:
- `comparator`: >, <, >=, <=
- `type`: {p}/percent, {n}/frequency, {n_levels}/number of levels
- `limit`: numeric value from which to apply collapse
- `level`: label for new collapsed level

For example, this would produce the output shown in the reprex/screenshot, i.e., collapse stages with 25% or less of the observations as "(Other stages)", removing T3 and T4.

```r
gtsummary::trial %>%
  tbl_summary(
    collapse = stage ~ c(comparator = "<=", type = "p",  limit = 25, level = "(Infrequent stages)")
  )
```
Additional examples:
Collapse stages with more than 52 observations as "(Frequent stages)", removing T1 and T2.
`collapse = stage ~ c(comparator = ">", type = "n",  limit = 52, level = "(Frequent stages)")`

Collapse 2 least frequent stages as "(2 least frequest stages)", removing T3 and T4.
`collapse = stage ~ c(comparator = "<=", type = "n_level",  limit = 2, level = "(2 least frequest stages)")`

Ideally, this "collapsed" level could also be placed below/above the other levels, not subject to `sort`. This could be implemented as another option for `collapse` (e.g., `sort = "top"/"bottom"`), but I think this could also be a separate feature, so I will separate that request.

**Reprex/screenshot**
Here is a reprex to create the summary table with both the original version (showing all individual levels) and "other" version (`stage_grouped`), with stages representing 25% or less of the sample grouped as "(Infrequent stages)"

``` r
library(dplyr)
library(gtsummary)

gtsummary::trial %>%
  select(stage) %>%
  add_count() %>%
  group_by(stage) %>%
  mutate(
    pct_stage = n()/n,
    stage_grouped = if_else(pct_stage <= 0.25, "(Infrequent stages)", as.character(stage))
  ) %>%
  select(-pct_stage, -n) %>%
  tbl_summary(
    sort = everything() ~ "frequency"
  )
#> Warning: The `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
```
<sup>Created on 2021-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<img width="291" alt="Screen Shot 2021-02-12 at 23 02 12" src="https://user-images.githubusercontent.com/38968656/107827087-5a1fa280-6d86-11eb-9c06-e295ec289f71.png">

**Comment by ddsjoberg** [comment]
hey hey!

My response here is similar to your other....there is a forcats function that lumps less frequent levels!

``` r
library(gtsummary)

trial %>%
  # lump everything not in the top two most frequent groups
  mutate(stage = forcats::fct_lump_n(stage, 2)) %>%
  select(stage) %>%
  tbl_summary() %>%
  as_kable() # convert to kable to display on github
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>N = 200</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">T Stage</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">T1</td>
<td style="text-align: left;">53 (26%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">T2</td>
<td style="text-align: left;">54 (27%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other</td>
<td style="text-align: left;">93 (46%)</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-02-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by maia-sh** [comment]
Thank you! I believe `forcats::fct_lump_` functions cover all the use cases I mentioned, so I can close this.
