### ISSUE TITLE
Feature request: relocate specified level separate from `sort` in `tbl_summary()` 

### ISSUE THREAD

**Issue by maia-sh** [ddsjoberg/gtsummary#782]
Thanks again for the package! Another feature idea...

**Context**
Sometimes I have a categorical variable with one (or more) "special" level(s) which I do not want sorted like the others. For example, a collapsed level. I.e., regardless of `sort = "alphanumeric"` or `sort = "frequency"`, the special level(s) should appear at the top or bottom (user-specified). This seems to be the behavior with `missing`, so perhaps an extension of that functionality.

**Current workaround**
None yet! If using `sort = "alphanumeric"` then using a non-word symbol in the variable name works to get the special level on top (see below), but this doesn't work with `sort = "frequency"` and doesn't allow me to move it to the bottom.

**Proposed implementation**
I could imagine this as an extra argument to `sort` to flag that the special level(s) should be sorted differently, e.g.:
`sort = stage ~ c("frequency", special = "(TSpecial)", special_location = "bottom")`

Or as a separate argument to `tbl_summary()`, e.g.:
```
tbl_summary(
 sort = stage ~ "frequency",
 special = stage ~ c(level = "(TSpecial)", location = "bottom")
)
```

I could also see this as allowing the user to specify a vector of the order of all the levels in sorted order, e.g.:
`sort = c("T2", "T1", "T4", "T3", "(TSpecial", "Unknown")`

**Reprex/screenshot**
```r
gtsummary::trial %>%
  select(stage) %>% 
  add_row(stage = rep(NA, 80)) %>% 
  add_row(stage = rep("(TSpecial)", 48)) %>% 
  tbl_summary(sort = stage ~ "alphanumeric")
```
<img width="256" alt="Screen Shot 2021-02-12 at 23 28 58" src="https://user-images.githubusercontent.com/38968656/107829409-162e9c80-6d8a-11eb-8728-a491ce7721a6.png">

```r
gtsummary::trial %>%
  select(stage) %>% 
  add_row(stage = rep(NA, 80)) %>% 
  add_row(stage = rep("(TSpecial)", 48)) %>% 
  tbl_summary(sort = stage ~ "frequency")
```
<img width="250" alt="Screen Shot 2021-02-12 at 23 29 20" src="https://user-images.githubusercontent.com/38968656/107829499-25154f00-6d8a-11eb-908b-543384da068e.png">

**Comment by ddsjoberg** [comment]
hello hello! thank you for the kind words and the post!

I will need to sit for this a while and think of the best implementation, if we do it.  My first reaction is that the forcats package has a huge suite a functions to do just this: order your variable levels any way you want.  Their API is already so user friendly, and it would be very difficult to implement something better and comprehensize.

Because the first input of gtsummary functions is the data frame, we can change the order of a variable as we pipe the data frame into `tbl_summary()`

``` r
library(gtsummary)

trial %>%
  select(grade) %>%
  # move grade III to the front
  mutate(grade = forcats::fct_relevel(grade, "III")) %>%
  tbl_summary() %>%
  as_kable() # convert to kable to display on github
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>N = 200</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grade</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">III</td>
<td style="text-align: left;">64 (32%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I</td>
<td style="text-align: left;">68 (34%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">II</td>
<td style="text-align: left;">68 (34%)</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-02-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by maia-sh** [comment]
Thanks for the prompt reply and helpful suggestions, to both issues! I hadn't realized that {gtsummary} keeps the input order, but since this is the case, it seems like these {forcats} solutions are efficient and address most use cases. I could see this solution not working if you also want to `sort` on "frequency", since this would overwrite `forcats::fct_relevel`.

``` r
library(dplyr)
library(gtsummary)

gtsummary::trial %>%
  select(stage) %>%
  add_row(stage = rep("(TSpecial)", 48)) %>%
  mutate(stage = forcats::fct_relevel(stage, "(TSpecial)")) %>% 
  tbl_summary(sort = stage ~ "frequency") %>% 
  as_kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>N = 248</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">stage</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">T2</td>
<td style="text-align: left;">54 (22%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">T1</td>
<td style="text-align: left;">53 (21%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">T4</td>
<td style="text-align: left;">50 (20%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(TSpecial)</td>
<td style="text-align: left;">48 (19%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">T3</td>
<td style="text-align: left;">43 (17%)</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
forcats has a fct_ function to order by frequency...I think a combination of these could work?

**Comment by maia-sh** [comment]
Indeed! Thanks again. Realizing this would have been better as a SO post; I'm still figuring out the balance between SO questions vs. feature requests, so thank you for your patience.

``` r
library(dplyr)
library(gtsummary)

gtsummary::trial %>%
  select(stage) %>%
  add_row(stage = rep("(TSpecial)", 48)) %>%
  mutate(
    stage = forcats::fct_infreq(stage),
    stage = forcats::fct_relevel(stage, "(TSpecial)")
    ) %>% 
  tbl_summary() %>% 
  as_kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>N = 248</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">stage</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">(TSpecial)</td>
<td style="text-align: left;">48 (19%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">T2</td>
<td style="text-align: left;">54 (22%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">T1</td>
<td style="text-align: left;">53 (21%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">T4</td>
<td style="text-align: left;">50 (20%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">T3</td>
<td style="text-align: left;">43 (17%)</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
Anytime, happy coding 👯‍♂️
