### ISSUE TITLE
Issue exporting table as image 

### ISSUE THREAD

**Issue by zongell-star** [ddsjoberg/gtsummary#785]
I have created a table with gtsummary 

However, when I export the plot, the table copies over as a screen shot ( some of the table and some of R Studio in the background) . 

I have tried both the development and RStudio version 

Any help would be much appreciated 

Thanks,
Lauren

---

Brief description of the problem.
Code used: 
```r

participants %>%
  select(trialVersion, age, gender, employment_type, AUDIT_score_cat) %>%
  mutate(
    trialVersion = factor(trialVersion, labels = c("Standard Arm", "MRT Arm", "No Notification Arm")) %>% 
      fct_explicit_na(na_level = "Missing Response Status")
  ) %>%  
  
  tbl_summary(
    by = trialVersion, 
    missing = "ifany",
    label = list(age ~ "Age", AUDIT_score_cat ~ "AUDIT Score", gender ~ "Gender", employment_type ~ "Employment Type"),
    statistic = all_continuous() ~ "{median} ({p25}, {p75})"
  ) %>%
 

  add_n() %>%
  bold_labels() %>%
  modify_spanning_header(all_stat_cols() ~ "**Baseline Summary**") %>%
  modify_header(label = "**User Characterisitcs**") 


```

**Comment by ddsjoberg** [comment]
Hi @zongell-star , Can you share a reproducible example, please? I don't see anything in your code above about saving the table as an image. Please include that code as well.

How one would typically save a gtsummary table as an image is via the gt package's `gt::gtsave()` function. For example, 

```r
library(gtsummary)

tbl_summary(trial) %>%    # build gtsummary table
  as_gt() %>%             # convert to gt table
  gt::gtsave(             # save table as image
    filename = "my_table_image.png"
  )
```

If you're experiencing issues with `gt::gtsave()` you should likely post an issue to the gt repo.

**Comment by zongell-star** [comment]
Thanks for the quick response @ddsjoberg 
This was very helpful. Appreciate the professional looking output too. 

I had to run this code: webshot::install_phantomjs()

The code below works for the trial data example

data(trial)

library(gtsummary)

webshot::install_phantomjs()

trial2 <- trial %>% select(trt, age, grade)


trial2 %>% tbl_summary() %>%    # build gtsummary table
  as_gt() %>%             # convert to gt table
  gt::gtsave(             # save table as image
    filename = "my_table_image.png"
  )

**Comment by ddsjoberg** [comment]
Great, so your saving issue is resolved?

**Comment by zongell-star** [comment]
Yes, thanks
