### ISSUE TITLE
Customized functions for categorical data using {n} and {N} such as Wilson CI

### ISSUE THREAD

**Issue by zachariae** [ddsjoberg/gtsummary#786]
In a table, I would like to have confidence intervals for the percent information. There are functions that can calculate these CIs. 
Such functions need information on n and N, which is already provided, and on some other "constants" such as how broad the CI should be (e.g. 95%) or what method should be used ("wilson").

Up to now, custom functions are allowed only for continuous data, probably since most information only need the data itself?

There is also the add_stat function, but it seems to me that this function does not work if the results are best described as df or matrix format (many rows and many columns).

I hope, I have been able to describe my point clearly.

Thank you, kind regards, Silke

**Comment by ddsjoberg** [comment]
Hi hi @zachariae !

Thanks for the comment. Can you kindly review the add_stat() function in the dev version of gtsummary? We've made updates just for this situation. Please let me know if the updated function meets your needs. If it doesn't, perhaps we can update to accommodate.

**Comment by zachariae** [comment]
Hi, thank you for your hint. I will try this as soon as I am able to install the new dev version. At the moment, I have problems installing the broom.helpers from the github repository. But I have seen, that a new release version of this dependency is on the way?!

**Comment by ddsjoberg** [comment]
I am going to go ahead and close this issue. But please feel free to re-open if you want to discuss further.

**Comment by zachariae** [comment]
I would like to re-open this issue since I was not able to address my problem with the _add_stat()_ function.

![image](https://user-images.githubusercontent.com/22980643/109500729-e45e4b00-7a96-11eb-98aa-f492091fd7a4.png)

My goal is to create a table such as in the given example: In my opinion, an elegant way would be the give the statistic for categorical data like "{p}% ({cil}%-{cih}%)". The functions cil and cih could be defined using p, n, and N. 
Up to now, user-defined functions in the statistics are only allowed for  continuous variables: statistic = list(age ~ "{mean} ({sd}), {foo}").

But I think, it could be very helpful to define a special function for _all_categorical()_ that would  take the already allowed parameters p, n and N, and some additional constant parameters.

If I understand the add_stat() correctly, it is only possible to add one column with values for every row (level), or just one new value (label). 
But I want additional values for every cell from a kind of cross_table that has been realized using _tbl_summary()_.

Kind regards, Silke

**Comment by ddsjoberg** [comment]
Hi @zachariae 

I don't disagree with you that your suggestion would be help and indeed an elegant solution. I will, however, be frank, that that would require some large-ish re-arrangement of the internals of `tbl_summary()` and I don't have the time to dedicate for the update.

Here is the code I would use to create a table like you have given as an example.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.3.7.9000'

# 1. Define a function to calculate the CIs however you'd like
ci_fun <- function(data, variable, ...) {
  (table(data[[variable]]) / sum(table(data[[variable]]))) %>% 
    as.data.frame() %>%
    dplyr::mutate(
      # calculate CI howeve you'd like
      conf.low = Freq - 0.2,
      conf.high = Freq + 0.2,
    ) %>%
    dplyr::mutate_at(vars(Freq, conf.low, conf.high), ~style_number(., digits = 1, scale = 100)) %>%
    # combine results in a single column
    dplyr::mutate(stat = stringr::str_glue("{Freq} ({conf.low} - {conf.high})")) %>%
    dplyr::pull(stat)
}

# test the function
ci_fun(trial, "stage")
#> 26.5 (6.5 - 46.5)
#> 27.0 (7.0 - 47.0)
#> 21.5 (1.5 - 41.5)
#> 25.0 (5.0 - 45.0)

# 2. Create table
tbl <-
  trial %>%
  mutate(grade = paste("Grade", grade)) %>%
  select(grade, stage) %>%
  tbl_strata(
    strata = grade, 
    ~ tbl_summary(.x, statistic = stage ~ "{n}") %>%
      add_stat(
        fns = stage ~ ci_fun,
        location = stage ~ "level"
      ) %>%
      modify_header(
        list(stat_0 ~ "_n_", add_stat_1 ~ "_% (95% CI)_") 
      )
  ) %>%
  modify_footnote(everything() ~ NA)
```
![image](https://user-images.githubusercontent.com/26774684/109513794-72283f00-7a73-11eb-929c-c4fb0cb59837.png)

<sup>Created on 2021-03-01 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


Additional steps you could take to get the _exact_table:
1. To get the first column of n, use `tbl_merge()` to merge the big table with a single column table with n created using `tbl_summary()`.
2. To get the total row, you can use `tbl_stack()`.

**Comment by zachariae** [comment]
Thank you very much for your help. Unfortunately, I still not able to use the tbl_strata function since I am not able to install the dev-version of the package. However, I tried to change to code of the function in order to get the percentage per column instead of per row.

````
ci_fun_02 <- function(data, variable, row_totals = row_totals,...) {
  data.frame(n = as.vector(table(data[[variable]])),N = as.vector(row_totals)) %>% 
    as.data.frame() %>%
    dplyr::mutate(
      # calculate CI however you'd like
      p = n/N,
      conf.low = Hmisc::binconf(x=n,n = N, method = "wilson")[,2],
      conf.high = Hmisc::binconf(x=n,n = N, method = "wilson")[,3]
    ) %>%
    dplyr::mutate_at(vars(p, conf.low, conf.high), ~style_number(., digits = 1, scale = 100)) %>%
    # combine results in a single column
    dplyr::mutate(stat = stringr::str_glue("{p} ({conf.low} - {conf.high})")) %>%
    dplyr::pull(stat)
}

ci_fun_02(trial, "stage", row_totals = table(trial[["stage"]]))
````
I hope, that this could also work for the tbl_strata. I don't know, if there is a more elegant way to get the totals for the rows within the strata.

**Comment by ddsjoberg** [comment]
Great! Happy Programming 👩‍💻👨‍💻
