### ISSUE TITLE
 tbl_regression support for stats::nls model

### ISSUE THREAD

**Issue by raphidoc** [ddsjoberg/gtsummary#787]
stats::nls is supported by broom::tidy and could be added as vetted model.

For now getting error message: `Cannot identify variables. Quitting execution.`

I will be glad to help adding this feature.

**Comment by ddsjoberg** [comment]
@raphidoc , thank you for the post!

Can you please download the GitHub version of the broom.helpers package and try your model with broom.helpers::tidy_plus_plus()? I think some recent developments may have addressed this issue.

cc @larmarange

**Comment by larmarange** [comment]
Dear @ddsjoberg 

this is a particular case where it is not meaningful to attach a variable to a term because terms are not attached to a variable. See the example.

``` r
library(broom)
library(broom.helpers)

mod <- stats::nls(Petal.Width ~ a * Petal.Length - (Sepal.Width + Sepal.Length) / b + a^2, data = iris, start = list(a = 1, b = 1))
tidy(mod)
#> # A tibble: 2 x 5
#>   term  estimate std.error statistic  p.value
#>   <chr>    <dbl>     <dbl>     <dbl>    <dbl>
#> 1 a        0.429    0.0114      37.7 1.00e-77
#> 2 b       15.0      1.42        10.6 8.12e-20
tidy_plus_plus(mod)
#> x Unable to identify the list of variables.
#> 
#> This is usually due to an error calling `stats::model.frame(x)`or `stats::model.matrix(x)`.
#> It could be the case if that type of model does not implement these methods.
#> Rarely, this error may occur if the model object was created within
#> a functional programming framework (e.g. using `lappy()`, `purrr::map()`, etc.).
#> # A tibble: 2 x 17
#>   term  variable var_label var_class var_type var_nlevels contrasts
#>   <chr> <chr>    <chr>         <int> <chr>          <int> <chr>    
#> 1 a     a        a                NA unknown           NA <NA>     
#> 2 b     b        b                NA unknown           NA <NA>     
#> # ... with 10 more variables: contrasts_type <chr>, reference_row <lgl>,
#> #   label <chr>, estimate <dbl>, std.error <dbl>, statistic <dbl>,
#> #   p.value <dbl>, conf.low <dbl>, conf.high <dbl>, n <dbl>
tidy_plus_plus(mod, strict = TRUE)
#> x Unable to identify the list of variables.
#> 
#> This is usually due to an error calling `stats::model.frame(x)`or `stats::model.matrix(x)`.
#> It could be the case if that type of model does not implement these methods.
#> Rarely, this error may occur if the model object was created within
#> a functional programming framework (e.g. using `lappy()`, `purrr::map()`, etc.).
#> Error: Cannot identify variables. Quitting execution.
```

<sup>Created on 2021-02-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


So far:

- if we failed to attach a variable to a term, the value of `variable` is set to be equal to the value of `term`, `var_type` is then equal to unknown.
- if `quiet = FALSE`, we have a message but probably not relevant here
- if `strict = TRUE`, we have an error

To be noted that `tbl_regression()` apply `strict = TRUE`.

**What could be done in broom.helpers?**

- For such models, we could change `tidy_identidy_variables()` for displaying another message (i.e. "identifying variables not relevant for such model") and to not produce an error if `strict = TRUE`.
- A question would be: should we populate `variable` column with the content of `term` or should it be equal to `NA_character_`

For `broom.helpers`, the code is now generic enough. It will not produce any error in subsequent functions (see below). However, I do not know if it could be a problem in `gtsummary::tbl_regression()` or `GGally::ggcoef_model` to have only NA for variable column (maybe the code would need to be adapted)

``` r
x <- mod %>% tidy_and_attach() %>% tidy_identify_variables()
#> x Unable to identify the list of variables.
#> 
#> This is usually due to an error calling `stats::model.frame(x)`or `stats::model.matrix(x)`.
#> It could be the case if that type of model does not implement these methods.
#> Rarely, this error may occur if the model object was created within
#> a functional programming framework (e.g. using `lappy()`, `purrr::map()`, etc.).
x$variable <- NA_character_
x %>% 
  tidy_add_contrasts() %>% 
  tidy_add_reference_rows() %>%
  tidy_add_estimate_to_reference_rows() %>%
  tidy_add_variable_labels() %>%
  tidy_add_term_labels() %>%
  tidy_add_header_rows() %>%
  tidy_add_n() %>%
  tidy_remove_intercept() %>%
  tidy_add_coefficients_type()
#> # A tibble: 2 x 16
#>   term  variable var_label var_class var_type var_nlevels header_row contrasts
#>   <chr> <chr>    <chr>         <int> <chr>          <int> <lgl>      <chr>    
#> 1 a     <NA>     <NA>             NA unknown           NA NA         <NA>     
#> 2 b     <NA>     <NA>             NA unknown           NA NA         <NA>     
#> # ... with 8 more variables: contrasts_type <chr>, reference_row <lgl>,
#> #   label <chr>, estimate <dbl>, std.error <dbl>, statistic <dbl>,
#> #   p.value <dbl>, n <dbl>
```

<sup>Created on 2021-02-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by larmarange** [comment]
And additional question: are there other types of models that should be managed in a similar way?

**Comment by ddsjoberg** [comment]
Hey hey @larmarange ! If possible, I think it's best to always fill the variable column. When there is no `terms()` method and the true variable cannot be identified, we use the term as you indicated.  

I know for gsummary, we definitely need the variable column filled for all models. And I think this would be true to `broom.helpers` as well...any selector that uses variable names would have no way to select based on term if variable is NA.

**Comment by larmarange** [comment]
Thank you  @ddsjoberg  for your feedback. No problem to keep populating `variable` column.

What needs to be answered. For models like `stats::nls()`, when we fail to identify variables, if `strict = TRUE` an error is returned.  As a reminder, `gtsummary` calls `tidy_plus_plus()` with `strict = TRUE` cf. https://github.com/ddsjoberg/gtsummary/blob/814e921abbf0107e99f78a2fcb60816609bdf17a/R/utils-tbl_regression.R#L34

- an option is to be less restrictive in `tbl_regression` and to use `strict = FALSE`
- or in `broom.helpers` define a list of models for those it is expected that variable identification will fail

It is the case for other type of models, e.g. `cmprsk::crr` for whom we are not able to identify variables.

**Comment by ddsjoberg** [comment]
Instead of an error, perhaps a printed note that variables could not be determined instead of the error.  I like the idea of the list of models that do not error/print the message.

I would prefer to keep strict = TRUE in gtsummary because it catches other types of potential input error that are good to report to users. But I do think I could change to FALSE if needed.

**Comment by larmarange** [comment]
should be OK with https://github.com/larmarange/broom.helpers/pull/99

`tidy_identify_variables()` does not produce an error when identification fails as it could be the case for some models. `strict` argument remains for the other `tidy_*` functions.

**Comment by raphidoc** [comment]
Thank to both of you for taking time to look at this issue !

I've just change for `strict = F` in utils-tbl_regression.R and it work fine for my purpose.

Regarding the way to properly implement this, I think it would be more clear to add a list of model in `broom.helpers ` to skip variable identification (as it is not relevant with those).

**Comment by raphidoc** [comment]
@larmarange will test with [larmarange/broom.helpers#99](larmarange/broom.helpers#99) right now !

**Comment by larmarange** [comment]
With that pull request, `gtsummary::tbl_regression()` works as expected.

``` r
mod <- stats::nls(
  Petal.Width ~ a * Petal.Length - (Sepal.Width + Sepal.Length) / b + a^2,
  data = iris,
  start = list(a = 1, b = 1)
)
library(gtsummary)
mod %>% tbl_regression()
#> x Unable to identify the list of variables.
#> 
#> This is usually due to an error calling `stats::model.frame(x)`or `stats::model.matrix(x)`.
#> It could be the case if that type of model does not implement these methods.
#> Rarely, this error may occur if the model object was created within
#> a functional programming framework (e.g. using `lappy()`, `purrr::map()`, etc.).
```

![image](https://user-images.githubusercontent.com/966307/108110908-40d36a80-7094-11eb-8cb8-c7a433b1a9ac.png)


<sup>Created on 2021-02-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by ddsjoberg** [comment]
Fantastic!

**Comment by raphidoc** [comment]
Work's fine for me !

Thanks a lot @larmarange  and @ddsjoberg !

Is it the time to close the issue ?

**Comment by ddsjoberg** [comment]
Thank you @larmarange for the always quick attention!
