### ISSUE TITLE
RR in tbl_regression header

### ISSUE THREAD

**Issue by zongell-star** [ddsjoberg/gtsummary#788]
Hello,

I am running the tbl_regression for a gee model with a log link to obtain the relative risk. 

The table header for relative risk states "exp(Beta)" - how can I change this to show "RR"? 

gee2 <- geeglm(y ~ treatment + days_since_download + age + AUDIT_score_cat + treatment*days_since_download, id=ID, data=PO_final, family=binomial(link="log"), corstr="independence")

tbl_regression(gee2, exponentiate = TRUE)
Thanks.

**Comment by ddsjoberg** [comment]
hey @zongell-star , you can use the `modify_header()` function to change the column headers

**Comment by zongell-star** [comment]
Thanks - found your tutorial, which made it clear

http://www.danieldsjoberg.com/gtsummary/reference/modify.html

**Comment by ddsjoberg** [comment]
Great, glad that page was helpful.

In the future, when you have questions about how to use the package, please post to stackoverflow.com, use the gtsummary tag, and I will be notified of your post.

Users search SO for help more often than GH. Thanks!
