### ISSUE TITLE
Combining Odds Ratios, Confidence Intervals, and P-Value Star + Suggested Journals for Clinical Psychology/Epidimiology

### ISSUE THREAD

**Issue by gjones1219** [ddsjoberg/gtsummary#789]
In the next version of gtsummary, it would be great if you could create tbl_regression templates for (logistic) regression model outputs that would be relevant for clinical psychology/psychiatry. Specifically, creating an output that:

1. Combines odds ratios/adjusted odds ratios and confidence intervals into a single column
2. Reports p-values using starring to indicate the significance level (i.e * = p<0.05, ** = p<0.01, *** = p<0.001)
3. Bolds significant aORs (with the confidence intervals and stars bolded as well)

Here are some journals that would be amenable to this formatting. These journals do not require this formatting per se, but key papers I've seen published in these outlets have applied much of this formatting. It also supports readability across many similar journals as well. The example journals are:

-JAMA Psychiatry (aORs and Confidence Intervals in One Column, P-Values in Separate Column).
-Clinical Psychological Science 
-Journal of Psychopharmacology 
-Addiction 
-Drug and Alcohol Dependence

Lastly, it would be great to create a feature that easily lets one switch between the P-value star format versus a separate column for p-values when using these journal templates (also would be great to have this feature generally). Would also be great to have a function that lets one easily switch between aORs and Confidence Intervals being in one column versus being separate.

Thanks so much!

**Comment by ddsjoberg** [comment]
Awesome 😎 Do any of these journals have published reporting guidelines suggesting these formats? Or is more a culture of the journal to have most model formats like you've suggested. 

If there are guidelines, can you link to them? If not, can you link to a few articles using the suggested format?

**Comment by zachariae** [comment]
The American Psychological Association has its own publishing guidelines: I found this R-package for APA-styled tables https://cran.microsoft.com/snapshot/2018-08-09/web/packages/apaTables/vignettes/apaTables.html. However, the guidelines themselves (or the book that cover them) are not free of charge.

**Comment by gjones1219** [comment]
Papers:
-https://journals.sagepub.com/doi/10.1177/0269881114565653
-https://jamanetwork.com/journals/jamapsychiatry/fullarticle/2763444
-https://www.sciencedirect.com/science/article/pii/S0376871620300594
-https://pubmed.ncbi.nlm.nih.gov/31797462/

**Comment by ddsjoberg** [comment]
hey hey @gjones1219 !

I implemented a JAMA Psychiatry theme in pull request https://github.com/ddsjoberg/gtsummary/pull/830 . What do you think? Can it be improved? The other related themes (including those with significance stars) follow a similar implementation, and can easily be added.

Thanks for your attention


``` r
library(gtsummary)
theme_gtsummary_journal("jama_psychiatry")
#> Setting `JAMA Psychiatry` theme

tbl1 <-
  lm(time ~ ph.ecog + sex, survival::lung) %>%
  tbl_regression(label = list(ph.ecog = "ECOG Score", sex = "Sex"))
```

![image](https://user-images.githubusercontent.com/26774684/112719306-af46ec00-8ece-11eb-836a-fe2a853140d2.png)

```r
tbl2 <-
  trial %>%
  select(response, age, grade) %>%
  tbl_uvregression(
    y = response, 
    method = glm,
    method.args = list(family = binomial),
    exponentiate = TRUE
  )
```

![image](https://user-images.githubusercontent.com/26774684/112719320-c84f9d00-8ece-11eb-9716-18ecf2f5500b.png)

<sup>Created on 2021-03-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by ddsjoberg** [comment]
hey hey @gjones1219 !

I added the JAMA Psychiatry, and I think have implemented everything you'd need to create the other themes.  Here's an example, 

```r
tbl <- 
  lm(time ~ ph.ecog + sex, survival::lung) %>%
  tbl_regression(label = list(ph.ecog = "ECOG Score", sex = "Sex")) %>%
  # add sig stars, and combine CI and coef into single column
  add_significance_stars(
    pattern = "{estimate} ({conf.low}, {conf.high}){stars}",
    hide_se = TRUE
  ) %>%
  # bold coef and CI if significant
  modify_table_styling(
    columns = estimate,
    rows = p.value < 0.05,
    text_format = "bold"
  )
```

![image](https://user-images.githubusercontent.com/26774684/112763761-d9ce9d00-8fd3-11eb-9bf4-c024b22ea690.png)

Look into source code for journal themes `"qjecon"` and `"jama_psychiatry"` for reference in writing the others.
https://github.com/ddsjoberg/gtsummary/blob/5fc80a50be4cf74dc980e6b145338aa3d776c3fb/R/theme_gtsummary.R#L147

I'd be happy to add the other journal themes when you submit a pull request.

Thank you for opening this issue and helping the development along!

**Comment by gjones1219** [comment]
Wow thank you so much! Should I download the latest version from Github to
gain this functionality?

Appreciate your letting me know and thanks so much.

Grant

**Comment by ddsjoberg** [comment]
yep, install the latest version from github and you'll have this functionality.  we expect to the next CRAN release in a couple of weeks

**Comment by gjones1219** [comment]
Perfect thanks and feel free to let me know when the CRAN release is out
(if you want!). Thank you so much for this awesome work, so appreciate it!

Grant

**Comment by ddsjoberg** [comment]
if you need notifications for releases, you can "watch" the github repo

**Comment by gjones1219** [comment]
Thanks.

G

**Comment by ddsjoberg** [comment]
Hey @gjones1219 !

I was reviewing the JAMA theme (not the JAMA Psychiatry theme) to see if there were any parts that should be updated with the new functionalities that have been introduced in recent versions. I think we may not need the JAMA Psychiatry theme, because everything can just go in JAMA. I updated JAMA...let me know if we need something else
