### ISSUE TITLE
columns for pairwise comparisons between groups?

### ISSUE THREAD

**Issue by arbet003** [ddsjoberg/gtsummary#790]
Hello,

I am wondering if there are any plans in the future to allow for pairwise comparisons between >2 groups when using the by argument in tbl_summary?  For example, if there are 3 groups, you could have 3 columns each reporting p-values for all pairwise comparisons between the groups, e.g. pairwise t-tests or rank tests for numeric variables, pairwise chisquare or fisher's exact tests for categorical variables?

I realize with a lot of groups, this would result in a ton of columns... but I think it would still be useful if one has a small number of groups. 

There could be a lot of customization with this as well.  For example, reporting differences in means or proportions, with confidence intervals for the differences.  Or including letters to identify groups whose mean (or proportion) does not significantly differ using some threshold. 

EDIT:  I see there was a similar post in July 2020 https://github.com/ddsjoberg/gtsummary/issues/570  I will try this solution for now, but curious if there are plans to help automate this in the future.

Thanks

**Comment by ddsjoberg** [comment]
Hey @arbet003 ! Thank you for the post!

We still do not have this on the to do list. But we have improved the `add_stat()` function to make creating custom tables pretty easy. You'll need to install the dev version of gtsummary for this to work.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.3.6.9013'
library(tidyverse)


# define a pairwise test in the gtsummary format to calculate pairwise p-values
gts_pairwise.t.test <- function(data, variable, by, ...) {
  pairwise.t.test(data[[variable]], data[[by]]) %>% 
    broom::tidy() %>%
    mutate(label = glue::glue("**{group2} vs. {group1}**")) %>%
    select(label, p.value) %>%
    spread(label, p.value)
}

# test function
gts_pairwise.t.test(trial, "age", "grade")
#> # A tibble: 1 x 3
#>   `**I vs. II**` `**I vs. III**` `**II vs. III**`
#>            <dbl>           <dbl>            <dbl>
#> 1              1               1                1

trial %>%
  select(age, marker, grade) %>%
  # create summary table split by Grade
  tbl_summary(
    by = grade,
    missing = "no",
    statistic = everything() ~ "{mean} ({sd})"
  ) %>%
  # add pairwise comparisons
  add_stat(fns = everything() ~ gts_pairwise.t.test) %>%
  modify_fmt_fun(c('**I vs. II**', '**I vs. III**', '**II vs. III**') ~ style_pvalue) %>%
  # convert to kable to display on github
  as_kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>I</strong>, N = 68</th>
<th style="text-align: left;"><strong>II</strong>, N = 68</th>
<th style="text-align: left;"><strong>III</strong>, N = 64</th>
<th style="text-align: left;"><strong>I vs. II</strong></th>
<th style="text-align: left;"><strong>I vs. III</strong></th>
<th style="text-align: left;"><strong>II vs. III</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: left;">46 (15)</td>
<td style="text-align: left;">48 (14)</td>
<td style="text-align: left;">48 (14)</td>
<td style="text-align: left;">&gt;0.9</td>
<td style="text-align: left;">&gt;0.9</td>
<td style="text-align: left;">&gt;0.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marker Level (ng/mL)</td>
<td style="text-align: left;">1.07 (0.89)</td>
<td style="text-align: left;">0.68 (0.73)</td>
<td style="text-align: left;">1.00 (0.92)</td>
<td style="text-align: left;">0.031</td>
<td style="text-align: left;">0.6</td>
<td style="text-align: left;">0.079</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-02-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by ddsjoberg** [comment]
I am going to go ahead and close this issue. But please feel free to re-open if you want to discuss further.

**Comment by stevenyan0127** [comment]
Hi, @ddsjoberg. Is there a function that compares the difference in categorical groups?

**Comment by ddsjoberg** [comment]
@stevenyan0127 did you just post this question to SO as well? https://stackoverflow.com/questions/76157843

If so, please keep posts to one platform on SO.

**Comment by stevenyan0127** [comment]
@ddsjoberg Hi, yes, I posted on stackoverflow too. I'm struggling to write a function for categorical groups.

**Comment by stevenyan0127** [comment]
@ddsjoberg I did not post this original question, I just found it on github, and since this question was closed. I thought I would ask on stackoverflow. Anyways, thank you for your reply. I'm still trying to write a function for categorical groups, have you had any luck writing one?

**Comment by lucavd** [comment]
Hi Daniel,
I reopen this to report an issue. I followed your examples here and on StackOverflow, but I encountered an issue when applying it to a table that has both categorical and continuous data.

```
add_stat_pairwise <- function(data, variable, by, ...) {
  # calculate pairwise p-values
  pw <- pairwise.wilcox.test(as.numeric(data[[variable]]), data[[by]], p.adj = "fdr")
  
  # convert p-values to list
  index <- 0L
  p.value.list <- list()
  for (i in seq_len(nrow(pw$p.value))) {
    for (j in seq_len(nrow(pw$p.value))) {
      index <- index + 1L
      
      p.value.list[[index]] <- 
        c(pw$p.value[i, j]) %>%
        setNames(glue::glue("**{colnames(pw$p.value)[j]} vs. {rownames(pw$p.value)[i]}**"))
    }
  }
  
  # convert list to data frame
  p.value.list %>% 
    unlist() %>%
    purrr::discard(is.na) %>%
    t() %>%
    as.data.frame() %>%
    # formatting/rounding p-values
    dplyr::mutate(dplyr::across(everything(), style_pvalue))
}
```

Here
` pw <- pairwise.wilcox.test(as.numeric(data[[variable]]), data[[by]], p.adj = "fdr") ` 
It seems that I can work only with a type of data (and test), and if I use on something like this

```
#NOT RUN  
results <- map(strata, ~ dati_fail |> 
  select(all_of(fail_outcomes), .x) |>  
  tbl_summary(by = .x) |> 
  add_p(test.args = all_tests("fisher.test") ~ list(simulate.p.value = TRUE)) %>% 
  add_q() |> 
  add_stat(everything() ~ add_stat_pairwise) |> 
  modify_spanning_header(all_stat_cols() ~ glue::glue("**{.x}**"))) 

results
```
I have to be sure that all the variables in the dataframe are of the same type.

**Comment by lucavd** [comment]
I came up to something like that but it is too complicated to me. Maybe you have a more elegant solution (like the way `tbl_summary` decides how to treat a variable). And this doesn't work everytime...

```
library(dplyr)
library(purrr)
library(glue)
library(stats)
library(tidyr)

style_pvalue <- function(p) {
  ifelse(p < 0.001, "< 0.001", format(p, digits = 2, scientific = FALSE))
}

# Define the generalized function
add_stat_pairwise <- function(data, variable, by, ...) {
  if (is.numeric(data[[variable]])) {
    # Pairwise Wilcoxon test for continuous variables
    pw <- pairwise.wilcox.test(as.numeric(data[[variable]]), data[[by]], p.adj = "fdr")
    
    # Convert p-values to a tidy data frame
    p_values_df <- as.data.frame(as.table(pw$p.value))
    
    # Format p-values
    formatted_p_values <- p_values_df %>%
      filter(!is.na(Freq)) %>%
      mutate(
        comparison = glue("**{Var1} vs. {Var2}**"),
        formatted_p = style_pvalue(Freq)
      ) %>%
      select(comparison, formatted_p) %>%
      spread(key = comparison, value = formatted_p)
    
    return(formatted_p_values)
    
  } else if (is.factor(data[[variable]]) || is.character(data[[variable]])) {
    # Fisher's exact test for categorical variables
    levels <- unique(data[[by]])
    n <- length(levels)
    
    p.value.matrix <- matrix(NA, nrow = n, ncol = n,
                             dimnames = list(levels, levels))
    
    for (i in seq_len(n - 1)) {
      for (j in seq(i + 1, n)) {
        tbl <- table(data[[variable]][data[[by]] %in% c(levels[i], levels[j])],
                     data[[by]][data[[by]] %in% c(levels[i], levels[j])])
        p.value.matrix[i, j] <- fisher.test(tbl)$p.value
      }
    }
    
    # Convert p-values to list
    p.value.list <- p.value.matrix %>%
      as.data.frame() %>%
      rownames_to_column(var = "Var1") %>%
      gather(key = "Var2", value = "p.value", -Var1) %>%
      filter(!is.na(p.value)) %>%
      mutate(comparison = glue("**{Var2} vs. {Var1}**")) %>%
      select(comparison, p.value) %>%
      mutate(p.value = style_pvalue(p.value)) %>%
      spread(key = comparison, value = p.value)
    
    return(p.value.list)
  } else {
    stop("Variable type not supported.")
  }
}

# Test the generalized function
test_add_stat_pairwise <- function() {
  # Create sample dataset
  set.seed(123)
  data <- data.frame(
    continuous_var = rnorm(100),
    categorical_var = sample(c("A", "B", "C"), 100, replace = TRUE),
    group = sample(c("X", "Y", "Z"), 100, replace = TRUE)
  )
  
  # Test with continuous variable
  continuous_results <- add_stat_pairwise(data, "continuous_var", "group")
  print("Continuous variable results:")
  print(continuous_results)
  
  # Test with categorical variable
  categorical_results <- add_stat_pairwise(data, "categorical_var", "group")
  print("Categorical variable results:")
  print(categorical_results)
}

# Run the test function
test_add_stat_pairwise()
```
