### ISSUE TITLE
tbl_summary incorrectly renders footer for github_document

### ISSUE THREAD

**Issue by ercbk** [ddsjoberg/gtsummary#795]
When rendering the github_document md file, there's a extra space created in the html between the style and the footer text, and it causes the footer to be rendered incorrectly.  

![tbl-summary-footer](https://user-images.githubusercontent.com/25374582/108860517-42cd8a00-75bc-11eb-8866-6f0a41e109ba.png)

``` r
library(dplyr, warn.conflicts = F)
library(readr)
library(gtsummary)
library(gt)
bvc <- read_csv("https://raw.githubusercontent.com/ercbk/Indiana-COVID-19-Tracker/master/data/beds-vents-complete.csv")
#> 
#> -- Column specification --------------------------------------------------------
#> cols(
#>   date = col_date(format = ""),
#>   beds_icu_total = col_double(),
#>   beds_icu_occupied_covid_19 = col_double(),
#>   beds_available_icu_beds_total = col_double(),
#>   vents_total = col_double(),
#>   vents_all_use_covid_19 = col_double(),
#>   vents_non_covid_pts_on_vents = col_double(),
#>   vents_all_available_vents_not_in_use = col_double()
#> )


tbl_summary(bvc,
            missing = "ifany",
            missing_text = "Missing")
#> Column(s) 'date' omitted from output.
#> Accepted classes are 'character', 'factor', 'numeric', 'logical', 'integer', or 'difftime'.
```

<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#azqaekjuoe .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#azqaekjuoe .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#azqaekjuoe .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#azqaekjuoe .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#azqaekjuoe .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#azqaekjuoe .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#azqaekjuoe .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#azqaekjuoe .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#azqaekjuoe .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#azqaekjuoe .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#azqaekjuoe .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#azqaekjuoe .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#azqaekjuoe .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#azqaekjuoe .gt_from_md > :first-child {
  margin-top: 0;
}

#azqaekjuoe .gt_from_md > :last-child {
  margin-bottom: 0;
}

#azqaekjuoe .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#azqaekjuoe .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#azqaekjuoe .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#azqaekjuoe .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#azqaekjuoe .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#azqaekjuoe .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#azqaekjuoe .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#azqaekjuoe .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#azqaekjuoe .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#azqaekjuoe .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#azqaekjuoe .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#azqaekjuoe .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#azqaekjuoe .gt_left {
  text-align: left;
}

#azqaekjuoe .gt_center {
  text-align: center;
}

#azqaekjuoe .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#azqaekjuoe .gt_font_normal {
  font-weight: normal;
}

#azqaekjuoe .gt_font_bold {
  font-weight: bold;
}

#azqaekjuoe .gt_font_italic {
  font-style: italic;
}

#azqaekjuoe .gt_super {
  font-size: 65%;
}

#azqaekjuoe .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="azqaekjuoe" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>N = 283</strong><sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_left">beds_icu_total</td>
      <td class="gt_row gt_center">2,233 (2,162, 2,400)</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">beds_icu_occupied_covid_19</td>
      <td class="gt_row gt_center">365 (267, 548)</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">beds_available_icu_beds_total</td>
      <td class="gt_row gt_center">807 (598, 954)</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">vents_total</td>
      <td class="gt_row gt_center">2,890 (2,803, 2,910)</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">vents_all_use_covid_19</td>
      <td class="gt_row gt_center">141 (87, 248)</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">vents_non_covid_pts_on_vents</td>
      <td class="gt_row gt_center">447 (412, 468)</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">vents_all_available_vents_not_in_use</td>
      <td class="gt_row gt_center">2,314 (2,110, 2,417)</td>
    </tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="2">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          Median (IQR)
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table></div>

<sup>Created on 2021-02-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.3 (2020-10-10)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/New_York            
#>  date     2021-02-23                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package       * version    date       lib source                          
#>  assertthat      0.2.1      2019-03-21 [1] CRAN (R 4.0.2)                  
#>  backports       1.2.1      2020-12-09 [1] CRAN (R 4.0.3)                  
#>  broom.helpers   1.1.0      2020-11-24 [1] RSPM (R 4.0.3)                  
#>  checkmate       2.0.0      2020-02-06 [1] CRAN (R 4.0.2)                  
#>  cli             2.3.0      2021-01-31 [1] RSPM (R 4.0.3)                  
#>  colorspace      2.0-0      2020-11-11 [1] CRAN (R 4.0.3)                  
#>  commonmark      1.7        2018-12-01 [1] CRAN (R 4.0.2)                  
#>  crayon          1.4.1      2021-02-08 [1] RSPM (R 4.0.3)                  
#>  curl            4.3        2019-12-02 [1] CRAN (R 4.0.2)                  
#>  DBI             1.1.1      2021-01-15 [1] CRAN (R 4.0.3)                  
#>  digest          0.6.27     2020-10-24 [1] CRAN (R 4.0.3)                  
#>  dplyr         * 1.0.4      2021-02-02 [1] RSPM (R 4.0.3)                  
#>  ellipsis        0.3.1      2020-05-15 [1] CRAN (R 4.0.2)                  
#>  evaluate        0.14       2019-05-28 [1] CRAN (R 4.0.2)                  
#>  forcats         0.5.1      2021-01-27 [1] RSPM (R 4.0.3)                  
#>  fs              1.5.0      2020-07-31 [1] CRAN (R 4.0.2)                  
#>  generics        0.1.0      2020-10-31 [1] CRAN (R 4.0.3)                  
#>  ggplot2         3.3.3      2020-12-30 [1] CRAN (R 4.0.3)                  
#>  glue            1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                  
#>  gt            * 0.2.2      2020-08-05 [1] CRAN (R 4.0.2)                  
#>  gtable          0.3.0      2019-03-25 [1] CRAN (R 4.0.2)                  
#>  gtsummary     * 1.3.6      2021-01-08 [1] RSPM (R 4.0.3)                  
#>  highr           0.8        2019-03-20 [1] CRAN (R 4.0.2)                  
#>  hms             1.0.0      2021-01-13 [1] CRAN (R 4.0.3)                  
#>  htmltools       0.5.1.1    2021-01-22 [1] RSPM (R 4.0.3)                  
#>  knitr           1.31       2021-01-27 [1] RSPM (R 4.0.3)                  
#>  lattice         0.20-41    2020-04-02 [2] CRAN (R 4.0.3)                  
#>  lifecycle       0.2.0      2020-03-06 [1] CRAN (R 4.0.2)                  
#>  magrittr        2.0.1      2020-11-17 [1] CRAN (R 4.0.3)                  
#>  Matrix          1.2-18     2019-11-27 [2] CRAN (R 4.0.3)                  
#>  munsell         0.5.0      2018-06-12 [1] CRAN (R 4.0.2)                  
#>  pillar          1.4.7      2020-11-20 [1] CRAN (R 4.0.3)                  
#>  pkgconfig       2.0.3      2019-09-22 [1] CRAN (R 4.0.2)                  
#>  ps              1.5.0      2020-12-05 [1] CRAN (R 4.0.3)                  
#>  purrr           0.3.4      2020-04-17 [1] CRAN (R 4.0.2)                  
#>  R6              2.5.0      2020-10-28 [1] CRAN (R 4.0.3)                  
#>  readr         * 1.4.0.9000 2020-11-20 [1] Github (tidyverse/readr@97186a8)
#>  reprex          1.0.0      2021-01-27 [1] RSPM (R 4.0.3)                  
#>  rlang           0.4.10     2020-12-30 [1] CRAN (R 4.0.3)                  
#>  rmarkdown       2.6        2020-12-14 [1] CRAN (R 4.0.3)                  
#>  rstudioapi      0.13       2020-11-12 [1] CRAN (R 4.0.3)                  
#>  sass            0.3.1      2021-01-24 [1] RSPM (R 4.0.3)                  
#>  scales          1.1.1      2020-05-11 [1] CRAN (R 4.0.2)                  
#>  sessioninfo     1.1.1      2018-11-05 [1] CRAN (R 4.0.2)                  
#>  stringi         1.5.3      2020-09-09 [1] CRAN (R 4.0.3)                  
#>  stringr         1.4.0      2019-02-10 [1] CRAN (R 4.0.2)                  
#>  styler          1.3.2      2020-02-23 [1] CRAN (R 4.0.2)                  
#>  survival        3.2-7      2020-09-28 [2] CRAN (R 4.0.3)                  
#>  tibble          3.0.6      2021-01-29 [1] RSPM (R 4.0.3)                  
#>  tidyr           1.1.2      2020-08-27 [1] CRAN (R 4.0.2)                  
#>  tidyselect      1.1.0      2020-05-11 [1] CRAN (R 4.0.2)                  
#>  usethis         2.0.1      2021-02-10 [1] RSPM (R 4.0.3)                  
#>  vctrs           0.3.6      2020-12-17 [1] CRAN (R 4.0.3)                  
#>  withr           2.4.1      2021-01-26 [1] RSPM (R 4.0.3)                  
#>  xfun            0.21       2021-02-10 [1] RSPM (R 4.0.3)                  
#>  yaml            2.2.1      2020-02-01 [1] CRAN (R 4.0.2)                  
#> 
#> [1] C:/Users/tbats/Documents/R/win-library/4.0
#> [2] C:/Program Files/R/R-4.0.3/library
```

</details>

**Comment by ddsjoberg** [comment]
Hi @ercbk ! Thanks for the report. I think this is due to an outstanding issue in the gt package. Can you please confirm whether this is gt it gtsummary specific?

**Comment by ercbk** [comment]
Yep, guess so. Guess I'll head over there. Thx.
