### ISSUE TITLE
Missing levels across models makes it difficult to determine reference group tbl_merge

### ISSUE THREAD

**Issue by michaelcurry1123** [ddsjoberg/gtsummary#81]
I wanted to see what would happen if you ran a model with all levels and then removed one of the levels in a separate model and then used tbl_merge to look at both models.  Both the missing level and the reference group get a dashed line which makes it difficult to determine which one is the reference and which is the missing level.  Should the missing level just be blank instead of dashed?

```
library(survival)
library(gtsummary)
library(dplyr)


lung2 <- mutate(lung, stat = ifelse(status==2,0,1),
                ph.ecog = as.character(ph.ecog))

moda <-   glm(stat ~ ph.ecog,family = binomial, data =lung2) %>% 
          tbl_regression()

lung3 <- lung2 %>% 
         filter(ph.ecog != 3) %>% 
         mutate(ph.ecog = as.character(ph.ecog))

modb <-   glm(stat ~ ph.ecog,family = binomial, data =lung3) %>% 
  tbl_regression()

gtsummary::tbl_merge(tbls = list(moda,modb), tab_spanner = c("1", "s"))
```
![image](https://user-images.githubusercontent.com/30420015/56367691-d74a5280-61c3-11e9-8acc-2330f0b6a5cf.png)

**Comment by ddsjoberg** [comment]
I definitely hadn't thought of this one :) You're so so good.

I think the only way to get around this is to add a column to `tbl_regression` results indicating whether the row is a reference row.  I'll work on this one....I think it'll be a somewhat involved update
