### ISSUE TITLE
Tips and Tricks Vignette

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#811]

**Comment by ddsjoberg** [comment]
Maybe convert the gallery of tables into a FAQ/tips and tricks...

The top will list all the Qs (or phrase a tip as a Q), and link the to the tables below. That will help with linking to specific tables as well.

**Comment by ddsjoberg** [comment]
Hey hey @larmarange , the table gallery vignette has been converted to a FAQ, which will make it easier to add other tips and tricks.
https://www.danieldsjoberg.com/gtsummary/dev/articles/gallery.html

**Comment by larmarange** [comment]
That's awesome!!! Thanks a lot

PS: sorry for not having being very active these last weeks

**Comment by larmarange** [comment]
Quick question: do you think that the questions should be repeated in the main text? It would facilitate the reading.

**Comment by ddsjoberg** [comment]
> Quick question: do you think that the questions should be repeated in the main text? It would facilitate the reading.

@larmarange we included a brief description above the example tables explaining the modifications in the table. If we had a one Question to one Example Table, repeating the question would be perfect. But we have multiple questions linking to the same examples, so I think we'll just stick with the brief description for now.

**Comment by larmarange** [comment]
ok thanks for the clarification
