### ISSUE TITLE
IQR is the DIFFERENCE between 3rd and 1st quartiles

### ISSUE THREAD

**Issue by sdchasalow** [ddsjoberg/gtsummary#827]
Using "IQR" as a standard label when you actually display the individual 1st and 3rd quartiles is really really bad. It just encourages and reinforces the already all-too-common misunderstanding and misuse of the term "IQR".

**Comment by ddsjoberg** [comment]
Hi @sdchasalow ! Thanks for sharing your opinion on the matter. 

I am aware the precise definition of IQR, and prefer to use IQR to label Q1 and Q3. The labelling can of course be changed in your tables.

**Comment by sdchasalow** [comment]
“When I use a word,’ Humpty Dumpty said in rather a scornful tone, ‘it means just what I choose it to mean — neither more nor less.’

’The question is,’ said Alice, ‘whether you can make words mean so many different things.’

’The question is,’ said Humpty Dumpty, ‘which is to be master — that’s all.”

― Lewis Carroll, Through the Looking Glass

Curiouser and curiouser... of course you may do whatever you like. But to prefer to mislead people is an interesting choice.
