### ISSUE TITLE
Add N and R^2 for linear models 

### ISSUE THREAD

**Issue by albertostefanelli** [ddsjoberg/gtsummary#839]
tbl_regression() might benefit from displaying N and R^2 for lm() and glm(family=gaussian)

**Comment by ddsjoberg** [comment]
Hi @albertostefanelli ! Thanks you for the comment!

To add these statistics as a table source note, you can use `add_glance_sournce_note()` and `add_glance_table()` adds them to the bottom of the regression table.
http://www.danieldsjoberg.com/gtsummary/dev/reference/add_glance.html

You can also add a new column of N with `add_n()` 
http://www.danieldsjoberg.com/gtsummary/dev/reference/add_n_regression.html

 `add_glance_table()` and  `add_n()` are available in the dev version of gtsummary that will be release in a couple of weeks.

Does that work for you?

**Comment by ddsjoberg** [comment]
hey @albertostefanelli , I am going to go ahead and close this issue. please feel free if you'd like to discuss further!

FYI, you can also add the N with `modify_header()` and `modify_spanning_header()`
