### ISSUE TITLE
{gt} tables in help files (cont.)

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#84]
@karissawhiting putting the comments from #83 in this issue to keep track. 

1. We should shorten the `tbl_summary` table examples (and perhaps others). Also, two examples should be sufficient (rather than the three we have). With fewer examples and shorter tables, the space between example code and the rest of the help file will be shorter. 
1. Rather than call the section "Figures", perhaps we should call it "Example Output"? That may help people understand more easily that these are the output tables.
1. Is there a way to make a separation between two example tables? 

What do you think?

**Comment by karissawhiting** [comment]
1. Agree that shortening some of the docs would be good! Do you think we should remove some examples completely, or just have only one or two of them actually evaluate to figures (and leave the rest in the doc example section unevaluated)?
2. I like it. 
3. What kind of separation did you have in mind? Whitespace, or a line?

**Comment by ddsjoberg** [comment]
1. Great, I made a branch called "#84-help_files" (https://github.com/ddsjoberg/gtsummary/tree/%2384-help_files) where we can make the updates.  I'll get started on shortening the table output for the files that have long output.
1. :)
1. I don't know what we can add as separation.  Maybe just some text that says "Example 1"?

**Comment by ddsjoberg** [comment]
I updated the `tbl_summary` with the codes below.  I tried to change the widths of the output tables, so the fonts are the same size.  Can you install this version and take a look?  Should we make any other changes (before I go through and make a ton of updates)?

```
#' @section Example Output:
#' \if{html}{Example 1}
#'
#' \if{html}{\figure{tbl_summary_ex1.png}{options: width=40\%}}
#'
#' \if{html}{Example 2}
#'
#' \if{html}{\figure{tbl_summary_ex2.png}{options: width=55\%}}
```

**Comment by karissawhiting** [comment]
I think that looks great

**Comment by ddsjoberg** [comment]
I made a first pass at all of the help files.  We can continue to update along the way if we see a file that could use it :)
