### ISSUE TITLE
Update SO answers based on 1.4.0 release....most items we said could not be done are now possible

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#865]
- [x] https://stackoverflow.com/questions/66893532 2021-03-31 Moses
- [x] https://stackoverflow.com/questions/66885963 2021-03-31 Moses
- [x] https://stackoverflow.com/questions/66846316 2021-03-28 Jasmine
- [x] https://stackoverflow.com/questions/66835663 2021-03-27 Erin Giles
- [x] https://stackoverflow.com/questions/66814238 2021-03-26 binyam girma
- [x] https://stackoverflow.com/questions/66670806 2021-03-17 Michael Corrigan
- [x] https://stackoverflow.com/questions/66588374 2021-03-11 user15377786
- [x] https://stackoverflow.com/questions/66567212 2021-03-10 bee
- [x] https://stackoverflow.com/questions/66553702 2021-03-09 Elliott Chinn
- [x] https://stackoverflow.com/questions/66552227 2021-03-09 Joe Crozier
- [x] https://stackoverflow.com/questions/66366115 2021-02-25 Yannick Binois
- [x] https://stackoverflow.com/questions/66519349 2021-03-07 Kellan Baker
- [x] https://stackoverflow.com/questions/66507126 2021-03-06 ebay
- [x] https://stackoverflow.com/questions/66493847 2021-03-05 Cristiano
- [x] https://stackoverflow.com/questions/66483775 2021-03-04 Cristiano
- [x] https://stackoverflow.com/questions/66474960 2021-03-04 B_slash_
- [x] https://stackoverflow.com/questions/66388681 2021-02-26 Cristiano
- [x] https://stackoverflow.com/questions/66351409 2021-02-24 mahol
- [x] https://stackoverflow.com/questions/66348684 2021-02-24 Nelly
- [x] https://stackoverflow.com/questions/66294935 2021-02-20 Kellan Baker
- [x] https://stackoverflow.com/questions/66287968 2021-02-19 sk454
- [x] https://stackoverflow.com/questions/66270637 2021-02-18 Kellan Baker
- [x] https://stackoverflow.com/questions/66262072 2021-02-18 GMJ
- [x] https://stackoverflow.com/questions/66203133 2021-02-15 Alfonso Al
- [x] https://stackoverflow.com/questions/66201850 2021-02-14 Kellan Baker
- [x] https://stackoverflow.com/questions/66190482 2021-02-13 Alfonso Al
- [x] https://stackoverflow.com/questions/66175868 2021-02-12 Nelly
- [x] https://stackoverflow.com/questions/66147951 2021-02-10 tskstkw
- [x] https://stackoverflow.com/questions/66131469 2021-02-10 arbetj
- [x] https://stackoverflow.com/questions/66135460 2021-02-10 TarJae
- [x] https://stackoverflow.com/questions/66119997 2021-02-09 TarJae
- [x] https://stackoverflow.com/questions/66093896 2021-02-07 GMJ
- [x] https://stackoverflow.com/questions/61360954 2020-04-22 Nelly
- [x] https://stackoverflow.com/questions/65882941 2021-01-25 Benjamin Moran
- [x] https://stackoverflow.com/questions/64037898 2020-09-23 NewBee
- [x] https://stackoverflow.com/questions/65767331 2021-01-17 matr
- [x] https://stackoverflow.com/questions/65769674 2021-01-18 matr
- [x] https://stackoverflow.com/questions/65747694 2021-01-16 Pascal Schmidt
- [x] https://stackoverflow.com/questions/65716058 2021-01-14 Nelly
- [x] https://stackoverflow.com/questions/65673290 2021-01-11 GMJ
- [x] https://stackoverflow.com/questions/65665465 2021-01-11 Benjamin Moran
- [x] https://stackoverflow.com/questions/65649545 2021-01-09 GMJ
- [x] https://stackoverflow.com/questions/65623256 2021-01-07 Benjamin Moran
- [x] https://stackoverflow.com/questions/65484295 2020-12-28 Adri
- [x] https://stackoverflow.com/questions/65481620 2020-12-28 Nelly
- [x] https://stackoverflow.com/questions/60534214 2020-03-04 susannah_rip
- [x] https://stackoverflow.com/questions/65414864 2020-12-22 Elliott Chinn
- [x] https://stackoverflow.com/questions/65364989 2020-12-18 West_End_Line
- [x] https://stackoverflow.com/questions/65314702 2020-12-15 West_End_Line
- [x] https://stackoverflow.com/questions/65316228 2020-12-15 James Cutler
- [x] https://stackoverflow.com/questions/65175474 2020-12-06 Eric Green
- [x] https://stackoverflow.com/questions/65059775 2020-11-29 Cristiano
- [x] https://stackoverflow.com/questions/64699682 2020-11-05 Mohamed Yusuf
- [x] https://stackoverflow.com/questions/64937128 2020-11-20 HSC
- [x] https://stackoverflow.com/questions/64929285 2020-11-20 Willard Tinago
- [x] https://stackoverflow.com/questions/64038463 2020-09-23 SimRock
- [x] https://stackoverflow.com/questions/64919447 2020-11-19 HSC
- [x] https://stackoverflow.com/questions/64901655 2020-11-18 HSC
- [x] https://stackoverflow.com/questions/64884901 2020-11-17 OGC
- [x] https://stackoverflow.com/questions/64791964 2020-11-11 jesse_b
- [x] https://stackoverflow.com/questions/64760909 2020-11-09 ju.
- [x] https://stackoverflow.com/questions/64761041 2020-11-09 ju.
- [x] https://stackoverflow.com/questions/64709998 2020-11-06 Mohamed Yusuf
- [x] https://stackoverflow.com/questions/64667366 2020-11-03 Silchara
- [x] https://stackoverflow.com/questions/64658354 2020-11-03 Polly
- [x] https://stackoverflow.com/questions/64654901 2020-11-02 Marco B
- [x] https://stackoverflow.com/questions/64581870 2020-10-28 Mohamed Yusuf
- [x] https://stackoverflow.com/questions/64550565 2020-10-27 Mohamed Yusuf
- [x] https://stackoverflow.com/questions/64533310 2020-10-26 Jeff Smith
- [x] https://stackoverflow.com/questions/64539128 2020-10-26 TarJae
- [x] https://stackoverflow.com/questions/64536345 2020-10-26 TarJae
- [x] https://stackoverflow.com/questions/64528291 2020-10-25 Pascal Schmidt
- [x] https://stackoverflow.com/questions/64528848 2020-10-25 todd_b
- [x] https://stackoverflow.com/questions/64499552 2020-10-23 jllls
- [x] https://stackoverflow.com/questions/64496547 2020-10-23 Marco B
- [x] https://stackoverflow.com/questions/64483436 2020-10-22 Marco B
- [x] https://stackoverflow.com/questions/64477394 2020-10-22 Mohamed Yusuf
- [x] https://stackoverflow.com/questions/64469429 2020-10-21 Mohamed Yusuf
- [x] https://stackoverflow.com/questions/64463878 2020-10-21 Mohamed Yusuf
- [x] https://stackoverflow.com/questions/64372290 2020-10-15 Nelly
- [x] https://stackoverflow.com/questions/64362734 2020-10-14 Sylv
- [x] https://stackoverflow.com/questions/64347952 2020-10-14 user1697590
- [x] https://stackoverflow.com/questions/64268904 2020-10-08 NewBee
- [x] https://stackoverflow.com/questions/64197029 2020-10-04 TarJae
- [x] https://stackoverflow.com/questions/63990095 2020-09-21 user7988184
- [x] https://stackoverflow.com/questions/64107740 2020-09-28 Phindi
- [x] https://stackoverflow.com/questions/64046253 2020-09-24 Jeff Smith
- [x] https://stackoverflow.com/questions/63924910 2020-09-16 NewBee
- [x] https://stackoverflow.com/questions/63840164 2020-09-10 NewBee
- [x] https://stackoverflow.com/questions/63801918 2020-09-08 arbetj
- [x] https://stackoverflow.com/questions/63728367 2020-09-03 itsMeInMiami
- [x] https://stackoverflow.com/questions/63678684 2020-08-31 fbm77
- [x] https://stackoverflow.com/questions/63640473 2020-08-28 TJ87
- [x] https://stackoverflow.com/questions/63483511 2020-08-19 Jay Achar
- [x] https://stackoverflow.com/questions/63455513 2020-08-17 Misha
- [x] https://stackoverflow.com/questions/63435344 2020-08-16 Wei Qi Loh
- [x] https://stackoverflow.com/questions/63384584 2020-08-12 arbetj
- [x] https://stackoverflow.com/questions/63180323 2020-07-30 Willard Tinago
- [x] https://stackoverflow.com/questions/63160875 2020-07-29 ju.
- [x] https://stackoverflow.com/questions/62684132 2020-07-01 B_slash_
- [x] https://stackoverflow.com/questions/61360954 2020-04-22 Nelly
- [x] https://stackoverflow.com/questions/60534214 2020-03-04 susannah_rip
- [x] https://stackoverflow.com/questions/62627290 2020-06-28 pkreville
- [x] https://stackoverflow.com/questions/62525071 2020-06-22 neuroR
- [x] https://stackoverflow.com/questions/62456616 2020-06-18 neuroR
- [x] https://stackoverflow.com/questions/62289468 2020-06-09 Aleksei Ponomarenko
- [x] https://stackoverflow.com/questions/60751172 2020-03-19 shortessay
- [x] https://stackoverflow.com/questions/62114659 2020-05-31 Nelly
- [x] https://stackoverflow.com/questions/62137514 2020-06-01 Cristiano
- [x] https://stackoverflow.com/questions/61897198 2020-05-19 Pan Qing
- [x] https://stackoverflow.com/questions/61917395 2020-05-20 Parseltongue
- [x] https://stackoverflow.com/questions/61895779 2020-05-19 Parseltongue
- [x] https://stackoverflow.com/questions/61638996 2020-05-06 Pan Qing
- [x] https://stackoverflow.com/questions/61605923 2020-05-05 Pan Qing
- [x] https://stackoverflow.com/questions/61532704 2020-04-30 Misha
- [x] https://stackoverflow.com/questions/61531464 2020-04-30 user13294558
- [x] https://stackoverflow.com/questions/61369062 2020-04-22 Steffi Rocchi
- [x] https://stackoverflow.com/questions/61331399 2020-04-20 Nelly
- [x] https://stackoverflow.com/questions/61190043 2020-04-13 nelsn
- [x] https://stackoverflow.com/questions/60997710 2020-04-02 sar
- [x] https://stackoverflow.com/questions/61173570 2020-04-12 user13294558
- [x] https://stackoverflow.com/questions/60958953 2020-03-31 sar
- [x] https://stackoverflow.com/questions/60643652 2020-03-11 RockinRichi
- [x] https://stackoverflow.com/questions/60367673 2020-02-23 braden

**Comment by larmarange** [comment]
All these answers would be great to produce a FAQ vignette

**Comment by ddsjoberg** [comment]
@larmarange that is a great idea
