### ISSUE TITLE
95% CI for proportions

### ISSUE THREAD

**Issue by proshano** [ddsjoberg/gtsummary#869]
Love the package.

Occasionally I want to display 95% confidence intervals for proportions/percentages in tbl_summary. Is this possible at this time?

**Comment by ddsjoberg** [comment]
Hi proshano ! Thank you for the post.

It's possible to add the confidence interval, but it's not simple at the moment. It's something I am hoping to add easy integration in the future.

You can subscribe to this issue for updates https://github.com/ddsjoberg/gtsummary/issues/868

In the meantime, here is a solution you can implement
https://stackoverflow.com/questions/67125791

**Comment by ddsjoberg** [comment]
I am going to go ahead and close this issue. please re-open if you would like to discuss more
