### ISSUE TITLE
Problem with p-values in tbl_summary when continuous variables are labelled

### ISSUE THREAD

**Issue by lspeetluk** [ddsjoberg/gtsummary#876]
I'm noticing a consistent error in tbl_summary %>% add_p when including continuous variables that have been supplied labels in their dataframe. I get the following error (for example, using cd4_count): 

> x There was an error calculating the summary statistics for 'cd4_count'. Is this variable's class supported by `median` and `quantile`?
Error: Problem with `mutate()` input `df_stats`.
x nms %in% c("i", "x", "") are not all TRUE
i input `df_stats` is `pmap(...)`.

When I remove the label, the error goes away

**Comment by ddsjoberg** [comment]
Thanks @lspeetluk for the report ! Can you please add a reproducible example that I can also run on my machine? 😊

**Comment by lspeetluk** [comment]
Realized the error occurs with tbl_summary regardless of the add_p option. 

Here's code to reproduce an example: 

```
library(gtsummary)
library(Hmisc)

data <- structure(list(cd4_count = c(30, 97, 210, NA, 358, 242, 126, 
792, 6, 145, 22, 150, 43, 23, 39, 953, 357, 427, 367, 239, 72, 
61, 61, 438, 392, 1092, 245, 326, 42, 135, 199, 158, 17, NA, 
287, 187, 252, 477, 157, NA, NA, 362, NA, 183, 885, 109, 321, 
286, 142, 797), unsuccessful = c(0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 
1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 
0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0), age = c(40, 
28, 31, 25, 50, 28, 34, 20, 28, 46, 36, 43, 38, 70, 35, 60, 39, 
50, 25, 52, 32, 34, 44, 24, 31, 35, 39, 60, 29, 51, 34, 26, 33, 
35, 47, 61, 36, 54, 44, 18, 50, 47, 20, 50, 49, 58, 48, 38, 55, 
39)), row.names = c(NA, 50L), class = "data.frame")

# This one works - no variables are labelled
data %>% 
  tbl_summary(by=unsuccessful)

# Add label to CD4 count, using Hmisc package
label(data$cd4_count) <- "CD4 count"

# Now tbl_summary shows error
data %>% 
  tbl_summary(by=unsuccessful)
```

Somewhat new to forums, so apologies if this isn't the cleanest way to create the reproducible example. Please let me know if you need additional details. Thanks! 

Side note: It seems to maybe be related to labelled variables with missing values. When I label age (which has no missing data) the error doesn't occur

**Comment by ddsjoberg** [comment]
Thanks for posting this....the behavior of the labelled vector is so strange!

The issue is that when the median is calculated for each group, the results are different classes and dplyr refuses to put them in the same column. The question is....why do the medians come back with different classes!?!?  Will continue to investigate...... 🤔 

``` r
library(magrittr)

data <-
  structure(
    list(
      cd4_count = c(
        30, 97, 210, NA, 358, 242, 126,
        792, 6, 145, 22, 150, 43, 23, 39, 953, 357, 427, 367, 239, 72,
        61, 61, 438, 392, 1092, 245, 326, 42, 135, 199, 158, 17, NA,
        287, 187, 252, 477, 157, NA, NA, 362, NA, 183, 885, 109, 321,
        286, 142, 797
      ),
      unsuccessful = c(
        0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
        1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0
      ),
      age = c(
        40, 28, 31, 25, 50, 28, 34, 20, 28, 46, 36, 43, 38, 70, 35, 60, 39,
        50, 25, 52, 32, 34, 44, 24, 31, 35, 39, 60, 29, 51, 34, 26, 33,
        35, 47, 61, 36, 54, 44, 18, 50, 47, 20, 50, 49, 58, 48, 38, 55,
        39
      )
    ),
    row.names = c(NA, 50L),
    class = "data.frame"
  )

# Add label to CD4 count, using Hmisc package
Hmisc::label(data$cd4_count) <- "CD4 count"

# the classes here are all the same
data$cd4_count %>% class()
#> [1] "labelled" "numeric"
data$cd4_count[data$unsuccessful == 0] %>% class()
#> [1] "labelled" "numeric"
data$cd4_count[data$unsuccessful == 1] %>% class()
#> [1] "labelled" "numeric"


# Why are the results not the same class?!?!
data$cd4_count[data$unsuccessful == 0] %>% median(na.rm = TRUE) %>% class()
#> [1] "labelled" "numeric"
data$cd4_count[data$unsuccessful == 1] %>% median(na.rm = TRUE) %>% class()
#> [1] "numeric"
```

<sup>Created on 2021-04-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by ddsjoberg** [comment]
https://stackoverflow.com/questions/67291199/r-inconsistent-class-returned-by-median-when-vector-labelled-with-hmisc

**Comment by lspeetluk** [comment]
Thanks! Will keep an eye on that post

**Comment by ddsjoberg** [comment]
The response on stackoverflow has a potential solution by adding whatever attributes may be present on the original vector onto the result. This would need to be applied to every single summary statistic.

I am hesitant to add something like this that adds computation time to every single calculation. Will need to think on it more...
