### ISSUE TITLE
Solving Error: Problem with `mutate()` input `test_name`.

### ISSUE THREAD

**Issue by ElfatihHasabo** [ddsjoberg/gtsummary#878]
When i start using gt summary package in R using add.p to add p value for the table, the p value didn't appear for me and showing the following:
Error: Problem with `mutate()` input `test_name`.
x Result 8 must be a single string, not NULL of length 0
i Input `test_name` is `map_chr(.data$test_info, ~pluck(.x, "test_name"))`.
Run `rlang::last_error()` to see where the error occurred.

how can i solve this problem?

**Comment by ddsjoberg** [comment]
Thanks for the comment @ElfatihHasabo !

Ease provide a reproducible example that I can run in my machine, and I'll look into it.

**Comment by ElfatihHasabo** [comment]
Thank you@ddsjoberg for your reply

I run this code for my excell file dsh

tbl_summary(dsh, by = timesspecial, digits = list(all_categorical() ~ c(0, 1),all_continuous() ~ c(1, 1))) %>% add_n() %>% bold_labels() %>% add_overall() %>% add_p()

-Then it showed 
Error: Problem with `mutate()` input `test_name`.
x Result 8 must be a single string, not NULL of length 0
i Input `test_name` is `map_chr(.data$test_info, ~pluck(.x, "test_name"))`.
Run `rlang::last_error()` to see where the error occurred.


- when i run `rlang::last_error()`, it appeared :

x
+-<error/dplyr:::mutate_error>
| Problem with `mutate()` input `test_name`.
| x Result 8 must be a single string, not NULL of length 0
| i Input `test_name` is `map_chr(.data$test_info, ~pluck(.x, "test_name"))`.
\-<error/purrr_error_bad_element_vector>
  Result 8 must be a single string, not NULL of length 0
Backtrace:
  1. `%>%`(...)
 11. purrr:::stop_bad_element_vector(...)
 12. purrr:::stop_bad_vector(...)
 13. purrr:::stop_bad_type(...)
Run `rlang::last_trace()` to see the full context.


-Then, when i run `rlang::last_trace()` to see the full context, i found this

x
+-<error/dplyr:::mutate_error>
| Problem with `mutate()` input `test_name`.
| x Result 8 must be a single string, not NULL of length 0
| i Input `test_name` is `map_chr(.data$test_info, ~pluck(.x, "test_name"))`.
\-<error/purrr_error_bad_element_vector>
  Result 8 must be a single string, not NULL of length 0
Backtrace:
     x
  1. +-`%>%`(...)
  2. +-gtsummary::add_p(.)
  3. +-gtsummary:::add_p.tbl_summary(.)
  4. | \-`%>%`(...)
  5. +-dplyr::mutate(...)
  6. +-dplyr:::mutate.data.frame(...)
  7. | \-dplyr:::mutate_cols(.data, ...)
  8. |   +-base::withCallingHandlers(...)
  9. |   \-mask$eval_all_mutate(quo)
 10. +-purrr::map_chr(.data$test_info, ~pluck(.x, "test_name"))
 11. \-purrr:::stop_bad_element_vector(...)
 12.   \-purrr:::stop_bad_vector(...)
 13.     \-purrr:::stop_bad_type(...)
 

**attention-**
gt summary is working probably except when i run a %>% add_p() to see p-value, it showed this error, please fix this error for me; becaus when i put this code in another, laptop it worked for me.

thanks in advance

**Comment by ddsjoberg** [comment]
Hi @ElfatihHasabo !

To help you I need a minimal reproducible example that I can run on my machine. Please review this post about how to prepare a proper example. https://reprex.tidyverse.org/

**Comment by ddsjoberg** [comment]
hello @ElfatihHasabo !

I am going to go ahead and close this issue for now. Please re-open the issue when you've prepared the minimal reproducible example 😃
