### ISSUE TITLE
Let huxtable use markdown 

### ISSUE THREAD

**Issue by hughjonesd** [ddsjoberg/gtsummary#885]
Since version 5.0.0, huxtable supports markdown within table cells with the `set_markdown()` functionality:

```r
set_markdown(ht, rows, cols)
# or the shortcut
set_markdown_contents(ht, rows, cols, "**bold** *italic*")
```

**Describe the solution you'd like**

`as_hux_table` should set `strip_md_bold = FALSE` by default, and probably this option could be deprecated. Cells containing markdown should have `set_markdown(TRUE)` set on them.

**Additional context**

I'd make a pull request myself, but I have to be honest - I find the gtsummary code really hard to get my head around! I suspect you could do this much faster than I can, but if you don't have time, tell me and I will try.

**Comment by ddsjoberg** [comment]
Can you give an example how the markdown function is used?  How would I go about allowing markdown for the header rows?

**Comment by hughjonesd** [comment]
Last line should be `set_markdown(1, everywhere, TRUE)`.

**Comment by ddsjoberg** [comment]
Thanks! I'll add it to the list of things to do. 

Some notes for myself.... I think all I need to do is add the one line above to the huxtable calls. When there is a spanning header, then I'll likely need to include `row = 1:2`

```r
library(gtsummary)

tbl <- 
  trial %>%
  select(age, trt) %>%
  tbl_summary(by = trt) %>%
  as_hux_table(strip_md_bold = FALSE) %>%
  huxtable::set_markdown(row = 1, col = huxtable::everywhere, value = TRUE)
```
