### ISSUE TITLE
tidymodels and gtsummary

### ISSUE THREAD

**Issue by yonicd** [ddsjoberg/gtsummary#890]
When I use tidymodels it creates all kinds of funky variable names for the covariates in the model, is there a way to manipulate the term cell values to use labelled or something to be able to change the variables names into a more human readable value?

i would think this would need to be post table creation since the input is a fit object that has no way to easily change the names of the terms in the model for tblsummary to use.

or am i just using the package wrong :)

**Comment by ddsjoberg** [comment]
hey @yonicd ! thank you so much for the post!

I've been meaning to look into how gtsummary and tidymodels work together for some time now....but i jsut haven't gotten into it yet! https://github.com/ddsjoberg/gtsummary/issues/647


Can you post example code that I can also run on my machine and I'll investigate how to integrate tidymodels with gtsummary?

**Comment by ddsjoberg** [comment]
hey hey @yonicd ! Can you install this version of the package (https://github.com/ddsjoberg/gtsummary/pull/892) and test it with tidymodels?  I don't use tidymodels, but I think this fix will work

**Comment by yonicd** [comment]
Thanks! How do i change values of cells once it is in a gtsummary class?

**Comment by yonicd** [comment]
Btw my initial try was to use it with the forest plot spark line, which worked, but the sticking point was the term names, which end users have no idea how to read

**Comment by ddsjoberg** [comment]
Hmmm I'm not certain what you're asking. Can you provide an example?

**Comment by yonicd** [comment]
so if i have a model setup

```r
md_rec <- md%>%
  recipes::recipe(RESPONSE ~ .) %>% 
  recipes::step_rm(USUBJID, APERIOD, COHORT, AVISITN, MAX_APERIOD, 
                   MDDFST, NUMEPSD, NUMEPSDCAT, RACEGR1, AGEGR1) %>% 
  recipes::step_string2factor(recipes::all_nominal(), -recipes::all_outcomes()) %>%
  recipes::step_normalize(recipes::all_numeric(), -recipes::all_outcomes())%>%
  recipes::step_dummy(recipes::all_nominal(), -recipes::all_outcomes())%>% 
  recipes::step_interact(terms = ~ BASE:starts_with("NUMEPSDFL_"))%>%
  #recipes::step_interact(terms = ~ starts_with("D15"):contains('RET28'))%>%
  recipes::step_zv(recipes::all_predictors())

wf <- workflow() %>% 
  add_model(log_mod) %>%
  add_recipe(md_rec)

wf_fit <- wf%>%
  fit(data = md)

wf_fit%>%
  pull_workflow_fit()%>%
  gtsummary::tbl_regression(exponentiate = TRUE) %>%
  bstfun::add_inline_forest_plot()
```

i get this
![2021-05-05 10_35_39-Window_LI](https://user-images.githubusercontent.com/1755487/117159268-21dc9e80-ad8e-11eb-8898-3de81232359a.jpg)

there is no good way to add labels for the terms to make it more human readable than what the recipe creates.

i can create it from a broom gt way, but then getting sparklines in that is a headache

```r
wf_fit%>%
  tidy(exponentiate = TRUE, conf.int = TRUE)%>%
  dplyr::mutate(
    timing = dplyr::case_when(
      term %in% c('BASE','BMIBL','SEX_M','ANTDEBFL_Y','NUMEPSDFL_X4.','BASE_x_NUMEPSDFL_X4.') ~ 'Baseline',
      TRUE ~ 'Post Baseline'      
    )
  )%>%
  mutate(
    term = dplyr::case_when(
      term == 'PCHG' ~ 'D15 HAM-D % Change',
      term == 'BASE' ~ 'D0 HAM-D',
      term == 'ANTDEBFL_Y' ~ 'Antidepressant use at Baseline',
      term == 'NUMEPSDFL_X4.' ~ 'Number of Dep Episodes >= 4',
      term == 'D15_REMISSION_Y' ~ 'D15 Remission',
      term == 'BMIBL' ~ 'BMI',
      term == 'SEX_M' ~ 'Male',
      term == 'BASE_x_NUMEPSDFL_X4.' ~ 'D0 HAM-D x Number of Dep Episodes >= 4',
      term == 'RETREAT_FLAG_LE70' ~ 'Retreatament <= 70 Days after end of Treatment',
      term == 'PCHG15_RET28_N' ~ 'D15 Change From Baseline Retention < 80% at D28',
      term == 'D15_REMISSION_Y_x_PCHG15_RET28_N' ~ 'D15 Remission x D15 Change From Baseline Retention < 80% at D28',
      TRUE ~ term
    )
  )%>%
  dplyr::arrange(timing,dplyr::desc(estimate))%>%
  dplyr::mutate(
    term = forcats::fct_reorder2(term, timing,estimate),
    dplyr::across(c(conf.low,conf.high),scales::label_number(accuracy = 0.01)),
    ci = glue::glue('{conf.low}, {conf.high}')
  )%>%
  dplyr::select(timing, term,estimate,ci, p.value)%>%
  gt::gt(rowname_col = 'term',groupname_col = 'timing')%>%
  gt::row_group_order(groups = c('Baseline','Post Baseline'))%>%
  gt::fmt_number(vars(estimate))%>%
  gt::fmt(vars(p.value), fns = scales::pvalue)%>%
  gt::cols_label(
    ci = '95% CI',
    p.value = 'p-value'
  )

```

![2021-05-05 10_41_33-217-MDD-303 - master - RStudio_LI](https://user-images.githubusercontent.com/1755487/117160075-d1197580-ad8e-11eb-8f9b-18f8705fc704.jpg)


does that make more sense?

**Comment by larmarange** [comment]
Did you try to use the `label` argument of `tbl_regression()`?

**Comment by larmarange** [comment]
@ddsjoberg   Just to be sure, `labels` in `tbl_regression()` is mapped to  `variable_labels` of `broom.helpers::tidy_plus_plus()`. Is there a way to pass elements to `term_labels`?

**Comment by ddsjoberg** [comment]
> so if i have a model setup
> 
> ```r
> md_rec <- md%>%
>   recipes::recipe(RESPONSE ~ .) %>% 
>   recipes::step_rm(USUBJID, APERIOD, COHORT, AVISITN, MAX_APERIOD, 
>                    MDDFST, NUMEPSD, NUMEPSDCAT, RACEGR1, AGEGR1) %>% 
>   recipes::step_string2factor(recipes::all_nominal(), -recipes::all_outcomes()) %>%
>   recipes::step_normalize(recipes::all_numeric(), -recipes::all_outcomes())%>%
>   recipes::step_dummy(recipes::all_nominal(), -recipes::all_outcomes())%>% 
>   recipes::step_interact(terms = ~ BASE:starts_with("NUMEPSDFL_"))%>%
>   #recipes::step_interact(terms = ~ starts_with("D15"):contains('RET28'))%>%
>   recipes::step_zv(recipes::all_predictors())
> 
> wf <- workflow() %>% 
>   add_model(log_mod) %>%
>   add_recipe(md_rec)
> 
> wf_fit <- wf%>%
>   fit(data = md)
> 
> wf_fit%>%
>   pull_workflow_fit()%>%
>   gtsummary::tbl_regression(exponentiate = TRUE) %>%
>   bstfun::add_inline_forest_plot()
> ```
> 
> i get this
> ![2021-05-05 10_35_39-Window_LI](https://user-images.githubusercontent.com/1755487/117159268-21dc9e80-ad8e-11eb-8898-3de81232359a.jpg)
> 
> there is no good way to add labels for the terms to make it more human readable than what the recipe creates.
> 
> i can create it from a broom gt way, but then getting sparklines in that is a headache
> 
> ```r
> wf_fit%>%
>   tidy(exponentiate = TRUE, conf.int = TRUE)%>%
>   dplyr::mutate(
>     timing = dplyr::case_when(
>       term %in% c('BASE','BMIBL','SEX_M','ANTDEBFL_Y','NUMEPSDFL_X4.','BASE_x_NUMEPSDFL_X4.') ~ 'Baseline',
>       TRUE ~ 'Post Baseline'      
>     )
>   )%>%
>   mutate(
>     term = dplyr::case_when(
>       term == 'PCHG' ~ 'D15 HAM-D % Change',
>       term == 'BASE' ~ 'D0 HAM-D',
>       term == 'ANTDEBFL_Y' ~ 'Antidepressant use at Baseline',
>       term == 'NUMEPSDFL_X4.' ~ 'Number of Dep Episodes >= 4',
>       term == 'D15_REMISSION_Y' ~ 'D15 Remission',
>       term == 'BMIBL' ~ 'BMI',
>       term == 'SEX_M' ~ 'Male',
>       term == 'BASE_x_NUMEPSDFL_X4.' ~ 'D0 HAM-D x Number of Dep Episodes >= 4',
>       term == 'RETREAT_FLAG_LE70' ~ 'Retreatament <= 70 Days after end of Treatment',
>       term == 'PCHG15_RET28_N' ~ 'D15 Change From Baseline Retention < 80% at D28',
>       term == 'D15_REMISSION_Y_x_PCHG15_RET28_N' ~ 'D15 Remission x D15 Change From Baseline Retention < 80% at D28',
>       TRUE ~ term
>     )
>   )%>%
>   dplyr::arrange(timing,dplyr::desc(estimate))%>%
>   dplyr::mutate(
>     term = forcats::fct_reorder2(term, timing,estimate),
>     dplyr::across(c(conf.low,conf.high),scales::label_number(accuracy = 0.01)),
>     ci = glue::glue('{conf.low}, {conf.high}')
>   )%>%
>   dplyr::select(timing, term,estimate,ci, p.value)%>%
>   gt::gt(rowname_col = 'term',groupname_col = 'timing')%>%
>   gt::row_group_order(groups = c('Baseline','Post Baseline'))%>%
>   gt::fmt_number(vars(estimate))%>%
>   gt::fmt(vars(p.value), fns = scales::pvalue)%>%
>   gt::cols_label(
>     ci = '95% CI',
>     p.value = 'p-value'
>   )
> 
> ```
> 
> ![2021-05-05 10_41_33-217-MDD-303 - master - RStudio_LI](https://user-images.githubusercontent.com/1755487/117160075-d1197580-ad8e-11eb-8f9b-18f8705fc704.jpg)
> 
> 
> does that make more sense?
> 
> 

Can you update this with code/data example I can run on my machine?

**Comment by ddsjoberg** [comment]
> @ddsjoberg   Just to be sure, `labels` in `tbl_regression()` is mapped to  `variable_labels` of `broom.helpers::tidy_plus_plus()`. Is there a way to pass elements to `term_labels`?

I think it possible with themes...but it's been a while since I last reviewed that code

**Comment by yonicd** [comment]
i am not familiar with that, can you add a link to an example of the usage? thanks

**Comment by ddsjoberg** [comment]
> i am not familiar with that, can you add a link to an example of the usage? thanks

Review this short article on how to create a reproducible example, aka a reprex https://www.tidyverse.org/help/#reprex

**Comment by yonicd** [comment]
sorry. i didnt mean reprex, i meant broom.helpers. I found the vignette. nice package!

https://cran.r-project.org/web/packages/broom.helpers/vignettes/tidy.html

**Comment by yonicd** [comment]
having trouble with gt to render in a reprex without just giving back a html tables. here is the script

```r
library(modeldata)
library(magrittr)
library(tidymodels)

data(penguins)
penguins <- penguins %>% 
  na.omit()

rec <- recipe(sex ~., data = penguins)

int_mod_2 <- rec %>%
  step_dummy(sex, species, island) %>%
  step_interact(terms = ~ body_mass_g:starts_with("species"))

int_mod_2 <- prep(int_mod_2, training = penguins)

log_mod <- logistic_reg() %>%
  set_engine('glm') 

wf_test <- workflow() %>% 
  add_model(log_mod) %>%
  add_recipe(rec)

wf_fit <- wf_test%>%
  fit(data = penguins)

wf_fit%>%
  pull_workflow_fit()%>%
  gtsummary::tbl_regression(exponentiate = TRUE) %>%
  bstfun::add_inline_forest_plot()
```

The interesting piece is that if i do this 

```r
wf_fit%>%
  pull_workflow_fit()%>%
  gtsummary::tbl_regression(exponentiate = TRUE) %>%
  bstfun::add_inline_forest_plot()%>%
  gtsummary::as_gt()%>%
  gt::gt_preview()
```

i get more info including var_label that maybe gets informed by broom.helpers.

**Comment by yonicd** [comment]
@larmarange label is the way! that makes sense now. thanks

**Comment by yonicd** [comment]
last question. is there any way to add post hoc information like `gt::gt(rowname_col , groupname_col)` to bin the rows by term type in `tbl_regression`? to create a similar grouping like i have above?

**Comment by yonicd** [comment]
figured it out

```r
wf_fit%>%
  pull_workflow_fit()%>%
  gtsummary::tbl_regression(exponentiate = TRUE,label = lbls) %>%
  bstfun::add_inline_forest_plot()%>%
  gtsummary::as_gt(rowname_col = 'label')%>%
  gt::tab_row_group(group = 'group a',rows = c(1,2,3))%>%
  gt::tab_row_group(group = 'group b',rows = c(4,5,6))
```
