### ISSUE TITLE
tbl_regression() and lme4::lmer()

### ISSUE THREAD

**Issue by sachijay** [ddsjoberg/gtsummary#893]
When I try to use `tbl_regression()` on a `lme4::lmer()` object, for some variables the variable name is displayed instead of the assigned label. I had to solve the issue by using the `label` argument in `tbl_regression()`.

The model has 12 variables but only 2 variables have this issue. For the same set of variables, `lm()` works fine.

Unfortunately, I was unable to reproduce this issue for a different dataset. But the following is the same code (only for a dataset with few variables).

``` r
data(Orthodont, package = "nlme")
dat <- Orthodont

attr(dat$distance, which = "label") <- "Distances from the pituitary to the pterygomaxillary fissure (mm)"
attr(dat$age, which = "label") <- "Ages of the subject (yr)"
attr(dat$Sex, which = "label") <- "Sex of the subject"


m_mod <- lme4::lmer(distance ~ age + Sex + (1 | Subject), 
              data = dat)

gtsummary::tbl_regression(m_mod)
#> Warning: The `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0.
```

**Comment by ddsjoberg** [comment]
hi @sachijay ! thank you for the post! I took a look, and unfortunately, without an example I am not sure where to go from here. If you see the issue again and can put together an example for me to run too, please re-open this issue!
