### ISSUE TITLE
Feature Request: Add `add_global_p()` support for `mgcv::gam`

### ISSUE THREAD

**Issue by StaffanBetner** [ddsjoberg/gtsummary#895]
`car::Anova` does not support `mgcv::gam` objects, hence `add_global_p` does not work. For `mgcv::gam` objects `mgcv::anova` should be used (which is a type III Anova test). 

Reprex:
```r
gam(formula = mpg ~ s(hp)+factor(cyl), data=mtcars) %>% tbl_regression() %>% add_global_p()
```

**Comment by ddsjoberg** [comment]
hey @StaffanBetner ! thank you for the post!

I am in a bit of a dev break at the moment FYI. I'll revisit the request when I am back to it!

**Comment by StaffanBetner** [comment]
No worries, I will post a workaround here when I am finished with it. (Similar to what you suggested for geeglm and emmeans)

**Comment by ddsjoberg** [comment]
Hey hey @StaffanBetner ! I took a quick look at this. The first step would be to write a `tidy()` function for the `mgcv::anova()` results (similar to the `tidy()` function that tidies the `car::Anova()` results). Have you written one already? If so (or if you haven't and are willing to assist), can you add the code here?

**Comment by StaffanBetner** [comment]
I did something way more ad-hoc, unfortunately. But I can take a look at what I did in the coming days. I will work on that project tomorrow.

**Comment by ddsjoberg** [comment]
We can start with having the tidier run in gtsummary, but it would be good for the community to also do a pull request to add it to `broom::tidy()` (if they'll accept it, they have a strong preference for tidiers going in the original package now) and to `paramaters::model_parameters()`. Just a thought!

**Comment by ddsjoberg** [comment]
Hey @StaffanBetner ! FYI the infrastructure for this is now ready and support for  gam models can be added. We had to wait for a bug to get fixed in the survival package for parametric survival models before we could move forward.

If you write a tidier for the `mgcv::anova` object with output that looks the same as `car::Anova() %>% broom::tidy()` we can work to incorporate!

**Comment by ddsjoberg** [comment]
Hello Again @StaffanBetner ,

FYI, the `add_global_p(anova_fun=)` argument has been added (in the dev version). We have a few options for moving forward with this issue.
1. Do nothing, and users can write their own anova function for GAM models as needed.
2. Write a function that performs anova for GAM models and export it as a part of gtsummary.
3. Write the function in #2 AND make it the default anova method when users pass a GAM model to `add_global_p()`.

Do you wan to work on any of these options? If not, i'll likely close this issue and let users write their own functions as they are needed.
