### ISSUE TITLE
tbl_regression(): Better handling of large regression model objects

### ISSUE THREAD

**Issue by Chris-M-P** [ddsjoberg/gtsummary#899]
Regression models in R can become quite large. Processing these models through `tbl_regression()` can cause RAM issues resulting in very long waits for tables to be produced.

The `strip` package ([https://github.com/paulponcet/strip](url)) allows different parts of the regression model object to be removed, greatly reducing the object size while retaining levels of functionality (e.g. able to run `predict` commands) - could this type of functionality be introduced to `gtsummary`? Currently the output from `strip` doesn't appear to be compatible with `tbl_regression()`, but this might be a useful starting point.

**Comment by ddsjoberg** [comment]
Hi @Chris-M-P ! Thank you for the post!

Can you provide an example I can run on my machine (using `strip()`, not a huge model)? Is this package on CRAN?  Is it similar to the tidymodels butcher package?

FYI, I am on a bit of a development break, and may not get around to looking into this for some time. Apologies in advance,

**Comment by Chris-M-P** [comment]
Hi @ddsjoberg ,

Yes, `strip` is on CRAN. Here's some sample code (from the package vignette):

    data("mtcars")
    set.seed(110)
    i = sample(2, nrow(mtcars), replace = TRUE, prob=c(0.8, 0.2))
    r1 = lm(mpg ~ ., data = mtcars[i==1,])
    r2 = strip(r1, keep = "predict")

    # Estimate the objects' size as the size of their serialization
    length(serialize(r1, NULL))
    length(serialize(r2, NULL))

    # Check that predictions are the same
    p1 = predict(r1, newdata = mtcars[i==2,])
    p2 = predict(r2, newdata = mtcars[i==2,])
    identical(p1, p2) # TRUE`

I hadn't seen the `butcher` package, but unfortunately `butcher` doesn't seem to offer much improvement in size for the `glm` models I've been generating (a few MBs trimmed off 1.5GB). Whereas `strip` trims my model down to 61kb (!) with enough info retained to run `predict` or `print`

**Comment by Chris-M-P** [comment]
I'll have a look into it and let you know!

**Comment by ddsjoberg** [comment]
What you'll want to do is write a tidier that creates a tibble that looks like the one below.  Ideally, it'll have arguments `tidy_strip(x, exponentiate = FALSE, conf.level = 0.95, conf.int = TRUE)`

``` r
data("mtcars")
set.seed(110)
i = sample(2, nrow(mtcars), replace = TRUE, prob=c(0.8, 0.2))
r1 = lm(mpg ~ ., data = mtcars[i==1,])
broom::tidy(r1, conf.int = TRUE)
#> # A tibble: 11 x 7
#>    term         estimate std.error statistic p.value   conf.low conf.high
#>    <chr>           <dbl>     <dbl>     <dbl>   <dbl>      <dbl>     <dbl>
#>  1 (Intercept) -76.5       39.3       -1.95   0.0756 -162.         9.19  
#>  2 cyl           5.20       2.36       2.21   0.0477    0.0622    10.3   
#>  3 disp          0.00625    0.0186     0.337  0.742    -0.0342     0.0467
#>  4 hp           -0.00580    0.0234    -0.247  0.809    -0.0569     0.0453
#>  5 drat          5.91       2.35       2.52   0.0270    0.797     11.0   
#>  6 wt           -1.19       2.03      -0.585  0.569    -5.60       3.23  
#>  7 qsec          1.58       0.721      2.19   0.0488    0.00992    3.15  
#>  8 vs            3.81       2.24       1.70   0.114    -1.06       8.69  
#>  9 am            7.48       2.64       2.83   0.0152    1.72      13.2   
#> 10 gear          6.43       2.92       2.20   0.0479    0.0714    12.8   
#> 11 carb         -3.56       1.33      -2.68   0.0202   -6.46      -0.661
```

<sup>Created on 2021-05-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by Chris-M-P** [comment]
`broom` already seems to handle `summary.lm` models to handle large `lm` models:

> The tidy.summary.lm() method is a potentially useful alternative to tidy.lm(). For instance, if users have already converted large lm objects into their leaner summary.lm equivalents to conserve memory

This is compatible with `tbl_regression` but doesn't bring through variable and value labels. This could be a starting point for handling large models though

**Comment by ddsjoberg** [comment]
Fantastic! So that tidier handles the stripped models,l after a summary?

Honestly, I think it's unlikely you'll be able to access the labels after stripping the model. You'll have to pass them in the label argument

**Comment by Chris-M-P** [comment]
Turns out I was barking up the wrong tree - the default estimation of the confidence intervals, not the size of the model object, was causing the performance issues. I modified your code for a customised tidier to calculate Wald CIs for `glm` models and it's now blazing fast:
```
my_tidy <- function(x, exponentiate =  TRUE, conf.level = 0.95, ...) {
  dplyr::bind_cols(
    broom::tidy(x, exponentiate = exponentiate, conf.int = FALSE),
    # calculate the confidence intervals, and save them in a tibble
    exp(stats::confint.default(x)) %>%
      tibble::as_tibble() %>%
      rlang::set_names(c("conf.low", "conf.high"))  )
}
```
Incidentally, there's an open issue raised on the `broom` github repo relating to this: [https://github.com/tidymodels/broom/issues/989](url)

**Comment by ddsjoberg** [comment]
That is great! I'll close the issue now. But if you need to re-open , please feel free

**Comment by arvgus** [comment]
> Turns out I was barking up the wrong tree - the default estimation of the confidence intervals, not the size of the model object, was causing the performance issues. I modified your code for a customised tidier to calculate Wald CIs for `glm` models and it's now blazing fast:
> 
> ```
> my_tidy <- function(x, exponentiate =  TRUE, conf.level = 0.95, ...) {
>   dplyr::bind_cols(
>     broom::tidy(x, exponentiate = exponentiate, conf.int = FALSE),
>     # calculate the confidence intervals, and save them in a tibble
>     exp(stats::confint.default(x)) %>%
>       tibble::as_tibble() %>%
>       rlang::set_names(c("conf.low", "conf.high"))  )
> }
> ```
> 
> Incidentally, there's an open issue raised on the `broom` github repo relating to this: [https://github.com/tidymodels/broom/issues/989](url)

I am using your function for Wald CIs and it works. However compared to using the regular estimate (where CIs are centered around 1.00) I instead get CIs centered around 0 (with negatives sometimes). Is this the supposed behaviour and would it be possible to change?
