### ISSUE TITLE
Split long gtsummary() table to n smaller tables

### ISSUE THREAD

**Issue by andrader** [ddsjoberg/gtsummary#905]
I would like [bstfun::tbl_split](http://www.danieldsjoberg.com/bstfun/reference/tbl_split.html) to be part o `gtsummary`

I think this is something that would be helpful to many users, so I am making this feature request based off this SO question and answer:
https://stackoverflow.com/questions/66119997/split-long-gtsummary-table-to-n-smaller-tables
(Thank you Daniel D. Sjoberg for the solution)

**Comment by ddsjoberg** [comment]
Hey hey @andrader ! Thanks for the post!

I'm taking a bit of a gtsummary dev break at the moment, so I may not fully respond to this issue quickly, FYI

I think it's something that could go into gtsummary. But I would need to spend the time to think/program what to do when these tables are printed, e.g. should there be a page break inserted automatically between the split tables.....

**Comment by ddsjoberg** [comment]
adding in #994
