### ISSUE TITLE
Feature Request: Add Standardized mean difference to add_difference()

### ISSUE THREAD

**Issue by uriahf** [ddsjoberg/gtsummary#916]
Thank you for this great package! I use it all the time in my workplace.

One of my collegues wondered if there's a way to add Standardized Mean Difference to the tables, the same way one can add regular mean difference with `add_difference`.

**Comment by ddsjoberg** [comment]
hi hi! thanks for the post.

You can add Cohen's D, is that what you're looking for?
http://www.danieldsjoberg.com/gtsummary/reference/tests.html#tbl-summary-gt-add-difference-

**Comment by uriahf** [comment]
That's exactly what I need! 
But I failed to run the code, what did I do wrong?



library(magrittr)
library(gtsummary)

trial %>%
  select(trt, age, marker, response, death) %>%
  tbl_summary(
    by = trt,
    statistic =
      list(
        all_continuous() ~ "{mean} ({sd})",
        all_dichotomous() ~ "{p}%"
      ),
    missing = "no"
  ) %>%
  add_n() %>%
  add_difference(list(all_continuous() ~ "cohens_d"))
#> There was an error in 'add_p()/add_difference()' for variable 'age', p-value omitted:
#> Error in eval(expr, envir = list(`?` = function(...) stop()), enclos = envir): argument "fn" is missing, with no default
#> There was an error in 'add_p()/add_difference()' for variable 'marker', p-value omitted:
#> Error in eval(expr, envir = list(`?` = function(...) stop()), enclos = envir): argument "fn" is missing, with no default
Characteristic	N	Drug A, N = 981	Drug B, N = 1021	p-value2	Difference2	95% CI2,3
Age	189	47 (15)	47 (14)			
Marker Level (ng/mL)	190	1.02 (0.89)	0.82 (0.83)			
Tumor Response	193	29%	34%	0.6	-4.2%	-18%, 9.9%
Patient Died	200	53%	59%	0.5	-5.8%	-21%, 9.0%
1

      Mean (SD); %
      <br />
    </p>
    <p class="gt_footnote">
      <sup class="gt_footnote_marks">
        <em>2</em>
      </sup>
       
      Two sample test for equality of proportions
      <br />
    </p>
    <p class="gt_footnote">
      <sup class="gt_footnote_marks">
        <em>3</em>
      </sup>
       
      CI = Confidence Interval
      <br />
    </p>
  </td>
</tr>
Created on 2021-06-07 by the reprex package (v2.0.0)

**Comment by ddsjoberg** [comment]
Thank you for reporting this issue. I am getting the same error when I run on the release version currently available from CRAN, and no error with the current dev version. I don't recall dixing a bug related to this recently, but it looks like i did!  Try installing the dev version, please.


``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.4.1.9000'

trial %>%
  select(trt, age, marker, response, death) %>%
  tbl_summary(
    by = trt,
    statistic =
      list(
        all_continuous() ~ "{mean} ({sd})",
        all_dichotomous() ~ "{p}%"
      ),
    missing = "no"
  ) %>%
  add_difference(list(all_continuous() ~ "cohens_d")) %>%
  as_kable() # convert to Kable to display on github
```

| **Characteristic**   | **Drug A**, N = 98 | **Drug B**, N = 102 | **Difference** | **95% CI**  | **p-value** |
|:---------------------|:-------------------|:--------------------|:---------------|:------------|:------------|
| Age                  | 47 (15)            | 47 (14)             | -0.03          | -0.32, 0.25 |             |
| Marker Level (ng/mL) | 1.02 (0.89)        | 0.82 (0.83)         | 0.23           | -0.06, 0.51 |             |
| Tumor Response       | 29%                | 34%                 | -4.2%          | -18%, 9.9%  | 0.6         |
| Patient Died         | 53%                | 59%                 | -5.8%          | -21%, 9.0%  | 0.5         |

<sup>Created on 2021-06-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by uriahf** [comment]
It works, but I get an error message:

```

library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.4.1.9001'

trial %>%
  select(trt, age, marker, response, death) %>%
  tbl_summary(
    by = trt,
    statistic =
      list(
        all_continuous() ~ "{mean} ({sd})",
        all_dichotomous() ~ "{p}%"
      ),
    missing = "no"
  ) %>%
  add_difference(list(all_continuous() ~ "cohens_d")) %>%
  as_kable() # convert to Kable to display on github
#> There was an error in 'add_p()/add_difference()' for variable 'age', p-value omitted:
#> Error in eval(expr, envir = list(`?` = function(...) stop()), enclos = envir): argument "fn" is missing, with no default
#> There was an error in 'add_p()/add_difference()' for variable 'marker', p-value omitted:
#> Error in eval(expr, envir = list(`?` = function(...) stop()), enclos = envir): argument "fn" is missing, with no default
Characteristic	Drug A, N = 98	Drug B, N = 102	p-value	Difference	95% CI
Age	47 (15)	47 (14)			
Marker Level (ng/mL)	1.02 (0.89)	0.82 (0.83)			
Tumor Response	29%	34%	0.6	-4.2%	-18%, 9.9%
Patient Died	53%	59%	0.5	-5.8%	-21%, 9.0%
Created on 2021-06-09 by the reprex package (v2.0.0)
```

By the way, how can I make the output table to look like yours in a github message? 
I use reprex::reprex() and just copy paste the output from the viewer.

**Comment by ddsjoberg** [comment]
I am using `reprex::reprex()` as well...I am not sure why it's not rendering properly.

NOTE FOR MYSELF TO INVESTIGTE FURTHER:
Why is the error printing? It seems to be occurring in the conversion of the test name to the test function. If I pass the internal function directly, I don't see the error message.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.4.1'

trial %>%
  select(trt, age, marker, response, death) %>%
  tbl_summary(
    by = trt,
    statistic =
      list(
        all_continuous() ~ "{mean} ({sd})",
        all_dichotomous() ~ "{p}%"
      ),
    missing = "no"
  ) %>%
  add_difference(list(all_continuous() ~ gtsummary:::add_p_test_cohens_d)) %>%
  as_kable()
```

| **Characteristic**   | **Drug A**, N = 98 | **Drug B**, N = 102 | **Difference** | **95% CI**  | **p-value** |
|:---------------------|:-------------------|:--------------------|:---------------|:------------|:------------|
| Age                  | 47 (15)            | 47 (14)             | -0.03          | -0.32, 0.25 |             |
| Marker Level (ng/mL) | 1.02 (0.89)        | 0.82 (0.83)         | 0.23           | -0.06, 0.51 |             |
| Tumor Response       | 29%                | 34%                 | -4.2%          | -18%, 9.9%  | 0.6         |
| Patient Died         | 53%                | 59%                 | -5.8%          | -21%, 9.0%  | 0.5         |

<sup>Created on 2021-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by roman2023** [comment]
Hi, Thanks so much for the great package. I am getting the same problem. I am running Ver 1.4.1. Has this been fixed? How do I overcome this?

**Comment by ddsjoberg** [comment]
@roman2023 I haven't looked into this in detail yet. Did you try the solution in the comment above?

**Comment by ddsjoberg** [comment]
@uriahf  I asked a few friends to test this on the most recent release, and it seems to be working. Can you check on your machine and let me know? Thanks!

**Comment by roman2023** [comment]
Hi @ddsjoberg 
This worked great for continuous variables. I am not able to get the SMD for categorical variables though. 
I am writing add_difference (list (all_continous()~ gtsummary:::add_p_test_cohens_d))
Is there any way I can also get the SMD for categorical variables?

**Comment by ddsjoberg** [comment]
@roman2023 can you test  `add_difference (list (all_continous()~ "cohens_d"))` on gtsummary v1.4.2, and let me know if it works? I am not seeing the error on my machine.

Regarding SMD for categorical variables...it's yet to be implemented. You can make a feature request in a separate issue if you'd like.

**Comment by roman2023** [comment]
@ddsjoberg yes: add_difference (list (all_continous()~ "cohens_d")) works. 
Okay, good to know that SMD for categorical is yet to be implemented. I will add to feature request. Thanks so much for your help !

**Comment by ddsjoberg** [comment]
Thank you @uriahf for posting this issue....it seems as though this is resolved. If not, please reopen the issue :)
