### ISSUE TITLE
create {gtsummary} cheatsheet

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#92]
:smile_cat:

**Comment by ddsjoberg** [comment]
Templates are here:
https://www.rstudio.com/resources/cheatsheets/how-to-contribute-a-cheatsheet/

**Comment by margarethannum** [comment]
Could this be a hackathon project?

**Comment by ddsjoberg** [comment]
That is a GREAT idea, @margarethannum !

**Comment by karissawhiting** [comment]
Love that idea!

**Comment by ddsjoberg** [comment]
The hackathon is going to be 🔥

**Comment by jhk0530** [comment]
Hi, I've created gtsummary `cheatsheet` with 2 pages. 

Here are brief screenshots.

![image](https://user-images.githubusercontent.com/6457691/73817641-d8ba3980-482e-11ea-9072-b100372ef6df.png)

![image](https://user-images.githubusercontent.com/6457691/73817654-e374ce80-482e-11ea-828d-b68f060c70ba.png)

You can see detail in  [forked repository](https://github.com/jhk0530/gtsummary/blob/master/gtsummary_cheatsheet.pdf)

I'm not sure about whether I visualized your meaning well or not.

If you are interested, check and give me some advice.

Regards.

**Comment by ddsjoberg** [comment]
@jhk0530 , thank you for putting this together!  We've got one that is under construction.  I'll take a look at both, and see how we can work together to consolidate :)

**Comment by jhk0530** [comment]
@ddsjoberg I didn't know that, I'm sorry. I downloaded ppt template file and worked with powerpoint.

**Comment by ddsjoberg** [comment]
https://github.com/rstudio/cheatsheets/blob/master/README.md
