### ISSUE TITLE
p-value for categorical variable is not chi-square?

### ISSUE THREAD

**Issue by chrisleitzinger** [ddsjoberg/gtsummary#920]
Hi,

Thank you so much for this package. I love using it! 

I recently realized that when computing the p-value for categorical variable with `add_p()`, it is giving me wrong results.
It will write at the bottom that it computed a chi square test but I will get another p-value by forcing a chi-square with `add_p(all_categorical() ~ "chisq.test")`. In the below example, if I force a kruskal test, I get the same p-value as with `add_p()`.

```r
df <- data.frame(Drugs = c(sample(c("A", "B"),200, replace = TRUE), rep("A", 50)),
                 Mutations= c(sample(c("X", "Y"),200, replace = TRUE), rep("X", 50)))

df %>% 
  select(Drugs, Mutations) %>%
  tbl_summary(by = Drugs) %>%
  bold_labels() %>% add_p()

df %>% 
  select(Drugs, Mutations) %>%
  tbl_summary(by = Drugs) %>%
  bold_labels() %>% add_p(all_categorical() ~ "chisq.test")

df %>% 
  select(Drugs, Mutations) %>%
  tbl_summary(by = Drugs) %>%
  bold_labels() %>% add_p(all_categorical() ~ "kruskal.test")
```
Please let me know if I did something wrong,
Thank you very much!

**Comment by ddsjoberg** [comment]
Hello @chrisleitzinger !  Thank you for the post!

The default test for most categorical data the chi-squared test without the continuity correction, meaning that to compare you must use the `correct = FALSE` option to compare the p-values from the `chisq.test()` function.

Below is an example showing the results from `add_p()` match the output from `chisq.test()`.


``` r
set.seed(3452)
library(gtsummary)
library(tidyverse)
df <- data.frame(Drugs = c(sample(c("A", "B"),200, replace = TRUE), rep("A", 50)),
                 Mutations= c(sample(c("X", "Y"),200, replace = TRUE), rep("X", 50)))

# without continuity correction
chisq.test(x = df$Mutations, y = factor(df$Drugs), correct = FALSE) %>% 
  broom::tidy() %>% pull(p.value) %>% style_pvalue()
#> [1] "0.053"
df %>% 
  select(Drugs, Mutations) %>%
  tbl_summary(by = Drugs) %>%
  add_p() %>%
  as_kable()
```

| **Characteristic** | **A**, N = 151 | **B**, N = 99 | **p-value** |
|:-------------------|:---------------|:--------------|:------------|
| Mutations          |                |               | 0.053       |
| X                  | 92 (61%)       | 48 (48%)      |             |
| Y                  | 59 (39%)       | 51 (52%)      |             |

``` r
# with continuity correction
chisq.test(x = df$Mutations, y = factor(df$Drugs)) %>% 
  broom::tidy() %>% pull(p.value) %>% style_pvalue()
#> [1] "0.071"
df %>% 
  select(Drugs, Mutations) %>%
  tbl_summary(by = Drugs) %>%
  add_p(all_categorical() ~ "chisq.test") %>%
  as_kable()
```

| **Characteristic** | **A**, N = 151 | **B**, N = 99 | **p-value** |
|:-------------------|:---------------|:--------------|:------------|
| Mutations          |                |               | 0.071       |
| X                  | 92 (61%)       | 48 (48%)      |             |
| Y                  | 59 (39%)       | 51 (52%)      |             |

<sup>Created on 2021-06-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

You can read more about the continuity correction here http://www.danieldsjoberg.com/continuity-correction/

**Comment by chrisleitzinger** [comment]
@ddsjoberg, thank you so much for for explanation and the link!! And again great work on the package, it is awesome!
