### ISSUE TITLE
Add `by=` variable to `tbl_svysummary(include=)` by default

### ISSUE THREAD

**Issue by coreysparks** [ddsjoberg/gtsummary#925]
I may have found a bug, below is reproducible code to generate the error. I expect to get a simple summary of variable v151 for the levels of v139, but I get an error stating

```
Error: Problem with `mutate()` column `df_stats`.
i `df_stats = pmap(...)`.
x Can't subset columns that don't exist.
x Column `v139` doesn't exist.
Run `rlang::last_error()` to see where the error occurred
```

---

Brief description of the problem.

```r
dhs<-haven::read_dta("https://github.com/coreysparks/data/blob/master/ZZIR62FL.DTA?raw=true")
dhs<-haven::zap_labels(dhs)
dhs$v005<- dhs$v005/1000000
dhs2<- select(dhs, v021, v022, v005, v139, v151)

names(dhs2)
library(dplyr); library(gtsummary)
options(survey.lonely.psu = "adjust")
t1<- survey::svydesign(ids = ~v021,
               strata=~v022,
               weights = ~v005,
               data=dhs2)%>%
  gtsummary::tbl_svysummary(by = "v139", include = c(v151))

```

**Comment by ddsjoberg** [comment]
hi @coreysparks ! thanks for the post! you'll need to add the `by=` variable to the `inlcude=` argument to get your code working. it's added by default in `tbl_summary()` but looks like i need to add it for `tbl_svysummary()` as well

``` r
library(gtsummary)

dhs<-haven::read_dta("https://github.com/coreysparks/data/blob/master/ZZIR62FL.DTA?raw=true")
dhs<-haven::zap_labels(dhs)
dhs$v005<- dhs$v005/1000000
dhs2<- select(dhs, v021, v022, v005, v139, v151)

names(dhs2)
#> [1] "v021" "v022" "v005" "v139" "v151"
library(dplyr); library(gtsummary)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
options(survey.lonely.psu = "adjust")
survey::svydesign(ids = ~v021,
                  strata=~v022,
                  weights = ~v005,
                  data=dhs2)%>%
  tbl_svysummary(by = "v139", include = c(v151, v139)) %>%
  as_kable() # convert to kable to display on github
```

| **Characteristic**    | **1**, N = 2,850 | **2**, N = 1,599 | **3**, N = 2,279 | **4**, N = 1,562 | **97**, N = 58 |
|:----------------------|:-----------------|:-----------------|:-----------------|:-----------------|:---------------|
| sex of household head |                  |                  |                  |                  |                |
| 1                     | 1,975 (69%)      | 1,180 (74%)      | 1,494 (66%)      | 1,162 (74%)      | 41 (72%)       |
| 2                     | 876 (31%)        | 418 (26%)        | 786 (34%)        | 400 (26%)        | 16 (28%)       |

<sup>Created on 2021-06-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by coreysparks** [comment]
Gotcha! Thanks for the swift reply!
