### ISSUE TITLE
Sort table by overall mean

### ISSUE THREAD

**Issue by xkcococo** [ddsjoberg/gtsummary#929]
Hi, I was wondering if it is possible to sort the variables by overall mean? All of the variables in my table are numeric.

Thanks in advance!

**Comment by ddsjoberg** [comment]
Hi @xkcococo ! Thanks for the post.

Can you please include an example of what you're looking for? Please if possible, use the trial dataset included in the package as your exams data.

**Comment by ddsjoberg** [comment]
Hey hey @xkcococo , I am going to close this issue for now. But please feel free to reopen the issue when you add your example as mentioned above.
