### ISSUE TITLE
Failure due to survey update

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#930]
From Thomas Lumley:

> You are listed as the maintainers of one or more of these CRAN packages
 "convey"       "grattan"      "gtsummary"    "hutils"       "iNZightPlots" "iNZightTools" "jstable"     
 "svyPVpack"    "tab"          "tableone"   

> With the forthcoming version 4.1 of the survey package your package has new check errors. I think all these errors are due to the new implementation of svyquantile()

> If you just want to make your package pass check with minimal effort, change "svyquantile" to "oldsvyquantile" if "oldsvyquantile" exists (or require version 4.1 of survey). However, the new implementation is better in a number of ways and you might want to use it instead.

> You can get the current development version of 'survey' from https://r-forge.r-project.org/R/?group_id=1788

**Comment by larmarange** [comment]
Do you want to use the old function until the release of survey and then switch to the new version with a certain requirement once survey 4.1 on CRAN

Alternatively we can check the version number of survey to adapt the code accordingly

**Comment by ddsjoberg** [comment]
I would be fine with either....I guess I have a preference to update to the new version when survey makes it's cran release.  What do you think?

**Comment by larmarange** [comment]
It would be cleaner on the long term

Joseph Larmarange

Le mar. 29 juin 2021 à 15:03, Daniel Sjoberg ***@***.***> a
écrit :

**Comment by ddsjoberg** [comment]
FYI Lumley said he plans to submit to CRAN in mid-July. The new survey version requires R 3.5, and our current min version is 3.4.
