### ISSUE TITLE
LDKEY=607 is too small for this problem

### ISSUE THREAD

**Issue by THIB20** [ddsjoberg/gtsummary#933]
Dear all,

when I use gtsummary, I get the following error message:

There was an error in 'add_p()/add_difference()' for variable 'lar', p-value omitted:
Error in stats::fisher.test(structure(c(4L, 4L, 2L, 2L, 4L, 2L, 4L, 4L, : FEXACT error 6.  LDKEY=608 is too small for this problem,
  (ii := key2[itp=808] = 32150630, ldstp=18240)
Try increasing the size of the workspace and possibly 'mult'

Apparently this affects some factor variables. has anybode had this before and can help? Any help is appreciated!

Thanks,
T

**Comment by ddsjoberg** [comment]
HI @THIB20 ! Thank you for the post!

A couple of things:
1. Please include a reproducible example with your post (i.e. code that I can run on my machine).
2. Please try to calculate the p-value outside of `add_p()` and report back whether it is calculable in `fisher.test()`.

**Comment by THIB20** [comment]
Dear @ddsjoberg ! Thank you for your prompt reply!

So I have a huge dataset and I would need some time to create a representative example.

In the meantime I ran fisher.test(), and was able to solve the problem by increasind the workspace (from 200,000 to 20,000,000). Is there a way to incorporate this in the gtsummary call?

**Comment by ddsjoberg** [comment]
Great! Glad it was solved!

I can't integrate those kinds of solutions. Essentially, I am just running the Fisher exact test and reporting the results. If the Fisher test doesn't run, I just return the error as a message to the user.
