### ISSUE TITLE
Allow modification of reference row marker in `tbl_regression`

### ISSUE THREAD

**Issue by maia-sh** [ddsjoberg/gtsummary#942]
Thank you again for this time-saving package!

It would be great to have finer-grained control of the reference  row marker in `tbl_regression`.

Currently the `add_estimate_to_reference_rows` argument replaces the em-dash with OR = 1.00. It would also be great to be able to specify the term, e.g. "1 (Ref)" or "Reference".

``` r
library(dplyr)
library(gtsummary)

glm(response ~ age + trt, trial, family = binomial(link = "logit")) %>%
  tbl_regression(
    exponentiate = TRUE,
    add_estimate_to_reference_rows = TRUE
  ) %>% 
  as_kable()
```

| **Characteristic**     | **OR** | **95% CI** | **p-value** |
|:-----------------------|:-------|:-----------|:------------|
| Age                    | 1.02   | 1.00, 1.04 | 0.095       |
| Chemotherapy Treatment |        |            |             |
| Drug A                 | 1.00   |            |             |
| Drug B                 | 1.13   | 0.60, 2.13 | 0.7         |

<sup>Created on 2021-07-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by ddsjoberg** [comment]
Hello, and thanks for the post! Delighted to hear the package is useful for you.

Here is an example on how to update the reference row to display anything you'd like.

``` r
library(gtsummary)
#> #BlackLivesMatter
packageVersion("gtsummary")
#> [1] '1.4.1'

tbl <-
  glm(response ~ age + trt, trial, family = binomial(link = "logit")) %>%
  tbl_regression(
    exponentiate = TRUE
  ) %>%
  # update the ref row to with 'Reference'
  modify_table_styling(
    column = estimate,
    reference_row %in% TRUE,
    missing_symbol = "Reference"
  ) 
```
![image](https://user-images.githubusercontent.com/26774684/125951345-74f3b5aa-5862-471e-b97a-f1db57cb02ce.png)

<sup>Created on 2021-07-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by ddsjoberg** [comment]
I am going to go ahead close this issue, but please feel free to re-open if needed!
