### ISSUE TITLE
add a new column for p.values of glm

### ISSUE THREAD

**Issue by xkcococo** [ddsjoberg/gtsummary#944]
Hi, 

I am trying to use this function in my research. I created a table like this one
![image](https://user-images.githubusercontent.com/43758155/125973721-cad344ed-3fa9-48e7-a131-bf275fa62297.png)
I was wondering if it can be added a column next to the p-values. The column is p.values from glm statistics by controlling covariates.

Thanks!

**Comment by ddsjoberg** [comment]
Sure, you can merge in the p-values using `tbl_merge()`. 

```r
library(gtsummary)

tbl1 <-
  trial %>%
  select(age, grade, trt) %>%
  tbl_summary(by = trt, missing = "no") %>%
  add_p()

tbl2 <-
  trial %>%
  select(age, grade, marker, trt) %>%
  mutate(trt = factor(trt)) %>%
  tbl_uvregression(
    y = trt,
    method = glm,
    method.args = list(family = binomial),
    # adjust all models for marker level
    formula = "{y} ~ {x} + marker"
  ) %>%
  add_global_p() %>%
  # hide all columns, except p-value
  modify_column_hide(-p.value) %>%
  # add header to p.value
  modify_header(p.value ~ "**Adjusted p-value**") %>%
  modify_footnote(p.value ~ "Logistic regression adjusted for marker level")

tbl_merge(list(tbl1, tbl2)) %>%
  modify_spanning_header(everything() ~ NA)
```
![image](https://user-images.githubusercontent.com/26774684/125987733-52123903-d92a-4163-b40c-a2c3145d0ef9.png)


FYI, the best place to ask questions about how to use gtsummary is stackoverflow.com. Use the gtsummary tag and the package authors will be notified of your post.

**Comment by ddsjoberg** [comment]
I am going to go ahead close this issue, but please feel free to re-open if needed!

**Comment by xkcococo** [comment]
@ddsjoberg  Thank you very much!!

I have another questions want to ask. If I also want to apply FDR correction to these two columns of p.value, how could I apply it?

Thanks in advance!

**Comment by ddsjoberg** [comment]
Use the `add_q()` function before you merge the tables.

**Comment by ddsjoberg** [comment]
FYI, @xkcococo , I am happy to answer questions about how to use gtsummary. The best place to ask questions about gtsummary is on stackoverflow.com. Use the gtsummary tag, and the gtsummary authors and I will be notified of the post. Use GitHub Issues to  report bugs. Thanks!

**Comment by xkcococo** [comment]
@ddsjoberg Thank you very much! I will use it for further questions!
