### ISSUE TITLE
Summary of a dataset by a continous variable

### ISSUE THREAD

**Issue by kwakuduahc1** [ddsjoberg/gtsummary#945]
This package is a very important one. However, I think there is a missing feature. Do forgive me if I do not know where to find it. I want to summary some variables by a continuous variable.  Currently, the tbl_summary function would treat that variable as a categorical variable which is not the desired output.

Output by tbl_summary
![image](https://user-images.githubusercontent.com/11381582/125990017-c663dbdd-94ee-4aae-a9cf-b3cf4a5f4121.png)

Expected output
The finalfit package has a similar function to the tbl_summary. It produces the desired output
![image](https://user-images.githubusercontent.com/11381582/125990085-51ae93bc-c479-4122-9dc6-87f81763afd9.png)

I think the addition of that would make the package a complete one. Do forgive me if the feature is available but I have not found it. I have been searching for 2 days now.

**Comment by ddsjoberg** [comment]
hello @kwakuduahc1 ! thank you for the post

we're working on this, but it's not yet ready for incorporation in gtsummary. you can take a look here http://www.danieldsjoberg.com/bstfun/reference/tbl_2way_summary.html

FYI, I am on a development break at the moment, so there is no timeline for when this will be implemented fully

**Comment by ddsjoberg** [comment]
hey @kwakuduahc1 ! i am going to go ahead and close this issue....the function will migrated to gtsummary eventually and made better than the current bstfun implementation!

**Comment by kwakuduahc1** [comment]
Hello @ddsjoberg , thank you for your response. I hope to see this feature soon. My R skills are intermediary and hopefully I can help one day. 

See you.
