### ISSUE TITLE
Creating a summary table of yes/nos for multiple questions

### ISSUE THREAD

**Issue by dieuv0** [ddsjoberg/gtsummary#946]
Hi there! 

I have a data frame that has 6 columns, each representing a yes/no survey question.

I would like to create a summary table with each of these questions listed in the rows, and counts of "Yes/No/Missing" in the columns. Is that possible with this package? 

Thanks!

**Comment by ddsjoberg** [comment]
@dieuv0 if you have questions about how to use the package, first consult the help files, the package website/documentation including the vignettes (http://www.danieldsjoberg.com/gtsummary/). if you have further questions, ask on stackoverflow.com and use the gtsummary tag.
