### ISSUE TITLE
Feature request: as_flex_table method for "gt_tbl" objects

### ISSUE THREAD

**Issue by bwiernik** [ddsjoberg/gtsummary#949]
**Is your feature request related to a problem? Please describe.**
I like to use *gt* to create tables, as it has the most intuitive interface of the various tabling packages in my experience, especially in terms of teaching students. As *gtsummary* already has an `as_flex_table()` function for converting `"gtsummary"` objects to `"flextable"` objects, I wonder if it make a generic form compatible with `"gt_tbl"` objects to facilitate *gt* output to Word.

**Describe the solution you'd like**
Convert `as_flex_table()` to a generic with `.gtsummary` and `gt_tbl` methods.

**Describe alternatives you've considered**
The other alternative would be to work directly with *flextable*, but I would really like to be able to use the *gt* API with HTML and Word output.

**Comment by ddsjoberg** [comment]
hello @bwiernik !! Thank you for the post. 

I like the idea, but I think that kind of functionality is out of scope for the gtsummary package. A gtsummary object is quite simple compared to flextable and gt, making it relatively easy to convert a gtsummary table to either gt or flextable.  Conversely, converting between gt and flextable would be a huge undertaking.

I assume you'd like the functionality so you can take advantage of the Word output in flextable? Recently, the RTF (Word compatible) output for gt tables has made big strides. While still being developed, most gt tables exported to RTF render beautifully.

**Comment by ddsjoberg** [comment]
hey hey @bwiernik ! I am going to close this issue. But if you start of the conversion method, please ping me! I'd love to see it develop!

**Comment by bwiernik** [comment]
Apparently gt has an in-progress `as_word()` function
