### ISSUE TITLE
Feature request: How to add R square for linear regression model

### ISSUE THREAD

**Issue by ShixiangWang** [ddsjoberg/gtsummary#950]
Hi, I want to add R suare to the table but cannot find any description in vignette. How can I do this?

```
library(gtsummary)

tbl_regression(lm(mpg ~ cyl + hp + wt + gear, data = mtcars)) |> 
  bold_labels() |> 
  bold_p()
```

![image](https://user-images.githubusercontent.com/25057508/126770783-47a7412e-1a2d-477d-bc0a-55e8d18b02b7.png)

**Comment by ddsjoberg** [comment]
Hello @ShixiangWang ! Have you reviewed the `add_glance_*()` functions? They can help add the R2.

**Comment by ShixiangWang** [comment]
@ddsjoberg Thanks, I will take a look.

**Comment by ShixiangWang** [comment]
That's great, thanks :)

```
library(gtsummary)

tbl_regression(lm(mpg ~ cyl + hp + wt + gear, data = mtcars)) |> 
  bold_labels() |> 
  bold_p() |> 
  add_glance_table(
    label = list(sigma ~ "\U03C3"),
    include = c(r.squared, AIC, sigma)
  )

```

![image](https://user-images.githubusercontent.com/25057508/126777449-d9ad69fa-6dce-4eef-85df-2d634761bed3.png)
