### ISSUE TITLE
workspace problem in Fisher exact test

### ISSUE THREAD

**Issue by chrisleitzinger** [ddsjoberg/gtsummary#952]
Hi,
I am using the `tbl_summary()` function and adding `add_p` to get the p value but I get this error message:

![Screenshot2021_07_30_175705](https://user-images.githubusercontent.com/55062754/127715529-713a9324-330e-4657-b808-de85fdc45e4a.jpg)

Here a quick reprex

```r
df <- data_frame(type = rep(c("A", "A", "A", "A", "B", "C", "C"), 100),
              treatment = c(
                rep(c("v", "x", "x", "y", "z"), 2),
                rep(c("z", "z", "x", "y", "x"), 2),
                rep(c("w", "x", "x", "y", "z"), 136)
                ))
df %>% 
tbl_summary(by = type) %>% add_p()
```
If I try using the `fisher.test` function and increasing the workspace I can get a p val but not if I try to increase it in `tbl_summary`

```r
fisher.test(df$type, df$treatment, workspace=2e9)
```
![Screenshot2021_07_30_180109](https://user-images.githubusercontent.com/55062754/127715824-1b6a343b-d104-4d97-ad27-4b8969eb1673.jpg)

I tried to include `workspace=2e9` or other `simulate.p.value = TRUE, B = 1e5` 

```r
df %>% 
  tbl_summary(by = type) %>% add_p(workspace=2e9)
```
but nothing seems to work.

Thanks!

**Comment by ddsjoberg** [comment]
Hello @chrisleitzinger ! Thanks for the post.

You'll need to use the test.args argument to pass the argument directly to to the Fisher test. Let me know if you need more guidence passing the argument! (I am not at a computer at the moment, or I'd give more details)

**Comment by ddsjoberg** [comment]
hey hey @chrisleitzinger try passing the argument like this
```r
tbl_summary(by = type) %>% add_p(test.args = all_tests("fisher.test") ~ list(workspace=2e9))
```

**Comment by ddsjoberg** [comment]
@chrisleitzinger i am going to go ahead and close this issue. Please feel to reach out if you have more questions. I am happy to answer questions about how to use gtsummary. The best place to ask questions about gtsummary is on stackoverflow.com. Use the gtsummary tag, and the gtsummary authors and I will be notified of the post. Use GitHub Issues to report bugs. Thanks!

**Comment by chrisleitzinger** [comment]
@ddsjoberg Thank you very much! It works perfectly!
