### ISSUE TITLE
Feature request: Footnote citation at each variable

### ISSUE THREAD

**Issue by ABorakati** [ddsjoberg/gtsummary#955]
Hi,

First of all, I'd like to say thanks on making such a great package, by far the slickest and most customisable table making package on r,

At the moment footnotes are shown with a single superscript citation at the column headers, even when there are multiple tests/ statistics described by a single footnote e.g:
![image](https://user-images.githubusercontent.com/41518783/128637217-5cbb1da7-ed65-489a-8897-e67b271dce1c.png)

both Wilcoxon and chi-squared tests are represented by the superscript 2,

What I would like is a different superscript for each test e.g. 2 for Wilcoxon and 3 for chi-squared and those superscripts to be on the respective p-values calculated using those tests e.g. '2' on 0.7 and '3' on 0.9 in the above example.

It might be obvious which is which in this example, but when you are using, say, both t-test and Wilcoxon tests for different continuous variables in a single table, it might be hard to distinguish which test was used for each one,

Thanks a lot

**Comment by ddsjoberg** [comment]
Hello @ABorakati ! Thanks for the post!

I think this function will do exactly what you're after. http://www.danieldsjoberg.com/bstfun/reference/gts_add_p_footnotes.html

Let us know!

**Comment by ABorakati** [comment]
> Hello @ABorakati ! Thanks for the post!
> 
> I think this function will do exactly what you're after. http://www.danieldsjoberg.com/bstfun/reference/gts_add_p_footnotes.html
> 
> Let us know!


Thanks! Exactly what I was looking for, please include in the main package!

**Comment by ddsjoberg** [comment]
It'll get there eventually 😜 We use bstfun as a proving ground for new functions.

**Comment by ddsjoberg** [comment]
@ABorakati if you have suggestions for the name of the function when it's migrated to gtsummary, please share them here.
