### ISSUE TITLE
p values for ordinal logistic regression using `MASS::polr()` and `gtsummary::tbl_regression()`

### ISSUE THREAD

**Issue by coeus-analytics** [ddsjoberg/gtsummary#958]
Hi @ddsjoberg,

I think I may have identified another feature for `gtsummary` - let me know if I'm wrong. This is for `MASS::polr()` and the `gtsummary::tbl_regression()` functions. 

I am trying to add p values for an ordinal logistic regression univariate model. It seems to work for imputed data sets but not for the original.

Is it possible to have p values shown for `tbl_regression()` when a `polr` is used?

Thanks!

<hr>

**Ordinal logistic regression with original data**

The below results in **no p value** in the `gtsummary` table - even if I add `add_p()`.

```
# packages
library(gtsummary)
library(dplyr)
library(MASS)

# example data for ordinal logistic regression
df <- foreign::read.dta("https://stats.idre.ucla.edu/stat/data/ologit.dta") %>% 
  mutate(public = ifelse(public == 1, "Public", "Private"))

# run model
mod1 <- polr(data = df, formula = apply ~ public, Hess = TRUE)

# shows OR and 95% CI but no p value
tbl_regression(mod1,
               exponentiate = TRUE)
```

**Ordinal logistic regression with imputed data**

The below results in a table **with a p value** in the `gtsummary` table.

```
# insert random NA values
df2 <- df %>% 
  mutate(public = ifelse(row_number() %in% sample(1:nrow(.), 20), NA, public))

# quick multiple imputations
df2_imp <- mice(df2, m = 5)
df2_imp_long <- mice::complete(df2_imp, action = "long", include = TRUE)

# pooled estimates appear to provide p values
as.mids(df2_imp_long) %>% 
  with(polr(data = df, formula = apply ~ public, Hess = TRUE)) %>% 
  tbl_regression(.,
                 exponentiate = TRUE) 
```

**Comment by ddsjoberg** [comment]
For some reason, the tidier from polr objects does not include the p-values by default. The `tbl_regression()` function uses the tidiers in the background to perform the initial cleaning up of the model results. To get the p-values from the polr tidier, you need to specify the `broom::tidy(p.values = TRUE)` argument. Below is an example how to pass the custom tidier to `tbl_regression()` to get the p-values in your table!

The mice tidier, conversely, includes p-values by default (like most other tidiers). 

``` r
library(gtsummary)
library(dplyr)
library(MASS)

# example data for ordinal logistic regression
df <- 
  foreign::read.dta("https://stats.idre.ucla.edu/stat/data/ologit.dta") %>% 
  mutate(public = ifelse(public == 1, "Public", "Private"))

# run model
mod1 <- polr(data = df, formula = apply ~ public, Hess = TRUE)

broom::tidy(mod1, p.values = TRUE)
#> # A tibble: 3 x 6
#>   term                        estimate std.error statistic p.value coef.type  
#>   <chr>                          <dbl>     <dbl>     <dbl>   <dbl> <chr>      
#> 1 publicPublic                   0.183     0.284     0.646   0.520 coefficient
#> 2 unlikely|somewhat likely       0.225     0.108     2.09   NA     scale      
#> 3 somewhat likely|very likely    2.22      0.172    12.9    NA     scale

# shows OR and 95% CI but no p value
tbl_regression(
  mod1, 
  exponentiate = TRUE,
  tidy_fun = function(x, ...) broom::tidy(x, ..., p.values = TRUE)
) %>%
  as_kable() # converting with kable so table will render on GitHub
#> Warning: The `x` argument of `as_tibble.matrix()` must have unique column names if `.name_repair` is omitted as of tibble 2.0.0.
#> Using compatibility `.name_repair`.
```

| **Characteristic** | **OR** | **95% CI** | **p-value** |
|:-------------------|:-------|:-----------|:------------|
| public             |        |            |             |
| Private            |        |            |             |
| Public             | 1.20   | 0.68, 2.09 | 0.5         |

<sup>Created on 2021-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by coeus-analytics** [comment]
Wow, simple as that!

Thanks @ddsjoberg. I'll use that instead.

**Comment by coeus-analytics** [comment]
@ddsjoberg, I might have spoken too soon. Not going to reopen the issue as this likely is due to the limitation of the `broom` tidier. p values aren't produced for polr model if the categorical variable has more than two levels.

Comment for reference.

``` r
library(gtsummary)
library(dplyr)
library(MASS)

# example data for ordinal logistic regression
df <- 
  foreign::read.dta("https://stats.idre.ucla.edu/stat/data/ologit.dta") %>% 
  mutate(public = sample(c("Public", "Private", "Other"), n(), replace = TRUE))

# run model
mod1 <- polr(data = df, formula = apply ~ public, Hess = TRUE)

# shows OR and 95% CI but no p value
tbl_regression(
  mod1, 
  exponentiate = TRUE,
  tidy_fun = function(x, ...) broom::tidy(x, ..., p.values = TRUE)
) %>%
  as_kable()
#> p-values can presently only be returned for models that contain 
#>               no categorical variables with more than two levels
```

| **Characteristic** | **OR** | **95% CI** | **p-value** |
| :----------------- | :----- | :--------- | :---------- |
| public             |        |            |             |
| Other              |        |            |             |
| Private            | 0.82   | 0.51, 1.32 |             |
| Public             | 1.03   | 0.65, 1.62 |             |

<sup>Created on 2021-08-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by larmarange** [comment]
Maybe you can try `ordinal::clm()` which offers more options for ordinal logistic regression. If I remember correctly, it does compute p-values for all terms.

**Comment by coeus-analytics** [comment]
@larmarange , good one. Tried it out and seems to play well with `tbl_regression`. It does calculate p values and renders it via gtsummary. Code below with p value comparisons too.

Thanks all. May comment further if I stumble across anything else.

<hr> 

``` r
library(gtsummary)
library(tibble)
library(dplyr)
library(MASS)
library(ordinal)

# example data for ordinal logistic regression
df <- 
  foreign::read.dta("https://stats.idre.ucla.edu/stat/data/ologit.dta") %>% 
  mutate(public = sample(c("Public", "Private", "Other"), n(), replace = TRUE))

# run model using MASS::polr
mod1 <- polr(data = df, formula = apply ~ public, Hess = TRUE)

# just calculate p values for comparison
ctable <- coef(summary(mod1))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
enframe(p) %>% knitr::kable()
```

| name                        |     value |
| :-------------------------- | --------: |
| publicPrivate               | 0.4858300 |
| publicPublic                | 0.0310871 |
| unlikely|somewhat likely    | 0.9208815 |
| somewhat likely|very likely | 0.0000000 |

``` r

# run model using ordinal::clm
mod2 <- ordinal::clm(data = df, formula = apply ~ public)

# tbl_regression for mod2
tbl_regression(
  mod2, 
  exponentiate = TRUE,
  tidy_fun = function(x, ...) broom::tidy(x, ..., p.values = TRUE)
) %>%
  as_kable()
```

| **Characteristic** | **OR** | **95% CI** | **p-value** |
| :----------------- | :----- | :--------- | :---------- |
| public             |        |            |             |
| Other              |        |            |             |
| Private            | 0.85   | 0.54, 1.34 | 0.5         |
| Public             | 0.59   | 0.37, 0.95 | 0.031       |

<sup>Created on 2021-08-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
