### ISSUE TITLE
Bug Report: html_notebook UTF-8 Characters show incorrectly

### ISSUE THREAD

**Issue by polc1410** [ddsjoberg/gtsummary#963]
If a gtsummary table has utf-8 characters in the table, when viewed as an html notebook these tables show incorrect characters,  If the identical code is run outside of the notebook - the tables render correctly

Here is an example notebook
`
---
title: "Results Section"
output: html_notebook
---
    
## R Reprex for UTF-8 testing

```{r}
require(gtsummary)

testData <- data.frame ( "Dose (mg/m²)" = 1:10, Result = as.factor( rep(c("A", "B"), 5)))
glm( Result ~ `Dose..mg.m².`, data = testData, family = "binomial") %>%
    tbl_regression()
```

`
![table - errors](https://user-images.githubusercontent.com/1819213/129777114-fe758674-7dab-49f0-a59f-559b58bc22a2.png)

If the code chunk:

```r
require(gtsummary)

testData <- data.frame ( "Dose (mg/m²)" = 1:10, Result = as.factor( rep(c("A", "B"), 5)))
glm( Result ~ `Dose..mg.m².`, data = testData, family = "binomial") %>%
    tbl_regression()

```
Is run without using the notebook, the table renders correctly (see attached pictures)
![table-noerros](https://user-images.githubusercontent.com/1819213/129777187-939fa287-92bd-448d-8266-4ad5fcb3b5c5.png)

**Comment by ddsjoberg** [comment]
hello @polc1410 ! thank you for the post!

I think this issue report would best be posted to the gt package's github page https://github.com/rstudio/gt . The gtsummary package uses gt to print the summary tables.
