### ISSUE TITLE
Add a `add_ci.tbl_svysummary()` function

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#965]
Use `survey::svyciprop()` to calculate CIs

**Comment by trevinoj** [comment]
Hello, I look forward to the release of this new function.  For whatever it's worth, it would be great to have this function include an option to generate confidence intervals for proportions or point estimates.

Here are example tables of I created to depict confidence intervals of the: 

**proportion estimate** (i.e., using survey::svby with function svyciprop), and
![gtsummary table with CI proportions](https://user-images.githubusercontent.com/8698756/144785807-cd9e9df0-134e-400b-b9da-1bea65fed23e.jpg)

**point estimate** (i.e., using survey::svby with function svytotal
![gtsummary table with CI point estimates](https://user-images.githubusercontent.com/8698756/144785923-4e20fbae-42c7-4e14-9655-e7ebd0687b47.jpg)
)

**Comment by aspina7** [comment]
hey @ddsjoberg - hope all good; just wondering if you have an estimated timeline for when might be able to implement this? 
We are migrating the above project to use {gtsummary} - might have some funding available if it helps (as above we considered writing minor wrappers in the meantime, but probably more efficient if we could just help push the package forward directly) 
Might not be helpful but as aside there is some code [here](https://github.com/R4EPI/epitabulate/blob/master/R/tabulate_survey.R) for a tidy style wrapper using {srvyr} (which itself is a wrapper of {survey}... 
Happy to jump on a call some time if easier!

**Comment by ddsjoberg** [comment]
hello @trevinoj and @aspina7 ,

I don't have at timeline for this function. Perhaps I can find someone at my institutions next hackathon in April who would be interested in developing.

If either of you would like to implement, please be sure to model the function after `add_ci.tbl_summary()`: perhaps, the two functions have be entirely integrated. Please know if advance, I may not have time in the next couple of months to review a pull request.

**Comment by aspina7** [comment]
thanks @ddsjoberg - no worries, in that case we might just work on a wrapper over on our repo for the meantime and then touch base with you in april to see about helping out with `add_ci.tbl_summary()` or starting a pr for review when you have more time. 
@amygimma fyi

**Comment by ddsjoberg** [comment]
@trevinoj @aspina7 did you ever write wrappers for this type of functionality? If so, can you link to it? If not, would you be able to provide the following minimal code examples? It will be helpful when implementing.
1. Code for calculating the CI for a continuous variable's mean
1. Code for calculating the CI for a continuous variable's mean when there is `tbl_svysummary(by=)` present

If you can use the example data set from the `tbl_svysummary()` help file, that would be easiest for me to review. Also, please keep the example as minimal as possible

**Comment by aspina7** [comment]
hi @ddsjoberg sorry for delay in replying - piled under books again. Haven't managed getting a functioning wrapper going, but see minimal examples below. 
This [wrapper](https://github.com/gergness/srvyr/blob/main/R/survey_statistics_helpers.R#L53) used in the {[srvyr](https://github.com/gergness/srvyr/blob/main/R/survey_statistics.r)} functions does a lot of heavy lifting for calculating confidence intervals. Having all those params in {gtsummary} would be awesome. 

You already know this but doing props with CI for categorical vars is a bit of a pain in {survey} - and not entirely sure that {srvyr} has a solution for it either... see notes [here](https://github.com/R4EPI/epitabulate/blob/master/R/tabulate_survey.R#L57)

See reprex below for CIs with means comparing {survey} and {srvyr}. 

``` r
library(survey)
library(srvyr)

# A dataset with a complex design
data(api, package = "survey")

## create a {survey} design object
surveyobj <- survey::svydesign(id = ~dnum, weights = ~pw, data = apiclus1, fpc = ~fpc)

## create a {srvyr} design object
srvyrobj  <- apiclus1 %>% 
  srvyr::as_survey_design(id = dnum, weights = pw, fpc = fpc) 

######## CI and design effect for a continuous vars mean 

## calculate the mean academic performance index (and design effect)

# using {survey}
stat <- svymean(~api00, surveyobj, na.rm = TRUE, deff = TRUE) 
stats::confint(stat, level = 0.95)
#>          2.5 %   97.5 %
#> api00 598.0275 690.3113
deff(stat)
#>    api00 
#> 9.345869

# using {srvyr}
srvyrobj %>% 
  summarise(
    srvyr::survey_mean(api00, vartype = "ci", deff = TRUE))
#> # A tibble: 1 x 4
#>    coef `_low` `_upp` `_deff`
#>   <dbl>  <dbl>  <dbl>   <dbl>
#> 1  644.   594.   695.    9.35

######## Stratified CI and design effect for a continuous vars mean 

stat <- svyby(~api00, ~stype, surveyobj, svymean, deff = TRUE)
stats::confint(stat, level = 0.95)
#>      2.5 %   97.5 %
#> E 605.0385 692.6976
#> H 544.0531 693.0897
#> M 569.4866 693.3934
deff(stat)
#> [1] 6.583674 2.228259 2.163900

srvyrobj %>% 
  group_by(stype) %>% 
  summarise(
    srvyr::survey_mean(api00, vartype = "ci", deff = TRUE)
  )
#> # A tibble: 3 x 5
#>   stype  coef `_low` `_upp` `_deff`
#>   <fct> <dbl>  <dbl>  <dbl>   <dbl>
#> 1 E      649.   601.   697.    6.58
#> 2 H      619.   537.   700.    2.23
#> 3 M      631.   564.   699.    2.16
```

<sup>Created on 2022-04-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
Thanks @aspina7 . I'm just looking at the code on my phone at the moment, but do you have code to calculate the CIs using survey pkg? We dont use svry internally and I don't want to add another dependency for the CIs. Thanks!

**Comment by aspina7** [comment]
yep - the above shows both {survey} and {srvyr}. The {survey} examples are the best I can muster without going in to some very dense iteration. 
If you take a look at the {srvyr} wrapper I linked to though it uses {survey} functions.

**Comment by aspina7** [comment]
yeap exactly - the binary bit is the real pain. 

below is an example of a very hideously outdated basic function used for a tutorial a while back 

```r
# Function used to calculate weighted proportions, CI and design effect
svy_prop <- function(x, design) {
p1 <- round(svyciprop(as.formula(paste0( "~" , x)), design, na.rm = T) * 100, digits = 2)
p2 <- round(confint(p1) * 100, digits = 2)
p3 <- deff(round(svymean(as.formula(paste0( "~" , x)), design, na.rm = T, deff = T) * 100, digits = 2))
p4 <- cbind("Proportion" = p1, p2, "Design effect" = p3)
}

# Function used to calculate weighted proportions, CI and design effect for categorical variables
svy_prop_cat <- function(x, dataset, designids, designweight, designstrata){
  
  #create a list to save outputs in 
  
  outer <- list() 
  
  #change each of the variables of interest to factor
  dataset[,x] <- as.factor(dataset[,x])
  
  #For each level of the categorical variable of interest
  for (i in levels(dataset[,x])){
    
    #create a new binary variable called var temp for each level
    dataset[,paste0(x, "temp")] <- ifelse(dataset[,x] == i, 1, 0)
    
    #define your design
    design <- svydesign(ids = as.formula(paste0("~",designids)), 
                        weights = as.formula(paste0("~",designweight)), 
                        strata = as.formula(paste0("~",designstrata)), 
                        data = dataset)
    
    #use the svy_prop function on binary variable
    overall <- svy_prop(paste0(var ,"temp"), design = design)
    
    #label the rows of your output with the variable and category level
    rownames(overall) <- paste0(var,": ", i)
    
    #save within the list 
    outer[[var]][[i]] <- overall
  }
  
  #bind the output from the list in to a dataframe
  do.call(rbind, outer[[1]][1:length(outer[[1]])])
} 

```

**Comment by szimmer** [comment]
Moving discussion from #1187 here. Yes, agreed this goes into add_ci - the difference in svyciprop is whether the interval is calculated on the log transform, the Wald approximation, and some other options but the SE is the same. I have some time to look at this and will look at add_ci as it currently stands as well as svyciprop and confint (for CI of means). 

Another opinionated piece is the degrees of freedom - I don't agree with the defaults of the survey package (Infinity) but we need to stick with them and add option of the better option which uses the degf function.

**Comment by larmarange** [comment]
I agree that it is better to follow the defaults of the `survey` package (otherwise users get lost) and to add an option to change the behaviour.

**Comment by larmarange** [comment]
Sorry. This issue has been opened for more than a year now.

I just drafted a PR implemented support for proportions, means and medians CIs with `tbl_svysummary()`

You can have a look at it: #1402

**Comment by fBedecarrats** [comment]
> Sorry. This issue has been opened for more than a year now.
> 
> I just drafted a PR implemented support for proportions, means and medians CIs with `tbl_svysummary()`
> 
> You can have a look at it: #1402

This is great! I'll make some tests by the beginning of next week. Many thanks. From where I sit, that was very fast.

**Comment by fBedecarrats** [comment]
I am testing with the survey data I am analysing (which I am not allowed to share) and it works great! I'm still struggling with the add_ci() funciton to correctly format the output, asthe syntax for the number of decimal digits to display seems quite different from the tb_summary/tb_svysummary(), but it is a different topic. 
MANY thanks @larmarange for the update!
