### ISSUE TITLE
Feature request: SMD for categorical variables 

### ISSUE THREAD

**Issue by roman2023** [ddsjoberg/gtsummary#966]
Need feature to implement SMD for categorical variables.

At present add_difference (list (all_continous()~ "cohens_d")) works well for continuous variables. 

However, this is not yet available for categorical variables. 

An example of how this is implemented in SAS can be found in the link here: 
https://support.sas.com/resources/papers/proceedings12/335-2012.pdf

This would be extremely helpful to complete the summary tables as many of the variables are categorical in life sciences.

**Comment by ddsjoberg** [comment]
Thank you @roman2023 for posting the issue! This is not something I use in my work. I think we can find a good-hearted user to implement this for us some time.

To implement:
1. Use the `.$meta_data$df_stats` to calculate the SMD as it already has the group probabilities saved in that tibble.
2. The SAS link above has a clear description of the calculation
3. Model function after those found in https://github.com/ddsjoberg/gtsummary/blob/master/R/utils-add_p_tests.R
4. The documentation in `tests.R` will need to be updated to include SMD, including the internal data frame listing all tests and pseudo-code.

**Comment by ddsjoberg** [comment]
@roman2023 I implemented the methods as outlined in the SAS document you provided (https://github.com/ddsjoberg/gtsummary/pull/970).

I checked my results against the smd and tableone packages, and for categorical variables the SMD estimate are slightly different. Are you familiar with these methods? Are you able to investigate?
