### ISSUE TITLE
Bug Report: tbl_summary throws error when grouping and data contains a factor filled with NAs

### ISSUE THREAD

**Issue by erikvona** [ddsjoberg/gtsummary#977]
I'm using tbl_summary programmatically.
If I have a table with a factor variable and all values happen to be NA, an error occurs:

Reprex:

```r
library(gtsummary)
trial2 <- trial %>% select(trt, age, grade)
trial2$has_banana <- factor(NA) # We don't know which patients have a banana
trial2 %>% tbl_summary(by = trt) # Error :(
```

> Error: Problem with `mutate()` column `tbl_stats`.
i `tbl_stats = pmap(...)`.
x Can't subset columns that don't exist.
x Columns `stat_1` and `stat_2` don't exist.

If the factor has levels, `tbl_summary` works, but `add_p` fails:

```r
library(gtsummary)
trial3 <- trial %>% select(trt, age, grade)
trial3$has_banana <- factor(NA, levels = c("Yes", "No")) # We don't know which patients have a banana
trial3 %>% tbl_summary(by = trt) %>% add_p() # Error :(
```

> Error: Problem with `mutate()` column `test`.
i `test = map2(...)`.
x missing value where TRUE/FALSE needed

(I tend to run a `fct_drop` across all factors so mine don't have levels, but it would be nice if both could get fixed so tbl_summary and add_p could produce valid output for any factor).

**Comment by ddsjoberg** [comment]
Thank you @erikvona for reporting the bug! I am surprised this hasn't been addressed previously. We'll ensure this fix makes it into the next release

**Comment by ddsjoberg** [comment]
@erikvona 

The issue here is that the factor variable has no levels, FYI. If there is a level, the function doesn't return an error.
```r
trial %>% 
  dplyr::mutate(
    has_banana = factor(NA, levels = "level") # We don't know which patients have a banana
  ) %>% 
  tbl_summary(by = trt, include = has_banana)
```
![image](https://user-images.githubusercontent.com/26774684/133776535-ed64399e-e768-4136-a046-3c335de68930.png)

**Comment by erikvona** [comment]
@ddsjoberg  That's true, but if the factor has levels, `add_p()` still fails, see the second example. If desired I could split this in two reports, since they could be considered separate issues.

**Comment by ddsjoberg** [comment]
Thanks for adding the second example. I am surprised to see that the `fisher.test()` returns a p-value when all observations are missing! 😨 😨 😨 

```r
> with(df, table(has_banana, trt)) %>%
+   fisher.test()

	Fisher's Exact Test for Count Data

data:  .
p-value = 1
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
   0 Inf
sample estimates:
odds ratio 
         0 
```
