### ISSUE TITLE
Add robust SEs options for `tbl_regression()`

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#979]
https://stackoverflow.com/questions/69235739

Utilizing robust standard errors should be easier in gtsummary. The example in the SO link is good, except the jtools solution requires you to choose to export standard errors OR CIs (not both).

**Comment by larmarange** [comment]
Can you use https://easystats.github.io/parameters/reference/model_parameters.default.html to get robust errors?

**Comment by ddsjoberg** [comment]
> Can you use https://easystats.github.io/parameters/reference/model_parameters.default.html to get robust errors?

@larmarange that looks like it'll be perfect and fit much better with the workflow. thanks!
