### ISSUE TITLE
Document list-formula notation

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#981]
> discuss the opportunity of simplifying the syntax in `.formula_list_to_named_list()`, i.e. allowing to write `~ something` as a shortcut of `everything() ~ something`? @larmarange 

I"ve been thinking about updates to the syntax here as well. I like your suggestion. I would also like to accept a mix of formula and named element notation. For example, it would be helpful to be able to pass something like `statistic = list(all_categorical() ~ "{n}", age = "{mean}")`

**Comment by larmarange** [comment]
For information, you PR in broom.helpers has been merged: https://github.com/larmarange/broom.helpers/issues/121

Maybe it could be nice to have a short vignette in `gtsummary` presenting all allowed syntaxes? I have found this in the NEWS:

```r
tbl_summary(trial, label = age ~ "NEW LABEL"))
tbl_summary(trial, label = "age" ~ "NEW LABEL"))
tbl_summary(trial, label = c("age", "trt") ~ "NEW LABEL"))
tbl_summary(trial, label = c(age, trt) ~ "NEW LABEL"))
tbl_summary(trial, label = vars(age, trt) ~ "NEW LABEL"))
tbl_summary(trial, label = vars(everything(), -age, -trt) ~ "NEW LABEL"))

age_column = "age"
tbl_summary(trial, label = age_column ~ "NEW LABEL"))
tbl_summary(trial, label = vars(age_column) ~ "NEW LABEL")

purrr::map(c("trt", "grade"), ~tbl_summary(trial, by = .x))
```

Could be nice to extend it and add few explanations.

**Comment by ddsjoberg** [comment]
@larmarange any opinions on the best place to add this documentation? The tblsummaru vignette?

**Comment by larmarange** [comment]
As it is transversal to all tbl_* functions, maybe a dedicated short vignette?

**Comment by ddsjoberg** [comment]
A link to the help file was added to tbl_summary and tbl_svysummary
