### ISSUE TITLE
Add `tbl_custom_svysummary()` function

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#982]
@larmarange let's add this, but perhaps after we've had a bit more experience with `tbl_custom_summary()`?

**Comment by larmarange** [comment]
Agree. Let's develop and play with `tbl_custom_summary` before developing a survey version

**Comment by ddsjoberg** [comment]
hey hey hey @larmarange ! I am adding a GH Action to close stale issues, so I just assigned this one so it won't be auto-closed. No rush at all here.

**Comment by larmarange** [comment]
oh thanks. True that it still something to develop.

Not so much time right now but good to keep it open

**Comment by ddsjoberg** [comment]
Hey! Let's hold off on this for now. I may need to make some structural changes to the pkg to adhere to some guidelines within pharma (for the new job), which would affect this function's implementation.

**Comment by larmarange** [comment]
Sure. It could also part of the more global discussion about V2 of gtsummary

**Comment by ddsjoberg** [comment]
i think the functionality `tbl_custom_svysummary()` offers is encompassed in the ARD-framework and can be built with `tbl_ard_summary()`. We will bolster documentation for the ARD framework in the next quarter. WIth that in mind and also this issue has been opened for over three years, I am going to go ahead and close
