### ISSUE TITLE
Export also rename() from dplyr

### ISSUE THREAD

**Issue by discoleo** [ddsjoberg/gtsummary#988]
## Problem
Sometimes it is not practical to use the exact names for variables: the name is either too long, or it contains special characters, etc). Renaming the variables as the 'last" step before the summary becomes then necessary.

## Solution
Export also the rename() function from package dplyr.

*Note:*
The select function is already exported. Having both functions available removes the necessity to load explicitly dplyr and is quite convenient for end-users.

**Comment by ddsjoberg** [comment]
hello! I don't know if it is a particularly high need to export the re-export the `rename()` function. As a user, you can still utilize the function without loading the dplyr library with `dplyr::rename()`

**Comment by discoleo** [comment]
Hello!

## Convenience function
1. Side effects: as noted, loading a package may have sometimes unwanted side-effects (masking other functions, etc); it is still possible to use dplyr::rename(), but it is a little cumbersome;
2. Simple users: may not need to perform a lot of data manipulation; rename() would be just a convenience function;

## Data Labels vs rename vs attributes
This is a far more interesting debate.
- rename(): is much cleaner than FUN(label = "...");
- global attributes (for the data frame) are the better solution and exist in other software packages, but unfortunately not in R;

**Comment by ddsjoberg** [comment]
The gtsummary package already accepts the label attribute `attr(trial$age, "label"), that multiple packages add to columns in data frames. When the label attribute is present, it is used.

i don't see how `rename(Age = age, `Treatment` = trt)` is easier than `label = list(Age = age, `Treatment` = trt)`

**Comment by discoleo** [comment]
It is easier to copy across code-blocks:

**Block 1**
```
data %>%
   statistics1() %>%
   rename(Age = age, Treatment = trt) %>%
   ... # report 1
```

**Block 2**
```
data %>%
   statistics2() %>%
   rename(Age = age, Treatment = trt) %>%
   ... # report 2
```

**Comment by ddsjoberg** [comment]
Thank you @discoleo for the suggestion. Given users can easily access rename without gtsummary exporting the function, and there are plenty of workflows where no rename is needed, we'll continue to use it as it is
