### ISSUE TITLE
Split Table Header on 2 Rows

### ISSUE THREAD

**Issue by discoleo** [ddsjoberg/gtsummary#989]
## Problem
The header of tables presenting grouped summaries may become very wide, if the factor levels are complex names. Adding the block "N = {N}" further increases the width.

## Solution
Split the header using 2 rows:
- 1st row: the factor levels / the by-grouping;
- 2nd row: N = {N};

*Utility Function:*
- generate the appropriate code automatically (includes the ```"<br/>"``` tag):
```
update = list(
	all_stat_cols(FALSE) ~ "**{level}**<br/> N = {style_number(n)}",
	label ~ paste0("**", "Characteristic", "**")
)
```

**Comment by discoleo** [comment]
## Overall Column

```
header0 = list(
	stat_0 ~ "**Overall**<br/> N = {style_number(N)}"
)
header = list(
	all_stat_cols(FALSE) ~ "**{level}**<br/> N = {style_number(n)}",
	label ~ paste0("**", "Characteristic", "**")
)
# and now the summary
data %>%
tbl_summary(by = trt) %>%
	modify_header(update = header) %>%
	add_p() %>%
	add_overall() %>%
	modify_header(update = header0)
```

**Comment by ddsjoberg** [comment]
For this, we are waiting for the gt package to respect the `\n` linebreak notation that will be supported in all output types. The `<br>` will unfortunately only work for HTML tables. THe gt package has an open issue for this already.
